Repository mlflow/mlflow, pull requests merged in 2018-10, with the labels that each got.

#576 Fix regression in mlflow_create_experiment()
  mlflow/R/mlflow/R/tracking-fluent.R
  mlflow/R/mlflow/tests/testthat/test-tracking.R
Labels: R

#586 Don't require user to attach keras when predicting
  mlflow/R/mlflow/R/model-keras.R
  mlflow/R/mlflow/tests/testthat/test_keras_model.R
Labels: R

#587 Pin Keras version to 2.2.2 to fix tests
  test-requirements.txt
Labels: LGTM

#583 Make `databricks://profile-name` tracking URIs respect casing
  mlflow/tracking/utils.py
  tests/tracking/test_utils.py
Labels: LGTM, bug-fix

#582 Make errors from RestStore more descriptive.
  mlflow/exceptions.py
  mlflow/server/handlers.py
  mlflow/store/rest_store.py
  mlflow/utils/validation.py
  tests/server/test_handlers.py
  tests/test_exceptions.py
Labels: bug-fix

#594 Disable CRAN install while r is published to CRAN
  docs/source/quickstart.rst
  docs/source/tutorial.rst
  mlflow/R/mlflow/README.Rmd
  mlflow/R/mlflow/README.md
Labels: R, docs

#580 Bump versions from 0.7.0 -> 0.7.1 in the Python, Java, and R packages
  mlflow/R/mlflow/DESCRIPTION
  mlflow/java/client/pom.xml
  mlflow/java/pom.xml
  mlflow/java/scoring/pom.xml
  mlflow/version.py
Labels: LGTM

#592 Add get_experiment_by_name to RestStore
  mlflow/store/rest_store.py
Labels: LGTM

#476 Display run name throughout UI
  mlflow/server/js/src/components/App.css
  mlflow/server/js/src/components/BreadcrumbTitle.css
  mlflow/server/js/src/components/BreadcrumbTitle.js
  mlflow/server/js/src/components/CompareRunScatter.css
  mlflow/server/js/src/components/CompareRunScatter.js
  mlflow/server/js/src/components/CompareRunView.js
  mlflow/server/js/src/components/ExperimentRunsTableCompactView.js
  mlflow/server/js/src/components/ExperimentRunsTableMultiColumnView.js
  mlflow/server/js/src/components/ExperimentViewUtil.js
  mlflow/server/js/src/components/MetricView.css
  mlflow/server/js/src/components/MetricView.js
  mlflow/server/js/src/components/RunView.js
  mlflow/server/js/src/utils/Utils.js
Labels: LGTM

#581 Updated multistep workflow example to include diagram
  docs/source/_static/images/tutorial-multistep-workflow.png
  examples/multistep_workflow/README.rst
Labels: LGTM, docs

#560 Properly handle HTTP request failures instead of raising JSON decode errors
  mlflow/projects/databricks.py
  mlflow/store/dbfs_artifact_repo.py
  mlflow/store/rest_store.py
  mlflow/utils/rest_utils.py
  tests/projects/test_databricks.py
  tests/store/test_dbfs_artifact_repo.py
  tests/store/test_rest_store.py
  tests/utils/test_rest_utils.py
Labels: LGTM

#603 Implement page not found view
  mlflow/server/js/src/components/App.js
  mlflow/server/js/src/components/CompareRunPage.js
  mlflow/server/js/src/components/MetricPage.js
  mlflow/server/js/src/components/PageNotFoundView.js
  mlflow/server/js/src/components/RunPage.js
Labels: LGTM

#604 Don't create default experiment if the FileStore root is already present
  mlflow/java/client/src/test/java/org/mlflow/tracking/TestClientProvider.java
  mlflow/store/file_store.py
  tests/projects/test_projects.py
  tests/projects/utils.py
  tests/spark/test_spark_model_export.py
  tests/store/test_file_store.py
Labels: LGTM

#611 Use PyYAML for MLflow conda environment generation
  mlflow/utils/environment.py
Labels: LGTM

#605 Improve experiment deletion UX
  mlflow/server/js/package-lock.json
  mlflow/server/js/package.json
  mlflow/server/js/src/components/ExperimentListView.js
  mlflow/server/js/src/components/ExperimentListView.test.js
  mlflow/server/js/src/components/ExperimentPage.js
  mlflow/server/js/src/components/ExperimentRunsTableCompactView.js
  mlflow/server/js/src/components/ExperimentRunsTableMultiColumnView.js
  mlflow/server/js/src/components/ExperimentView.js
  mlflow/server/js/src/components/HomePage.js
  mlflow/server/js/src/components/HomeView.js
  mlflow/server/js/src/components/HomeView.test.js
  mlflow/server/js/src/components/NoExperimentView.js
  mlflow/server/js/src/components/RequestStateWrapper.js
  mlflow/server/js/src/reducers/Reducers.js
  mlflow/server/js/src/static/no-experiments.svg
  mlflow/server/js/src/test-utils/Fixtures.js
Labels: LGTM

#620 Address some issues with compact runs view
  mlflow/server/js/src/components/ExperimentRunsTableCompactView.js
  mlflow/server/js/src/components/ExperimentView.css
Labels: LGTM

#622 [Java] Add documentation on how to use extended createRun
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowClient.java
Labels: LGTM

#612 Tensorflow: Bug fixes, API standardization, performance improvements
  mlflow/tensorflow.py
  mlflow/utils/file_utils.py
  tests/tensorflow/test_tensorflow_model_export.py
Labels: LGTM

#619 [UI] Add link from child run to parent
  mlflow/server/js/src/components/RunView.css
  mlflow/server/js/src/components/RunView.js
Labels: LGTM

#625 Update README.md
  mlflow/java/client/README.md
Labels: LGTM

#514 Add tags and R and Java APIs to tracking topic.
  docs/source/index.rst
  docs/source/tracking.rst
  docs/source/tutorial.rst
Labels: LGTM

#646 Removed anaconda channels to fix tests.
  mlflow/sagemaker/__init__.py
  mlflow/sagemaker/container/__init__.py
  mlflow/utils/environment.py
  tests/resources/example_project/conda.yaml
Labels: LGTM

#632 Error handling for experiment or run: meta.yaml is not found
  mlflow/exceptions.py
  mlflow/store/file_store.py
  mlflow/utils/file_utils.py
  tests/store/test_file_store.py
Labels: LGTM

#649 follow up change to #632: styling fix dict to kwargs
  mlflow/store/file_store.py
Labels: LGTM

#650 Remove superfluous print statement in file store
  mlflow/store/file_store.py
Labels: LGTM

#669 Azure Deployment: Add reference to open Python2 support issue in exception message
  mlflow/azureml/__init__.py
Labels: LGTM

#671 MLeap Serialization: Use absolute output paths
  mlflow/mleap.py
  tests/spark/test_spark_model_export.py
Labels: LGTM

#662 Precompute metric ranges instead of computing them per row
  mlflow/server/js/src/components/ExperimentRunsTableMultiColumnView.js
Labels: LGTM
