Repository mlflow/mlflow, pull requests merged in 2019-09, with the labels that each got.

#1757 Added fit_generator hooks for autolog
  mlflow/keras.py
  tests/keras_autolog/test_keras_autolog.py
Labels: rn/feature

#1801 Speed up Travis build in common cases by moving correlated tests into "large" stage
  .travis.yml
Labels: rn/none

#1805 SQLAlchemy: Improve performance of experiment list / get functions
  mlflow/store/sqlalchemy_store.py
Labels: LGTM, rn/feature

#1841 Configure MLflow repository with Probot-stale
  .github/stale.yml
Labels: will-fix

#1775 Add GetExperimentByName REST API & call it from the Python client
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
  mlflow/server/handlers.py
  mlflow/store/rest_store.py
  mlflow/tracking/utils.py
  tests/store/test_rest_store.py
  tests/store/test_sqlalchemy_store.py
  tests/tracking/test_rest_tracking.py
Labels: rn/feature

#1621 Propagate artifact storage configuration to docker env
  mlflow/projects/__init__.py
  tests/projects/test_docker_projects.py
Labels: rn/feature

#1846 Retry 429s in REST Client
  mlflow/utils/rest_utils.py
  tests/utils/test_rest_utils.py
Labels: LGTM

#1847 Retry 429s in MLflow UI
  mlflow/server/js/src/Actions.js
  mlflow/server/js/src/Actions.test.js
Labels: rn/feature

#1834 [Docs] Streamline docs for getting started with hosted MLflow
  docs/source/R-api.rst
  docs/source/index.rst
  docs/source/quickstart.rst
  docs/source/tracking.rst
Labels: rn/documentation

#1852 [UI] Enhance docstring for helper method used to make AJAX requests
  mlflow/server/js/src/Actions.js
Labels: LGTM, rn/none

#1862 [R] Fix bug where mlflow_list_artifact throws when listing artifacts for a run without any logged
  mlflow/R/mlflow/R/tracking-runs.R
  mlflow/R/mlflow/tests/testthat/test-tracking-runs.R
Labels: rn/bug-fix

#1860 [Docs] Clarify Mlflow quickstart code snippet for logging to your own tracking server vs CE
  docs/source/quickstart.rst
Labels: rn/documentation

#1876 Bump Jackson dependency versions
  mlflow/java/pom.xml
Labels: LGTM, rn/none

#1878 Fix SqlAlchemyStore search memory usage
  mlflow/store/sqlalchemy_store.py
  tests/store/test_sqlalchemy_store.py
Labels: rn/feature

#1803 Show geojson files on leaflet map
  mlflow/server/js/package-lock.json
  mlflow/server/js/package.json
  mlflow/server/js/src/components/ArtifactView.js
  mlflow/server/js/src/components/artifact-view-components/ShowArtifactHtmlView.js
  mlflow/server/js/src/components/artifact-view-components/ShowArtifactMapView.css
  mlflow/server/js/src/components/artifact-view-components/ShowArtifactMapView.js
  mlflow/server/js/src/components/artifact-view-components/ShowArtifactMapView.test.js
  mlflow/server/js/src/components/artifact-view-components/ShowArtifactPage.js
  mlflow/server/js/src/utils/FileUtils.js
Labels: LGTM
