Repository mlflow/mlflow, pull requests merged in 2019-07, with the labels that each got.

#1536 Add feature flag for enabling use of absolute Ajax URLs in the MLflow UI
  mlflow/server/js/config-overrides.js
  mlflow/server/js/package-lock.json
  mlflow/server/js/src/sdk/MlflowService.js
  mlflow/server/js/src/utils/Utils.js
Labels: rn/none

#1542 Add pagination support to sqlalchemy and file stores
  mlflow/server/handlers.py
  mlflow/store/file_store.py
  mlflow/store/rest_store.py
  mlflow/store/sqlalchemy_store.py
  mlflow/utils/search_utils.py
  tests/server/test_handlers.py
  tests/store/test_file_store.py
  tests/store/test_sqlalchemy_store.py
  tests/tracking/test_rest_tracking.py
  tests/utils/test_search_utils.py
Labels: LGTM

#1548 Python fluent API search_runs auto-pagination
  mlflow/store/__init__.py
  mlflow/tracking/fluent.py
  tests/tracking/test_fluent.py
Labels: LGTM

#1564 Support "Load more" on runs table
  mlflow/server/js/lint.sh
  mlflow/server/js/src/Actions.js
  mlflow/server/js/src/components/BaggedCell.js
  mlflow/server/js/src/components/ExperimentPage.js
  mlflow/server/js/src/components/ExperimentPage.test.js
  mlflow/server/js/src/components/ExperimentRunsTableCompactView.js
  mlflow/server/js/src/components/ExperimentView.css
  mlflow/server/js/src/components/ExperimentView.js
  mlflow/server/js/src/components/ExperimentView.test.js
  mlflow/server/js/src/components/ExperimentViewUtil.js
  mlflow/server/js/src/components/LoadMoreBar.js
  mlflow/server/js/src/components/LoadMoreBar.test.js
  mlflow/server/js/src/reducers/MetricReducer.js
  mlflow/server/js/src/reducers/Reducers.js
  mlflow/server/js/src/sdk/MlflowLocalStorageMessages.js
  mlflow/server/js/src/utils/Utils.js
Labels: LGTM

#1589 Fixing incorrect docs about log_artifacts
  docs/source/tracking.rst
Labels: LGTM

#1590 Fix top search area alignment
  mlflow/server/js/src/components/ExperimentView.css
  mlflow/server/js/src/components/ExperimentView.js
Labels: LGTM

#1599 Make Page interface public
  mlflow/java/client/src/main/java/org/mlflow/tracking/Page.java
Labels: LGTM

#1607 Fix OSS docs build bug
  docs/Makefile
  docs/build-javadoc.sh
Labels: rn/none

#1610 Set minimal required version fro tibble.
  mlflow/R/mlflow/DESCRIPTION
Labels: LGTM, rn/none

#1575 Update search docs to include searching by mlflow tag
  docs/source/search-syntax.rst
  docs/source/tracking.rst
Labels: docs

#1601 Autolog from Keras to MLflow
  .travis.yml
  docs/source/tracking.rst
  mlflow/keras.py
  tests/keras_autolog/test_keras_autolog.py
  tests/tensorflow_autolog/test_tensorflow_autolog.py
  travis/run-large-python-tests.sh
  travis/run-small-python-tests.sh
Labels: enhancement

#1614 Correctly display "permission denied" view in UI
  mlflow/server/js/src/components/ExperimentPage.js
  mlflow/server/js/src/components/ExperimentPage.test.js
Labels: rn/none

#1622 [Easy] doc fix for project cli option name change
  docs/source/projects.rst
Labels: rn/none

#1592 Added support for third-party plugins for MLFlow server
  mlflow/server/handlers.py
  tests/server/test_handlers.py
Labels: LGTM, rn/feature

#1636 Fix lint errors in test_artifact_repo.py
  tests/store/test_artifact_repo.py
Labels: rn/none

#1634 Keras parameter logging fixes
  mlflow/keras.py
  tests/keras_autolog/test_keras_autolog.py
Labels: rn/none

#1640 Finalize MLflow Branch 1.1
  mlflow/version.py
Labels: rn/none

#1641 Handle project file upload race condition
  mlflow/projects/databricks.py
Labels: rn/none

#1633 Add examples for Autologging
  examples/README.md
  examples/keras/train.py
  examples/tensorflow/train_predict.py
Labels: LGTM

#1646 Autologging doc improvements
  docs/source/tracking.rst
  mlflow/tensorflow.py
  tests/tensorflow_autolog/test_tensorflow_autolog.py
Labels: LGTM, rn/none

#1647 Deprecate `runs` field in GetExperiment.Response proto
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
Labels: rn/documentation

#1648 MLflow 1.1 Changelog
  CHANGELOG.rst
Labels: rn/none

#1659 Bump all package versions from 1.0.0 to 1.1.1.dev0
  mlflow/R/mlflow/DESCRIPTION
  mlflow/java/client/pom.xml
  mlflow/java/pom.xml
  mlflow/java/scoring/pom.xml
  mlflow/version.py
Labels: rn/none

#1656 Revamping GitHub Issue workflow
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/doc_fix_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/ISSUE_TEMPLATE/installation_issue_template.md
  ISSUE_POLICY.md
  ISSUE_TEMPLATE.md
  README.rst
Labels: LGTM, rn/none

#1663 Docs fixes
  mlflow/__init__.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: rn/none

#1658 Fix Spark bug loading Spark UDFs on Databricks
  mlflow/pyfunc/__init__.py
  tests/projects/test_projects.py
  tests/projects/test_projects_cli.py
Labels: rn/bug-fix

#1681 Fix UI search error behavior
  mlflow/server/js/src/components/ExperimentPage.js
  mlflow/server/js/src/components/ExperimentPage.test.js
Labels: rn/bug-fix

#1664 display artifact previews even if extension is upper case
  mlflow/server/js/src/components/artifact-view-components/ShowArtifactPage.js
Labels: LGTM
