Repository mlflow/mlflow, pull requests merged in 2019-11, with the labels that each got.

#2034 [LINT] Let ESLint detect react version
  mlflow/server/js/.eslintrc.js
Labels: LGTM

#1972 [UI] Update react-mde to the latest version
  mlflow/server/js/package-lock.json
  mlflow/server/js/package.json
  mlflow/server/js/src/common/components/EditableNote.js
Labels: LGTM

#2058 Add tag example in the search bar
  mlflow/server/js/src/components/ExperimentView.js
Labels: LGTM, rn/none

#2062 [UI] Disable service worker registration
  mlflow/server/js/src/index.js
Labels: rn/none

#1994 Add ability to mount volumes and specify environment variables when using mlflow with docker
  docs/source/projects.rst
  mlflow/projects/__init__.py
  mlflow/projects/_project_spec.py
  tests/projects/test_docker_projects.py
Labels: rn/feature

#2064 Enable logging pyspark ml params directly with log batch and log params.
  mlflow/entities/param.py
  tests/spark/test_sparkml_param_integration.py
Labels: LGTM

#2065 Improve support for unicode characters
  mlflow/projects/_project_spec.py
  mlflow/server/handlers.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/utils/string_utils.py
  mlflow/utils/validation.py
  tests/projects/test_projects_cli.py
  tests/utils/test_string_utils.py
  tests/utils/test_validation.py
Labels: LGTM

#2074 Fix typo in exception description string
  mlflow/projects/__init__.py
Labels: LGTM, rn/none

#2066 Fix Java package name used for MLflow model registry protos
  mlflow/java/client/src/main/java/org/mlflow/api/proto/ModelRegistry.java
  mlflow/protos/model_registry.proto
  mlflow/protos/model_registry_pb2.py
Labels: rn/breaking-change

#2063 Add RST docs job to Travis tests
  .travis.yml
  docs/source/cli.rst
  docs/source/languagesections/__init__.py
  docs/source/python_api/exceptions/mlflow.exceptions.rst
  docs/source/python_api/mlflow.entities.rst
  docs/source/search-syntax.rst
  mlflow/cli.py
  mlflow/exceptions.py
  mlflow/mleap.py
  mlflow/models/cli.py
  mlflow/projects/__init__.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
Labels: rn/none

#2068 Don't unconditionally format values as metrics in generic HtmlTableView component
  mlflow/server/js/src/components/HtmlTableView.js
  mlflow/server/js/src/components/RunView.js
Labels: rn/bug-fix

#2067 Fix models serve, models predict CLI commands against models:/ URIs
  mlflow/models/cli.py
  mlflow/store/artifact/models_artifact_repo.py
  tests/helper_functions.py
  tests/models/test_cli.py
Labels: rn/bug-fix

#2077 Remove quotes from the tag search example
  mlflow/server/js/src/components/ExperimentView.js
Labels: rn/none

#2054 Fix note editor on the experiment page
  mlflow/server/js/src/components/ExperimentView.js
  mlflow/server/js/src/components/NoteEditorView.js
Labels: LGTM, rn/bug-fix

#2083 Add alt text to icon img tags
  mlflow/server/js/.eslintrc.js
  mlflow/server/js/src/utils/Utils.js
Labels: LGTM

#2095 Added fit_generator hooks for TensorFlow.Keras autolog
  mlflow/tensorflow.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/tensorflow_autolog/test_tensorflow_autolog.py
Labels: rn/feature

#2100 Wrapping TensorFlow/Keras autolog runs with try_mlflow_log()
  mlflow/keras.py
  mlflow/tensorflow.py
Labels: rn/none

#2114 Fix search docs to reflect MLflow user tag support and start/end time ordering
  docs/source/search-syntax.rst
Labels: rn/none

#2109 [Docs] Add back reference to fluent API
  mlflow/__init__.py
Labels: docs, rn/none

#2128 Doc models:/ scheme for URI for load_model methods.
  docs/source/concepts.rst
  docs/source/models.rst
  docs/source/tracking.rst
  mlflow/R/mlflow/man/mlflow_load_model.Rd
  mlflow/azureml/__init__.py
  mlflow/gluon.py
  mlflow/h2o.py
  mlflow/keras.py
  mlflow/onnx.py
  mlflow/pyfunc/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/sagemaker/__init__.py
  mlflow/sklearn.py
  mlflow/spark.py
  mlflow/tensorflow.py
Labels: rn/documentation

#2121 Fix typos in docstrings
  mlflow/h2o.py
  mlflow/keras.py
  mlflow/onnx.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
  mlflow/pytorch/__init__.py
  mlflow/sklearn.py
  mlflow/spark.py
  mlflow/tensorflow.py
Labels: rn/none

#2119 Adding TensorFlow.Keras and Keras parameter logging
  docs/source/tracking.rst
  mlflow/keras.py
  mlflow/tensorflow.py
  mlflow/utils/autologging_utils.py
  tests/keras_autolog/test_keras_autolog.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/tensorflow_autolog/test_tensorflow_autolog.py
  tests/utils/test_autologging_utils.py
Labels: rn/feature

#2124 Add support for XGBoost flavor
  .travis.yml
  mlflow/xgboost.py
  tests/xgboost/test_xgboost_model_export.py
  travis/large-requirements.txt
  travis/run-large-python-tests.sh
  travis/run-small-python-tests.sh
Labels: rn/feature

#2146 Local bootstrap css
  mlflow/server/js/public/bootstrap/bootstrap.min.css
  mlflow/server/js/public/index.html
Labels: rn/none

#2137 Strip "dev" suffix from PySpark versions
  mlflow/spark.py
  tests/spark/test_spark_model_export.py
Labels: LGTM, rn/bug-fix

#2138 Update active_run() docs for accessing current run data
  docs/source/tracking.rst
  mlflow/tracking/fluent.py
Labels: docs, rn/documentation

#2132 Clarify MLflow Projects existing cluster restrictions
  docs/source/projects.rst
  mlflow/projects/databricks.py
  tests/projects/test_databricks.py
Labels: LGTM
