Repository mlflow/mlflow, pull requests merged in 2019-10, with the labels that each got.

#1892 Fix download of artifacts with HdfsArtifactRepository (#1890)
  mlflow/store/hdfs_artifact_repo.py
  tests/store/test_hdfs_artifact_repo.py
Labels: rn/bug-fix

#1885 Changelog for MLflow 1.3
  CHANGELOG.rst
Labels: rn/none

#1904 R - fixing broken tests
  mlflow/R/mlflow/.travis.R
  mlflow/R/mlflow/tests/testthat/test-style.R
Labels: rn/none

#1894 Update package versions to 1.3.1.dev0 etc
  mlflow/R/mlflow/DESCRIPTION
  mlflow/java/client/pom.xml
  mlflow/java/pom.xml
  mlflow/java/scoring/pom.xml
  mlflow/version.py
Labels: rn/none

#1915 Move URI helper methods to utils.uri module
  mlflow/cli.py
  mlflow/projects/__init__.py
  mlflow/projects/databricks.py
  mlflow/spark.py
  mlflow/store/artifact/artifact_repository_registry.py
  mlflow/store/artifact/cli.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/registry.py
  mlflow/tracking/utils.py
  mlflow/utils/__init__.py
  mlflow/utils/uri.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/test_tracking.py
  tests/tracking/test_utils.py
  tests/utils/test_uri.py
  tests/utils/test_utils.py
Labels: rn/breaking-change

#1928 Suppress deprecation warnings when using mlflow.pyfunc.load_model()
  mlflow/pyfunc/__init__.py
Labels: LGTM, rn/none

#1914 Correct the documentation filename
  examples/flower_classifier/README.rst
Labels: LGTM, rn/none

#1929 [UI] Enable scroll zoom on metrics and run comparison plots
  mlflow/server/js/package-lock.json
  mlflow/server/js/package.json
  mlflow/server/js/src/components/CompareRunScatter.js
  mlflow/server/js/src/components/MetricsPlotView.js
Labels: UI/UX, rn/feature

#1932 Remove recharts from dependencies
  mlflow/server/js/package-lock.json
  mlflow/server/js/package.json
  mlflow/server/js/src/components/MetricView.css
Labels: LGTM, rn/none

#1913 Fix dependency-installation bug in Java MLflow model scoring server
  mlflow/models/docker_utils.py
Labels: rn/bug-fix

#1952 [cleanup] Get rid of `\` in projects/__init__.py
  mlflow/projects/__init__.py
Labels: rn/none

#1955 [cleanup] Fix some indent and bad parameter names
  mlflow/projects/__init__.py
Labels: rn/none

#1968 Fix encoding of metric names in MLflow UI URLs
  mlflow/server/js/src/Actions.js
  mlflow/server/js/src/Routes.js
Labels: LGTM, UI/UX, rn/bug-fix

#1981 Make detection of MLproject files case insensitive
  mlflow/projects/_project_spec.py
  tests/projects/test_project_spec.py
Labels: LGTM, rn/bug-fix

#1978 [UI] Fix bug where UI endlessly spins on attempting to view a metric from the runs page
  mlflow/server/js/src/components/MetricsPlotPanel.js
Labels: UI/UX, rn/none

#1983 Improve error messages for stores that do not support the model registry
  mlflow/tracking/client.py
  mlflow/tracking/registry.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
  tests/tracking/_tracking_service/test_utils.py
  tests/tracking/test_client.py
Labels: LGTM

#1923 Add functions from mlflow client to fluent api
  mlflow/__init__.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  tests/tracking/test_fluent.py
Labels: rn/feature

#2017 Update version to 1.4
  mlflow/R/mlflow/DESCRIPTION
  mlflow/java/client/pom.xml
  mlflow/java/pom.xml
  mlflow/java/scoring/pom.xml
  mlflow/version.py
Labels: rn/none

#1996 Bug-fix for remote execution from windows using posixpath
  mlflow/projects/databricks.py
Labels: rn/bug-fix

#1958 [UI] Display "Loading..." when the artifact image viewer is loading an image
  mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js
Labels: rn/feature

#1995 Model Registry integration tests
  mlflow/entities/model_registry/model_version_stages.py
  mlflow/server/handlers.py
  mlflow/store/model_registry/dbmodels/models.py
  mlflow/store/model_registry/sqlalchemy_store.py
  tests/server/test_handlers.py
  tests/tracking/__init__.py
  tests/tracking/_tracking_service/test_utils.py
  tests/tracking/context/test_default_context.py
  tests/tracking/context/test_git_context.py
  tests/tracking/context/test_registry.py
  tests/tracking/integration_test_utils.py
  tests/tracking/test_client.py
  tests/tracking/test_fluent.py
  tests/tracking/test_model_registry.py
  tests/tracking/test_rest_tracking.py
  tests/tracking/test_tracking.py
Labels: rn/bug-fix

#2021 Model Registry docs
  docs/source/_static/images/oss_registry_1_register.png
  docs/source/_static/images/oss_registry_2_dialog.png
  docs/source/_static/images/oss_registry_3_overview.png
  docs/source/_static/images/oss_registry_3b_version.png
  docs/source/_static/images/oss_registry_4_version.png
  docs/source/_static/images/oss_registry_5_transition.png
  docs/source/index.rst
  docs/source/model-registry.rst
  docs/source/python_api/mlflow.entities.rst
  docs/source/rest-api.rst
  mlflow/entities/model_registry/model_version.py
  mlflow/entities/model_registry/model_version_detailed.py
  mlflow/entities/model_registry/registered_model.py
  mlflow/entities/model_registry/registered_model_detailed.py
  mlflow/java/client/src/main/java/com/databricks/api/proto/mlflow/ModelRegistry.java
  mlflow/protos/model_registry.proto
  mlflow/protos/model_registry_pb2.py
Labels: rn/documentation

#1959 [UI] Prevent the x-axis range from changing when toggling scatter markers
  mlflow/server/js/src/components/MetricsPlotView.js
  mlflow/server/js/src/components/MetricsPlotView.test.js
Labels: UI/UX, rn/none

#2027 Update version to 1.4.1
  mlflow/R/mlflow/DESCRIPTION
  mlflow/java/client/pom.xml
  mlflow/java/pom.xml
  mlflow/java/scoring/pom.xml
  mlflow/version.py
Labels: LGTM, rn/none
