Repository mlflow/mlflow, pull requests merged in 2019-12, with the labels that each got.

#2157 Docs: Add SparkR tips for Project execution on Databricks
  docs/source/projects.rst
Labels: rn/none

#2167 Add doc for XGBoost flavor
  docs/source/python_api/mlflow.xgboost.rst
  mlflow/xgboost.py
Labels: docs, rn/documentation

#2161 Travis Nightly Build
  .travis.yml
  CONTRIBUTING.rst
  travis/run-large-python-tests.sh
Labels: rn/none

#2170 Doc enhancements for XGBoost and LightGBM flavors
  docs/source/models.rst
  mlflow/lightgbm.py
  mlflow/xgboost.py
Labels: LGTM, rn/documentation

#2180 Add pom.xml for MLflow Spark datasource autologging integration
  mlflow/java/pom.xml
  mlflow/java/spark/pom.xml
Labels: rn/none

#2188 Update contributor dependencies
  dev-requirements.txt
  generate-protos.sh
  mlflow/protos/databricks.proto
  mlflow/server/js/package-lock.json
  test-generate-protos.sh
Labels: dependencies, rn/none

#2197 Add note about active run instantiation side effect in fluent APIs
  mlflow/models/__init__.py
  mlflow/spark.py
  mlflow/tracking/fluent.py
Labels: rn/documentation

#2186 Add XGBoost and LightGBM examples
  docs/source/tutorials-and-examples/index.rst
  examples/lightgbm/MLproject
  examples/lightgbm/README.md
  examples/lightgbm/conda.yaml
  examples/lightgbm/train.py
  examples/xgboost/MLproject
  examples/xgboost/README.md
  examples/xgboost/conda.yaml
  examples/xgboost/train.py
  tests/examples/test_examples.py
Labels: rn/documentation

#2207 Log project backend for local runs with no environment
  mlflow/projects/__init__.py
  tests/projects/test_docker_projects.py
  tests/projects/test_projects.py
Labels: rn/none

#2216 Fix mlflow.keras.save_model with DBFS
  mlflow/keras.py
  travis/large-requirements.txt
Labels: rn/bug-fix

#2221 Fix artifact URI constructions in FileStore and SqlAlchemyStore
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/utils/uri.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/utils/test_uri.py
Labels: rn/none

#2181 Add Java implementation of Spark datasource autologging
  mlflow/java/spark/pom.xml
  mlflow/java/spark/src/main/scala/org/apache/spark/sql/SparkAutologgingUtils.scala
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/DatasourceAttributeExtractor.scala
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/ExceptionUtils.scala
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/MlflowAutologEventPublisher.scala
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/MlflowAutologEventSubscriber.scala
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/SparkDataSourceListener.scala
  mlflow/java/spark/src/test/scala/org/apache/spark/mlflow/MlflowSparkAutologgingTestUtils.scala
  mlflow/java/spark/src/test/scala/org/mlflow/spark/autologging/SparkAutologgingIntegrationSuite.scala
Labels: rn/none

#2232 registry.html points to model-registry.html
  docs/source/registry.rst
Labels: docs

#2243 Fix tests
  tests/tensorflow/test_tensorflow_model_export.py
  travis/large-requirements.txt
Labels: rn/none
