Repository mlflow/mlflow, pull requests merged in 2020-11, with the labels that each got.

#3534 Remove `attrdict` from dependencies by using `collections.namedtuple` instead
  dev/small-requirements.txt
  tests/tracking/test_tracking.py
Labels: rn/none

#3557 Logging/Loading TorchScripted model
  examples/pytorch/torchscript/IrisClassification/MLproject
  examples/pytorch/torchscript/IrisClassification/README.md
  examples/pytorch/torchscript/IrisClassification/conda.yaml
  examples/pytorch/torchscript/IrisClassification/iris_classification.py
  examples/pytorch/torchscript/MNIST/MLproject
  examples/pytorch/torchscript/MNIST/README.md
  examples/pytorch/torchscript/MNIST/conda.yaml
  examples/pytorch/torchscript/MNIST/mnist_torchscript.py
  mlflow/pytorch/__init__.py
  tests/pytorch/test_pytorch_model_export.py
Labels: area/models, rn/feature

#3597 mlflow deployments - Adding predict cli option and adding config argument for delete deployment
  mlflow/deployments/cli.py
  tests/deployments/test_cli.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/fake_deployment_plugin.py
Labels: area/models, language/r, rn/feature

#3601 Autolog with PyTorch using lightning
  dev/extra-ml-requirements.txt
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_pytorch_autolog.py
  tests/pytorch/iris.py
  tests/pytorch/test_pytorch_autolog.py
Labels: area/artifacts, area/models, rn/feature

#3607 Log torchserve artifacts under `torchserve_artifacts` and log their locations in MLmodel file
  mlflow/pytorch/__init__.py
  tests/pytorch/test_pytorch_model_export.py
Labels: rn/none

#3617 Autologging: Pluralize configuration arguments
  mlflow/lightgbm.py
  mlflow/sklearn/__init__.py
  mlflow/tracking/fluent.py
  mlflow/xgboost.py
  tests/lightgbm/test_lightgbm_autolog.py
  tests/sklearn/test_sklearn_autolog.py
  tests/tracking/fluent/test_fluent_autolog.py
  tests/xgboost/test_xgboost_autolog.py
Labels: area/tracking, rn/none

#3608 Autolog with PyTorch using lightning - Examples
  examples/pytorch/BertNewsClassification/MLproject
  examples/pytorch/BertNewsClassification/README.md
  examples/pytorch/BertNewsClassification/bert_classification.py
  examples/pytorch/BertNewsClassification/conda.yaml
  examples/pytorch/MNIST/README.md
  examples/pytorch/MNIST/example1/MLproject
  examples/pytorch/MNIST/example1/README.md
  examples/pytorch/MNIST/example1/conda.yaml
  examples/pytorch/MNIST/example1/mnist_autolog_example1.py
  examples/pytorch/MNIST/example2/MLproject
  examples/pytorch/MNIST/example2/README.md
  examples/pytorch/MNIST/example2/conda.yaml
  examples/pytorch/MNIST/example2/mnist_autolog_example2.py
Labels: area/models

#3635 Remove optimizer step override in PL examples
  examples/pytorch/MNIST/example1/mnist_autolog_example1.py
  examples/pytorch/MNIST/example2/mnist_autolog_example2.py
Labels: area/examples, rn/bug-fix

#3632 Pytorch Autolog - Using tmpdir for model checkpoints and adding updating gitignore
  .gitignore
  tests/pytorch/test_pytorch_autolog.py
Labels: area/artifacts, rn/none

#3634 Mlflow torchserve plugin doc
  docs/source/plugins.rst
Labels: area/artifacts, rn/documentation

#3630 fix issue #1997 with sparkling water and s3
  mlflow/h2o.py
Labels: area/models, needs review

#3648 Put preview paths before non-preview paths for backwards compatibility
  mlflow/java/client/src/main/java/org/mlflow/api/proto/ModelRegistry.java
  mlflow/protos/model_registry.proto
  mlflow/protos/model_registry_pb2.py
  tests/store/model_registry/test_rest_store.py
Labels: area/model-registry, rn/feature

#3639 PyTorch Autolog Example Readme files
  examples/pytorch/BertNewsClassification/MLproject
  examples/pytorch/BertNewsClassification/README.md
  examples/pytorch/BertNewsClassification/bert_classification.py
  examples/pytorch/MNIST/example1/MLproject
  examples/pytorch/MNIST/example1/README.md
  examples/pytorch/MNIST/example1/mnist_autolog_example1.py
  examples/pytorch/MNIST/example2/MLproject
  examples/pytorch/MNIST/example2/README.md
  examples/pytorch/MNIST/example2/mnist_autolog_example2.py
Labels: area/docs, rn/none

#3651 Fix crash in ddp due to no sync of validation loss
  examples/pytorch/BertNewsClassification/bert_classification.py
  examples/pytorch/MNIST/example1/mnist_autolog_example1.py
  examples/pytorch/MNIST/example2/mnist_autolog_example2.py
Labels: area/examples, rn/bug-fix

#3636 Pytorch Autologging Description Added To Tracking.rst
  docs/source/tracking.rst
  mlflow/pytorch/__init__.py
Labels: area/artifacts, area/docs, rn/documentation

#3638 Updating pytorch autolog to log only the first optimizer params
  mlflow/pytorch/_pytorch_autolog.py
  tests/pytorch/test_pytorch_autolog.py
Labels: area/artifacts, rn/none

#3552 (Issue #3224) Allow keras models to be saved with SavedModel format
  mlflow/keras.py
  tests/keras/test_keras_model_export.py
Labels: area/models, rn/bug-fix

#3662 Add Pytorch lightning autologging to universal autologging
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: area/tracking, rn/none

#3664 Use gorilla inlined into MLflow in Pytorch autologging
  mlflow/pytorch/_pytorch_autolog.py
Labels: rn/none

#3654 Re-enable `devtools::check_built` for R
  mlflow/R/mlflow/.run-tests.R
Labels: language/r, rn/none

#3667 Fix library incompatibility for exported Keras models
  dev/extra-ml-requirements.txt
  mlflow/R/mlflow/.create-test-env.R
  mlflow/keras.py
  tests/keras/test_keras_model_export.py
Labels: area/models, area/scoring, rn/bug-fix

#3619 Introduce time-based batch metrics logging and change XGBoost to use it
  mlflow/utils/autologging_utils.py
  mlflow/xgboost.py
  tests/utils/test_autologging_utils.py
Labels: area/tracking, rn/none

#3655 Pytorch autolog Examples - Fixing argument parser & Adding `accelerator` to MLProject
  examples/pytorch/BertNewsClassification/MLproject
  examples/pytorch/BertNewsClassification/README.md
  examples/pytorch/BertNewsClassification/bert_classification.py
  examples/pytorch/BertNewsClassification/conda.yaml
  examples/pytorch/MNIST/example1/MLproject
  examples/pytorch/MNIST/example1/README.md
  examples/pytorch/MNIST/example1/mnist_autolog_example1.py
  examples/pytorch/MNIST/example2/MLproject
  examples/pytorch/MNIST/example2/README.md
  examples/pytorch/MNIST/example2/mnist_autolog_example2.py
Labels: area/examples, rn/none

#3675 Minor edits to MLflow 1.12.0 changelogs
  CHANGELOG.rst
Labels: rn/none

#3658 Fix a flaky pytorch autologging test
  tests/pytorch/test_pytorch_autolog.py
Labels: area/build, rn/none

#3678 Add `log_text`
  mlflow/__init__.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  tests/tracking/test_tracking.py
Labels: area/artifacts, rn/feature

#3685 Add `log_dict`
  mlflow/__init__.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  tests/tracking/test_tracking.py
Labels: area/artifacts, rn/feature

#3653 Do not disable existing loggers when init alembic
  mlflow/store/db_migrations/env.py
Labels: area/tracking, rn/bug-fix, rn/none

#3703 Only import matplotlib where necessary for artifact plotting
  mlflow/sklearn/utils.py
Labels: area/tracking, rn/bug-fix

#3419 Some additional model handling to azureml.deploy
  mlflow/azureml/__init__.py
Labels: integrations/azure, rn/feature

#3643 Adding DatabricksModelArtifactRepository
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/store/artifact/models_artifact_repo.py
  mlflow/store/artifact/utils/__init__.py
  mlflow/store/artifact/utils/models.py
  mlflow/utils/file_utils.py
  tests/store/artifact/test_databricks_models_artifact_repo.py
  tests/store/artifact/test_models_artifact_repo.py
  tests/store/artifact/utils/__init__.py
  tests/store/artifact/utils/test_model_utils.py
Labels: area/artifacts, area/model-registry, area/models, integrations/databricks, rn/feature

#3649 Java Client changes to incorporate PreSigned Url support.
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowClient.java
  mlflow/java/client/src/test/java/org/mlflow/tracking/ModelRegistryMlflowClientTest.java
Labels: area/artifacts, area/model-registry, language/java, rn/feature

#3681 Fix run_link for cross-workspace model versions
  mlflow/utils/databricks_utils.py
  tests/utils/test_databricks_utils.py
Labels: area/model-registry, rn/none

#3663 Add log_models configuration for autologging
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_pytorch_autolog.py
  mlflow/sklearn/__init__.py
  mlflow/tensorflow.py
  mlflow/tracking/fluent.py
  mlflow/xgboost.py
  tests/fastai/test_fastai_autolog.py
  tests/gluon_autolog/test_gluon_autolog.py
  tests/keras_autolog/test_keras_autolog.py
  tests/lightgbm/test_lightgbm_autolog.py
  tests/pytorch/test_pytorch_autolog.py
  tests/sklearn/test_sklearn_autolog.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/tensorflow_autolog/test_tensorflow_autolog.py
  tests/tracking/fluent/test_fluent_autolog.py
  tests/xgboost/test_xgboost_autolog.py
Labels: area/tracking, rn/feature

#3699 [mlflow.log_dict] Specify `Loader` in `yaml.load` to suppress deprecated warning
  tests/tracking/test_tracking.py
Labels: area/build, rn/none

#3701 [mlflow.log_dict] Set `default_flow_style` to False in `yaml.dump`
  mlflow/tracking/client.py
Labels: rn/none

#3621 drop global filterwwarnings module at import time
  mlflow/__init__.py
Labels: rn/bug-fix

#3707 Add `log_figure`
  dev/large-requirements.txt
  mlflow/__init__.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  tests/tracking/test_tracking.py
Labels: area/artifacts, rn/feature

#3725 Code snippet for autolog and some retrofitting to include model.fit() where necessary
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: area/docs

#3721 Ensure azure-storage-blob>=12.0.0
  setup.py
Labels: area/build, rn/none

#3736 Avoid using mutable default argument value
  mlflow/xgboost.py
Labels: area/models, rn/none

#3735 Unpin TF / Keras and fix bugs in autologging integrations for newer versions
  dev/extra-ml-requirements.txt
  dev/run-python-tf-tests.sh
  mlflow/fastai.py
  mlflow/keras.py
  mlflow/tensorflow.py
  mlflow/utils/autologging_utils.py
  tests/keras/test_keras_model_export.py
  tests/keras_autolog/test_keras_autolog.py
  tests/onnx/test_onnx_model_export.py
  tests/tensorflow/test_tensorflow_model_export.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/utils/test_autologging_utils.py
Labels: area/tracking, rn/bug-fix

#3728 Add `log_image`
  mlflow/__init__.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  tests/tracking/test_tracking.py
Labels: area/artifacts, rn/feature

#3747 Use `distutils.version.LooseVersion` instead of `packaging.version` in `test_keras_model_export.py`
  tests/keras/test_keras_model_export.py
Labels: area/build, rn/none

#3749 Specify `eval_metric` in xgboost autologging test
  tests/xgboost/test_xgboost_autolog.py
Labels: area/build, rn/none

#3650 Adding Unit Tests for pytorch autolog examples
  tests/examples/test_examples.py
Labels: area/examples, rn/none

#3750 [xgboost autologging test] Fix expected value for `maximize` argument in `xgboost.train`
  tests/xgboost/test_xgboost_autolog.py
Labels: area/build, rn/none
