Repository mlflow/mlflow, pull requests merged in 2020-09, with the labels that each got.

#3327 Add addition metrics for auto logging
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
  tests/sklearn/test_sklearn_autolog.py
Labels: area/tracking

#3302 Verify valid JSON format in REST output
  mlflow/utils/rest_utils.py
  tests/store/artifact/test_dbfs_rest_artifact_repo.py
  tests/utils/test_rest_utils.py
Labels: area/tracking, integrations/databricks, rn/none

#3294 Add a utility function to apply a patch while preserving the attributes of an original function
  mlflow/utils/autologging_utils.py
  tests/utils/test_autologging_utils.py
Labels: area/models, rn/none

#3387 Use `wrap_patch` in autologging integrations to preserve original function attributes
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/sklearn/__init__.py
  mlflow/tensorflow.py
  mlflow/xgboost.py
Labels: area/models, rn/none

#3386 Add inference of input/output schema and input example to LightGBM autologging
  mlflow/lightgbm.py
  tests/lightgbm/test_lightgbm_autolog.py
Labels: area/models, rn/feature

#3243 mention additional librairies
  docs/source/quickstart.rst
Labels: area/docs, rn/documentation

#3376 Await model version creation
  mlflow/fastai.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/models/model.py
  mlflow/onnx.py
  mlflow/pyfunc/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/spark.py
  mlflow/tensorflow.py
  mlflow/tracking/_model_registry/__init__.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
  mlflow/xgboost.py
  tests/fastai/test_fastai_model_export.py
  tests/keras/test_keras_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/onnx/test_onnx_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spark/test_spark_model_export.py
  tests/tensorflow/test_tensorflow2_model_export.py
  tests/tensorflow/test_tensorflow_model_export.py
  tests/tracking/_model_registry/test_model_registry_client.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
  tests/tracking/test_client.py
  tests/xgboost/test_xgboost_model_export.py
Labels: area/model-registry, area/models, area/tracking, rn/breaking-change, rn/feature

#3345 Allow to skip TLS verification of S3 endpoint
  docs/source/tracking.rst
  mlflow/data.py
  mlflow/projects/backend/local.py
  mlflow/store/artifact/s3_artifact_repo.py
  tests/projects/backend/test_local.py
Labels: area/tracking, rn/documentation

#3417 Fix model version run_link URL for some Databricks regions
  mlflow/utils/databricks_utils.py
  tests/utils/test_databricks_utils.py
Labels: area/model-registry, rn/bug-fix

#3394 Pin fbprophet
  examples/prophet/conda.yaml
Labels: area/examples, rn/none

#3370 Mention sklearn autologging in main autologging doc section
  docs/source/tracking.rst
Labels: area/docs, rn/none

#3329 Fix for restarting terminated run not setting status correctly
  mlflow/tracking/fluent.py
  tests/tracking/test_fluent.py
Labels: area/tracking, rn/none

#3424 Cherry-pick #3370 into branch-1.11
  docs/source/tracking.rst
Labels: rn/none

#3385 Part 1 of code snippets for the fluent mlflow API module. This addresses issue #3153
  mlflow/__init__.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/_model_registry/utils.py
  mlflow/tracking/_tracking_service/utils.py
  mlflow/tracking/fluent.py
Labels: area/docs, rn/documentation

#3422 Log the best cv score when auto-logging parameter search estimator
  mlflow/sklearn/__init__.py
  tests/sklearn/test_sklearn_autolog.py
Labels: area/models, rn/none

#3420 docs: indicate that input example artifacts will be included for xgboost and lightgbm autologging
  docs/source/tracking.rst
Labels: area/docs, rn/none

#3410 "Call `atexit.register(_flush_queue)` in `tensorflow.autolog`
  .github/workflows/master.yml
  mlflow/tensorflow.py
Labels: area/models, rn/bug-fix

#3403 Add inference of input/output schema and input example to XGBoost autologging
  examples/xgboost/train.py
  mlflow/lightgbm.py
  mlflow/sklearn/__init__.py
  mlflow/utils/autologging_utils.py
  mlflow/xgboost.py
  tests/xgboost/test_xgboost_autolog.py
Labels: area/models, rn/feature

#3399 Fixing pylint issues in mlflow pytorch
  mlflow/pytorch/__init__.py
  tests/pytorch/test_pytorch_model_export.py
Labels: area/models, rn/none

#3145 fix duplicate stderr logging
  mlflow/R/mlflow/R/cli.R
Labels: language/r, rn/bug-fix

#3276 Set experiment on start run
  mlflow/R/mlflow/R/tracking-runs.R
  mlflow/R/mlflow/tests/testthat/test-run.R
Labels: area/tracking, area/uiux, language/r, rn/none

#3416 support h2o for R
  docs/source/R-api.rst
  docs/source/models.rst
  mlflow/R/mlflow/.run-tests.R
  mlflow/R/mlflow/DESCRIPTION
  mlflow/R/mlflow/NAMESPACE
  mlflow/R/mlflow/R/install.R
  mlflow/R/mlflow/R/model-h2o.R
  mlflow/R/mlflow/R/model-keras.R
  mlflow/R/mlflow/R/model-utils.R
  mlflow/R/mlflow/R/model-xgboost.R
  mlflow/R/mlflow/R/model.R
  mlflow/R/mlflow/man/mlflow_maybe_create_conda_env.Rd
  mlflow/R/mlflow/man/mlflow_save_model.Rd
  mlflow/R/mlflow/tests/testthat/test-model-h2o.R
  mlflow/R/mlflow/tests/testthat/test-serve.R
  mlflow/R/mlflow/tests/testthat/test/crate.bin
Labels: area/models, language/r, rn/feature

#3423 Add additional artifacts for auto logging
  dev/small-requirements.txt
  mlflow/sklearn/utils.py
  tests/sklearn/test_sklearn_autolog.py
Labels: area/models, rn/feature

#3434 Pin sqlparse
  setup.py
Labels: area/model-registry, rn/none

#3439 Update example code for Spark autologging
  mlflow/spark.py
Labels: area/docs, rn/documentation

#3373 Add mlflow-yarn backend to the doc
  docs/source/plugins.rst
Labels: area/projects, rn/documentation

#3437 Part 2 of the issue 3153 code snippets for the remaing API methods
  mlflow/projects/__init__.py
  mlflow/tracking/_tracking_service/utils.py
  mlflow/tracking/fluent.py
Labels: area/docs, rn/documentation

#3459 Update helper functions used for detecting context information in jobs to pull from allowlisted APIs
  mlflow/utils/databricks_utils.py
Labels: rn/none

#3451 Performance improvement in Spark UDFs that return an array
  mlflow/pyfunc/__init__.py
Labels: rn/none
