Repository mlflow/mlflow, pull requests merged in 2020-04, with the labels that each got.

#2531 Minor improvement to error message readability for SqlAlchemyStore
  mlflow/store/model_registry/sqlalchemy_store.py
Labels: rn/none

#2654 documenting datatype for `step` argument in `log_metric`
  mlflow/tracking/client.py
Labels: rn/documentation

#2532 Fix typos and docs for update_registered_model
  mlflow/tracking/client.py
Labels: rn/none

#2652 Update TF version to 1.15.2
  examples/multistep_workflow/conda.yaml
  mlflow/R/mlflow/.travis.R
  travis/large-requirements.txt
Labels: rn/none

#2679 Fix short help text for MLflow GC CLI
  mlflow/cli.py
Labels: rn/bug-fix

#2670 Fix bug causing erroneous deletion of TensorBoard logging directory
  mlflow/tensorflow.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/tensorflow_autolog/test_tensorflow_autolog.py
Labels: rn/bug-fix

#2695 Add model registry to PR component template
  .github/pull_request_template.md
Labels: rn/none

#2723 Make MlflowClient serializable
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowClient.java
Labels: LGTM

#2566 Add plugin interface for executing MLflow projects against custom backends
  docs/source/plugins.rst
  mlflow/projects/__init__.py
  mlflow/projects/backend/__init__.py
  mlflow/projects/backend/abstract_backend.py
  mlflow/projects/backend/loader.py
  mlflow/projects/databricks.py
  mlflow/projects/utils.py
  tests/examples/README.md
  tests/projects/backend/test_loader.py
  tests/projects/conftest.py
  tests/projects/test_projects.py
  tests/projects/test_utils.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/__init__.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/dummy_backend.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/file_store.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/local_artifact.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/run_context_provider.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/sql_store_alchemy.py
  tests/resources/mlflow-test-plugin/setup.py
  tests/server/test_handlers.py
  tests/store/artifact/test_artifact_repository_registry.py
  tests/tracking/_tracking_service/test_utils.py
  tests/tracking/context/test_registry.py
Labels: rn/feature

#2743 Update compatibility with later versions of pyarrow (up to 0.17.0)
  docs/source/tracking.rst
  mlflow/projects/__init__.py
  mlflow/store/artifact/hdfs_artifact_repo.py
  tests/projects/test_docker_projects.py
  tests/pyfunc/test_spark.py
  tests/spark/test_spark_model_export.py
  tests/store/artifact/test_hdfs_artifact_repo.py
  travis/large-requirements.txt
  travis/lint-requirements.txt
  travis/small-requirements.txt
Labels: Acknowledged
