Repository mlflow/mlflow, pull requests merged in 2020-01, with the labels that each got.

#2253 Update protoc installation instructions
  CONTRIBUTING.rst
Labels: rn/none

#2191 CONTRIBUTING.rst Devloop updates
  CONTRIBUTING.rst
Labels: LGTM

#2261 Fix typo in documentation
  mlflow/models/__init__.py
Labels: LGTM

#2226 Fix typos in append_to_uri_path docstring
  mlflow/utils/uri.py
Labels: LGTM, rn/none

#2237 Use append_to_uri_path for URI construction in other relevant locations
  mlflow/models/cli.py
  mlflow/spark.py
  mlflow/tracking/artifact_utils.py
  mlflow/utils/model_utils.py
  tests/tracking/test_tracking.py
Labels: rn/none

#2278 Pin TF version to 2.0.0
  travis/run-large-python-tests.sh
Labels: rn/none

#2288 Depend on older stringi
  .travis.yml
  mlflow/R/mlflow/DESCRIPTION
Labels: rn/none

#2267 Updated version to 1.5.1.dev0
  mlflow/R/mlflow/DESCRIPTION
  mlflow/java/client/pom.xml
  mlflow/java/pom.xml
  mlflow/java/scoring/pom.xml
  mlflow/version.py
Labels: LGTM

#2291 Increase stale bot timeouts
  .github/stale.yml
Labels: rn/none

#2281 Removing the URL that contains password for the log message.
  mlflow/store/db/utils.py
Labels: rn/none

#2286 Add autodetection of job environments to Java client
  mlflow/java/client/src/main/java/org/mlflow/tracking/utils/DatabricksContext.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/utils/MlflowTagConstants.java
  mlflow/java/client/src/test/java/org/mlflow/tracking/utils/DatabricksContextTest.java
Labels: rn/feature

#2289 Escape % in db_url
  mlflow/store/db/utils.py
  tests/store/db/test_utils.py
Labels: rn/bug-fix

#2258 Regenerate R docs with up-to-date version of roxygen2
  docs/source/R-api.rst
  mlflow/R/mlflow/DESCRIPTION
  mlflow/R/mlflow/man/mlflow_end_run.Rd
  mlflow/R/mlflow/man/mlflow_get_experiment.Rd
  mlflow/R/mlflow/man/mlflow_list_experiments.Rd
  mlflow/R/mlflow/man/mlflow_list_run_infos.Rd
  mlflow/R/mlflow/man/mlflow_load_model.Rd
  mlflow/R/mlflow/man/mlflow_log_artifact.Rd
  mlflow/R/mlflow/man/mlflow_log_batch.Rd
  mlflow/R/mlflow/man/mlflow_log_metric.Rd
  mlflow/R/mlflow/man/mlflow_rfunc_serve.Rd
  mlflow/R/mlflow/man/mlflow_run.Rd
  mlflow/R/mlflow/man/mlflow_save_model.Rd
  mlflow/R/mlflow/man/mlflow_search_runs.Rd
  mlflow/R/mlflow/man/mlflow_server.Rd
  mlflow/R/mlflow/man/mlflow_set_experiment.Rd
  mlflow/R/mlflow/man/mlflow_set_experiment_tag.Rd
  mlflow/R/mlflow/man/mlflow_start_run.Rd
Labels: rn/documentation

#2272 Add autodetection of job environments to R client
  mlflow/R/mlflow/R/databricks-utils.R
  mlflow/R/mlflow/tests/testthat/test-databricks-utils.R
Labels: rn/feature

#2249 Add REPL-aware listener for Spark datasource autologging
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/DatasourceAttributeExtractor.scala
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/ExceptionUtils.scala
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/MlflowAutologEventPublisher.scala
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/ReflectionUtils.scala
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/ReplAwareSparkDataSourceListener.scala
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/SparkDataSourceListener.scala
  mlflow/java/spark/src/test/scala/org/mlflow/spark/autologging/ReflectionUtilsSuite.scala
  mlflow/java/spark/src/test/scala/org/mlflow/spark/autologging/SparkAutologgingIntegrationSuite.scala
Labels: rn/none

#2244 Fix XGBoost and LightGBM flavor tests
  tests/lightgbm/test_lightgbm_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none

#2270 Document MLflow plugin system
  docs/source/_static/images/quickstart-ui-screenshot.png
  docs/source/index.rst
  docs/source/plugins.rst
  docs/source/tutorials-and-examples/index.rst
  mlflow/tracking/context/abstract_context.py
  tests/resources/mlflow-test-plugin/setup.py
Labels: rn/documentation

#2313 Adds an example of querying for the best model
  docs/source/search-syntax.rst
Labels: rn/documentation

#2259 Documentation: Add help file for R package
  docs/build-rdoc.sh
  docs/source/R-api.rst
  mlflow/R/mlflow/R/mlflow-package.R
  mlflow/R/mlflow/man-roxygen/roxlate-model-uri.R
  mlflow/R/mlflow/man/mlflow-package.Rd
  mlflow/R/mlflow/man/mlflow_load_model.Rd
  mlflow/R/mlflow/man/mlflow_rfunc_serve.Rd
Labels: rn/documentation

#2251 New runs table column view
  mlflow/server/js/package-lock.json
  mlflow/server/js/package.json
  mlflow/server/js/src/common/components/SearchTree.js
  mlflow/server/js/src/common/components/SearchTree.test.js
  mlflow/server/js/src/common/components/ag-grid/RunsTableCustomHeader.js
  mlflow/server/js/src/common/components/ag-grid/RunsTableCustomHeader.test.js
  mlflow/server/js/src/common/utils.js
  mlflow/server/js/src/components/ExperimentRunsTableCompactView.js
  mlflow/server/js/src/components/ExperimentRunsTableMultiColumnView2.js
  mlflow/server/js/src/components/ExperimentRunsTableMultiColumnView2.test.js
  mlflow/server/js/src/components/ExperimentView.css
  mlflow/server/js/src/components/ExperimentView.js
  mlflow/server/js/src/components/ExperimentView.test.js
  mlflow/server/js/src/components/ExperimentViewUtil.js
  mlflow/server/js/src/components/LoadMoreBar.js
  mlflow/server/js/src/components/LoadMoreBar.test.js
  mlflow/server/js/src/components/RunsTableColumnSelectionDropdown.js
  mlflow/server/js/src/components/RunsTableColumnSelectionDropdown.test.js
  mlflow/server/js/src/components/Spinner.css
  mlflow/server/js/src/sdk/MlflowLocalStorageMessages.js
  mlflow/server/js/src/utils/Utils.js
Labels: rn/feature

#2332 Removing cd from nightly script
  travis/stage-python3.sh
Labels: rn/none

#2293 Add feature importance plot to LightGBM auto logging
  mlflow/lightgbm.py
  tests/lightgbm/test_lightgbm_autolog.py
Labels: rn/none

#2269 Add testing for most examples
  examples/hyperparam/conda.yaml
  examples/hyperparam/search_hyperopt.py
  examples/keras/train.py
  examples/pytorch/conda.yaml
  mlflow/projects/__init__.py
  tests/examples/test_examples.py
  travis/stage-python2-nightly.sh
Labels: rn/none

#2314 Unpin Pillow and update torchvision
  tests/pytorch/test_pytorch_model_export.py
  travis/large-requirements.txt
  travis/run-large-python-tests.sh
Labels: rn/none

#2355 Bump versions to 1.6
  mlflow/java/client/pom.xml
  mlflow/java/pom.xml
  mlflow/java/scoring/pom.xml
  mlflow/java/spark/pom.xml
Labels: rn/none

#2308 [ML-9117] Java API - Model Registry API Download Models Implementation
  mlflow/java/client/pom.xml
  mlflow/java/client/src/main/java/org/mlflow/api/proto/ModelRegistry.java
  mlflow/java/client/src/main/java/org/mlflow/artifacts/CliBasedArtifactRepository.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowClient.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowHttpCaller.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowProtobufMapper.java
  mlflow/java/client/src/test/java/org/mlflow/tracking/MlflowClientTest.java
  mlflow/java/client/src/test/java/org/mlflow/tracking/ModelRegistryMlflowClientTest.java
  mlflow/java/client/src/test/java/org/mlflow/tracking/TestClientProvider.java
Labels: rn/feature

#2364 Use Java source, not Scala
  mlflow/java/scoring/pom.xml
Labels: rn/none

#2370 Update test requirement
  travis/large-requirements.txt
Labels: LGTM, rn/none
