Repository mlflow/mlflow, pull requests merged in 2020-12, with the labels that each got.

#3754 [XGBoost autologging test] Stringify `fname` in `xgboost.DMatrix.save_binary`
  tests/xgboost/test_xgboost_autolog.py
Labels: area/build, rn/none

#3575 Fix bug related with bad alignment of history entries when "initial_epoch" is different from zero.
  mlflow/keras.py
  mlflow/tensorflow.py
  tests/keras_autolog/test_keras_autolog.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/tensorflow_autolog/test_tensorflow_autolog.py
Labels: area/tracking, rn/bug-fix

#3756 include run_id to `create_run` tracking event callback
  mlflow/R/mlflow/R/tracking-runs.R
  mlflow/R/mlflow/tests/testthat/test-tracking-runs.R
Labels: language/r

#3765 support nested-run in mlflow R client
  mlflow/R/mlflow/R/tracking-globals.R
  mlflow/R/mlflow/R/tracking-runs.R
  mlflow/R/mlflow/man/mlflow_start_run.Rd
  mlflow/R/mlflow/tests/testthat/test-tracking-runs.R
Labels: area/tracking, language/r, rn/feature

#3771 Fix CircleCI error
  .circleci/config.yml
Labels: area/build, rn/none

#3760 Fix errors in examples tests
  examples/pytorch/BertNewsClassification/conda.yaml
  examples/pytorch/conda.yaml
Labels: area/build, rn/none

#3723 Extend use of BatchMetricsLogger to all autologging integrations
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/pytorch/_pytorch_autolog.py
  mlflow/tensorflow.py
  mlflow/utils/autologging_utils.py
  mlflow/xgboost.py
  tests/fastai/test_fastai_autolog.py
  tests/gluon_autolog/test_gluon_autolog.py
  tests/keras_autolog/test_keras_autolog.py
  tests/lightgbm/test_lightgbm_autolog.py
  tests/pytorch/test_pytorch_autolog.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/utils/test_autologging_utils.py
  tests/xgboost/test_xgboost_autolog.py
Labels: area/tracking, rn/none

#3768 Make run_id an optional parameter for python client
  mlflow/store/db_migrations/versions/a8c4a736bde6_allow_nulls_for_run_id.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/dbmodels/models.py
  mlflow/store/model_registry/rest_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/client.py
  tests/resources/db/latest_schema.sql
  tests/store/model_registry/test_rest_store.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/tracking/_model_registry/test_model_registry_client.py
  tests/tracking/test_client.py
Labels: area/model-registry, rn/feature

#3304 Add support for statsmodels flavor
  conftest.py
  dev/extra-ml-requirements.txt
  dev/run-python-flavor-tests.sh
  docs/source/models.rst
  docs/source/python_api/mlflow.statsmodels.rst
  docs/source/tracking.rst
  docs/source/tutorials-and-examples/index.rst
  examples/statsmodels/MLproject
  examples/statsmodels/README.md
  examples/statsmodels/conda.yaml
  examples/statsmodels/train.py
  mlflow/__init__.py
  mlflow/models/__init__.py
  mlflow/statsmodels.py
  mlflow/tracking/fluent.py
  tests/examples/test_examples.py
  tests/statsmodels/model_fixtures.py
  tests/statsmodels/test_statsmodels_autolog.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: area/docs, area/examples, area/models, rn/feature

#3776 Unpin sphinx to fix pip-20.3 issue in circleci build
  .circleci/config.yml
  docs/source/conf.py
Labels: area/build, rn/none

#3731 Cross version tests for MLflow Models / autologging integrations
  .github/workflows/README.md
  .github/workflows/cross-version-tests.yml
  .github/workflows/sklearn.yml
  dev/set_matrix.py
  ml-package-versions.yml
  mlflow/keras.py
  tests/keras/test_keras_model_export.py
Labels: area/build, rn/none

#3794 Add a badge for the cross version tests
  README.rst
Labels: area/build, rn/none

#3784 retry sqlalchemy create engine
  mlflow/db.py
  mlflow/store/db/utils.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/db/test_utils.py
Labels: area/sqlalchemy, rn/feature

#3786 Unpin mxnet
  dev/extra-ml-requirements.txt
  tests/gluon/test_gluon_model_export.py
  tests/gluon_autolog/test_gluon_autolog.py
Labels: area/build, rn/none

#3753 PyTorch model snippets
  docs/source/_static/images/pytorch_lightening_autolog.png
  docs/source/_static/images/pytorch_logged_models.png
  mlflow/pytorch/__init__.py
Labels: area/docs, rn/none

#3809 [HOT FIX] Fix an optimizer name issue in pytorch-lightning 1.1.0.
  tests/pytorch/test_pytorch_autolog.py
Labels: area/build, rn/none

#3800 [HOT FIX] skip `test` job if matrix ends up being empty in cross version tests
  .github/workflows/cross-version-tests.yml
  dev/set_matrix.py
Labels: area/build, rn/none

#3807 Allow using post releases in the cross version tests
  .github/workflows/cross-version-tests.yml
  dev/set_matrix.py
Labels: area/build

#3682 Introduce utilities for autologging error tolerance / safety
  mlflow/utils/autologging_utils.py
  tests/autologging/test_autologging_safety_unit.py
  tests/autologging/test_autologging_utils.py
Labels: area/tracking, rn/none

#3822 reject bool metric value
  mlflow/utils/validation.py
  tests/utils/test_validation.py
Labels: area/tracking, rn/bug-fix

#3798 Update schema enforcement
  docs/source/models.rst
  mlflow/pyfunc/__init__.py
  mlflow/types/utils.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
Labels: area/scoring

#3825 Fix `AttributeError: 'Dataset' object has no attribute 'value'` in h5py < 3.0.0
  tests/keras/test_keras_model_export.py
Labels: area/models, rn/none

#3826 Add gluon to the cross version tests
  ml-package-versions.yml
  mlflow/gluon.py
  tests/gluon/test_gluon_model_export.py
  tests/gluon_autolog/test_gluon_autolog.py
Labels: area/build, rn/none

#3828 Fix invalid metric error in statsmodels tests
  mlflow/statsmodels.py
  mlflow/utils/validation.py
  tests/utils/test_validation.py
Labels: area/build, rn/none

#3815 Add autologging safety utils to several autologging integrations
  mlflow/keras.py
  mlflow/sklearn/__init__.py
  mlflow/tracking/fluent.py
  mlflow/utils/autologging_utils.py
  mlflow/xgboost.py
  tests/autologging/__init__.py
  tests/autologging/fixtures.py
  tests/autologging/test_autologging_safety_integration.py
  tests/autologging/test_autologging_safety_unit.py
  tests/autologging/test_autologging_utils.py
  tests/conftest.py
  tests/fastai/test_fastai_autolog.py
  tests/sklearn/test_sklearn_autolog.py
Labels: area/tracking, rn/none

#3837 Change javier affiliation in R
  mlflow/R/mlflow/DESCRIPTION
Labels: language/r, rn/none

#3844 Fix ONNX and TF test failures
  dev/extra-ml-requirements.txt
  mlflow/spark.py
  tests/onnx/test_onnx_model_export.py
  tests/resources/onnx/generate_onnx_models.py
  tests/resources/onnx/sklearn_model.onnx
  tests/resources/onnx/tf_model_multiple_inputs_float32.onnx
  tests/resources/onnx/tf_model_multiple_inputs_float64.onnx
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/tensorflow_autolog/test_tensorflow_autolog.py
Labels: area/models, area/tracking, rn/none

#3833 Add autologging safety utils to LightGBM integration
  mlflow/lightgbm.py
  tests/autologging/test_autologging_safety_integration.py
Labels: area/models, rn/none

#3853 Autologging: Fix bug where metrics are not logged for single-epoch tf.keras training sessions
  mlflow/tensorflow.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
Labels: area/tracking, rn/bug-fix

#3854 Add autologging safety utils to gluon
  mlflow/gluon.py
  tests/autologging/test_autologging_safety_integration.py
Labels: area/models, rn/none

#3847 Set tags on autologged runs for easy identification (and add tags to start_run)
  mlflow/sklearn/__init__.py
  mlflow/tracking/fluent.py
  mlflow/utils/autologging_utils.py
  mlflow/utils/mlflow_tags.py
  tests/autologging/test_autologging_safety_unit.py
  tests/sklearn/test_sklearn_autolog.py
  tests/tracking/fluent/test_fluent.py
Labels: area/tracking, rn/feature

#3855 Add autologging safety utils to pytorch integration
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_pytorch_autolog.py
  mlflow/utils/autologging_utils.py
  pylintrc
  tests/autologging/test_autologging_safety_integration.py
  tests/autologging/test_autologging_safety_unit.py
Labels: rn/none

#3850 API code snippets for fastai model
  docs/source/_static/images/fastai_autolog.png
  mlflow/fastai.py
Labels: area/docs, area/models, rn/none

#3851 Mutual exclusivity for autologged runs
  mlflow/keras.py
  mlflow/sklearn/__init__.py
  mlflow/tracking/fluent.py
  mlflow/utils/autologging_utils.py
  mlflow/xgboost.py
  tests/autologging/test_autologging_safety_integration.py
  tests/autologging/test_autologging_safety_unit.py
Labels: area/tracking

#3864 Fixes sqlalchemy schema failures in master
  dev/small-requirements.txt
  tests/resources/db/latest_schema.sql
Labels: area/sqlalchemy

#3861 Add autologging safety utils to tensorflow
  mlflow/tensorflow.py
Labels: area/models, rn/none

#3859 Add autologging safety utils to statsmodels & Fast.ai
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/pytorch/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/tracking/fluent.py
  mlflow/xgboost.py
  tests/autologging/fixtures.py
  tests/autologging/test_autologging_safety_integration.py
  tests/conftest.py
  tests/statsmodels/test_statsmodels_autolog.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: area/tracking, rn/bug-fix

#3845 Run tensorflow & keras autologging tests faster
  tests/keras_autolog/test_keras_autolog.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/tensorflow_autolog/test_tensorflow_autolog.py
Labels: area/build, rn/none

#3869 Add `exclusive` flag to remaining relevant autologging integrations
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/lightgbm.py
  mlflow/pytorch/__init__.py
  mlflow/statsmodels.py
  mlflow/tensorflow.py
  tests/autologging/test_autologging_safety_integration.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: area/tracking, rn/feature

#3878 Fix formatting / stack trace level for missing value schema inference
  mlflow/types/utils.py
Labels: area/models, rn/none

#3877 Cleanups for TF autologging
  mlflow/tensorflow.py
Labels: area/tracking, rn/none

#3882 [DOC FIX] remove `run_id` in `log_image` and `log_figure`
  mlflow/tracking/fluent.py
Labels: area/docs, rn/none

#3870 Add developer instrumentation hooks / APIs for autologging (AutologgingEventLogger)
  mlflow/tracking/fluent.py
  mlflow/utils/autologging_utils.py
  tests/autologging/test_autologging_safety_unit.py
  tests/autologging/test_autologging_utils.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: area/tracking, rn/none

#3874 Add info-level logs when new fluent runs are during autologging
  mlflow/tensorflow.py
  mlflow/utils/autologging_utils.py
  tests/autologging/test_autologging_safety_unit.py
Labels: area/tracking, rn/none

#3880 Pin the version of mlflow in the databricks job to the same version as that of the client
  mlflow/projects/databricks.py
  mlflow/version.py
  tests/test_version.py
Labels: area/projects, integrations/databricks, rn/bug-fix

#3883 Autologging: Add context to MLflow warnings raised by patch implementations
  mlflow/utils/autologging_utils.py
  tests/autologging/test_autologging_safety_unit.py
Labels: area/tracking, rn/none

#3887 [CROSS VERSION TEST] Fix regular expression to capture flavor name from changed files
  dev/set_matrix.py
Labels: area/build, rn/none

#3889 Fix BertNewsClassification & Gluon examples
  .github/workflows/examples.yml
  examples/gluon/train.py
  examples/pytorch/BertNewsClassification/conda.yaml
Labels: area/examples, rn/none

#3808 Add support for np array-based tensors for Keras, Pytorch and TF flavors
  mlflow/keras.py
  mlflow/pyfunc/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/tensorflow.py
  tests/keras/test_pyfunc_model_works_with_all_input_types.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/pytorch/test_pytorch_model_export.py
  tests/tensorflow/test_tensorflow2_model_export.py
  tests/tensorflow/test_tensorflow_model_export.py
Labels: area/models, area/scoring

#3896 Include scikit-learn as a pip dependency in conda_env.yml
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
Labels: area/build, rn/none

#3891 [MINOR FIX] Separate anaconda compatibility tests
  .github/workflows/master.yml
Labels: area/build, rn/none

#3901 Fix pytorch-lightning optimizer name issue
  mlflow/pytorch/_pytorch_autolog.py
  tests/pytorch/test_pytorch_autolog.py
Labels: area/build, rn/none

#3687 [MLflowSkinny] Base changes for MLflow Skinny Client
  .github/workflows/master.yml
  dev/install-common-deps.sh
  dev/run-python-skinny-tests.sh
  dev/skinny-requirements.txt
  mlflow/cli.py
  mlflow/db.py
  mlflow/deployments/cli.py
  mlflow/models/cli.py
  mlflow/models/flavor_backend_registry.py
  mlflow/projects/__init__.py
  mlflow/projects/backend/local.py
  mlflow/pyfunc/scoring_server/__init__.py
  mlflow/server/handlers.py
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/tracking/file_store.py
  mlflow/utils/proto_json_utils.py
  setup.py
  tests/projects/test_projects_cli.py
  tests/projects/utils.py
  tests/test_cli.py
  tests/test_runs.py
  tests/test_skinny.py
Labels: area/tracking

#3899 Cleanup `dev-requirements.txt` and use it when building docs in CircleCI
  .circleci/config.yml
  dev-requirements.txt
  docs/build-rdoc.sh
Labels: area/build, rn/none

#3902 Build R docs to find issues/errors in advance before the release process
  .circleci/config.yml
  .circleci/dump-r-dependencies.R
Labels: area/docs, rn/none

#3900 Run `master.yml` workflow on release branches
  .github/workflows/master.yml
Labels: area/build, rn/none

#3905 Cherry-pick #3899 & #3900 into branch-1.13
  .circleci/config.yml
  .github/workflows/master.yml
  dev-requirements.txt
  docs/build-rdoc.sh
Labels: area/build, rn/none

#3913 Autologging: Fix exclusive session management
  mlflow/tensorflow.py
  mlflow/utils/autologging_utils.py
  tests/autologging/test_autologging_safety_unit.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
Labels: area/tracking, rn/bug-fix

#3914 TensorFlow autologging: Fix longstanding race condition
  mlflow/tensorflow.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
Labels: area/tracking, rn/bug-fix

#3917 Forward spark autologging configs from mlflow.autolog()
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: area/tracking, rn/bug-fix

#3922 Resolve bug in logging call during mlflow.azureml.deploy
  mlflow/azureml/__init__.py
Labels: integrations/azure, rn/bug-fix

#3918 Adding mlflow-algorithmia
  docs/source/plugins.rst
Labels: area/docs

#3928 Fix UI crashes / inconsistencies related to path normalization
  mlflow/server/js/src/common/utils/Utils.js
  mlflow/server/js/src/common/utils/Utils.test.js
  mlflow/server/js/src/experiment-tracking/components/ArtifactView.js
  mlflow/server/js/src/experiment-tracking/components/ArtifactView.test.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.test.js
Labels: area/uiux, rn/bug-fix

#3929 Fix bug causing `transition_model_version_stage` to fail archiving existing model versions when uncanonical stage name is passed
  mlflow/store/model_registry/sqlalchemy_store.py
  tests/store/model_registry/test_sqlalchemy_store.py
Labels: area/model-registry, rn/none
