Repository mlflow/mlflow, pull requests merged in 2020-08, with the labels that each got.

#3119 [V2] Enable registering models to a Databricks workspace from outside
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/dbfs_artifact_repo.py
  mlflow/store/artifact/models_artifact_repo.py
  mlflow/store/artifact/runs_artifact_repo.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/artifact_utils.py
  mlflow/tracking/client.py
  mlflow/utils/uri.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/store/artifact/test_dbfs_artifact_repo.py
  tests/store/artifact/test_dbfs_rest_artifact_repo.py
  tests/store/artifact/test_models_artifact_repo.py
  tests/store/artifact/test_runs_artifact_repo.py
  tests/tracking/test_artifact_utils.py
  tests/tracking/test_client.py
  tests/utils/test_uri.py
Labels: area/model-registry, rn/feature

#3209 [Model Version Schema] Add Schema Section in Model Version and Compare Model Version View
  mlflow/server/js/src/common/utils/ArtifactUtils.js
  mlflow/server/js/src/common/utils/Utils.js
  mlflow/server/js/src/experiment-tracking/components/RunView.css
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactHtmlView.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactMapView.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactPdfView.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactTextView.js
  mlflow/server/js/src/model-registry/actions.js
  mlflow/server/js/src/model-registry/components/CompareModelVersionsPage.js
  mlflow/server/js/src/model-registry/components/CompareModelVersionsView.js
  mlflow/server/js/src/model-registry/components/CompareModelVersionsView.test.js
  mlflow/server/js/src/model-registry/components/ModelVersionPage.js
  mlflow/server/js/src/model-registry/components/ModelVersionView.js
  mlflow/server/js/src/model-registry/components/ModelVersionView.test.js
  mlflow/server/js/src/model-registry/reducers.js
  mlflow/server/js/src/model-registry/reducers.test.js
Labels: area/model-registry, area/uiux, rn/feature

#2947 fix(dbfs_artifact_repo.py): use params for GET call instead of json
  mlflow/projects/databricks.py
  mlflow/store/artifact/dbfs_artifact_repo.py
Labels: area/artifacts, area/projects, integrations/databricks, needs review, rn/bug-fix

#3062 Handle 400 error in Models page
  mlflow/server/js/src/common/components/Error404View.js
  mlflow/server/js/src/common/components/ErrorView.js
  mlflow/server/js/src/common/components/ErrorView.test.js
  mlflow/server/js/src/experiment-tracking/components/PageNotFoundView.js
  mlflow/server/js/src/experiment-tracking/components/RunNotFoundView.js
  mlflow/server/js/src/model-registry/components/ModelListPage.js
  mlflow/server/js/src/model-registry/components/ModelPage.js
  mlflow/server/js/src/model-registry/components/ModelVersionPage.js
Labels: area/model-registry, area/uiux, rn/bug-fix

#3204 Fix directory doubling issue for `FTPArtifactRepository.log_artifacts`
  mlflow/store/artifact/ftp_artifact_repo.py
  tests/store/artifact/test_ftp_artifact_repo.py
Labels: area/artifacts, rn/bug-fix

#3210 Fix error due to names with absolute path returned by ftp.nlst
  mlflow/store/artifact/ftp_artifact_repo.py
  tests/store/artifact/test_ftp_artifact_repo.py
Labels: area/artifacts, rn/bug-fix

#3183 Add Pagination to list_run_infos
  mlflow/__init__.py
  mlflow/store/tracking/abstract_store.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  tests/store/tracking/test_abstract_store.py
  tests/tracking/test_fluent.py
Labels: area/tracking, rn/feature

#3238 Retry small requirements installation when it fails
  travis/install-common-deps.sh
Labels: area/build, rn/none

#3220 MlflowClient should pass in the tracking uri info to ArtifactRepository
  .gitignore
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/artifact_utils.py
  mlflow/tracking/client.py
  tests/tracking/_tracking_service/test_tracking_service_client.py
Labels: area/artifacts, area/tracking, rn/bug-fix

#3232 [Multiworkspace-Registry] use colon instead of slash to delimit scope and prefix
  mlflow/tracking/client.py
  mlflow/utils/databricks_utils.py
  mlflow/utils/uri.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/store/artifact/test_runs_artifact_repo.py
  tests/tracking/_tracking_service/test_tracking_service_client.py
  tests/tracking/test_artifact_utils.py
  tests/utils/test_databricks_utils.py
  tests/utils/test_uri.py
Labels: area/model-registry, rn/none

#3242 Fix bug with list_artifacts in gcp
  mlflow/store/artifact/gcs_artifact_repo.py
Labels: area/models, rn/bug-fix

#3244 Fix flaky test_search_attrs
  tests/store/tracking/test_sqlalchemy_store.py
Labels: area/build, rn/bug-fix

#3245 Remove conda environments after examples tests to prevent docker test from failing due to no-space-left error
  .github/workflows/examples.yml
  Dockerfile
Labels: area/build, rn/none

#3231 Trigger auto-labeling action when new issue or PR has been opened
  .github/workflows/labeling.yml
Labels: area/build, rn/none

#3259 Fix command line parameters (remove -P in front of URI)
  examples/hyperparam/README.rst
Labels: rn/documentation

#3253 Rename `travis` folder to `dev`
  .circleci/config.yml
  .dockerignore
  .github/workflows/examples.yml
  .github/workflows/master.yml
  dev/install-common-deps.sh
  dev/large-requirements.txt
  dev/lint-requirements.txt
  dev/run-large-python-tests.sh
  dev/run-python-flavor-tests.sh
  dev/run-python-sagemaker-tests.sh
  dev/run-python-tf-tests.sh
  dev/run-small-python-tests.sh
  dev/small-requirements.txt
  dev/test-anaconda-compatibility-in-docker.sh
  dev/test-anaconda-compatibility.sh
  dev/test-spark-autologging.sh
  mlflow/R/mlflow/.Rbuildignore
  mlflow/R/mlflow/.run-tests.R
  test-requirements.txt
Labels: area/build, rn/none

#3256 Fix error when cleaning up conda environments
  .github/workflows/examples.yml
  dev/remove-conda-envs.sh
Labels: area/build, rn/none

#3168 Fix a bug where artifact locations become malformed when using an SFTP file store in Windows
  mlflow/store/artifact/sftp_artifact_repo.py
Labels: area/artifacts, area/windows, rn/bug-fix

#3264 Add `--showlocals` option for pytest to make it easier to debug test failures
  pytest.ini
Labels: area/build, rn/none

#3194 Added fastai, spacy, and autologging sections for #issue 3137
  docs/source/models.rst
  docs/source/tracking.rst
  docs/source/tutorials-and-examples/index.rst
  mlflow/fastai.py
  mlflow/models/__init__.py
  mlflow/spacy.py
Labels: area/docs, area/models, rn/documentation

#3266 Decrease epochs for hyperparam example tests
  .github/workflows/examples.yml
  tests/examples/test_examples.py
Labels: area/build, rn/none

#3267 Use `MNIST_TINY` in fastai example
  examples/fastai/train.py
Labels: area/build, area/examples, rn/none

#3163 Fix bug in Azure artifact repo's list_artifact
  mlflow/store/artifact/azure_blob_artifact_repo.py
  tests/store/artifact/test_azure_blob_artifact_repo.py
Labels: area/artifacts, rn/none

#3255 Fix bug in GCS artifact repo's list_artifact
  mlflow/store/artifact/gcs_artifact_repo.py
  tests/store/artifact/test_gcs_artifact_repo.py
Labels: area/artifacts, rn/none

#3260 Fix pylint issues
  lint.sh
  tests/examples/test_examples.py
  tests/fastai/test_fastai_autolog.py
  tests/fastai/test_fastai_model_export.py
  tests/gluon/test_gluon_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/keras/test_keras_model_export.py
  tests/keras_autolog/test_keras_autolog.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/onnx/test_onnx_model_export.py
  tests/pytorch/test_pytorch_model_export.py
  tests/resources/example_docker_project/scripts/docker_tracking_test.py
  tests/resources/example_project/check_conda_env.py
  tests/resources/example_project_no_spec/check_conda_env.py
  tests/spark/test_spark_model_export.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/tensorflow/test_tensorflow2_model_export.py
  tests/tensorflow/test_tensorflow_model_export.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/tensorflow_autolog/test_tensorflow_autolog.py
  tests/tracking/_model_registry/test_model_registry_client.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
  tests/xgboost/test_xgboost_model_export.py
Labels: area/build, rn/none

#3250 Update AzureML model deploy
  docs/source/models.rst
Labels: integrations/azure, rn/documentation

#3085 support xgboost for R
  .github/workflows/master.yml
  docs/source/R-api.rst
  docs/source/models.rst
  mlflow/R/mlflow/.run-tests.R
  mlflow/R/mlflow/DESCRIPTION
  mlflow/R/mlflow/NAMESPACE
  mlflow/R/mlflow/R/install.R
  mlflow/R/mlflow/R/model-python.R
  mlflow/R/mlflow/R/model-xgboost.R
  mlflow/R/mlflow/R/tracking-experiments.R
  mlflow/R/mlflow/man/install_mlflow.Rd
  mlflow/R/mlflow/man/mlflow-package.Rd
  mlflow/R/mlflow/man/mlflow_rename_experiment.Rd
  mlflow/R/mlflow/man/mlflow_save_model.Rd
  mlflow/R/mlflow/man/reexports.Rd
  mlflow/R/mlflow/tests/testthat.R
  mlflow/R/mlflow/tests/testthat/test-model-xgboost.R
Labels: rn/feature

#3263 Add `SklearnTrainigSession` for sklearn autologging
  mlflow/sklearn.py
  tests/sklearn/test_sklearn_training_session.py
Labels: area/models, rn/none

#3265 Suppress spark download progress
  dev/test-spark-autologging.sh
Labels: area/build, rn/none

#3279 Enable `import-init` option for pylint
  mlflow/__init__.py
  mlflow/azureml/__init__.py
  mlflow/azureml/cli.py
  mlflow/cli.py
  mlflow/data.py
  mlflow/deployments/base.py
  mlflow/deployments/interface.py
  mlflow/gluon.py
  mlflow/mleap.py
  mlflow/models/__init__.py
  mlflow/onnx.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/backend.py
  mlflow/pyfunc/scoring_server/__init__.py
  mlflow/sagemaker/__init__.py
  mlflow/spark.py
  mlflow/store/artifact/artifact_repo.py
  mlflow/store/tracking/abstract_store.py
  mlflow/tensorflow.py
  mlflow/tracking/__init__.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
  mlflow/utils/__init__.py
  pylintrc
  tests/sagemaker/mock/__init__.py
Labels: area/build, rn/none

#3288 Expose model flavors under `mlflow` so users don't have to import them
  .github/workflows/master.yml
  mlflow/__init__.py
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/tensorflow.py
  tests/test_flavors.py
  tests/tracking/test_fluent.py
Labels: area/models, rn/none

#3295 Adding logging and scoring
  examples/pytorch/mnist_tensorboard_artifact.py
Labels: area/examples, rn/none

#3225 Fix a bug where order_by parsing allows duplicate fields
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: area/model-registry, rn/none

#3046 [docs] Make clear that the client is the one logging artifacts to the artifact store
  docs/source/tracking.rst
Labels: area/artifacts, area/docs, rn/documentation

#3271 Add ability to add description in model/version create APIs
  mlflow/java/client/src/main/java/org/mlflow/api/proto/ModelRegistry.java
  mlflow/protos/model_registry.proto
  mlflow/protos/model_registry_pb2.py
  mlflow/server/handlers.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/rest_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/client.py
  tests/store/model_registry/test_rest_store.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/tracking/_model_registry/test_model_registry_client.py
  tests/tracking/test_client.py
Labels: area/model-registry, rn/feature

#3275 Update slack invite link
  README.rst
Labels: rn/none

#3289 Store wheel as artifact on push to master branch
  .github/workflows/build-wheel.yml
Labels: area/build, rn/none

#3314 Add slack badge
  README.rst
Labels: rn/none

#3287 Add autologging for scikit-learn
  .github/workflows/sklearn.yml
  dev/large-requirements.txt
  dev/small-requirements.txt
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
  tests/sklearn/test_sklearn_autolog.py
Labels: area/models, area/tracking, rn/feature

#3328 Delete Databricks project information from docs
  docs/source/projects.rst
Labels: area/docs, rn/documentation

#3330 Support remote Databricks model registries in `mlflow.<flavor>.load_model`
  mlflow/store/artifact/models_artifact_repo.py
  tests/store/artifact/test_models_artifact_repo.py
Labels: area/artifacts, area/model-registry, rn/feature

#3338 Handle spaces in Databricks profile URIs
  mlflow/utils/uri.py
  tests/utils/test_uri.py
Labels: area/artifacts, area/model-registry, area/tracking, rn/none

#3323 Scikit-learn autologging specializations for parameter search
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
  tests/sklearn/test_sklearn_autolog.py
Labels: area/models, rn/feature

#3344 Add temporary workaround for error in R check
  mlflow/R/mlflow/.run-tests.R
Labels: area/build, rn/none

#3341 Remove dependency on SQLAlchemy to import mlflow
  mlflow/utils/search_utils.py
Labels: rn/none

#3348 Fix Azure Blob storage import issue with 12.4.0
  mlflow/store/artifact/azure_blob_artifact_repo.py
Labels: area/artifacts, rn/bug-fix

#3322 Added filter_string descripition and code snippet; address issue #3173
  mlflow/tracking/client.py
Labels: area/docs

#3326 Log model signature and input example in sklearn autologging
  mlflow/sklearn/__init__.py
  tests/sklearn/test_sklearn_autolog.py
  tests/sklearn/test_sklearn_model_export.py
Labels: area/models, rn/none

#3347 Fix for parameter parsing when parameter contains '='
  mlflow/cli.py
  tests/projects/test_projects_cli.py
Labels: area/projects, rn/bug-fix

#3350 Run sklearn autologging check against dev version for forwards compatibility
  .github/workflows/sklearn.yml
Labels: area/build, rn/none

#3357 Use debug log for generally less relevant piece of info
  mlflow/spark.py
Labels: area/models, rn/none

#3358 Add signature and input example to parameter search best estimator
  mlflow/sklearn/__init__.py
  tests/sklearn/test_sklearn_autolog.py
Labels: area/models, rn/feature

#3359 Fix example code in docstring of `mllfow.sklearn.autolog`
  mlflow/sklearn/__init__.py
Labels: area/models, rn/none

#3324 Add examples for sklearn autologging
  .github/workflows/sklearn.yml
  examples/sklearn_autolog/README.md
  examples/sklearn_autolog/grid_search_cv.py
  examples/sklearn_autolog/linear_regression.py
  examples/sklearn_autolog/pipeline.py
  examples/sklearn_autolog/utils.py
  tests/examples/test_examples.py
Labels: area/examples, rn/none
