Repository mlflow/mlflow, pull requests merged in 2021-08, with the labels that each got.

#4633 PyTorch Examples - PTL 1.4.0 Fixes
  examples/pytorch/AxHyperOptimizationPTL/conda.yaml
  examples/pytorch/BertNewsClassification/conda.yaml
  examples/pytorch/IterativePruning/conda.yaml
  examples/pytorch/IterativePruning/iterative_prune_mnist.py
  examples/pytorch/MNIST/conda.yaml
Labels: area/examples, rn/none

#4634 Use `concurrency` in `MLflow tests` workflow to cancel redundant runs
  .github/workflows/cross-version-tests.yml
  .github/workflows/master.yml
Labels: rn/none

#4639 Fix PyTorch Lightning autologging dev version tests
  tests/pytorch/iris.py
Labels: area/tracking, enable-dev-tests, rn/none

#4640 Remove IPython test-only dependency
  dev/extra-ml-requirements.txt
Labels: area/build, rn/none

#4632 Add `_get_pinned_requirement` to accurately obtain package versions
  mlflow/catboost.py
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/h2o.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/onnx.py
  mlflow/paddle/__init__.py
  mlflow/pyfunc/model.py
  mlflow/pytorch/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/spacy.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/tensorflow.py
  mlflow/utils/requirements_utils.py
  mlflow/xgboost.py
  tests/utils/test_requirements_utils.py
Labels: enable-dev-tests, rn/none

#4635 Update tracking.rst
  docs/source/tracking.rst
Labels: area/tracking, rn/none

#4637 Add serving tests to all flavors
  tests/catboost/test_catboost_model_export.py
  tests/fastai/test_fastai_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/shap/test_log.py
  tests/sklearn/test_sklearn_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none

#4610 Docker utils - Raise error if docker build has failed
  mlflow/models/docker_utils.py
Labels: area/docker, area/models, rn/bug-fix

#4573 Make it possible to access artifacts in public S3 artifact buckets
  mlflow/store/artifact/s3_artifact_repo.py
Labels: area/artifacts, rn/none

#4638 sklearn eval metric autologging: patch `metrics.SCORERS`
  mlflow/sklearn/__init__.py
  tests/sklearn/test_sklearn_autolog.py
Labels: area/tracking, rn/feature

#4644 Redundant word in error message
  mlflow/pyfunc/__init__.py
Labels: rn/none

#4627 Introdcue `_is_available_on_pypi` and use it to determine whether we need to use `--no-conda` for `pyfunc_serve_and_score_model`
  .github/workflows/master.yml
  mlflow/ml-package-versions.yml
  tests/catboost/test_catboost_model_export.py
  tests/gluon/test_gluon_model_export.py
  tests/helper_functions.py
  tests/keras/test_keras_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/onnx/test_onnx_model_export.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spacy/test_spacy_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/tensorflow/test_tensorflow2_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: enable-dev-tests, rn/none

#4631 Fix some issues in gorillar patch
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/autologging_utils/safety.py
  mlflow/utils/gorilla.py
  tests/autologging/test_autologging_safety_unit.py
  tests/sklearn/test_sklearn_autolog.py
  tests/utils/test_gorilla.py
Labels: area/tracking, rn/bug-fix

#4649 Remove tests marked by `pytest.mark.release`
  conftest.py
  tests/h2o/test_h2o_model_export.py
  tests/keras/test_keras_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sklearn/test_sklearn_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tensorflow/test_tensorflow2_model_export.py
  tests/tensorflow/test_tensorflow_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none

#4641 Remove experimental decorators and notes from MLflow tracking APIs
  mlflow/java/client/src/main/java/org/mlflow/artifacts/CliBasedArtifactRepository.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowClient.java
  mlflow/store/artifact/artifact_repo.py
  mlflow/store/tracking/abstract_store.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: integrations/sagemaker, rn/none

#4651 Notify DCO check failure
  .github/workflows/notify-dco-failure.js
  .github/workflows/notify-dco-failure.yml
Labels: rn/none

#4653 Remove redundant `conda_env` in tests for `log_model` and `save_model`
  tests/catboost/test_catboost_model_export.py
  tests/fastai/test_fastai_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/keras/test_keras_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/onnx/test_onnx_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spacy/test_spacy_model_export.py
  tests/spark/test_spark_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/tensorflow/test_tensorflow2_model_export.py
  tests/tensorflow/test_tensorflow_model_export.py
  tests/utils/test_environment.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none

#4663 Fixed SQLAlchemy backend not releasing DB connections by using a cache of SQLAlchemy Engines instead of creating new ones each time.
  mlflow/store/db/utils.py
  mlflow/store/tracking/sqlalchemy_store.py
  tests/tracking/_tracking_service/test_utils.py
Labels: rn/bug-fix, area/tracking, area/sqlalchemy

#4648 Remove experimental decorators and notes from MLflow Models, Model Registry, deployment APIs
  docs/source/rest-api.rst
  mlflow/catboost.py
  mlflow/deployments/__init__.py
  mlflow/deployments/base.py
  mlflow/deployments/interface.py
  mlflow/entities/model_registry/model_version.py
  mlflow/entities/model_registry/registered_model.py
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/h2o.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/mleap.py
  mlflow/models/cli.py
  mlflow/models/model.py
  mlflow/onnx.py
  mlflow/paddle/__init__.py
  mlflow/pyfunc/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/shap.py
  mlflow/sklearn/__init__.py
  mlflow/spacy.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/tensorflow.py
  mlflow/xgboost.py
Labels: rn/none

#4666 Fix `build_doc_r` job by replacing `install_github` with `install_git`
  docs/build-rdoc.sh
Labels: rn/none

#4518 Implement auto pip dependency inference for `mlflow.*.log_model`
  dev/run-python-flavor-tests.sh
  dev/run-python-tf-tests.sh
  dev/test-anaconda-compatibility-in-docker.sh
  mlflow/catboost.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/ml-package-versions.yml
  mlflow/models/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/tensorflow.py
  mlflow/utils/_capture_modules.py
  mlflow/utils/environment.py
  mlflow/utils/requirements_utils.py
  mlflow/xgboost.py
  setup.py
  tests/catboost/test_catboost_model_export.py
  tests/conftest.py
  tests/helper_functions.py
  tests/keras/test_keras_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sklearn/test_sklearn_model_export.py
  tests/tensorflow/test_tensorflow2_model_export.py
  tests/tensorflow/test_tensorflow_model_export.py
  tests/utils/test_requirements_utils.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/feature, enable-dev-tests

#4672 Pyspark CrossValidator autolog "std metrics"
  mlflow/pyspark/ml/__init__.py
  tests/spark_autologging/ml/test_pyspark_ml_autologging.py
Labels: rn/feature, area/tracking, enable-dev-tests

#4675 Replace `lambda` in `_get_databricks_rest_store` with `functools.partial`
  mlflow/tracking/_model_registry/utils.py
  mlflow/tracking/_tracking_service/utils.py
  tests/tracking/_model_registry/test_utils.py
  tests/tracking/_tracking_service/test_utils.py
Labels: rn/none

#4628 make sklearn autologging supporting delegated methods in estimators
  mlflow/sklearn/__init__.py
  mlflow/utils/autologging_utils/safety.py
  tests/autologging/test_autologging_safety_unit.py
  tests/autologging/test_autologging_utils.py
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/feature, enable-dev-tests

#4683 Fix DCO failure notification message
  .github/workflows/notify-dco-failure.js
Labels: rn/none

#4611 Scoring Server - Added support for wrapped prediction responses
  mlflow/pyfunc/scoring_server/__init__.py
Labels: rn/feature, area/scoring

#4684 Remove unused `tmpdir` in `test_store_object_can_be_serialized_by_pickle`
  tests/tracking/_model_registry/test_utils.py
Labels: rn/none

#4691 Temporarily pin tensorflow and keras
  dev/extra-ml-requirements.txt
Labels: rn/none, area/build

#4682 Always use `importlib_metadata.version` when obtaining package version to prevent version mismatch between `importlib_metadata.version` and `<package>.__version__`
  mlflow/utils/requirements_utils.py
  tests/helper_functions.py
  tests/spark/test_spark_model_export.py
  tests/utils/test_requirements_utils.py
Labels: rn/none

#4690 Fix incorrect URI usage in docstring for client.create_model_version
  mlflow/tracking/client.py
Labels: area/docs, rn/none, area/model-registry

#4646 Update docs for AzureML deployment plugin
  docs/source/plugins.rst
  mlflow/azureml/__init__.py
  mlflow/azureml/cli.py
Labels: area/docs, rn/documentation, integrations/azure

#4686 Pyspark ml autolog post-training metric
  mlflow/ml-package-versions.yml
  mlflow/pyspark/ml/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/utils/autologging_utils/__init__.py
  tests/autologging/test_autologging_utils.py
  tests/sklearn/test_sklearn_autolog.py
  tests/spark_autologging/ml/test_pyspark_ml_autologging.py
Labels: rn/feature, area/tracking, enable-dev-tests

#4699 Replace keras models in tests with sklearn models to decrease maintenance burden
  dev/run-python-tf-tests.sh
  tests/autologging/test_autologging_behaviors_integration.py
  tests/azureml/test_deploy.py
  tests/azureml/test_image_creation.py
  tests/spark_autologging/datasource/test_spark_datasource_autologging_crossframework.py
Labels: rn/none

#4662 [PART 2] Implement auto pip dependency inference for mlflow.*.log_model
  dev/run-python-flavor-tests.sh
  dev/run-python-skinny-tests.sh
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/h2o.py
  mlflow/onnx.py
  mlflow/paddle/__init__.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
  mlflow/shap.py
  mlflow/spacy.py
  mlflow/statsmodels.py
  mlflow/tracking/artifact_utils.py
  mlflow/utils/_capture_modules.py
  mlflow/utils/requirements_utils.py
  tests/fastai/test_fastai_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/helper_functions.py
  tests/models/test_cli.py
  tests/onnx/test_onnx_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/spacy/test_spacy_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/tracking/test_rest_tracking.py
  tests/utils/test_requirements_utils.py
Labels: rn/none

#4700 Fix example for `pip_requirements`
  examples/pip_requirements/pip_requirements.py
Labels: rn/none

#4701 Update the `build_doc_r` job to stabilize build
  .circleci/config.yml
Labels: rn/none

#4625 Update param docs of `log_model` and `save_model` for auto dependency inference
  docs/source/python_api/mlflow.pyfunc.rst
  mlflow/catboost.py
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/h2o.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/onnx.py
  mlflow/paddle/__init__.py
  mlflow/pyfunc/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/shap.py
  mlflow/sklearn/__init__.py
  mlflow/spacy.py
  mlflow/statsmodels.py
  mlflow/tensorflow.py
  mlflow/utils/docstring_utils.py
  mlflow/xgboost.py
Labels: rn/none

#4674 Update tracking.rst
  docs/source/tracking.rst
Labels: rn/none

#4527 Added more Model Registry Functions to R
  docs/source/R-api.rst
  mlflow/R/mlflow/NAMESPACE
  mlflow/R/mlflow/R/model-registry.R
  mlflow/R/mlflow/R/tracking-rest.R
  mlflow/R/mlflow/man/mlflow_create_model_version.Rd
  mlflow/R/mlflow/man/mlflow_delete_model_version.Rd
  mlflow/R/mlflow/man/mlflow_get_latest_versions.Rd
  mlflow/R/mlflow/man/mlflow_get_model_version.Rd
  mlflow/R/mlflow/man/mlflow_get_registered_model.Rd
  mlflow/R/mlflow/man/mlflow_list_registered_models.Rd
  mlflow/R/mlflow/man/mlflow_rename_registered_model.Rd
  mlflow/R/mlflow/man/mlflow_transition_model_version_stage.Rd
  mlflow/R/mlflow/man/mlflow_update_model_version.Rd
  mlflow/R/mlflow/man/mlflow_update_registered_model.Rd
  mlflow/R/mlflow/tests/testthat/test-model-registry.R
Labels: area/docs, language/r, rn/feature, area/model-registry

#4705 Introduce `log_post_training_metrics` to enable/disable evaluation metrics autologging
  mlflow/pyspark/ml/__init__.py
  mlflow/sklearn/__init__.py
  tests/sklearn/test_sklearn_autolog.py
  tests/spark_autologging/ml/test_pyspark_ml_autologging.py
Labels: rn/none

#4609 Scoring Server - Correctly handle request content-type with charset parameter
  mlflow/pyfunc/scoring_server/__init__.py
  tests/pyfunc/test_scoring_server.py
Labels: rn/bug-fix, area/scoring

#4706 Rename `disable_prevent_infer_pip_requirements_fallback` with `allow_infer_pip_requirements_fallback`
  tests/catboost/test_catboost_model_export.py
  tests/conftest.py
  tests/helper_functions.py
  tests/keras/test_keras_model_export.py
  tests/models/test_cli.py
  tests/spacy/test_spacy_model_export.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#4708 Do not call `get_default_pip_requirements` if `pip_requirements` is specified
  mlflow/catboost.py
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/h2o.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/onnx.py
  mlflow/paddle/__init__.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
  mlflow/pytorch/__init__.py
  mlflow/shap.py
  mlflow/sklearn/__init__.py
  mlflow/spacy.py
  mlflow/statsmodels.py
  mlflow/tensorflow.py
  mlflow/xgboost.py
Labels: rn/none

#4707 Strictly test `pip_requirements` behavior
  tests/catboost/test_catboost_model_export.py
  tests/fastai/test_fastai_model_export.py
  tests/gluon/test_gluon_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/helper_functions.py
  tests/keras/test_keras_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/onnx/test_onnx_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pytorch/test_pytorch_model_export.py
  tests/shap/test_log.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spacy/test_spacy_model_export.py
  tests/spark/test_spark_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/tensorflow/test_tensorflow2_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none

#4694 Allow manually running cross version tests against fork repositories
  .github/workflows/cross-version-tests.yml
Labels: rn/none

#4679 Fix lint/test errors caused by keras 2.6.0
  dev/extra-ml-requirements.txt
  mlflow/keras.py
  mlflow/ml-package-versions.yml
  mlflow/tensorflow.py
  tests/keras/test_keras_model_export.py
  tests/keras/test_pyfunc_model_works_with_all_input_types.py
  tests/keras_autolog/test_keras_autolog.py
  tests/pyfunc/test_scoring_server.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
Labels: rn/none

#4710 Remove `fit_generator` tests in keras and tensorflow flavors
  tests/keras_autolog/test_keras_autolog.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/tensorflow_autolog/test_tensorflow_autolog.py
Labels: rn/none

#4709 Fix keras early stopping logging logic
  mlflow/keras.py
  mlflow/tensorflow.py
  tests/keras_autolog/test_keras_autolog.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/tensorflow_autolog/test_tensorflow_autolog.py
Labels: rn/bug-fix

#4703 Remove `tensorflow` job in `master.yml` and move tests for spark datasource autologging in `cross-version-tests.yml`
  .github/workflows/cross-version-tests.yml
  .github/workflows/master.yml
  dev/run-python-tf-tests.sh
  dev/setup-spark-datasource-autologging.sh
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#4719 Make MlflowClient serializable, cache utils._get_store
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/_model_registry/registry.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/_tracking_service/registry.py
  tests/spark/test_spark_model_export.py
  tests/test_cli.py
  tests/tracking/_model_registry/test_utils.py
  tests/tracking/_tracking_service/test_utils.py
  tests/tracking/test_client.py
Labels: rn/none, area/tracking

#4724 Fix & simplify pytorch / statsmodels logging tests
  tests/pytorch/test_pytorch_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
Labels: rn/none, area/build

#4723 Revert `h2o`, `shap`, and `paddle` in `dev/run-python-flavor-tests.sh`
  dev/run-python-flavor-tests.sh
  tests/h2o/test_h2o_model_export.py
  tests/paddle/test_paddle_model_export.py
Labels: rn/none

#4688 Specifying docker-build command platform for Apple Sillicon computers
  mlflow/models/docker_utils.py
Labels: rn/none

#4717 Support distributed pytorch lightning autologging execution
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_pytorch_autolog.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/autologging_utils/client.py
  tests/pytorch/test_pytorch_autolog.py
Labels: rn/feature, area/tracking

#4725 Fix `examples/keras/train.py`
  examples/keras/train.py
Labels: rn/none

#4722 Run `tests/models` in a separate job and decrease CI execution time by 9 ~ 10 minutes
  .github/workflows/master.yml
  dev/run-python-flavor-tests.sh
Labels: rn/none, area/build

#4716 Add deprecation warnings for tensorflow < 2 and keras < 2.3
  mlflow/keras.py
  mlflow/tensorflow.py
  tests/keras/test_keras_model_export.py
  tests/tensorflow/test_tensorflow2_model_export.py
Labels: rn/breaking-change

#4729 Set `nextPageToken` to `null` when switching experiments
  mlflow/server/js/src/experiment-tracking/components/ExperimentPage.js
Labels: rn/bug-fix

#4730 Enable `concurrency` in workflows containing time-consuming jobs to decrease redundant runs as much as possible
  .github/workflows/examples.yml
  .github/workflows/release-note-category.yml
  .github/workflows/test-package-build.yml
Labels: rn/none

#4698 Fixed the Model Registry plugin registration failures
  mlflow/tracking/_model_registry/utils.py
  tests/tracking/test_client.py
Labels: rn/none

#4711 Added retry logic for recoverable errors in the HTTP request method
  mlflow/azure/client.py
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/dbfs_artifact_repo.py
  mlflow/utils/rest_utils.py
  tests/projects/test_databricks.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/store/tracking/test_rest_store.py
  tests/utils/test_rest_utils.py
Labels: rn/none

#4728 Deprecate fast.ai V1 support
  mlflow/fastai.py
  mlflow/utils/annotations.py
Labels: rn/documentation, area/models, area/tracking

#4734 Fix mlflow platform argument
  mlflow/models/docker_utils.py
Labels: rn/none, integrations/sagemaker, area/build

#4748 Use getfullargspec when fetching lightgbm args
  mlflow/lightgbm.py
  mlflow/xgboost.py
Labels: rn/none, area/tracking, enable-dev-tests

#4756 Use componentDidMount for fetching column defs in experiment table
  mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js
Labels: rn/none, area/uiux

#4757 Run keras tests against `keras-nightly`
  .github/workflows/cross-version-tests.yml
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests
