Repository mlflow/mlflow, pull requests merged in 2021-02, with the labels that each got.

#3921 Update type of input json data to `StringIO`
  mlflow/pyfunc/scoring_server/__init__.py
  tests/pyfunc/test_scoring_server.py
Labels: area/scoring, rn/bug-fix

#4028 GCP artifact upload / download support
  mlflow/java/client/src/main/java/com/databricks/api/proto/mlflow/DatabricksArtifacts.java
  mlflow/protos/databricks_artifacts.proto
  mlflow/protos/databricks_artifacts_pb2.py
  mlflow/store/artifact/databricks_artifact_repo.py
  tests/store/artifact/test_databricks_artifact_repo.py
Labels: area/artifacts, rn/none

#4038 Fix spacy 3.0 issue
  examples/spacy/train.py
  ml-package-versions.yml
  tests/spacy/test_spacy_model_export.py
Labels: rn/none

#4051 Fix `Unsupported class file major version 55` issue in spark tests
  .github/workflows/master.yml
Labels: rn/none

#4052 Fix R cache key to refresh package cache when ubuntu version is updated
  .github/workflows/master.yml
Labels: rn/none

#4013 Deprecate Python 3.5
  mlflow/__init__.py
Labels: rn/breaking-change

#4054 Install mlflow-test-plugin without dependencies
  .github/workflows/master.yml
  dev/install-common-deps.sh
  dev/skinny-requirements.txt
  dev/small-requirements.txt
Labels: rn/none

#3773 Updating unit tets for PyTorch
  tests/pytorch/iris.py
  tests/pytorch/iris_data_module.py
  tests/pytorch/test_pytorch_autolog.py
  tests/pytorch/test_pytorch_model_export.py
Labels: area/examples, rn/none

#3819 support MLeap for R
  .circleci/config.yml
  .github/workflows/master.yml
  docs/source/R-api.rst
  docs/source/models.rst
  mlflow/R/mlflow/.create-test-env.R
  mlflow/R/mlflow/DESCRIPTION
  mlflow/R/mlflow/NAMESPACE
  mlflow/R/mlflow/R/model-mleap.R
  mlflow/R/mlflow/R/model-utils.R
  mlflow/R/mlflow/man/mlflow-package.Rd
  mlflow/R/mlflow/man/mlflow_save_model.Rd
  mlflow/R/mlflow/tests/testthat/test-model-mleap.R
Labels: area/models, language/r, rn/feature

#4063 use Java version 8 because of Spark-related dependencies at runtime
  .github/workflows/master.yml
Labels: rn/none

#4043 Use SavedModel format by default in mlflow.keras.log_model
  .github/workflows/cross-version-tests.yml
  mlflow/keras.py
  tests/keras/test_keras_model_export.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
Labels: area/models, rn/feature

#4050 Don't log autolog success message if disable=True
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: area/tracking, rn/none

#4042 Update client to pass request headers created by all RequestHeaderProviders
  mlflow/tracking/request_header/registry.py
  mlflow/utils/rest_utils.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/request_header_provider.py
  tests/resources/mlflow-test-plugin/setup.py
  tests/tracking/context/test_registry.py
  tests/tracking/request_header/test_registry.py
  tests/utils/test_rest_utils.py
Labels: area/tracking, rn/feature

#4016 Remove branch name spacifiers in cross-version-tests config
  ml-package-versions.yml
Labels: rn/none

#4059 Run `twine check` to ensure python package `long_description` is correct
  .github/workflows/test-package-build.yml
  setup.py
Labels: rn/none

#4070 Updated Plugin documentation
  docs/source/plugins.rst
  mlflow/tracking/request_header/databricks_request_header_provider.py
Labels: area/docs, rn/none

#4049 Eedeleon/release skinny client
  README_SKINNY.rst
  setup.py
Labels: rn/feature

#4067 Restore `wheel-name` in `test-package-build.yml`
  .github/workflows/test-package-build.yml
Labels: rn/none

#4003 [bug-fix] add missing client parameter in `mlflow_restore_run()`
  mlflow/R/mlflow/R/tracking-runs.R
  mlflow/R/mlflow/tests/testthat/test-tracking-runs.R
Labels: area/tracking, language/r, rn/bug-fix

#4044 Drop azure-blob-storage dependency from MLflow client
  dev/small-requirements.txt
  mlflow/azure/__init__.py
  mlflow/azure/client.py
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/utils/file_utils.py
  mlflow/utils/rest_utils.py
  setup.py
  tests/store/artifact/test_databricks_artifact_repo.py
Labels: area/artifacts, rn/none

#4069 #4055 allow infer_signature to read pandas ExtensionDtype
  mlflow/types/utils.py
  tests/models/test_model_input_examples.py
Labels: area/models, rn/bug-fix

#4086 Don't clear spark autologging tags between runs
  mlflow/_spark_autologging.py
  mlflow/spark.py
  tests/spark_autologging/test_spark_datasource_autologging.py
Labels: area/tracking, rn/breaking-change

#4079 Add multi-dimensional array (aka Tensor) support
  docs/source/conf.py
  mlflow/models/utils.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/scoring_server/__init__.py
  mlflow/types/__init__.py
  mlflow/types/schema.py
  mlflow/types/utils.py
  mlflow/utils/proto_json_utils.py
  tests/gluon/test_gluon_model_export.py
  tests/lightgbm/test_lightgbm_autolog.py
  tests/models/test_model_input_examples.py
  tests/models/test_signature.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/pyfunc/test_scoring_server.py
  tests/sklearn/test_sklearn_autolog.py
  tests/sklearn/test_sklearn_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/types/test_schema.py
  tests/utils/test_proto_json_utils.py
  tests/xgboost/test_xgboost_autolog.py
Labels: area/models, rn/breaking-change

#4084 Support tensor-based model signatures in schema enforcement
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/sklearn/test_sklearn_autolog.py
Labels: area/scoring, rn/feature, rn/none

#4091 Use `20newsgroups` dataset instead of `AG_NEWS` in `best_classification.py` + Fix no-disk-space-left issue in `test_examples.py`
  examples/pytorch/BertNewsClassification/MLproject
  examples/pytorch/BertNewsClassification/bert_classification.py
  tests/examples/test_examples.py
Labels: rn/none

#4096 Fix broken pytorch-lightning tests for dev in cross version tests
  tests/pytorch/iris.py
  tests/pytorch/test_pytorch_autolog.py
Labels: rn/none

#4068 Update documentation with support for tensor-input types
  docs/source/models.rst
  mlflow/gluon.py
  mlflow/keras.py
  mlflow/onnx.py
  mlflow/pyfunc/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/tensorflow.py
Labels: rn/documentation

#4093 Fix for universal autolog configs overriding integration-specific configs
  mlflow/tracking/fluent.py
  mlflow/utils/autologging_utils.py
  tests/autologging/test_autologging_safety_integration.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: area/tracking, rn/breaking-change, rn/bug-fix

#4090 Captured Tensorboard log in autologging for tf.Estimator APIs
  mlflow/tensorflow.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/tensorflow_autolog/test_tensorflow_autolog.py
Labels: area/artifacts, rn/none

#4100 Don't allow schema creation for multiple unnamed TensorSpecs
  mlflow/types/schema.py
  tests/models/test_signature.py
  tests/types/test_schema.py
Labels: rn/none

#4099 Improve method to parse tf-serving json
  mlflow/models/utils.py
  mlflow/pyfunc/scoring_server/__init__.py
  mlflow/utils/proto_json_utils.py
  tests/utils/test_proto_json_utils.py
Labels: area/scoring, rn/bug-fix

#4041 Added tensor input support for ONNX and gluon flavors.
  mlflow/gluon.py
  mlflow/onnx.py
  tests/gluon/test_gluon_model_export.py
  tests/onnx/test_onnx_model_export.py
Labels: area/scoring, rn/feature

#4101 Fix `enable_test_mode_by_default_for_autologging_integrations`
  tests/conftest.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/none

#4097 Add monkey patching for old and new tf.Estimator classes
  mlflow/tensorflow.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
Labels: area/tracking, rn/bug-fix

#4110 Support parsing df input with tensor schema and parsing tensor input with df schema.
  mlflow/utils/proto_json_utils.py
  tests/utils/test_proto_json_utils.py
Labels: area/scoring, rn/none

#4102 [Follow-up for #4101] Fix broken autologging example tests
  mlflow/fastai.py
  mlflow/models/model.py
  mlflow/tensorflow.py
  mlflow/tracking/fluent.py
  mlflow/utils/autologging_utils.py
  tests/fastai/test_fastai_autolog.py
Labels: rn/none

#3989 SHAP Explainer Logging Integration
  docs/source/python_api/mlflow.shap.rst
  examples/shap/explainer_logging.py
  mlflow/shap.py
  tests/examples/test_examples.py
  tests/shap/test_log.py
Labels: area/examples, area/models, rn/feature

#4108 Check DBFS FUSE availability before using it in mlflow.spark APIs
  mlflow/spark.py
Labels: area/models, rn/none

#4117 Cherry picks for 1.14.0 release
  mlflow/spark.py
Labels: rn/none

#4118 Avoid duplicate metrics logging in pytorch-lightning 1.2.0
  mlflow/pytorch/_pytorch_autolog.py
  tests/pytorch/iris.py
  tests/pytorch/iris_data_module.py
  tests/pytorch/test_pytorch_autolog.py
Labels: rn/none

#4130 Merge tensorflow-1.x and tensorflow-2.x in cross version tests config
  ml-package-versions.yml
Labels: rn/none

#3964 [MINOR FIX] Unpin pip and try new dependency resolver introduced in 20.3
  dev/install-common-deps.sh
Labels: area/build, rn/none

#4116 Update example run command in tutorial
  docs/source/tutorials-and-examples/tutorial.rst
Labels: area/examples, rn/none

#4114 [ML-13739] Model version creation should fail if the status returned is not READY
  mlflow/entities/model_registry/model_version.py
  mlflow/tracking/_model_registry/client.py
  tests/tracking/test_client.py
Labels: area/model-registry, rn/bug-fix

#4134 Include README_skinny.rst in sdist
  .github/workflows/test-package-build.yml
  MANIFEST.in
Labels: rn/none

#4133 Run test scripts under tests/autologging
  conftest.py
  dev/run-python-flavor-tests.sh
Labels: rn/none

#4136 Set tags only when it's not none in `create_managed_run`
  mlflow/utils/autologging_utils.py
Labels: rn/none

#4138 Remove prefix argument for ModelCheckpoint
  tests/pytorch/test_pytorch_autolog.py
Labels: rn/none

#4139 Add statsmodels cross version test in CI
  ml-package-versions.yml
Labels: area/build, rn/none

#4141 Replace `IrisClassificationWithoutValidation` with `IrisClassification`
  tests/pytorch/test_pytorch_autolog.py
Labels: rn/none

#4144 Use `callbacks` instead of `checkpoint_callback` which will be remove in pytorch-lightning 1.3
  tests/pytorch/test_pytorch_autolog.py
Labels: rn/none

#4147 Fix issues in handling flexible numpy datatypes in TensorSpec
  mlflow/pyfunc/__init__.py
  mlflow/types/schema.py
  mlflow/types/utils.py
  tests/types/test_schema.py
Labels: area/models, rn/none
