Repository mlflow/mlflow, pull requests merged in 2021-03, with the labels that each got.

#4151 Cherry-pick the tensor-info bug fix into branch 1.14
  mlflow/pyfunc/__init__.py
  mlflow/types/schema.py
  mlflow/types/utils.py
  tests/types/test_schema.py
Labels: rn/none

#4152 Add CHANGELOG for 1.14.1 release
  CHANGELOG.rst
Labels: rn/none

#4029 Add example for Ray Serve deployment plugin
  docs/source/plugins.rst
  examples/ray_serve/README.md
  examples/ray_serve/input.json
  examples/ray_serve/train_model.py
  tests/examples/test_examples.py
Labels: area/examples, rn/none

#4155 Drop the autologging subsection from the pytorch section in ml-package-versions.yaml
  ml-package-versions.yml
Labels: rn/none

#4119 Disable autologging for untested library versions
  .github/workflows/cross-version-tests.yml
  dev/set_matrix.py
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/ml-package-versions.yml
  mlflow/pytorch/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/statsmodels.py
  mlflow/tensorflow.py
  mlflow/tracking/fluent.py
  mlflow/utils/annotations.py
  mlflow/utils/autologging_utils.py
  mlflow/xgboost.py
  setup.py
  tests/autologging/test_autologging_utils.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: area/tracking, rn/feature

#4157 Fix flaky `spark_install` in `.create-test-env.R`
  .github/workflows/master.yml
  mlflow/R/mlflow/.Rbuildignore
  mlflow/R/mlflow/.create-test-env.R
  mlflow/R/mlflow/.spark-version
Labels: rn/none

#4162 Use latest version of torchvision to fix MNIST download issue
  examples/pytorch/MNIST/example1/conda.yaml
  examples/pytorch/MNIST/example2/conda.yaml
  examples/pytorch/conda.yaml
Labels: rn/none

#4149 Skip logging during sanity check in pytorch autologging
  mlflow/pytorch/_pytorch_autolog.py
  tests/pytorch/test_pytorch_autolog.py
Labels: area/build, rn/none

#4160 Update documentation on preserving spark_udf column names
  docs/source/models.rst
  mlflow/pyfunc/__init__.py
Labels: rn/documentation

#4161 Add back alembic files to avoid KeyError "formatters"
  setup.py
Labels: area/sqlalchemy, rn/bug-fix

#4167 Update event loggers to reflect stderr changes, add enable / disable capabilities
  mlflow/utils/logging_utils.py
  tests/utils/test_logging_utils.py
Labels: area/tracking, rn/none

#4191 [Follow-up for #4180] Avoid using mxnet 1.8.0 & Fix no-space-left error in `test-anaconda-compatibility.sh`
  .github/workflows/master.yml
  dev/extra-ml-requirements.txt
  mlflow/db.py
  mlflow/store/db/utils.py
  mlflow/store/db_migrations/versions/39d1c3be5f05_add_is_nan_constraint_for_metrics_tables_if_necessary.py
  mlflow/store/tracking/dbmodels/models.py
  mlflow/temporary_db_migrations_for_pre_1_users/README
  mlflow/temporary_db_migrations_for_pre_1_users/__init__.py
  mlflow/temporary_db_migrations_for_pre_1_users/alembic.ini
  mlflow/temporary_db_migrations_for_pre_1_users/env.py
  mlflow/temporary_db_migrations_for_pre_1_users/script.py.mako
  mlflow/temporary_db_migrations_for_pre_1_users/versions/__init__.py
  mlflow/temporary_db_migrations_for_pre_1_users/versions/ff01da956556_ensure_unique_constraint_names.py
  tests/resources/db/latest_schema.sql
  tests/store/tracking/test_sqlalchemy_store.py
  tests/store/tracking/test_sqlalchemy_store_schema.py
  tests/tracking/_tracking_service/test_utils.py
Labels: rn/none

#4184 Refactor autologging utilities for future modularity / extensibility
  mlflow/_spark_autologging.py
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/ml-package-versions.yml
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_pytorch_autolog.py
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/tensorflow.py
  mlflow/tracking/fluent.py
  mlflow/utils/autologging/__init__.py
  mlflow/xgboost.py
  tests/autologging/fixtures.py
  tests/autologging/test_autologging_safety_integration.py
  tests/autologging/test_autologging_safety_unit.py
  tests/autologging/test_autologging_utils.py
  tests/conftest.py
  tests/fastai/test_fastai_autolog.py
  tests/gluon_autolog/test_gluon_autolog.py
  tests/keras_autolog/test_keras_autolog.py
  tests/lightgbm/test_lightgbm_autolog.py
  tests/pytorch/test_pytorch_autolog.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/tracking/fluent/test_fluent_autolog.py
  tests/xgboost/test_xgboost_autolog.py
Labels: area/tracking, rn/none

#4193 Update tested ML package versions
  mlflow/ml-package-versions.yml
Labels: rn/none

#4179 Drop python 3.5 support
  mlflow/__init__.py
  setup.py
  tests/test_no_f_strings.py
Labels: rn/breaking-change

#4195 Bug fix for TensorFlow autologging: do not mutate user-specified callbacks list
  mlflow/tensorflow.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
Labels: area/tracking, rn/bug-fix

#4017 mlflow_get_experiment() should return same tag structure as mlflow_list_experiments()
  mlflow/R/mlflow/R/tracking-experiments.R
  mlflow/R/mlflow/tests/testthat/test-tracking-experiments.R
Labels: area/tracking, language/r, rn/bug-fix

#4194 TensorFlow autologging: change every_n_iter default to 1, always log last epoch
  mlflow/tensorflow.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
Labels: area/tracking, rn/breaking-change

#4153 Move to new SHAP Serialization API
  mlflow/shap.py
  tests/shap/test_log.py
Labels: area/models, rn/breaking-change

#4200 End autologged runs when execution is interrupted (sigint)
  mlflow/utils/autologging/__init__.py
  tests/autologging/test_autologging_safety_unit.py
Labels: area/tracking, rn/bug-fix

#4203 Rename mlflow.utils.autologging to mlflow.utils.autologging_utils for backwards compatibility
  mlflow/_spark_autologging.py
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_pytorch_autolog.py
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/tensorflow.py
  mlflow/tracking/fluent.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/xgboost.py
  tests/autologging/fixtures.py
  tests/autologging/test_autologging_safety_integration.py
  tests/autologging/test_autologging_safety_unit.py
  tests/autologging/test_autologging_utils.py
  tests/conftest.py
  tests/fastai/test_fastai_autolog.py
  tests/gluon_autolog/test_gluon_autolog.py
  tests/keras_autolog/test_keras_autolog.py
  tests/lightgbm/test_lightgbm_autolog.py
  tests/pytorch/test_pytorch_autolog.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/tracking/fluent/test_fluent_autolog.py
  tests/xgboost/test_xgboost_autolog.py
Labels: area/tracking, rn/none

#4173 Add silent option for autologging integrations
  conftest.py
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/pytorch/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/tensorflow.py
  mlflow/tracking/fluent.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/autologging_utils/logging_and_warnings.py
  mlflow/xgboost.py
  tests/autologging/fixtures.py
  tests/autologging/test_autologging_behaviors_integration.py
  tests/autologging/test_autologging_behaviors_unit.py
  tests/autologging/test_autologging_safety_unit.py
  tests/autologging/test_autologging_utils.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: area/tracking, rn/feature

#4206 Add changelog for MLflow 1.15.0 release
  CHANGELOG.rst
Labels: rn/none

#4207 Pytorch - MNIST example - Dataset Download Error - Fix
  examples/pytorch/MNIST/example1/conda.yaml
  examples/pytorch/MNIST/example2/conda.yaml
  examples/pytorch/conda.yaml
Labels: area/examples, rn/none

#3885 [PyTorch] Adding Example for Ax Hyperparameter Optimization
  examples/pytorch/AxHyperOptimizationPTL/MLproject
  examples/pytorch/AxHyperOptimizationPTL/README.md
  examples/pytorch/AxHyperOptimizationPTL/__init__.py
  examples/pytorch/AxHyperOptimizationPTL/ax_hpo_mnist.py
  examples/pytorch/AxHyperOptimizationPTL/conda.yaml
  examples/pytorch/AxHyperOptimizationPTL/iris.py
  examples/pytorch/AxHyperOptimizationPTL/iris_data_module.py
  tests/examples/test_examples.py
Labels: area/examples, rn/none
