Repository mlflow/mlflow, pull requests merged in 2021-04, with the labels that each got.

#4211 Fix 1.15 migration error
  mlflow/store/db_migrations/versions/39d1c3be5f05_add_is_nan_constraint_for_metrics_tables_if_necessary.py
  mlflow/store/db_migrations/versions/c48cb773bb87_reset_default_value_for_is_nan_in_metrics_table_for_mysql.py
Labels: area/server-infra, area/sqlalchemy, rn/bug-fix

#4218 Add mlflow.sklearn.eval_and_log_metrics
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
  tests/sklearn/test_sklearn_autolog.py
Labels: area/tracking, rn/feature

#4225 Added two special cases to the Model Registry Workflow API
  docs/source/model-registry.rst
Labels: area/docs, rn/none

#2417 [FLAVOR] Add CatBoost flavor
  conftest.py
  dev/extra-ml-requirements.txt
  dev/run-python-flavor-tests.sh
  docs/source/models.rst
  docs/source/python_api/mlflow.catboost.rst
  examples/catboost/train.py
  mlflow/__init__.py
  mlflow/catboost.py
  mlflow/ml-package-versions.yml
  tests/catboost/test_catboost_model_export.py
  tests/examples/test_examples.py
Labels: area/models, rn/feature

#3866 [PyTorch] Adding example for Captum Implementation with MLflow
  examples/pytorch/CaptumExample/MLproject
  examples/pytorch/CaptumExample/README.md
  examples/pytorch/CaptumExample/Titanic_Captum_Interpret.py
  examples/pytorch/CaptumExample/conda.yaml
  tests/examples/test_examples.py
Labels: area/examples, rn/none

#4233 Set SPARK_LOCAL_IP to fix flaky spark session creation
  .github/workflows/master.yml
Labels: rn/none

#3884 [PyTorch] Adding example for Iterative pruning
  examples/pytorch/IterativePruning/MLproject
  examples/pytorch/IterativePruning/README.md
  examples/pytorch/IterativePruning/conda.yaml
  examples/pytorch/IterativePruning/iterative_prune_mnist.py
  examples/pytorch/IterativePruning/mnist.py
  examples/pytorch/MNIST/MLproject
  examples/pytorch/MNIST/README.md
  examples/pytorch/MNIST/conda.yaml
  examples/pytorch/MNIST/example1/README.md
  examples/pytorch/MNIST/example2/MLproject
  examples/pytorch/MNIST/example2/README.md
  examples/pytorch/MNIST/mnist_autolog_example.py
  mlflow/pytorch/__init__.py
  tests/examples/test_examples.py
Labels: area/examples, rn/none

#4237 Add SPARK_LOCAL_IP in cross version tests config
  .github/workflows/cross-version-tests.yml
Labels: rn/none

#4243 Separate MLeap tests and unpin pyspark
  dev/extra-ml-requirements.txt
  dev/run-python-sagemaker-tests.sh
  tests/pyfunc/test_spark.py
  tests/spark/test_mleap_model_export.py
  tests/spark/test_spark_model_export.py
Labels: rn/none

#4231 Fix autologging silent mode bugs
  mlflow/utils/autologging_utils/safety.py
  tests/autologging/test_autologging_behaviors_unit.py
Labels: area/tracking, rn/bug-fix

#4247 Add spark model export tests in cross version tests
  mlflow/ml-package-versions.yml
Labels: rn/none

#4242 Add return type annotations to key MLflow APIs
  docs/source/conf.py
  docs/source/python_api/mlflow.entities.rst
  mlflow/store/entities/__init__.py
  mlflow/store/entities/paged_list.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/_model_registry/utils.py
  mlflow/tracking/_tracking_service/utils.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: rn/none

#4253 Unpin pyspark in cross version tests for keras
  mlflow/ml-package-versions.yml
Labels: rn/none

#4254 Remove h5py from extra-ml-requirements.txt
  dev/extra-ml-requirements.txt
Labels: rn/none

#4241 Add datetime data type for MLflow model signatures
  docs/source/models.rst
  mlflow/models/signature.py
  mlflow/pyfunc/__init__.py
  mlflow/types/schema.py
  mlflow/types/utils.py
  mlflow/utils/proto_json_utils.py
  tests/models/test_signature.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/pyfunc/test_scoring_server.py
  tests/pyfunc/test_spark.py
  tests/types/test_schema.py
Labels: area/models, rn/feature

#4228 Implementation: pyspark autologging for basic estimator
  dev/run-python-flavor-tests.sh
  docs/source/python_api/mlflow.pyspark.ml.rst
  mlflow/__init__.py
  mlflow/ml-package-versions.yml
  mlflow/pyspark/__init__.py
  mlflow/pyspark/ml/__init__.py
  mlflow/pyspark/ml/log_model_allowlist.txt
  mlflow/tracking/fluent.py
  mlflow/utils/__init__.py
  mlflow/utils/autologging_utils/versioning.py
  setup.py
  tests/autologging/test_autologging_behaviors_integration.py
  tests/autologging/test_autologging_utils.py
  tests/spark_autologging/datasource/test_spark_datasource_autologging.py
  tests/spark_autologging/datasource/test_spark_datasource_autologging_crossframework.py
  tests/spark_autologging/datasource/test_spark_datasource_autologging_missing_jar.py
  tests/spark_autologging/datasource/test_spark_datasource_autologging_order.py
  tests/spark_autologging/datasource/test_spark_datasource_autologging_unit.py
  tests/spark_autologging/datasource/test_spark_disable_autologging.py
  tests/spark_autologging/ml/test_pyspark_ml_autologging.py
  tests/spark_autologging/ml/test_pyspark_ml_autologging_custom_allowlist.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: area/tracking, rn/feature

#4252 Move utility functions used in sklearn autologging to reuse them in pyspark autologging
  conftest.py
  mlflow/ml-package-versions.yml
  mlflow/pyspark/ml/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
  mlflow/utils/__init__.py
  mlflow/utils/autologging_utils/__init__.py
  tests/autologging/test_training_session.py
  tests/sklearn/test_sklearn_autolog.py
  tests/spark_autologging/ml/test_pyspark_ml_autologging.py
  tests/utils/test_utils.py
Labels: rn/none

#4264 Update Cross version tests on spark to include allowlist suite.
  mlflow/ml-package-versions.yml
Labels: area/build, rn/none

#4236 Enable spark_udf to use column names from model signature by default
  docs/source/models.rst
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_spark.py
Labels: area/scoring, rn/feature

#4255 Add argument type annotations
  docs/source/conf.py
  mlflow/tracking/_model_registry/utils.py
  mlflow/tracking/_tracking_service/utils.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: rn/none

#4274 Fix flaky test
  tests/autologging/test_autologging_behaviors_integration.py
  tests/autologging/test_autologging_safety_unit.py
  tests/conftest.py
Labels: area/build, rn/none

#4268 Separate MLeap jars in spark tests
  tests/spark/test_mleap_model_export.py
  tests/spark/test_spark_model_export.py
Labels: rn/none

#4275 Add tests to ensure database can be initialized for postgresql and mysql
  .github/workflows/master.yml
  tests/db/.dockerignore
  tests/db/Dockerfile
  tests/db/docker-compose.yml
  tests/db/log.py
Labels: rn/none

#4266 Add dev version of spark to cross version tests
  mlflow/ml-package-versions.yml
  tests/spark/test_spark_model_export.py
Labels: rn/none

#4280 Update ML package versions for 1.16.0 release
  mlflow/ml-package-versions.yml
Labels: area/build, rn/none

#4286 Chery picks for 1.16.0
  mlflow/ml-package-versions.yml
Labels: area/build, rn/none

#4263 Implementation: pyspark ML autologging for pipeline
  mlflow/pyspark/ml/__init__.py
  mlflow/pyspark/ml/log_model_allowlist.txt
  tests/spark_autologging/ml/test_pyspark_ml_autologging.py
Labels: area/tracking, rn/none

#4265 Add Pyspark ML autologging examples
  .github/workflows/examples.yml
  examples/pyspark_ml_autologging/README.md
  examples/pyspark_ml_autologging/logistic_regression.py
  examples/pyspark_ml_autologging/one_vs_rest.py
  tests/examples/test_examples.py
Labels: area/examples, rn/none

#4284 Add package and version to cross-versions-tests matrix
  dev/set_matrix.py
Labels: rn/none

#4276 Fix: When top level call autologging failed, nested calls autologging are still enabled
  mlflow/utils/autologging_utils/safety.py
  tests/autologging/fixtures.py
  tests/autologging/test_autologging_safety_unit.py
Labels: area/tracking, rn/none

#4297 Fix run deletion message on GDPR-enabled platforms
  mlflow/server/js/src/experiment-tracking/components/modals/DeleteExperimentModal.js
  mlflow/server/js/src/experiment-tracking/components/modals/DeleteRunModal.js
Labels: area/tracking, area/uiux, rn/none

#4287 Cache pyspark wheel bulilt from source
  .github/workflows/cross-version-tests.yml
  dev/set_matrix.py
  mlflow/ml-package-versions.yml
Labels: rn/none

#3599 Add pyproject.toml to simplify black command
  CONTRIBUTING.rst
  MANIFEST.in
  lint.sh
  pyproject.toml
Labels: area/build, rn/none

#4302 Fix a leaked run error in `test_pytorch_test_metrics_logged`
  tests/pytorch/test_pytorch_autolog.py
Labels: rn/none

#4289 Add pipeline example for pyspark ML autologging
  examples/pyspark_ml_autologging/pipeline.py
  tests/examples/test_examples.py
Labels: rn/none
