Repository mlflow/mlflow, pull requests merged in 2021-06, with the labels that each got.

#4402 Use batch credential fetch APIs for Databricks artifact logging
  mlflow/java/client/src/main/java/com/databricks/api/proto/mlflow/DatabricksArtifacts.java
  mlflow/protos/databricks_artifacts.proto
  mlflow/protos/databricks_artifacts_pb2.py
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/utils/__init__.py
  tests/store/artifact/test_databricks_artifact_repo.py
Labels: rn/none

#4417 Add Dockerfile to simplify building protobuf files
  .github/workflows/master.yml
  CONTRIBUTING.rst
  dev/Dockerfile.protos
  dev/Dockerfile.protos.dockerignore
Labels: rn/none

#4418 Fix dev sklearn build failure due to `scikit-learn requires numpy >= 1.14.6`
  .github/workflows/cross-version-tests.yml
  mlflow/ml-package-versions.yml
Labels: rn/none

#4409 Logging additional pip dependencies in requirements.txt
  mlflow/catboost.py
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/h2o.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/onnx.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
  mlflow/shap.py
  mlflow/sklearn/__init__.py
  mlflow/spacy.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/tensorflow.py
  mlflow/utils/environment.py
  mlflow/xgboost.py
  tests/catboost/test_catboost_model_export.py
  tests/fastai/test_fastai_model_export.py
  tests/gluon/test_gluon_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/helper_functions.py
  tests/keras/test_keras_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/onnx/test_onnx_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spacy/test_spacy_model_export.py
  tests/spark/test_spark_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/tensorflow/test_tensorflow2_model_export.py
  tests/tensorflow/test_tensorflow_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: area/tracking, rn/feature

#4424 Revert "Fix dev sklearn build failure due to scikit-learn requires numpy >= 1.14.6"
  mlflow/ml-package-versions.yml
Labels: rn/none

#4422 PyTorch log additional pip requirements in `requirements.txt`
  mlflow/pytorch/__init__.py
  tests/pytorch/test_pytorch_model_export.py
Labels: area/tracking, rn/feature

#4047 change default value of verify to None
  mlflow/store/artifact/s3_artifact_repo.py
  tests/store/artifact/test_s3_artifact_repo.py
Labels: area/artifacts, rn/bug-fix

#4421 Log databricks runtime in MLmodel
  mlflow/models/model.py
  mlflow/utils/databricks_utils.py
  tests/models/test_model.py
  tests/tracking/test_client.py
Labels: area/models, area/tracking, rn/feature

#4406 Integrate PaddlePaddle into MLflow
  conftest.py
  dev/extra-ml-requirements.txt
  dev/run-python-flavor-tests.sh
  docs/source/python_api/mlflow.paddle.rst
  examples/paddle/MLproject
  examples/paddle/conda.yaml
  examples/paddle/train.py
  mlflow/__init__.py
  mlflow/models/__init__.py
  mlflow/paddle/__init__.py
  tests/paddle/test_paddle_model_export.py
Labels: area/models, rn/feature

#4159 [bug-fix] Fix KubernetesSubmittedRun.get_status() (#3962)
  mlflow/projects/kubernetes.py
Labels: area/docker, area/projects, rn/bug-fix

#4440 Bump `actions/setup-java` to fix flakiness
  .github/workflows/cross-version-tests.yml
  .github/workflows/master.yml
Labels: area/build, rn/none

#4428 Docs for logging pip requirements and databricks runtime
  docs/source/models.rst
  docs/source/tracking.rst
Labels: area/docs, rn/none

#4446 fix: Remove deprecated Variable API for tensor
  examples/pytorch/mnist_tensorboard_artifact.py
Labels: area/examples, rn/none

#4435 [ML-15604] Remove defaults conda channel in MLflow examples
  examples/fastai/conda.yaml
  examples/flower_classifier/conda.yaml
  examples/flower_classifier/image_pyfunc.py
  examples/h2o/conda.yaml
  examples/hyperparam/conda.yaml
  examples/lightgbm/conda.yaml
  examples/multistep_workflow/conda.yaml
  examples/prophet/conda.yaml
  examples/prophet/train.ipynb
  examples/prophet/train.py
  examples/pytorch/AxHyperOptimizationPTL/conda.yaml
  examples/pytorch/BertNewsClassification/conda.yaml
  examples/pytorch/CaptumExample/conda.yaml
  examples/pytorch/IterativePruning/conda.yaml
  examples/pytorch/MNIST/conda.yaml
  examples/pytorch/MNIST/example2/conda.yaml
  examples/pytorch/conda.yaml
  examples/pytorch/torchscript/IrisClassification/conda.yaml
  examples/pytorch/torchscript/MNIST/conda.yaml
  examples/sklearn_elasticnet_diabetes/linux/conda.yaml
  examples/sklearn_elasticnet_diabetes/osx/conda.yaml
  examples/sklearn_elasticnet_wine/conda.yaml
  examples/sklearn_logistic_regression/conda.yaml
  examples/spacy/conda.yaml
  examples/statsmodels/conda.yaml
  examples/tensorflow/tf1/conda.yaml
  examples/tensorflow/tf2/conda.yaml
  examples/xgboost/conda.yaml
  mlflow/pytorch/__init__.py
Labels: area/examples, rn/none

#4449 Support dev version of pyspark in autologging in Databricks
  mlflow/utils/autologging_utils/versioning.py
  tests/autologging/test_autologging_utils.py
Labels: rn/none

#4444 Make sure `import mlflow` doesn't import ML packages
  conftest.py
  dev/run-python-flavor-tests.sh
  docs/source/conf.py
  mlflow/mleap.py
  mlflow/models/signature.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
  tests/test_mlflow_lazily_imports_ml_packages.py
Labels: rn/none

#4319 Fix loading of TensorFlow SavedModel format (#4223)
  mlflow/tensorflow.py
  tests/tensorflow/test_tensorflow2_model_export.py
Labels: area/models, area/scoring, rn/bug-fix

#4431 [ML-15298] `mlflow.shap.log_explanation` creates extraneous run if autologging enabled
  mlflow/shap.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/autologging_utils/safety.py
  tests/autologging/test_autologging_utils.py
  tests/shap/test_log.py
Labels: area/tracking, rn/none

#4453 Show HEAD commit hash when installing package from GitHub in cross version tests
  mlflow/ml-package-versions.yml
Labels: area/build, rn/none

#4403 Fix bug that removes any strings like "git" from source uri.
  mlflow/server/js/src/common/utils/Utils.js
  mlflow/server/js/src/common/utils/Utils.test.js
Labels: area/server-infra, rn/bug-fix

#3881 list experiments page token
  mlflow/__init__.py
  mlflow/experiments.py
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
  mlflow/server/handlers.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  mlflow/utils/validation.py
  tests/store/tracking/test_abstract_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_rest_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/fluent/test_fluent.py
  tests/tracking/test_rest_tracking.py
  tests/tracking/test_tracking.py
  tests/utils/test_validation.py
Labels: area/tracking, rn/feature

#4464 Remove duplicate test execution for spark autologging
  dev/test-spark-autologging.sh
Labels: rn/none

#4439 [PaddlePaddle] support paddle model built by high level api
  examples/paddle/train_high_level_api.py
  examples/paddle/train_low_level_api.py
  mlflow/paddle/__init__.py
  tests/paddle/test_paddle_model_export.py
Labels: area/models, rn/feature

#4459 Fix failure in pytorch `pickle_module` test
  tests/pytorch/test_pytorch_model_export.py
Labels: area/build, rn/none

#4461 Specify `--upgrade` when installing `torch_nightly` to force an overwrite
  mlflow/ml-package-versions.yml
Labels: area/build, rn/none

#4405 Revert patched code when disabling autolog
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/autologging_utils/safety.py
  mlflow/utils/gorilla.py
  tests/autologging/test_autologging_behaviors_integration.py
  tests/autologging/test_autologging_utils.py
Labels: area/tracking, rn/bug-fix

#4467 Autologging: Set parent run tags using CreateRun API request, rather than separate batch logging request
  mlflow/utils/autologging_utils/safety.py
Labels: area/tracking, rn/none

#4471 Update file_utils to support writing to YAML file without sorting.
  mlflow/utils/file_utils.py
  setup.py
  tests/utils/test_file_utils.py
Labels: area/tracking, rn/none

#4416 Efficient batching / parallel client utility for autologging implementations
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/autologging_utils/client.py
  tests/autologging/test_autologging_client.py
  tests/sklearn/test_sklearn_autolog.py
Labels: area/tracking, rn/feature

#4473 Autologging performance improvements for XGBoost / LightGBM
  mlflow/lightgbm.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/xgboost.py
  tests/xgboost/test_xgboost_autolog.py
Labels: area/tracking, rn/feature

#4455 Follow-up for #3881
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/store/tracking/abstract_store.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: rn/none

#4469 Specify `decimal` for `np.testing.assert_array_almost_equal` in PaddlePaddle test to avoid flakiness
  tests/paddle/test_paddle_model_export.py
Labels: area/build, rn/none

#4482 [branch-1.18] Enable nexus-staging-maven-plugin
  mlflow/java/pom.xml
Labels: rn/none

#4481 [master] Enable `nexus-staging-maven-plugin`
  mlflow/java/pom.xml
Labels: rn/none

#4480 Pin `sphinx` to 3.5.4
  dev-requirements.txt
Labels: rn/none

#4485 [branch-1.18] Pin sphinx to `3.5.4`
  dev-requirements.txt
Labels: rn/none

#4493 Don't trigger dev version testing on pull requests
  .github/workflows/cross-version-tests.yml
  dev/set_matrix.py
Labels: area/build, rn/none

#4486 Prevent `sklearn.compose.ColumnTransformer` from triggering autologging
  mlflow/sklearn/__init__.py
  tests/sklearn/test_sklearn_autolog.py
Labels: area/models, rn/none

#4494 Fix autologging event logger log_autolog_called with disable=True
  mlflow/utils/autologging_utils/__init__.py
  tests/autologging/test_autologging_utils.py
Labels: area/tracking, rn/bug-fix

#4497 Support setting tags while resuming run
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent.py
Labels: area/tracking, rn/feature

#4503 Enforce updating R documents
  .circleci/config.yml
  docs/source/R-api.rst
  mlflow/R/mlflow/document.R
Labels: area/build, rn/none

#4359 Adding explain option in mlflow deployments cli
  mlflow/deployments/base.py
  mlflow/deployments/cli.py
  tests/deployments/test_cli.py
  tests/deployments/test_deployments.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/fake_deployment_plugin.py
Labels: area/models, rn/none

#4506 Fix json serialization of numpy arrays with object dtype
  mlflow/utils/proto_json_utils.py
  tests/models/test_model_input_examples.py
Labels: area/models, rn/none

#4483 Added create/delete registered model to R API
  mlflow/R/mlflow/DESCRIPTION
  mlflow/R/mlflow/R/model-registry.R
  mlflow/R/mlflow/R/tracking-rest.R
  mlflow/R/mlflow/tests/testthat/test-model-registry.R
Labels: area/model-registry, language/r, rn/feature

#4501 Added commandRunId request header
  mlflow/tracking/request_header/databricks_request_header_provider.py
  mlflow/utils/databricks_utils.py
  tests/tracking/request_header/test_databricks_request_header_provider.py
Labels: integrations/databricks, rn/none

#4509 Instantiate `mock.MagicMock`
  tests/store/artifact/test_databricks_models_artifact_repo.py
  tests/store/model_registry/test_rest_store.py
  tests/store/tracking/test_rest_store.py
Labels: rn/none
