Repository mlflow/mlflow, pull requests merged in 2021-12, with the labels that each got.

#5125 Deprecate python 3.6
  mlflow/__init__.py
Labels: rn/none

#5045 Add server option for serving only artifacts and proxied serving mode
  examples/mlflow_artifacts/README.md
  examples/mlflow_artifacts/docker-compose.yml
  examples/mlflow_artifacts/example.py
  mlflow/azure/client.py
  mlflow/cli.py
  mlflow/projects/utils.py
  mlflow/server/__init__.py
  mlflow/server/handlers.py
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/http_artifact_repo.py
  mlflow/store/artifact/mlflow_artifacts_repo.py
  mlflow/store/tracking/__init__.py
  mlflow/utils/cli_args.py
  mlflow/utils/file_utils.py
  mlflow/utils/rest_utils.py
  mlflow/utils/uri.py
  tests/store/artifact/test_mlflow_artifact_repo.py
  tests/test_cli.py
  tests/tracking/test_mlflow_artifacts.py
Labels: rn/feature, area/examples, area/tracking, area/server-infra

#5065 Introduce autoformatting bot
  .github/workflows/README.md
  .github/workflows/autoformat.js
  .github/workflows/autoformat.yml
  dev/lint.sh
Labels: rn/none

#5136 Checkout to fork branch when running autoformat bot
  .github/workflows/autoformat.js
  .github/workflows/autoformat.yml
Labels: rn/none

#4695 Caching boto client to improve artifact download speed
  mlflow/store/artifact/s3_artifact_repo.py
  tests/store/artifact/test_s3_artifact_repo.py
Labels: rn/bug-fix, area/artifacts

#5017 Automatically update metric plots for in-progress runs #2099
  mlflow/server/js/src/experiment-tracking/components/MetricsPlotControls.js
  mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.js
  mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.test.js
  mlflow/server/js/src/experiment-tracking/reducers/MetricReducer.js
  mlflow/server/js/src/i18n/default/en.json
Labels: rn/feature, area/uiux

#5140 Pass environment variable SERVING_ENVIRONMENT to SageMaker model
  mlflow/models/container/__init__.py
  mlflow/sagemaker/__init__.py
  tests/sagemaker/test_deployment.py
Labels: rn/none, integrations/sagemaker

#5134 MLflow Schema enforcement should not cast object to pandas String
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/pyfunc/test_scoring_server.py
Labels: rn/bug-fix, area/scoring

#5003 BUG: fixed model serve fail with HTTP 400 on Bad Request.
  mlflow/pyfunc/scoring_server/__init__.py
  tests/models/test_cli.py
  tests/pyfunc/test_scoring_server.py
Labels: rn/bug-fix, area/scoring

#4256 Start a run before logging a model
  mlflow/R/mlflow/R/model.R
Labels: language/r, rn/none

#5121 Track server metrics for all endpoints, remove high cardinality path label
  mlflow/server/prometheus_exporter.py
  tests/server/test_prometheus_exporter.py
Labels: rn/breaking-change, area/server-infra

#5016 Make example input and PyFuncInput support csc csr matrix
  docs/source/conf.py
  mlflow/models/utils.py
  mlflow/pyfunc/__init__.py
  mlflow/types/utils.py
  setup.py
  tests/models/test_model_input_examples.py
  tests/sklearn/test_sklearn_autolog.py
  tests/types/test_schema.py
Labels: rn/feature, area/artifacts

#3863 Proper Python worker reuse for test_model_cache.
  tests/pyfunc/test_spark.py
Labels: rn/none, area/build

#4604 Bug Fix Issue #4603 Access problem
  mlflow/projects/docker.py
  mlflow/utils/file_utils.py
  tests/projects/test_docker_projects.py
  tests/utils/test_file_utils.py
Labels: rn/none, area/projects, area/docker

#5069 Implement model evaluation API (part 1)
  docs/source/python_api/mlflow.models.evaluation.base.rst
  docs/source/python_api/mlflow.models.evaluation.rst
  mlflow/__init__.py
  mlflow/models/__init__.py
  mlflow/models/evaluation/__init__.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/evaluator_registry.py
  tests/models/test_evaluation.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/dummy_evaluator.py
  tests/resources/mlflow-test-plugin/setup.py
Labels: rn/feature, area/tracking

#5156 Change type hint of return type of method get_latest_versions to List[ModelVersion] Fixes #5155
  mlflow/tracking/client.py
Labels: area/docs, rn/none

#5149 Log model uuid
  mlflow/models/model.py
  tests/models/test_model.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/tracking/test_rest_tracking.py
Labels: rn/feature, area/tracking

#5160 Remove param 'verbose_eval' in lightgbm version > 3.3.1
  tests/lightgbm/test_lightgbm_autolog.py
Labels: rn/none, area/tracking, enable-dev-tests

#5162 Move `mleap` to `Enhances` section in `DESCRIPTION`
  .github/workflows/master.yml
  mlflow/R/mlflow/DESCRIPTION
Labels: rn/none

#5164 Use `drat` to install `mleap`
  .github/workflows/master.yml
  mlflow/R/mlflow/DESCRIPTION
Labels: rn/none

#5166 Drop mleap for R
  docs/source/R-api.rst
  mlflow/R/mlflow/DESCRIPTION
  mlflow/R/mlflow/NAMESPACE
  mlflow/R/mlflow/R/model-mleap.R
  mlflow/R/mlflow/man/mlflow_save_model.Rd
  mlflow/R/mlflow/tests/testthat/test-model-mleap.R
Labels: rn/breaking-change

#5165 Add `model_uuid` to Java `Model`
  mlflow/java/scoring/src/main/java/org/mlflow/models/Model.java
  mlflow/java/scoring/src/test/java/org/mlflow/ModelTest.java
  mlflow/java/scoring/src/test/resources/org/mlflow/models/sample_model_root/MLmodel
  mlflow/java/scoring/src/test/resources/org/mlflow/models/sample_model_root/MLmodel.no.model_uuid
  mlflow/mleap.py
Labels: rn/none

#5167 Only generate model uuid when logging model
  mlflow/models/model.py
  tests/models/test_model.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
Labels: rn/bug-fix, area/artifacts

#5177 Fix `can_parse_as_json`
  mlflow/utils/rest_utils.py
  tests/utils/test_rest_utils.py
Labels: rn/none

#5163 Bugfix: properly pass kwargs to `torch.jit.load` from `mlfow.pytorch.load_model`
  mlflow/pytorch/__init__.py
Labels: rn/bug-fix, area/models

#5176 Improve pip requrements infer error handling
  mlflow/utils/environment.py
Labels: rn/none, area/artifacts

#5180 Use python 3.7 when running dev cross version tests
  .github/workflows/cross-version-tests.yml
  mlflow/spark.py
Labels: rn/none, enable-dev-tests

#5183 Build wheel for python 3.7 in onnx dev test
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#5153 remove: torchvision dependency when log torch model. fixed #4381
  mlflow/pytorch/__init__.py
Labels: rn/breaking-change

#5182 Dockerize R package build
  .github/workflows/master.yml
  mlflow/R/mlflow/.Rbuildignore
  mlflow/R/mlflow/.build-package.R
  mlflow/R/mlflow/.gitignore
  mlflow/R/mlflow/.run-tests.R
  mlflow/R/mlflow/.utils.R
  mlflow/R/mlflow/Dockerfile.build
  mlflow/R/mlflow/build-package.sh
Labels: rn/none

#5132 Use REPL context attributes if available to avoid calling JVM methods
  mlflow/utils/databricks_utils.py
  tests/utils/test_databricks_utils.py
Labels: rn/none

#5188 Build R documentation using Docker
  .circleci/config.yml
  docs/build-rdoc.sh
  docs/source/R-api.rst
  mlflow/R/mlflow/.Rbuildignore
  mlflow/R/mlflow/.build-doc.R
  mlflow/R/mlflow/.build-package.R
  mlflow/R/mlflow/.install-deps.R
  mlflow/R/mlflow/Dockerfile.build
  mlflow/R/mlflow/Dockerfile.dev
  mlflow/R/mlflow/build-package.sh
Labels: rn/none

#5191 Do not modify tags dict on start_run()
  mlflow/tracking/fluent.py
Labels: rn/bug-fix, area/tracking

#5194 Fix `_use_repl_context_if_available` to return original function result when `get_context` returns None
  mlflow/utils/databricks_utils.py
  tests/utils/test_databricks_utils.py
Labels: rn/none

#5174 [ML-19342] Fix cross-workspace job source link on databricks
  mlflow/tracking/context/databricks_job_context.py
  mlflow/tracking/context/databricks_notebook_context.py
  mlflow/utils/mlflow_tags.py
  tests/tracking/context/test_databricks_job_context.py
  tests/tracking/context/test_databricks_notebook_context.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/none, area/tracking, integrations/databricks

#5130 Autologging functionality for scikit-learn integration with LightGBM (Part 1)
  mlflow/lightgbm.py
  tests/lightgbm/test_lightgbm_model_export.py
Labels: rn/feature, area/models

#5202 Fix python command in the XGBoost scikit-learn example
  examples/xgboost/xgboost_sklearn/README.md
Labels: rn/none, area/examples

#5206 Remove param 'evals_result' 'early_stopping_rounds' in lightgbm version > 3.3.1
  mlflow/lightgbm.py
  tests/lightgbm/test_lightgbm_autolog.py
  tests/sagemaker/mock/__init__.py
Labels: rn/none, area/tracking, enable-dev-tests
