Repository mlflow/mlflow, pull requests merged in 2021-05, with the labels that each got.

#4310 Update to include code of conduct
  CODE_OF_CONDUCT.rst
  CONTRIBUTING.rst
Labels: area/docs, rn/documentation

#4311 MLflow Java client: Retry on 500s
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowHttpCaller.java
  mlflow/java/client/src/test/java/org/mlflow/tracking/HttpCallerTest.java
Labels: language/java, rn/bug-fix

#4313 Make datetime.date objects JSON serializable
  mlflow/utils/proto_json_utils.py
  tests/models/test_model.py
Labels: area/models, rn/bug-fix

#4270 Implementation: autologging for hyperparameter-tuning
  mlflow/pyspark/ml/__init__.py
  mlflow/pyspark/ml/log_model_allowlist.txt
  tests/spark_autologging/ml/test_pyspark_ml_autologging.py
Labels: area/tracking, rn/feature

#4320 Change "source activate" -> "conda activate"
  CONTRIBUTING.rst
Labels: area/docs, rn/documentation

#4324 Document brew dependencies for OSX, split pip install into two sections
  CONTRIBUTING.rst
Labels: area/docs, rn/documentation

#4325 Sklearn autologging bug fix: Don't compute metrics when labels are missing
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
  tests/sklearn/test_sklearn_autolog.py
Labels: area/tracking, rn/bug-fix

#4333 Fix PyTorch Lightning callback hook args
  mlflow/pytorch/_pytorch_autolog.py
Labels: area/models, rn/bug-fix

#4335 Update supported / tested ML package versions
  mlflow/ml-package-versions.yml
Labels: area/models, rn/none

#4181 Add GPG sign for pom.xml and update pom distributionManagement
  mlflow/java/client/pom.xml
  mlflow/java/pom.xml
  mlflow/java/scoring/pom.xml
  mlflow/java/spark/pom.xml
Labels: area/build, rn/none

#4341 Temporary fix: `test_autolog_respects_silent_mode` occasionally leaks a run
  tests/autologging/test_autologging_behaviors_integration.py
Labels: rn/none

#4285 Cache catboost wheel for dev version
  .github/workflows/cross-version-tests.yml
  mlflow/ml-package-versions.yml
Labels: area/build, rn/none

#4174 [ML-14300] Add a script that updates `ml-package-versions.yml`
  dev/update_ml_package_versions.py
  mlflow/ml-package-versions.yml
  tests/dev/test_update_ml_package_versions.py
Labels: area/build, rn/none

#4261 Cache artifact root for Databricks artifact repository
  docs/source/tracking.rst
  mlflow/tracking/_tracking_service/client.py
  tests/tracking/_tracking_service/test_tracking_service_client.py
Labels: area/tracking, rn/none

#4350 Fix issues caused by Flask 2.0.0 release
  dev/install-common-deps.sh
  dev/small-requirements.txt
  tests/catboost/test_catboost_model_export.py
  tests/deployments/test_cli.py
  tests/statsmodels/test_statsmodels_model_export.py
Labels: rn/none

#4349 Handle package versions that violate PEP 440
  mlflow/utils/autologging_utils/versioning.py
  tests/autologging/test_autologging_utils.py
Labels: rn/none

#4360 Add Nexus Staging Maven Plugin for mlflow-java Deployment and Release
  mlflow/java/pom.xml
Labels: area/build, rn/none

#4363 Replace `add_javascript` with `add_js_file` in Sphinx configuration script
  docs/source/conf.py
  docs/source/languagesections/__init__.py
Labels: rn/none

#4364 Increase the JVM stack size to fix flaky spark build
  mlflow/ml-package-versions.yml
Labels: area/build, rn/none

#4348 Fix prepare_data issue in dev version of pytorch-lightning
  examples/pytorch/AxHyperOptimizationPTL/ax_hpo_mnist.py
  examples/pytorch/AxHyperOptimizationPTL/iris_data_module.py
  examples/pytorch/BertNewsClassification/bert_classification.py
  examples/pytorch/IterativePruning/iterative_prune_mnist.py
  examples/pytorch/IterativePruning/mnist.py
  examples/pytorch/MNIST/mnist_autolog_example.py
  tests/pytorch/iris_data_module.py
  tests/pytorch/test_pytorch_autolog.py
Labels: rn/none

#4369 Allow running cross version tests manually
  .github/workflows/cross-version-tests.yml
Labels: area/build, rn/none

#4368 Set protobuf dependency >= 3.7.0
  setup.py
Labels: area/tracking, rn/none

#4371 Fix for TensorFlow 2.5 compatibility
  mlflow/ml-package-versions.yml
  mlflow/tensorflow.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/tensorflow_autolog/test_tensorflow_autolog.py
Labels: area/tracking, rn/bug-fix

#4372 Fix version mismatch between h2o client and cluster in R
  mlflow/R/mlflow/.create-test-env.R
  mlflow/R/mlflow/tests/testthat/test-model-h2o.R
Labels: rn/none

#4378 Remove h2o version mismatch between python and R
  mlflow/R/mlflow/.create-test-env.R
  mlflow/R/mlflow/tests/testthat/test-model-h2o.R
Labels: area/build, rn/none

#4373 Ignore yanked releases when generating a test matrix for the cross version tests
  dev/set_matrix.py
Labels: area/build, rn/none

#4380 Use python 3.7 for dev sklearn testing
  .github/workflows/cross-version-tests.yml
Labels: area/build, rn/none

#4384 Fix cross version test for keras 2.4.3
  mlflow/ml-package-versions.yml
Labels: rn/none

#4238 Fix #2551
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/bug-fix

#4260 Parallelize Databricks artifact downloading and uploading
  mlflow/store/artifact/artifact_repo.py
  mlflow/store/artifact/databricks_artifact_repo.py
  tests/store/artifact/test_databricks_artifact_repo.py
Labels: area/tracking, rn/feature

#4385 Fix docker tests
  .dockerignore
  .github/workflows/examples.yml
  dev/remove-conda-envs.sh
Labels: area/build, rn/none

#4386 Migrate to `packaging.version` from `distutils.version`
  examples/spacy/train.py
  mlflow/azureml/__init__.py
  mlflow/gluon.py
  mlflow/keras.py
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_pytorch_autolog.py
  mlflow/sklearn/utils.py
  mlflow/tensorflow.py
  mlflow/xgboost.py
  tests/gluon/test_gluon_model_export.py
  tests/gluon_autolog/test_gluon_autolog.py
  tests/keras/test_keras_model_export.py
  tests/pytorch/test_pytorch_autolog.py
  tests/spacy/test_spacy_model_export.py
  tests/spark_autologging/ml/test_pyspark_ml_autologging.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/xgboost/test_xgboost_autolog.py
Labels: rn/none

#4389 Fix dev spacy testing
  mlflow/ml-package-versions.yml
Labels: area/build, rn/none

#4382 Limit # of child runs created for hyperparam search models
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
  tests/sklearn/test_sklearn_autolog.py
Labels: area/tracking, rn/feature

#4377 Fix `mlflow models serve` failure in Windows
  mlflow/pyfunc/backend.py
  tests/helper_functions.py
  tests/test_cli.py
Labels: area/windows, rn/bug-fix

#4352 Fix forced default experiment creation
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: area/docker, area/server-infra, area/sqlalchemy, area/tracking, rn/bug-fix

#4398 Fix pytorch-lightning dev testing
  mlflow/pytorch/_pytorch_autolog.py
Labels: area/build, rn/none

#4393 Migrate all model dependencies from conda to "pip" section
  mlflow/catboost.py
  mlflow/fastai.py
  mlflow/h2o.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/onnx.py
  mlflow/pyfunc/model.py
  mlflow/pytorch/__init__.py
  mlflow/shap.py
  mlflow/sklearn/__init__.py
  mlflow/spacy.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/tensorflow.py
  mlflow/utils/environment.py
  mlflow/xgboost.py
  tests/gluon/test_gluon_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/keras/test_keras_model_export.py
  tests/onnx/test_onnx_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/pytorch/test_pytorch_model_export.py
  tests/shap/test_log.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spacy/test_spacy_model_export.py
  tests/spark/test_spark_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/tensorflow/test_tensorflow2_model_export.py
  tests/tensorflow/test_tensorflow_model_export.py
Labels: area/tracking, rn/none

#3759 [MINOR FIX] Enable `--verbose` for pytest by default
  .github/workflows/README.md
  .github/workflows/cross-version-tests.yml
  .github/workflows/examples.yml
  .github/workflows/master.yml
  CONTRIBUTING.rst
  dev/run-large-python-tests.sh
  dev/run-python-flavor-tests.sh
  dev/run-python-sagemaker-tests.sh
  dev/run-python-skinny-tests.sh
  dev/run-python-tf-tests.sh
  dev/run-small-python-tests.sh
  dev/set_matrix.py
  mlflow/ml-package-versions.yml
  pytest.ini
Labels: area/build, rn/none
