Repository mlflow/mlflow, pull requests merged in 2021-11, with the labels that each got.

#4975 Avoid using tensorflow-estimator 2.7
  dev/extra-ml-requirements.txt
Labels: rn/none

#4976 Avoid using `torchmetrics` 0.6.0
  examples/pytorch/IterativePruning/conda.yaml
  examples/pytorch/MNIST/conda.yaml
Labels: rn/none

#4968 Use `EXTRA_PYFUNC_SERVING_TEST_ARGS` in `test_catboost_model_export.py` to avoid attempting to install catboost version that doesn't exist on PyPI
  tests/catboost/test_catboost_model_export.py
Labels: rn/none

#4979 Pin `transformers` for `keras <= 2.3.1`
  mlflow/ml-package-versions.yml
Labels: rn/none

#4978 Show how to apply black formatting when `black --check .` fails
  lint.sh
Labels: rn/none

#4967 Avoid passing a relative path to `pkg_resources.resource_filename`
  mlflow/utils/autologging_utils/versioning.py
  mlflow/utils/requirements_utils.py
Labels: rn/none

#4958 Add debugging statement to parameter collision exception
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/utils/validation.py
  tests/store/tracking/test_file_store.py
  tests/tracking/test_tracking.py
Labels: rn/none, area/tracking

#4980 Show package release dates to make it easier to identify updated packages
  .github/workflows/cross-version-tests.yml
  dev/install-common-deps.sh
  dev/show_package_release_dates.py
Labels: rn/none

#4966 Fix pytest options to show skipped tests and how to unskip them rather than deselecting them
  conftest.py
Labels: rn/none

#4970 Update `pylint` version to run lint check faster by about 4 minutes
  dev/lint-requirements.txt
  lint.sh
  mlflow/gluon.py
  mlflow/mleap.py
  mlflow/projects/backend/local.py
  mlflow/pyfunc/__init__.py
  mlflow/pyspark/ml/__init__.py
  mlflow/server/handlers.py
  mlflow/types/schema.py
  pylintrc
  tests/autologging/test_autologging_behaviors_integration.py
  tests/gluon/test_gluon_model_export.py
  tests/gluon_autolog/test_gluon_autolog.py
  tests/keras/test_keras_model_export.py
  tests/resources/example_project_no_spec/check_conda_env.py
  tests/spark_autologging/datasource/test_spark_datasource_autologging_crossframework.py
  tests/store/tracking/test_rest_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/test_mlflow_lazily_imports_ml_packages.py
  tests/utils/test_uri.py
Labels: rn/none

#4984 Pin tensorflow-estimator to `< 2.7.0` in cross version test
  mlflow/ml-package-versions.yml
Labels: rn/none

#4989 Replace pytorch_lightning.metrics by torchmetrics
  examples/pytorch/AxHyperOptimizationPTL/iris.py
  examples/pytorch/IterativePruning/conda.yaml
  examples/pytorch/IterativePruning/mnist.py
  examples/pytorch/MNIST/conda.yaml
  examples/pytorch/MNIST/mnist_autolog_example.py
  mlflow/pytorch/__init__.py
Labels: rn/none

#4985 Update `defaults.run.shell` to show executed command by default
  .github/workflows/cross-version-tests.yml
  .github/workflows/examples.yml
  .github/workflows/labeling.yml
  .github/workflows/master.yml
  .github/workflows/release-note-category.yml
  .github/workflows/test-package-build.yml
Labels: rn/none

#4998 Use `globalSetup` to set timezone when running JS tests
  .github/workflows/master.yml
  mlflow/server/js/package.json
  mlflow/server/js/scripts/global-setup.js
  mlflow/server/js/src/timezone.test.js
Labels: rn/none

#5005 Fix `the specified blob already exists` error
  mlflow/store/artifact/azure_blob_artifact_repo.py
Labels: rn/none

#5002 Change pathing in test harness for windows
  tests/helper_functions.py
  tests/pyfunc/test_scoring_server.py
  tests/store/tracking/test_file_store.py
Labels: rn/none, area/tracking

#4962 Update “latest_metrics” and “metrics” table “timestamp” field default value to be int(time.time()*1000)
  mlflow/store/tracking/dbmodels/models.py
Labels: rn/none, area/tracking

#4991 updating documentation to address issue 4202 Signed-off-by: westford1…
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: area/docs, rn/documentation

#5008 Remove `tests/<flavor_name>/autologging` directories to unify folder structures
  conftest.py
  dev/run-python-flavor-tests.sh
  mlflow/ml-package-versions.yml
  tests/gluon/test_gluon_autolog.py
  tests/gluon/test_gluon_model_export.py
  tests/gluon/utils.py
  tests/keras/test_keras_autolog.py
  tests/spark/autologging/__init__.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging_crossframework.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging_missing_jar.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging_order.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging_unit.py
  tests/spark/autologging/datasource/test_spark_disable_autologging.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging_custom_allowlist.py
  tests/spark/autologging/utils.py
  tests/tensorflow/iris_test.csv
  tests/tensorflow/iris_training.csv
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/none

#4964 Remove `try_mlflow_log` from autologging & tests
  examples/pytorch/IterativePruning/iterative_prune_mnist.py
  mlflow/fastai/__init__.py
  mlflow/fastai/callback.py
  mlflow/gluon.py
  mlflow/keras.py
  mlflow/pyspark/ml/__init__.py
  mlflow/statsmodels.py
  mlflow/tensorflow.py
  mlflow/utils/autologging_utils/safety.py
Labels: rn/none, area/examples

#5011 Run TensorFlow 2.7+ tests with Python 3.7
  .github/workflows/cross-version-tests.yml
  mlflow/tensorflow.py
Labels: rn/none, area/build

#5012 Add optional experiment_id parameter to `mlflow.set_experiment`
  mlflow/tracking/fluent.py
  tests/tracking/test_tracking.py
Labels: rn/feature, area/tracking

#5014 Clean up pylint command
  dev/set_matrix.py
  dev/show_package_release_dates.py
  lint.sh
  pylintrc
Labels: rn/none

#5019 Add a pre-commit hook for running `black` and `pylint`
  CONTRIBUTING.rst
  hooks/pre-commit
Labels: rn/none

#5018 Bugfix: Truncated values in sortBy column
  mlflow/server/js/src/experiment-tracking/components/ExperimentView.css
  mlflow/server/js/src/experiment-tracking/components/ExperimentView.js
Labels: rn/bug-fix, area/uiux

#4947 fix metricplotview crashes while metric value is large
  mlflow/server/js/src/experiment-tracking/components/MetricsPlotView.js
  mlflow/server/js/src/experiment-tracking/components/MetricsPlotView.test.js
Labels: rn/bug-fix, area/uiux

#5024 Run Keras 2.7+ tests against Python 3.7
  .github/workflows/cross-version-tests.yml
Labels: rn/none, area/build

#4946 [Proxied artifact operations] Implement REST API endpoints and artifact repository
  .gitignore
  examples/mlflow_artifacts/.dockerignore
  examples/mlflow_artifacts/Dockerfile
  examples/mlflow_artifacts/Dockerfile.dev
  examples/mlflow_artifacts/README.md
  examples/mlflow_artifacts/build.sh
  examples/mlflow_artifacts/docker-compose.yml
  examples/mlflow_artifacts/example.py
  generate-protos.sh
  mlflow/cli.py
  mlflow/java/client/src/main/java/org/mlflow/api/proto/MlflowArtifacts.java
  mlflow/protos/mlflow_artifacts.proto
  mlflow/protos/mlflow_artifacts_pb2.py
  mlflow/server/__init__.py
  mlflow/server/handlers.py
  mlflow/store/artifact/artifact_repository_registry.py
  mlflow/store/artifact/http_artifact_repo.py
  mlflow/utils/proto_json_utils.py
  tests/store/artifact/test_http_artifact_repo.py
  tests/tracking/test_mlflow_artifacts.py
Labels: rn/feature

#4997 Improve load_model() by adding param dst_path
  mlflow/catboost.py
  mlflow/fastai/__init__.py
  mlflow/gluon.py
  mlflow/h2o.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/onnx.py
  mlflow/paddle/__init__.py
  mlflow/prophet.py
  mlflow/pyfunc/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/spacy.py
  mlflow/statsmodels.py
  mlflow/tensorflow.py
  mlflow/xgboost.py
Labels: rn/none, area/models

#5026 Remove try_mlflow_log() and unwanted tests
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/autologging_utils/safety.py
  tests/autologging/test_autologging_safety_unit.py
  tests/autologging/test_autologging_utils.py
Labels: rn/none

#5007 Run `extract-i18n.js --lint` to make sure `src/i18n/default/en.json` is up-to-date
  .github/workflows/master.yml
  mlflow/server/js/src/i18n/default/en.json
Labels: rn/none

#5030 Add missing `down` for `docker-compose`
  examples/mlflow_artifacts/README.md
Labels: rn/none

#5032 Add `--artifacts-destination` option to `mlflow ui`
  mlflow/cli.py
  mlflow/utils/cli_args.py
Labels: rn/none

#5031 Add instructions to preview documentation on CircleCI in pull request template
  .github/pull_request_template.md
Labels: rn/none

#5000 convert nan's in input examples to None before converting to JSON
  mlflow/models/utils.py
  tests/models/test_model_input_examples.py
Labels: rn/none, area/models

#4999 Add POST version of GetLatestVersions api
  mlflow/java/client/src/main/java/org/mlflow/api/proto/ModelRegistry.java
  mlflow/protos/model_registry.proto
  mlflow/protos/model_registry_pb2.py
  mlflow/store/model_registry/rest_store.py
  mlflow/utils/rest_utils.py
  tests/store/model_registry/test_rest_store.py
  tests/utils/test_rest_utils.py
Labels: rn/bug-fix, area/model-registry

#5029 Clarify how cross version testing works
  .github/workflows/README.md
  .github/workflows/cross-version-testing.md
Labels: rn/none

#5037 Fix `CondaVerificationError` when runnng `conda create`
  mlflow/utils/conda.py
Labels: rn/none

#5028 Remove the experimental decorators on autolog() for all flavors
  docs/source/tracking.rst
  mlflow/fastai/__init__.py
  mlflow/gluon.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/paddle/__init__.py
  mlflow/pyspark/ml/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/tensorflow.py
  mlflow/xgboost.py
Labels: rn/feature, area/tracking

#5036 Exclude `mlflow/protos` when running `black` in `hooks/pre-commit`
  hooks/pre-commit
Labels: rn/none

#5022 Truncate in middle for the dropdown of sorting columns in Experiment View
  mlflow/server/js/src/common/utils/StringUtils.js
  mlflow/server/js/src/common/utils/StringUtils.test.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentView.js
Labels: rn/feature, area/artifacts

#5042 Pytorch examples - Pytorch Lightning 1.5.1 support
  examples/pytorch/AxHyperOptimizationPTL/conda.yaml
  examples/pytorch/BertNewsClassification/bert_classification.py
  examples/pytorch/BertNewsClassification/conda.yaml
  examples/pytorch/IterativePruning/conda.yaml
  examples/pytorch/IterativePruning/iterative_prune_mnist.py
  examples/pytorch/IterativePruning/mnist.py
  examples/pytorch/MNIST/conda.yaml
  examples/pytorch/MNIST/mnist_autolog_example.py
Labels: rn/none, area/examples

#5046 Remove codecov badges from readmes
  mlflow/R/mlflow/README.Rmd
  mlflow/R/mlflow/README.md
Labels: area/docs, rn/none

#5010 Fix a bug that converts int64 to string when converting Protobuf to JSON
  generate-protos.sh
  mlflow/utils/proto_json_utils.py
  pylintrc
  pyproject.toml
  tests/protos/__init__.py
  tests/protos/test_message.proto
  tests/protos/test_message_pb2.py
  tests/store/artifact/test_cli.py
  tests/tracking/test_mlflow_artifacts.py
  tests/utils/test_proto_json_utils.py
Labels: rn/none, area/model-registry

#5047 Set `remote` for `devtools::check_built` to `True` to detect invalid URLs
  .github/workflows/master.yml
  mlflow/R/mlflow/.run-tests.R
Labels: rn/none

#5043 Add a test to make sure `mlflow ui` and `mlflow server` commands run successfully
  tests/test_cli.py
Labels: rn/none

#5044 Remove the experimental decorator from log_model() in gluon
  mlflow/gluon.py
Labels: rn/none, area/tracking

#5041 Obtain changed files using GitHub `/pulls/{ pr_number }/files` API in cross version tests
  .github/workflows/cross-version-tests.yml
  dev/list_changed_files.py
Labels: rn/none

#5052 Unpin isort
  dev/lint-requirements.txt
Labels: rn/none

#5053 Fix `devtools::check_built failure` failure
  mlflow/R/mlflow/.run-tests.R
Labels: rn/none

#4718 Remove `manual_run` fixture in keras, tensorflow and fastai tests to decrease the number of tests
  tests/fastai/test_fastai_autolog.py
  tests/keras/test_keras_autolog.py
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/none

#5060 Change the deafult value of `python_version` for `install_mlflow` in MLflow R to `3.7`
  docs/source/R-api.rst
  mlflow/R/mlflow/R/install.R
  mlflow/R/mlflow/man/install_mlflow.Rd
Labels: rn/none

#5063 Clean up `dev-requirements.txt`
  .circleci/config.yml
  .github/workflows/master.yml
  CONTRIBUTING.rst
  doc-requirements.txt
Labels: rn/none

#5064 Unpin `tensorflow estimator`
  dev/extra-ml-requirements.txt
  mlflow/ml-package-versions.yml
Labels: rn/none

#5066 Use `pull_request.user` rather than `pull_request.head.user` in `notify-dco-failure` workflow
  .github/workflows/notify-dco-failure.js
Labels: rn/none

#5072 Remove `pyarrow` from `lint-requirements.txt`
  dev/lint-requirements.txt
Labels: rn/none

#5073 Re-organize requirements files
  .circleci/config.yml
  .dockerignore
  .github/actions/cache-pip/action.yml
  .github/workflows/cross-version-tests.yml
  .github/workflows/master.yml
  CONTRIBUTING.rst
  Dockerfile
  dev/install-common-deps.sh
  dev/setup-spark-datasource-autologging.sh
  lint.sh
  requirements/doc-requirements.txt
  requirements/extra-ml-requirements.txt
  requirements/large-requirements.txt
  requirements/lint-requirements.txt
  requirements/skinny-requirements.txt
  requirements/small-requirements.txt
  requirements/test-requirements.txt
  test-requirements.txt
Labels: rn/none

#5075 Replace deprecated method trainer.disable_validation()
  mlflow/pytorch/_pytorch_autolog.py
  tests/pytorch/test_pytorch_autolog.py
Labels: rn/none, enable-dev-tests

#5039 Ensure all autologging callbacks are picklable
  mlflow/gluon/__init__.py
  mlflow/gluon/_autolog.py
  mlflow/lightgbm.py
  mlflow/tensorflow/__init__.py
  mlflow/tensorflow/_autolog.py
  mlflow/utils/autologging_utils/safety.py
  mlflow/xgboost/__init__.py
  mlflow/xgboost/_autolog.py
  tests/autologging/test_autologging_safety_unit.py
  tests/fastai/test_fastai_autolog.py
  tests/gluon/test_gluon_autolog.py
  tests/lightgbm/test_lightgbm_autolog.py
  tests/tensorflow/test_tensorflow2_autolog.py
  tests/xgboost/test_xgboost_autolog.py
Labels: rn/none

#5006 Render code to load model when pyfunc flavor is unavailable
  mlflow/server/js/src/common/constants.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactLoggedModelView.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactLoggedModelView.test.js
  mlflow/server/js/src/i18n/default/en.json
Labels: rn/bug-fix

#4923 Allow Deploying SageMaker Endpoints to Another AWS Account #4921
  mlflow/sagemaker/__init__.py
  requirements/small-requirements.txt
  tests/sagemaker/test_deployment.py
Labels: rn/feature, integrations/sagemaker

#5081 Run tests using dev version of `databricks-cli`
  requirements/small-requirements.txt
Labels: rn/none

#5058 Unblock PIP package hashes when logging models
  docs/source/tutorials-and-examples/index.rst
  examples/README.md
  examples/supply_chain_security/MLproject
  examples/supply_chain_security/README.rst
  examples/supply_chain_security/conda.yaml
  examples/supply_chain_security/requirements.in
  examples/supply_chain_security/requirements.txt
  examples/supply_chain_security/train.py
  mlflow/utils/environment.py
  tests/examples/test_examples.py
  tests/utils/test_environment.py
Labels: area/docs, rn/bug-fix, rn/documentation, area/artifacts, area/examples

#5088 Fix `test_environment.py`.
  mlflow/utils/environment.py
  tests/utils/test_environment.py
Labels: rn/none

#5085 Enable `line-too-long` for pylint
  dev/set_matrix.py
  mlflow/pytorch/_pytorch_autolog.py
  mlflow/sklearn/utils.py
  mlflow/tracking/client.py
  mlflow/xgboost/__init__.py
  pylintrc
  tests/autologging/test_autologging_safety_unit.py
  tests/helper_functions.py
  tests/resources/mlflow-test-plugin/setup.py
  tests/shap/test_log.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/store/artifact/test_gcs_artifact_repo.py
  tests/tracking/context/test_databricks_job_context.py
  tests/tracking/context/test_databricks_notebook_context.py
  tests/tracking/fluent/test_fluent.py
  tests/tracking/test_tracking.py
  tests/utils/test_databricks_utils.py
  tests/utils/test_uri.py
Labels: rn/none

#5089 Removed Creator field in ModelVersionView if user_id is undefined
  mlflow/server/js/src/model-registry/components/ModelVersionView.js
  mlflow/server/js/src/model-registry/components/ModelVersionView.test.js
  mlflow/server/js/src/model-registry/test-utils.js
Labels: rn/bug-fix, area/uiux, area/model-registry

#5095 Wrap flaky test in a retry
  mlflow/R/mlflow/tests/testthat/test-model-mleap.R
Labels: language/r, rn/none

#5070 Enable mlflow-artifacts scheme as wrapper around http artifact scheme
  mlflow/store/artifact/artifact_repository_registry.py
  mlflow/store/artifact/http_artifact_repo.py
  mlflow/store/artifact/mlflow_artifacts_repo.py
  tests/store/artifact/test_mlflow_artifact_repo.py
Labels: rn/feature, area/artifacts

#5101 Update python version in conda.yaml for prophet example
  examples/prophet/conda.yaml
Labels: rn/bug-fix, area/examples, area/docker

#4936 Add share button in experiment view
  mlflow/server/js/src/common/utils/Utils.js
  mlflow/server/js/src/common/utils/Utils.test.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentPage.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentPage.test.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentView.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentView.test.js
  mlflow/server/js/src/experiment-tracking/constants.js
  mlflow/server/js/src/experiment-tracking/sdk/MlflowLocalStorageMessages.js
  mlflow/server/js/src/i18n/default/en.json
Labels: rn/feature, area/uiux

#5103 Rename `test-requirements.txt` to `dev-requirements.txt`
  CONTRIBUTING.rst
  Dockerfile
  requirements/dev-requirements.txt
Labels: rn/none

#5099 Add support for azure china
  mlflow/store/artifact/azure_blob_artifact_repo.py
  tests/store/artifact/test_azure_blob_artifact_repo.py
Labels: rn/none, area/artifacts

#5105 Define `_get_class_from_string`
  mlflow/utils/class_utils.py
  mlflow/xgboost/__init__.py
  tests/utils/test_class_utils.py
Labels: rn/none

#5107 Move shell scripts in `dev` folder
  .github/workflows/master.yml
  CONTRIBUTING.rst
  dev/generate-protos.sh
  dev/lint.sh
  dev/test-generate-protos.sh
Labels: rn/none

#5111 Fix list in documentation explaining priorities of Azure settings
  docs/source/tracking.rst
Labels: area/docs, rn/none

#5078 Autologging functionality for scikit-learn integration with XGBoost (Part 2)
  examples/xgboost/README.md
  examples/xgboost/xgboost_native/MLproject
  examples/xgboost/xgboost_native/README.md
  examples/xgboost/xgboost_native/conda.yaml
  examples/xgboost/xgboost_native/train.py
  examples/xgboost/xgboost_sklearn/MLproject
  examples/xgboost/xgboost_sklearn/README.md
  examples/xgboost/xgboost_sklearn/conda.yaml
  examples/xgboost/xgboost_sklearn/train.py
  examples/xgboost/xgboost_sklearn/utils.py
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
  mlflow/xgboost/__init__.py
  tests/autologging/test_autologging_behaviors_integration.py
  tests/examples/test_examples.py
  tests/xgboost/test_xgboost_autolog.py
Labels: rn/documentation, area/examples, area/tracking

#5119 Replace `searchPlaceholder` for `TreeSelect` with `placeholder`
  mlflow/server/js/src/experiment-tracking/components/MetricsPlotControls.js
  mlflow/server/js/src/experiment-tracking/components/ParallelCoordinatesPlotControls.js
Labels: rn/none

#5120 Remove `mlruns` directory in module teardown
  tests/conftest.py
Labels: rn/none

#5127 Remove `noqa` for `pycodestyle`
  mlflow/__init__.py
  mlflow/sagemaker/__init__.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/file_utils.py
  tests/entities/test_run_data.py
Labels: rn/none

#5117 Parse subdirectory with quotes
  mlflow/projects/utils.py
  tests/projects/test_utils.py
Labels: rn/bug-fix, area/projects
