Repository mlflow/mlflow, pull requests merged in 2021-01, with the labels that each got.

#3939 Update tutorial.rst
  docs/source/tutorials-and-examples/tutorial.rst
Labels: area/examples, area/windows, rn/none

#3740 add [extras] to dev setup doc
  CONTRIBUTING.rst
Labels: area/docs, rn/none

#3894 Add support for tf serving input to REST API
  mlflow/pyfunc/scoring_server/__init__.py
  tests/pyfunc/test_scoring_server.py
Labels: area/scoring, rn/feature

#3938 Disable `broad-except` in Pylint
  mlflow/_spark_autologging.py
  mlflow/azureml/__init__.py
  mlflow/cli.py
  mlflow/lightgbm.py
  mlflow/projects/databricks.py
  mlflow/projects/docker.py
  mlflow/pyfunc/scoring_server/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
  mlflow/spark.py
  mlflow/store/db_migrations/versions/0a8213491aaa_drop_duplicate_killed_constraint.py
  mlflow/tracking/context/registry.py
  mlflow/tracking/fluent.py
  mlflow/utils/_spark_utils.py
  mlflow/utils/autologging_utils.py
  mlflow/utils/databricks_utils.py
  mlflow/utils/rest_utils.py
  mlflow/xgboost.py
  pylintrc
  tests/helper_functions.py
  tests/spark/test_spark_model_export.py
  tests/store/tracking/test_file_store.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: area/build, rn/none

#3907 Add pytorch-lightning to cross version tests
  ml-package-versions.yml
Labels: area/build, rn/none

#3916 Remove `six` from dependencies
  mlflow/mleap.py
  mlflow/pyfunc/scoring_server/__init__.py
  mlflow/utils/__init__.py
  setup.py
Labels: rn/none

#3774 Unpin transformers in bert classification example
  examples/pytorch/BertNewsClassification/bert_classification.py
  examples/pytorch/BertNewsClassification/conda.yaml
Labels: area/examples, rn/none

#3906 Validate at least one release-note category is selected
  .github/pull_request_template.md
  .github/workflows/release-note-category.js
  .github/workflows/release-note-category.yml
Labels: area/build, rn/feature, rn/none

#3947 Test anaconda 2020.11 instead of 2020.02
  .github/workflows/master.yml
  dev/test-anaconda-compatibility.sh
Labels: area/build, rn/none

#3834 Add onnx to the cross version tests
  ml-package-versions.yml
Labels: area/build, rn/none

#3937 Use `xgboost.callback.TrainingCallback` in newer versions (>= 1.3.0) of XGBoost
  mlflow/xgboost.py
Labels: area/models, rn/none

#3946 Created request_header_provider and implemented databricks_request_header
  mlflow/tracking/request_header/__init__.py
  mlflow/tracking/request_header/abstract_request_header_provider.py
  mlflow/tracking/request_header/databricks_request_header_provider.py
  tests/tracking/request_header/test_databricks_request_header_provider.py
Labels: area/tracking, integrations/databricks, rn/none

#3948 Fix flaky `test_autolog_logs_signature_and_input_example`
  tests/sklearn/test_sklearn_autolog.py
Labels: area/build, rn/none

#3872 fix a bug with attributes of MLflow model flavor in R
  mlflow/R/mlflow/R/model.R
  mlflow/R/mlflow/tests/testthat.R
  mlflow/R/mlflow/tests/testthat/test-model.R
Labels: area/models, language/r, rn/bug-fix

#3949 [MINOR FIX] Remove `python-dateutil` from dependencies
  setup.py
Labels: rn/none

#3957 AutologgingEventLogger: Pass all arguments to `log_autolog_called` in keyword form
  mlflow/utils/autologging_utils.py
  tests/autologging/test_autologging_utils.py
Labels: rn/none

#3958 mlflow gc - delete_artifacts() for s3
  mlflow/store/artifact/s3_artifact_repo.py
  tests/store/artifact/test_s3_artifact_repo.py
Labels: area/artifacts, rn/feature

#3705 Saving and Loading pytorch model as state dict
  mlflow/pytorch/__init__.py
  tests/pytorch/test_pytorch_model_export.py
Labels: area/models, rn/feature

#3976 #3975 Pass await_creation_for in run uri model registration
  mlflow/tracking/_model_registry/fluent.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
Labels: area/model-registry, area/tracking, rn/bug-fix

#3978 Autologging: remove redundant / verbose python event logging message
  mlflow/utils/autologging_utils.py
Labels: area/tracking, rn/bug-fix

#3816 Make mlflow::start_run() work again when a run id is set (directly or via MLFLOW_RUN_ID)
  mlflow/R/mlflow/R/tracking-runs.R
  mlflow/R/mlflow/tests/testthat/test-tracking-runs.R
Labels: area/tracking, language/r, rn/none

#3981 Temporary workaround for keras EarlyStopping issue
  ml-package-versions.yml
  tests/keras_autolog/test_keras_autolog.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/tensorflow_autolog/test_tensorflow_autolog.py
Labels: rn/none

#3990 Install ipython to fix `ModuleNotFoundError: No module named 'IPython'` in shap
  dev/extra-ml-requirements.txt
Labels: rn/none

#3982 Fix sklearn_elasticnet_wine example dependencies and doc
  docs/source/tutorials-and-examples/tutorial.rst
  examples/sklearn_elasticnet_wine/conda.yaml
Labels: area/examples, rn/none

#3993 Fix bug in scikit-learn autologging where metrics plots are computed from incorrect target values
  mlflow/sklearn/utils.py
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/bug-fix

#3992 Fix broken link of cross-version-tests badge on README
  README.rst
Labels: rn/none

#4001 Fix minor language ambiguity to address issue 3968
  docs/source/model-registry.rst
Labels: area/docs, rn/none

#3942 Fix mlflow_list_experiments()
  mlflow/R/mlflow/R/mlflow-package.R
  mlflow/R/mlflow/R/tracking-experiments.R
  mlflow/R/mlflow/tests/testthat/test-tracking-experiments.R
Labels: area/tracking, language/r, rn/bug-fix

#4014 [DOC FIX] Show diagrams and elaborate on interaction between the client, the tracking server and stores
  docs/source/_static/images/scenario_1.png
  docs/source/_static/images/scenario_2.png
  docs/source/_static/images/scenario_3.png
  docs/source/_static/images/scenario_4.png
  docs/source/tracking.rst
Labels: area/artifacts, area/docs, area/tracking, rn/none

#4021 Remove failure when deployment uri has two slashes
  mlflow/deployments/utils.py
  tests/deployments/test_deployments.py
Labels: rn/none
