Repository mlflow/mlflow, pull requests merged in 2021-07, with the labels that each got.

#4512 Update `R-api.rst` to unblock the `build_doc_r` check
  .circleci/config.yml
  .circleci/dump-r-dependencies.R
  docs/source/R-api.rst
  mlflow/R/mlflow/.Rbuildignore
  mlflow/R/mlflow/.dump-r-dependencies.R
  mlflow/R/mlflow/.gitignore
  mlflow/R/mlflow/NAMESPACE
  mlflow/R/mlflow/man/mlflow_create_registered_model.Rd
  mlflow/R/mlflow/man/mlflow_delete_registered_model.Rd
Labels: rn/none

#4513 Use `setup-python` in cross version tests to stabilize python version setup
  .github/workflows/cross-version-tests.yml
Labels: area/build, rn/none

#4511 [DOCS][MINOR] Minor typo update
  docs/source/projects.rst
Labels: area/docs, rn/documentation

#3409 Fix metrics sorting error on UI
  mlflow/utils/search_utils.py
  tests/utils/test_search_utils.py
Labels: area/uiux, rn/bug-fix

#4508 Fix `AttributeError` in `DatabricksRestStore._paginate_list_experiments`
  mlflow/store/tracking/rest_store.py
  tests/store/tracking/test_rest_store.py
Labels: rn/none

#4515 Fix pip install extras command in CONTRIUTING doc
  CONTRIBUTING.rst
Labels: rn/none

#4516 Skip XGBoost autologging test that no longer applies to XGB > 1.4.2
  tests/xgboost/test_xgboost_autolog.py
Labels: area/tracking, rn/none

#4517 Install `wheel` in cross version tests
  .github/workflows/cross-version-tests.yml
Labels: rn/none

#4521 Created command context provider to set job group ID as part of run tags
  mlflow/tracking/context/databricks_command_context.py
  mlflow/tracking/context/registry.py
  mlflow/utils/databricks_utils.py
  mlflow/utils/mlflow_tags.py
  tests/tracking/context/test_databricks_command_context.py
Labels: area/tracking, rn/none

#4523 XGBoost autologging: support per-class importance plots
  mlflow/xgboost.py
  tests/xgboost/test_xgboost_autolog.py
Labels: area/tracking, rn/feature

#4534 [cross version tests] Clean up commands for installing dev versions
  .github/workflows/README.md
  mlflow/ml-package-versions.yml
Labels: enable-dev-tests, rn/none

#4541 Fix spacy test failure caused by spacy 3.10
  tests/spacy/test_spacy_model_export.py
Labels: enable-dev-tests, rn/none

#4458 Updated the examples to use pytorch 1.9.0 and pytorch-lightning 1.3.5
  examples/pytorch/AxHyperOptimizationPTL/conda.yaml
  examples/pytorch/BertNewsClassification/MLproject
  examples/pytorch/BertNewsClassification/bert_classification.py
  examples/pytorch/BertNewsClassification/conda.yaml
  examples/pytorch/IterativePruning/conda.yaml
  examples/pytorch/MNIST/conda.yaml
  examples/pytorch/MNIST/mnist_autolog_example.py
  examples/pytorch/torchscript/IrisClassification/conda.yaml
  examples/pytorch/torchscript/MNIST/conda.yaml
Labels: area/examples, rn/none

#4544 Add is_in_databricks_runtime method
  mlflow/utils/autologging_utils/versioning.py
  mlflow/utils/databricks_utils.py
  tests/autologging/test_autologging_utils.py
  tests/tracking/test_client.py
  tests/utils/test_databricks_utils.py
Labels: area/tracking, rn/none

#4554 Missing pandas dependency on examples/sklearn_elasticnet_wine
  examples/sklearn_elasticnet_wine/conda.yaml
Labels: rn/none

#4549 Fix Spark model logging on passthrough-enabled clusters
  mlflow/spark.py
Labels: rn/none

#4551 Spark datasource autologging: Improve fidelity of REPL ID / context information
  mlflow/_spark_autologging.py
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/MlflowAutologEventPublisher.scala
  mlflow/java/spark/src/test/scala/org/mlflow/spark/autologging/SparkAutologgingIntegrationSuite.scala
  mlflow/utils/databricks_utils.py
  tests/utils/test_databricks_utils.py
Labels: area/tracking, rn/none

#4542 Set `_R_CHECK_SYSTEM_CLOCK_` to false to skip the system clock check in `devtools::check_built`
  .github/workflows/master.yml
Labels: rn/none

#4537 Fix release-note category validation workflow
  .github/workflows/release-note-category.js
  .github/workflows/release-note-category.yml
Labels: rn/none

#4555 [DOC][MINOR] Added step for dev env setup
  CONTRIBUTING.rst
Labels: area/docs, rn/none

#4559 Fetch the latest micro version of python from conda in cross version tests to avoid `ResolvePackageNotFound` error
  .github/workflows/cross-version-tests.yml
  mlflow/onnx.py
Labels: rn/none

#4519 [ML-16200] Add `pip_requirements` and `additional_pip_requirements` to `log_model`
  dev/small-requirements.txt
  docs/source/tutorials-and-examples/tutorial.rst
  examples/pip_requirements/pip_requirements.py
  mlflow/utils/environment.py
  mlflow/utils/requirements_utils.py
  mlflow/xgboost.py
  tests/examples/test_examples.py
  tests/helper_functions.py
  tests/utils/test_environment.py
  tests/utils/test_requirements_utils.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/feature

#4545 Fix dev version test for onnx
  mlflow/ml-package-versions.yml
Labels: enable-dev-tests, rn/none

#4568 Set `defaults.run.shell` to `bash`
  .github/workflows/cross-version-tests.yml
  .github/workflows/examples.yml
  .github/workflows/labeling.yml
  .github/workflows/master.yml
  .github/workflows/release-note-category.yml
  .github/workflows/test-package-build.yml
Labels: rn/none

#4576 Fix dev pyspark test
  mlflow/ml-package-versions.yml
Labels: enable-dev-tests, rn/none

#4574 Fix dev gluon test
  mlflow/gluon.py
  tests/gluon/test_gluon_model_export.py
  tests/gluon_autolog/test_gluon_autolog.py
Labels: enable-dev-tests, rn/none

#4570 Fix test for dev version of statsmodels
  tests/statsmodels/model_fixtures.py
Labels: enable-dev-tests, rn/none

#4572 Allow specifying flavors and versions when manually running cross-version tests
  .github/workflows/cross-version-tests.yml
  dev/set_matrix.py
  tests/dev/test_set_matrix.py
Labels: rn/none

#4580 Avoid running multiple commands using a semicolon in Dockerfile
  mlflow/models/docker_utils.py
Labels: rn/none

#4564 [`pip_requirements` and `extra_pip_requirements`] Add support for constraints files
  examples/pip_requirements/pip_requirements.py
  mlflow/utils/environment.py
  mlflow/utils/requirements_utils.py
  mlflow/xgboost.py
  tests/helper_functions.py
  tests/utils/test_environment.py
  tests/utils/test_requirements_utils.py
  tests/xgboost/test_xgboost_model_export.py
Labels: area/models, rn/none

#4575 Add `_get_default_pip_requirements` to all flavors
  mlflow/catboost.py
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/h2o.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/onnx.py
  mlflow/paddle/__init__.py
  mlflow/pyfunc/model.py
  mlflow/pytorch/__init__.py
  mlflow/shap.py
  mlflow/sklearn/__init__.py
  mlflow/spacy.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/tensorflow.py
  mlflow/xgboost.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none

#4586 Test statsmodels against python 3.7
  .github/workflows/cross-version-tests.yml
Labels: area/build, rn/none

#4588 Fix bad i18n object for model registration date
  mlflow/server/js/src/experiment-tracking/components/ArtifactView.js
Labels: area/model-registry, rn/none

#4410 Implemented Sagemaker Batch Transform integration with MLflow
  mlflow/sagemaker/__init__.py
  mlflow/sagemaker/cli.py
  tests/sagemaker/mock/__init__.py
  tests/sagemaker/mock/test_sagemaker_service_mock.py
  tests/sagemaker/test_batch_deployment.py
Labels: integrations/sagemaker, rn/feature

#4565 Lazily obtain Databricks runtime version in `Model` to avoid importing pyspark when loading MLflow model
  mlflow/models/model.py
Labels: rn/none

#4583 Remove print statements in pip_requirements example
  examples/pip_requirements/pip_requirements.py
Labels: rn/none

#4581 Introduce `format_docstring` decorator to deduplicate param docs
  mlflow/utils/docstring_utils.py
  mlflow/xgboost.py
  tests/utils/test_docstring_utils.py
Labels: rn/none

#4600 Avoid using tensorflow 2.5.0 which is incompatible with keras 2.4.3
  dev/extra-ml-requirements.txt
Labels: rn/none

#4599 Fix docker build error in `test_docker_uri_mode_validation`
  Dockerfile
  tests/resources/example_docker_project/Dockerfile
Labels: rn/none

#4605 Clean up dummy change added to trigger cross version tests for onnx
  mlflow/onnx.py
Labels: rn/none

#4608 Run `python-large` test faster
  tests/resources/example_docker_project/Dockerfile
Labels: rn/none

#4598 Cache scikit-learn wheel in cross version tests
  mlflow/ml-package-versions.yml
Labels: enable-dev-tests, rn/breaking-change

#4460 Add `mlflow-vizmod` in docs
  docs/source/models.rst
Labels: area/docs, rn/none

#4613 Fix PyTorch model flavor MLmodel serialization in latest dev+ PyTorch
  mlflow/pytorch/__init__.py
Labels: area/build, enable-dev-tests, rn/none

#4612 Fix ONNX dev tests by testing pyfunc scoring outside conda environment
  tests/onnx/test_onnx_model_export.py
Labels: area/build, enable-dev-tests, rn/none

#4602 [PART 2] Add `pip_requirements` and `extra_pip_requirements` to all flavors except xgboost flavor
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/keras.py
  mlflow/onnx.py
  mlflow/paddle/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/spacy.py
  mlflow/tensorflow.py
  tests/fastai/test_fastai_model_export.py
  tests/gluon/test_gluon_model_export.py
  tests/keras/test_keras_model_export.py
  tests/onnx/test_onnx_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/pytorch/test_pytorch_model_export.py
  tests/spacy/test_spacy_model_export.py
  tests/tensorflow/test_tensorflow2_model_export.py
Labels: rn/feature

#4577 [PART1] Add `pip_requirements` and `extra_pip_requirements` to all flavors except xgboost flavor
  mlflow/catboost.py
  mlflow/h2o.py
  mlflow/lightgbm.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
  mlflow/shap.py
  mlflow/sklearn/__init__.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/utils/environment.py
  mlflow/xgboost.py
  tests/azureml/test_image_creation.py
  tests/catboost/test_catboost_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/helper_functions.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/models/test_cli.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/shap/test_log.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spark/test_spark_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/utils/test_environment.py
Labels: area/models, enable-dev-tests, rn/feature

#4491 Autolog post training metrics for sklearn
  mlflow/sklearn/__init__.py
  mlflow/utils/__init__.py
  mlflow/utils/autologging_utils/__init__.py
  tests/autologging/test_autologging_utils.py
  tests/autologging/test_training_session.py
  tests/sklearn/test_sklearn_autolog.py
  tests/utils/test_utils.py
Labels: area/tracking, enable-dev-tests, rn/feature

#4590 Disable autologging for sklearn cross_val_* APIs
  mlflow/sklearn/__init__.py
  tests/sklearn/test_sklearn_autolog.py
Labels: area/tracking, rn/bug-fix

#4292 Pytorch Ax HPO example - Readme Update
  examples/pytorch/AxHyperOptimizationPTL/MLproject
  examples/pytorch/AxHyperOptimizationPTL/README.md
  examples/pytorch/AxHyperOptimizationPTL/ax_hpo_iris.py
  examples/pytorch/AxHyperOptimizationPTL/screenshots/ax_hpo.png
  examples/pytorch/AxHyperOptimizationPTL/screenshots/parent_run.png
  examples/pytorch/AxHyperOptimizationPTL/screenshots/trial_run.png
Labels: area/examples, rn/none

#4622 Fix broken `protoc` download link
  .github/workflows/master.yml
Labels: rn/none

#4619 De-hardcode conda env file name
  mlflow/catboost.py
  mlflow/fastai.py
  mlflow/gluon.py
  mlflow/h2o.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/onnx.py
  mlflow/paddle/__init__.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
  mlflow/pytorch/__init__.py
  mlflow/shap.py
  mlflow/sklearn/__init__.py
  mlflow/spacy.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/tensorflow.py
  mlflow/utils/environment.py
  mlflow/xgboost.py
Labels: rn/none

#4621 Enable GitHub Actions concurrency feature to avoid queueing too many cross-version-tests runs
  .github/workflows/cross-version-tests.yml
Labels: rn/none

#4620 Deprecate `requriements_file` argument for pytorch flavor
  mlflow/pytorch/__init__.py
  tests/pytorch/test_pytorch_model_export.py
Labels: rn/feature

#4589 Added archive argument to the Sagemaker Batch Transform integration
  mlflow/sagemaker/__init__.py
  mlflow/sagemaker/cli.py
  tests/sagemaker/test_batch_deployment.py
Labels: integrations/sagemaker, rn/feature

#4629 Label definition adjustments for area/server-infra, area/scoring, and area/uiux
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/pull_request_template.md
  ISSUE_TRIAGE.rst
Labels: area/build, rn/none
