Repository mlflow/mlflow, pull requests merged in 2021-09, with the labels that each got.

#4764 Increase HTTP timeout to 90s. Disabled cloud storage HTTP timeout.
  mlflow/utils/rest_utils.py
  tests/projects/test_databricks.py
  tests/store/tracking/test_rest_store.py
  tests/utils/test_rest_utils.py
Labels: rn/bug-fix

#4765 Bump java version to 1.20.1
  mlflow/java/client/pom.xml
  mlflow/java/pom.xml
  mlflow/java/scoring/pom.xml
  mlflow/java/spark/pom.xml
Labels: rn/none, language/java, area/build

#4759 Enable auto dependency inference in spark flavor
  mlflow/spark.py
  mlflow/utils/_capture_modules.py
  mlflow/utils/requirements_utils.py
  tests/spark/test_spark_model_export.py
Labels: rn/none

#4768 Fix `test_autolog_emits_warning_message_when_model_prediction_fails`
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/none, enable-dev-tests

#4767 Use `sanity_checking` instead of `running_sanity_check` in pytorch-lightning > 1.4.5
  mlflow/pytorch/_pytorch_autolog.py
Labels: rn/none, enable-dev-tests

#4769 refactor: Extract the docker image building _build_image_from_context function
  mlflow/models/docker_utils.py
Labels: rn/none, area/models, area/docker

#4766 Fix autologging compatibility with Keras >= 2.6.0
  mlflow/keras.py
  mlflow/tracking/fluent.py
  mlflow/utils/import_hooks/__init__.py
  tests/tensorflow_autolog/test_tensorflow2_autolog.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/bug-fix, area/tracking

#4770 Update spark support version to be 3.2
  dev/set_matrix.py
  mlflow/ml-package-versions.yml
Labels: rn/none, area/tracking

#4777 Changelog message tweak
  CHANGELOG.rst
Labels: area/docs, rn/none

#4772 FIx small typo
  mlflow/sklearn/utils.py
Labels: rn/none

#4669 Push MLflow model to Sagemaker model registry
  mlflow/sagemaker/__init__.py
  mlflow/sagemaker/cli.py
Labels: rn/feature, integrations/sagemaker

#4780 Fix tensorflow dev cross test
  .github/workflows/cross-version-tests.yml
  tests/tensorflow/test_tensorflow2_model_export.py
Labels: rn/none, area/tracking, enable-dev-tests

#4784 replacing `tf.Session()` to `tf.compat.v1.Session()`
  examples/flower_classifier/train.py
Labels: rn/none, area/examples

#4788 Add a tags field to the CreateExperiment REST API
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
Labels: rn/feature, area/tracking

#4773 Add prophet flavor
  conftest.py
  dev/extra-ml-requirements.txt
  dev/run-python-flavor-tests.sh
  docs/source/models.rst
  docs/source/python_api/mlflow.prophet.rst
  docs/source/tutorials-and-examples/index.rst
  examples/prophet/MLproject
  examples/prophet/conda.yaml
  examples/prophet/predict.py
  examples/prophet/train.ipynb
  examples/prophet/train.py
  mlflow/__init__.py
  mlflow/prophet.py
  tests/examples/test_examples.py
  tests/prophet/test_prophet_model_export.py
Labels: rn/feature, area/examples, area/models, needs review

#4789 Fix RoxygenNote version
  mlflow/R/mlflow/DESCRIPTION
Labels: rn/none, area/build

#4746 [FR] Use mamba for creating environments
  mlflow/utils/conda.py
  tests/projects/test_projects.py
Labels: rn/feature, area/projects

#4670 GC CLI SFTP Support: implement delete_artifacts in sftp_artifact_repository
  mlflow/store/artifact/sftp_artifact_repo.py
  tests/store/artifact/test_sftp_artifact_repo.py
Labels: rn/feature, area/artifacts

#4797 Run `mleap` tests in cross version testing
  conftest.py
  dev/extra-ml-requirements.txt
  dev/run-python-sagemaker-tests.sh
  mlflow/ml-package-versions.yml
  pylintrc
  setup.py
  tests/mleap/test_mleap_model_export.py
Labels: rn/none

#4796 Fix default value for `verbose_eval` in lightgbm autologging
  tests/lightgbm/test_lightgbm_autolog.py
Labels: rn/none, enable-dev-tests

#4801 Fix PyTorch LightningDeprecationWarning ModelSummary
  mlflow/pytorch/_pytorch_autolog.py
Labels: rn/none, area/artifacts, enable-dev-tests

#4715 Upgraded fastai from v1 to v2 (>=2.4.1)
  dev/extra-ml-requirements.txt
  examples/README.md
  examples/fastai/README.md
  examples/fastai/conda.yaml
  examples/fastai/train.py
  mlflow/fastai/__init__.py
  mlflow/fastai/callback.py
  mlflow/ml-package-versions.yml
  mlflow/utils/autologging_utils/versioning.py
  tests/autologging/test_autologging_utils.py
  tests/examples/test_examples.py
  tests/fastai/test_fastai_autolog.py
  tests/fastai/test_fastai_model_export.py
Labels: rn/feature, area/models

#4731 Bug-Fix Issue #4732 Add client_cert_path and server_cert_path into model registry rest store utils
  mlflow/tracking/_model_registry/utils.py
Labels: rn/bug-fix, area/model-registry

#4795 Add experiment tags to experiment creation APIs
  docs/source/R-api.rst
  mlflow/R/mlflow/R/tracking-experiments.R
  mlflow/R/mlflow/man/mlflow_create_experiment.Rd
  mlflow/R/mlflow/tests/testthat/test-tracking-experiments.R
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowClient.java
  mlflow/java/client/src/test/java/org/mlflow/tracking/MlflowClientTest.java
  mlflow/server/handlers.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  tests/store/tracking/test_abstract_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/test_client.py
  tests/tracking/test_rest_tracking.py
Labels: rn/feature, area/tracking

#4809 Limit length of tag set by Spark datasource autologging
  mlflow/_spark_autologging.py
  mlflow/utils/__init__.py
  tests/spark_autologging/datasource/test_spark_datasource_autologging.py
Labels: rn/bug-fix

#4817 Catch `Exception` rather than `AtributeError` when extracting metrics from fitted model in statsmodels autologging
  mlflow/statsmodels.py
Labels: rn/none

#4002 Enable AzureDefaultCredential for authenticating against Azure Storage backends (closes #3998)
  dev/small-requirements.txt
  docs/source/tracking.rst
  mlflow/store/artifact/azure_blob_artifact_repo.py
  tests/store/artifact/test_azure_blob_artifact_repo.py
Labels: area/docs, rn/feature, area/artifacts

#4790 Remove mlflow.keras raise deprecation warning to avoid keras==2.4.3 tensorflow==2.5.1 issue
  mlflow/keras.py
  tests/keras/test_keras_model_export.py
Labels: rn/none

#4841 Fix `_get_installed_version` to avoid capturing undesired package versions
  mlflow/utils/requirements_utils.py
Labels: rn/none

#4846 Add roadmap links & info to README
  README.rst
Labels: rn/documentation, area/uiux, area/artifacts, area/models, area/scoring, area/tracking, integrations/sagemaker

#4840 Added a duration column to the runs table in the experiment UI. closes #4826
  mlflow/server/js/src/common/utils/Utils.js
  mlflow/server/js/src/common/utils/Utils.test.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentViewUtil.js
  mlflow/server/js/src/experiment-tracking/components/RunView.js
  mlflow/server/js/src/experiment-tracking/components/RunsTableColumnSelectionDropdown.test.js
Labels: rn/feature, area/uiux

#4843 improve pyspark ml log pretraining metadata error message:
  mlflow/pyspark/ml/__init__.py
  tests/spark_autologging/ml/test_pyspark_ml_autologging.py
Labels: rn/none, area/tracking

#4848 Added lifecycle stage to run page
  mlflow/server/js/src/experiment-tracking/components/RunView.js
Labels: rn/feature, area/uiux

#4834 Updating versions in mlflow docker example
  examples/docker/Dockerfile
Labels: rn/none, area/examples, area/docker

#4847 Visibility of default column sorting order. closes #4825
  mlflow/server/js/src/experiment-tracking/components/ExperimentPage.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentPage.test.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableCompactView.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.test.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentView.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentView.test.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentViewUtil.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentViewUtil.test.js
  mlflow/server/js/src/experiment-tracking/components/RunsTableColumnSelectionDropdown.js
  mlflow/server/js/src/experiment-tracking/components/RunsTableColumnSelectionDropdown.test.js
  mlflow/server/js/src/experiment-tracking/constants.js
  mlflow/server/js/src/experiment-tracking/sdk/MlflowLocalStorageMessages.js
Labels: rn/feature, area/uiux

#4857 Fix R doc lint failure
  mlflow/R/mlflow/man/mlflow-package.Rd
Labels: language/r, rn/none

#4838 Shallow git fetch before mlflow run
  mlflow/projects/utils.py
  tests/projects/conftest.py
  tests/projects/test_utils.py
  tests/projects/utils.py
Labels: rn/none, area/projects
