Repository mlflow/mlflow, pull requests merged in 2022-02, with the labels that each got.

#5306 Condense run comparison table
  mlflow/server/js/src/experiment-tracking/components/CompareRunView.css
  mlflow/server/js/src/experiment-tracking/components/CompareRunView.js
Labels: rn/feature, area/tracking

#5346 MLflow UI updates
  .gitattributes
  mlflow/server/js/.env
  mlflow/server/js/package.json
  mlflow/server/js/src/common/components/CollapsibleTagsCell.jsx
  mlflow/server/js/src/common/components/CollapsibleTagsCell.test.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentPage.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentView.js
  mlflow/server/js/src/model-registry/components/SchemaTable.js
Labels: rn/none, area/uiux

#5345 add test for pandas df evaluate submission and type definition handling
  mlflow/models/evaluation/base.py
  tests/models/test_evaluation.py
Labels: rn/bug-fix, area/models

#5347 Add warning in MLflow pytorch docs to include signature
  mlflow/pytorch/__init__.py
Labels: area/docs, rn/none, autoformat

#5355 Record logged Spark model
  mlflow/spark.py
  tests/spark/test_spark_model_export.py
Labels: rn/bug-fix, area/models, area/tracking

#5362 Fix debug logging
  mlflow/utils/logging_utils.py
  tests/utils/test_logging_utils.py
Labels: rn/bug-fix, area/build

#5367 Return None in get_workspace_info_from_dbutils if error
  mlflow/utils/databricks_utils.py
Labels: rn/none, integrations/databricks

#5333 Add developer guide for building model evaluation plugins
  docs/source/plugins.rst
  tests/resources/mlflow-test-plugin/setup.py
Labels: area/docs, rn/documentation

#5366 Add support for minor version incremental increase for pyspark
  mlflow/utils/autologging_utils/versioning.py
  tests/autologging/test_autologging_utils.py
Labels: rn/bug-fix, integrations/databricks

#5357 Create SECURITY.md
  SECURITY.md
Labels: rn/none

#5359 Parallelize download of artifacts and improve performance of downloading large models.
  mlflow/store/artifact/artifact_repo.py
  mlflow/store/artifact/databricks_artifact_repo.py
  tests/store/artifact/test_artifact_repo.py
  tests/store/artifact/test_databricks_artifact_repo.py
Labels: rn/bug-fix, area/artifacts

#5375 Fix pytorch test exception assert
  tests/pytorch/test_pytorch_model_export.py
Labels: rn/none, area/build

#5363 Increase Docker API requests timeout on image push
  mlflow/projects/kubernetes.py
Labels: rn/bug-fix

#5368 Warning for dependency mismatches
  mlflow/pyfunc/__init__.py
  mlflow/utils/requirements_utils.py
  tests/helper_functions.py
  tests/pyfunc/test_spark.py
  tests/pyfunc/test_warn_dependency_requirement_mismatches.py
Labels: rn/feature, area/tracking

#5384 store/artifact/mlflow: fix resolved path order
  mlflow/store/artifact/mlflow_artifacts_repo.py
Labels: rn/bug-fix, area/artifacts

#5385 store/artifact/mlflow: utilize netloc over host:port
  mlflow/store/artifact/mlflow_artifacts_repo.py
Labels: rn/bug-fix, area/artifacts

#5348 Update logged workspace url
  mlflow/tracking/context/databricks_job_context.py
  mlflow/tracking/context/databricks_notebook_context.py
  mlflow/utils/databricks_utils.py
  tests/tracking/context/test_databricks_job_context.py
  tests/tracking/context/test_databricks_notebook_context.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/none, area/tracking, integrations/databricks

#4971 Move the code that deploys a SageMaker Endpoint to a plugin that implements BaseDeploymentClient
  docs/source/conf.py
  mlflow/deployments/base.py
  mlflow/deployments/cli.py
  mlflow/deployments/interface.py
  mlflow/deployments/plugin_manager.py
  mlflow/sagemaker/__init__.py
  tests/deployments/test_cli.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/fake_deployment_plugin.py
  tests/sagemaker/test_deployment.py
  tests/sagemaker/test_sagemaker_deployment_client.py
Labels: rn/feature, area/scoring, integrations/sagemaker

#5210 Uniquely-named directory was always created for hdfs artifact repo
  mlflow/store/artifact/hdfs_artifact_repo.py
Labels: rn/bug-fix, area/artifacts, area/tracking

#5382 Fix #5360
  mlflow/store/tracking/sqlalchemy_store.py
  tests/db/run_checks.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/bug-fix, area/sqlalchemy, area/server-infra

#5403 Fix XGBoost autologging for metrics with @
  mlflow/xgboost/_autolog.py
  tests/xgboost/test_xgboost_autolog.py
Labels: rn/bug-fix, area/tracking

#5401 add cross version testing for prophet
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#5399 Replace `continuumio/miniconda3` image with `condaforge/miniforge3` image
  Dockerfile
  examples/docker/Dockerfile
  tests/resources/example_docker_project/Dockerfile
Labels: rn/none

#5406 Fix log matplot figure bug
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: rn/bug-fix, area/artifacts

#5373 Pmdarima flavor
  conftest.py
  dev/run-python-flavor-tests.sh
  docs/source/models.rst
  docs/source/python_api/mlflow.pmdarima.rst
  docs/source/tutorials-and-examples/index.rst
  examples/pmdarima/MLproject
  examples/pmdarima/conda.yaml
  examples/pmdarima/train.py
  mlflow/__init__.py
  mlflow/ml-package-versions.yml
  mlflow/pmdarima.py
  mlflow/prophet.py
  mlflow/xgboost/_autolog.py
  requirements/extra-ml-requirements.txt
  tests/examples/test_examples.py
  tests/pmdarima/__init__.py
  tests/pmdarima/test_pmdarima_model_export.py
Labels: area/docs, rn/feature, area/examples, area/models, enable-dev-tests

#5395 Add model registration argument for autolog
  mlflow/fastai/__init__.py
  mlflow/fastai/callback.py
  mlflow/gluon/__init__.py
  mlflow/gluon/_autolog.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/paddle/__init__.py
  mlflow/paddle/_paddle_autolog.py
  mlflow/pyspark/ml/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_pytorch_autolog.py
  mlflow/sklearn/__init__.py
  mlflow/statsmodels.py
  mlflow/tensorflow/__init__.py
  mlflow/tensorflow/_autolog.py
  mlflow/xgboost/__init__.py
  tests/fastai/test_fastai_autolog.py
  tests/gluon/test_gluon_autolog.py
  tests/keras/test_keras_autolog.py
  tests/lightgbm/test_lightgbm_autolog.py
  tests/paddle/test_paddle_autolog.py
  tests/pytorch/test_pytorch_autolog.py
  tests/sklearn/test_sklearn_autolog.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
  tests/statsmodels/test_statsmodels_autolog.py
  tests/tensorflow/test_tensorflow2_autolog.py
  tests/xgboost/test_xgboost_autolog.py
Labels: rn/feature, area/tracking

#5409 Fix ListArtifacts and get-artifact compatibility errors with proxied artifacts
  examples/mlflow_artifacts/example.py
  mlflow/server/handlers.py
  mlflow/store/artifact/artifact_repository_registry.py
  tests/tracking/test_mlflow_artifacts.py
Labels: rn/bug-fix, area/artifacts

#5389 [Custom Metrics] Enabled support for logging of numerical metrics
  examples/evaluation/evaluate_with_custom_metrics.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  tests/models/test_default_evaluator.py
  tests/models/test_evaluation.py
Labels: rn/feature, area/tracking

#5411 Adding support for multiclass models or models returning multiple probabilities in fastai and the pyfunc flavor
  mlflow/fastai/__init__.py
Labels: rn/bug-fix, area/models

#5396 Implement the `predict()` function for SageMaker deployment plugin
  mlflow/sagemaker/__init__.py
  tests/sagemaker/test_sagemaker_deployment_client.py
Labels: rn/feature, area/scoring, integrations/sagemaker

#5431 Add script to validate release version
  dev/validate_release_version.py
Labels: rn/none, area/build

#5422 fix: Use Python's default protocol version when pickling
  mlflow/sklearn/__init__.py
Labels: rn/none
