Repository mlflow/mlflow, pull requests merged in 2022-05, with the labels that each got.

#5807 Pass in the `pos_label` parameter to `eval_and_log_metrics`
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/feature, area/tracking

#5810 Update broken link in "Fastai" section
  docs/source/models.rst
Labels: rn/none

#5805 Adjust auto generated image sizes and formatting
  mlflow/models/evaluation/default_evaluator.py
  mlflow/sklearn/utils.py
  tests/models/test_default_evaluator.py
Labels: rn/none, area/tracking

#5812 Fix log_artifact for large model in HDFS
  mlflow/store/artifact/hdfs_artifact_repo.py
  tests/store/artifact/test_hdfs_artifact_repo.py
Labels: rn/bug-fix, area/artifacts, area/model-registry

#5816 PyTorch examples - MNIST and Bert multi gpu training
  examples/pytorch/BertNewsClassification/MLproject
  examples/pytorch/BertNewsClassification/README.md
  examples/pytorch/BertNewsClassification/bert_classification.py
  examples/pytorch/BertNewsClassification/conda.yaml
  examples/pytorch/MNIST/MLproject
  examples/pytorch/MNIST/README.md
  examples/pytorch/MNIST/mnist_autolog_example.py
Labels: rn/none, area/examples

#5811 Added mechanism to delete artifacts from GCS repository using MLFlow garbage collection
  mlflow/store/artifact/gcs_artifact_repo.py
  tests/store/artifact/test_gcs_artifact_repo.py
Labels: rn/feature, area/artifacts

#5650 Add configuration warning for --artifacts-only server initialization
  mlflow/cli.py
  mlflow/utils/server_cli_utils.py
  mlflow/utils/uri.py
  tests/test_cli.py
Labels: rn/none, area/server-infra

#5818 [FIX-5789] Added sticky header to experiment run list
  mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js
Labels: rn/feature, area/uiux

#5663 Scoring server timeout #5381
  mlflow/models/cli.py
  mlflow/models/flavor_backend.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/backend.py
  mlflow/pyfunc/mlserver.py
  mlflow/pyfunc/scoring_server/__init__.py
  mlflow/rfunc/backend.py
  mlflow/utils/cli_args.py
  tests/pyfunc/test_mlserver.py
  tests/pyfunc/test_scoring_server.py
  tests/pyfunc/test_spark.py
Labels: area/docs, rn/feature, rn/documentation, area/scoring

#5825 Fix tf-serving parsing when input are columnar formatter
  mlflow/utils/proto_json_utils.py
  tests/utils/test_proto_json_utils.py
Labels: rn/bug-fix, area/scoring

#5725 Update ag-grid and implement getRowId to improve runs table performance
  mlflow/server/js/package.json
  mlflow/server/js/src/common/utils/Utils.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.test.js
  mlflow/server/js/src/experiment-tracking/reducers/Reducers.js
  mlflow/server/js/yarn.lock
Labels: rn/bug-fix, area/uiux, area/tracking

#5834 Add `run-dev-server.sh` to quickly launch development server from repository root
  dev/run-dev-server.sh
Labels: rn/none, area/tracking

#5824 Update mlflow.set_tracking_uri to support pathlib.Path (#5820)
  docs/source/conf.py
  mlflow/tracking/_tracking_service/utils.py
  tests/tracking/_tracking_service/test_utils.py
Labels: rn/feature, area/tracking

#5717 Dev env setup script
  .github/workflows/dev-setup.yml
  CONTRIBUTING.rst
  dev/dev-env-setup.sh
  dev/test-dev-env-setup.sh
Labels: area/docs, rn/feature, area/build

#5826 Spark Datasource autologging: Fix REPL ID propagation from datasource listener to publisher
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/ReplAwareSparkDataSourceListener.scala
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/SparkDataSourceListener.scala
  mlflow/java/spark/src/test/scala/org/mlflow/spark/autologging/SparkAutologgingIntegrationSuite.scala
Labels: rn/bug-fix, area/tracking

#5731 Add endpoint changes to the deployment CLI.
  mlflow/deployments/cli.py
Labels: rn/feature, area/scoring

#5842 Avoid appending `--env-manager` when `env_manager` is `None` in `_get_cluster_mlflow_run_cmd`
  mlflow/projects/databricks.py
Labels: rn/none

#5829 Refactor `ExperimentListView` using `@databricks/design-system`'s `Tree` component
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.css
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.test.js
  mlflow/server/js/src/experiment-tracking/components/HomeView.js
Labels: rn/none, area/uiux

#5845 Fix tests for SFTP artifact repository
  .github/workflows/master.yml
  dev/run-small-python-tests.sh
  tests/store/artifact/test_sftp_artifact_repo.py
Labels: rn/none

#5854 Pin some ML dependencies to prevent pip from filling up diskspace while resolving dependencies
  dev/install-common-deps.sh
  requirements/extra-ml-requirements.txt
Labels: rn/none

#5853 Fix `validate_docker_installation` to throw when docker daemon is not running
  mlflow/projects/docker.py
Labels: rn/none, area/projects, area/docker

#5859 Fix bug where clicking mlflow logo returns "No Experiments Exist"
  mlflow/server/js/src/experiment-tracking/components/HomeView.js
  mlflow/server/js/src/experiment-tracking/components/HomeView.test.js
Labels: rn/none, area/uiux

#5858 Update MLflow UI
  mlflow/server/js/.eslintrc.js
  mlflow/server/js/.storybook/main.js
  mlflow/server/js/.storybook/preview.js
  mlflow/server/js/package.json
  mlflow/server/js/src/common/styles/color.js
  mlflow/server/js/src/common/utils/Utils.js
  mlflow/server/js/src/experiment-tracking/components/App.js
  mlflow/server/js/src/experiment-tracking/components/ArtifactView.css
  mlflow/server/js/src/experiment-tracking/components/ExperimentPage.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentView.css
  mlflow/server/js/src/experiment-tracking/components/ExperimentViewHelpers.js
  mlflow/server/js/src/experiment-tracking/components/RunView.css
  mlflow/server/js/src/experiment-tracking/components/RunView.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactHtmlView.css
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactHtmlView.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactImageView.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactLoggedModelView.css
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactLoggedModelView.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactMapView.css
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactPdfView.css
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactTextView.css
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactTextView.js
  mlflow/server/js/src/experiment-tracking/reducers/Reducers.js
  mlflow/server/js/src/i18n/default/en.json
  mlflow/server/js/src/model-registry/routes.js
  mlflow/server/js/src/model-registry/utils.js
  mlflow/server/js/src/shared/building_blocks/PageHeader.jsx
  mlflow/server/js/src/shared/colors.js
  mlflow/server/js/yarn.lock
Labels: rn/none, area/uiux

#5843 Add `Related Issues/PRs` section in pull request template
  .github/pull_request_template.md
Labels: rn/none

#5869 Set sklearn max support version to be 1.1.0
  mlflow/ml-package-versions.yml
Labels: area/tracking

#5870 Set sklearn max support version to be 1.1.0
  mlflow/ml-package-versions.yml
Labels: rn/none

#5874 Replace `ACCOUNT_ID` with `get_account_id`
  tests/sagemaker/mock/__init__.py
Labels: rn/none, integrations/sagemaker

#5875 Replace `unittest.TestCase.assertRaises` with `unittest.TestCase.assertRaisesRegex`
  pylint_plugins/unittest_assert_raises.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#5879 Replace `npm` with `yarn`
  .github/ISSUE_TEMPLATE/bug_report_template.yaml
  CONTRIBUTING.rst
Labels: rn/none

#5865 Automatically find minimum required python version for ML package in cross version test
  .github/workflows/cross-version-tests.yml
  dev/get_minimum_required_python.py
Labels: rn/none, enable-dev-tests

#5886 Fix `test_get_params_returns_dict_that_has_more_keys_than_max_params_tags_per_bat`
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/none, area/build, enable-dev-tests

#5890 Pin `roxygen2` to fix `build_doc_r` failure
  mlflow/R/mlflow/.build-doc.R
Labels: rn/none, area/build

#5893 Removed redundant spaces
  examples/multistep_workflow/load_raw_data.py
  mlflow/azureml/__init__.py
  mlflow/models/docker_utils.py
  mlflow/sagemaker/__init__.py
  mlflow/tracking/fluent.py
  mlflow/utils/search_utils.py
Labels: rn/none, area/tracking

#5891 Revert #5657
  mlflow/pyfunc/model.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/none, area/models

#5888 Add UI bug template
  .github/ISSUE_TEMPLATE/images/console-panel.png
  .github/ISSUE_TEMPLATE/images/network-panel.png
  .github/ISSUE_TEMPLATE/ui_bug_report_template.yaml
Labels: rn/none, area/build

#5889 Use HEAD branch when running a git project
  mlflow/projects/utils.py
Labels: rn/bug-fix, area/projects

#5912 Improve readability of motivation section in feature request.
  .github/ISSUE_TEMPLATE/feature_request_template.yaml
Labels: rn/none

#5910 Remove unnecessary lines in tests/test_skinny_client_omits_sql_libs.py
  tests/test_skinny_client_omits_sql_libs.py
Labels: rn/none, area/build

#5909 fixed infered typo to inferred
  mlflow/models/evaluation/default_evaluator.py
Labels: rn/none

#5900 Make ImageEvaluationArtifact instance close image once GCed
  mlflow/models/evaluation/artifacts.py
Labels: rn/none, area/tracking

#5914 Fix `unittest-assert-raises` pylint errors
  pylint_plugins/unittest_assert_raises.py
  tests/entities/test_run_status.py
  tests/store/db/test_utils.py
  tests/store/tracking/__init__.py
  tests/store/tracking/test_file_store.py
Labels: rn/none, area/build

#5919 Disable estimator parameter validation in `scikit-learn >= 1.2.0`, not `scikit-learn > 1.1.0`
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/none

#5929 Fixed typos in `tests/generate_ui_test_data.py`
  tests/generate_ui_test_data.py
Labels: rn/none

#5930 Modify `.[extras]` with single quotes
  CONTRIBUTING.rst
Labels: rn/none

#5921 Fix `get_model_dependencies` to support models URI containing artifact path
  mlflow/store/artifact/models_artifact_repo.py
  mlflow/tracking/artifact_utils.py
  tests/pyfunc/test_dependencies_functions.py
  tests/store/artifact/test_models_artifact_repo.py
Labels: rn/bug-fix, area/tracking

#5932 Fix `disable_validate_params` condition
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/none, area/build, enable-dev-tests

#5903 Make `DefaultEvaluator` log sklearn model score if model is scorable
  mlflow/models/evaluation/default_evaluator.py
  tests/models/test_default_evaluator.py
Labels: rn/feature, area/tracking

#5906 Improve UI bug template
  .github/ISSUE_TEMPLATE/ui_bug_report_template.yaml
Labels: rn/none

#5935 Add doc for DefaultEvaluator logging sklearn model score metric
  mlflow/models/evaluation/base.py
Labels: rn/documentation

#5940 Remove `pytest tests/sagemaker/mock` in `dev/run-python-sagemaker-tests.sh`
  dev/run-python-sagemaker-tests.sh
Labels: rn/none, integrations/sagemaker

#5937 Increase repl timeout for Java test suite
  mlflow/java/spark/pom.xml
  mlflow/java/spark/src/test/scala/org/mlflow/spark/autologging/SparkAutologgingIntegrationSuite.scala
Labels: rn/none, language/java, area/build

#5907 Show run ID on Run page
  mlflow/server/js/src/experiment-tracking/components/RunView.js
  mlflow/server/js/src/i18n/default/en.json
Labels: rn/none, area/uiux

#5941 Run pyfunc tests in a separate job
  .github/workflows/master.yml
  dev/run-python-flavor-tests.sh
  tests/helper_functions.py
Labels: rn/none, area/build

#5942 Merge `large-requirements.txt` and `small-requirements.txt`
  .dockerignore
  .github/workflows/cross-version-tests.yml
  .github/workflows/examples.yml
  .github/workflows/master.yml
  CONTRIBUTING.rst
  EXTRA_DEPENDENCIES.rst
  dev/dev-env-setup.sh
  dev/install-common-deps.sh
  dev/setup-spark-datasource-autologging.sh
  requirements/dev-requirements.txt
  requirements/extra-ml-requirements.txt
  requirements/large-requirements.txt
  requirements/test-requirements.txt
Labels: rn/none, area/build

#5943 fix shebang for commit msg hook
  hooks/prepare-commit-msg
Labels: rn/none

#5945 Regenerate protos using protoc 3.19.4
  .github/workflows/master.yml
  .github/workflows/r.yml
  dev/Dockerfile.protos
  dev/generate-protos.sh
  mlflow/R/mlflow/.create-test-env.R
  mlflow/java/client/src/main/java/com/databricks/api/proto/databricks/Databricks.java
  mlflow/java/client/src/main/java/com/databricks/api/proto/mlflow/DatabricksArtifacts.java
  mlflow/java/client/src/main/java/org/mlflow/api/proto/MlflowArtifacts.java
  mlflow/java/client/src/main/java/org/mlflow/api/proto/ModelRegistry.java
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/java/client/src/main/java/org/mlflow/scalapb_interface/Scalapb.java
  mlflow/java/pom.xml
  mlflow/protos/databricks_artifacts_pb2.py
  mlflow/protos/databricks_pb2.py
  mlflow/protos/mlflow_artifacts_pb2.py
  mlflow/protos/model_registry_pb2.py
  mlflow/protos/scalapb/scalapb_pb2.py
  mlflow/protos/service_pb2.py
  tests/helper_functions.py
  tests/models/test_cli.py
  tests/paddle/test_paddle_model_export.py
  tests/protos/test_message_pb2.py
  tests/pyfunc/test_spark.py
  tests/resources/example_virtualenv_conda_project/conda.yaml
  tests/resources/example_virtualenv_project/requirements.txt
  tests/test_cli.py
Labels: rn/none

#5947 Disable autologging during `mlflow.evaluate`
  mlflow/models/evaluation/default_evaluator.py
  tests/models/test_default_evaluator.py
Labels: rn/none, area/tracking

#5957 Recommend pull requests be filed from non-master branch
  .github/pull_request_template.md
  CONTRIBUTING.rst
Labels: area/docs, rn/none

#5959 Improve readability
  CONTRIBUTING.rst
  dev/dev-env-setup.sh
  dev/get_minimum_required_python.py
  dev/set_matrix.py
  docs/source/models.rst
  examples/README.md
  examples/pytorch/CaptumExample/README.md
  examples/pytorch/IterativePruning/README.md
  mlflow/models/evaluation/default_evaluator.py
  mlflow/projects/__init__.py
  mlflow/pyspark/ml/__init__.py
  mlflow/server/js/README.md
  mlflow/sklearn/__init__.py
  mlflow/statsmodels.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/rest_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/client.py
  mlflow/utils/gorilla.py
  tests/pyfunc/test_spark.py
  tests/sagemaker/test_deployment.py
  tests/sagemaker/test_sagemaker_deployment_client.py
  tests/sklearn/test_sklearn_autolog.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
  tests/store/artifact/test_artifact_repository_registry.py
  tests/store/model_registry/test_rest_store.py
  tests/tracking/_tracking_service/test_utils.py
  tests/tracking/context/test_registry.py
  tests/tracking/default_experiment/test_registry.py
  tests/tracking/request_header/test_registry.py
  tests/tracking/test_client.py
Labels: rn/documentation

#5926 Fix two models one code name #5923
  mlflow/utils/model_utils.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/feature, area/models

#5965 Update setup.py to require minimum protobuf version that is compatible with protoc 3.19.4
  setup.py
Labels: rn/bug-fix, area/build

#5969 modified bug_report_template.yaml
  .github/ISSUE_TEMPLATE/bug_report_template.yaml
Labels: rn/none

#5980 Removed StringIo Import StringIo
  mlflow/pyfunc/scoring_server/__init__.py
  tests/models/test_cli.py
  tests/pyfunc/test_scoring_server.py
Labels: rn/none

#5983 Fix typo
  tests/helper_functions.py
Labels: rn/none

#5982 Update test_keras_autolog.py
  tests/keras/test_keras_autolog.py
Labels: rn/none

#5981 Fix typo occured -> occurred
  mlflow/exceptions.py
Labels: rn/none

#5986 Fix typo
  mlflow/utils/environment.py
  tests/utils/test_python_env.py
Labels: rn/none

#5984 Add problem matcher for black
  .github/workflows/master.yml
  .github/workflows/matchers/black.json
Labels: rn/none, area/build

#5972 Pin `protobuf` in cross-version test
  dev/set_matrix.py
  mlflow/ml-package-versions.yml
  tests/keras/test_keras_model_export.py
  tests/tensorflow/test_tensorflow2_model_export.py
Labels: rn/none, area/build

#5974 Refactor `tests/test_mlflow_lazily_imports_ml_packages.py`
  .github/workflows/master.yml
  conftest.py
  dev/run-python-flavor-tests.sh
  pytest.ini
  tests/test_mlflow_lazily_imports_ml_packages.py
Labels: rn/none, area/build

#5988 Merge pytest commands in `dev/run-python-skinny-tests.sh`
  dev/run-python-skinny-tests.sh
Labels: rn/none

#5999 Changed to python3 style super() without arguments
  mlflow/sagemaker/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/utils/autologging_utils/safety.py
  tests/onnx/test_onnx_model_export.py
  tests/paddle/test_paddle_model_export.py
Labels: rn/none

#5991 Fix flaky test `test_score_model_as_spark_udf`
  tests/keras/test_keras_model_export.py
  tests/pyfunc/test_spark.py
Labels: rn/none, area/scoring

#6002 Fix typos
  mlflow/tracking/fluent.py
Labels: rn/none

#6005 fix typo
  tests/utils/test_utils.py
Labels: rn/none

#6006 Improve Python files readability r2
  examples/flower_classifier/train.py
  examples/pytorch/BertNewsClassification/bert_classification.py
  examples/pytorch/CaptumExample/Titanic_Captum_Interpret.py
  examples/pytorch/mnist_tensorboard_artifact.py
  mlflow/fastai/__init__.py
  mlflow/models/evaluation/base.py
  mlflow/models/signature.py
  mlflow/onnx.py
  mlflow/pyfunc/scoring_server/__init__.py
  mlflow/utils/autologging_utils/safety.py
Labels: rn/none

#6007 fix typo
  mlflow/utils/requirements_utils.py
Labels: rn/none

#5962 Update PR template to remind users to write tests
  .github/pull_request_template.md
Labels: area/docs, rn/none
