Repository mlflow/mlflow, pull requests merged in 2022-12, with the labels that each got.

#7432 fix sftp delete artifacts incorrect path
  mlflow/store/artifact/sftp_artifact_repo.py
Labels: rn/none, area/artifacts

#7436 Replace `--artifact-destination-root` with `--artifact-destination`
  docs/source/tracking.rst
Labels: rn/none

#7430 Improve black pre-commit hook
  .github/workflows/autoformat.yml
  .github/workflows/master.yml
  .gitignore
  .pre-commit-config.yaml
  dev/black.sh
Labels: rn/none

#7440 Do not fail fast jobs in `js` workflow
  .github/workflows/js.yml
Labels: rn/none

#7240 Report SQLAlchemy OperationalError as a retryable HTTP error (503) not 400
  mlflow/store/db/utils.py
  tests/db/test_tracking_operations.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/bug-fix, area/sqlalchemy, area/server-infra

#7435 Fix torch examples and tests that are broken by incompatible torchmetrics accuracy API change
  examples/pytorch/AxHyperOptimizationPTL/iris.py
  examples/pytorch/IterativePruning/mnist.py
  examples/pytorch/MNIST/mnist_autolog_example.py
  tests/pytorch/iris.py
Labels: rn/none, area/examples

#7447 add unittest for path_not_unique
  tests/utils/test_validation.py
Labels: rn/none

#7428 Adding search registered models
  mlflow/__init__.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/feature, area/model-registry

#7450 Add `test-code-block` directive to test code examples in docstring
  .circleci/config.yml
  docs/.gitignore
  docs/Makefile
  docs/conftest.py
  docs/source/conf.py
  docs/source/test_code_block.py
  mlflow/tracking/_tracking_service/utils.py
Labels: rn/none

#7404 Prevent nested xgboost / lightgbm model being autologged
  mlflow/lightgbm.py
  mlflow/pyspark/ml/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/xgboost/__init__.py
  tests/autologging/test_training_session.py
  tests/lightgbm/test_lightgbm_autolog.py
  tests/xgboost/test_xgboost_autolog.py
Labels: rn/bug-fix, area/tracking

#7449 Fix `--artifact-destination` to `--artifacts-destination`
  docs/source/tracking.rst
  mlflow/utils/cli_args.py
Labels: rn/none

#7441 Add example for unwrap_python_model() method
  mlflow/pyfunc/__init__.py
Labels: rn/none

#7454 Use `pytest.mark.parameterize` for simple validation tests
  tests/utils/test_validation.py
Labels: rn/none

#7453 Separate package installation in `build_doc_r`
  mlflow/R/mlflow/.build-doc.R
  mlflow/R/mlflow/.install-deps.R
Labels: rn/none

#7451 Adding support for table format to allow spacing in column names
  mlflow/recipes/steps/predict.py
Labels: rn/none, area/recipes

#7464 Move fluent `search_registered_models` in `mlflow/tracking/_model_registry/fluent.py`
  mlflow/__init__.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/fluent.py
Labels: rn/none

#7467 Fix cross-version test order
  dev/set_matrix.py
Labels: rn/none, only-latest

#7433 Allow environment variable and tag specification for models deployed via MLflow SageMaker integration
  mlflow/deployments/cli.py
  mlflow/sagemaker/__init__.py
  tests/sagemaker/mock/__init__.py
  tests/sagemaker/test_sagemaker_deployment_client.py
Labels: rn/feature, integrations/sagemaker

#7469 Add custom `use-f-string` rule
  pylint_plugins/__init__.py
  pylint_plugins/errors.py
  pylint_plugins/string_checker.py
  pylint_plugins/tests/test_string_checker.py
Labels: rn/none

#7470 Remove duplicate problem matchers
  .github/workflows/js.yml
Labels: rn/none

#6966 Fix URI handling in mleap; test mleap on Windows
  .github/workflows/master.yml
  mlflow/mleap.py
  mlflow/utils/file_utils.py
  tests/mleap/test_mleap_model_export.py
Labels: rn/bug-fix, area/models

#7484 Fix tensorflow dev version for multi-dim pyfunc scoring test suite
  tests/tensorflow/test_keras_pyfunc_model_works_with_all_input_types.py
Labels: rn/none, area/build

#7486 Adjust tolerance thresholds for TF DNN model in test suite
  tests/tensorflow/test_load_saved_tensorflow_estimator.py
Labels: rn/none, area/build

#7485 Fix test failures for deprecations in scikit-learn 1.20.0
  examples/pytorch/BertNewsClassification/conda.yaml
  examples/pytorch/BertNewsClassification/python_env.yaml
  tests/shap/test_log.py
Labels: rn/none, area/build

#7461 Unitest2pytest entities file info
  tests/entities/conftest.py
  tests/entities/test_experiment.py
  tests/entities/test_file_info.py
  tests/entities/test_param.py
  tests/entities/test_run.py
  tests/entities/test_run_data.py
  tests/entities/test_run_info.py
Labels: rn/none

#7487 Add more examples to runs search docs page
  docs/source/search-runs.rst
Labels: area/docs, rn/documentation

#7499 Fix additional broken references in examples for deprecated sklearn library
  examples/pytorch/CaptumExample/python_env.yaml
  examples/pytorch/torchscript/IrisClassification/python_env.yaml
Labels: rn/none, area/examples, area/build

#7492 Add runs search aliases for run name and start time to correspond to UI column names
  docs/source/search-runs.rst
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/utils/search_utils.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/feature, area/tracking

#7498 Change volume of test validation data for shap logging suite
  tests/shap/test_log.py
Labels: rn/none, area/build

#7504 Convert `.. code-block:: python` to `.. test-code-block:: python` in mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/_model_registry/fluent.py
Labels: rn/none

#7479 FTP password with spacial url-encoding characters parsing error when using FTP as artifact root
  mlflow/store/artifact/ftp_artifact_repo.py
Labels: rn/bug-fix, area/artifacts

#7509 Fix TF test for change to lazy validation of custom objects
  tests/tensorflow/test_keras_model_export.py
Labels: rn/none, area/build

#7517 Support Model.load() from remote locations
  mlflow/models/model.py
  tests/models/test_model.py
Labels: rn/feature, area/models

#7415 Add Python client support for automated pagination to GetMetricHistory for REST Store
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
  mlflow/store/entities/paged_list.py
  mlflow/store/tracking/__init__.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/_tracking_service/client.py
  tests/store/tracking/test_abstract_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_rest_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/feature, area/tracking

#7496 Move from pkg_resources to importlib
  mlflow/pyspark/ml/__init__.py
  mlflow/utils/autologging_utils/versioning.py
  mlflow/utils/import_hooks/__init__.py
Labels: rn/none, area/models, area/tracking

#7523 Add support for client pagination in GetMetricHistory to the R API
  CONTRIBUTING.md
  docs/source/R-api.rst
  mlflow/R/mlflow/R/databricks-utils.R
  mlflow/R/mlflow/R/tracking-runs.R
  mlflow/R/mlflow/man/build_context_tags_from_databricks_job_info.Rd
  mlflow/R/mlflow/man/build_context_tags_from_databricks_notebook_info.Rd
  mlflow/R/mlflow/man/mlflow_search_runs.Rd
  mlflow/R/mlflow/tests/testthat/test-tracking-runs.R
  mlflow/R/mlflow/tests/testthat/test/crate.bin
Labels: language/r, rn/feature, area/tracking, only-latest

#7511 Added getRegisteredModel method to Java MlflowClient (#6602)
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowClient.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowProtobufMapper.java
  mlflow/java/client/src/test/java/org/mlflow/tracking/ModelRegistryMlflowClientTest.java
Labels: rn/feature, language/java, area/model-registry

#7527 Support result_type=StructType for mlflow.pyfunc.spark_udf
  docs/source/models.rst
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_spark.py
Labels: rn/feature, area/scoring

#7529 Remove unused dev/lint.sh script
  dev/lint.sh
Labels: rn/none, area/build

#7534 fix a bug in the code example of comments
  mlflow/tracking/client.py
Labels: area/docs

#7489 [ML-25726] Support mlflowdbfs with infer_pip_requirements
  mlflow/spark.py
  tests/spark/test_spark_model_export.py
Labels: rn/none, area/artifacts, integrations/databricks

#7538 Updating early_stop function to support custom function from steps.train
  mlflow/recipes/steps/train.py
Labels: rn/bug-fix, area/recipes

#7533 Add support for client pagination in GetMetricHistory to the Java API
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowClient.java
  mlflow/java/client/src/test/java/org/mlflow/tracking/MlflowClientTest.java
Labels: rn/none

#7462 Adding links to searching runs with user_id and life cycle stage
  mlflow/server/js/src/common/utils/StringUtils.js
  mlflow/server/js/src/experiment-tracking/components/RunView.js
  mlflow/server/js/src/experiment-tracking/routes.js
Labels: rn/feature, area/uiux, area/server-infra

#7531 Add doc for PyFuncModel and spark_udf supporting multi-dimensional array input
  docs/source/models.rst
  mlflow/pyfunc/__init__.py
Labels: rn/documentation, area/scoring

#7540 fix dataframe_split typo
  docs/source/models.rst
Labels: area/docs, rn/documentation

#7541 Hide `Edit on GitHub` link
  docs/theme/mlflow/breadcrumbs.html
Labels: area/docs, rn/none

#7542 Fix badge image URLs on README
  README.rst
Labels: rn/none

#7539 Remove `mlflow/R/mlflow/tests/testthat/test/crate.bin`
  mlflow/R/mlflow/.gitignore
  mlflow/R/mlflow/tests/testthat/test/crate.bin
Labels: rn/none

#7546 Show test-code block location in pytest report
  docs/source/test_code_block.py
Labels: rn/none

#7526 Fix order of features
  docs/source/tutorials-and-examples/tutorial.rst
Labels: area/docs, rn/none

#7458 Support multi-class classification
  mlflow/recipes/step.py
  mlflow/recipes/steps/automl/flaml.py
  mlflow/recipes/steps/evaluate.py
  mlflow/recipes/steps/ingest/__init__.py
  mlflow/recipes/steps/predict.py
  mlflow/recipes/steps/split.py
  mlflow/recipes/steps/train.py
  mlflow/recipes/steps/transform.py
  mlflow/recipes/utils/metrics.py
  mlflow/recipes/utils/step.py
  tests/recipes/test_split_step.py
  tests/recipes/test_train_step.py
  tests/recipes/test_transform_step.py
Labels: rn/bug-fix

#7557 Increase version restriction for flask install for Spacy
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#7553 Warn contributor when a PR is filed from the master branch
  .github/workflows/advice.js
  .github/workflows/advice.yml
  .github/workflows/notify-dco-failure.js
Labels: rn/none

#7237 Add custom metadata in the MLmodel file
  mlflow/catboost.py
  mlflow/diviner.py
  mlflow/fastai/__init__.py
  mlflow/gluon/__init__.py
  mlflow/h2o.py
  mlflow/java/scoring/src/main/java/org/mlflow/models/Model.java
  mlflow/java/scoring/src/test/java/org/mlflow/ModelTest.java
  mlflow/java/scoring/src/test/resources/org/mlflow/models/sample_model_root/MLmodel.with.metadata
  mlflow/lightgbm.py
  mlflow/mleap.py
  mlflow/models/model.py
  mlflow/onnx.py
  mlflow/paddle/__init__.py
  mlflow/pmdarima.py
  mlflow/prophet.py
  mlflow/pyfunc/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/shap.py
  mlflow/sklearn/__init__.py
  mlflow/spacy.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/tensorflow/__init__.py
  mlflow/xgboost/__init__.py
  tests/catboost/test_catboost_model_export.py
  tests/diviner/test_diviner_model_export.py
  tests/fastai/test_fastai_model_export.py
  tests/gluon/test_gluon_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/mleap/test_mleap_model_export.py
  tests/models/test_model.py
  tests/onnx/test_onnx_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/pmdarima/test_pmdarima_model_export.py
  tests/prophet/test_prophet_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_scoring_server.py
  tests/pytorch/test_pytorch_model_export.py
  tests/shap/test_log.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spacy/test_spacy_model_export.py
  tests/spark/test_spark_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/tensorflow/test_keras_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/feature, area/models, only-latest

#7543 Distribute model to spark executor by NFS directory instead of calling `sparkContext.addFile`
  mlflow/utils/_spark_utils.py
Labels: rn/none, area/scoring

#7561 Avoid using GitHub API
  tests/projects/test_utils.py
Labels: rn/none

#7549 Introduce stability annotation indicator for contributors
  CONTRIBUTING.md
  mlflow/deployments/base.py
  mlflow/deployments/plugin_manager.py
  mlflow/exceptions.py
  mlflow/models/cli.py
  mlflow/models/evaluation/artifacts.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/lift_curve.py
  mlflow/models/flavor_backend.py
  mlflow/models/model.py
  mlflow/models/signature.py
  mlflow/projects/backend/abstract_backend.py
  mlflow/projects/submitted_run.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/backend.py
  mlflow/sagemaker/cli.py
  mlflow/store/artifact/artifact_repo.py
  mlflow/store/artifact/artifact_repository_registry.py
  mlflow/store/artifact/cli.py
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/store/artifact/dbfs_artifact_repo.py
  mlflow/store/artifact/s3_artifact_repo.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/tracking/abstract_store.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/_tracking_service/utils.py
  mlflow/tracking/context/abstract_context.py
  mlflow/tracking/context/databricks_job_context.py
  mlflow/tracking/context/databricks_notebook_context.py
  mlflow/tracking/context/system_environment_context.py
  mlflow/tracking/default_experiment/abstract_context.py
  mlflow/tracking/default_experiment/databricks_job_experiment_provider.py
  mlflow/tracking/request_header/abstract_request_header_provider.py
  mlflow/utils/annotations.py
Labels: area/docs, rn/none

#7474 Adding support for predict and predict_proba in mlflow recipe model
  mlflow/recipes/steps/evaluate.py
  mlflow/recipes/steps/train.py
  mlflow/recipes/utils/wrapped_recipe_model.py
  tests/recipes/helper_functions.py
  tests/recipes/test_evaluate_step.py
  tests/recipes/test_train_step.py
Labels: rn/feature, area/recipes

#7568 convert recipies/cards to pytest
  tests/recipes/cards/test_histogram_generator.py
Labels: rn/none

#7573 Update requirements for Mlflow 2.1.0 releasing
  requirements/skinny-requirements.txt
  requirements/skinny-requirements.yaml
Labels: rn/none, area/build

#7581 Fix HDFS stored artifacts not loading on MLFLow UI
  mlflow/store/artifact/hdfs_artifact_repo.py
Labels: rn/bug-fix, area/artifacts, area/server-infra

#7584 Update target-version in black configuration
  pyproject.toml
Labels: rn/none

#7583 Add a python script to create a release tag
  dev/create_release_tag.py
Labels: rn/none

#7585 Improve `advice` message
  .github/workflows/advice.js
Labels: rn/none

#7587 Remove the TensorFlow links - the examples don't exist
  docs/source/tutorials-and-examples/index.rst
Labels: rn/documentation

#7592 [Branch-2.1] For spark dataframe with array type column input, remove to_list conversion in spark_udf and make PyFuncModel.predict support dataframe contains numpy array field
  mlflow/models/utils.py
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/pyfunc/test_spark.py
Labels: rn/bug-fix, area/scoring

#7591 For spark dataframe with array type column input, remove `to_list` conversion in spark_udf and make `PyFuncModel.predict` support dataframe contains numpy array field
  mlflow/models/utils.py
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/pyfunc/test_spark.py
Labels: rn/bug-fix, area/scoring

#7594 [Branch-2.1] Make ScoringServerClient support input dataframe with elements of Numpy array
  mlflow/pyfunc/scoring_server/client.py
  mlflow/utils/proto_json_utils.py
  tests/tensorflow/test_keras_pyfunc_model_works_with_all_input_types.py
  tests/utils/test_proto_json_utils.py
Labels: rn/bug-fix

#7595 Make ScoringServerClient support input dataframe with elements of Numpy array
  mlflow/pyfunc/scoring_server/client.py
  mlflow/utils/proto_json_utils.py
  tests/tensorflow/test_keras_pyfunc_model_works_with_all_input_types.py
  tests/utils/test_proto_json_utils.py
Labels: rn/bug-fix, area/scoring

#7550 Don't load ml-package-version.yml on `import mlflow`
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/autologging_utils/versioning.py
  tests/autologging/test_autologging_utils.py
Labels: rn/none, area/tracking

#7577 Compile `ml-package-versions.yml` into a python module
  .pre-commit-config.yaml
  dev/compile_ml_package_versions.py
  mlflow/ml_package_versions.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/autologging_utils/versioning.py
  pylintrc
  pyproject.toml
  setup.py
  tests/autologging/test_autologging_utils.py
Labels: rn/none

#7599 [master] Ensure mlflow imports ML packages lazily
  .github/workflows/master.yml
  dev/run-python-flavor-tests.sh
  mlflow/recipes/steps/automl/flaml.py
  mlflow/recipes/steps/train.py
  tests/check_mlflow_lazily_imports_ml_packages.py
  tests/test_mlflow_lazily_imports_ml_packages.py
Labels: rn/none

#7597 Ensure mlflow imports ML packages lazily
  .github/workflows/master.yml
  conftest.py
  dev/run-python-flavor-tests.sh
  mlflow/recipes/steps/automl/flaml.py
  mlflow/recipes/steps/split.py
  mlflow/recipes/steps/train.py
  tests/check_mlflow_lazily_imports_ml_packages.py
  tests/test_mlflow_lazily_imports_ml_packages.py
Labels: rn/none

#7602 Lazily import `sklearn.utils.compute_class_weight`
  mlflow/recipes/steps/split.py
Labels: rn/none

#7598 Fix cross-version test for tensorflow dev
  tests/tensorflow/test_keras_pyfunc_model_works_with_all_input_types.py
Labels: rn/none, enable-dev-tests, only-latest

#7601 Fix tests for virtualenv project execution
  .github/actions/setup-pyenv/action.yml
  mlflow/utils/virtualenv.py
Labels: rn/none

#7586 Help contributors wrap code with a codeblock in the bug reporte template
  .github/ISSUE_TEMPLATE/bug_report_template.yaml
Labels: rn/none

#7589 Return an empty List on GetMetricHistory when a metric doesn't exist for a run
  mlflow/store/tracking/file_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_rest_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/test_rest_tracking.py
Labels: rn/bug-fix, area/tracking

#7582 Add usage example for R Function (``crate``)
  docs/source/models.rst
Labels: area/docs, rn/none

#7614 Do not drop mlflow's dependencies in dependency inference
  mlflow/utils/requirements_utils.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/utils/test_requirements_utils.py
Labels: rn/none

#7615 Do not update the version if it's newer than the latest version in `dev/update_ml_package_versions.py`
  dev/update_ml_package_versions.py
Labels: rn/none

#7600 On non-databricks runtime, lazily importing PySpark when calling mlflow.autolog()
  mlflow/tracking/fluent.py
  tests/check_mlflow_lazily_imports_ml_packages.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/none, area/tracking

#7613 [Recipes] Matching the metric names of recipes and mlflow.evaluate
  mlflow/recipes/steps/automl/flaml.py
  mlflow/recipes/utils/metrics.py
  tests/recipes/test_train_step.py
Labels: rn/bug-fix, area/recipes

#7626 [Recipes][Bug Fix] Fixing transform step step_config for positive_class
  mlflow/recipes/steps/transform.py
  tests/recipes/test_transform_step.py
Labels: rn/bug-fix, area/recipes
