Repository mlflow/mlflow, pull requests merged in 2022-06, with the labels that each got.

#5995 fix-sklearn-autolog-without-matplotlib
  mlflow/ml-package-versions.yml
  mlflow/sklearn/utils.py
  tests/sklearn/test_sklearn_autolog_without_matplotlib.py
Labels: rn/bug-fix

#6000 Added more robust `_GIT_URI_REGEX`
  mlflow/projects/utils.py
  tests/projects/test_utils.py
Labels: area/windows, rn/bug-fix, area/projects, language/new

#6017 Fix typos
  mlflow/sklearn/utils.py
  tests/conftest.py
Labels: rn/none

#6019 Upgrade `actions/cache` to v3
  .github/workflows/cross-version-tests.yml
  .github/workflows/r.yml
Labels: rn/none, area/build

#6018 Remove redundant protobuf requirements
  tests/pyfunc/test_spark.py
Labels: rn/none, area/build

#6020 Add image artifact file closing logic
  mlflow/models/evaluation/artifacts.py
Labels: rn/none, area/tracking

#6014 Fix getting run UUID using unexisting pascalCased property name
  mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.test.js
Labels: rn/bug-fix, area/uiux

#6021 Fix examples protobuf dependencies
  examples/hyperparam/conda.yaml
  examples/pytorch/AxHyperOptimizationPTL/conda.yaml
  examples/pytorch/BertNewsClassification/conda.yaml
  examples/pytorch/IterativePruning/conda.yaml
  examples/pytorch/MNIST/conda.yaml
  examples/pytorch/conda.yaml
Labels: rn/none, area/examples

#6024 Pin sqlalchemy version in project setup
  setup.py
Labels: rn/bug-fix

#6025 Remove anaconoda compatibility tests
  .github/workflows/master.yml
  dev/test-anaconda-compatibility-in-docker.sh
  dev/test-anaconda-compatibility.sh
Labels: rn/none, area/build

#6026 fix typo
  mlflow/utils/import_hooks/__init__.py
  tests/helper_functions.py
Labels: rn/none

#6023 detailed annotation for black formatting issue
  .github/workflows/matchers/black.json
  dev/lint.sh
Labels: rn/none, area/build

#5840 Ad-hoc connection pool for SFTPArtifactRepository
  mlflow/store/artifact/artifact_repo.py
  mlflow/store/artifact/sftp_artifact_repo.py
  tests/store/artifact/test_sftp_artifact_repo.py
Labels: rn/bug-fix

#6030 Fix lint issue for `SageMakerBackend`
  tests/sagemaker/mock/__init__.py
Labels: rn/none, area/build

#6031 Allow logging a param with an empty string as a value
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/bug-fix

#6029 Define `mock_s3_bucket` in `conftest.py`
  tests/azureml/test_deploy.py
  tests/azureml/test_image_creation.py
  tests/catboost/test_catboost_model_export.py
  tests/conftest.py
  tests/diviner/test_diviner_model_export.py
  tests/fastai/test_fastai_model_export.py
  tests/helper_functions.py
  tests/keras/test_keras_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/pmdarima/test_pmdarima_model_export.py
  tests/prophet/test_prophet_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spark/test_spark_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/store/artifact/test_s3_artifact_repo.py
  tests/tensorflow/test_tensorflow2_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none, area/build

#5756 Tracking: Better support for ndarrays and tensors
  mlflow/ml-package-versions.yml
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/metric_value_conversion_utils.py
  tests/pytorch/test_pytorch_metric_value_conversion_utils.py
  tests/tensorflow/test_tensorflow2_metric_value_conversion_utils.py
  tests/tracking/fluent/test_metric_value_conversion_utils.py
Labels: rn/feature, area/tracking

#6032 add CatBoostRanker support
  mlflow/catboost.py
  tests/catboost/test_catboost_model_export.py
Labels: rn/feature, rn/documentation, area/models

#6037 Fix sklearn flavor load model with code path
  mlflow/sklearn/__init__.py
  mlflow/utils/model_utils.py
Labels: rn/bug-fix

#5997 Feature/implement delete in http artifact repository
  examples/mlflow_artifacts/README.md
  examples/mlflow_artifacts/example.py
  mlflow/java/client/src/main/java/org/mlflow/api/proto/MlflowArtifacts.java
  mlflow/protos/mlflow_artifacts.proto
  mlflow/protos/mlflow_artifacts_pb2.py
  mlflow/server/handlers.py
  mlflow/store/artifact/http_artifact_repo.py
  tests/store/artifact/test_http_artifact_repo.py
Labels: rn/none, area/artifacts

#6046 Closes issue 6045: referenced before assignment
  mlflow/models/container/__init__.py
Labels: rn/bug-fix, area/build

#6050 Fix cross-version test failure for tensorflow dev
  tests/tensorflow/test_tensorflow2_model_export.py
Labels: rn/none, area/models, enable-dev-tests

#6053 Fixed typo in docs
  docs/source/tracking.rst
Labels: area/docs, rn/none

#6041 Bugfix/log figure correct file extension
  mlflow/tracking/client.py
  requirements/test-requirements.txt
  tests/tracking/test_log_figure.py
Labels: rn/none, area/tracking

#6060 Format `mlflow/models/container/__init__.py`
  mlflow/models/container/__init__.py
Labels: rn/none, area/build

#6044 Fix some shap evaluation issues
  mlflow/models/evaluation/default_evaluator.py
  tests/models/test_default_evaluator.py
Labels: rn/bug-fix, area/tracking

#5971 Enable multi-experiment run comparison
  docs/source/tracking.rst
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.css
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.test.js
  mlflow/server/js/src/experiment-tracking/components/HomeView.js
  mlflow/server/js/src/experiment-tracking/components/modals/DeleteExperimentModal.js
  mlflow/server/js/src/experiment-tracking/components/modals/DeleteExperimentModal.test.js
  mlflow/server/js/src/experiment-tracking/routes.js
Labels: area/docs, rn/feature, area/uiux, area/tracking

#6067 Align `_MIN_SKLEARN_VERSION` to the tested version
  mlflow/sklearn/utils.py
Labels: rn/none, area/models

#6070 Remove min sklearn version
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/none, area/tracking

#6071 Fix pyfunc spark UDF test expected error message
  tests/pyfunc/test_spark.py
Labels: rn/none, area/models

#6057 Use `NumpyEncoder` when dumping evaluation metrics
  mlflow/models/evaluation/artifacts.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  tests/models/test_default_evaluator.py
Labels: rn/none, area/tracking

#6063 Make pyfunc.spark_udf support empty partition
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_spark.py
Labels: rn/bug-fix, area/scoring

#6064 Deletion of an experiment to mark runs associated with that experiment to be deleted
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/feature, area/artifacts

#6113 docs: modify example of pytorch autolog (#6107)
  mlflow/pytorch/__init__.py
Labels: area/docs, rn/none

#6052 Automatically split large metrics, tags, or params into smaller chunks to avoid request limit error
  mlflow/tracking/_tracking_service/client.py
  tests/tracking/test_tracking.py
Labels: rn/feature, area/tracking

#6111 updated rest api example to new requirements
  examples/rest_api/mlflow_tracking_rest_api.py
Labels: rn/none

#6123 Set `charset` in step card to render arrow icon properly in scikit-learn model diagram
  mlflow/pipelines/cards/templates/base.html
Labels: rn/none, area/tracking

#6125 Update Slack invite link
  README.rst
Labels: area/docs, rn/none

#6124 Add CircleCI job to preview MLflow pipeline outputs
  .circleci/config.yml
Labels: rn/none, area/build

#6133 [MLflow Pipelines] Silence spark connection messages
  mlflow/pipelines/step.py
Labels: rn/none, area/tracking

#6136 Pipelines: remove redundant colon in step card
  mlflow/pipelines/step.py
Labels: rn/none, area/pipelines

#6134 [MLflow Pipelines] Throw clear exception when pipeline / profile YAML parsing fails
  mlflow/pipelines/utils/__init__.py
  tests/pipelines/regression/v1/test_regression_pipeline.py
  tests/pipelines/test_pipeline.py
  tests/pipelines/test_utils.py
Labels: rn/none, area/tracking

#6137 Adding a alias shortcut for mlflow pipelines to mlp
  .circleci/config.yml
  setup.py
Labels: rn/none, area/pipelines

#6139 [Pipelines] Add missing ingest.py dependency to ingest step dependencies
  mlflow/pipelines/utils/execution.py
Labels: rn/none, area/pipelines

#6138 Adding shorthand for step and profile options to -s and -p respectively
  mlflow/pipelines/cli.py
Labels: rn/none, area/pipelines

#6140 Made YAML parsing strict
  mlflow/pipelines/utils/__init__.py
  mlflow/utils/file_utils.py
  tests/pipelines/test_tracking_utils.py
  tests/pipelines/test_utils.py
  tests/utils/test_file_utils.py
Labels: rn/none, area/pipelines

#6144 Stop installing prophet build dependencies
  dev/dev-env-setup.sh
  dev/install-common-deps.sh
Labels: rn/none

#6143 Fix bug in profile existence check from pipeline subdirectory
  mlflow/pipelines/utils/__init__.py
  tests/pipelines/test_utils.py
Labels: rn/bug-fix, area/pipelines

#6146 Track git repository URL when creating MLflow Runs from MLflow Pipelines
  mlflow/pipelines/steps/evaluate.py
  mlflow/pipelines/steps/train.py
  mlflow/pipelines/utils/tracking.py
  mlflow/projects/docker.py
  mlflow/projects/utils.py
  mlflow/server/js/src/common/utils/Utils.js
  mlflow/tracking/context/git_context.py
  mlflow/utils/git_utils.py
  tests/pipelines/test_pipeline.py
  tests/projects/test_docker_projects.py
Labels: rn/feature, area/pipelines

#6117 Add `pos_label` parameter for `mlflow.sklearn.autolog`
  mlflow/sklearn/__init__.py
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/none, area/tracking

#6148 Add test to ensure MLP dataframe split is deterministic
  mlflow/pipelines/steps/split.py
  tests/pipelines/test_split_step.py
Labels: rn/none, area/pipelines

#6158 Update worst examples generation to use training data instead
  mlflow/pipelines/steps/train.py
Labels: rn/none, area/pipelines

#6147 Add Leader board for MLP train step card
  mlflow/pipelines/cards/__init__.py
  mlflow/pipelines/step.py
  mlflow/pipelines/steps/evaluate.py
  mlflow/pipelines/steps/train.py
  mlflow/pipelines/utils/metrics.py
  tests/pipelines/test_evaluate_step.py
Labels: rn/feature, area/pipelines

#6160 Fix error message for invalid `C` parameter in `LinearSVC`
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/none, area/models, enable-dev-tests

#6161 Pin `cmdstanpy` in `diviner` tests
  mlflow/ml-package-versions.yml
Labels: rn/none, area/models, enable-dev-tests

#6048 [FR] Allow user to download metrics data as csv
  mlflow/server/js/package.json
  mlflow/server/js/src/experiment-tracking/components/MetricsPlotControls.js
  mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.js
  mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.test.js
  mlflow/server/js/src/experiment-tracking/components/MetricsPlotView.js
  mlflow/server/js/src/i18n/default/en.json
Labels: rn/feature, area/tracking

#6165 Fix bug where LocalArtifactRepository.delete_artifacts() throws if artifacts don't exist
  mlflow/store/artifact/local_artifact_repo.py
  tests/store/artifact/test_local_artifact_repo.py
  tests/test_cli.py
Labels: rn/bug-fix, area/artifacts

#6106 Handle auth required http status code to prevent nested exception
  mlflow/exceptions.py
  mlflow/store/tracking/rest_store.py
  mlflow/utils/rest_utils.py
Labels: rn/none, rn/bug-fix, area/tracking
