Repository mlflow/mlflow, pull requests merged in 2022-11, with the labels that each got.

#7208 Change "add metrics & params" to "show more metrics & params"
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/ExperimentViewRunsTableAddColumnCTA.tsx
  mlflow/server/js/src/i18n/default/en.json
Labels: rn/none, area/uiux, area/tracking

#7192 Set `metric_prefix` in MLP steps
  mlflow/pipelines/steps/evaluate.py
  mlflow/pipelines/steps/train.py
  tests/pipelines/test_evaluate_step.py
  tests/pipelines/test_pipeline.py
  tests/pipelines/test_train_step.py
Labels: rn/none

#7211 Bump version to `2.0.0rc0`
  mlflow/version.py
Labels: rn/none

#7210 Fix flaky tests in `tests/test_cli.py`
  tests/test_cli.py
Labels: rn/none

#7223 Pin ubuntu version to 20.04
  .github/workflows/master.yml
  .github/workflows/r.yml
Labels: rn/none, area/build

#7218 Fix experiment search ordering bug and change default sort order
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/utils/search_utils.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, area/tracking

#7180 predict_proba output column
  mlflow/pipelines/steps/train.py
  mlflow/pipelines/utils/metrics.py
Labels: rn/none, area/pipelines

#7224 Install libtbb2 when running cross-version test for dev prophet
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#7225 Fix DBR version check in `display_html`
  mlflow/pipelines/utils/step.py
Labels: rn/none

#7227 Format notebooks via black
  examples/h2o/random_forest.ipynb
  examples/rapids/mlflow_project/notebooks/rapids_mlflow.ipynb
  examples/restore_model_dependencies/restore_model_dependencies_example.ipynb
  examples/sklearn_elasticnet_wine/train.ipynb
  requirements/lint-requirements.txt
Labels: rn/none

#7230 Update `mlflow/R/mlflow/Dockerfile.dev` to use `rocker/r-ver:4.2.1`
  mlflow/R/mlflow/Dockerfile.dev
Labels: language/r, rn/none

#7219 Adding inline examples of model flavor usage with MLflow for fastai.
  docs/source/models.rst
Labels: area/docs, rn/none

#7226 Fix package repository URL and unpin Ubuntu in R workflow
  .github/workflows/r.yml
  mlflow/R/mlflow/.Rprofile
Labels: rn/none

#7214 Add headline for MLflow 2.0 RC on README
  README.rst
Labels: rn/none

#7143 Add database migration check
  .github/workflows/master.yml
  tests/db/.gitignore
  tests/db/check_migration.py
  tests/db/check_migration.sh
  tests/db/compose.yml
  tests/db/entrypoint.sh
Labels: rn/none, area/sqlalchemy

#7236 Replace unittest assertmethods with plain assert
  tests/entities/model_registry/test_model_version.py
  tests/entities/model_registry/test_registered_model.py
  tests/entities/test_experiment.py
  tests/entities/test_file_info.py
  tests/entities/test_param.py
  tests/entities/test_run.py
  tests/entities/test_run_data.py
  tests/entities/test_run_info.py
  tests/entities/test_run_status.py
  tests/recipes/cards/test_histogram_generator.py
  tests/store/db/test_utils.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/bug-fix

#7209 handle imbalanced datasets
  mlflow/recipes/steps/train.py
Labels: rn/none, area/pipelines

#7242 Fix `hooks/pre-commit`
  hooks/pre-commit
Labels: rn/none

#7245 Updated MLflow Doc to Rename Pipeline to Recipe
  docs/source/_static/images/pipelines_databricks_fixme.png
  docs/source/_static/images/pipelines_databricks_logged_artifacts.png
  docs/source/_static/images/pipelines_databricks_notebook_ui.png
  docs/source/_static/images/pipelines_databricks_repo_ui.png
  docs/source/_static/images/pipelines_databricks_ui.png
  docs/source/_static/images/recipes_databricks_dag.png
  docs/source/_static/images/recipes_databricks_fixme.png
  docs/source/_static/images/recipes_databricks_logged_artifacts.png
  docs/source/_static/images/recipes_databricks_notebook_ui.png
  docs/source/_static/images/recipes_databricks_repo_ui.png
  docs/source/_static/images/recipes_databricks_ui.png
  docs/source/_static/images/recipes_evaluate_step_card.png
  docs/source/recipes.rst
  mlflow/server/js/src/experiment-tracking/components/RunView.js
Labels: area/docs, rn/none

#7228 Add run_name when specified in start_run tags
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/fluent.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_rest_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/bug-fix, area/tracking

#7247 Add matplotlib to MLflow's dependencies
  .circleci/config.yml
  requirements/core-requirements.txt
  requirements/core-requirements.yaml
  requirements/test-requirements.txt
Labels: rn/none

#7258 Replace `assert expected == actual` to `assert actual == expected`
  tests/autologging/test_autologging_utils.py
  tests/entities/test_run_info.py
  tests/entities/test_run_status.py
  tests/models/test_cli.py
  tests/models/test_default_evaluator.py
  tests/models/test_evaluation.py
  tests/projects/test_kubernetes.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/test_model_registry.py
  tests/utils/test_search_utils.py
Labels: rn/bug-fix

#7259 Add `a.py` in `.gitignore`
  .gitignore
Labels: rn/none

#7271 unit test for rebalancing
  tests/recipes/test_train_step.py
Labels: rn/none, area/recipes

#7250 Fix issue with MLeap 0.21.0
  .github/workflows/cross-version-tests.yml
  mlflow/ml-package-versions.yml
  tests/mleap/test_mleap_model_export.py
Labels: rn/none

#7267 Fix `FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated`
  mlflow/recipes/cards/pandas_renderer.py
Labels: rn/none

#7264 Rename pipeline workflow YAML files
  .github/workflows/recipe-template.yml
  .github/workflows/recipe.yml
Labels: rn/none

#7272 fix unneccessary collection (<dict/list/tuple>) call and rewrite them as literal
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/models/utils.py
  mlflow/projects/docker.py
  mlflow/sagemaker/__init__.py
  mlflow/sklearn/utils.py
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/s3_artifact_repo.py
  mlflow/utils/environment.py
  tests/autologging/test_autologging_safety_unit.py
  tests/projects/test_databricks.py
  tests/sagemaker/test_sagemaker_deployment_client.py
  tests/test_skinny_client_autolog_without_scipy.py
Labels: rn/bug-fix, area/build

#7266 Fix Facets Overview background
  .circleci/config.yml
  mlflow/recipes/cards/pandas_renderer.py
Labels: rn/none

#7263 Run commit hooks using `pre-commit`
  .github/workflows/master.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  dev/black.sh
  dev/dev-env-setup.sh
  dev/lint.sh
  examples/flower_classifier/README.rst
  hooks/pre-commit
  hooks/prepare-commit-msg
  requirements/lint-requirements.txt
Labels: rn/none

#7279 Fix specifying an incorrect image URI when skipping image build
  mlflow/projects/docker.py
Labels: rn/none, area/projects, area/docker

#7283 Print out DBR version in `mlflow.doctor`
  mlflow/__init__.py
  mlflow/_doctor.py
  tests/test_doctor.py
Labels: rn/none

#7287 enable use-dict-literal and use-list-literal rule in pylintrc file
  pylintrc
Labels: rn/none

#7284 Enable color when running `pre-commit run`
  .github/workflows/master.yml
Labels: rn/none

#7281 Set `DataCaptureConfig` when creating a new endpoint config
  mlflow/sagemaker/__init__.py
Labels: rn/bug-fix, integrations/sagemaker

#7260 Fix color and spacing of header on MLflow UI
  mlflow/server/js/src/experiment-tracking/components/App.css
  mlflow/server/js/src/experiment-tracking/components/App.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.js
Labels: rn/none

#7278 Do not create context if `--build-image` is not specified
  mlflow/projects/docker.py
Labels: rn/none

#7275 Fixed MLflow Recipes Doc DAG Image
  docs/source/_static/images/recipes_databricks_dag.png
Labels: area/docs, rn/none

#7249 Replace `Series.iteritems` (deprecated) with `Series.items`
  mlflow/sklearn/utils.py
Labels: rn/none

#7290 Explicitly state pylint rules as replacement to convention filter
  pylintrc
  tests/azureml/test_deploy.py
  tests/azureml/test_image_creation.py
Labels: rn/none, area/build

#7299 Classifier tuning fix
  mlflow/recipes/steps/train.py
Labels: rn/none, area/recipes

#7254 Bump MLServer version to 1.2.0.dev13
  docs/source/models.rst
  docs/source/tutorials-and-examples/tutorial.rst
  mlflow/models/container/__init__.py
  mlflow/pyfunc/mlserver.py
  setup.py
  tests/models/test_cli.py
  tests/pyfunc/test_mlserver.py
  tests/test_cli.py
Labels: area/docs, rn/feature, area/scoring

#7298 enable `superfluous-parens / C0325` rule and fixed the pylint errors
  mlflow/sklearn/utils.py
  pylintrc
  tests/autologging/test_autologging_behaviors_unit.py
  tests/models/test_artifacts.py
Labels: rn/bug-fix

#7300 Update documentation for serving 1.x models on 2.x release
  mlflow/models/cli.py
Labels: area/docs, rn/none

#7308 Change ordering of tests in spark udf testing suite to mitigate flaky test behavior
  tests/pyfunc/test_spark.py
Labels: rn/none, area/build

#7310 enable dictionary iterator rule and fix pylint failures
  mlflow/models/evaluation/artifacts.py
  mlflow/tracking/client.py
  pylintrc
  tests/pyfunc/test_scoring_server.py
  tests/tracking/_tracking_service/test_utils.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/none, area/build

#7311 Improve documentation preview comment
  .github/workflows/preview-docs.yml
  dev/preview_docs.py
Labels: rn/none

#7313 Reintroduce `--no-conda` flag for backward compatibility
  mlflow/models/cli.py
  mlflow/utils/cli_args.py
Labels: rn/none

#7314 feat: adjusted column order and icon sizes in experiment runs table
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/ExperimentViewRunsTable.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/cells/DateCellRenderer.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/cells/PinRowCellRenderer.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/cells/RunNameCellRenderer.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/utils/experimentPage.column-utils.ts
Labels: rn/none, area/tracking

#7135 Changes to support ragged arrays in signature handling
  docs/source/models.rst
  mlflow/models/utils.py
  tests/types/test_schema.py
Labels: area/docs, rn/bug-fix, area/scoring

#7261 Do we really need to use Algolia?
  docs/source/conf.py
  docs/theme/mlflow/layout.html
  docs/theme/mlflow/search.html
  docs/theme/mlflow/searchbox.html
  docs/theme/mlflow/static/css/algolia.css
  docs/theme/mlflow/static/js/custom.js
Labels: area/docs, rn/none

#7309 Adding documentation for classification template and example in mlflow docs
  docs/source/recipes.rst
  mlflow/recipes/dag_help_strings.py
Labels: rn/none, area/recipes

#7321 release version update 2.0
  mlflow/java/client/pom.xml
  mlflow/java/pom.xml
  mlflow/java/scoring/pom.xml
  mlflow/java/spark/pom.xml
  mlflow/server/js/src/common/constants.js
  mlflow/version.py
Labels: rn/none, area/build

#7325 Fix camel-cased variables to snake case
  mlflow/models/utils.py
  mlflow/recipes/cards/pandas_renderer.py
  tests/recipes/test_pipeline.py
  tests/recipes/test_transform_step.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
  tests/spark/test_spark_model_export.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/utils/test_file_utils.py
  tests/utils/test_proto_json_utils.py
Labels: rn/none

#7326 Use `custom_function` attribute when extracting custom metric function
  mlflow/recipes/utils/metrics.py
  tests/recipes/test_evaluate_step.py
Labels: rn/bug-fix, area/recipes

#7329 Add descriptive MLflow 2.0 migration error message for invalid serving input formats
  mlflow/pyfunc/scoring_server/__init__.py
Labels: rn/none, area/scoring

#7327 Remove useless `list` in `sorted`
  mlflow/recipes/steps/ingest/datasets.py
  mlflow/recipes/utils/step.py
  tests/spark/autologging/utils.py
Labels: rn/none

#7328 Replace collection calls such as `list()` with comprehension
  mlflow/_doctor.py
  mlflow/exceptions.py
  mlflow/projects/backend/local.py
  mlflow/recipes/steps/evaluate.py
  mlflow/server/handlers.py
  tests/dev/test_set_matrix.py
  tests/pyfunc/test_scoring_server.py
  tests/recipes/test_split_step.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_rest_store.py
Labels: rn/none

#7322 FLAML classifier metrics
  mlflow/recipes/steps/automl/flaml.py
Labels: rn/none, area/recipes

#7332 Adding test_train_step_classifier_automl test
  mlflow/recipes/steps/train.py
  tests/recipes/test_train_step.py
Labels: rn/none, area/recipes

#7335 Remove xgboost from automl test
  tests/recipes/test_train_step.py
Labels: rn/none, area/recipes

#7333 Fix NFS enablement check when Spark session is unavailable on Databricks workers
  mlflow/utils/nfs_on_spark.py
Labels: rn/none, area/scoring

#7273 Added /version endpoint for tracking server
  docs/source/tracking.rst
  mlflow/server/__init__.py
  mlflow/server/prometheus_exporter.py
  tests/server/test_handlers.py
  tests/server/test_prometheus_exporter.py
Labels: area/docs, rn/feature, area/tracking

#7344 Optimize code by replacing map-lambda with comprehension
  mlflow/fastai/__init__.py
  mlflow/pytorch/_pytorch_autolog.py
  mlflow/recipes/utils/step.py
  mlflow/server/handlers.py
  mlflow/store/artifact/utils/models.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/types/schema.py
  mlflow/types/utils.py
  mlflow/utils/search_utils.py
  mlflow/utils/virtualenv.py
  tests/fastai/test_fastai_autolog.py
  tests/fastai/test_fastai_model_export.py
  tests/gluon/test_gluon_autolog.py
  tests/h2o/test_h2o_model_export.py
  tests/pytorch/test_pytorch_autolog.py
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/none

#7343 Add `mlflow.doctor` in bug report template
  .github/ISSUE_TEMPLATE/bug_report_template.yaml
Labels: rn/none

#7334 add cherry-picked commits
  CHANGELOG.md
Labels: rn/none, area/build

#7346 Update development versions to 2.0.2
  mlflow/R/mlflow/DESCRIPTION
  mlflow/java/client/pom.xml
  mlflow/java/pom.xml
  mlflow/java/scoring/pom.xml
  mlflow/java/scoring/src/main/java/org/mlflow/sagemaker/ScoringServer.java
  mlflow/java/scoring/src/test/java/org/mlflow/ScoringServerTest.java
  mlflow/java/spark/pom.xml
  mlflow/server/js/src/common/constants.js
  mlflow/version.py
Labels: rn/none, area/build

#7307 Fix `_create_local_spark_session_for_recipes` function used in MLflow recipe
  mlflow/spark.py
  mlflow/utils/_capture_modules.py
  mlflow/utils/_spark_utils.py
Labels: rn/bug-fix, area/tracking, area/recipes

#7348 Enable 'ungrouped-imports' pylint check
  mlflow/pytorch/_pytorch_autolog.py
  mlflow/recipes/steps/ingest/datasets.py
  mlflow/types/utils.py
  mlflow/utils/rest_utils.py
  pylintrc
  tests/models/test_artifacts.py
  tests/models/test_cli.py
  tests/models/test_default_evaluator.py
  tests/models/test_evaluation.py
  tests/onnx/test_onnx_model_export.py
  tests/projects/test_docker_projects.py
  tests/pyfunc/test_dependencies_functions.py
  tests/pyfunc/test_spark.py
  tests/pytorch/test_pytorch_autolog.py
  tests/resources/onnx/generate_onnx_models.py
  tests/shap/test_log.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
  tests/tensorflow/test_keras_model_export.py
  tests/tracking/default_experiment/test_databricks_job_experiment_provider.py
  tests/tracking/test_mlflow_artifacts.py
  tests/tracking/test_rest_tracking.py
  tests/utils/test_databricks_utils.py
  tests/utils/test_proto_json_utils.py
Labels: rn/none, area/build

#6493 Add dev container configuration for VSCode
  .devcontainer/Dockerfile.devcontainer
  .devcontainer/Dockerfile.devcontainer.dockerignore
  .devcontainer/README.md
  .devcontainer/codespaces.zsh-theme
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/images/codespace.png
  .devcontainer/pip-compile.sh
  .devcontainer/postCreate.sh
  .devcontainer/requirements.txt
  .github/workflows/devcontainer.yml
  .gitignore
  CONTRIBUTING.md
  assets/create-codespace.png
  dev/run-dev-server.sh
Labels: rn/none

#7345 Add CLI command to run `mlflow.doctor`
  mlflow/_doctor.py
  mlflow/cli.py
  tests/test_cli.py
Labels: rn/none

#7350 Upgrade rstcheck
  .devcontainer/requirements.txt
  .github/workflows/devcontainer.yml
  requirements/lint-requirements.txt
Labels: rn/none

#7352 Install `less` in devcontainer image
  .devcontainer/Dockerfile.devcontainer
Labels: rn/none

#7351 Enable pre-commit hooks on devcontainer creation
  .devcontainer/postCreate.sh
Labels: rn/none

#7289 Adding a using option of custom in transform step
  docs/source/recipes.rst
  mlflow/recipes/dag_help_strings.py
  mlflow/recipes/steps/transform.py
  tests/recipes/test_execution_utils.py
  tests/recipes/test_transform_step.py
Labels: rn/none, area/recipes

#7353 Remove useless `getattr` and `setattr`
  mlflow/lightgbm.py
  mlflow/recipes/steps/train.py
  mlflow/recipes/steps/transform.py
  mlflow/utils/environment.py
  mlflow/xgboost/__init__.py
  tests/recipes/test_ingest_step.py
Labels: rn/none

#7354 Do not use dict as argument default value
  mlflow/recipes/steps/train.py
Labels: rn/none

#7336 Remove "www" from docs canonical urls
  docs/theme/mlflow/layout.html
Labels: area/docs, rn/none

#7361 Small fix for JSON model server example in docs
  docs/source/models.rst
Labels: area/docs, rn/documentation

#6605 Support FileStore for Model Registry
  mlflow/entities/model_registry/model_version.py
  mlflow/entities/model_registry/registered_model.py
  mlflow/server/handlers.py
  mlflow/store/model_registry/__init__.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/model_registry/rest_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/store/tracking/file_store.py
  mlflow/tracking/_model_registry/utils.py
  mlflow/utils/file_utils.py
  mlflow/utils/search_utils.py
  tests/store/model_registry/test_file_store.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
  tests/tracking/test_client.py
Labels: rn/feature, area/model-registry

#7366 Pin tensorflow to <2.11 due to breaking changes that affect transformers package
  .github/workflows/r.yml
  requirements/extra-ml-requirements.txt
Labels: rn/none, area/build, only-latest

#7371 Fix TF 2.10.1 param assert in test
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/none, area/build

#7373 Fix moto-dependent test compatibility with latest moto version
  tests/sagemaker/mock/__init__.py
Labels: rn/none, area/build

#7370 Disable incompatible TF 2.11 transformers test (fixes cross version tests)
  tests/tensorflow/test_keras_model_export.py
Labels: rn/none, area/build

#7364 Introduce major version pinning for mlflow requirement in saved models
  mlflow/utils/environment.py
  tests/catboost/test_catboost_model_export.py
  tests/diviner/test_diviner_model_export.py
  tests/fastai/test_fastai_model_export.py
  tests/gluon/test_gluon_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/helper_functions.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/models/test_wheeled_model.py
  tests/onnx/test_onnx_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/pmdarima/test_pmdarima_model_export.py
  tests/prophet/test_prophet_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pytorch/test_pytorch_model_export.py
  tests/shap/test_log.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spacy/test_spacy_model_export.py
  tests/spark/test_spark_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/tensorflow/test_keras_model_export.py
  tests/utils/test_environment.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/feature, area/models, only-latest

#7375 Do not allow contributors to autoformat
  .github/workflows/autoformat.js
  .github/workflows/autoformat.yml
  dev/black.sh
Labels: rn/none

#7379 Fix autoformat workflow
  .github/workflows/autoformat.yml
Labels: rn/none

#7381 Fix Examples pip requirements dependency checks
  examples/pip_requirements/pip_requirements.py
Labels: rn/none, area/build

#7372 Updating the source type to recipe
  mlflow/entities/source_type.py
  tests/recipes/test_register_step.py
  tests/recipes/test_train_step.py
Labels: rn/none, area/recipes

#7376 Replace `assertEqual` in tests/store/model_registry/test_file_store.py
  tests/store/model_registry/test_file_store.py
Labels: rn/none

#7390 Add static test datasets to avoid unresponsive requests from uci servers
  tests/data/winequality-red.csv
  tests/data/winequality-white.csv
Labels: rn/none, area/build

#7388 Add sleep for filestore test in windows for chronological precision issues in windows
  tests/store/model_registry/test_file_store.py
Labels: rn/none, area/build

#7391 Use GitHub master branch to fetch test data from url rather than UCI legacy servers
  examples/sklearn_elasticnet_wine/train.py
  tests/recipes/test_ingest_step.py
Labels: rn/none, area/build

#7291 Make TF / keras model spark UDF supports multi dimension input
  .github/workflows/cross-version-tests.yml
  mlflow/models/utils.py
  mlflow/pyfunc/__init__.py
  mlflow/tensorflow/__init__.py
  mlflow/utils/proto_json_utils.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/tensorflow/test_keras_model_export.py
  tests/tensorflow/test_keras_pyfunc_model_works_with_all_input_types.py
Labels: rn/feature, area/scoring, area/tracking

#7395 Rename sub-commands in `update_mlflow_versions.py`
  dev/update_mlflow_versions.py
Labels: rn/none

#7393 Add doc for official mlflow docker image
  README.rst
  docs/source/docker.rst
  docs/source/index.rst
Labels: rn/none

#7399 Fix flaky recipe test test_predict_correctly_handles_save_modes
  tests/recipes/test_predict_step.py
Labels: rn/none, area/build

#7396 Add a script to create a release branch
  dev/create_release_branch.py
Labels: rn/none

#7398 Add model logging docs for ONNX flavor
  docs/source/models.rst
Labels: area/docs, rn/documentation

#7407 Do not run `devcontainer` workflow in fork repositories
  .github/workflows/devcontainer.yml
Labels: rn/none

#7409 Fix `.github/workflows/closing-pr.js`
  .github/workflows/closing-pr.js
Labels: rn/none

#7406 Set `OWNER` and `REPO` when running `gh` CLI
  .github/workflows/autoformat.yml
Labels: rn/none

#7410 Autoformat R documentation
  .circleci/config.yml
  .github/workflows/autoformat.yml
Labels: rn/none

#7414 Adding positive and negative splits profiling
  mlflow/recipes/steps/evaluate.py
  mlflow/recipes/steps/split.py
  tests/recipes/test_evaluate_step.py
  tests/recipes/test_split_step.py
Labels: rn/none, area/recipes

#7418 Change `mlflow.autolog` metrics name to the same as `mlflow.evaluate`
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
  mlflow/tracking/fluent.py
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/bug-fix, area/tracking

#7401 Set model version tag in R API
  docs/source/R-api.rst
  mlflow/R/mlflow/NAMESPACE
  mlflow/R/mlflow/R/model-registry.R
  mlflow/R/mlflow/man/mlflow_set_model_version_tag.Rd
  mlflow/R/mlflow/tests/testthat/test-model-registry.R
Labels: area/docs, language/r, rn/feature, area/model-registry

#7426 Create models directory when intializing model registry FileStore
  mlflow/store/model_registry/file_store.py
Labels: rn/none

#7427 Fix permission issue in `get_nfs_cache_root_dir`
  mlflow/utils/nfs_on_spark.py
Labels: rn/bug-fix, area/scoring, area/tracking

#7386 Fixes #6028: Don't add /code subdirectories to sys.path
  mlflow/utils/model_utils.py
  tests/utils/test_model_utils.py
  tests/utils/test_resources/dummy_package/__init__.py
  tests/utils/test_resources/dummy_package/base.py
  tests/utils/test_resources/dummy_package/operator.py
Labels: rn/none, area/models
