Repository mlflow/mlflow, pull requests merged in 2022-09, with the labels that each got.

#6571 Also add support for reading JSON from profile.yml files
  mlflow/pipelines/utils/__init__.py
  mlflow/utils/file_utils.py
  tests/pipelines/test_utils.py
  tests/utils/test_file_utils.py
Labels: rn/none

#6494 feat: add utility for signature validation of logged model to dataset
  mlflow/models/__init__.py
  mlflow/models/model.py
  mlflow/models/utils.py
  mlflow/pyfunc/__init__.py
  mlflow/utils/annotations.py
  tests/models/test_model.py
  tests/types/test_schema.py
Labels: rn/feature, area/models

#6650 [2.0] Make mlflow.sagemaker.deploy() / delete() APIs internal, remove CLIs
  docs/source/models.rst
  mlflow/deployments/plugin_manager.py
  mlflow/models/__init__.py
  mlflow/models/cli.py
  mlflow/models/flavor_backend_registry.py
  mlflow/pyfunc/__init__.py
  mlflow/sagemaker/__init__.py
  mlflow/sagemaker/cli.py
  tests/helper_functions.py
  tests/models/test_cli.py
  tests/pyfunc/test_scoring_server.py
  tests/pyfunc/test_spark.py
  tests/sagemaker/test_deployment.py
Labels: rn/breaking-change, area/scoring

#6651 Deprecate mlflow.sagemaker.deploy() & mlflow.sagemaker.delete()
  docs/source/models.rst
  mlflow/sagemaker/__init__.py
  mlflow/sagemaker/cli.py
Labels: area/docs, rn/documentation, area/scoring

#6658 Use virtualenv if no env file is present in project
  mlflow/projects/_project_spec.py
  mlflow/projects/backend/local.py
  mlflow/utils/environment.py
  tests/projects/test_projects_cli.py
  tests/projects/test_virtualenv_projects.py
  tests/resources/example_project_no_spec/check_conda_env.py
Labels: rn/none, area/projects

#6486 Set production variant name
  mlflow/sagemaker/__init__.py
Labels: rn/feature

#6664 Document how to set up repository
  CONTRIBUTING.rst
Labels: area/docs, rn/none

#6638 Remove conda from R client
  .github/workflows/r.yml
  docs/source/R-api.rst
  mlflow/R/mlflow/.Rbuildignore
  mlflow/R/mlflow/.create-test-env.R
  mlflow/R/mlflow/.install-mlflow-r.R
  mlflow/R/mlflow/.run-tests.R
  mlflow/R/mlflow/DESCRIPTION
  mlflow/R/mlflow/NAMESPACE
  mlflow/R/mlflow/R/cli.R
  mlflow/R/mlflow/R/install.R
  mlflow/R/mlflow/R/python.R
  mlflow/R/mlflow/R/tracking-ui.R
  mlflow/R/mlflow/README.Rmd
  mlflow/R/mlflow/README.md
  mlflow/R/mlflow/document.R
  mlflow/R/mlflow/man/install_mlflow.Rd
  mlflow/R/mlflow/man/mlflow_maybe_create_conda_env.Rd
  mlflow/R/mlflow/man/mlflow_ui.Rd
  mlflow/R/mlflow/man/uninstall_mlflow.Rd
  mlflow/R/mlflow/tests/testthat/test-bypass-conda.R
  mlflow/R/mlflow/tests/testthat/test-python-install.R
Labels: language/r, rn/breaking-change

#6663 Fix flaky windows pipeline suite by skipping profiling for multi-dataset http ingest case
  tests/pipelines/test_ingest_step.py
Labels: rn/none, area/build

#6668 Avoid gyptorch 1.9.0 in example test requirements
  examples/pytorch/AxHyperOptimizationPTL/conda.yaml
  examples/pytorch/IterativePruning/conda.yaml
Labels: rn/none, area/build

#6634 [ML-24539] add logging for process during split step
  mlflow/pipelines/steps/split.py
Labels: rn/none, area/pipelines

#6674 change logic for experiment env variables
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/breaking-change, area/tracking

#6677 Remove old gtm tags and make gtm tag configurable
  docs/source/_templates/layout.html
  docs/source/conf.py
  docs/theme/mlflow/google_tag_manager.html
  docs/theme/mlflow/layout.html
  docs/theme/mlflow/search.html
Labels: area/docs, rn/none

#6679 [1.28] Remove old gtm tags and make gtm tag configurable
  docs/source/_templates/layout.html
  docs/source/conf.py
  docs/theme/mlflow/google_tag_manager.html
  docs/theme/mlflow/layout.html
  docs/theme/mlflow/search.html
Labels: area/docs, rn/none

#6669 Remove experimental decorators applies on MLflow APIs except for MLflow Pipelines
  mlflow/deployments/base.py
  mlflow/diviner.py
  mlflow/models/evaluation/base.py
  mlflow/onnx.py
  mlflow/pmdarima.py
  mlflow/pytorch/__init__.py
  mlflow/sagemaker/__init__.py
  mlflow/sagemaker/cli.py
  mlflow/shap.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: rn/none

#6667 Remove preview routes from mlflow and model-registry APIs
  docs/source/rest-api.rst
  examples/rest_api/mlflow_tracking_rest_api.py
  mlflow/java/client/src/main/java/org/mlflow/api/proto/ModelRegistry.java
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/model_registry.proto
  mlflow/protos/model_registry_pb2.py
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
  mlflow/server/handlers.py
  mlflow/server/js/src/experiment-tracking/sdk/MlflowService.js
  mlflow/server/js/src/model-registry/services.js
  tests/server/test_handlers.py
  tests/store/model_registry/test_rest_store.py
Labels: rn/breaking-change, area/model-registry, area/tracking

#6670 Drop support for passing `PyFuncModel` to `mlflow.evaluate`
  mlflow/models/evaluation/base.py
  tests/models/test_evaluation.py
Labels: rn/breaking-change, area/tracking

#6647 Fix bug when reloading modules
  mlflow/utils/model_utils.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/bug-fix, area/models

#6687 Added MlflowException on top level
  mlflow/__init__.py
Labels: rn/none

#6681 Rename `df` arg in deploy predict abstract method
  mlflow/deployments/base.py
  mlflow/sagemaker/__init__.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/fake_deployment_plugin.py
Labels: rn/breaking-change, area/scoring

#6600 Add support for Decimal object to Double cast in ML Flow
  mlflow/models/utils.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
Labels: rn/feature, area/models

#6685 Add `--only-latest` option to `set_matrix.py`
  .github/workflows/cross-version-tests.yml
  dev/set_matrix.py
Labels: rn/none, area/build, only-latest

#6555 Fix truncation issues when using explainable evaluator
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/utils/string_utils.py
  tests/models/test_default_evaluator.py
  tests/models/test_evaluation.py
Labels: rn/none, area/models

#6701 Fix cross version test failure
  .github/workflows/cross-version-tests.yml
Labels: rn/none, area/build

#6702 Fix flaky `test_download_artifacts` in `tests/store/artifact/test_http_artifact_repo.py`
  tests/store/artifact/test_http_artifact_repo.py
Labels: rn/none

#6700 Temporarily use `tensorflow>=2.10.0rc3` in `keras>=2.10.0`
  mlflow/ml-package-versions.yml
Labels: rn/none

#6699 Change base image to `python:3.7` in `Dockerfile`
  Dockerfile
  dev/Dockerfile.test
  examples/docker/Dockerfile
  tests/resources/example_docker_project/Dockerfile
Labels: rn/none

#6706 Remove `tabulate`
  mlflow/experiments.py
  mlflow/runs.py
  mlflow/utils/string_utils.py
Labels: rn/none

#6707 Merge master branch into branch-2.0
  .github/workflows/cross-version-tests.yml
  Dockerfile
  dev/Dockerfile.test
  dev/set_matrix.py
  examples/docker/Dockerfile
  mlflow/__init__.py
  mlflow/ml-package-versions.yml
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/models/utils.py
  mlflow/pipelines/steps/ingest/__init__.py
  mlflow/utils/string_utils.py
  tests/models/test_default_evaluator.py
  tests/models/test_evaluation.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/resources/example_docker_project/Dockerfile
  tests/store/artifact/test_http_artifact_repo.py
Labels: rn/none, only-latest

#6691 Remove deprecated azureml modules
  dev/run-python-flavor-tests.sh
  docs/source/cli.rst
  docs/source/python_api/mlflow.azureml.rst
  mlflow/azureml/__init__.py
  mlflow/azureml/cli.py
  mlflow/cli.py
  mlflow/deployments/__init__.py
  requirements/extra-ml-requirements.txt
  tests/azureml/__init__.py
  tests/azureml/test_deploy.py
  tests/azureml/test_image_creation.py
Labels: rn/breaking-change, integrations/azure, area/build

#6680 [ML-24654] hyperparameter tuning scaffolding and search space
  mlflow/pipelines/steps/train.py
  tests/pipelines/test_train_step.py
Labels: rn/none, area/pipelines

#6713 Remove experimental designators in docs
  docs/source/models.rst
  docs/source/plugins.rst
  docs/source/projects.rst
  docs/source/rest-api.rst
  docs/source/tracking.rst
  docs/source/tutorials-and-examples/tutorial.rst
Labels: area/docs, rn/documentation

#6710 Clean up imports in `mlflow/__init__.py` for more efficient code navigation
  mlflow/__init__.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/none

#6711 Do not auto-format files in `examples/pipelines/sklearn_regression`
  pyproject.toml
Labels: rn/none

#6704 Add `.git-blame-ignore-revs` to ignores commits for `black` in git blame
  .git-blame-ignore-revs
Labels: rn/none

#6717 Revert "Temporarily use `tensorflow>=2.10.0rc3` in `keras>=2.10.0`"
  mlflow/ml-package-versions.yml
Labels: rn/none

#6708 Install miniforge in `Dockerfile.test`
  dev/Dockerfile.test
Labels: rn/none

#6718 Fix CRAN incoming check
  docs/source/R-api.rst
  mlflow/R/mlflow/R/install.R
  mlflow/R/mlflow/man/install_mlflow.Rd
Labels: rn/none, area/build

#6719 Set `env_manager` default to virtualenv
  mlflow/models/container/__init__.py
  mlflow/pyfunc/backend.py
Labels: rn/none

#6720 Fix `lint:fix` command in `package.json`
  mlflow/server/js/package.json
Labels: rn/none

#6725 Use `monkeypatch.syspath_prepend` when mutating `sys.path` in tests
  tests/utils/test_databricks_utils.py
  tests/utils/test_requirements_utils.py
Labels: rn/none

#6721 Remove DefaultEvaluator shap plot de-duplicating feature names logic and fix color bar
  mlflow/models/evaluation/default_evaluator.py
  tests/models/test_default_evaluator.py
  tests/models/test_evaluation.py
Labels: rn/none, area/tracking

#6729 Fix accuracy score feature name in model validation
  examples/evaluation/evaluate_with_model_validation.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
Labels: rn/none

#6689 fix: regression caused by #6376
  mlflow/pipelines/pipeline.py
  mlflow/pipelines/steps/train.py
  mlflow/pipelines/utils/execution.py
  tests/pipelines/test_execution_utils.py
  tests/pipelines/test_train_step.py
Labels: rn/none, area/pipelines

#6683 Remove duplicate `_SPARK_MODEL_PATH_SUB`
  mlflow/spark.py
  tests/spark/test_spark_model_export.py
Labels: rn/bug-fix

#6722 Scope Databricks inferred pip requirements to modules
  mlflow/utils/_capture_modules.py
  mlflow/utils/requirements_utils.py
  tests/utils/test_requirements_utils.py
Labels: rn/bug-fix, area/models

#6690 Fix predict step target
  mlflow/pipelines/steps/predict.py
  mlflow/pipelines/utils/execution.py
Labels: rn/none, area/pipelines

#6694 add sklearn usage example
  docs/source/models.rst
Labels: area/docs, rn/none

#6737 Updating contributing to match the required version in generate-proto.sh
  CONTRIBUTING.rst
Labels: rn/none, area/build

#6696 Add `pos_label` to `mlflow.evaluate`
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  tests/models/test_default_evaluator.py
Labels: rn/feature, area/tracking

#6684 Expand env field in pyfunc spec to create `conda` and `virtualenv` subfields
  mlflow/R/mlflow/R/model-h2o.R
  mlflow/R/mlflow/R/model-keras.R
  mlflow/R/mlflow/R/model-utils.R
  mlflow/R/mlflow/R/model-xgboost.R
  mlflow/catboost.py
  mlflow/diviner.py
  mlflow/fastai/__init__.py
  mlflow/gluon/__init__.py
  mlflow/h2o.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/models/container/__init__.py
  mlflow/onnx.py
  mlflow/paddle/__init__.py
  mlflow/pmdarima.py
  mlflow/prophet.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/backend.py
  mlflow/pyfunc/model.py
  mlflow/pytorch/__init__.py
  mlflow/shap.py
  mlflow/sklearn/__init__.py
  mlflow/spacy.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/tensorflow/__init__.py
  mlflow/utils/virtualenv.py
  mlflow/xgboost/__init__.py
  tests/catboost/test_catboost_model_export.py
  tests/diviner/test_diviner_model_export.py
  tests/fastai/test_fastai_model_export.py
  tests/gluon/test_gluon_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/keras/test_keras_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/onnx/test_onnx_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/pmdarima/test_pmdarima_model_export.py
  tests/prophet/test_prophet_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spacy/test_spacy_model_export.py
  tests/spark/test_spark_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/tensorflow/test_tensorflow2_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none, area/models, only-latest

#6733 Update get_model_dependencies to download all model artifacts
  mlflow/pyfunc/__init__.py
  mlflow/utils/model_utils.py
  tests/pyfunc/test_dependencies_functions.py
Labels: rn/none

#6741 Remove useless `pylint: disable=unused-variable`
  tests/autologging/test_autologging_behaviors_integration.py
  tests/projects/backend/test_local.py
  tests/tensorflow/test_tensorflow2_autolog.py
  tests/test_cli.py
  tests/utils/test_requirements_utils.py
Labels: rn/none

#6724 hyperparameter tuning
  mlflow/pipelines/steps/train.py
Labels: rn/none, area/pipelines

#6751 [doc] update CONTRIBUTING.rst instruction of git clone to use SSH instead of HTTPs
  CONTRIBUTING.rst
Labels: area/docs, rn/none

#6736 Add generated run name to create run backend stores if not supplied
  docs/source/tracking.rst
  mlflow/R/mlflow/tests/testthat/test-tracking-runs.R
  mlflow/java/client/src/test/java/org/mlflow/tracking/MlflowClientTest.java
  mlflow/server/handlers.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/fluent.py
  mlflow/utils/name_utils.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_rest_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/test_cli.py
  tests/tracking/test_tracking.py
  tests/utils/test_utils.py
Labels: rn/feature, area/tracking

#6761 Fix metric names in `examples/evaluation/evaluate_with_model_validation.py`
  examples/evaluation/evaluate_with_model_validation.py
  mlflow/models/evaluation/base.py
Labels: rn/none

#6760 Fix pmdarima dev cross-version test
  mlflow/ml-package-versions.yml
Labels: rn/none, area/models, enable-dev-tests

#6743 Support disjoint DAGs in MLP
  mlflow/pipelines/pipeline.py
  mlflow/pipelines/regression/v1/pipeline.py
  tests/pipelines/regression/v1/test_regression_pipeline.py
  tests/pipelines/test_pipeline.py
Labels: rn/none, area/pipelines

#6586 Wheeled Model
  mlflow/models/__init__.py
  mlflow/models/model.py
  mlflow/models/utils.py
  mlflow/models/wheeled_model.py
  tests/models/test_utils.py
  tests/models/test_wheeled_model.py
Labels: rn/feature, area/model-registry, area/models

#6678 Enable TF and Keras auto signature logging
  mlflow/tensorflow/__init__.py
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/breaking-change, area/models

#6762 Update autoformat bot to generate proto code
  .github/workflows/autoformat.js
  .github/workflows/autoformat.yml
  dev/Dockerfile.protos
  dev/test-generate-protos.sh
Labels: rn/none, area/build

#6567 Feature/csv data preview
  mlflow/server/js/package.json
  mlflow/server/js/src/common/utils/FileUtils.js
  mlflow/server/js/src/experiment-tracking/components/ArtifactView.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/LazyShowArtifactTableView.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactPage.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactPage.test.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactTableView.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactTableView.test.js
  mlflow/server/js/src/i18n/default/en.json
  mlflow/server/js/yarn.lock
Labels: rn/feature, area/uiux

#6753 [UI][easy] In addition to the file extension, also check if the selected artifact is directory when we show artifact view
  mlflow/server/js/src/experiment-tracking/components/ArtifactView.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactPage.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactPage.test.js
Labels: rn/none, area/uiux

#6745 Use `mslex.quote` when shell-escaping strings
  mlflow/projects/_project_spec.py
  mlflow/projects/databricks.py
  mlflow/rfunc/backend.py
  mlflow/utils/string_utils.py
  tests/utils/test_string_utils.py
Labels: rn/none, area/projects

#6772 Do not activate environment when `env_manager=local` in `mlflow models build-docker`
  mlflow/models/container/__init__.py
Labels: rn/none

#6769 Update RunInfo, CreateRun and UpdateRun infos to accept run names
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
Labels: rn/feature, area/tracking

#6591 [CLI] [FR] Add new CLI command for generating Dockerfile (issue #6532)
  mlflow/models/cli.py
  mlflow/models/docker_utils.py
  mlflow/models/flavor_backend.py
  mlflow/pyfunc/backend.py
  mlflow/rfunc/backend.py
  tests/helper_functions.py
  tests/models/test_cli.py
Labels: rn/feature, area/docker, area/build

#6784 Revert "Update RunInfo, CreateRun and UpdateRun infos to accept run names (#6769)"
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
Labels: rn/none, area/tracking

#6665 Add logging message to indicate whether cache is used
  mlflow/pipelines/regression/v1/pipeline.py
  mlflow/pipelines/step.py
  mlflow/pipelines/utils/execution.py
  tests/pipelines/test_execution_utils.py
  tests/pipelines/test_pipeline.py
Labels: rn/none, area/pipelines

#6731 Tracking server image
  docker/Dockerfile
Labels: rn/feature, area/docker, area/build

#6777 Convert CONTRIBUTING.rst to Markdown
  CONTRIBUTING.md
  CONTRIBUTING.rst
Labels: rn/none, area/projects

#6768 Move MLflow Pipelines dependencies to core
  .circleci/config.yml
  .github/workflows/pipeline-template.yml
  .github/workflows/pipeline.yml
  dev/Dockerfile.test
  docs/source/pipelines.rst
  docs/source/quickstart.rst
  requirements/core-requirements.txt
  requirements/core-requirements.yaml
  setup.py
  tests/utils/test_requirements_utils.py
Labels: rn/none, area/pipelines

#6787 [Java] Remove experiment, run, and model listing APIs in favor of search
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowClient.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowHttpCaller.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowProtobufMapper.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/samples/QuickStartDriver.java
  mlflow/java/client/src/test/java/org/mlflow/tracking/MlflowClientTest.java
Labels: rn/breaking-change, language/java, area/model-registry, area/tracking

#6662 Creating a data profiler to profile data frames.
  dev/generate-protos.sh
  mlflow/pipelines/cards/histogram_generator.py
  mlflow/pipelines/cards/pandas_renderer.py
  mlflow/protos/facet_feature_statistics.proto
  mlflow/protos/facet_feature_statistics_pb2.py
  tests/pipelines/cards/test_histogram_generator.py
  tests/pipelines/cards/test_pandas_renderer.py
Labels: rn/none, area/pipelines

#6788 [JS] Remove use of experiment, run, and model listing APIs in favor of search
  mlflow/server/js/src/experiment-tracking/actions.js
  mlflow/server/js/src/experiment-tracking/components/HomePage.js
  mlflow/server/js/src/experiment-tracking/components/HomePage.test.js
  mlflow/server/js/src/experiment-tracking/components/modals/CreateExperimentModal.js
  mlflow/server/js/src/experiment-tracking/components/modals/CreateExperimentModal.test.js
  mlflow/server/js/src/experiment-tracking/components/modals/DeleteExperimentModal.js
  mlflow/server/js/src/experiment-tracking/components/modals/DeleteExperimentModal.test.js
  mlflow/server/js/src/experiment-tracking/reducers/Reducers.js
  mlflow/server/js/src/experiment-tracking/reducers/Reducers.test.js
  mlflow/server/js/src/experiment-tracking/sdk/MlflowMessages.js
  mlflow/server/js/src/experiment-tracking/sdk/MlflowService.js
  mlflow/server/js/src/model-registry/actions.js
  mlflow/server/js/src/model-registry/components/RegisterModelButton.js
  mlflow/server/js/src/model-registry/components/RegisterModelButton.test.js
  mlflow/server/js/src/model-registry/reducers.js
  mlflow/server/js/src/model-registry/reducers.test.js
  mlflow/server/js/src/model-registry/services.js
Labels: rn/none, area/uiux

#6785 [Python] Remove experiment, run, and model listing APIs in favor of search
  examples/rest_api/mlflow_tracking_rest_api.py
  mlflow/__init__.py
  mlflow/experiments.py
  mlflow/server/handlers.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/_tracking_service/utils.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  mlflow/utils/__init__.py
  mlflow/utils/validation.py
  tests/db/test_tracking_operations.py
  tests/store/artifact/test_mlflow_artifact_repo.py
  tests/store/tracking/test_abstract_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_rest_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/test_cli.py
  tests/tracking/_tracking_service/test_utils.py
  tests/tracking/fluent/test_fluent.py
  tests/tracking/test_rest_tracking.py
  tests/tracking/test_tracking.py
  tests/utils/test_validation.py
Labels: rn/breaking-change, area/model-registry, area/tracking

#6791 Replace `CONTRIBUTING.rst` with `CONTRIBUTING.md`
  .github/ISSUE_TEMPLATE/feature_request_template.yaml
  .github/workflows/notify-dco-failure.js
  CODE_OF_CONDUCT.rst
  CONTRIBUTING.md
  README.rst
  docs/theme/mlflow/side_nav.html
  mlflow/R/mlflow/README.Rmd
  mlflow/R/mlflow/README.md
  mlflow/server/__init__.py
  mlflow/store/db_migrations/README.md
  tests/tracking/_model_registry/test_utils.py
  tests/tracking/_tracking_service/test_utils.py
Labels: area/docs, rn/none

#6580 Update mlflowclient to implement java.io.closeable
  mlflow/java/client/README.md
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowClient.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowHttpCaller.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/samples/FluentExample.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/samples/QuickStartDriver.java
  mlflow/java/client/src/test/java/org/mlflow/tracking/TestClientProvider.java
Labels: rn/none, language/java

#6781 Added keras pyfunc usage example
  docs/source/models.rst
Labels: area/docs, rn/none

#6766 Fix batch scoring pipeline artifact writing on Databricks
  .github/workflows/master.yml
  mlflow/pipelines/regression/v1/pipeline.py
  mlflow/pipelines/steps/predict.py
  mlflow/utils/file_utils.py
  tests/pipelines/test_predict_step.py
  tests/utils/test_file_utils.py
Labels: rn/none

#6796 Fix bug with 1-D arrays
  mlflow/tensorflow/__init__.py
  tests/tensorflow/test_tensorflow2_model_export.py
Labels: rn/bug-fix, area/scoring

#6752 writing params to yaml and show in step card
  mlflow/pipelines/regression/v1/pipeline.py
  mlflow/pipelines/steps/train.py
Labels: rn/none, area/pipelines

#6756 adding creation_time and last_update_time to experiment
  mlflow/entities/experiment.py
  mlflow/store/db_migrations/versions/97727af70f4d_creation_time_last_update_time_experiments.py
  mlflow/store/tracking/dbmodels/models.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/fluent.py
  tests/db/schemas/mssql.sql
  tests/db/schemas/mysql.sql
  tests/db/schemas/postgresql.sql
  tests/db/schemas/sqlite.sql
  tests/db/test_schema.py
  tests/db/update_schemas.sh
  tests/entities/test_experiment.py
  tests/resources/db/latest_schema.sql
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/feature, area/tracking

#6786 [R] Remove experiment, run, and model listing APIs in favor of search
  .github/ISSUE_TEMPLATE/feature_request_template.yaml
  .github/workflows/notify-dco-failure.js
  CODE_OF_CONDUCT.rst
  README.rst
  docs/source/R-api.rst
  docs/theme/mlflow/side_nav.html
  mlflow/R/mlflow/NAMESPACE
  mlflow/R/mlflow/R/model-registry.R
  mlflow/R/mlflow/R/tracking-experiments.R
  mlflow/R/mlflow/R/tracking-runs.R
  mlflow/R/mlflow/R/tracking-server.R
  mlflow/R/mlflow/README.Rmd
  mlflow/R/mlflow/README.md
  mlflow/R/mlflow/man/mlflow_list_experiments.Rd
  mlflow/R/mlflow/man/mlflow_list_run_infos.Rd
  mlflow/R/mlflow/man/mlflow_search_registered_models.Rd
  mlflow/R/mlflow/tests/testthat/test-client.R
  mlflow/R/mlflow/tests/testthat/test-model-registry.R
  mlflow/R/mlflow/tests/testthat/test-run.R
  mlflow/R/mlflow/tests/testthat/test-tracking-experiments.R
  mlflow/R/mlflow/tests/testthat/test-tracking-runs.R
  mlflow/server/__init__.py
  mlflow/store/db_migrations/README.md
  tests/tracking/_model_registry/test_utils.py
  tests/tracking/_tracking_service/test_utils.py
Labels: language/r, rn/breaking-change, area/model-registry, area/tracking

#6800 Remove list API references from docs
  docs/source/model-registry.rst
  docs/source/search-runs.rst
  docs/source/tracking.rst
Labels: area/docs, rn/breaking-change

#6801 Fix flaky `test_download_artifacts`
  tests/store/artifact/test_mlflow_artifact_repo.py
Labels: rn/none, area/artifacts

#6808 Model Validation polishing
  docs/source/models.rst
  mlflow/models/evaluation/base.py
Labels: rn/none

#6809 Add setuptools for packaging dependency resolution
  dev/requirements.txt
Labels: rn/none, area/build

#6806 Introduce sample_weights arg to mlflow.evaluate()
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/models/evaluation/lift_curve.py
  mlflow/models/utils.py
  tests/models/test_default_evaluator.py
Labels: rn/feature, area/models

#6804 Retry conda env creation in pytest session
  mlflow/utils/conda.py
  tests/projects/test_projects.py
Labels: rn/none

#6810 Revert "Add setuptools for packaging dependency resolution"
  dev/requirements.txt
Labels: rn/none

#6803 Update `dev/update_changelog.py` to automatically add category to entries in `CHANGELOG.md`
  dev/update_changelog.py
Labels: rn/none

#6792 Integrating step card with pandas_renderer
  mlflow/__init__.py
  mlflow/cli.py
  mlflow/pipelines/cards/__init__.py
  mlflow/pipelines/cards/pandas_renderer.py
  mlflow/pipelines/steps/ingest/__init__.py
  mlflow/pipelines/utils/step.py
  tests/pipelines/cards/test_base_card.py
  tests/pipelines/test_ingest_step.py
  tests/pipelines/test_step_utils.py
Labels: rn/feature, area/pipelines

#6730 Added ADLS Gen2 support to mlflow
  mlflow/azure/client.py
  mlflow/java/client/src/main/java/com/databricks/api/proto/mlflow/DatabricksArtifacts.java
  mlflow/protos/databricks_artifacts.proto
  mlflow/protos/databricks_artifacts_pb2.py
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/utils/rest_utils.py
Labels: rn/none, area/artifacts, integrations/azure

#6807 Implemented `unwrap_python_model()` method in mlflow.pyfunc.PyFuncModel
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_pyfunc_class_methods.py
Labels: rn/none, area/models

#6798 Update RunInfo, CreateRun and UpdateRun proto messages to accept run names
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
Labels: rn/feature, area/tracking

#6782 Add run name field to MLflow create/get/update API implementations for all stores
  mlflow/R/mlflow/tests/testthat/test-tracking-runs.R
  mlflow/entities/run_info.py
  mlflow/java/client/src/test/java/org/mlflow/tracking/MlflowClientTest.java
  mlflow/runs.py
  mlflow/server/handlers.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/dbmodels/models.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  mlflow/utils/autologging_utils/client.py
  tests/autologging/test_autologging_client.py
  tests/entities/test_run.py
  tests/entities/test_run_info.py
  tests/store/tracking/test_abstract_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_rest_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/test_cli.py
  tests/tracking/fluent/test_fluent.py
  tests/tracking/test_client.py
  tests/tracking/test_rest_tracking.py
  tests/tracking/test_tracking.py
Labels: rn/feature, area/tracking

#6732 Create push-images.yml
  .github/workflows/push-images.yml
Labels: rn/none, area/docker, area/build

#6830 Mark the `unwrap_python_model()` method as experimental
  mlflow/pyfunc/__init__.py
Labels: rn/none, area/models

#6833 Set version to 2.0 in 2.0 branch
  mlflow/R/mlflow/DESCRIPTION
  mlflow/java/client/pom.xml
  mlflow/java/pom.xml
  mlflow/java/scoring/pom.xml
  mlflow/java/spark/pom.xml
  mlflow/server/js/src/common/constants.js
  mlflow/version.py
Labels: rn/none, area/build

#6834 Fix `TypeError: None has type NoneType, but expected one of: bytes, unicode` in `RunInfo.to_proto`
  mlflow/entities/run_info.py
Labels: rn/none

#6530 Remove `mlflow.keras` module, drop mlflow TF estimator autologging and logging/saving TF estimator model code, integrate logging keras model code to mlflow.log_model, Support saving and loading TF2 module
  .github/workflows/master.yml
  docs/source/models.rst
  docs/source/python_api/mlflow.keras.rst
  docs/source/tracking.rst
  examples/README.md
  examples/flower_classifier/image_pyfunc.py
  examples/flower_classifier/train.py
  examples/hyperparam/train.py
  examples/keras/train.py
  examples/multistep_workflow/train_keras.py
  examples/tensorflow/README.md
  examples/tensorflow/tf2/MLproject
  examples/tensorflow/tf2/README.md
  examples/tensorflow/tf2/python_env.yaml
  examples/tensorflow/tf2/train_predict_2.py
  mlflow/__init__.py
  mlflow/keras.py
  mlflow/ml-package-versions.yml
  mlflow/models/__init__.py
  mlflow/pyfunc/__init__.py
  mlflow/tensorflow/__init__.py
  mlflow/tracking/fluent.py
  requirements/extra-ml-requirements.txt
  tests/autologging/test_autologging_behaviors_integration.py
  tests/helper_functions.py
  tests/keras/test_keras_autolog.py
  tests/pyfunc/test_scoring_server.py
  tests/tensorflow/mlflow-128-tf-23-env.yaml
  tests/tensorflow/save_keras_model.py
  tests/tensorflow/save_tf_estimator_model.py
  tests/tensorflow/test_keras_model_export.py
  tests/tensorflow/test_keras_pyfunc_model_works_with_all_input_types.py
  tests/tensorflow/test_load_saved_tensorflow_estimator.py
  tests/tensorflow/test_tensorflow2_autolog.py
  tests/tensorflow/test_tensorflow2_core_model_export.py
  tests/tensorflow/test_tensorflow2_model_export.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/breaking-change, area/tracking

#6828 Giving important to user defined metrics in step card
  mlflow/pipelines/steps/evaluate.py
  mlflow/pipelines/steps/train.py
Labels: rn/none, area/pipelines

#6823 hp tuning with sparktrials
  mlflow/pipelines/steps/train.py
Labels: rn/none, area/pipelines

#6799 tuning tests
  mlflow/pipelines/steps/train.py
  requirements/test-requirements.txt
  tests/pipelines/test_train_step.py
Labels: rn/none, area/pipelines

#6831 Fix infinite recursion in `get_feature_cols`
  mlflow/pyspark/ml/__init__.py
  mlflow/pyspark/ml/_autolog.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
Labels: rn/bug-fix, area/models

#6824 pytorch examples - PTL 1.7.6 fixes
  examples/pytorch/AxHyperOptimizationPTL/conda.yaml
  examples/pytorch/BertNewsClassification/MLproject
  examples/pytorch/BertNewsClassification/README.md
  examples/pytorch/BertNewsClassification/bert_classification.py
  examples/pytorch/BertNewsClassification/conda.yaml
  examples/pytorch/IterativePruning/conda.yaml
  examples/pytorch/MNIST/MLproject
  examples/pytorch/MNIST/README.md
  examples/pytorch/MNIST/conda.yaml
  examples/pytorch/MNIST/mnist_autolog_example.py
Labels: rn/none, area/examples

#6849 Set working directory in `dev/Dockerfile.protos`
  dev/Dockerfile.protos
Labels: rn/none

#6829 Add local test for validation of git branch pull for project run
  tests/projects/test_projects_cli.py
Labels: rn/none, area/projects

#6728 Add environment restoration to mlflow.evaluate()
  .github/workflows/master.yml
  examples/evaluation/evaluate_with_model_validation.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/pyfunc/__init__.py
  mlflow/utils/conda.py
  mlflow/utils/env_manager.py
  tests/models/test_cli.py
  tests/models/test_default_evaluator.py
  tests/models/test_evaluation.py
Labels: rn/feature, area/models

#6520 Remove mlflow.sklearn.eval_and_log_metrics() API
  .github/workflows/cross-version-tests.yml
  mlflow/sklearn/__init__.py
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/breaking-change, area/models

#6844 add hp tuning to docs
  mlflow/pipelines/regression/v1/pipeline.py
Labels: area/docs, rn/none, area/pipelines

#6846 Spark session jupyter
  mlflow/pipelines/steps/ingest/datasets.py
  mlflow/pipelines/steps/predict.py
  mlflow/utils/_spark_utils.py
  tests/pipelines/test_ingest_step.py
Labels: rn/bug-fix, area/pipelines

#6853 minor UI fixes in train output card
  mlflow/pipelines/steps/train.py
  tests/pipelines/test_train_step.py
Labels: rn/none, area/pipelines

#6850 Add transformer package dependency for tensorflow cross tests.
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#6855 Add dependency `transformers` to extra-ml-requirements, `virtualenv` to test-requirements
  requirements/test-requirements.txt
Labels: rn/none, area/build

#6861 [ML-25315] error for pipelines in old DBR
  mlflow/pipelines/utils/step.py
  tests/pipelines/test_step_utils.py
Labels: rn/none, area/pipelines

#6859 Hyperparameter tuning in MLP
  docs/source/pipelines.rst
  mlflow/pipelines/regression/v1/pipeline.py
  mlflow/pipelines/steps/train.py
  requirements/test-requirements.txt
  tests/pipelines/test_train_step.py
Labels: area/docs, rn/feature, area/pipelines

#6872 Make creating python environment output less verbose
  mlflow/utils/conda.py
  mlflow/utils/virtualenv.py
Labels: rn/none, area/scoring, area/tracking

#6860 Merge train/validation/test profiles into one card in the split step
  mlflow/pipelines/steps/ingest/__init__.py
  mlflow/pipelines/steps/predict.py
  mlflow/pipelines/steps/split.py
  mlflow/pipelines/steps/train.py
  mlflow/pipelines/steps/transform.py
  mlflow/pipelines/utils/step.py
  tests/pipelines/test_ingest_step.py
  tests/pipelines/test_predict_step.py
  tests/pipelines/test_split_step.py
  tests/pipelines/test_step_utils.py
Labels: rn/none, area/pipelines

#6868 [2.0] Remove list_run_infos
  examples/multistep_workflow/main.py
  mlflow/store/tracking/abstract_store.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  tests/fastai/test_fastai_autolog.py
  tests/lightgbm/test_lightgbm_autolog.py
  tests/projects/test_databricks.py
  tests/projects/test_docker_projects.py
  tests/projects/test_projects.py
  tests/pytorch/test_pytorch_autolog.py
  tests/sklearn/test_sklearn_autolog.py
  tests/statsmodels/test_statsmodels_autolog.py
  tests/store/tracking/test_abstract_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tensorflow/test_tensorflow2_autolog.py
  tests/tracking/test_rest_tracking.py
  tests/tracking/test_tracking.py
  tests/xgboost/test_xgboost_autolog.py
Labels: rn/breaking-change, area/tracking

#6884 Use `TokenType.Name.Builtin` when parsing order_by
  mlflow/utils/search_utils.py
Labels: rn/none

#6885 Fix `test_pyfunc_serve_and_score_transformers`
  tests/keras/test_keras_model_export.py
Labels: enable-dev-tests

#6887 Extend pytest monkeypatch fixture to use `setenvs` and `delenvs`
  tests/conftest.py
  tests/projects/test_databricks.py
Labels: rn/none

#6845 Add unit test for DatabricksArtifactRepository uploading artifacts through ADL Gen2
  tests/store/artifact/test_databricks_artifact_repo.py
Labels: rn/none

#6875 [ML-25305] reduce logging part1
  mlflow/pipelines/steps/ingest/__init__.py
  mlflow/pipelines/steps/ingest/datasets.py
  mlflow/pipelines/steps/split.py
  mlflow/pipelines/steps/train.py
  mlflow/pipelines/utils/execution.py
  tests/pipelines/test_pipeline.py
Labels: rn/none, area/pipelines

#6876 [ML-25327] shortened step card names
  mlflow/pipelines/steps/evaluate.py
  mlflow/pipelines/steps/train.py
Labels: rn/none, area/pipelines

#6862 Add logger documentation and set capture output for evaluate env restoration
  docs/source/python_api/index.rst
  mlflow/pyfunc/__init__.py
Labels: rn/none

#6892 Removing validation profiling from transform step
  mlflow/pipelines/steps/transform.py
Labels: rn/none, area/pipelines

#6886 Debug traceback when logging model metadata failed
  mlflow/models/model.py
Labels: rn/none

#6895 [ML-25317] remove conda install for MLP
  docs/source/pipelines.rst
Labels: rn/none, area/pipelines

#6888 Get run name from tags
  mlflow/entities/run_info.py
  mlflow/store/tracking/dbmodels/models.py
  mlflow/store/tracking/file_store.py
  mlflow/utils/mlflow_tags.py
Labels: rn/none

#6890 Store `mlflow.runName` tag when creating or updating run
  mlflow/R/mlflow/tests/testthat/test-tracking-runs.R
  mlflow/java/client/src/test/java/org/mlflow/tracking/MlflowClientTest.java
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/test_tracking.py
Labels: rn/none, area/tracking

#6898 Use timestamp in milliseconds
  examples/rest_api/mlflow_tracking_rest_api.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/pyspark/ml/__init__.py
  mlflow/sklearn/utils.py
  mlflow/store/model_registry/dbmodels/models.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/store/tracking/dbmodels/models.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tensorflow/__init__.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/fluent.py
  mlflow/utils/autologging_utils/client.py
  mlflow/utils/time_utils.py
  tests/entities/test_experiment.py
  tests/entities/test_metric.py
  tests/entities/test_run_data.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/dummy_evaluator.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/test_cli.py
  tests/tracking/fluent/test_fluent.py
  tests/tracking/test_model_registry.py
  tests/tracking/test_rest_tracking.py
  tests/tracking/test_tracking.py
Labels: rn/none, area/tracking

#6880 adding end_time attribute of RunInfo in search_runs
  docs/source/search-runs.rst
  mlflow/entities/run_info.py
  mlflow/utils/search_utils.py
  tests/entities/test_run_info.py
  tests/utils/test_search_utils.py
Labels: rn/feature, area/tracking

#6903 fix: remove potential duplicate downloads for spark flavor
  mlflow/spark.py
Labels: rn/bug-fix, area/models

#6902 Fix to make manual test passes
  mlflow/azure/client.py
  mlflow/spark.py
  mlflow/store/artifact/databricks_artifact_repo.py
Labels: rn/none, area/tracking

#6896 [ML-25308] show data preview in ingest step card
  mlflow/pipelines/steps/ingest/__init__.py
  tests/pipelines/test_ingest_step.py
Labels: rn/none, area/pipelines

#6881 adding user_id attribute of RunInfo in search_runs
  docs/source/search-runs.rst
  mlflow/entities/run_info.py
  tests/entities/test_run_info.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/utils/test_search_utils.py
Labels: rn/feature, area/tracking

#6879 Update tracking.rst
  docs/source/tracking.rst
Labels: rn/documentation

#6901 Replace `TokenType.keyword` with `TokenType.Keyword` (capital `K`)
  mlflow/utils/search_utils.py
Labels: rn/none

#6900 Fix bug: `=` and `!=` operators are not case-sensitive in run search
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/utils/search_utils.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none, area/tracking

#6916 Fix: disable dangerous-default-value in tests/pipelines/test_train_step.py
  tests/pipelines/test_train_step.py
Labels: rn/none

#6750 Refactor mlflow pipelines code in preparation for classification template
  mlflow/pipelines/step.py
  mlflow/pipelines/steps/evaluate.py
  mlflow/pipelines/steps/train.py
  mlflow/pipelines/utils/metrics.py
  tests/pipelines/test_pipeline.py
Labels: rn/none, area/pipelines

#6923 Add env_manager property to _ServedPyFuncModel class
  mlflow/pyfunc/__init__.py
  tests/models/test_evaluation.py
Labels: rn/none

#6883 Support an environment variable option to use sqlalchemy.pool.NullPool
  mlflow/environment_variables.py
  mlflow/store/db/utils.py
  tests/store/db/test_utils.py
Labels: rn/feature, area/sqlalchemy

#6911 Fix single upload
  mlflow/azure/client.py
  mlflow/store/artifact/databricks_artifact_repo.py
  tests/store/artifact/test_databricks_artifact_repo.py
Labels: rn/none, area/artifacts

#6919 Update spark config in test
  tests/pyfunc/test_spark.py
Labels: rn/none, area/build

#6899 Support searching for runs by `run_name`
  docs/source/search-runs.rst
  mlflow/entities/run_info.py
  mlflow/store/tracking/dbmodels/models.py
  mlflow/store/tracking/sqlalchemy_store.py
  tests/entities/test_run_info.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/feature, area/tracking
