Repository mlflow/mlflow, pull requests merged in 2022-08, with the labels that each got.

#6372 Add a status badge for the stale action
  README.rst
Labels: rn/none, area/build

#6362 Skipping the transform step by using Functional transformer
  mlflow/pipelines/steps/transform.py
  tests/pipelines/test_transform_step.py
Labels: rn/none, area/pipelines

#6361 Series schema
  mlflow/types/utils.py
  tests/types/test_schema.py
Labels: rn/feature, area/model-registry

#6282 Integrate mlflowdbfs with mlflow python client
  mlflow/environment_variables.py
  mlflow/spark.py
  mlflow/tracking/artifact_utils.py
  mlflow/utils/databricks_utils.py
  tests/spark/test_spark_model_export.py
Labels: rn/feature, integrations/databricks

#6378 Fix step card display breakage in Jupyter notebooks
  mlflow/pipelines/utils/step.py
Labels: rn/none, area/pipelines

#6380 Avoid using flask 2.2.0
  requirements/test-requirements.txt
Labels: rn/none, area/build

#6375 Migrate GCS environment variables to `mlflow.environment_variables` module
  mlflow/environment_variables.py
  mlflow/store/artifact/gcs_artifact_repo.py
Labels: rn/none

#6365 Avoid logging model signatures in pyspark ML autologging if model input/output dataframe contains unsupported data types
  mlflow/pyspark/ml/__init__.py
  mlflow/types/schema.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
Labels: rn/bug-fix, area/models

#6373 Refactor `set_matrix.py`
  .github/workflows/cross-version-tests.yml
  dev/requirements.txt
  dev/set_matrix.py
  tests/dev/test_set_matrix.py
Labels: rn/none, area/build

#6385 Fix `is_matrix_empty` in cross-version tests
  dev/set_matrix.py
Labels: rn/none

#5897 Allow mlflow-skinny's autolog() to succeed when no scipy is installed
  dev/run-python-skinny-tests.sh
  docs/source/conf.py
  mlflow/models/utils.py
  mlflow/pyfunc/__init__.py
  tests/test_skinny_client_autolog_without_scipy.py
Labels: rn/none, area/artifacts, area/tracking

#6389 Fix extraneous warning about pyspark evaluation truncation
  mlflow/models/evaluation/base.py
Labels: rn/none, area/tracking

#6386 Revert #6380
  conftest.py
  requirements/test-requirements.txt
Labels: rn/none, area/build

#6381 Validate metric value in `FileStore.log_metric`
  mlflow/java/client/src/test/java/org/mlflow/tracking/MlflowClientTest.java
  mlflow/store/tracking/file_store.py
  mlflow/utils/validation.py
  tests/store/tracking/test_file_store.py
Labels: rn/none

#6333 Make search experiment by tag key comparison case sensitive in MYSQL
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/utils/search_utils.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/bug-fix, area/tracking

#6390 Run Model Registry SQLAlchemy tests in PostgreSQL, MySQL, and MSSQL
  mlflow/store/model_registry/sqlalchemy_store.py
  tests/store/model_registry/test_sqlalchemy_store.py
Labels: rn/none, area/build

#6388 Fix filestore data loss on failed write & mitigate read / write race condition
  mlflow/store/tracking/file_store.py
  tests/store/tracking/test_file_store.py
Labels: rn/bug-fix, area/tracking

#6368 Added a custom filter from_json to render_and_merge_yaml
  mlflow/utils/file_utils.py
  tests/utils/test_file_utils.py
Labels: rn/none, area/pipelines

#6397 Fix `!=` operator for MySQL
  mlflow/utils/search_utils.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none, area/sqlalchemy

#6398 Simplify the documentation section in the PR template
  .github/pull_request_template.md
Labels: rn/none

#6354 Timebased gc
  mlflow/cli.py
  mlflow/store/db_migrations/versions/0c779009ac13_add_deleted_time_field_to_runs_table.py
  mlflow/store/tracking/dbmodels/models.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  tests/db/schemas/mssql.sql
  tests/db/schemas/mysql.sql
  tests/db/schemas/postgresql.sql
  tests/db/schemas/sqlite.sql
  tests/resources/db/initial_models.py
  tests/resources/db/latest_schema.sql
  tests/resources/example_virtualenv_conda_project/conda.yaml
  tests/resources/example_virtualenv_project/requirements.txt
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/test_cli.py
Labels: rn/feature, area/tracking, area/sqlalchemy

#6399 Separate protos job
  .github/workflows/master.yml
  .github/workflows/protos.yml
Labels: rn/none, area/build

#6402 Fix flaky `TestFileStore.test_get_deleted_runs`
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
Labels: rn/none, area/tracking

#6396 Migrate environment variables for SQLAlchemy store to `mlflow.environment_variables`
  mlflow/environment_variables.py
  mlflow/store/db/utils.py
Labels: rn/none, area/sqlalchemy

#6405 Deduplicate MlflowClient in MLflow docs, move to mlflow.client module
  docs/source/model-registry.rst
  docs/source/projects.rst
  docs/source/python_api/mlflow.client.rst
  docs/source/python_api/mlflow.rst
  docs/source/search-experiments.rst
  docs/source/search-runs.rst
  docs/source/tracking.rst
  mlflow/__init__.py
  mlflow/client.py
  mlflow/tracking/fluent.py
Labels: rn/documentation

#6408 Remove unused functions in `mlflow.data` module
  mlflow/data.py
Labels: rn/none, area/tracking

#6320 Tag based registered model search and model version search
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  mlflow/utils/search_utils.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/tracking/test_model_registry.py
Labels: rn/feature, area/model-registry

#6358 Increase maximum param value length to 500
  mlflow/store/db_migrations/versions/cc1f77228345_change_param_value_length_to_500.py
  mlflow/store/tracking/dbmodels/models.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  mlflow/utils/validation.py
  tests/db/schemas/mssql.sql
  tests/db/schemas/mysql.sql
  tests/db/schemas/postgresql.sql
  tests/db/schemas/sqlite.sql
  tests/resources/db/latest_schema.sql
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: area/docs, rn/bug-fix, area/tracking, area/sqlalchemy

#6418 Add workflow dispatch for requirements validation, remove duplicate file
  .github/workflows/requirements.yml
  .github/workflows/test-requirements.yml
Labels: rn/none, area/build

#6328 [Model Validation] Add MetricThreshold and Model Validation Functionality to MLflow.evaluate
  mlflow/models/__init__.py
  mlflow/models/evaluation/__init__.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/validation.py
  tests/models/test_validation.py
Labels: rn/feature, area/models

#6417 Fix regression in pandas type inference behavior for scoring server
  mlflow/types/schema.py
  mlflow/utils/proto_json_utils.py
  tests/models/test_model.py
  tests/pyfunc/test_scoring_server.py
  tests/utils/test_proto_json_utils.py
Labels: rn/none, area/scoring

#6415 Adjust client to use SearchExperiments POST method
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
  tests/store/tracking/test_rest_store.py
Labels: rn/none

#6420 Fix CI error __init__() got an unexpected keyword argument 'unbound_message' when importing flask
  requirements/test-requirements.txt
Labels: rn/none, area/build

#6355 Check if artifacts are proxied in model_version_artifact_handler
  mlflow/server/handlers.py
  tests/tracking/test_mlflow_artifacts.py
Labels: rn/bug-fix, area/uiux, area/artifacts, area/models

#6413 Allow sql filter IN operator right-hand side values including whitespaces
  mlflow/utils/search_utils.py
  tests/store/model_registry/test_sqlalchemy_store.py
Labels: rn/bug-fix, area/tracking

#6411 Fix IN operator related issues in sql filter parser
  examples/rapids/mlflow_project/envs/conda.yaml
  examples/rapids/mlflow_project/notebooks/conda.yaml
  mlflow/utils/search_utils.py
  requirements/skinny-requirements.txt
  requirements/skinny-requirements.yaml
Labels: rn/bug-fix, area/tracking

#6412 Remove unused method `SearchUtils._get_comparison_for_model_registry`
  mlflow/utils/search_utils.py
Labels: rn/none, area/tracking

#6430 Deprecation message update
  mlflow/utils/annotations.py
Labels: area/docs, rn/none

#6426 Raise clear error message when pipeline path contains a space
  mlflow/pipelines/pipeline.py
  tests/pipelines/test_pipeline.py
Labels: rn/bug-fix

#6440 Patch mlflowdbfs availability check on credential passthrough clusters
  mlflow/spark.py
Labels: rn/none, area/models

#6437 Augment predict step to use model name for register step
  mlflow/pipelines/steps/predict.py
  mlflow/pipelines/steps/split.py
  tests/pipelines/test_predict_step.py
Labels: rn/none, area/pipelines

#6423 Add data capture config to SageMaker Deployments
  mlflow/sagemaker/__init__.py
Labels: rn/feature, integrations/sagemaker

#6452 Fix small search_runs docs issues
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: rn/none

#6461 Avoid using xgboost on conda-forge
  mlflow/R/mlflow/.create-test-env.R
Labels: language/r, rn/none

#6460 Add environment variable for `echo` option in `create_engine`
  mlflow/environment_variables.py
  mlflow/store/db/utils.py
  tests/store/db/test_utils.py
  tests/test_environment_variables.py
Labels: rn/none, area/tracking

#6463 Avoid using assertions at top level in `mlflow/models/docker_utils.py`
  mlflow/models/docker_utils.py
Labels: rn/none, area/build

#6474 Fix mlflowdbfs availability check
  mlflow/environment_variables.py
  mlflow/spark.py
  tests/spark/test_spark_model_export.py
Labels: rn/none, area/models

#6464 Replace `assertRaisesRegex` with `pytest.raises`
  pylint_plugins/unittest_assert_raises.py
  tests/entities/test_run_status.py
  tests/pylint_plugins/test_unittest_assert_raises.py
  tests/store/db/test_utils.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/store/tracking/__init__.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none, area/build

#6376 CLI command suggestion after running the pipeline
  mlflow/pipelines/pipeline.py
  mlflow/pipelines/steps/train.py
  mlflow/server/js/src/common/utils/Utils.js
  mlflow/server/js/src/experiment-tracking/components/RunView.css
  mlflow/server/js/src/experiment-tracking/components/RunView.js
  mlflow/utils/mlflow_tags.py
  tests/pipelines/test_train_step.py
Labels: rn/feature, area/uiux, area/pipelines

#6481 Remove redundant int conversion in `create_sqlalchemy_engine`
  mlflow/store/db/utils.py
Labels: rn/none, area/tracking

#6478 Improve code-to-reproduce section in the bug report template
  .github/ISSUE_TEMPLATE/bug_report_template.yaml
Labels: rn/none, area/build

#6456 Add Pipelines step option to skip step profiling
  mlflow/pipelines/steps/ingest/__init__.py
  mlflow/pipelines/steps/split.py
  mlflow/pipelines/steps/train.py
  mlflow/pipelines/steps/transform.py
  tests/pipelines/test_ingest_step.py
  tests/pipelines/test_split_step.py
Labels: rn/feature, area/pipelines

#6482 Implement _download_file in hdfs_artifact_repo
  mlflow/server/handlers.py
Labels: rn/bug-fix, area/artifacts

#6484 [ML-19871] R documentation fix
  docs/source/R-api.rst
  mlflow/R/mlflow/R/model-registry.R
  mlflow/R/mlflow/man/mlflow_transition_model_version_stage.Rd
Labels: area/docs, language/r, rn/none

#6489 Use `virtualenv` by default when running an ML project
  mlflow/cli.py
  mlflow/projects/_project_spec.py
  mlflow/utils/cli_args.py
  tests/projects/test_virtualenv_projects.py
  tests/projects/utils.py
  tests/resources/example_virtualenv_no_python_env/MLproject
  tests/resources/example_virtualenv_no_python_env/entrypoint.py
  tests/resources/example_virtualenv_no_python_env/python_env.yaml
  tests/resources/example_virtualenv_no_python_env/requirements.txt
Labels: rn/none, area/projects

#6483 feat: return param value for mlflow.log_param
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  tests/tracking/test_tracking.py
Labels: rn/none, area/tracking

#6459 Use `virtualenv` by default when restoring a model environment
  .github/workflows/master.yml
  .github/workflows/r.yml
  mlflow/models/cli.py
  mlflow/pyfunc/__init__.py
  mlflow/sagemaker/cli.py
  mlflow/utils/cli_args.py
  mlflow/utils/environment.py
  mlflow/utils/virtualenv.py
  tests/models/test_cli.py
  tests/pyfunc/test_spark.py
  tests/utils/test_python_env.py
Labels: rn/feature, area/models

#6490 Set `busy_timeout` for SQLite to deflake `test_log_metric_concurrent_logging_succeeds`
  mlflow/store/db/utils.py
Labels: rn/none, area/build

#6492 Ignore empty environment variables in `_get_maven_proxy`
  mlflow/models/docker_utils.py
Labels: rn/none, area/build

#6501 Remove `--no-conda`
  docs/source/R-api.rst
  docs/source/quickstart.rst
  mlflow/R/mlflow/R/project-run.R
  mlflow/R/mlflow/man/mlflow_run.Rd
  mlflow/cli.py
  mlflow/models/cli.py
  mlflow/utils/cli_args.py
  tests/models/test_cli.py
  tests/projects/test_kubernetes.py
  tests/projects/test_projects_cli.py
Labels: rn/breaking-change

#6438 Migrate environment variables for S3
  mlflow/environment_variables.py
  mlflow/projects/backend/local.py
  mlflow/store/artifact/hdfs_artifact_repo.py
  mlflow/store/artifact/s3_artifact_repo.py
  tests/store/artifact/test_s3_artifact_repo.py
Labels: rn/none

#6505 Remove `branches` on `pull_request`
  .github/workflows/examples.yml
  .github/workflows/js.yml
  .github/workflows/r.yml
  .github/workflows/test-package-build.yml
Labels: rn/none, area/build

#6509 Document how to install `mlflow-pipelines` from conda
  docs/source/pipelines.rst
  docs/source/quickstart.rst
Labels: area/docs, rn/none

#6506 Move tests for pylint plugins in `pylint_plugin` directory
  .github/workflows/master.yml
  pylint_plugins/tests/test_print_function.py
  pylint_plugins/tests/test_pytest_raises_checker.py
  pylint_plugins/tests/test_unittest_assert_raises.py
  pylint_plugins/tests/utils.py
  tests/pylint_plugins/test_print_function.py
  tests/pylint_plugins/test_unittest_assert_raises.py
  tests/pylint_plugins/utils.py
Labels: rn/none

#6514 Retry pulling docker image on CircleCI
  docs/build-rdoc.sh
Labels: rn/none, area/build

#6510 Sync `branch-2.0` with master
  .github/ISSUE_TEMPLATE/bug_report_template.yaml
  .github/workflows/examples.yml
  .github/workflows/js.yml
  .github/workflows/r.yml
  .github/workflows/test-package-build.yml
  docs/source/R-api.rst
  mlflow/R/mlflow/R/model-registry.R
  mlflow/R/mlflow/man/mlflow_transition_model_version_stage.Rd
  mlflow/environment_variables.py
  mlflow/models/docker_utils.py
  mlflow/pipelines/pipeline.py
  mlflow/pipelines/steps/ingest/__init__.py
  mlflow/pipelines/steps/split.py
  mlflow/pipelines/steps/train.py
  mlflow/pipelines/steps/transform.py
  mlflow/projects/backend/local.py
  mlflow/server/handlers.py
  mlflow/server/js/src/common/utils/FileUtils.js
  mlflow/server/js/src/common/utils/Utils.js
  mlflow/server/js/src/experiment-tracking/components/RunView.css
  mlflow/server/js/src/experiment-tracking/components/RunView.js
  mlflow/spark.py
  mlflow/store/artifact/hdfs_artifact_repo.py
  mlflow/store/artifact/s3_artifact_repo.py
  mlflow/store/db/utils.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  mlflow/utils/mlflow_tags.py
  pylint_plugins/unittest_assert_raises.py
  tests/entities/test_run_status.py
  tests/pipelines/test_ingest_step.py
  tests/pipelines/test_split_step.py
  tests/pipelines/test_train_step.py
  tests/pylint_plugins/test_unittest_assert_raises.py
  tests/spark/test_spark_model_export.py
  tests/store/artifact/test_s3_artifact_repo.py
  tests/store/db/test_utils.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/store/tracking/__init__.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/test_tracking.py
Labels: rn/none

#6516 Remove unnecessary comprehension
  mlflow/deployments/cli.py
  mlflow/lightgbm.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/runs.py
  pylintrc
  tests/lightgbm/test_lightgbm_autolog.py
  tests/models/test_evaluation.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/store/tracking/__init__.py
Labels: rn/none

#6508 Don't use mlflowdbfs if dbutils is unavailable
  mlflow/spark.py
  tests/spark/test_spark_model_export.py
Labels: rn/bug-fix, area/models

#6521 bug-fix to allow non-string column names (#6503)
  mlflow/models/evaluation/base.py
  tests/models/test_evaluation.py
Labels: rn/none, area/models

#6533 Add `use-set-literal` rule for better performace
  pylint_plugins/__init__.py
  pylint_plugins/set_checker.py
  pylint_plugins/tests/test_set_checker.py
Labels: rn/none

#6465 feat: Docker development scripts and readme
  CONTRIBUTING.rst
  dev/Dockerfile.test
  dev/Dockerfile.test.dockerignore
  dev/run-test-container.sh
Labels: rn/feature, area/build

#6495 Adding cd to run reproduce steps
  mlflow/server/js/src/experiment-tracking/components/RunView.js
Labels: rn/none, area/uiux, area/pipelines

#6541 Move prometheus client dependency to `extras`
  requirements/core-requirements.txt
  requirements/core-requirements.yaml
  setup.py
Labels: rn/breaking-change, area/server-infra

#6542 fix use-set-literal errors batch 1 (#mlflow-6535)
  mlflow/server/handlers.py
  mlflow/tracking/fluent.py
  mlflow/utils/autologging_utils/safety.py
  pylint_plugins/set_checker.py
Labels: rn/none

#6543 fix use-set-literal errors batch 2 (#mlflow-6535)
  pylint_plugins/set_checker.py
  tests/autologging/test_autologging_behaviors_unit.py
  tests/entities/test_run_info.py
  tests/entities/test_run_status.py
Labels: rn/none

#6524 Remove deprecated runs field from GetExperiment response
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
Labels: rn/breaking-change, area/tracking

#6534 Fix `use-set-literal` errors
  mlflow/utils/search_utils.py
  pylint_plugins/set_checker.py
  tests/entities/model_registry/test_model_version.py
  tests/entities/model_registry/test_registered_model.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/test_model_registry.py
Labels: rn/none

#6507 Discourage use of conda and recommend virtualenv
  docs/source/models.rst
  docs/source/projects.rst
  mlflow/environment_variables.py
  mlflow/utils/cli_args.py
  tests/models/test_cli.py
Labels: rn/none, area/models, area/projects

#6547 Remove run_uuid is not None check
  mlflow/entities/run_info.py
Labels: rn/none, area/tracking

#6550 Deprecate ListExperiments, ListRegisteredModels, ListRunInfos APIs
  mlflow/java/client/src/main/java/org/mlflow/api/proto/ModelRegistry.java
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/model_registry.proto
  mlflow/protos/model_registry_pb2.py
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: rn/documentation, area/model-registry, area/tracking

#6549 Use `set` instead of `{}` to fix `R` CI check
  mlflow/server/handlers.py
Labels: rn/none

#6552 Improve `deprecated` decorator
  mlflow/utils/annotations.py
  tests/utils/test_annotations.py
Labels: rn/none

#6540 Fix violating consider-using-set-comprehension pylint rule
  mlflow/pipelines/utils/metrics.py
  mlflow/store/model_registry/sqlalchemy_store.py
  pylintrc
  tests/entities/model_registry/test_model_version.py
  tests/entities/model_registry/test_registered_model.py
  tests/entities/test_run_data.py
  tests/pipelines/test_pipeline.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/store/tracking/__init__.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tensorflow/test_tensorflow2_autolog.py
  tests/tracking/test_model_registry.py
  tests/tracking/test_rest_tracking.py
  tests/tracking/test_tracking.py
  tests/utils/test_search_utils.py
Labels: rn/none

#6537 Deprecate duplicate artifact download APIs
  examples/mlflow_artifacts/example.py
  examples/pip_requirements/pip_requirements.py
  examples/shap/binary_classification.py
  examples/shap/multiclass_classification.py
  examples/shap/regression.py
  mlflow/artifacts/__init__.py
  mlflow/tracking/client.py
  tests/tracking/test_mlflow_artifacts.py
  tests/tracking/test_rest_tracking.py
Labels: rn/breaking-change, area/artifacts

#6557 Install conda in R development image
  mlflow/R/mlflow/.create-test-env.R
  mlflow/R/mlflow/Dockerfile.dev
Labels: rn/none

#6502 Enable `--serve-artifacts` by default
  docs/source/R-api.rst
  docs/source/_static/images/scenario_1.png
  docs/source/_static/images/scenario_2.png
  docs/source/_static/images/scenario_3.png
  docs/source/_static/images/scenario_4.png
  docs/source/_static/images/scenario_5.png
  docs/source/_static/images/scenario_6.png
  docs/source/tracking.rst
  examples/mlflow_artifacts/README.md
  examples/mlflow_artifacts/docker-compose.yml
  examples/mlflow_artifacts/example.py
  mlflow/R/mlflow/R/tracking-server.R
  mlflow/R/mlflow/man/mlflow_server.Rd
  mlflow/server/handlers.py
  mlflow/utils/cli_args.py
  mlflow/utils/server_cli_utils.py
  tests/test_cli.py
  tests/tracking/test_mlflow_artifacts.py
Labels: rn/feature, area/tracking

#6544 fix use-set-literal errors
  mlflow/azure/client.py
  mlflow/entities/lifecycle_stage.py
  mlflow/entities/run_status.py
  pylint_plugins/set_checker.py
Labels: rn/none

#6559 Removed unwanted `os.system` calls
  mlflow/models/container/__init__.py
  mlflow/models/docker_utils.py
Labels: rn/none

#6558 Fix CircleCI artifact URL in `build_doc_r` job
  .circleci/config.yml
Labels: language/r, rn/none

#6561 Add searchExperiments API to Java client, deprecate listExperiments
  mlflow/java/client/README.md
  mlflow/java/client/src/main/java/org/mlflow/tracking/ExperimentsPage.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowClient.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowHttpCaller.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowProtobufMapper.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/samples/QuickStartDriver.java
  mlflow/java/client/src/test/java/org/mlflow/tracking/MlflowClientTest.java
Labels: rn/feature, language/java, area/tracking

#6565 Pin `pmdarima` in diviner test
  .github/workflows/cross-version-tests.yml
  mlflow/ml-package-versions.yml
Labels: rn/none, area/models, enable-dev-tests

#6560 fix use-set-literal errors batch 3 (#mlflow-6535)
  tests/lightgbm/test_lightgbm_autolog.py
  tests/models/test_model_input_examples.py
  tests/projects/test_project_spec.py
Labels: rn/none

#6570 replaced all self.assertTrue with assert
  tests/entities/test_run_status.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#6569 [bug-fix] Removing the fixed width css for the experimentlist container
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.js
Labels: rn/bug-fix, area/tracking

#6563 Clarify ports in JS dev server instructions
  CONTRIBUTING.rst
Labels: area/docs, rn/none

#6457 Allow specifying mlflow command line args as env variables.
  mlflow/cli.py
  mlflow/utils/cli_args.py
Labels: rn/none, area/tracking

#6517 [ML-22889] Get artifact cli
  mlflow/pipelines/cli.py
  mlflow/pipelines/pipeline.py
  mlflow/pipelines/regression/v1/pipeline.py
  tests/pipelines/test_cli.py
Labels: rn/feature, area/pipelines

#6577 [Model Validation] Finishing touches and documentation
  docs/source/models.rst
  examples/evaluation/README.md
  examples/evaluation/evaluate_with_model_validation.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/validation.py
  tests/examples/test_examples.py
  tests/models/test_evaluation.py
  tests/models/test_validation.py
Labels: area/docs, rn/none, area/models

#6584 fix final batch of use-set-literal errors #6535
  pylint_plugins/set_checker.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/store/artifact/test_ftp_artifact_repo.py
  tests/utils/test_requirements_utils.py
  tests/xgboost/test_xgboost_autolog.py
Labels: rn/none

#6573 Update doc to clarify tf.keras should not be logged with mlflow.tensorflow
  mlflow/tensorflow/__init__.py
Labels: area/docs, rn/none

#6576 Add mlflow_search_experiments API to R client
  docs/source/R-api.rst
  mlflow/R/mlflow/NAMESPACE
  mlflow/R/mlflow/R/tracking-experiments.R
  mlflow/R/mlflow/document.R
  mlflow/R/mlflow/man/mlflow_search_experiments.Rd
  mlflow/R/mlflow/tests/testthat/test-tracking-experiments.R
Labels: language/r, rn/feature, area/tracking

#6578 [2.0] Add mlflow_search_experiments to R client
  docs/source/R-api.rst
  mlflow/R/mlflow/NAMESPACE
  mlflow/R/mlflow/R/tracking-experiments.R
  mlflow/R/mlflow/document.R
  mlflow/R/mlflow/man/mlflow_search_experiments.Rd
  mlflow/R/mlflow/tests/testthat/test-tracking-experiments.R
Labels: language/r, rn/feature, area/tracking

#6579 [2.0] Add searchExperiments API to Java client
  mlflow/java/client/README.md
  mlflow/java/client/src/main/java/org/mlflow/tracking/ExperimentsPage.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowClient.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowHttpCaller.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowProtobufMapper.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/samples/QuickStartDriver.java
  mlflow/java/client/src/test/java/org/mlflow/tracking/MlflowClientTest.java
Labels: rn/feature, language/java, area/tracking

#6526 Make URLs clickable in the MLflow Tracking UI
  mlflow/server/js/src/common/utils/Utils.js
  mlflow/server/js/src/common/utils/Utils.test.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.test.js
Labels: rn/feature, area/uiux

#6595 Removing actual code from DAG strings for MLP and just keeping user guide
  mlflow/pipelines/regression/v1/dag_help_strings.py
Labels: rn/none, area/pipelines

#6593 Add confs for metric prefix and metric dataset info to mlflow.evaluate(), rename accuracy to accuracy_score
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  tests/models/test_default_evaluator.py
Labels: rn/feature, area/models

#6582 [Model Validation] Land model validation feature
  docs/source/models.rst
  examples/evaluation/README.md
  examples/evaluation/evaluate_with_model_validation.py
  mlflow/models/__init__.py
  mlflow/models/evaluation/__init__.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/models/evaluation/validation.py
  mlflow/pyfunc/__init__.py
  tests/examples/test_examples.py
  tests/models/test_default_evaluator.py
  tests/models/test_evaluation.py
  tests/models/test_validation.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/dummy_evaluator.py
Labels: rn/feature, area/models

#6596 [ML-20702] increase version font size
  docs/theme/mlflow/static/css/custom.css
Labels: area/docs, rn/none

#6597 Changed the name Start Time to Created
  mlflow/server/js/src/experiment-tracking/components/ExperimentView.js
  mlflow/server/js/src/experiment-tracking/components/RunsTableColumnSelectionDropdown.test.js
  mlflow/server/js/src/experiment-tracking/constants.js
Labels: rn/none, area/uiux

#6574 feat[scoring_server]: add `/health` endpoint
  mlflow/pyfunc/scoring_server/__init__.py
Labels: rn/feature, area/scoring

#6614 Update start time col
  mlflow/server/js/src/i18n/default/en.json
Labels: rn/none, area/uiux

#6624 Add a script to update `CHANGELOG.md`
  dev/requirements.txt
  dev/update_changelog.py
Labels: rn/none, area/build

#6612 Improve styling of DAG and rearrange transform step node
  mlflow/pipelines/regression/v1/resources/pipeline_dag_template.html
Labels: rn/none, area/pipelines

#6632 Update documentation for model version `run_link` field
  mlflow/java/client/src/main/java/org/mlflow/api/proto/ModelRegistry.java
  mlflow/protos/model_registry.proto
Labels: area/docs, rn/documentation

#6621 Move data capture config argument to end of mlflow.sagemaker.deploy()
  mlflow/sagemaker/__init__.py
Labels: rn/feature, integrations/sagemaker

#6633 [ML-24659] adding using conf to yaml
  docs/source/pipelines.rst
  mlflow/pipelines/steps/train.py
  tests/pipelines/test_train_step.py
Labels: area/docs, rn/feature, area/pipelines

#6623 Used tuple instead a comma-separated string in pytest.mark.parametrize.
  tests/autologging/test_autologging_safety_unit.py
  tests/autologging/test_autologging_utils.py
  tests/db/test_schema.py
  tests/dev/test_set_matrix.py
  tests/examples/README.md
  tests/examples/test_examples.py
  tests/keras/test_keras_model_export.py
  tests/models/test_artifacts.py
  tests/models/test_default_evaluator.py
  tests/models/test_evaluation.py
  tests/pipelines/regression/v1/test_regression_pipeline.py
  tests/pipelines/test_register_step.py
  tests/pipelines/test_step_utils.py
  tests/pipelines/test_tracking_utils.py
  tests/projects/test_docker_projects.py
  tests/projects/test_project_spec.py
  tests/projects/test_projects.py
  tests/projects/test_utils.py
  tests/pyfunc/test_mlserver.py
  tests/pyfunc/test_scoring_server.py
  tests/sklearn/test_sklearn_autolog.py
  tests/store/artifact/test_artifact_repo.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/store/artifact/test_databricks_models_artifact_repo.py
  tests/store/artifact/test_dbfs_artifact_repo.py
  tests/store/artifact/test_dbfs_rest_artifact_repo.py
  tests/store/artifact/test_mlflow_artifact_repo.py
  tests/store/artifact/test_runs_artifact_repo.py
  tests/store/artifact/test_s3_artifact_repo.py
  tests/store/artifact/utils/test_model_utils.py
  tests/tracking/_tracking_service/test_tracking_service_client.py
  tests/tracking/fluent/test_fluent_autolog.py
  tests/tracking/request_header/test_databricks_request_header_provider.py
  tests/tracking/test_tracking.py
  tests/utils/test_arguments_utils.py
  tests/utils/test_databricks_utils.py
  tests/utils/test_proto_json_utils.py
  tests/utils/test_search_utils.py
  tests/utils/test_string_utils.py
  tests/utils/test_uri.py
Labels: rn/none, area/examples

#6551 Stabilize SearchExperiments API
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: rn/documentation, area/tracking

#6639 Fix command to trigger auto-formatting
  .github/workflows/autoformat.yml
  dev/lint.sh
Labels: rn/none, area/build

#6640 [branch-2.0] Set `pyfunc.spark_udf` `env_manager` argument default value to be ``local``
  mlflow/pyfunc/__init__.py
Labels: rn/breaking-change, area/scoring

#6642 Support argument for local_tmpdir when loading spark model.
  mlflow/spark.py
Labels: area/docs, rn/none, area/artifacts

#6475 adding load_text, load_image, load_dict to fluent.py
  mlflow/artifacts/__init__.py
  tests/artifacts/test_artifacts.py
Labels: rn/feature, area/tracking

#6630 update DFS_TMP in mlflow.spark to accept environment variable
  mlflow/environment_variables.py
  mlflow/spark.py
  tests/spark/test_spark_model_export.py
Labels: rn/none

#6525 [ML-24419] Updated artifact downloads to pass in http headers
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/utils/file_utils.py
  tests/store/artifact/test_databricks_models_artifact_repo.py
Labels: rn/none, area/artifacts

#6648 update pmdarima dependency versions for CI
  mlflow/ml-package-versions.yml
Labels: rn/none, area/models

#6641 Make run & experiment deletion / restoration idempotent
  mlflow/entities/run_info.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/bug-fix, area/tracking

#6631 Improve flexibility of PyFuncModel prediction
  mlflow/pyfunc/__init__.py
  mlflow/sklearn/__init__.py
  tests/sklearn/test_sklearn_model_export.py
Labels: rn/feature, area/models

#6629 Add a script to update MLflow package versions
  dev/update_mlflow_versions.py
Labels: rn/none

#6653 Remove unnecessary if condition in autoformat workflow
  .github/workflows/autoformat.js
  .github/workflows/autoformat.yml
Labels: rn/none, area/build

#6655 Fix `env_manager` doc in `mlflow.projects.run`
  mlflow/projects/__init__.py
Labels: rn/none, area/projects

#6644 Define all pylint-plugin errors in one file
  pylint_plugins/errors.py
  pylint_plugins/pytest_raises_checker/__init__.py
  pylint_plugins/set_checker.py
  pylint_plugins/tests/test_pytest_raises_checker.py
  pylint_plugins/tests/test_set_checker.py
  pylint_plugins/unittest_assert_raises.py
Labels: rn/none

#6656 Use `ml-package-versions.yml` on base branch in cross version tests
  .github/workflows/cross-version-tests.yml
Labels: rn/none, area/build

#6654 Remove `use_conda` argument in `mlflow.projects.run`
  examples/hyperparam/search_hyperopt.py
  mlflow/projects/__init__.py
  tests/projects/test_projects.py
Labels: rn/breaking-change, area/projects

#6661 Fix bug in MLP evaluation step in which list is accessed as if it were a dictionary
  mlflow/pipelines/steps/evaluate.py
Labels: rn/none, area/pipelines
