Repository mlflow/mlflow, pull requests merged in 2022-03, with the labels that each got.

#5428 Switched rest_utils to use cached Requests.Session objects
  mlflow/utils/rest_utils.py
Labels: rn/none

#5435 Show python version mismatch by default when loading model.
  mlflow/pyfunc/__init__.py
Labels: rn/none, area/tracking

#5437 Pin pip in conda.yaml
  mlflow/utils/environment.py
  tests/utils/test_environment.py
Labels: rn/none, area/models

#5442 Fix Jobs experiment creation source type tag
  mlflow/tracking/fluent.py
Labels: rn/none, integrations/databricks

#5445 Use python 3.8 when running tests for dev version of scikit-learn
  .github/workflows/cross-version-tests.yml
Labels: rn/none

#5446 Use `manylinux2014_x86_64` when building a wheel for dev version of onnx
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#5443 Create index on `run_uuid` columns for PostgreSQL to improve SQL operations
  mlflow/store/db_migrations/versions/bd07f7e963c5_create_index_on_run_uuid.py
  tests/store/tracking/test_sqlalchemy_store_schema.py
Labels: rn/bug-fix

#5452 Fix cross-version test of dev scikit-learn
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/none, enable-dev-tests

#5447 Improve infer model type method for default evaluator
  mlflow/models/evaluation/default_evaluator.py
  tests/models/test_default_evaluator.py
Labels: rn/none, area/tracking

#5454 Refactor fastai example
  examples/fastai/README.md
  examples/fastai/train.py
Labels: rn/none

#5453 Avoid setting `MLFLOW_TRACKING_URI` in `test_examples.py`
  tests/examples/test_examples.py
Labels: rn/none

#5438 Add ENV variables to control GCS upload/download chunk size and timeouts
  docs/source/tracking.rst
  mlflow/store/artifact/gcs_artifact_repo.py
  tests/store/artifact/test_gcs_artifact_repo.py
Labels: rn/bug-fix, area/artifacts

#5463 Fix mlflow-R for passing CRAN checks
  mlflow/R/mlflow/R/install.R
  mlflow/R/mlflow/R/python.R
Labels: language/r, rn/none, area/build

#5465 [MASTER] Fix mlflow-R for passing CRAN checks
  mlflow/R/mlflow/R/install.R
  mlflow/R/mlflow/R/python.R
Labels: language/r, rn/none, area/build

#5459 Add an info log when xgboost autologging metric names are sanitized
  mlflow/xgboost/_autolog.py
  tests/xgboost/test_xgboost_autolog.py
Labels: rn/none, area/tracking

#5455 Convert `CHANGELOG.rst` to markdown
  CHANGELOG.md
  CONTRIBUTING.rst
Labels: rn/none

#5468 Use `<=` instead of `==` when logging pip requirement on conda.yaml
  mlflow/shap.py
  mlflow/utils/environment.py
  mlflow/utils/requirements_utils.py
  tests/utils/test_environment.py
Labels: rn/none

#5286 Remove deprecated numpy type aliases
  examples/flower_classifier/image_pyfunc.py
  mlflow/pyfunc/__init__.py
  mlflow/pyspark/ml/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/types/schema.py
  mlflow/types/utils.py
  mlflow/utils/proto_json_utils.py
  pytest.ini
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/pyfunc/test_scoring_server.py
  tests/pyfunc/test_spark.py
  tests/sklearn/test_sklearn_autolog.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
  tests/statsmodels/model_fixtures.py
  tests/types/test_schema.py
Labels: rn/bug-fix

#5466 feat: Support spark transformers tracking with mlflow
  mlflow/spark.py
  tests/spark/test_spark_model_export.py
Labels: rn/feature, area/models

#5448 Add `code_paths` parameter to all flavors
  hooks/pre-commit
  mlflow/catboost.py
  mlflow/fastai/__init__.py
  mlflow/gluon/__init__.py
  mlflow/h2o.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/onnx.py
  mlflow/paddle/__init__.py
  mlflow/pmdarima.py
  mlflow/prophet.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/utils.py
  mlflow/pytorch/__init__.py
  mlflow/shap.py
  mlflow/sklearn/__init__.py
  mlflow/spacy.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/tensorflow/__init__.py
  mlflow/utils/model_utils.py
  mlflow/xgboost/__init__.py
  tests/catboost/test_catboost_model_export.py
  tests/fastai/test_fastai_model_export.py
  tests/gluon/test_gluon_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/helper_functions.py
  tests/keras/test_keras_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/onnx/test_onnx_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/pmdarima/test_pmdarima_model_export.py
  tests/prophet/test_prophet_model_export.py
  tests/pytorch/test_pytorch_model_export.py
  tests/shap/test_log.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spacy/test_spacy_model_export.py
  tests/spark/test_spark_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/tensorflow/test_tensorflow2_model_export.py
  tests/utils/test_model_utils.py
  tests/utils/test_resources/dummy_module.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/feature, area/models

#5461 Adds input example and model signature to autologging for tf.keras for certain x types on tf.keras.Model.fit
  mlflow/tensorflow/__init__.py
  mlflow/tensorflow/_autolog.py
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/feature, area/models

#5309 Enable plugin approach to enable default experiments framework
  mlflow/tracking/default_experiment/__init__.py
  mlflow/tracking/default_experiment/abstract_context.py
  mlflow/tracking/default_experiment/databricks_job_experiment_provider.py
  mlflow/tracking/default_experiment/databricks_notebook_experiment_provider.py
  mlflow/tracking/default_experiment/registry.py
  mlflow/tracking/fluent.py
  mlflow/utils/mlflow_tags.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/default_experiment_provider.py
  tests/resources/mlflow-test-plugin/setup.py
  tests/tracking/default_experiment/__init__.py
  tests/tracking/default_experiment/test_databricks_job_experiment_provider.py
  tests/tracking/default_experiment/test_databricks_notebook_experiment_provider.py
  tests/tracking/default_experiment/test_registry.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/none, area/tracking

#5485 Pin `torch` to `< 1.11.0` when testing older versions of `pytorch-lightning`
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#5488 Add `setup-pyenv` action
  .github/actions/setup-pyenv/action.yml
  .github/workflows/master.yml
Labels: rn/none

#5405 [Custom Metrics] Artifact type detection and logging
  docs/source/models.rst
  examples/evaluation/README.md
  examples/evaluation/evaluate_with_custom_metrics.py
  examples/evaluation/evaluate_with_custom_metrics_comprehensive.py
  mlflow/models/evaluation/artifacts.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  tests/examples/test_examples.py
  tests/models/test_artifacts.py
  tests/models/test_default_evaluator.py
Labels: rn/feature, area/tracking

#5495 Fix `tracking_uri_mock` to create `mlruns.sqlite` instead `mlruns`
  tests/conftest.py
Labels: rn/none

#5483 fix: func _parse_mlflow_gcs_vars
  docs/source/tracking.rst
  mlflow/store/artifact/gcs_artifact_repo.py
Labels: rn/bug-fix, area/artifacts

#5464 Use `Dockerfile.r-devel` to run CRAN submission check using R-devel
  mlflow/R/mlflow/.Rbuildignore
  mlflow/R/mlflow/Dockerfile.r-devel
  mlflow/R/mlflow/build-package.sh
Labels: rn/none, area/build

#5476 Fixed EvaluationResult not saving or loading artifacts with proper file names
  mlflow/models/evaluation/base.py
  tests/models/test_evaluation.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/dummy_evaluator.py
Labels: rn/bug-fix, area/artifacts

#5509 Fix type hint for set_experiment
  mlflow/tracking/fluent.py
Labels: rn/none, area/tracking

#5497 Support logging PyTorch metrics on training batch steps
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_pytorch_autolog.py
  tests/pytorch/iris.py
  tests/pytorch/test_pytorch_autolog.py
Labels: rn/feature, area/tracking

#5508 fix for MSSQL paginated list experiments on behalf of @HaraldVanWoerkom
  mlflow/store/tracking/sqlalchemy_store.py
  tests/db/run_checks.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/bug-fix, area/tracking, area/server-infra

#5505 Clean up conda environment when `pip install` fails during `conda create`
  mlflow/utils/conda.py
  tests/projects/test_projects.py
Labels: rn/none

#5500 Upgraded setup-python actions from v2 to v3
  .github/actions/setup-python/action.yml
  .github/workflows/autoformat.yml
  .github/workflows/cross-version-tests.yml
  .github/workflows/examples.yml
  .github/workflows/labeling.yml
  .github/workflows/master.yml
  .github/workflows/notify-dco-failure.yml
  .github/workflows/release-note-category.yml
  .github/workflows/test-package-build.yml
Labels: rn/none, area/artifacts, area/build

#5511 Revert "Support logging PyTorch metrics on training batch steps"
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_pytorch_autolog.py
  tests/pytorch/iris.py
  tests/pytorch/test_pytorch_autolog.py
Labels: rn/none

#5504 Add version to header and use version specific documentation links
  mlflow/server/js/src/common/constants.js
  mlflow/server/js/src/experiment-tracking/components/App.css
  mlflow/server/js/src/experiment-tracking/components/App.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentView.js
  mlflow/server/js/src/experiment-tracking/components/NoExperimentView.js
Labels: rn/feature, area/uiux

#5516 Support logging PyTorch metrics on training batch steps with autolog
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_pytorch_autolog.py
  tests/pytorch/iris.py
  tests/pytorch/test_pytorch_autolog.py
Labels: rn/feature, area/tracking, enable-dev-tests

#5491 [docs] Deploy a python_function model on Microsoft Azure ML - guidance
  docs/source/models.rst
Labels: area/docs, rn/documentation, integrations/azure

#5520 refactor: Import tensorflow.estimator explicitly
  examples/tensorflow/tf2/train_predict_2.py
  tests/tensorflow/test_tensorflow2_autolog.py
  tests/tensorflow/test_tensorflow2_model_export.py
Labels: rn/none, area/examples

#5515 Implement issue-5501 - add mlflow_version info to logged model
  mlflow/models/model.py
  tests/models/test_model.py
Labels: rn/feature, area/models

#5513 Refactor files in `tests/db` to allow running tests in repository root
  .github/workflows/master.yml
  CONTRIBUTING.rst
  setup.py
  tests/db/.dockerignore
  tests/db/.gitignore
  tests/db/Dockerfile
  tests/db/Dockerfile.mssql
  tests/db/README.md
  tests/db/build_wheel.sh
  tests/db/compose.sh
  tests/db/compose.yml
  tests/db/conftest.py
  tests/db/entrypoint.sh
  tests/db/init-mssql-db.sh
  tests/db/run_checks.py
  tests/db/schemas/postgresql.sql
  tests/db/test_schema.py
  tests/db/test_tracking_operations.py
  tests/db/update_schemas.sh
Labels: rn/none, area/build

#5502 Append user agent added by request_header_provider to default user agent
  mlflow/tracking/request_header/default_request_header_provider.py
  mlflow/tracking/request_header/registry.py
  mlflow/utils/rest_utils.py
  tests/projects/test_databricks.py
  tests/store/tracking/test_rest_store.py
  tests/tracking/request_header/test_default_request_header_provider.py
  tests/tracking/request_header/test_registry.py
  tests/utils/test_rest_utils.py
Labels: rn/none, area/tracking

#5522 Use `split` pandas orientation for sagemaker deployment predict() API
  mlflow/sagemaker/__init__.py
Labels: rn/bug-fix, area/scoring

#5187 Fix issue #2804 - Set run name in MLProject execution
  mlflow/cli.py
  mlflow/projects/__init__.py
Labels: rn/bug-fix, area/projects

#5487 Restoring virtual python environment for mlflow pyfunc spark_udf
  mlflow/models/flavor_backend.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/backend.py
  mlflow/pyfunc/scoring_server/client.py
  mlflow/pyfunc/spark_model_cache.py
  mlflow/rfunc/backend.py
  mlflow/utils/__init__.py
  mlflow/utils/_spark_utils.py
  mlflow/utils/nfs_on_spark.py
  tests/pyfunc/test_scoring_server.py
  tests/pyfunc/test_spark.py
Labels: rn/feature, area/scoring

#5538 Set timezone to UTC in windows
  mlflow/server/js/scripts/global-setup.js
Labels: rn/none

#5532 Fix doc build CI
  requirements/doc-requirements.txt
Labels: rn/none, area/build

#5481 feat: pyspark autologging enhancement
  mlflow/pyspark/ml/__init__.py
  mlflow/spark.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
Labels: rn/feature, area/tracking

#5547 Fix invalid Anaconda URLs
  mlflow/R/mlflow/README.Rmd
  mlflow/R/mlflow/README.md
Labels: rn/none

#5548 Use latest version of black fo fix lint check
  examples/statsmodels/train.py
  mlflow/pytorch/_pytorch_autolog.py
  mlflow/store/db/utils.py
  requirements/lint-requirements.txt
  tests/examples/test_examples.py
  tests/generate_ui_test_data.py
  tests/pylint_plugins/utils.py
  tests/statsmodels/model_fixtures.py
Labels: rn/none, area/build

#5552 Removing the mention of tf1.
  examples/tensorflow/README.md
Labels: area/examples

#5540 Run `test_sqlalchemy_store.py` against PostgreSQL, MySQL, and MSSQL
  .github/workflows/master.yml
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/utils/search_utils.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: area/windows, rn/none

#5557 Replace `universal_newlines` with `text` in `subprocess.Popen`
  mlflow/models/docker_utils.py
  mlflow/projects/backend/local.py
  mlflow/sagemaker/__init__.py
  mlflow/utils/process.py
  tests/helper_functions.py
  tests/models/test_cli.py
Labels: rn/none

#5559 Fix #5551 - PyTorch LightningDeprecationWarning ModelSummary and get_gpu_memory_map
  mlflow/pytorch/_pytorch_autolog.py
Labels: rn/none, area/artifacts, enable-dev-tests

#5560 Pin `click` to fix spacy tests
  mlflow/ml-package-versions.yml
  tests/spacy/test_spacy_model_export.py
Labels: rn/none, area/build, enable-dev-tests

#5449 Add default experiment ID provider for repo notebooks
  mlflow/tracking/default_experiment/databricks_notebook_experiment_provider.py
  mlflow/tracking/default_experiment/registry.py
  mlflow/utils/databricks_utils.py
  tests/tracking/default_experiment/test_databricks_notebook_experiment_provider.py
  tests/utils/test_databricks_utils.py
Labels: rn/none, integrations/databricks

#5556 Add custom pylint rule to detect print functions
  mlflow/cli.py
  mlflow/data.py
  mlflow/experiments.py
  mlflow/models/container/__init__.py
  mlflow/projects/__init__.py
  mlflow/runs.py
  mlflow/sagemaker/__init__.py
  mlflow/sagemaker/cli.py
  mlflow/store/artifact/cli.py
  mlflow/tracking/_tracking_service/utils.py
  mlflow/tracking/client.py
  mlflow/utils/logging_utils.py
  pylint_plugins/__init__.py
  pylint_plugins/print_function.py
  tests/pylint_plugins/test_print_function.py
  tests/pylint_plugins/test_pytest_raises_without_match.py
  tests/pylint_plugins/utils.py
Labels: rn/none

#5562 turn sphinx nitpicky mode on and force a failure
  docs/Makefile
  docs/source/conf.py
Labels: rn/none, area/build

#5543 Make mlflow.pyfunc.spark_udf driver side raise exception contains conda env create command stdout/stderr output.
  mlflow/models/flavor_backend.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/backend.py
  mlflow/server/__init__.py
  mlflow/utils/conda.py
  mlflow/utils/process.py
  tests/projects/test_projects.py
Labels: rn/none, area/scoring

#5290 Replace `mlflow.pyfunc.load_pyfunc` with `mlflow.pyfunc.load_model`
  examples/flower_classifier/score_images_spark.py
  mlflow/catboost.py
  mlflow/fastai/__init__.py
  mlflow/gluon/__init__.py
  mlflow/h2o.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/models/container/scoring_server/wsgi.py
  mlflow/onnx.py
  mlflow/paddle/__init__.py
  mlflow/prophet.py
  mlflow/pyfunc/model.py
  mlflow/pyfunc/spark_model_cache.py
  mlflow/pytorch/__init__.py
  mlflow/shap.py
  mlflow/sklearn/__init__.py
  mlflow/spacy.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/tensorflow/__init__.py
  mlflow/xgboost/__init__.py
  tests/azureml/test_deploy.py
  tests/azureml/test_image_creation.py
  tests/catboost/test_catboost_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/onnx/test_onnx_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/prophet/test_prophet_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/pyfunc/test_spark.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spacy/test_spacy_model_export.py
  tests/spark/test_spark_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none

#5568 Fix pytest fixtures that are unnecessarily session-scoped
  tests/fastai/test_fastai_autolog.py
  tests/fastai/test_fastai_model_export.py
  tests/lightgbm/test_lightgbm_autolog.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/mleap/test_mleap_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/projects/utils.py
  tests/prophet/test_prophet_model_export.py
  tests/pyfunc/test_scoring_server.py
  tests/pyfunc/test_spark.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spark/test_spark_model_export.py
  tests/utils/test_model_utils.py
  tests/xgboost/test_xgboost_autolog.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none

#5554 Add conda disclaimer to docs
  docs/source/models.rst
Labels: area/docs, rn/none
