Repository mlflow/mlflow, pull requests merged in 2022-01, with the labels that each got.

#5212 Add a Python API to load model input examples
  mlflow/models/model.py
  mlflow/models/utils.py
  tests/models/test_model.py
Labels: rn/feature, area/models

#5189 Propagate API response error to client for list_artifacts
  mlflow/store/artifact/databricks_models_artifact_repo.py
  tests/store/artifact/test_databricks_models_artifact_repo.py
Labels: rn/breaking-change, area/model-registry

#5217 Remove mleap commands in `.create-test-env.R`
  .github/workflows/master.yml
  mlflow/R/mlflow/.create-test-env.R
  mlflow/R/mlflow/.spark-version
Labels: rn/none

#5226 Use python 3.7 in R
  mlflow/R/mlflow/.create-test-env.R
Labels: rn/none

#5219 Remove unused `xml2` in R
  .github/workflows/master.yml
  mlflow/R/mlflow/.run-tests.R
  mlflow/R/mlflow/DESCRIPTION
Labels: rn/none

#5220 Use `https://packagemanager.rstudio.com` to install R packages faster
  .github/workflows/master.yml
  mlflow/R/mlflow/.Rprofile
Labels: rn/none

#5229 Upgrade nodejs to 14.x (recommended) since 10.x is EOL
  .github/workflows/autoformat.yml
  .github/workflows/master.yml
  Dockerfile
Labels: rn/none, area/build

#5082 Install python dependencies with a single `pip install`
  dev/install-common-deps.sh
Labels: rn/none

#5235 Use python 3.8 for when running tests for dev version of `statsmodels`
  .github/actions/setup-python/action.yml
  .github/workflows/cross-version-tests.yml
  mlflow/statsmodels.py
Labels: rn/none, area/build, enable-dev-tests

#5234 Stop using Java8 because we no longer support spark < 3.0
  .github/workflows/cross-version-tests.yml
  .github/workflows/master.yml
  mlflow/mleap.py
  mlflow/spark.py
  tests/mleap/test_mleap_model_export.py
  tests/spark/test_spark_model_export.py
Labels: rn/none, enable-dev-tests

#5232 Clean up CI job for R
  .github/workflows/master.yml
  mlflow/R/mlflow/.build-package.R
  mlflow/R/mlflow/.create-test-env.R
  mlflow/R/mlflow/.run-tests.R
  mlflow/R/mlflow/tests/testthat.R
  mlflow/R/mlflow/tests/testthat/test-model-h2o.R
  mlflow/R/mlflow/tests/testthat/test-model-xgboost.R
Labels: rn/none

#5239 Remove commented out step in r job
  .github/workflows/master.yml
Labels: rn/none

#5240 Remove inheritance from `object`
  examples/flower_classifier/image_pyfunc.py
  mlflow/entities/_mlflow_object.py
  mlflow/entities/lifecycle_stage.py
  mlflow/entities/model_registry/model_version_status.py
  mlflow/entities/run_status.py
  mlflow/entities/source_type.py
  mlflow/entities/view_type.py
  mlflow/models/flavor_backend.py
  mlflow/models/model.py
  mlflow/models/signature.py
  mlflow/models/utils.py
  mlflow/paddle/__init__.py
  mlflow/projects/_project_spec.py
  mlflow/projects/databricks.py
  mlflow/projects/submitted_run.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
  mlflow/pyfunc/spark_model_cache.py
  mlflow/pytorch/__init__.py
  mlflow/spark.py
  mlflow/tensorflow/__init__.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  mlflow/tracking/context/abstract_context.py
  mlflow/tracking/context/registry.py
  mlflow/tracking/request_header/abstract_request_header_provider.py
  mlflow/tracking/request_header/registry.py
  mlflow/types/schema.py
  mlflow/types/utils.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/file_utils.py
  mlflow/utils/gorilla.py
  mlflow/utils/rest_utils.py
  mlflow/utils/search_utils.py
  tests/helper_functions.py
  tests/keras/test_keras_model_export.py
  tests/models/test_model.py
  tests/projects/test_projects.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/pyfunc/test_spark.py
  tests/store/artifact/test_azure_blob_artifact_repo.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/store/artifact/test_databricks_models_artifact_repo.py
  tests/store/artifact/test_dbfs_fuse_artifact_repo.py
  tests/store/artifact/test_dbfs_rest_artifact_repo.py
  tests/store/tracking/__init__.py
  tests/store/tracking/test_rest_store.py
  tests/test_exceptions.py
  tests/tracking/context/test_registry.py
  tests/tracking/request_header/test_registry.py
Labels: rn/none

#5243 Fix concurrency group value to avoid cancelling runs on push to master branch
  .github/workflows/cross-version-tests.yml
  .github/workflows/examples.yml
  .github/workflows/master.yml
  .github/workflows/release-note-category.yml
  .github/workflows/test-package-build.yml
Labels: rn/none

#5092 Evaluation Default evaluator
  mlflow/models/evaluation/artifacts.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/models/evaluation/evaluator_registry.py
  mlflow/models/evaluation/lift_curve.py
  mlflow/models/utils.py
  mlflow/utils/string_utils.py
  requirements/small-requirements.txt
  tests/models/test_default_evaluator.py
  tests/models/test_evaluation.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/dummy_evaluator.py
Labels: rn/feature, area/tracking

#5027 Support specifying 'latest' in model URI to get the latest version of a model regardless of the stage
  mlflow/java/client/src/test/java/org/mlflow/tracking/ModelRegistryMlflowClientTest.java
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/store/artifact/models_artifact_repo.py
  mlflow/store/artifact/utils/models.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/rest_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  tests/store/artifact/utils/test_model_utils.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/tracking/test_model_registry.py
Labels: rn/feature, area/model-registry, area/sqlalchemy

#5248 Print table schema in DB initialization test
  .github/workflows/master.yml
  tests/db/.dockerignore
  tests/db/.gitignore
  tests/db/Dockerfile
  tests/db/Dockerfile.mssql
  tests/db/docker-compose.yml
  tests/db/init-mssql-db.sh
  tests/db/init-mssql-db.sql
  tests/db/log.py
  tests/db/run_checks.py
Labels: rn/none

#5205 Renamed sqlalchemy_store in test plugin to fix file reference
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/sqlalchemy_store.py
Labels: rn/none

#5255 Pin setuptools to fix pytorch example failures
  examples/pytorch/BertNewsClassification/conda.yaml
  examples/pytorch/IterativePruning/conda.yaml
  examples/pytorch/MNIST/conda.yaml
Labels: rn/none

#5230 Return Model from log_model
  docs/source/python_api/mlflow.models.rst
  mlflow/catboost.py
  mlflow/fastai/__init__.py
  mlflow/gluon/__init__.py
  mlflow/h2o.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/mleap.py
  mlflow/models/model.py
  mlflow/onnx.py
  mlflow/paddle/__init__.py
  mlflow/prophet.py
  mlflow/pyfunc/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/spacy.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/tensorflow/__init__.py
  mlflow/xgboost/__init__.py
  tests/catboost/test_catboost_model_export.py
  tests/fastai/test_fastai_model_export.py
  tests/gluon/test_gluon_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/keras/test_keras_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/mleap/test_mleap_model_export.py
  tests/models/test_model.py
  tests/onnx/test_onnx_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/prophet/test_prophet_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spacy/test_spacy_model_export.py
  tests/spark/test_spark_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/tensorflow/test_tensorflow2_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none, area/models

#5249 Unpin alembic
  .github/workflows/master.yml
  mlflow/store/db_migrations/versions/0a8213491aaa_drop_duplicate_killed_constraint.py
  mlflow/store/db_migrations/versions/cfd24bdc0731_update_run_status_constraint_with_killed.py
  setup.py
  tests/db/Dockerfile
  tests/db/Dockerfile.mssql
  tests/db/build_wheel.sh
  tests/db/docker-compose.yml
  tests/db/run_checks.py
Labels: rn/none

#5244 Explain why we run tests against dev versions
  .github/workflows/cross-version-testing.md
Labels: rn/none

#5256 Improve evaluation api
  docs/source/python_api/mlflow.models.evaluation.base.rst
  docs/source/python_api/mlflow.models.evaluation.rst
  mlflow/models/__init__.py
  mlflow/models/evaluation/__init__.py
  mlflow/models/evaluation/artifacts.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  tests/models/test_default_evaluator.py
  tests/models/test_evaluation.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/dummy_evaluator.py
Labels: rn/breaking-change, area/tracking

#5264 Dump table schemas and make CI fail when they change
  .github/workflows/master.yml
  CONTRIBUTING.rst
  tests/db/.gitignore
  tests/db/docker-compose.yml
  tests/db/run_checks.py
  tests/db/schemas/mssql.sql
  tests/db/schemas/mysql.sql
  tests/db/schemas/postgres.sql
  tests/db/schemas/sqlite.sql
  tests/db/update_schemas.sh
Labels: rn/none

#5186 Evaluate Api examples
  examples/evaluation/README.md
  examples/evaluation/evaluate_on_binary_classifier.py
  examples/evaluation/evaluate_on_multiclass_classifier.py
  examples/evaluation/evaluate_on_regressor.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/lift_curve.py
Labels: rn/none, area/examples

#5200 Autologging functionality for scikit-learn integration with LightGBM (Part 2)
  examples/lightgbm/README.md
  examples/lightgbm/lightgbm_native/MLproject
  examples/lightgbm/lightgbm_native/README.md
  examples/lightgbm/lightgbm_native/conda.yaml
  examples/lightgbm/lightgbm_native/train.py
  examples/lightgbm/lightgbm_sklearn/MLproject
  examples/lightgbm/lightgbm_sklearn/README.md
  examples/lightgbm/lightgbm_sklearn/conda.yaml
  examples/lightgbm/lightgbm_sklearn/train.py
  examples/lightgbm/lightgbm_sklearn/utils.py
  mlflow/lightgbm.py
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
  tests/autologging/test_autologging_behaviors_integration.py
  tests/examples/test_examples.py
  tests/lightgbm/test_lightgbm_autolog.py
Labels: rn/documentation, area/examples, area/tracking

#5271 Fix typo in lightgbm example README
  examples/lightgbm/README.md
  examples/lightgbm/lightgbm_native/README.md
Labels: rn/none

#5272 Add Model Evaluation docs to MLflow Models section and make small API doc improvements
  docs/source/_static/images/model_evaluation_feature_importance.png
  docs/source/_static/images/model_evaluation_metrics.png
  docs/source/models.rst
  mlflow/models/evaluation/base.py
Labels: area/docs, rn/none

#5273 Improve confusion matrix plot
  mlflow/models/evaluation/default_evaluator.py
  mlflow/sklearn/utils.py
Labels: rn/bug-fix, area/tracking

#5275 Use `len(classes_)` instead of `len(set(y_true))`
  mlflow/sklearn/utils.py
Labels: rn/none

#5284 Remove GPyOpt example
  examples/hyperparam/MLproject
  examples/hyperparam/README.rst
  examples/hyperparam/conda.yaml
  examples/hyperparam/search_gpyopt.py
  tests/examples/test_examples.py
Labels: rn/none

#5268 Replace `load_boston` with `load_diabetes`
  examples/paddle/train_low_level_api.py
  examples/shap/binary_classification.py
  examples/shap/explainer_logging.py
  examples/shap/multiclass_classification.py
  examples/shap/regression.py
  examples/shap/utils.py
  mlflow/paddle/__init__.py
  mlflow/shap.py
  tests/autologging/test_autologging_utils.py
  tests/paddle/test_paddle_model_export.py
  tests/shap/test_log.py
  tests/shap/test_shap.py
Labels: rn/none

#5283 Drop support for python 3.6
  .circleci/config.yml
  .github/actions/setup-python/action.yml
  .github/workflows/autoformat.yml
  .github/workflows/cross-version-tests.yml
  .github/workflows/examples.yml
  .github/workflows/master.yml
  CONTRIBUTING.rst
  Dockerfile
  examples/h2o/conda.yaml
  examples/hyperparam/conda.yaml
  examples/hyperparam/train.py
  examples/lightgbm/lightgbm_native/conda.yaml
  examples/lightgbm/lightgbm_sklearn/conda.yaml
  examples/mlflow_artifacts/Dockerfile
  examples/mlflow_artifacts/Dockerfile.dev
  examples/multistep_workflow/conda.yaml
  examples/paddle/conda.yaml
  examples/pytorch/conda.yaml
  examples/sklearn_elasticnet_diabetes/linux/conda.yaml
  examples/sklearn_elasticnet_diabetes/linux/train_diabetes.py
  examples/sklearn_elasticnet_diabetes/osx/conda.yaml
  examples/sklearn_elasticnet_diabetes/osx/train_diabetes.py
  examples/sklearn_logistic_regression/conda.yaml
  examples/spacy/conda.yaml
  examples/statsmodels/conda.yaml
  examples/tensorflow/tf2/conda.yaml
  examples/xgboost/xgboost_native/conda.yaml
  mlflow/__init__.py
  setup.py
  tests/db/Dockerfile
  tests/db/Dockerfile.mssql
  tests/resources/example_docker_project/Dockerfile
  tests/resources/example_project/conda.yaml
Labels: rn/breaking-change

#5289 Remove deprecated `mlflow.types.schema.columns`
  mlflow/types/schema.py
Labels: rn/breaking-change

#5236 Model creation timestamp for log model in R
  mlflow/R/mlflow/R/model.R
  mlflow/R/mlflow/tests/testthat/test-model.R
Labels: language/r, rn/none, area/tracking

#5267 Create job experiment if the start_run source is a job
  mlflow/tracking/fluent.py
  mlflow/utils/databricks_utils.py
  mlflow/utils/mlflow_tags.py
  tests/tracking/fluent/test_fluent.py
  tests/utils/test_databricks_utils.py
Labels: rn/feature, area/tracking, integrations/databricks

#5288 Remove deprecated `mlflow.data.download_uri`
  mlflow/data.py
  tests/data/test_data.py
Labels: rn/breaking-change

#5287 Remove deprecated methods/properties in `mlflow.types.schema`
  mlflow/types/schema.py
  mlflow/types/utils.py
  tests/types/test_schema.py
Labels: rn/breaking-change

#5299 Fix loading a spark model on databricks
  mlflow/spark.py
Labels: rn/bug-fix, integrations/databricks

#5305 Fix lint issues
  mlflow/models/evaluation/base.py
  tests/utils/test_databricks_utils.py
Labels: rn/none, area/build

#5304 Remove unused num_examples var from model eval example
  docs/source/models.rst
Labels: area/docs, rn/none

#5313 Run `apt-get update` before installing `libopenblas-dev`
  .github/workflows/master.yml
  mlflow/ml-package-versions.yml
Labels: rn/none

#5315 Fix spark ML integration test failure
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
Labels: rn/none, area/tracking

#5312 Fix the bug of stages in models URI being case-sensitive
  mlflow/store/artifact/utils/models.py
  tests/store/artifact/utils/test_model_utils.py
  tests/store/model_registry/test_sqlalchemy_store.py
Labels: rn/bug-fix, area/model-registry, area/sqlalchemy

#5321 Refresh R cache
  .github/workflows/master.yml
Labels: rn/none

#5307 Update UI
  .github/workflows/autoformat.yml
  .github/workflows/master.yml
  .github/workflows/test-package-build.yml
  mlflow/server/js/.env
  mlflow/server/js/.gitignore
  mlflow/server/js/.yarnrc.yml
  mlflow/server/js/README.md
  mlflow/server/js/package-lock.json
  mlflow/server/js/package.json
  mlflow/server/js/src/common/components/RequestStateWrapper.js
  mlflow/server/js/src/common/components/RequestStateWrapper.test.js
  mlflow/server/js/src/common/utils/Utils.js
  mlflow/server/js/src/common/utils/Utils.test.js
  mlflow/server/js/src/experiment-tracking/components/App.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.css
  mlflow/server/js/src/experiment-tracking/components/ExperimentPage.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentPage.test.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js
  mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactLoggedModelView.js
  mlflow/server/js/src/experiment-tracking/components/modals/CreateExperimentModal.test.js
  mlflow/server/js/src/experiment-tracking/constants.js
  mlflow/server/js/src/experiment-tracking/reducers/Reducers.js
  mlflow/server/js/src/i18n/I18nUtils.js
  mlflow/server/js/src/i18n/default/en.json
  mlflow/server/js/src/index.js
  mlflow/server/js/src/model-registry/components/CompareModelVersionsPage.js
  mlflow/server/js/src/model-registry/components/CompareModelVersionsPage.test.js
  mlflow/server/js/src/setupAjaxHeaders.js
  mlflow/server/js/yarn.lock
  mlflow/server/js/yarn/releases/yarn-3.1.1.cjs
Labels: rn/feature

#5326 Update `pd.read_json` to pass string type arguments
  tests/catboost/test_catboost_model_export.py
  tests/fastai/test_fastai_model_export.py
  tests/gluon/test_gluon_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/keras/test_keras_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/models/test_cli.py
  tests/onnx/test_onnx_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/prophet/test_prophet_model_export.py
  tests/shap/test_log.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spacy/test_spacy_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none, area/tracking, enable-dev-tests

#5310 Improve run compare ui
  examples/hyperparam/search_hyperopt.py
  examples/hyperparam/search_random.py
  mlflow/server/js/src/experiment-tracking/components/CompareRunView.js
  mlflow/server/js/src/experiment-tracking/components/ParallelCoordinatesPlotControls.js
  mlflow/server/js/src/experiment-tracking/components/ParallelCoordinatesPlotPanel.js
  mlflow/server/js/src/i18n/default/en.json
Labels: rn/none, area/examples, area/tracking

#5329 Scikit-Learn - Made the autolog model serialization format configurable
  mlflow/sklearn/__init__.py
Labels: rn/none, area/tracking

#5328 Fix contour plot
  mlflow/server/js/src/experiment-tracking/components/CompareRunContour.js
Labels: rn/none, area/uiux, area/tracking

#5320 Add docs for artifact proxy
  docs/source/_static/images/scenario_5.png
  docs/source/_static/images/scenario_6.png
  docs/source/concepts.rst
  docs/source/plugins.rst
  docs/source/tracking.rst
Labels: area/docs, rn/documentation
