Repository mlflow/mlflow, pull requests merged in 2022-04, with the labels that each got.

#5572 Do not fail save_model if existing empty folder
  mlflow/catboost.py
  mlflow/fastai/__init__.py
  mlflow/gluon/__init__.py
  mlflow/h2o.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/onnx.py
  mlflow/paddle/__init__.py
  mlflow/pmdarima.py
  mlflow/prophet.py
  mlflow/pyfunc/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/shap.py
  mlflow/sklearn/__init__.py
  mlflow/spacy.py
  mlflow/statsmodels.py
  mlflow/tensorflow/__init__.py
  mlflow/utils/model_utils.py
  mlflow/xgboost/__init__.py
  tests/models/test_model.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sklearn/test_sklearn_model_export.py
Labels: rn/bug-fix, area/models

#5567 Add `--env-manager` option for `mlflow models` commands and deprecate `--no-conda` flag
  mlflow/cli.py
  mlflow/models/cli.py
  mlflow/projects/backend/local.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/backend.py
  mlflow/utils/cli_args.py
  mlflow/utils/environment.py
  tests/models/test_cli.py
  tests/pyfunc/test_scoring_server.py
  tests/pyfunc/test_spark.py
Labels: rn/none

#5573 Fix mlflow-skinny version stack frame inspection failure
  dev/install-common-deps.sh
  mlflow/cli.py
Labels: rn/bug-fix, area/build

#5580 Convert CRLF to LF
  docs/source/python_api/mlflow.statsmodels.rst
  examples/statsmodels/MLproject
  examples/statsmodels/README.md
  examples/statsmodels/conda.yaml
  examples/statsmodels/train.py
  mlflow/server/prometheus_exporter.py
  tests/statsmodels/test_statsmodels_model_export.py
Labels: rn/none

#5570 docs(tracking): add warning regarding stacking artifact location when…
  docs/source/tracking.rst
Labels: rn/none

#5586 Make `EnvManager` private
  mlflow/cli.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/backend.py
  mlflow/utils/cli_args.py
  mlflow/utils/environment.py
  tests/pyfunc/test_scoring_server.py
  tests/pyfunc/test_spark.py
Labels: rn/none, area/tracking

#5587 Simplify `process.exec_cmd` using `subprocess.run`
  mlflow/data.py
  mlflow/projects/docker.py
  mlflow/server/__init__.py
  mlflow/utils/conda.py
  mlflow/utils/process.py
  tests/examples/test_examples.py
  tests/projects/test_projects.py
  tests/projects/test_projects_cli.py
Labels: rn/none

#5581 Fix #5566 - Remove print functions in tests
  tests/examples/test_examples.py
  tests/helper_functions.py
  tests/keras/test_keras_autolog.py
  tests/keras/test_keras_model_export.py
  tests/models/test_cli.py
  tests/models/test_default_evaluator.py
  tests/paddle/test_paddle_model_export.py
  tests/projects/test_kubernetes.py
  tests/projects/utils.py
  tests/resources/example_docker_project/scripts/docker_tracking_test.py
  tests/resources/example_project/greeter.py
  tests/resources/example_project/tracking_test.py
  tests/resources/example_project_no_spec/check_conda_env.py
  tests/server/test_handlers.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spacy/test_spacy_model_export.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging.py
  tests/store/artifact/test_artifact_repo.py
  tests/store/artifact/test_dbfs_fuse_artifact_repo.py
  tests/store/dump_schema.py
  tests/store/model_registry/test_rest_store.py
  tests/store/tracking/test_file_store.py
  tests/tensorflow/test_tensorflow2_autolog.py
  tests/tracking/fluent/test_fluent.py
  tests/tracking/integration_test_utils.py
  tests/tracking/test_model_registry.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, area/build

#5564 Implement issue-5507 - add search_runs_by_name
  docs/source/search-syntax.rst
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/feature, area/model-registry

#5529 Add SVG icon and logos
  assets/icon.svg
  assets/logo-white.svg
  assets/logo.svg
Labels: area/docs, rn/none

#5596 Remove unnecessary `set_tracking_uri` calls in tests
  tests/diviner/test_diviner_model_export.py
  tests/fastai/test_fastai_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/pmdarima/test_pmdarima_model_export.py
  tests/prophet/test_prophet_model_export.py
  tests/sklearn/test_sklearn_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none

#5592 enable cross version tests for diviner
  dev/run-python-flavor-tests.sh
  mlflow/ml-package-versions.yml
  tests/diviner/test_diviner_model_export.py
Labels: rn/none, area/build, enable-dev-tests

#5584 Introduce mlflow.last_active_run fluent API
  docs/source/tracking.rst
  examples/lightgbm/lightgbm_sklearn/train.py
  examples/ray_serve/train_model.py
  examples/sklearn_autolog/grid_search_cv.py
  examples/sklearn_autolog/linear_regression.py
  examples/sklearn_autolog/pipeline.py
  examples/xgboost/xgboost_sklearn/train.py
  mlflow/__init__.py
  mlflow/tracking/fluent.py
  tests/autologging/test_autologging_behaviors_integration.py
  tests/tracking/fluent/test_fluent.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/feature, area/tracking

#5602 Remove duplicate spark autologging ML tests
  dev/run-python-flavor-tests.sh
Labels: rn/none, area/build

#5604 Replace `"--no-conda"` with `"--env-manager", "local"` in tests
  tests/catboost/test_catboost_model_export.py
  tests/diviner/test_diviner_model_export.py
  tests/gluon/test_gluon_model_export.py
  tests/helper_functions.py
  tests/keras/test_keras_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/models/test_cli.py
  tests/onnx/test_onnx_model_export.py
  tests/pmdarima/test_pmdarima_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_scoring_server.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spacy/test_spacy_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/tensorflow/test_tensorflow2_model_export.py
  tests/test_cli.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none, area/build, enable-dev-tests

#5603 Enable print-function pylint check in `tests`
  pylint_plugins/print_function.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/fake_deployment_plugin.py
Labels: rn/none, area/build

#5600 Replace `import` GitHub Actions job with pytest test
  .github/workflows/master.yml
  tests/test_import.py
Labels: rn/none, area/build

#5605 Add Twitte badge on README
  README.rst
Labels: rn/none

#5585 Introduce an mlflow.artifacts.download_artifacts() API, equivalent to the preexisting CLI
  docs/source/python_api/mlflow.artifacts.rst
  mlflow/__init__.py
  mlflow/artifacts/__init__.py
  mlflow/store/artifact/cli.py
  tests/artifacts/test_artifacts.py
  tests/store/artifact/test_cli.py
Labels: rn/feature, area/artifacts

#5613 Support upcoming PySpark 3.3.0 release in MLflow autologging
  mlflow/utils/autologging_utils/versioning.py
  tests/autologging/test_autologging_utils.py
Labels: rn/none, area/tracking

#5616 [ML-21470] Fix cross-workspace source link by adding scheme to workspaceUrl
  mlflow/utils/databricks_utils.py
Labels: rn/none, area/tracking, integrations/databricks

#5593 Remove client name validation from metrics params and tags
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/utils/validation.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/test_tracking.py
Labels: rn/bug-fix, area/tracking

#5615 Disable `import/no-anonymous-default-export` warnings
  mlflow/server/js/src/experiment-tracking/styles/Colors.js
  mlflow/server/js/src/experiment-tracking/utils/test-utils/Fixtures.js
  mlflow/server/js/src/model-registry/reducers.js
Labels: rn/none

#5622 Remove attempted sqlalchemy import from mlflow skinny search path and add tests
  dev/run-python-skinny-tests.sh
  mlflow/utils/search_utils.py
  tests/helper_functions.py
Labels: rn/none, area/tracking

#5621 Fixed /model-versions/get-artifact not being proxied
  mlflow/server/js/src/setupProxy.js
Labels: rn/bug-fix, area/uiux, area/model-registry

#5623 Fix `import/no-anonymous-default-export` warnings
  mlflow/server/js/src/experiment-tracking/styles/Colors.js
  mlflow/server/js/src/experiment-tracking/utils/test-utils/Fixtures.js
  mlflow/server/js/src/model-registry/reducers.js
Labels: rn/none

#5624 Use local prophet version for dev scoring tests
  tests/prophet/test_prophet_model_export.py
Labels: rn/none, area/build, enable-dev-tests

#5610 Add ability to run docker image in AWS Sagemaker Serverless environment
  mlflow/models/docker_utils.py
Labels: rn/bug-fix, integrations/sagemaker

#5597 Remove TempDir references and os path manipulation in tests
  tests/diviner/test_diviner_model_export.py
  tests/pmdarima/test_pmdarima_model_export.py
  tests/prophet/test_prophet_model_export.py
Labels: rn/none, area/build

#5626 Fix icon arrows, optimize SVG paths, update logos and favicon
  assets/icon.svg
  assets/logo-white.svg
  assets/logo.svg
  docs/source/_static/MLflow-logo-final-black.png
  docs/source/_static/favicon.ico
Labels: area/docs, rn/none

#5629 Badge standardization
  README.rst
Labels: area/docs, rn/none

#5591 adding warnings for scenarios 5 and 6
  docs/source/tracking.rst
Labels: area/docs, rn/none

#5625 Add a python script to log MLflow runs in Databricks
  examples/databricks/log_runs.py
Labels: rn/none

#5632 Replace `use_conda` with `env_manager` in `mlflow/projects`
  mlflow/cli.py
  mlflow/projects/__init__.py
  mlflow/projects/backend/local.py
  mlflow/projects/utils.py
Labels: rn/none

#5561 pyfunc.spark_udf: conda env dir / cache dir isolation and NFS optimization
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/backend.py
  mlflow/utils/conda.py
  mlflow/utils/file_utils.py
  mlflow/utils/nfs_on_spark.py
  mlflow/utils/process.py
  tests/models/test_cli.py
  tests/utils/test_process_utils.py
Labels: rn/feature, area/scoring

#5640 Replace all(list comprehension) with all(generator) to lazily evaluate elements
  mlflow/models/utils.py
  mlflow/projects/_project_spec.py
  mlflow/pyfunc/__init__.py
  mlflow/sklearn/utils.py
  mlflow/spacy.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/types/utils.py
  mlflow/utils/search_utils.py
  mlflow/utils/uri.py
  tests/autologging/test_autologging_behaviors_integration.py
  tests/autologging/test_autologging_behaviors_unit.py
  tests/autologging/test_autologging_safety_unit.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sagemaker/mock/test_sagemaker_service_mock.py
  tests/sagemaker/test_batch_deployment.py
  tests/sagemaker/test_deployment.py
  tests/sagemaker/test_sagemaker_deployment_client.py
  tests/sklearn/test_sklearn_model_export.py
  tests/tensorflow/test_tensorflow2_autolog.py
  tests/tracking/test_tracking.py
  tests/types/test_schema.py
Labels: rn/none

#5639 Add problem matchers for pylint
  .github/workflows/master.yml
  .github/workflows/matchers/pylint.json
Labels: rn/none, area/build

#5646 All relevant strings concatenated, where appropriate, in python files
  examples/hyperparam/search_hyperopt.py
  examples/keras/train.py
  examples/multistep_workflow/main.py
  mlflow/azureml/cli.py
  mlflow/deployments/cli.py
  mlflow/mleap.py
  mlflow/models/evaluation/lift_curve.py
  mlflow/projects/__init__.py
  mlflow/projects/_project_spec.py
  mlflow/projects/databricks.py
  mlflow/projects/docker.py
  mlflow/projects/kubernetes.py
  mlflow/sagemaker/__init__.py
  mlflow/spark.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/types/utils.py
  mlflow/utils/autologging_utils/safety.py
  mlflow/utils/rest_utils.py
  mlflow/utils/search_utils.py
  tests/models/test_cli.py
  tests/onnx/test_onnx_model_export.py
  tests/resources/example_project/check_conda_env.py
  tests/resources/example_project_no_spec/check_conda_env.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/utils/test_rest_utils.py
Labels: rn/none

#5638 Remove files in `mlflow/server/js/src/mfe`
  mlflow/server/js/src/mfe/prefetch.js
  mlflow/server/js/src/mfe/register.js
Labels: rn/none

#5648 Revert #5571 (branch-1.25)
  docs/source/tracking.rst
  mlflow/cli.py
  mlflow/utils/server_cli_utils.py
  mlflow/utils/uri.py
  tests/test_cli.py
Labels: rn/none, area/server-infra

#5647 Revert #5571
  docs/source/tracking.rst
  mlflow/cli.py
  mlflow/utils/server_cli_utils.py
  mlflow/utils/uri.py
  tests/test_cli.py
Labels: rn/none, area/server-infra

#5652 Set `log_model_signatures=False` by default for `mlflow.tensorflow.autolog()`
  mlflow/tensorflow/__init__.py
  mlflow/tracking/fluent.py
  mlflow/utils/autologging_utils/__init__.py
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/none, area/tracking

#5661 Specify verson when fetching git repository
  mlflow/projects/utils.py
  tests/projects/test_utils.py
Labels: rn/none

#5627 Add `MlflowException.invalid_parameter_value`
  mlflow/exceptions.py
  tests/test_exceptions.py
Labels: rn/none

#5657 Fixes #5582
  mlflow/pyfunc/model.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/none, area/models

#5668 Update UI
  mlflow/server/js/.eslintignore
  mlflow/server/js/.eslintrc.js
  mlflow/server/js/craco.config.js
  mlflow/server/js/jsconfig.json
  mlflow/server/js/package.json
  mlflow/server/js/src/app.js
  mlflow/server/js/src/experiment-tracking/components/App.js
  mlflow/server/js/src/index.js
  mlflow/server/js/src/setupProxy.js
  mlflow/server/js/yarn.lock
Labels: rn/none

#5675 Fix documentation for experiment_names of search_runs
  docs/source/search-syntax.rst
  mlflow/tracking/fluent.py
Labels: rn/none

#5669 Create test coverage reports by default in pytest
  .github/workflows/cross-version-tests.yml
  dev/run-small-python-tests.sh
  pytest.ini
  tests/db/Dockerfile
  tests/db/Dockerfile.mssql
Labels: rn/none, area/build

#5685 Remove unnecessary warning capturing
  tests/gluon/test_gluon_autolog.py
  tests/gluon/test_gluon_model_export.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#5684 Fix temp directory permission issue on worker side
  mlflow/pyfunc/__init__.py
  mlflow/utils/file_utils.py
  mlflow/utils/nfs_on_spark.py
Labels: rn/none

#5688 [branch-1.25] Fix temp directory permission issue on worker side (#5684)
  mlflow/pyfunc/__init__.py
  mlflow/utils/file_utils.py
  mlflow/utils/nfs_on_spark.py
Labels: rn/none, area/scoring

#5380 Add pyenv + virtualenv support for MLflow Models
  .github/actions/setup-pyenv/action.yml
  .github/workflows/master.yml
  mlflow/catboost.py
  mlflow/diviner.py
  mlflow/fastai/__init__.py
  mlflow/gluon/__init__.py
  mlflow/h2o.py
  mlflow/keras.py
  mlflow/lightgbm.py
  mlflow/onnx.py
  mlflow/paddle/__init__.py
  mlflow/pmdarima.py
  mlflow/prophet.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/backend.py
  mlflow/pyfunc/model.py
  mlflow/pytorch/__init__.py
  mlflow/shap.py
  mlflow/sklearn/__init__.py
  mlflow/spacy.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/tensorflow/__init__.py
  mlflow/utils/cli_args.py
  mlflow/utils/conda.py
  mlflow/utils/environment.py
  mlflow/utils/process.py
  mlflow/utils/requirements_utils.py
  mlflow/utils/virtualenv.py
  mlflow/xgboost/__init__.py
  setup.py
  tests/pyfunc/test_virtualenv.py
  tests/utils/test_python_env.py
Labels: rn/none

#5531 Use schema when parsing csv
  mlflow/pyfunc/scoring_server/__init__.py
  tests/pyfunc/test_scoring_server.py
Labels: rn/feature, area/scoring

#5460 #4299 log_batch actually writes in batches
  mlflow/entities/metric.py
  mlflow/entities/param.py
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/bug-fix, area/tracking

#5695 Add python code to print out tracking URI and artifact URI in bug report template
  .github/ISSUE_TEMPLATE/bug_report_template.md
Labels: rn/none

#5696 Document virtualenv support for MLflow Models
  docs/source/models.rst
Labels: area/docs, rn/none

#5700 Replace deprecated sklearn plotting functions with plotting class methods
  mlflow/sklearn/utils.py
Labels: rn/none, area/tracking

#5702 Run JS tests only when files in `mlflow/server/js` change
  .github/workflows/js.yml
  .github/workflows/master.yml
Labels: rn/none, area/build

#3378 Adding end time and run duration to Compare Runs view
  mlflow/server/js/src/experiment-tracking/components/CompareRunView.js
  mlflow/server/js/src/i18n/default/en.json
Labels: rn/feature, area/uiux

#5707 Replace deprecated flag in examples
  examples/pytorch/AxHyperOptimizationPTL/README.md
  examples/pytorch/BertNewsClassification/README.md
  examples/pytorch/CaptumExample/README.md
  examples/pytorch/MNIST/README.md
  examples/pytorch/torchscript/IrisClassification/README.md
  examples/pytorch/torchscript/MNIST/README.md
  examples/rapids/mlflow_project/README.md
  examples/tensorflow/tf2/README.md
Labels: rn/none, area/examples

#5703 Replace `_EnvManager` enum with enum-like module
  mlflow/cli.py
  mlflow/projects/__init__.py
  mlflow/projects/backend/local.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/backend.py
  mlflow/utils/cli_args.py
  mlflow/utils/env_manager.py
  mlflow/utils/environment.py
  tests/models/test_cli.py
  tests/pyfunc/test_scoring_server.py
  tests/pyfunc/test_spark.py
Labels: rn/none, area/models, area/projects

#5708 Fix `assert-raises-without-msg` pylint rule
  pylint_plugins/__init__.py
  pylint_plugins/unittest_assert_raises.py
  tests/pylint_plugins/test_unittest_assert_raises.py
Labels: rn/none, area/build

#5710 Run `yarn build` in js workflow
  .github/workflows/js.yml
  .github/workflows/test-package-build.yml
Labels: rn/none, area/build

#5378 Introducing abstract endpoint methods
  mlflow/deployments/base.py
  mlflow/sagemaker/__init__.py
  tests/deployments/test_cli.py
  tests/deployments/test_deployments.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/fake_deployment_plugin.py
Labels: rn/feature, area/scoring

#5711 Update UI
  mlflow/server/js/src/common/components/ErrorView.js
  mlflow/server/js/src/common/components/ErrorView.test.js
  mlflow/server/js/src/common/styles/accessibility-overrides.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentPage.test.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentView.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentViewUtil.js
  mlflow/server/js/src/experiment-tracking/components/LoadMoreBar.js
  mlflow/server/js/src/experiment-tracking/components/LoadMoreBar.test.js
  mlflow/server/js/src/experiment-tracking/components/NoExperimentView.js
  mlflow/server/js/src/experiment-tracking/components/PermissionDeniedView.js
  mlflow/server/js/src/experiment-tracking/components/PermissionDeniedView.test.js
  mlflow/server/js/src/experiment-tracking/styles/Colors.js
  mlflow/server/js/src/i18n/default/en.json
  mlflow/server/js/src/model-registry/components/CompareModelVersionsView.js
  mlflow/server/js/src/model-registry/components/CreateModelButton.js
  mlflow/server/js/src/model-registry/components/ModelListView.js
  mlflow/server/js/src/model-registry/components/ModelVersionTable.js
  mlflow/server/js/src/model-registry/constants.js
  mlflow/server/js/src/model-registry/utils.js
Labels: rn/feature, area/uiux

#5721 Pin `google-cloud-storage` to >= 1.30.0
  setup.py
Labels: rn/none

#5458 Adds JSON Schema Validation
  mlflow/server/handlers.py
  tests/tracking/integration_test_utils.py
  tests/tracking/test_rest_tracking.py
Labels: rn/feature, rn/bug-fix, area/tracking

#5677 Doc and example code snippet for `mlflow.pyfunc.spark_udf` restoring model dependencies
  docs/source/models.rst
  examples/spark_udf/README.md
  examples/spark_udf/spark_udf.py
Labels: area/docs, rn/none

#5683 Added autologging safety validation exemptions, and fixed autolog does not log implicit batch_size for tf keras fit method
  mlflow/tensorflow/__init__.py
  mlflow/utils/__init__.py
  mlflow/utils/autologging_utils/safety.py
  tests/autologging/test_autologging_safety_unit.py
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/bug-fix, area/tracking

#5510 Added autologging of input example and signature for tf.estimator and keras fit_generator
  mlflow/keras.py
  mlflow/tensorflow/__init__.py
  mlflow/tensorflow/_autolog.py
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/feature, area/models

#5724 set requirements for pytorchlightning package regression
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#5676 Make `pyfunc.spark_udf` support virtualenv
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/backend.py
  mlflow/utils/conda.py
  mlflow/utils/file_utils.py
  mlflow/utils/process.py
  mlflow/utils/virtualenv.py
  tests/pyfunc/test_spark.py
Labels: rn/feature, area/scoring

#5726 Remove trailing spaces
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/pull_request_template.md
  .github/workflows/examples.yml
  CODE_OF_CONDUCT.rst
  CONTRIBUTING.rst
  ISSUE_TRIAGE.rst
  README.rst
  SECURITY.md
  docs/source/concepts.rst
  docs/source/index.rst
  docs/source/model-registry.rst
  docs/source/models.rst
  docs/source/plugins.rst
  docs/source/projects.rst
  docs/source/quickstart.rst
  docs/source/tracking.rst
  docs/source/tutorials-and-examples/tutorial.rst
  examples/README.md
  examples/docker/README.rst
  examples/evaluation/README.md
  examples/fastai/README.md
  examples/multistep_workflow/README.rst
  examples/pytorch/AxHyperOptimizationPTL/README.md
  examples/pytorch/BertNewsClassification/README.md
  examples/pytorch/CaptumExample/README.md
  examples/pytorch/IterativePruning/README.md
  examples/pytorch/MNIST/README.md
  examples/pytorch/torchscript/MNIST/README.md
  examples/rapids/mlflow_project/README.md
  examples/ray_serve/README.md
  examples/spark_udf/README.md
  examples/supply_chain_security/README.rst
  mlflow/R/mlflow/README.md
  mlflow/java/client/README.md
  mlflow/java/scoring/src/test/resources/org/mlflow/mleap_model/sample_input.json
  mlflow/java/scoring/src/test/resources/org/mlflow/regression_model/mleap/schema.json
  mlflow/server/js/README.md
  tests/examples/README.md
Labels: area/docs, rn/none

#5730 Resolved typos
  dev/set_matrix.py
  mlflow/projects/databricks.py
  tests/store/tracking/__init__.py
Labels: rn/none

#5734 Fixing typography in some files
  dev/update_ml_package_versions.py
  dev/update_pypi_package_index.py
  mlflow/models/utils.py
Labels: rn/none

#5735 #5712 typos fixed
  mlflow/store/artifact/s3_artifact_repo.py
  mlflow/tracking/request_header/registry.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#5743 Fixed Typos
  mlflow/projects/utils.py
  mlflow/server/handlers.py
  mlflow/tracking/context/registry.py
Labels: rn/none

#5746 fixed typos
  mlflow/fastai/__init__.py
  mlflow/server/__init__.py
  mlflow/sklearn/__init__.py
Labels: rn/none

#5747 fixed typos
  mlflow/sklearn/utils.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
Labels: rn/none

#5748 Add `min_python_version` command to get minimum python version mlflow supports easily
  .github/actions/setup-python/action.yml
  .github/workflows/cross-version-tests.yml
  .github/workflows/examples.yml
  .github/workflows/master.yml
  .github/workflows/test-package-build.yml
  setup.py
Labels: rn/none, area/build

#5758 Add mlflow_version field to Models docs
  docs/source/models.rst
Labels: area/docs, rn/none

#5727 Document virtualenv suppport for MLflow projects
  docs/source/projects.rst
Labels: area/docs, rn/none, rn/feature

#5631 Add virtualenv support for MLflow projects
  .github/workflows/master.yml
  examples/virtualenv/project/MLproject
  examples/virtualenv/project/entrypoint.py
  examples/virtualenv/project/python_env.yaml
  examples/virtualenv/project/requirements.txt
  mlflow/models/cli.py
  mlflow/projects/__init__.py
  mlflow/projects/_project_spec.py
  mlflow/projects/backend/local.py
  mlflow/projects/databricks.py
  mlflow/projects/env_type.py
  mlflow/utils/cli_args.py
  mlflow/utils/environment.py
  mlflow/utils/virtualenv.py
  tests/projects/test_databricks.py
  tests/projects/test_project_spec.py
  tests/projects/test_utils.py
  tests/projects/test_virtualenv_projects.py
  tests/projects/utils.py
  tests/resources/example_virtualenv_conda_project/MLproject
  tests/resources/example_virtualenv_conda_project/conda.yaml
  tests/resources/example_virtualenv_conda_project/entrypoint.py
  tests/resources/example_virtualenv_project/MLproject
  tests/resources/example_virtualenv_project/entrypoint.py
  tests/resources/example_virtualenv_project/python_env.yaml
  tests/resources/example_virtualenv_project/requirements.txt
  tests/utils/test_python_env.py
Labels: rn/feature, area/projects

#5760 Fix `min-python-version` to `min_python_version`
  .github/workflows/cross-version-tests.yml
Labels: rn/none, area/build

#5723 feat: support using wildcards in log_model_allowlist
  mlflow/_spark_autologging.py
  mlflow/pyspark/ml/__init__.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
Labels: rn/feature, area/tracking

#5761 Fix Spelling Mistake
  mlflow/utils/cli_args.py
Labels: rn/none

#5775 Use r-base Docker image as initial layer for R package build
  mlflow/R/mlflow/Dockerfile.r-devel
Labels: rn/none, area/build

#5769 Use yarn and node 16 in `Dockerfile`
  Dockerfile
Labels: rn/none, area/build

#5768 Remove old ML packages versions in `ml-package-versions.yml`
  mlflow/ml-package-versions.yml
Labels: rn/none

#5763 Fix `r` job broken by R 4.2.0
  mlflow/R/mlflow/Dockerfile.dev
  mlflow/R/mlflow/tests/testthat/test-keras-model.R
  mlflow/rfunc/backend.py
Labels: rn/none, area/build

#5765 Remove duplicate conda dependency check for MLflow Models
  mlflow/utils/virtualenv.py
Labels: rn/none, area/models, area/projects

#5752 Improve `is_in_databricks_runtime` function
  mlflow/utils/databricks_utils.py
  tests/utils/test_databricks_utils.py
Labels: rn/none, area/tracking

#5737 Add example for "pyfunc.get_model_dependencies", and improve get_model_dependencies pip command prefix printing
  examples/restore_model_dependencies/README.md
  examples/restore_model_dependencies/restore_model_dependencies_example.ipynb
  examples/spark_udf/README.md
  mlflow/pyfunc/__init__.py
  mlflow/utils/__init__.py
  tests/pyfunc/test_dependencies_functions.py
Labels: rn/none, area/examples, area/models

#5753 When loading spark model, bind spark.driver.bindAddress to 127.0.0.1
  mlflow/spark.py
Labels: rn/bug-fix, area/models

#5715 Mlflow db store raise mlflow exception with correct message argument
  mlflow/exceptions.py
  mlflow/store/db/utils.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none, area/tracking

#5764 PyTorch examples - Updating pytorch lightning version to 1.6.1
  examples/pytorch/AxHyperOptimizationPTL/conda.yaml
  examples/pytorch/BertNewsClassification/bert_classification.py
  examples/pytorch/BertNewsClassification/conda.yaml
  examples/pytorch/IterativePruning/conda.yaml
  examples/pytorch/MNIST/conda.yaml
Labels: rn/none, area/examples

#5728 Add virtualenv support for `mlflow models docker-build`
  dev/run-python-sagemaker-tests.sh
  mlflow/models/cli.py
  mlflow/models/container/__init__.py
  mlflow/models/docker_utils.py
  mlflow/pyfunc/backend.py
  mlflow/sagemaker/cli.py
  mlflow/utils/cli_args.py
  tests/helper_functions.py
  tests/models/test_cli.py
Labels: rn/feature, area/models

#5778 Fix JSON schema validation issue for `run_uuid`
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, area/tracking

#5606 Preview images with full width
  mlflow/server/js/src/experiment-tracking/components/ArtifactView.css
  mlflow/server/js/src/experiment-tracking/components/ArtifactView.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactImageView.css
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactImageView.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactImageView.test.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactPdfView.js
Labels: rn/bug-fix, area/uiux

#5767 fix: fix mlflow server starts in R on windows
  docs/source/R-api.rst
  hooks/prepare-commit-msg
  mlflow/R/mlflow/R/python.R
  mlflow/R/mlflow/R/tracking-server.R
  mlflow/R/mlflow/man/mlflow_server.Rd
Labels: area/windows, language/r, rn/bug-fix, area/server-infra

#5766 Remove unnecessary `set_boto_credentials` fixture
  tests/azureml/test_deploy.py
  tests/azureml/test_image_creation.py
  tests/catboost/test_catboost_model_export.py
  tests/fastai/test_fastai_model_export.py
  tests/helper_functions.py
  tests/keras/test_keras_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spark/test_spark_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/tensorflow/test_tensorflow2_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none

#5719 Autologging of input example and signature for pyspark ml
  mlflow/pyspark/ml/__init__.py
  mlflow/pyspark/ml/_autolog.py
  mlflow/spark.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
Labels: rn/feature, area/models

#5794 Fix `_find_latest_installable_python_version` to use `/databricks/.pyenv/bin/pyenv` on Databricks
  mlflow/utils/virtualenv.py
Labels: rn/none, area/models, area/projects

#5777 Run CRAN check with `r-devel` when releasing a new version & daily
  .github/workflows/master.yml
  .github/workflows/r.yml
  mlflow/R/mlflow/Dockerfile.r-devel
Labels: rn/none, area/build

#5749 Update MLflow client to read git info from CommandContext
  mlflow/tracking/context/databricks_repo_context.py
  mlflow/tracking/context/registry.py
  mlflow/utils/databricks_utils.py
  mlflow/utils/mlflow_tags.py
  tests/tracking/context/test_databricks_repo_context.py
  tests/tracking/context/test_registry.py
Labels: rn/none, area/tracking

#5795 Add status badge for CRAN check with `r-devel` on README
  README.rst
Labels: rn/none, area/build

#5574 Show latest, minimum and maximum metric values on metric page
  mlflow/server/js/src/experiment-tracking/components/HtmlTableView.js
  mlflow/server/js/src/experiment-tracking/components/MetricView.css
  mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.js
  mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.test.js
  mlflow/server/js/src/experiment-tracking/components/MetricsSummaryTable.js
  mlflow/server/js/src/experiment-tracking/components/MetricsSummaryTable.test.js
  mlflow/server/js/src/experiment-tracking/reducers/MetricReducer.js
  mlflow/server/js/src/experiment-tracking/reducers/MetricReducer.test.js
  mlflow/server/js/src/experiment-tracking/reducers/Reducers.js
  mlflow/server/js/src/i18n/default/en.json
Labels: rn/feature, area/uiux

#5806 Pyfunc: Fix code dir resolution of subdirectories
  mlflow/utils/model_utils.py
  tests/utils/test_model_utils.py
Labels: rn/bug-fix, area/models

#5785 fix metric names with "@" signs for lightgbm autolog
  mlflow/lightgbm.py
  tests/lightgbm/test_lightgbm_autolog.py
Labels: rn/bug-fix, area/tracking

#5808 Fix: Removed get_experiment_by_name as not required
  mlflow/tracking/fluent.py
Labels: rn/none
