Repository mlflow/mlflow, pull requests merged in 2023-05, with the labels that each got.

#8171 Quickstart
  docs/image-sources/quickstart/mlflow_tracking.mermaid
  docs/source/_static/images/quickstart-ui-screenshot.png
  docs/source/_static/images/quickstart/quickstart_databricks_workspace_url.png
  docs/source/_static/images/quickstart/quickstart_run_id.png
  docs/source/_static/images/quickstart/quickstart_tracking_overview.png
  docs/source/_static/images/quickstart/quickstart_ui_chart_view.png
  docs/source/_static/images/quickstart/quickstart_ui_detail_page.png
  docs/source/_static/images/quickstart/quickstart_ui_metric_history.png
  docs/source/_static/images/quickstart/quickstart_ui_screenshot.png
  docs/source/index.rst
  docs/source/models.rst
  docs/source/plugins.rst
  docs/source/quickstart.rst
  docs/source/quickstart_drilldown.rst
  docs/source/tracking.rst
Labels: area/docs, rn/documentation

#8364 [Feature branch] Add small test for dataset rest tracking returning correct entities
  tests/tracking/test_rest_tracking.py
Labels: rn/none, area/tracking

#8358 Fix log batch schema validation
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/bug-fix, area/server-infra

#8367 Pin ipython to fix recipes tests
  requirements/test-requirements.txt
Labels: rn/none, area/build

#8366 [Feature branch] Fix bug when constructing Spark datasets from file path sources
  mlflow/data/spark_dataset.py
  mlflow/data/spark_delta_utils.py
  tests/data/test_spark_dataset.py
Labels: rn/none, area/tracking

#8362 Fix bug in paginated search/listing of model versions in Unity Catalog
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/none

#8374 Lint fixes for LangChain
  tests/langchain/test_langchain_model_export.py
Labels: rn/none, area/build

#8377 Updated UC Model Registry Client to include aliases in RegisteredModel and ModelVersion payloads
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/store/_unity_catalog/registry/utils.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_utils.py
Labels: rn/bug-fix, area/model-registry

#8363 Added secret scope check to OpenAI credential call
  mlflow/openai/__init__.py
  mlflow/utils/databricks_utils.py
  tests/openai/test_openai_model_export.py
  tests/utils/test_databricks_utils.py
Labels: rn/bug-fix, area/models

#8381 pin numpy and fix tf test for dtype
  .github/workflows/master.yml
  mlflow/ml-package-versions.yml
  mlflow/models/evaluation/base.py
  tests/evaluate/__init__.py
  tests/evaluate/test_default_evaluator.py
  tests/evaluate/test_evaluation.py
  tests/evaluate/test_validation.py
  tests/tensorflow/test_load_saved_tensorflow_estimator.py
Labels: rn/none, area/build, enable-dev-tests

#8384 fix log_input with tags
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, area/tracking

#8391 Fix schema inference issue with Text2TextGenerationPipelines
  mlflow/transformers.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/none, area/models

#8390 Fetch active catalog and schema in UC client when model name is not fully specified
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/_unity_catalog/registry/utils.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/none, area/model-registry, integrations/databricks

#8399 change example to a modern updated model
  examples/transformers/simple.py
Labels: rn/none, area/examples

#8398 Fix LightGBM dev cross test
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build, enable-dev-tests

#8392 Bugfix: don't fail UC model version creation if we cannot fetch its source run
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/none, rn/bug-fix

#8402 Update LightGBM cross test command
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build, enable-dev-tests

#8403 added gluon pyfunc example
  docs/source/models.rst
Labels: area/docs, rn/documentation

#8394 6099 statsmodels pyfunc example
  docs/source/models.rst
Labels: area/docs, rn/documentation

#8371 A new community plugin for mlflow.evaluate() 🎉
  docs/source/models.rst
  docs/source/plugins.rst
Labels: rn/documentation

#8387 Add signatures to MLflow examples
  examples/evaluation/evaluate_on_binary_classifier.py
  examples/evaluation/evaluate_with_custom_metrics.py
  examples/evaluation/evaluate_with_custom_metrics_comprehensive.py
  examples/evaluation/evaluate_with_model_validation.py
  examples/flower_classifier/image_pyfunc.py
  examples/flower_classifier/train.py
  examples/hyperparam/train.py
  examples/pip_requirements/pip_requirements.py
  examples/pmdarima/train.py
  examples/prophet/train.py
  examples/pyfunc/train.py
  examples/pytorch/torchscript/IrisClassification/iris_classification.py
  examples/rapids/mlflow_project/src/rf_test/train.py
  examples/rapids/mlflow_project/src/rf_test/train_simple.py
  examples/sklearn_elasticnet_diabetes/linux/train_diabetes.py
  examples/sklearn_elasticnet_diabetes/osx/train_diabetes.py
  examples/sklearn_elasticnet_wine/train.ipynb
  examples/sklearn_elasticnet_wine/train.py
  examples/sklearn_logistic_regression/train.py
  examples/spark_udf/spark_udf.py
  examples/tensorflow/train.py
  examples/transformers/load_components.py
  examples/transformers/simple.py
Labels: rn/documentation, area/examples

#8400 Add signature to code examples in MLflow docs
  docs/source/model-registry.rst
  docs/source/models.rst
  docs/source/quickstart.rst
Labels: area/docs, rn/none

#8401 Add model signatures examples in function docstrings
  mlflow/lightgbm.py
  mlflow/models/model.py
  mlflow/models/utils.py
  mlflow/pytorch/__init__.py
  mlflow/sklearn/__init__.py
Labels: area/docs, rn/none

#8375 Use GPU automatically if available for PyTorch and TF backed HF models
  mlflow/environment_variables.py
  mlflow/transformers.py
Labels: rn/feature, area/models, area/scoring, integrations/databricks

#8286 Implement user & permissions for HTTP Basic Auth
  examples/auth/README.md
  examples/auth/auth.py
  mlflow/server/auth/__init__.py
  mlflow/server/auth/basic_auth.ini
  mlflow/server/auth/config.py
  mlflow/server/auth/entities.py
  mlflow/server/auth/logo.py
  mlflow/server/auth/permissions.py
  mlflow/server/auth/sqlalchemy_store.py
  mlflow/server/handlers.py
  tests/server/auth/test_auth.py
  tests/server/auth/test_sqlalchemy_store.py
Labels: rn/feature, area/tracking

#8405 Disable spurious autolog
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/tracking/fluent.py
  mlflow/transformers.py
  mlflow/utils/autologging_utils/__init__.py
  requirements/extra-ml-requirements.txt
  tests/autologging/test_autologging_utils.py
  tests/tracking/fluent/test_fluent_autolog.py
  tests/transformers/test_transformers_autolog.py
Labels: rn/feature, area/models, area/tracking

#8412 Adjust numpy requirements for gluon tests
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#8411 Add list of committers
  CONTRIBUTING.md
  README.rst
Labels: rn/none

#8385 Fix git remote in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: rn/none

#8415 Remove flaky assert in tests/store/artifact/test_databricks_artifact_repo.py
  tests/store/artifact/test_databricks_artifact_repo.py
Labels: rn/none

#8410 Change Python lists to numpy arrays and add model signatures in documentation
  examples/catboost/train.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
Labels: area/docs, rn/none, area/examples

#8365 What is mlflow?
  docs/source/_static/images/what-is-mlflow/mlflow-overview.png
  docs/source/_static/images/what-is-mlflow/model-details.png
  docs/source/_static/images/what-is-mlflow/tracking-chart.png
  docs/source/index.rst
  docs/source/what-is-mlflow.rst
Labels: area/docs, rn/documentation

#8422 Pin mlflow version strictly
  mlflow/utils/environment.py
  tests/helper_functions.py
Labels: rn/none

#8418 fix default worker in cli 'model serve' for docs
  mlflow/utils/cli_args.py
Labels: rn/none, area/scoring

#8421 Add support for setting torch_dtype in transformers pipelines
  docs/source/models.rst
  mlflow/transformers.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/feature, area/models

#8423 Add support for feature extraction pipelines to transformers
  docs/source/models.rst
  mlflow/transformers.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/feature, area/models

#8425 Add sentence transformers example
  examples/pip_requirements/pip_requirements.py
  examples/transformers/sentence_transformer.py
  tests/examples/test_examples.py
Labels: rn/feature, area/examples

#8427 Fixes for outdated references in docs
  docs/source/models.rst
  docs/source/projects.rst
  docs/source/tutorials-and-examples/index.rst
Labels: area/docs, rn/none

#8297 Adding agent support to LangChain flavor
  docs/source/models.rst
  examples/langchain/simple_agent.py
  mlflow/langchain/__init__.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/openai/utils.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/feature, area/tracking

#8434 Suppress version mismatch warning if mlflow's version is a dev version
  mlflow/utils/requirements_utils.py
Labels: rn/none

#8446 Replace `purrr::map` with `purrr::map_vec`
  mlflow/R/mlflow/tests/testthat/test-tracking-runs.R
Labels: language/r, rn/none

#8429 Fix R NA check for databricks-utils.R
  .github/workflows/r.yml
  mlflow/R/mlflow/R/databricks-utils.R
Labels: language/r, rn/none

#8445 Add Registered Model Alias to the Model Registry Doc Section
  docs/source/model-registry.rst
  mlflow/utils/validation.py
  tests/utils/test_validation.py
Labels: area/docs, rn/breaking-change, rn/documentation, area/model-registry

#8447 Allow empty values in `_EnvironmentVariable`
  mlflow/environment_variables.py
  tests/test_environment_variables.py
Labels: rn/none

#8458 Avoid holidays 0.25
  mlflow/ml-package-versions.yml
  requirements/extra-ml-requirements.txt
Labels: rn/none

#8420 Add MLflavors library to Community Model Flavors docs
  docs/source/community-model-flavors.rst
  docs/source/index.rst
  docs/source/models.rst
Labels: rn/documentation

#8459 Propagate Model Version Deletion to Associated Aliases
  mlflow/store/model_registry/file_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  tests/store/model_registry/test_file_store.py
  tests/store/model_registry/test_sqlalchemy_store.py
Labels: rn/bug-fix, area/model-registry

#8433 add ort session options
  mlflow/onnx.py
  mlflow/utils/model_utils.py
  tests/onnx/test_onnx_model_export.py
Labels: rn/feature, area/models

#8470 Fix typo `erorr_code`
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
Labels: rn/none

#8465 fix: fix failing prophet test
  tests/prophet/test_prophet_model_export.py
Labels: rn/none, enable-dev-tests

#8473 Upgrade black to 23.3.0 (latest version)
  requirements/lint-requirements.txt
Labels: rn/none

#8472 fix error message
  mlflow/onnx.py
  mlflow/utils/model_utils.py
Labels: rn/none, area/models

#8471 Add constants for supported model types of `mlflow.evaluate`
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
Labels: rn/none

#8466 fix: update SCORER usage sklearn version > 1.2.2
  mlflow/sklearn/__init__.py
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/none, area/build, enable-dev-tests

#8372 [Feature branch] Fix schema / profile support for tensor datasets with dictionaries
  mlflow/data/digest_utils.py
  mlflow/data/numpy_dataset.py
  mlflow/data/schema.py
  mlflow/data/tensorflow_dataset.py
  mlflow/tensorflow/__init__.py
  tests/data/test_numpy_dataset.py
  tests/data/test_tensorflow_dataset.py
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/none, area/tracking

#8469 Datasets boilerplate in transformers autolog
  mlflow/transformers.py
Labels: rn/none, area/tracking

#8468 Make `targets` argument of `mlflow.evaluate` optional
  mlflow/models/evaluation/base.py
  tests/evaluate/test_evaluation.py
Labels: rn/none

#8464 Add support for audio transcription pipelines in transformers
  .github/actions/setup-pyenv/action.yml
  docs/source/models.rst
  examples/transformers/whisper.py
  mlflow/ml-package-versions.yml
  mlflow/models/utils.py
  mlflow/transformers.py
  mlflow/types/utils.py
  requirements/extra-ml-requirements.txt
  tests/datasets/apollo11_launch.wav
  tests/examples/test_examples.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/feature, area/models

#8476 `set_signature` API to set the signature for model artifacts
  mlflow/models/__init__.py
  mlflow/models/signature.py
  mlflow/store/artifact/local_artifact_repo.py
  mlflow/tracking/artifact_utils.py
  tests/models/test_signature.py
  tests/tracking/test_artifact_utils.py
Labels: rn/feature, area/models

#8480 Update models.rst
  docs/source/models.rst
Labels: area/docs, rn/documentation

#8463 Don't use `max_age` if Flask version is <2.0
  mlflow/server/__init__.py
Labels: rn/bug-fix, area/uiux, area/server-infra

#8485 Remove unused attributes in `DefaultEvaluator`
  mlflow/models/evaluation/default_evaluator.py
Labels: rn/none

#8486 Remove useless try-catch in `_extract_raw_model`
  mlflow/models/evaluation/default_evaluator.py
Labels: rn/none

#8483 Suppress torch/torchvision local version warning on databricks
  mlflow/utils/requirements_utils.py
Labels: rn/none, area/uiux, area/models

#8496 Remove `self.y_prob` in DefaultEvaluator
  mlflow/models/evaluation/default_evaluator.py
Labels: rn/none

#8452 Clean HF model dependency
  mlflow/utils/_capture_modules.py
  mlflow/utils/_capture_transformers_modules.py
  mlflow/utils/requirements_utils.py
  tests/helper_functions.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/none, area/models

#8505 Remove unnecessary STATIC_DIR variable
  mlflow/server/__init__.py
Labels: rn/none, area/server-infra

#8504 Remove confusing relative paths in `setup.py`
  setup.py
Labels: rn/none

#8467 Adding log table to log dictionary or df as artifacts in MLflow run
  mlflow/__init__.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  mlflow/utils/mlflow_tags.py
  tests/tracking/test_tracking.py
Labels: rn/feature, area/tracking

#8490 Add documentation for setting model signatures
  docs/source/models.rst
  mlflow/models/signature.py
Labels: area/docs, rn/none

#8500 Disallow suppressing pylint rules with IDs
  .pre-commit-config.yaml
  dev/disallow_rule_ids.py
  mlflow/deployments/base.py
  mlflow/fastai/__init__.py
  mlflow/pyfunc/backend.py
  mlflow/recipes/steps/evaluate.py
  mlflow/store/db/utils.py
  mlflow/tensorflow/__init__.py
  mlflow/tracking/fluent.py
  mlflow/transformers.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/gorilla.py
  mlflow/utils/proto_json_utils.py
  mlflow/xgboost/__init__.py
  tests/autologging/test_autologging_utils.py
  tests/pytorch/test_pytorch_model_export.py
  tests/spacy/test_spacy_model_export.py
  tests/statsmodels/model_fixtures.py
  tests/utils/test_docstring_utils.py
  tests/utils/test_model_utils.py
  tests/utils/test_resources/dummy_package/base.py
Labels: rn/none, only-latest

#8503 Disallow importing built-in modules lazily
  examples/flower_classifier/train.py
  examples/rest_api/mlflow_tracking_rest_api.py
  mlflow/cli.py
  mlflow/fastai/__init__.py
  mlflow/models/evaluation/base.py
  mlflow/projects/utils.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/backend.py
  mlflow/pyspark/ml/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/recipes/cards/__init__.py
  mlflow/recipes/steps/automl/flaml.py
  mlflow/recipes/steps/evaluate.py
  mlflow/recipes/steps/train.py
  mlflow/recipes/utils/step.py
  mlflow/rfunc/backend.py
  mlflow/sagemaker/__init__.py
  mlflow/sklearn/utils.py
  mlflow/store/artifact/s3_artifact_repo.py
  mlflow/tracking/artifact_utils.py
  mlflow/transformers.py
  mlflow/utils/__init__.py
  mlflow/utils/_spark_utils.py
  mlflow/utils/file_utils.py
  mlflow/utils/import_hooks/__init__.py
  mlflow/xgboost/__init__.py
  pylint_plugins/__init__.py
  pylint_plugins/errors.py
  pylint_plugins/import_checker.py
  tests/autologging/test_autologging_utils.py
  tests/deployments/test_cli.py
  tests/deployments/test_deployments.py
  tests/examples/test_examples.py
  tests/models/test_model.py
  tests/projects/test_utils.py
  tests/projects/utils.py
  tests/recipes/test_train_step.py
  tests/sagemaker/test_batch_deployment.py
  tests/sagemaker/test_sagemaker_deployment_client.py
  tests/sklearn/test_sklearn_autolog.py
  tests/spark/test_spark_model_export.py
  tests/tensorflow/test_tensorflow2_autolog.py
  tests/tracking/test_artifact_utils.py
  tests/tracking/test_llm_utils.py
  tests/tracking/test_rest_tracking.py
  tests/utils/test_databricks_utils.py
  tests/utils/test_file_utils.py
  tests/utils/test_requirements_utils.py
Labels: rn/none, only-latest

#8506 Add `--dev` option to `mlflow server`
  dev/run-dev-server.sh
  mlflow/cli.py
Labels: rn/none

#8514 Set environment variables for testing openai and langchain automatically
  mlflow/ml-package-versions.yml
  tests/langchain/test_langchain_model_export.py
  tests/openai/test_openai_model_export.py
Labels: rn/none, only-latest

#8515 Replace `ast.literal_eval` with `json.loads`
  tests/tracking/test_tracking.py
Labels: rn/none

#8513 fix failing space & langchain tests
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#8436 Print warning when models are logged without signatures to databricks
  mlflow/models/model.py
Labels: rn/none, area/models

#8520 Reload `openai` after setting `OPENAI_API_KEY`
  mlflow/environment_variables.py
  mlflow/pyfunc/__init__.py
  tests/langchain/test_langchain_model_export.py
  tests/openai/test_openai_model_export.py
Labels: rn/none, enable-dev-tests, only-latest

#8493 Introduce get_parent_run fluent API
  mlflow/__init__.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/feature, area/tracking

#8495 Add support for uri inputs in audio models for transformers
  docs/source/models.rst
  mlflow/transformers.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/feature, area/models

#8524 Add Serena to the maintainer list
  CONTRIBUTING.md
  README.rst
Labels: rn/none

#8508 Shut down spark callback server when spark autologging is disabled or spark session is shut down
  mlflow/_spark_autologging.py
  mlflow/spark.py
Labels: rn/bug-fix, area/uiux, area/tracking

#8532 Remove useless condition in `_init_modules_to_packages_map`
  mlflow/utils/requirements_utils.py
Labels: rn/none

#8533 Fix `log_dict` type hint
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: rn/none

#8525 Update schema in sklearn and xgboost tests
  tests/sklearn/test_sklearn_autolog.py
  tests/xgboost/test_xgboost_autolog.py
Labels: rn/none, area/tracking

#8534 Remove useless temporary directory creation in `log_table`
  mlflow/tracking/client.py
Labels: rn/none

#8453 Support subclasses of chains for langchain flavor
  mlflow/langchain/__init__.py
  mlflow/langchain/api_request_parallel_processor.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/feature, area/models

#8530 Refactor `ArtifactRepository.download_artifacts` and use `as_completed`
  mlflow/store/artifact/artifact_repo.py
  tests/store/artifact/test_artifact_repo.py
Labels: rn/none, area/artifacts

#8448 Add support for multi-GPU inference and efficient weight loading for HuggingFace flavor
  mlflow/environment_variables.py
  mlflow/transformers.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/feature, area/models

#8536 Update optional targets logic with datasets
  mlflow/models/evaluation/base.py
  tests/evaluate/test_evaluation.py
Labels: rn/none, area/tracking

#8543 Fix get source code
  mlflow/data/dataset_source_registry.py
  tests/data/test_dataset_source.py
Labels: rn/none, area/tracking

#8489 Split metric and artifact evaluation in DefaultEvaluator
  mlflow/models/evaluation/default_evaluator.py
Labels: rn/none

#8550 Set `GITHUB_TOKEN` in lint job
  .github/workflows/master.yml
Labels: rn/none

#8518 Basic auth: filter search experiment / registered model results
  mlflow/server/auth/__init__.py
  tests/server/auth/test_auth.py
  tests/tracking/integration_test_utils.py
Labels: rn/feature, area/tracking

#8538 Add tests for Proto_json_utils and fix bug
  mlflow/utils/proto_json_utils.py
  tests/utils/test_proto_json_utils.py
Labels: rn/none

#8352 Use subprocess for multi-part download execution
  mlflow/projects/backend/local.py
  mlflow/projects/docker.py
  mlflow/projects/utils.py
  mlflow/recipes/steps/evaluate.py
  mlflow/recipes/steps/predict.py
  mlflow/recipes/steps/register.py
  mlflow/recipes/steps/train.py
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/store/artifact/local_artifact_repo.py
  mlflow/utils/databricks_utils.py
  mlflow/utils/download_cloud_file_chunk.py
  mlflow/utils/file_utils.py
  mlflow/utils/request_utils.py
  mlflow/utils/rest_utils.py
  sample-file-to-write
  tests/projects/conftest.py
  tests/recipes/test_pipeline.py
  tests/store/artifact/test_databricks_models_artifact_repo.py
  tests/utils/test_request_utils.py
  tests/utils/test_rest_utils.py
Labels: rn/feature, area/model-registry, area/tracking

#8545 Update `ColSpec` repr to handle optional inputs
  mlflow/types/schema.py
Labels: rn/none, area/models

#8528 Add a script to profile large artifact upload and download
  examples/databricks/artifact_perf.py
Labels: rn/none

#8564 feat(docker): build multi-arch images
  .github/workflows/push-images.yml
Labels: rn/feature, area/build

#8546 Convert transformers scalar string output to list of strings for batch inference
  docs/source/models.rst
  mlflow/transformers.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/bug-fix, area/models

#8549 [Feature branch] Increase spark dataset approx count timeout and use "unknown" if count zero returned
  mlflow/data/spark_dataset.py
  tests/data/test_spark_dataset.py
Labels: rn/none, area/tracking

#8303 [Feature branch] Docs for MLflow datasets
  docs/source/python_api/mlflow.data.rst
  docs/source/tracking.rst
  mlflow/data/__init__.py
  mlflow/data/dataset.py
  mlflow/data/dataset_registry.py
  mlflow/data/dataset_source.py
  mlflow/data/dataset_source_registry.py
  mlflow/data/delta_dataset_source.py
  mlflow/data/huggingface_dataset.py
  mlflow/data/huggingface_dataset_source.py
  mlflow/data/numpy_dataset.py
  mlflow/data/pandas_dataset.py
  mlflow/data/spark_dataset.py
  mlflow/data/spark_dataset_source.py
  mlflow/data/tensorflow_dataset.py
  mlflow/models/evaluation/base.py
  mlflow/tracking/fluent.py
  requirements/doc-requirements.txt
  tests/data/test_tensorflow_dataset.py
Labels: area/docs, rn/none, area/tracking

#8565 fix dependencies for cross version failures
  mlflow/ml-package-versions.yml
  tests/prophet/test_prophet_model_export.py
Labels: rn/none, area/build, enable-dev-tests

#8568 Do not suppress `ValueError` in `_TransformersWrapper.predict`
  mlflow/transformers.py
Labels: rn/none, only-latest

#8484 Extend `mlflow.evaluate` to support language model tasks
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  requirements/test-requirements.txt
  tests/evaluate/test_default_evaluator.py
Labels: rn/feature

#8569 Small lint and test fixes
  mlflow/data/__init__.py
  mlflow/data/dataset_registry.py
  mlflow/data/huggingface_dataset.py
  mlflow/data/numpy_dataset.py
  mlflow/data/spark_dataset.py
  mlflow/models/evaluation/base.py
  mlflow/tracking/client.py
  tests/data/test_huggingface_dataset_and_source.py
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/none, area/tracking

#8561 Do not use subprocess in multipart download
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/utils/download_cloud_file_chunk.py
  mlflow/utils/file_utils.py
  mlflow/utils/request_utils.py
  tests/store/artifact/test_databricks_models_artifact_repo.py
  tests/utils/test_request_utils.py
Labels: rn/none

#8548 Implement auth client to manage permissions
  examples/auth/auth.py
  mlflow/server/__init__.py
  mlflow/server/auth/__init__.py
  mlflow/server/auth/client.py
  mlflow/server/auth/entities.py
  mlflow/server/auth/routes.py
  setup.py
  tests/server/auth/auth_test_utils.py
  tests/server/auth/test_auth.py
  tests/server/auth/test_client.py
Labels: rn/documentation, area/tracking

#8566 Document mlflow.get_parent_run in tracking.rst
  docs/source/tracking.rst
Labels: rn/none

#8567 Support `max_shard_size` parameter for HuggingFace flavor
  docs/source/models.rst
  mlflow/environment_variables.py
  mlflow/transformers.py
Labels: rn/feature, area/models
