Repository mlflow/mlflow, pull requests merged in 2023-12, with the labels that each got.

#10553 Fix linking order in Line Chart
  mlflow/server/js/src/experiment-tracking/components/runs-charts/components/RunsMetricsLinePlot.tsx
Labels: rn/bug-fix, area/uiux, area/tracking

#10476 Add docs and tutorials for Sentence Transformers flavor
  docs/source/_static/images/tutorials/llms/semantic-search-arch.png
  docs/source/_static/images/tutorials/llms/sentence-transformers-architecture.png
  docs/source/index.rst
  docs/source/llms/custom-pyfunc-for-llms/notebooks/custom-pyfunc-advanced-llm.ipynb
  docs/source/llms/index.rst
  docs/source/llms/sentence-transformers/guide/index.rst
  docs/source/llms/sentence-transformers/index.rst
  docs/source/llms/sentence-transformers/tutorials/paraphrase-mining/paraphrase-mining-sentence-transformers.ipynb
  docs/source/llms/sentence-transformers/tutorials/quickstart/sentence-transformers-quickstart.ipynb
  docs/source/llms/sentence-transformers/tutorials/semantic-search/semantic-search-sentence-transformers.ipynb
  docs/source/llms/sentence-transformers/tutorials/semantic-similarity/semantic-similarity-sentence-transformers.ipynb
Labels: area/docs, rn/documentation

#10559 Pin sphinx-tabs
  requirements/doc-min-requirements.txt
Labels: rn/none

#10550 Update `docs/source/llms/deployments/index.rst`
  docs/source/llms/deployments/index.rst
Labels: rn/none

#10551 Update `docs/source/llms/index.rst`
  docs/source/llms/index.rst
Labels: rn/none, gateway-migration

#10554 Use `MLFLOW_DEPLOYMENTS_TARGET` in `gateway_proxy_handler`
  dev/server.py
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, gateway-migration

#10552 Update `docs/source/llms/prompt-engineering/index.rst`
  docs/source/llms/prompt-engineering/index.rst
Labels: rn/none, gateway-migration

#10565 Fix completions params
  docs/source/llms/deployments/index.rst
  mlflow/gateway/schemas/completions.py
Labels: rn/none

#10566 Fix incorrect Embeddings param: `text` -> `input`
  docs/source/llms/deployments/index.rst
  mlflow/gateway/schemas/embeddings.py
Labels: rn/none

#10569 Replace `candidates` with `choices`
  mlflow/gateway/providers/mlflow.py
  mlflow/metrics/genai/genai_metric.py
  mlflow/metrics/genai/model_utils.py
  tests/evaluate/test_default_evaluator.py
  tests/gateway/providers/test_mlflow.py
  tests/metrics/genai/test_genai_metrics.py
  tests/metrics/genai/test_model_utils.py
Labels: rn/none, gateway-migration

#10568 More gateway replacements
  docs/source/index.rst
  docs/source/introduction/index.rst
Labels: rn/none, gateway-migration

#10560 Add instructions in flavor documentation for Azure OpenAI
  docs/source/models.rst
Labels: area/docs, rn/documentation

#10570 [Docs] Updating the docs for prompt engineering with MLflow deployment
  docs/source/_static/images/prompt_modal_1.png
  docs/source/llms/prompt-engineering/index.rst
Labels: area/docs, rn/documentation

#10576 Gateway anthropic small fix for "n" parameter
  mlflow/gateway/providers/anthropic.py
  tests/gateway/providers/test_anthropic.py
Labels: rn/none, area/gateway

#10561 Fix example links
  docs/source/llms/index.rst
Labels: rn/none, gateway-migration

#10585 Validate path in `HttpArtifactRepository.list_artifacts`
  mlflow/server/handlers.py
  mlflow/store/artifact/http_artifact_repo.py
  mlflow/utils/uri.py
  tests/store/artifact/test_http_artifact_repo.py
Labels: rn/none

#10557 fix best_estimator_params bug
  mlflow/recipes/steps/train.py
  tests/recipes/test_train_step.py
Labels: rn/none, integrations/databricks, area/recipes

#10590 Update index.rst
  docs/source/auth/index.rst
Labels: area/docs, rn/documentation

#10344 Improve the code of quickstart 2 - hyperparam search
  docs/source/getting-started/quickstart-2/index.rst
  tests/tensorflow/save_keras_model.py
Labels: rn/documentation

#10577 Support completions endpoints
  mlflow/metrics/genai/genai_metric.py
  mlflow/metrics/genai/model_utils.py
  mlflow/metrics/genai/prompts/v1.py
  tests/evaluate/test_default_evaluator.py
  tests/metrics/genai/test_genai_metrics.py
  tests/metrics/genai/test_model_utils.py
Labels: rn/none

#10498 Update `docs/source/llms/gateway/migration.rst`
  docs/source/llms/deployments/index.rst
  docs/source/llms/gateway/deprecation.rst
  docs/source/llms/gateway/index.rst
  docs/source/llms/gateway/migration.rst
  mlflow/gateway/__init__.py
  mlflow/gateway/utils.py
Labels: rn/none, gateway-migration

#10586 Support saving torch_dtype for transformers with components logging
  mlflow/transformers/__init__.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/feature

#10593 Update quickstart quides
  docs/source/llms/deployments/guides/step1-create-deployments.rst
  docs/source/llms/deployments/guides/step2-query-deployments.rst
Labels: rn/none, gateway-migration

#10595 Re-enable the ci for docs change
  .github/workflows/gateway.yml
  .github/workflows/master.yml
  .github/workflows/r.yml
  .github/workflows/recipe.yml
Labels: rn/none, area/build

#10398 Add quickstart for Tensorflow
  docs/source/deep-learning/index.rst
  docs/source/deep-learning/tensorflow/index.rst
  docs/source/deep-learning/tensorflow/quickstart/quickstart_tensorflow.ipynb
  requirements/doc-requirements.txt
Labels: rn/documentation

#10567 Fix mobile layout for MLflow Tracking page
  docs/source/tracking.rst
  docs/theme/mlflow/layout.html
  docs/theme/mlflow/static/css/mobile.css
  docs/theme/mlflow/static/css/tabs.css
Labels: area/docs, rn/none

#10521 Support runnables in langchain
  .github/workflows/cross-version-tests.yml
  mlflow/langchain/__init__.py
  mlflow/langchain/api_request_parallel_processor.py
  mlflow/langchain/retriever_chain.py
  mlflow/langchain/runnables.py
  mlflow/langchain/utils.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/feature, enable-dev-tests

#10519 Refactor: move tests cases to pytest in SQLAlchemy test suite [ver#4]
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#10581 Replace make_response with jsonify
  mlflow/server/auth/__init__.py
Labels: rn/none, area/server-infra

#10612 remove file: geez.md
  geez.md
Labels: rn/none

#10611 Support saving/loading RunnableBranch
  mlflow/langchain/runnables.py
  mlflow/langchain/utils.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/feature

#10505 Support Scala 2.13 in mlflow-spark
  dev/setup-spark-datasource-autologging.sh
  docs/source/tracking/autolog.rst
  mlflow/_spark_autologging.py
  mlflow/java/pom.xml
  mlflow/java/scoring/pom.xml
  mlflow/java/spark/pom.xml
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/DatasourceAttributeExtractor.scala
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/MlflowAutologEventPublisher.scala
  mlflow/java/spark/src/test/scala/org/mlflow/spark/autologging/ReflectionUtilsSuite.scala
  mlflow/java/spark/src/test/scala/org/mlflow/spark/autologging/SparkAutologgingIntegrationSuite.scala
  mlflow/ml-package-versions.yml
  mlflow/spark/__init__.py
  tests/spark/autologging/conftest.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging.py
  tests/spark/autologging/utils.py
Labels: rn/none, language/java, area/tracking, enable-dev-tests

#10607 Fix for openai >= 1.0.0
  mlflow/metrics/genai/model_utils.py
  mlflow/openai/__init__.py
  mlflow/openai/api_request_parallel_processor.py
  mlflow/openai/utils.py
  tests/metrics/genai/test_model_utils.py
Labels: rn/none

#10613 Handle multiple optimizers in PyTorch Lightning step autologging
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_lightning_autolog.py
  tests/pytorch/iris.py
  tests/pytorch/test_pytorch_autolog.py
Labels: rn/bug-fix, area/tracking

#10605 Support extra env vars in spark udf
  mlflow/pyfunc/__init__.py
  mlflow/utils/_spark_utils.py
  tests/pyfunc/test_spark.py
Labels: rn/feature

#10615 Openai flavor for 0.x works with requests.post
  mlflow/openai/__init__.py
  mlflow/openai/utils.py
Labels: rn/none

#10619 Fix test requirements CI
  .github/workflows/requirements.yml
Labels: rn/none

#10481 Google Docstring Conversion Batch
  mlflow/openai/__init__.py
  mlflow/openai/api_request_parallel_processor.py
  mlflow/openai/utils.py
  mlflow/paddle/__init__.py
  mlflow/paddle/_paddle_autolog.py
  mlflow/pmdarima/__init__.py
  mlflow/prophet/__init__.py
Labels: area/docs, rn/none

#10625 fix transformers notebooks
  docs/source/llms/custom-pyfunc-for-llms/notebooks/custom-pyfunc-advanced-llm.ipynb
  docs/source/llms/sentence-transformers/tutorials/paraphrase-mining/paraphrase-mining-sentence-transformers.ipynb
  docs/source/llms/sentence-transformers/tutorials/quickstart/sentence-transformers-quickstart.ipynb
  docs/source/llms/sentence-transformers/tutorials/semantic-search/semantic-search-sentence-transformers.ipynb
  docs/source/llms/sentence-transformers/tutorials/semantic-similarity/semantic-similarity-sentence-transformers.ipynb
  docs/source/llms/transformers/tutorials/audio-transcription/whisper.ipynb
  docs/source/llms/transformers/tutorials/conversational/conversational-model.ipynb
  docs/source/llms/transformers/tutorials/fine-tuning/transformers-fine-tuning.ipynb
  docs/source/llms/transformers/tutorials/text-generation/text-generation.ipynb
  docs/source/llms/transformers/tutorials/translation/component-translation.ipynb
Labels: area/docs, rn/none

#10626 Revert Changes to PythonModel that introduced loading issues
  mlflow/models/flavor_backend.py
  mlflow/projects/backend/abstract_backend.py
  mlflow/pyfunc/model.py
  mlflow/store/artifact/artifact_repo.py
  mlflow/store/artifact/unity_catalog_models_artifact_repo.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/base_rest_store.py
  mlflow/store/tracking/abstract_store.py
  mlflow/tracking/context/abstract_context.py
  mlflow/tracking/default_experiment/abstract_context.py
  mlflow/tracking/registry.py
  mlflow/tracking/request_header/abstract_request_header_provider.py
  mlflow/utils/model_utils.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_pyfunc_model_config.py
Labels: rn/bug-fix, area/models

#10629 Add backward compat tests
  tests/pyfunc/test_backward_compatibility.py
  tests/resources/pyfunc_models/2.7.1/MLmodel
  tests/resources/pyfunc_models/2.7.1/conda.yaml
  tests/resources/pyfunc_models/2.7.1/python_env.yaml
  tests/resources/pyfunc_models/2.7.1/python_model.pkl
  tests/resources/pyfunc_models/2.7.1/requirements.txt
  tests/resources/pyfunc_models/2.8.1/MLmodel
  tests/resources/pyfunc_models/2.8.1/conda.yaml
  tests/resources/pyfunc_models/2.8.1/python_env.yaml
  tests/resources/pyfunc_models/2.8.1/python_model.pkl
  tests/resources/pyfunc_models/2.8.1/requirements.txt
  tests/resources/pyfunc_models/README.md
Labels: rn/none, area/build

#10609 Refactor: move tests cases to pytest in SQLAlchemy test suite [ver#5]
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#10641 Reject path containing `#` or `%23`
  mlflow/utils/uri.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#10638 Improve `is_local_uri`
  mlflow/utils/uri.py
  tests/utils/test_uri.py
Labels: rn/none

#10643 Remove the temporary test for regression fix validation
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/none, area/models

#10636 Fix pyfunc signature inference from type hints
  mlflow/models/signature.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/none

#10654 Run `pre-commit install` before running `pre-commit run prettier` in autoformat workflow
  .github/workflows/autoformat.yml
  .github/workflows/lint.yml
  .pre-commit-config.yaml
Labels: rn/none

#10655 Add env variable to disable redirects
  mlflow/environment_variables.py
  mlflow/utils/request_utils.py
  tests/projects/test_databricks.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/store/tracking/test_rest_store.py
  tests/utils/test_request_utils.py
  tests/utils/test_rest_utils.py
Labels: rn/feature, area/server-infra

#10647 Fix for windows traversal attack
  mlflow/data/http_dataset_source.py
  tests/data/test_http_dataset_source.py
Labels: area/windows, rn/bug-fix, area/server-infra

#10660 Add endpoints to LLM evaluation docs
  docs/source/llms/llm-evaluate/index.rst
Labels: rn/documentation, area/tracking, area/deployments

#10662 Fix Tensorflow flavor docstring and style
  mlflow/tensorflow/__init__.py
Labels: area/docs, rn/documentation

#10464 Pass in sourceId tag in all cases
  mlflow/tracking/default_experiment/databricks_notebook_experiment_provider.py
  mlflow/tracking/default_experiment/registry.py
  tests/tracking/default_experiment/test_databricks_notebook_experiment_provider.py
Labels: rn/none

#10653 Disable '..' in query string for artifact URI
  mlflow/server/handlers.py
  mlflow/utils/uri.py
  tests/utils/test_uri.py
Labels: rn/bug-fix, area/artifacts

#10665 Fix link
  docs/source/llms/gateway/migration.rst
Labels: rn/none

#10667 Install pre-commit before running it
  .github/workflows/autoformat.yml
Labels: rn/none

#10672 Revert "Add env variable to disable redirects (#10655)"
  mlflow/environment_variables.py
  mlflow/utils/request_utils.py
  tests/projects/test_databricks.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/store/tracking/test_rest_store.py
  tests/utils/test_request_utils.py
  tests/utils/test_rest_utils.py
Labels: rn/none, area/server-infra

#10623 Feature/non interactive databricks login
  docs/source/getting-started/tracking-server-overview/index.rst
  mlflow/utils/credentials.py
  tests/utils/test_credentials.py
Labels: rn/feature, integrations/databricks

#10603 Support for OCR jars and minor refactor for defining wheel URLS
  mlflow/johnsnowlabs/__init__.py
Labels: rn/feature, area/models

#10657 Apply `os.path.basename` before `.` or `..` check in `FTPArtifactRepository`
  mlflow/store/artifact/ftp_artifact_repo.py
  tests/store/artifact/test_ftp_artifact_repo.py
Labels: rn/none

#10639 Refactor: move tests cases to pytest in SQLAlchemy test suite [ver#6]
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#10648 Make MPU / MPD chunk size configurable via environment variables
  mlflow/environment_variables.py
  mlflow/store/artifact/azure_data_lake_artifact_repo.py
  mlflow/store/artifact/cloud_artifact_repo.py
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/store/artifact/optimized_s3_artifact_repo.py
  tests/store/artifact/test_azure_data_lake_artifact_repo.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/store/artifact/test_databricks_models_artifact_repo.py
  tests/store/artifact/test_optimized_s3_artifact_repo.py
Labels: rn/none

#10646 Add Tensorflow landing page
  docs/source/_static/images/deep-learning/tensorflow/guide/tensorflow-model-signature.png
  docs/source/deep-learning/index.rst
  docs/source/deep-learning/tensorflow/guide/index.rst
  docs/source/deep-learning/tensorflow/index.rst
  docs/source/python_api/mlflow.tensorflow.rst
  docs/source/python_api/mlflow.types.rst
Labels: area/docs, rn/documentation

#10676 Add sandboxed jinja2 loader for yaml rendering
  mlflow/utils/file_utils.py
Labels: rn/bug-fix, area/server-infra

#10666 Use validated path after path validation
  mlflow/server/handlers.py
  mlflow/store/artifact/http_artifact_repo.py
  mlflow/utils/uri.py
Labels: rn/none

#10661 Adding Notebook for RAG Blog
  docs/source/llms/rag/index.rst
  docs/source/llms/rag/notebooks/index.rst
  docs/source/llms/rag/notebooks/mlflow-e2e-evaluation.ipynb
Labels: area/docs, rn/documentation

#10673 Add env var to disable redirects again
  mlflow/environment_variables.py
  mlflow/utils/request_utils.py
  tests/projects/test_databricks.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/store/tracking/test_rest_store.py
  tests/utils/test_request_utils.py
  tests/utils/test_rest_utils.py
Labels: rn/feature, area/server-infra

#10677 Fix ImportError in new langchain version
  mlflow/langchain/runnables.py
Labels: rn/none, enable-dev-tests

#10473 Create `mlflow.deployments.openai`
  mlflow/deployments/__init__.py
  mlflow/deployments/openai/__init__.py
  mlflow/langchain/__init__.py
  mlflow/metrics/genai/model_utils.py
  mlflow/openai/__init__.py
  mlflow/openai/api_request_parallel_processor.py
  mlflow/utils/openai_utils.py
  requirements/gateway-requirements.txt
  requirements/gateway-requirements.yaml
  setup.py
  tests/deployments/openai/test_openai.py
  tests/langchain/test_langchain_model_export.py
  tests/openai/test_openai_model_export.py
Labels: rn/feature

#10674 Fix tests
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/spark/test_spark_model_export.py
Labels: rn/none, enable-dev-tests

#10692 Disable openai dev test
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#10691 Use Python 3.9 to test with scikit-learn dev version
  .github/workflows/cross-version-tests.yml
Labels: rn/none, area/build, enable-dev-tests

#10659 Write eval results to delta
  .github/workflows/master.yml
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator_delta.py
Labels: rn/none, area/tracking

#10680 Update DBFS tests with asserts on base network call
  tests/store/artifact/test_dbfs_rest_artifact_repo.py
Labels: rn/none, area/build

#10696 Fix version check for Tensorflow nightly
  mlflow/tensorflow/__init__.py
Labels: rn/none, area/build

#10622 OpenAI Flavor landing page and intro notebooks
  docs/source/_static/images/tutorials/llms/RLHF-architecture.png
  docs/source/_static/images/tutorials/llms/prompt-engineering.png
  docs/source/index.rst
  docs/source/llms/index.rst
  docs/source/llms/openai/guide/index.rst
  docs/source/llms/openai/index.rst
  docs/source/llms/openai/notebooks/openai-chat-completions.ipynb
  docs/source/llms/openai/notebooks/openai-quickstart.ipynb
  docs/source/models.rst
Labels: area/docs, rn/documentation

#10663 Add Mentions to CE
  docs/source/_static/images/tutorials/introductory/community-edition-main.png
  docs/source/_static/images/tutorials/introductory/import-notebook-into-ce.png
  docs/source/_static/images/tutorials/introductory/mlflow-ui-in-ce.png
  docs/source/deep-learning/index.rst
  docs/source/getting-started/index.rst
  docs/source/getting-started/intro-quickstart/index.rst
  docs/source/getting-started/intro-quickstart/notebooks/tracking_quickstart.ipynb
  docs/source/getting-started/logging-first-model/index.rst
  docs/source/getting-started/logging-first-model/notebooks/logging-first-model.ipynb
  docs/source/getting-started/logging-first-model/step1-tracking-server.rst
  docs/source/getting-started/quickstart-2/index.rst
  docs/source/getting-started/running-notebooks/index.rst
  docs/source/traditional-ml/hyperparameter-tuning-with-child-runs/notebooks/hyperparameter-tuning-with-child-runs.ipynb
Labels: area/docs, rn/documentation

#10682 add log_model example to sentence_transformers
  mlflow/sentence_transformers/__init__.py
Labels: area/docs, rn/none

#10707 Trigger CI checks when PR is marked as ready for review
  .github/workflows/cross-version-tests.yml
  .github/workflows/deployments.yml
  .github/workflows/devcontainer.yml
  .github/workflows/examples.yml
  .github/workflows/gateway.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/master.yml
  .github/workflows/protect.yml
  .github/workflows/protos.yml
  .github/workflows/r.yml
  .github/workflows/recipe.yml
  .github/workflows/release-note.yml
  .github/workflows/requirements.yml
  .github/workflows/test-package-build.yml
Labels: rn/none

#10712 Improve protect job failure message
  .github/workflows/protect.js
Labels: rn/none

#10717 Refactor PyTorch flavor docstring and code examples
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_pytorch_autolog.py
Labels: rn/none, area/server-infra

#10710 Fix cross vetsion test for tf-nightly
  mlflow/ml-package-versions.yml
  tests/tensorflow/test_keras_pyfunc_model_works_with_all_input_types.py
Labels: rn/none, area/build, enable-dev-tests

#9936 Objects and Array support in model signature
  docs/source/conf.py
  docs/source/models.rst
  examples/spark_udf/structs_and_arrays.py
  mlflow/langchain/__init__.py
  mlflow/langchain/api_request_parallel_processor.py
  mlflow/models/signature.py
  mlflow/models/utils.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/scoring_server/__init__.py
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactLoggedModelView.tsx
  mlflow/server/js/src/model-registry/components/SchemaTable.test.tsx
  mlflow/server/js/src/model-registry/components/SchemaTable.tsx
  mlflow/server/js/src/model-registry/constants.tsx
  mlflow/server/js/src/model-registry/types/model-schema.ts
  mlflow/transformers/__init__.py
  mlflow/types/schema.py
  mlflow/types/utils.py
  mlflow/utils/proto_json_utils.py
  tests/langchain/test_langchain_model_export.py
  tests/lightgbm/test_lightgbm_autolog.py
  tests/models/test_model_input_examples.py
  tests/models/test_signature.py
  tests/models/test_utils.py
  tests/openai/test_openai_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
  tests/pyfunc/test_scoring_server.py
  tests/pyfunc/test_spark.py
  tests/sentence_transformers/test_sentence_transformers_model_export.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
  tests/spark/test_spark_model_export.py
  tests/tracking/fluent/test_fluent.py
  tests/tracking/test_rest_tracking.py
  tests/transformers/test_transformers_model_export.py
  tests/types/test_schema.py
  tests/utils/test_proto_json_utils.py
  tests/xgboost/test_xgboost_autolog.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/feature, enable-dev-tests

#10713 Add graphql proto annotation into databricks.proto
  mlflow/java/client/src/main/java/com/databricks/api/proto/databricks/Databricks.java
  mlflow/protos/databricks.proto
  mlflow/protos/databricks_pb2.py
Labels: rn/none, area/build

#10715 Add flush functionality to async logging
  mlflow/__init__.py
  mlflow/store/tracking/abstract_store.py
  mlflow/tracking/fluent.py
  mlflow/utils/async_logging/async_logging_queue.py
  tests/tracking/fluent/test_fluent.py
  tests/utils/test_async_logging_queue.py
Labels: rn/feature, area/tracking

#10703 Remove scala-2.13 profile from mlflow-spark pom.xml
  mlflow/java/spark/pom.xml
Labels: rn/none, area/tracking

#10724 Pin pandas to < 2.0 for pyspark 3.3.x
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#10695 Fix `sentence_transformers` failure
  mlflow/sentence_transformers/__init__.py
  mlflow/store/artifact/s3_artifact_repo.py
Labels: rn/none, enable-dev-tests

#10675 Refactor Deployment page and add local / SageMaker / Azure / Databricks guides
  docs/source/_static/images/deployment/mlflow-deployment-overview.png
  docs/source/_static/images/logos/amazon-sagemaker-logo.png
  docs/source/_static/images/logos/azure-ml-logo.png
  docs/source/_static/images/logos/databricks-logo.png
  docs/source/_static/images/logos/flask-logo.png
  docs/source/_static/images/logos/kubernetes-logo.png
  docs/source/_static/images/logos/ray-serve-logo.svg
  docs/source/_static/images/logos/seldon-mlserver-logo.png
  docs/source/deployment/deploy-model-locally.rst
  docs/source/deployment/deploy-model-to-kubernetes/index.rst
  docs/source/deployment/deploy-model-to-ray-serve.rst
  docs/source/deployment/deploy-model-to-sagemaker.rst
  docs/source/deployment/index.rst
  docs/source/getting-started/quickstart-1/index.rst
  docs/source/models.rst
  docs/theme/mlflow/static/css/simple-cards.css
Labels: area/docs, rn/none

#10725 Do not emit warnings for `MLflow` and `Databricks` llms
  dev/mlflow-typo.sh
  mlflow/langchain/utils.py
Labels: rn/none

#9872 Johnsnowlabs-Flavor: disable mlflowdbfs
  mlflow/johnsnowlabs/__init__.py
Labels: rn/bug-fix, area/model-registry, area/models, integrations/databricks

#10708 Added protos for managed catalog
  dev/generate-protos.sh
  mlflow/protos/databricks_managed_catalog_messages.proto
  mlflow/protos/databricks_managed_catalog_messages_pb2.py
  mlflow/protos/databricks_managed_catalog_service.proto
  mlflow/protos/databricks_managed_catalog_service_pb2.py
Labels: rn/none

#10700 Add additional tutorials to OpenAI flavor docs
  docs/source/_static/images/tutorials/llms/openai-tutorials-explanation.png
  docs/source/llms/index.rst
  docs/source/llms/openai/index.rst
  docs/source/llms/openai/notebooks/openai-chat-completions.ipynb
  docs/source/llms/openai/notebooks/openai-code-helper.ipynb
  docs/source/llms/openai/notebooks/openai-embeddings-generation.ipynb
Labels: area/docs, rn/documentation

#10687 Add PyTorch landing page and guide
  docs/source/_static/images/deep-learning/pytorch/guide/pytorch-guide-basic-example-ui.png
  docs/source/_static/images/deep-learning/pytorch/guide/pytorch-guide-basic-saving.png
  docs/source/_static/images/deep-learning/pytorch/guide/pytorch-guide-model-signature.png
  docs/source/deep-learning/index.rst
  docs/source/deep-learning/pytorch/guide/index.rst
  docs/source/deep-learning/pytorch/index.rst
Labels: area/docs, rn/documentation

#10733 Apply pandas pinning to spark autolog test as well
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#10734 Remove `mlflow.llm.log_predictions`
  mlflow/llm/__init__.py
  mlflow/tracking/llm_utils.py
  tests/tracking/test_llm_utils.py
Labels: rn/breaking-change

#10727 Support nullable boolean column in schema enforcement
  mlflow/models/utils.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
Labels: rn/none

#10726 Refactor deployment docs and tutorials
  docs/source/_static/images/deployment/hyper-parameter-tuning-ui.png
  docs/source/_static/images/deployment/mlflow-deployment-overview.png
  docs/source/_static/images/deployment/tracking-ui-default.png
  docs/source/_static/images/logos/amazon-sagemaker-logo.png
  docs/source/_static/images/logos/azure-ml-logo.png
  docs/source/_static/images/logos/databricks-logo.png
  docs/source/_static/images/logos/flask-logo.png
  docs/source/_static/images/logos/kubernetes-logo.png
  docs/source/_static/images/logos/ray-serve-logo.svg
  docs/source/_static/images/logos/seldon-mlserver-logo.png
  docs/source/deployment/deploy-model-locally.rst
  docs/source/deployment/deploy-model-to-kubernetes/index.rst
  docs/source/deployment/deploy-model-to-kubernetes/tutorial.rst
  docs/source/deployment/deploy-model-to-sagemaker.rst
  docs/source/deployment/index.rst
  docs/source/getting-started/quickstart-1/index.rst
  docs/source/models.rst
  docs/source/tutorials-and-examples/index.rst
  docs/theme/mlflow/static/css/simple-cards.css
  mlflow/utils/docstring_utils.py
Labels: area/docs, rn/documentation

#10538 initpy and test_transformers_model_export
  mlflow/transformers/__init__.py
  tests/transformers/test_transformers_model_export.py
Labels: area/windows, rn/feature, rn/bug-fix, integrations/azure

#10723 Fix error message for missing "targets" column
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/none

#10714 Add basic graphql handler
  mlflow/server/graphql/__init__.py
  mlflow/server/graphql/graphql_schema_extensions.py
  mlflow/server/handlers.py
  requirements/core-requirements.txt
  requirements/core-requirements.yaml
  requirements/skinny-requirements.txt
  requirements/skinny-requirements.yaml
  requirements/test-requirements.txt
  tests/tracking/test_rest_tracking.py
Labels: rn/none, area/uiux, autoformat

#10749 Fix huggingface dataset test
  tests/data/test_huggingface_dataset_and_source.py
Labels: rn/none, area/build

#10750 Fix spark dev cross test
  dev/set-mlflow-spark-scala-version.py
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build, enable-dev-tests

#10751 Refactor args for `subprocess.run`
  mlflow/models/wheeled_model.py
Labels: rn/none

#10736 Some improvements to deep learning landing page
  docs/source/deep-learning/index.rst
Labels: area/docs, rn/documentation

#10742 Allow mlflow model serving to support arbitrary dict inputs
  mlflow/pyfunc/scoring_server/__init__.py
  tests/pyfunc/test_scoring_server.py
Labels: rn/feature, area/scoring

#10737 Add quickstart for pytorch flavor
  docs/source/deep-learning/pytorch/index.rst
  docs/source/deep-learning/pytorch/quickstart/pytorch_quickstart.ipynb
Labels: rn/documentation

#10755 Make pytorch model supporting model load-time param 'device'
  mlflow/pytorch/__init__.py
  tests/pytorch/test_pytorch_model_export.py
Labels: rn/none

#10757 Fix paddle flavor for paddle 2.6.0
  mlflow/paddle/__init__.py
  tests/paddle/test_paddle_model_export.py
Labels: rn/bug-fix, area/models, area/build

#10763 Move doctor utility to utils/ directory
  mlflow/__init__.py
  mlflow/utils/doctor.py
  tests/utils/test_doctor.py
Labels: rn/none, area/tracking
