Repository mlflow/mlflow, pull requests merged in 2023-02, with the labels that each got.

#7764 Warn if PR doesn't appear to have been filed using PR template
  .github/workflows/advice.js
Labels: rn/none

#7756 Fix test failures in SQLAlchemy 2.0
  .github/workflows/master.yml
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  requirements/core-requirements.txt
  requirements/core-requirements.yaml
  tests/conftest.py
  tests/store/db/test_utils.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/_model_registry/test_utils.py
  tests/tracking/_tracking_service/test_utils.py
  tests/tracking/integration_test_utils.py
  tests/tracking/test_model_registry.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#7763 [Bug-fix][Recipes] Updating the run_name API to be run_name_prefix
  mlflow/recipes/utils/tracking.py
  tests/recipes/test_tracking_utils.py
Labels: rn/bug-fix, area/recipes

#7769 Fix flakey `tests/tracking/test_rest_tracking.py::test_search_experiments`
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#7771 converted unittest to pytest for run_status
  tests/entities/test_run_status.py
Labels: rn/none

#7772 Run tests for SQLAlchemyStore in SQLAlchemy < 2.0
  .github/workflows/master.yml
Labels: rn/none

#7773 Do not truncate local variable values in pytest traceback
  pytest.ini
Labels: rn/none

#7775 Fetch branch from `mlflow/mlflow` in autoformat workflow
  .github/workflows/autoformat.yml
Labels: rn/none

#7776 Update black error messages only when `.black.log` exists
  .github/workflows/master.yml
Labels: rn/none

#7765 Make additional build script changes to ensure that UC model registry protos build properly
  dev/generate-protos.sh
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/protos/databricks_uc_registry_service.proto
  mlflow/protos/databricks_uc_registry_service_pb2.py
Labels: rn/none, area/model-registry, area/build

#7787 Pin SQLAlchemy < 2 in PyTorch examples
  examples/pytorch/AxHyperOptimizationPTL/conda.yaml
  examples/pytorch/AxHyperOptimizationPTL/python_env.yaml
  examples/pytorch/IterativePruning/conda.yaml
  examples/pytorch/IterativePruning/python_env.yaml
Labels: rn/none, area/examples

#7788 Use SQLAlchemy 1.x for testing some older TensorFlow versions
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#7781 Allow specifying `model_format` when autologging xgboost models
  mlflow/sklearn/__init__.py
  mlflow/xgboost/__init__.py
  tests/xgboost/test_xgboost_autolog.py
Labels: rn/feature, area/tracking

#7780 Migrate model-registry `RestStore` to pytest
  tests/helper_functions.py
  tests/store/model_registry/test_rest_store.py
Labels: rn/none

#7791 Fix pydoc compatiblility with PYTHONOPTIMIZE=2
  mlflow/pytorch/__init__.py
  mlflow/statsmodels.py
  mlflow/utils/annotations.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/docstring_utils.py
Labels: rn/bug-fix, area/build

#7792 Fix lightgbm autologging sklearn examples failure
  .github/workflows/examples.yml
  mlflow/sklearn/__init__.py
Labels: rn/none, area/examples, area/tracking, only-latest

#7753 6099 add spacy pyfunc example
  docs/source/models.rst
Labels: area/docs, rn/none, area/examples

#7783 Add env variable to let users set Azure artifact upload timeout
  docs/source/tracking.rst
  mlflow/environment_variables.py
  mlflow/store/artifact/azure_blob_artifact_repo.py
  mlflow/store/artifact/gcs_artifact_repo.py
Labels: rn/feature, area/tracking, integrations/azure

#7803 Add xgboost pyfunc example
  docs/source/models.rst
Labels: area/docs, rn/none

#7793 Fix: Update run-test-container.sh to run on arm64
  dev/Dockerfile.test
  dev/run-test-container.sh
Labels: rn/none, area/build

#7812 Use SQLAlchemy < 2 for additional TensorFlow cross version tests
  mlflow/ml-package-versions.yml
Labels: rn/none, area/models

#7811 Add missing whitespace in multiline strings
  examples/flower_classifier/train.py
  examples/hyperparam/train.py
  mlflow/cli.py
  mlflow/deployments/base.py
  mlflow/deployments/cli.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/pmdarima.py
  mlflow/recipes/recipe.py
  mlflow/recipes/steps/ingest/datasets.py
  mlflow/sagemaker/__init__.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tensorflow/__init__.py
  mlflow/tracking/client.py
  mlflow/types/utils.py
  mlflow/utils/process.py
  tests/helper_functions.py
  tests/pytorch/test_pytorch_autolog.py
  tests/store/tracking/test_file_store.py
  tests/tensorflow/test_tensorflow2_autolog.py
  tests/utils/test_process_utils.py
  tests/utils/test_resources/dummy_package/operator.py
Labels: rn/none

#7778 Migrate tracking `FileStore` to pytest: Part 1
  tests/store/tracking/test_file_store.py
Labels: rn/none

#7823 Fix pip package installation
  dev/install-common-deps.sh
Labels: rn/none

#7824 Set `timeout-minutes` for GitHub Action workflows
  .github/workflows/advice.yml
  .github/workflows/autoformat.yml
  .github/workflows/closing-pr.yml
  .github/workflows/cross-version-tests.yml
  .github/workflows/dev-setup.yml
  .github/workflows/devcontainer.yml
  .github/workflows/examples.yml
  .github/workflows/labeling.yml
  .github/workflows/master.yml
  .github/workflows/preview-docs.yml
  .github/workflows/protos.yml
  .github/workflows/push-images.yml
  .github/workflows/r.yml
  .github/workflows/recipe-template.yml
  .github/workflows/recipe.yml
  .github/workflows/release-note-category.yml
  .github/workflows/requirements.yml
  .github/workflows/stale.yml
  .github/workflows/test-package-build.yml
Labels: rn/none

#7766 Add REST client for UC model registry and support for registered model CRUD
  mlflow/store/_unity_catalog/__init__.py
  mlflow/store/_unity_catalog/registry/__init__.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/_unity_catalog/registry/utils.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/base_rest_store.py
  mlflow/store/model_registry/rest_store.py
  tests/helper_functions.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/none, area/model-registry

#7815 Optimizing the performance for custom split method
  mlflow/recipes/steps/split.py
  tests/recipes/test_split_step.py
Labels: rn/bug-fix, area/recipes

#7808 Save ONNX model external data True to overcome 2GB limit.
  mlflow/onnx.py
  tests/onnx/test_onnx_model_export.py
Labels: rn/feature, area/models

#7826 Use `ubuntu-latest` in flavors job
  .github/workflows/master.yml
Labels: rn/none

#7825 Deflake tests in `tests/store/tracking/test_sqlalchemy_store.py`
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#7828 Fix pip package installation
  dev/dev-env-setup.sh
  requirements/dev-requirements.txt
Labels: rn/none

#7831 Migrate `h2o`, `shap`, and `paddle` flavors to cross-version tests
  dev/run-python-flavor-tests.sh
  mlflow/ml-package-versions.yml
Labels: rn/none

#7818 bugfix-7801 Fixing validation bugs in experiments, models modals
  mlflow/server/js/src/common/components/EditableTagsTableView.js
  mlflow/server/js/src/common/forms/validations.js
  mlflow/server/js/src/common/forms/validations.test.js
  mlflow/server/js/src/experiment-tracking/components/modals/CreateExperimentForm.js
Labels: rn/bug-fix, area/uiux

#7834 Remove `distutils` in `setup.py`
  setup.py
Labels: rn/none

#7836 Upgrade supported version of LightGBM
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
Labels: rn/none

#7822 Fix tensorflow model cross version tests
  tests/tensorflow/mlflow-128-tf-23-env.yaml
  tests/tensorflow/save_keras_model.py
  tests/tensorflow/save_tf_estimator_model.py
Labels: rn/none, area/build

#7837 Allow `actions/cache` step to fail
  .github/actions/cache-pip/action.yml
  .github/workflows/cross-version-tests.yml
  .github/workflows/r.yml
Labels: rn/none

#7830 Do not clean up `AGENT_TOOLSDIRECTORY`
  .github/workflows/examples.yml
  .github/workflows/master.yml
Labels: rn/none

#7838 Clean up requirements
  requirements/extra-ml-requirements.txt
  requirements/test-requirements.txt
  setup.py
Labels: rn/none

#7845 Run blacken-docs on code blocks in markdown files
  .pre-commit-config.yaml
  examples/lightgbm/lightgbm_sklearn/README.md
Labels: rn/none

#7847 Temporary fix for catboost dev test
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#7852 [Bug fix] Fixing inspect recipes by pinning the mermaid version
  mlflow/recipes/resources/recipe_dag_template.html
Labels: rn/bug-fix, area/recipes

#7849 [DOC-FIX] The scikit-learn API is supported
  docs/source/tracking.rst
Labels: rn/none

#7827 Added proper headers for artifacts downloads
  mlflow/server/handlers.py
  tests/server/test_handlers.py
  tests/tracking/test_mlflow_artifacts.py
Labels: rn/bug-fix, area/artifacts

#7767 Add support for UC model version CRUD
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/_unity_catalog/registry/utils.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/feature, area/model-registry

#7854 Ignore tensorboard import failure in pytorch autolog
  mlflow/ml-package-versions.yml
  mlflow/pytorch/__init__.py
Labels: rn/none

#7796 Add samples for mlflow autologging
  docs/source/tutorials-and-examples/index.rst
  examples/synapseml/autologging.md
  mlflow/pyspark/ml/__init__.py
  mlflow/pyspark/ml/log_model_allowlist.txt
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging_custom_allowlist.py
Labels: rn/none

#7863 Reserve 'databricks-uc' URI scheme in MLflow Python client
  mlflow/tracking/_model_registry/utils.py
  mlflow/tracking/registry.py
  mlflow/utils/uri.py
  tests/tracking/_model_registry/test_utils.py
Labels: rn/none

#7865 Add lightgbm pyfunc example
  docs/source/models.rst
Labels: area/docs, rn/none

#7859 Enhance S3 artifact repo to support specifying AWS credentials
  mlflow/store/artifact/s3_artifact_repo.py
  tests/store/artifact/test_s3_artifact_repo.py
Labels: rn/none

#7868 Fix pytorch-lightning dev test
  tests/pytorch/test_pytorch_autolog.py
Labels: rn/none, enable-dev-tests, only-latest

#7623 Introduce max_results, order_by and page_token arguments to MlflowClient.search_model_versions
  mlflow/java/client/src/main/java/org/mlflow/api/proto/ModelRegistry.java
  mlflow/protos/model_registry.proto
  mlflow/server/handlers.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/model_registry/__init__.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/model_registry/rest_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/client.py
  mlflow/utils/search_utils.py
  tests/server/test_handlers.py
  tests/store/model_registry/test_file_store.py
  tests/store/model_registry/test_rest_store.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/tracking/_model_registry/test_model_registry_client.py
  tests/tracking/test_model_registry.py
Labels: rn/feature, area/model-registry

#7872 Fix error message when the "databricks-uc" registry URI scheme is specified
  mlflow/tracking/_model_registry/utils.py
Labels: rn/none

#7871 Fix flaky `test_recipe_batch_dag_clean_step_works`
  tests/recipes/regression/v1/test_regression_pipeline_batch_scoring.py
Labels: rn/none

#7874 Use `strategy="ddp_spawn"` in `pytorch-lightning > 1.9.3`
  tests/pytorch/test_pytorch_autolog.py
Labels: rn/none, enable-dev-tests

#7862 Enhance GCS artifact repo to support passing custom client
  mlflow/store/artifact/gcs_artifact_repo.py
  tests/store/artifact/test_gcs_artifact_repo.py
Labels: rn/none

#7875 Fix flaky tests in `tests/tracking/test_model_registry.py`
  tests/tracking/test_model_registry.py
Labels: rn/none

#7883 Fix `test_spark_udf_autofills_no_arguments` for pyspark 3.4.0
  tests/pyfunc/test_spark.py
Labels: rn/none

#7858 Add internal-only ADLS artifact repo
  mlflow/store/artifact/azure_data_lake_artifact_repo.py
  requirements/test-requirements.txt
  tests/store/artifact/test_azure_data_lake_artifact_repo.py
Labels: rn/none

#7877 Migrate model registry `test_registered_model` to pytest
  tests/entities/model_registry/test_registered_model.py
Labels: rn/none

#7882 Fix typo
  mlflow/server/handlers.py
Labels: rn/none

#7861 Introduce artifact repo for models in UC
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/_unity_catalog/registry/utils.py
  mlflow/store/artifact/unity_catalog_models_artifact_repo.py
  mlflow/tracking/registry.py
  mlflow/utils/uri.py
  tests/store/artifact/test_unity_catalog_models_artifact_repo.py
  tests/utils/test_uri.py
Labels: rn/none

#7886 Make `validate_path_is_safe` more strict
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#7880 Implement `searchModelVersions()` API in Java client
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowClient.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowProtobufMapper.java
  mlflow/java/client/src/main/java/org/mlflow/tracking/ModelVersionsPage.java
  mlflow/java/client/src/test/java/org/mlflow/tracking/ModelRegistryMlflowClientTest.java
Labels: rn/feature, language/java, area/tracking

#7892 Prevent registered model name from containing path separator
  mlflow/store/model_registry/file_store.py
  mlflow/utils/file_utils.py
  tests/store/model_registry/test_file_store.py
Labels: rn/none

#7891 Apply `validate_path_is_safe` to `path` and `artifact_path` for `/mlflow-artifacts/` endpoints
  mlflow/server/handlers.py
Labels: rn/none

#7898 Fix: `TypeError: describe() got an unexpected keyword argument 'datetime_is_numeric'` in pandas 2.0.0rc0
  mlflow/recipes/cards/pandas_renderer.py
Labels: rn/none

#7895 Migrate `test_model_version.py` & `test_sqlalchemy_store.py` to pytest
  tests/entities/model_registry/test_model_version.py
  tests/store/model_registry/test_sqlalchemy_store.py
Labels: rn/none

#7896 Improve error message if user tries to set tracking URI to UC
  mlflow/tracking/_tracking_service/utils.py
  tests/tracking/_tracking_service/test_utils.py
Labels: rn/none

#7866 Clean cache python
  Dockerfile
Labels: rn/none

#7899 Replaces `np.dtype("datetime64")` and `np.datetime64` with `np.dtype("datetime64[ns]")` for pandas 2.0
  mlflow/models/utils.py
  mlflow/types/schema.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
Labels: rn/none

#7908 Disallow local source for model version
  mlflow/java/client/src/test/java/org/mlflow/tracking/ModelRegistryMlflowClientTest.java
  mlflow/server/handlers.py
  mlflow/utils/uri.py
  tests/server/test_handlers.py
  tests/tracking/test_model_registry.py
  tests/tracking/test_rest_tracking.py
  tests/utils/test_uri.py
Labels: rn/none

#7910 Increase supported pandas major version to 2
  requirements/core-requirements.txt
  requirements/core-requirements.yaml
Labels: rn/none, area/build
