Repository mlflow/mlflow, pull requests merged in 2023-09, with the labels that each got.

#9476 Add default value for artifact download_chunk function timeout
  mlflow/environment_variables.py
  mlflow/store/artifact/cloud_artifact_repo.py
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/utils/file_utils.py
  mlflow/utils/request_utils.py
Labels: rn/none

#9504 fix failing test with alembic 1.12.0
  tests/store/tracking/test_sqlalchemy_store_schema.py
Labels: rn/none

#9509 Creating util for creating prompt_template
  mlflow/metrics/__init__.py
  mlflow/metrics/utils/__init__.py
  mlflow/metrics/utils/prompt_template.py
  tests/metrics/utils/test_prompt_template.py
Labels: rn/none, area/tracking

#9354 CreatePromptlabRun API
  mlflow/_promptlab.py
  mlflow/server/__init__.py
  mlflow/server/handlers.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/utils/mlflow_tags.py
  mlflow/utils/promptlab_utils.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/test_rest_tracking.py
  tests/utils/test_promptlab_utils.py
Labels: rn/none, area/models, area/tracking

#9517 Move _create_promptlab_run_impl to promptlab_utils.py
  mlflow/server/handlers.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/utils/test_promptlab_utils.py
Labels: rn/none, area/tracking

#9505 Update MosaicML Chat to not throw exceptions when parsing
  mlflow/gateway/providers/mosaicml.py
  tests/gateway/providers/test_mosaicml.py
Labels: rn/none, area/gateway

#9506 Refactor MPD error handling
  mlflow/store/artifact/cloud_artifact_repo.py
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/utils/download_cloud_file_chunk.py
  mlflow/utils/file_utils.py
  mlflow/utils/request_utils.py
  tests/store/artifact/test_databricks_models_artifact_repo.py
Labels: rn/none

#9482 Add Multipart Upload API Interface
  mlflow/java/client/src/main/java/org/mlflow/api/proto/MlflowArtifacts.java
  mlflow/protos/mlflow_artifacts.proto
  mlflow/protos/mlflow_artifacts_pb2.py
Labels: rn/feature, area/artifacts

#9518 Re-resolve gateway credentials before each request
  mlflow/gateway/client.py
Labels: rn/bug-fix, area/gateway

#9524 Updated Giskard community plugin links in docs
  docs/source/models.rst
  docs/source/plugins.rst
Labels: area/docs, rn/documentation

#9500 [LLM Evaluate] Adding v1 grading prompt template
  mlflow/metrics/base.py
  mlflow/metrics/utils/prompt_template.py
  mlflow/metrics/utils/prompts/__init__.py
  mlflow/metrics/utils/prompts/v1.py
  tests/metrics/test_base.py
  tests/metrics/utils/prompts/test_v1.py
Labels: rn/none, area/tracking

#9520 Ignore array columns with enforcing ColSpec signature, instead of throwing
  mlflow/models/utils.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
Labels: rn/none, area/models

#9474 Improve error message for direct loads of Feature Store models
  mlflow/models/model.py
  mlflow/pyfunc/__init__.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/none, area/models

#9528 Rerun cross version tests
  .github/workflows/rerun.js
  .github/workflows/rerun.yml
Labels: rn/none

#9533 Create /upload-artifacts route
  mlflow/server/__init__.py
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, area/tracking

#9488 add type annotations to spark dataset
  docs/source/conf.py
  mlflow/data/spark_dataset.py
Labels: rn/none

#9540 Add trailing slash to gateway list routes docs
  docs/source/gateway/index.rst
Labels: rn/none, area/gateway

#9512 Remove old versions from ml-package-versions.yml
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#9536 Force sqlalchemy to render unobfuscated url
  mlflow/server/auth/db/utils.py
Labels: rn/none

#9542 Adding make_genai_metric api
  mlflow/metrics/__init__.py
  mlflow/metrics/utils/make_genai_metric.py
  tests/metrics/utils/test_make_genai_metric.py
Labels: rn/none, area/tracking

#9515 Move metric definitions to mlflow.metrics
  .github/workflows/master.yml
  docs/source/python_api/mlflow.metrics.rst
  mlflow/metrics/__init__.py
  mlflow/metrics/base.py
  mlflow/metrics/utils/metric_definitions.py
  tests/metrics/test_metric_definitions.py
Labels: rn/none

#9561 Ignore exit status of `blacken-docs` in autoformat workflow
  .github/workflows/autoformat.yml
Labels: rn/none

#9564 Ban built-in `eval`
  pyproject.toml
Labels: rn/none

#9489 Fix TF autolog for input sequence with sample weights
  mlflow/tensorflow/__init__.py
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/none, area/tracking

#9562 Minimize the use of `MLFLOW_AUTOMATION_TOKEN`
  .github/workflows/cancel.yml
  .github/workflows/preview-docs.yml
  .github/workflows/rerun.js
  .github/workflows/rerun.yml
  .github/workflows/stale.yml
Labels: rn/none

#9560 Disallow passing pandas series for params in infer_signature
  mlflow/types/utils.py
  tests/types/test_schema.py
Labels: rn/none

#9569 Free disk space in models job
  .github/workflows/master.yml
Labels: rn/none

#9567 fix docs pyfunc.log_model
  mlflow/pyfunc/__init__.py
Labels: area/docs, rn/documentation

#9565 Update "dtype" to "type" in ParamSpec dictionary representation
  mlflow/types/schema.py
  tests/types/test_schema.py
Labels: rn/none

#9546 Improve error message for multipart download
  mlflow/store/artifact/artifact_repo.py
  mlflow/store/artifact/cloud_artifact_repo.py
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/utils/download_cloud_file_chunk.py
  mlflow/utils/file_utils.py
  tests/store/artifact/test_databricks_models_artifact_repo.py
Labels: rn/none

#9570 Handle none for stop parameter
  mlflow/server/js/src/experiment-tracking/components/evaluation-artifacts-compare/EvaluationCreatePromptParameters.tsx
  mlflow/server/js/src/experiment-tracking/components/evaluation-artifacts-compare/hooks/usePromptEvaluationParameters.tsx
Labels: rn/none, area/uiux, area/tracking

#9538 Handle model_uri for scoring
  mlflow/gateway/providers/openai.py
  mlflow/metrics/base.py
  mlflow/metrics/utils/model_utils.py
  tests/metrics/utils/test_model_utils.py
Labels: rn/none, area/tracking, area/gateway

#9573 Fix missed signature params entry
  tests/models/test_signature.py
Labels: rn/none, area/build

#9572 Add aggregations to existing metrics
  mlflow/metrics/utils/metric_definitions.py
  tests/metrics/test_metric_definitions.py
Labels: rn/none

#9577 Use `testcode` directive and stop using `https://github.com/harupy/blacken-docs.git@test-code-block`
  docs/source/conf.py
  docs/source/testcode_block.py
  examples/evaluation/README.md
  examples/pytorch/CaptumExample/README.md
  examples/pytorch/MNIST/README.md
  mlflow/pyfunc/__init__.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/_tracking_service/utils.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  mlflow/tracking/llm_utils.py
  requirements/lint-requirements.txt
Labels: rn/none

#9556 Setup R2 Artifact Repo to use correct s3 endpoint by default
  mlflow/store/artifact/r2_artifact_repo.py
  mlflow/store/artifact/s3_artifact_repo.py
  tests/store/artifact/test_r2_artifact_repo.py
Labels: rn/none, area/artifacts

#9580 Fix `pytest.raises` match in `tests/pytorch/test_pytorch_model_export.py`
  tests/pytorch/test_pytorch_model_export.py
Labels: rn/none

#9581 Improve status badge links
  README.rst
Labels: rn/none

#9582 Fix flaky `test_search_experiments_filter_by_tag`
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#9583 Fix flakiness in `kill_child_processes`
  mlflow/gateway/utils.py
Labels: rn/none

#9584 Remove more useless assign
  mlflow/artifacts/__init__.py
  mlflow/azure/client.py
  mlflow/lightgbm.py
  mlflow/models/utils.py
  mlflow/onnx.py
  mlflow/openai/api_request_parallel_processor.py
  mlflow/projects/__init__.py
  mlflow/projects/databricks.py
  mlflow/recipes/cards/pandas_renderer.py
  mlflow/recipes/steps/ingest/__init__.py
  mlflow/recipes/steps/train.py
  mlflow/sagemaker/__init__.py
  mlflow/server/handlers.py
  mlflow/server/prometheus_exporter.py
  mlflow/statsmodels.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/tracking/fluent.py
  mlflow/transformers.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/autologging_utils/safety.py
  mlflow/utils/environment.py
  mlflow/utils/git_utils.py
  mlflow/utils/model_utils.py
  mlflow/utils/promptlab_utils.py
  mlflow/utils/search_utils.py
  mlflow/utils/uri.py
  mlflow/xgboost/__init__.py
  pylint_plugins/assign_checker.py
  tests/evaluate/test_evaluation.py
  tests/helper_functions.py
  tests/johnsnowlabs/test_johnsnowlabs_model_export.py
  tests/onnx/test_onnx_model_export.py
  tests/prophet/test_prophet_model_export.py
  tests/pyfunc/test_spark.py
  tests/pytorch/iris.py
  tests/pytorch/iris_data_module.py
  tests/pytorch/test_pytorch_model_export.py
  tests/recipes/test_train_step.py
  tests/sagemaker/mock/__init__.py
  tests/spark/autologging/utils.py
  tests/tensorflow/iris_data_utils.py
  tests/tensorflow/test_tensorflow2_autolog.py
  tests/tracking/integration_test_utils.py
Labels: rn/none, only-latest

#9586 Use `packaging.requirements.Requirement` instead of `pkg_resources.Requirement`
  mlflow/utils/requirements_utils.py
Labels: rn/none

#9588 Replace `pkg_resources.get_distribution` with `importlib_metadata.version`
  mlflow/utils/docstring_utils.py
Labels: rn/none

#9574 Reduce disk usage to avoid CI runner available disk space issues
  tests/models/test_cli.py
Labels: rn/none, area/build

#9593 Properly propagate constructor S3 endpoint URL in S3ArtifactRepository
  mlflow/store/artifact/s3_artifact_repo.py
  tests/store/artifact/test_r2_artifact_repo.py
Labels: rn/none, area/artifacts

#9590 Remove `pkg_resources.resource_filename`
  mlflow/_doctor.py
  mlflow/models/container/__init__.py
  mlflow/utils/requirements_utils.py
  pyproject.toml
Labels: rn/none

#9568 Docs for prompt engineering UI
  docs/source/_static/images/add_row.png
  docs/source/_static/images/add_row_modal.png
  docs/source/_static/images/duplicate_run.png
  docs/source/_static/images/eval_view_1.png
  docs/source/_static/images/evaluate_all.png
  docs/source/_static/images/evaluate_all_results.png
  docs/source/_static/images/evaluate_new_input.png
  docs/source/_static/images/experiment_page.png
  docs/source/_static/images/load_model.png
  docs/source/_static/images/new_run.png
  docs/source/_static/images/prompt_eng_run_page.png
  docs/source/_static/images/prompt_eng_table_view.png
  docs/source/_static/images/prompt_modal_1.png
  docs/source/_static/images/prompt_modal_2.png
  docs/source/_static/images/prompt_modal_3.png
  docs/source/_static/images/prompt_modal_4.png
  docs/source/_static/images/save_new_input.png
  docs/source/gateway/index.rst
  docs/source/index.rst
  docs/source/llms/prompt-engineering.rst
Labels: area/docs, rn/none

#9587 Use `importlib_metadata` in `mlflow doctor`
  mlflow/_doctor.py
Labels: rn/none

#9596 Update prompt-engineering.rst
  docs/source/llms/prompt-engineering.rst
Labels: area/docs, rn/documentation

#9597 Fix `Title underline too short`
  docs/source/llms/prompt-engineering.rst
Labels: rn/none

#9595 Retry `_is_available_on_pypi`
  tests/helper_functions.py
Labels: rn/none

#9602 Replace `sparkm` with `mlflow.spark` to avoid confusion
  tests/spark/test_spark_model_export.py
Labels: rn/none, only-latest

#9603 Rename `time_utils.py` to `time.py`
  examples/rest_api/mlflow_tracking_rest_api.py
  mlflow/cli.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/pyspark/ml/__init__.py
  mlflow/runs.py
  mlflow/sklearn/utils.py
  mlflow/store/model_registry/dbmodels/models.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/store/tracking/dbmodels/models.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tensorflow/__init__.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/fluent.py
  mlflow/utils/autologging_utils/client.py
  mlflow/utils/time.py
  tests/entities/conftest.py
  tests/entities/test_experiment.py
  tests/entities/test_metric.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/dummy_evaluator.py
  tests/store/model_registry/test_file_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/test_cli.py
  tests/tracking/fluent/test_fluent.py
  tests/tracking/test_model_registry.py
  tests/tracking/test_rest_tracking.py
  tests/tracking/test_tracking.py
Labels: rn/none, only-latest

#9605 Pin xgboost in recipes tests
  .github/workflows/recipe.yml
Labels: rn/none

#9454 Add a MLflow Tensorflow callback
  mlflow/tensorflow/__init__.py
  mlflow/tensorflow/callback.py
  mlflow/tracking/fluent.py
  tests/check_mlflow_lazily_imports_ml_packages.py
  tests/tensorflow/test_mlflow_callback.py
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/feature, area/tracking

#9607 Add `Timer` for quick benchmarking
  mlflow/recipes/steps/split.py
  mlflow/utils/time.py
  tests/utils/test_time.py
Labels: rn/none

#9498 Add parallelization to S3ArtifactRepo artifact uploading and downloading
  mlflow/store/_unity_catalog/registry/utils.py
  mlflow/store/artifact/optimized_s3_artifact_repo.py
  mlflow/store/artifact/r2_artifact_repo.py
  mlflow/store/artifact/s3_artifact_repo.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/store/artifact/test_optimized_s3_artifact_repo.py
  tests/store/artifact/test_r2_artifact_repo.py
  tests/store/artifact/test_s3_artifact_repo.py
  tests/store/artifact/test_unity_catalog_models_artifact_repo.py
Labels: rn/none, area/artifacts

#9619 update deprecated logger.warn
  mlflow/utils/autologging_utils/logging_and_warnings.py
Labels: rn/none

#9622 Fix `create_tmp_dir`
  mlflow/utils/file_utils.py
Labels: rn/none

#9555 update docs with outputs
  docs/source/models.rst
  examples/langchain/retrieval_qa_chain.py
Labels: rn/none, area/examples

#9497 support langchain chains with multiple outputs
  mlflow/langchain/__init__.py
  mlflow/langchain/api_request_parallel_processor.py
  mlflow/openai/utils.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/bug-fix, area/models

#9576 [LLM eval] Updating code to use openai/gateway rather than pyfunc for judge predictions
  mlflow/metrics/utils/make_genai_metric.py
  tests/metrics/utils/test_make_genai_metric.py
Labels: rn/none, area/tracking

#9624 Fix returned path parsing bug from R cli handler when loading models
  mlflow/R/mlflow/R/tracking-runs.R
  mlflow/R/mlflow/tests/testthat.R
Labels: language/r, rn/bug-fix, area/models

#9627 Decouple torch and tf
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_pytorch_autolog.py
  mlflow/tensorflow/__init__.py
  mlflow/utils/autologging_utils/metrics_queue.py
  tests/tensorflow/test_tensorflow2_autolog.py
  tests/utils/test_autologging_utils.py
Labels: rn/none, area/tracking

#9618 Fix broken windows test
  mlflow/gateway/providers/openai.py
  mlflow/gateway/utils.py
Labels: rn/none, area/tracking, area/gateway

#9631 Add UC Volumes local target directory as an MPD disable condition
  mlflow/store/artifact/cloud_artifact_repo.py
  mlflow/utils/uri.py
  tests/utils/test_uri.py
Labels: rn/bug-fix, area/artifacts, integrations/databricks

#9629 Set minimal token permissions for all workflows
  .github/workflows/advice.yml
  .github/workflows/autoformat.yml
  .github/workflows/cancel.yml
  .github/workflows/closing-pr.yml
  .github/workflows/cross-version-tests.yml
  .github/workflows/dev-setup.yml
  .github/workflows/devcontainer.yml
  .github/workflows/examples.yml
  .github/workflows/gateway.yml
  .github/workflows/js.yml
  .github/workflows/labeling.yml
  .github/workflows/master.yml
  .github/workflows/preview-docs.yml
  .github/workflows/protos.yml
  .github/workflows/push-images.yml
  .github/workflows/r.yml
  .github/workflows/recipe-template.yml
  .github/workflows/recipe.yml
  .github/workflows/release-note.yml
  .github/workflows/requirements.yml
  .github/workflows/rerun.yml
  .github/workflows/stale.yml
  .github/workflows/test-package-build.yml
Labels: rn/none, area/build

#9638 use append_to_uri_path instead of str concat
  mlflow/gateway/providers/openai.py
Labels: rn/none, area/gateway

#9641 Use `GITHUB_TOKEN` when pushing a devcontainer image
  .github/workflows/devcontainer.yml
Labels: rn/none

#9516 Add set_limits and get_limits API in mlflow client for AI Gateway
  mlflow/gateway/__init__.py
  mlflow/gateway/app.py
  mlflow/gateway/base_models.py
  mlflow/gateway/client.py
  mlflow/gateway/config.py
  mlflow/gateway/constants.py
  mlflow/gateway/fluent.py
  tests/gateway/test_client.py
  tests/gateway/test_fluent.py
Labels: rn/feature, autoformat, area/gateway

#9640 Fix prefix for log_eval_table
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/none, area/models

#9575 Update mlflow server handlers.py to set tracking/registry uri after calculating them
  mlflow/server/handlers.py
  tests/test_cli.py
Labels: rn/none

#9643 Isolate `MLFLOW_AUTOMATION_TOKEN` in autoformat workflow
  .github/workflows/autoformat.js
  .github/workflows/autoformat.yml
Labels: rn/none

#9599 Calculate latency in mlflow.evaluate()
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/none, area/tracking

#9660 Fix AI Gateway chat example
  mlflow/gateway/schemas/chat.py
Labels: rn/none, area/examples

#9636 Fix call to model_utils.score_model_on_payload in genai metric
  mlflow/metrics/utils/make_genai_metric.py
  tests/metrics/utils/test_make_genai_metric.py
Labels: rn/none, area/tracking

#9666 Remove redundant checkout in `.github/workflows/push-images.yml`
  .github/workflows/push-images.yml
Labels: rn/none

#9671 Add claude-2 to supported models in Gateway docs
  docs/source/gateway/index.rst
Labels: area/docs, rn/none

#9668 Use parallelism to score with judge model
  mlflow/metrics/utils/make_genai_metric.py
  tests/metrics/utils/test_make_genai_metric.py
Labels: rn/none, area/tracking

#9677 Update models.rst (#5)
  docs/source/models.rst
Labels: area/docs, rn/none

#9594 Update evaluate to use new metrics
  mlflow/metrics/__init__.py
  mlflow/metrics/utils/metric_definitions.py
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
  tests/metrics/test_metric_definitions.py
Labels: rn/none

#9681 Add `user.name` and `user.email` before merging master in `autoforma.yml`
  .github/workflows/autoformat.yml
Labels: rn/none

#9044 add dynamic dataframe typing plus tests
  mlflow/models/utils.py
  tests/models/test_model_input_examples.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/bug-fix, area/models

#9683 Improve OpenAI judge robustness
  mlflow/metrics/utils/make_genai_metric.py
Labels: rn/none, area/tracking

#9557 Add system metrics logging to MLflow fluent API
  examples/system_metrics/collect_system_metrics.py
  mlflow/__init__.py
  mlflow/environment_variables.py
  mlflow/system_metrics/__init__.py
  mlflow/system_metrics/metrics/__init__.py
  mlflow/system_metrics/metrics/base_metrics_monitor.py
  mlflow/system_metrics/metrics/cpu_monitor.py
  mlflow/system_metrics/metrics/disk_monitor.py
  mlflow/system_metrics/metrics/gpu_monitor.py
  mlflow/system_metrics/metrics/network_monitor.py
  mlflow/system_metrics/system_metrics_monitor.py
  mlflow/tracking/fluent.py
  requirements/core-requirements.txt
  requirements/core-requirements.yaml
  requirements/gateway-requirements.txt
  requirements/gateway-requirements.yaml
  tests/autologging/test_autologging_client.py
  tests/evaluate/test_default_evaluator.py
  tests/system_metrics/test_collect_metrics.py
  tests/system_metrics/test_system_metrics_logging.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/feature, area/tracking

#9679 Add token allocation guard to MosaicML AI Gateway routes
  mlflow/gateway/constants.py
  mlflow/gateway/providers/mosaicml.py
  mlflow/gateway/providers/utils.py
  tests/gateway/providers/test_mosaicml.py
  tests/gateway/tools.py
Labels: rn/none, area/gateway

#9690 Enable LangChain SQLDatabaseChain test and fix bug
  mlflow/langchain/__init__.py
  tests/langchain/test_langchain_model_export.py
Labels: bug, rn/none

#9691 Updating the prompt based on feedback
  mlflow/metrics/base.py
  mlflow/metrics/utils/prompts/v1.py
  tests/metrics/utils/prompts/test_v1.py
  tests/metrics/utils/test_make_genai_metric.py
Labels: rn/none, area/tracking

#9694 Enable `mutable-argument-default`
  pyproject.toml
Labels: rn/none

#9637 Add a MLflow Tensorflow callback
  mlflow/tensorflow/__init__.py
  mlflow/tensorflow/callback.py
  mlflow/tracking/fluent.py
  tests/check_mlflow_lazily_imports_ml_packages.py
  tests/tensorflow/test_mlflow_callback.py
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/feature, area/models

#9645 R2 Artifact Repo to use _get_region_name() from its parent class
  mlflow/store/artifact/optimized_s3_artifact_repo.py
  mlflow/store/artifact/r2_artifact_repo.py
  tests/store/artifact/test_r2_artifact_repo.py
Labels: rn/none, area/artifacts

#9707 Fix spark dev java version
  .github/workflows/cross-version-tests.yml
Labels: rn/none, enable-dev-tests, only-latest

#9712 Add step for system metrics logging
  mlflow/system_metrics/system_metrics_monitor.py
  tests/system_metrics/test_system_metrics_logging.py
Labels: rn/bug-fix, area/tracking

#9692 move transformers module to its directory
  mlflow/transformers/__init__.py
Labels: rn/none, area/tracking

#9696 Allow None for scores, justifications, and aggregates
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/none

#9716 Call `spark.conf.get` with `default=None` to suppress error message for spark connect
  mlflow/utils/databricks_utils.py
Labels: rn/none

#9689 Add example for evalution with LLM judge
  examples/evaluation/evaluate_with_llm_judge.py
  mlflow/metrics/utils/make_genai_metric.py
  mlflow/models/evaluation/default_evaluator.py
  tests/metrics/utils/test_make_genai_metric.py
Labels: rn/none, area/examples, area/tracking

#9715 Fixing JSON parsing for LLM response
  mlflow/metrics/utils/make_genai_metric.py
  mlflow/metrics/utils/model_utils.py
  mlflow/models/evaluation/default_evaluator.py
  tests/metrics/utils/test_make_genai_metric.py
Labels: rn/none, area/tracking

#9658 Calculate token count in mlflow.evaluate()
  mlflow/models/evaluation/default_evaluator.py
  requirements/test-requirements.txt
  tests/evaluate/test_default_evaluator.py
Labels: rn/none, area/tracking

#9722 Making sure that open_ai returns json
  mlflow/metrics/utils/model_utils.py
Labels: rn/none, area/tracking

#9725 Pin pyspark < 3.5
  .github/workflows/master.yml
  .github/workflows/recipe.yml
Labels: rn/none

#9728 Make pytest less verbose
  pytest.ini
Labels: rn/none

#9732 Merge "Pin pyspark < 3.5" to mlflow-evaluation
  .github/workflows/master.yml
  .github/workflows/recipe.yml
Labels: rn/none

#9673 Default metric for correctness
  docs/source/conf.py
  mlflow/metrics/__init__.py
  mlflow/metrics/genai/make_genai_metric.py
  mlflow/metrics/genai/metric_definitions.py
  mlflow/metrics/genai/model_utils.py
  mlflow/metrics/genai/prompt_template.py
  mlflow/metrics/genai/prompts/v1.py
  mlflow/metrics/genai/utils.py
  mlflow/metrics/metric_definitions.py
  mlflow/metrics/utils/__init__.py
  mlflow/metrics/utils/prompts/__init__.py
  mlflow/metrics/utils/prompts/v1.py
  tests/metrics/genai/prompts/test_v1.py
  tests/metrics/genai/test_genai_metrics.py
  tests/metrics/genai/test_model_utils.py
  tests/metrics/genai/test_prompt_template.py
  tests/metrics/test_metric_definitions.py
Labels: rn/none

#9735 Free disk space in pyfunc job
  .github/workflows/master.yml
Labels: rn/none

#9745 Drop old sklearn versions
  mlflow/ml-package-versions.yml
Labels: rn/none

#9729 Improve `examples/databricks/artifact_perf.py`
  examples/databricks/artifact_perf.py
  examples/databricks/multipart.py
Labels: rn/none

#9750 Drop support for old catboost versions
  mlflow/ml-package-versions.yml
Labels: rn/none

#9751 Use Python 3.9 for tensorflow 2.14.0
  .github/actions/setup-python/action.yml
  .github/workflows/cross-version-tests.yml
  mlflow/tensorflow/__init__.py
Labels: rn/none

#9748 Pin pyspark in `.github/workflows/requirements.yml`
  .github/workflows/requirements.yml
Labels: rn/none

#9747 Unpin numpy for `evaluate` job
  .github/workflows/master.yml
Labels: rn/none

#9749 Fix langchain attribute error
  mlflow/langchain/__init__.py
  mlflow/langchain/api_request_parallel_processor.py
Labels: rn/none, enable-dev-tests

#9697 Clean up PR template
  .github/pull_request_template.md
Labels: rn/none

#9534 Make spark flavor support saving / loading spark connect ML models
  examples/pyspark_ml_connect/README.md
  examples/pyspark_ml_connect/pipeline.py
  mlflow/ml-package-versions.yml
  mlflow/spark.py
  mlflow/utils/requirements_utils.py
  tests/spark/test_spark_connect_model_export.py
Labels: rn/feature, area/tracking, enable-dev-tests

#9706 Customize model version creation await functionality
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/databricks_workspace_model_registry_rest_store.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/tracking/_model_registry/client.py
  tests/store/model_registry/test_rest_store.py
  tests/tracking/_model_registry/test_model_registry_client.py
  tests/tracking/test_client.py
Labels: rn/none, area/model-registry

#9714 Set network metrics to start from 0
  mlflow/system_metrics/metrics/base_metrics_monitor.py
  mlflow/system_metrics/metrics/cpu_monitor.py
  mlflow/system_metrics/metrics/disk_monitor.py
  mlflow/system_metrics/metrics/gpu_monitor.py
  mlflow/system_metrics/metrics/network_monitor.py
  tests/system_metrics/test_collect_metrics.py
Labels: rn/bug-fix, area/tracking

#9758 Docs for make_genai_metric
  examples/evaluation/evaluate_with_llm_judge.py
  mlflow/metrics/__init__.py
  mlflow/metrics/genai/genai_metric.py
  mlflow/metrics/genai/metric_definitions.py
  tests/metrics/genai/test_genai_metrics.py
Labels: area/docs, rn/none, area/tracking

#9761 Merge "Free disk space in pyfunc job" into mlflow-evaluation
  .github/workflows/master.yml
Labels: rn/none

#9724 Default metric for relevance
  mlflow/metrics/__init__.py
  mlflow/metrics/genai/metric_definitions.py
  mlflow/metrics/genai/prompts/v1.py
  tests/metrics/genai/test_genai_metrics.py
Labels: rn/none

#9762 Fix order of future as_completed
  mlflow/metrics/genai/genai_metric.py
Labels: rn/none, area/tracking

#9764 Fix examples prompt
  mlflow/metrics/genai/prompts/v1.py
  tests/metrics/genai/prompts/test_v1.py
  tests/metrics/genai/test_genai_metrics.py
Labels: rn/none

#9753 Insert codespaces badge when a PR is opened
  .github/workflows/advice.js
Labels: rn/none

#9770 Fix `test_whisper_model_supports_timestamps`
  tests/transformers/test_transformers_model_export.py
Labels: rn/none, enable-dev-tests, only-latest

#9768 Don't pin R version and use the latest
  .github/workflows/r.yml
Labels: rn/none

#9771 Move `mlflow/johnshowlabs.py` to `mlflow/johnshowlabs/__init__.py`
  mlflow/johnsnowlabs/__init__.py
Labels: rn/none

#9767 Update example to use precanned correctness
  examples/evaluation/evaluate_with_llm_judge.py
  mlflow/metrics/genai/prompts/v1.py
  tests/metrics/genai/prompts/test_v1.py
Labels: rn/none, area/examples

#9754 Use tensorflow-cpu for faster installation
  requirements/doc-requirements.txt
  requirements/extra-ml-requirements.txt
Labels: rn/none

#9774 doc: fixed typo "Sublcass"
  mlflow/system_metrics/metrics/base_metrics_monitor.py
Labels: rn/none

#9709 Update max length of params to 6k
  docs/source/tracking.rst
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/store/db_migrations/versions/2d6e25af4d3e_increase_max_param_val_length.py
  mlflow/store/tracking/dbmodels/models.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  mlflow/utils/validation.py
  tests/db/compose.yml
  tests/db/schemas/mssql.sql
  tests/db/schemas/mysql.sql
  tests/db/schemas/postgresql.sql
  tests/db/schemas/sqlite.sql
  tests/resources/db/latest_schema.sql
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/feature, area/tracking

#9704 Support for Azure AD authentication and fix embeddings on Azure OpenAI
  mlflow/openai/__init__.py
  mlflow/openai/api_request_parallel_processor.py
  mlflow/openai/utils.py
Labels: rn/feature, area/models, integrations/azure

#9766 Default metric for strict correctness
  mlflow/metrics/genai/metric_definitions.py
  mlflow/metrics/genai/prompts/v1.py
  tests/metrics/genai/prompts/test_v1.py
  tests/metrics/genai/test_genai_metrics.py
Labels: rn/none

#9746 Updating the concept of variables for eval_fn
  mlflow/metrics/genai/genai_metric.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
  tests/metrics/genai/test_genai_metrics.py
Labels: rn/none, area/tracking

#9756 Moved mlflow/shap.py to shap/__init__.py for consistency. Fixes #9743
  mlflow/shap/__init__.py
Labels: rn/none, area/models
