Repository mlflow/mlflow, pull requests merged in 2023-06, with the labels that each got.

#8578 Unpin `pyspark` in `recipes`
  .github/workflows/recipe.yml
  mlflow/utils/_spark_utils.py
  tests/recipes/test_ingest_step.py
  tests/recipes/test_predict_step.py
Labels: rn/none

#8577 Fix tests broken in pandas 2.0
  tests/pyfunc/test_pyfunc_schema_enforcement.py
  tests/recipes/test_ingest_step.py
  tests/types/test_schema.py
  tests/utils/test_proto_json_utils.py
Labels: rn/none

#8582 Incraese timeout-minutes of `database` job
  .github/workflows/master.yml
Labels: rn/none

#8575 Remove `sktime` from `requirements/test-requirements.txt`
  requirements/test-requirements.txt
  tests/examples/test_examples.py
Labels: rn/none

#8581 Automatically clean up python environments in tests
  conftest.py
Labels: rn/none

#8541 [ML-31719] Added lineage identifier header to the UC CreateModelVersion REST API call
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/model_registry/base_rest_store.py
  mlflow/utils/rest_utils.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/utils/test_rest_utils.py
Labels: rn/none, area/model-registry

#8588 fix distutils assertion failure
  mlflow/utils/environment.py
Labels: rn/none, area/build

#8580 Eliminate `tempfile.mkstemp`
  examples/pytorch/IterativePruning/iterative_prune_mnist.py
  mlflow/fastai/__init__.py
  mlflow/fastai/callback.py
  mlflow/lightgbm.py
  mlflow/projects/databricks.py
  mlflow/pytorch/_lightning_autolog.py
  mlflow/tracking/artifact_utils.py
  mlflow/utils/virtualenv.py
  mlflow/xgboost/__init__.py
  tests/recipes/test_predict_step.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging_order.py
  tests/spark/autologging/utils.py
  tests/store/dump_schema.py
  tests/test_runs.py
  tests/tracking/test_rest_tracking.py
  tests/tracking/test_tracking.py
  tests/utils/test_data.py
Labels: rn/none, only-latest

#8592 Support list[str] in __enforce__schema
  mlflow/models/utils.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
Labels: rn/none, area/models

#8595 Preserve string columns when computing pandas dataset hash
  mlflow/data/digest_utils.py
  tests/data/test_pandas_dataset.py
Labels: rn/none, area/tracking

#8589 Enable stream in `HTTPDatasetSource.load`
  mlflow/data/http_dataset_source.py
Labels: rn/none

#8547 Pyfunc support for SentenceTransformers
  mlflow/ml-package-versions.yml
  mlflow/sentence_transformers.py
  mlflow/utils/autologging_utils/versioning.py
  tests/sentence_transformers/test_sentence_transformers_model_export.py
Labels: rn/feature, area/models, area/scoring, integrations/databricks

#8593 Fix the lineage header protobuf definitions
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/none, area/model-registry

#8597 Avoid mutating input `base_dict` in `_to_dict`
  mlflow/data/huggingface_dataset.py
  mlflow/data/numpy_dataset.py
  mlflow/data/pandas_dataset.py
  mlflow/data/spark_dataset.py
  mlflow/data/tensorflow_dataset.py
  tests/resources/data/dataset.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/dummy_dataset.py
Labels: rn/none

#8587 Revert "Unpin pypsark in recipes (#8578)"
  .github/workflows/recipe.yml
Labels: rn/none, area/build

#8598 Remove strange `TypeVar` usage
  mlflow/recipes/step.py
  mlflow/recipes/steps/ingest/datasets.py
  mlflow/recipes/utils/tracking.py
Labels: rn/none

#8596 Use context manager in `spark_session` fixtures
  sample-file-to-write
  tests/data/test_pandas_dataset.py
  tests/data/test_spark_dataset.py
  tests/data/test_spark_dataset_source.py
  tests/evaluate/test_evaluation.py
  tests/recipes/test_ingest_step.py
  tests/recipes/test_predict_step.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging_unit.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
  tests/spark/autologging/utils.py
  tests/utils/test_file_utils.py
Labels: rn/none, only-latest

#8601 Skip displaying card in recipe tests
  mlflow/recipes/utils/step.py
  tests/recipes/test_step_utils.py
Labels: rn/none

#8604 Pin pandas to fix (some) cross version tests
  mlflow/ml-package-versions.yml
Labels: rn/none

#8586 Fast follow dataset cleanups
  mlflow/data/artifact_dataset_sources.py
  mlflow/data/code_dataset_source.py
  mlflow/data/dataset.py
  mlflow/data/dataset_registry.py
  mlflow/data/dataset_source.py
  mlflow/data/delta_dataset_source.py
  mlflow/data/filesystem_dataset_source.py
  mlflow/data/http_dataset_source.py
  mlflow/data/huggingface_dataset_source.py
  mlflow/data/spark_dataset_source.py
Labels: rn/none, area/tracking, only-latest

#8607 fix build docs
  mlflow/protos/service.proto
Labels: area/docs, rn/none

#8615 Fix matching rule in `update_ml_package_versions.py`
  dev/update_ml_package_versions.py
Labels: rn/none

#8617 Fix incorrect module key for `sentence_transformers`
  mlflow/ml_package_versions.py
  mlflow/utils/autologging_utils/versioning.py
Labels: rn/none

#8611 Use pandas<2 for Diviner <= 0.1.1
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#8556 add johnsnowlabs flavor
  .github/workflows/cross-version-tests.yml
  .github/workflows/master.yml
  conftest.py
  mlflow/__init__.py
  mlflow/johnsnowlabs.py
  mlflow/ml-package-versions.yml
  requirements/extra-ml-requirements.txt
  tests/johnsnowlabs/test_johnsnowlabs_model_export.py
Labels: rn/feature, area/model-registry

#8628 Use shinto shrine emoji to highlight `gateway` workflow
  .github/workflows/gateway.yml
Labels: rn/none

#8623 Replace `whisper-small` with `whisper-tiny` to save disk space
  tests/datasets/apollo11_launch.wav
  tests/transformers/test_transformers_model_export.py
Labels: rn/none

#8608 Replace `tmpdir` with `tmp_path`
  tests/catboost/test_catboost_model_export.py
  tests/fastai/test_fastai_autolog.py
  tests/fastai/test_fastai_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/lightgbm/test_lightgbm_autolog.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/onnx/test_onnx_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/sklearn/test_sklearn_model_export.py
  tests/xgboost/test_xgboost_autolog.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none, only-latest

#8634 extend timeout duration of waiting flask server
  tests/tracking/integration_test_utils.py
Labels: rn/none

#8637 Cancel concurrent runs on master branch
  .github/workflows/cross-version-tests.yml
  .github/workflows/dev-setup.yml
  .github/workflows/devcontainer.yml
  .github/workflows/examples.yml
  .github/workflows/gateway.yml
  .github/workflows/js.yml
  .github/workflows/master.yml
  .github/workflows/protos.yml
  .github/workflows/r.yml
  .github/workflows/recipe-template.yml
  .github/workflows/recipe.yml
  .github/workflows/release-note-category.yml
  .github/workflows/requirements.yml
  .github/workflows/test-package-build.yml
Labels: rn/none

#8622 Extend SearchRuns to support datasets
  docs/source/search-runs.rst
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/utils/search_utils.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/utils/test_search_utils.py
Labels: area/docs, rn/feature, area/tracking

#8599 Use context manager when creating a spark session
  tests/data/test_delta_dataset_source.py
  tests/data/test_pandas_dataset.py
  tests/mleap/test_mleap_model_export.py
  tests/pyfunc/test_spark.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging_missing_jar.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging_order.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging_custom_allowlist.py
  tests/tensorflow/test_keras_pyfunc_model_works_with_all_input_types.py
Labels: rn/none, only-latest

#8638 Fix UC model lineage header value
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/none

#8636 Monitor disk usage in transformers tests
  tests/examples/test_examples.py
  tests/helper_functions.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/none, only-latest

#8642 Import `datasets` lazily in `mlflow.data`
  mlflow/data/huggingface_dataset.py
  mlflow/data/huggingface_dataset_source.py
Labels: rn/none

#8647 Fix diviner cross version tests for dev
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build, enable-dev-tests

#8646 Fix sentence-transformers dev install in tests
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build, enable-dev-tests

#8650 Cancel GitHub Actions runs when a PR is closed or merged
  .github/workflows/cancel.js
  .github/workflows/cancel.yml
Labels: rn/none

#8572 Implement Gateway backend
  .github/workflows/gateway.yml
  mlflow/cli.py
  mlflow/gateway/__init__.py
  mlflow/gateway/app.py
  mlflow/gateway/cli.py
  mlflow/gateway/config.py
  mlflow/gateway/constants.py
  mlflow/gateway/handlers.py
  mlflow/gateway/runner.py
  mlflow/gateway/utils.py
  requirements/gateway-requirements.txt
  requirements/gateway-requirements.yaml
  requirements/test-requirements.txt
  tests/gateway/test_cli.py
  tests/gateway/test_gateway_app.py
  tests/gateway/test_gateway_config_parsing.py
  tests/gateway/test_gateway_handlers.py
  tests/gateway/test_runner.py
Labels: rn/feature, area/server-infra

#8648 fix some lfi issues
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#8660 Use a shared thread pool executor when downloading a large file
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/utils/file_utils.py
Labels: rn/none

#8653 Add environment variable to disable multipart download
  mlflow/environment_variables.py
  mlflow/store/artifact/databricks_models_artifact_repo.py
Labels: rn/none

#8655 Fix data target for hyperparam Example
  examples/hyperparam/MLproject
Labels: rn/none, area/examples

#8670 Rename `handlers.py` to `config.py`
  mlflow/gateway/app.py
  mlflow/gateway/config.py
  mlflow/gateway/handlers.py
  mlflow/gateway/runner.py
  tests/gateway/test_gateway_config_parsing.py
Labels: rn/none, gateway

#8664 Use valid openai config values
  tests/gateway/test_gateway_config_parsing.py
  tests/gateway/test_runner.py
Labels: rn/none, gateway

#8663 Remove unused `_parse_url_path_for_base_url`
  mlflow/gateway/utils.py
Labels: rn/none

#8661 Add gateway example for quick manual testing
  examples/gateway/README.md
  examples/gateway/config.yaml
  mlflow/gateway/utils.py
Labels: rn/none, gateway

#8668 Use `tmp_path` fixture when creating local files in tests
  tests/gateway/test_gateway_config_parsing.py
Labels: rn/none, gateway

#8666 Rename `instruct` to `completions` to avoid confusion
  tests/gateway/test_gateway_config_parsing.py
  tests/gateway/test_runner.py
Labels: rn/none, gateway

#8654 Revert "Do not use subprocess in multipart download"
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/utils/download_cloud_file_chunk.py
  mlflow/utils/file_utils.py
  mlflow/utils/request_utils.py
  tests/store/artifact/test_databricks_models_artifact_repo.py
  tests/utils/test_request_utils.py
Labels: rn/none

#8652 Ignore encoding errors with transformers model cards
  mlflow/transformers.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/bug-fix, area/models, only-latest

#8674 Databricks: use smaller chunk size for artifact downloads while maintaining a higher multipart download file size threshold
  mlflow/store/artifact/databricks_artifact_repo.py
Labels: rn/none, area/artifacts

#8677 Mark optional columns experimental
  mlflow/types/schema.py
Labels: area/docs, rn/none

#8678 Add duplicate requirements validation
  mlflow/transformers.py
  mlflow/utils/environment.py
  tests/transformers/test_transformers_model_export.py
  tests/utils/test_environment.py
Labels: rn/feature, area/models, only-latest

#8665 Use `monkeypatch.setenv` when setting env vars
  tests/gateway/test_gateway_config_parsing.py
Labels: rn/none, gateway

#8683 Update CHANGELOG.md
  CHANGELOG.md
Labels: area/docs, rn/none

#8682 Remove LRU session caching
  mlflow/utils/request_utils.py
Labels: rn/none, area/artifacts

#8690 Remove `test_get_request_session`
  tests/utils/test_rest_utils.py
Labels: rn/none

#8689 Add johnsnowlabs flavor docs
  docs/docs/source/python_api/mlflow.johnsnowlabs.rst
  docs/source/models.rst
  docs/source/python_api/mlflow.johnsnowlabs.rst
  examples/README.md
  examples/johnsnowlabs/export.py
  mlflow/johnsnowlabs.py
Labels: rn/none

#8693 Use `use-list_changed_files.py` in `.github/workflows/examples.yml`
  .github/workflows/examples.yml
  dev/list_changed_files.py
Labels: rn/none

#8692 Replace `tmpdir` with `tmp_path`
  tests/gluon/test_gluon_model_export.py
  tests/johnsnowlabs/test_johnsnowlabs_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pytorch/test_pytorch_model_export.py
  tests/shap/test_log.py
  tests/spacy/test_spacy_model_export.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging.py
  tests/spark/test_spark_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/tensorflow/test_keras_model_export.py
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/none, only-latest

#8498 gc delete invalid artifact url
  mlflow/cli.py
  mlflow/exceptions.py
  mlflow/utils/rest_utils.py
  tests/utils/test_rest_utils.py
Labels: rn/bug-fix, area/artifacts

#8673 Simplify `_extract_and_set_api_key`
  mlflow/gateway/config.py
Labels: rn/none, gateway

#8695 Examples + docs for LLMs & evaluation
  docs/source/_static/images/artifact-view-ui.png
  docs/source/models.rst
  examples/llms/README.md
  examples/llms/question_answering/MLproject
  examples/llms/question_answering/python_env.yaml
  examples/llms/question_answering/question_answering.py
  examples/llms/summarization/MLproject
  examples/llms/summarization/python_env.yaml
  examples/llms/summarization/summarization.py
  examples/llms/summarization/summarization_example_data.csv
Labels: area/docs, rn/none

#8709 Remove the default provider
  mlflow/gateway/config.py
Labels: rn/none, gateway

#8710 Read environment variable only when API key starts with `$`
  mlflow/gateway/config.py
  tests/gateway/test_gateway_config_parsing.py
Labels: rn/none, gateway

#8711 Add embeddings to route types
  mlflow/gateway/config.py
Labels: rn/none, gateway

#8712 Remove PROVIDERS constant
  mlflow/gateway/config.py
  mlflow/gateway/constants.py
Labels: rn/none, gateway

#8713 Ignore `gunicorn.conf.py`
  .gitignore
  mlflow/gateway/runner.py
Labels: rn/none, gateway

#8669 Add common request and schemas for LLM query interface
  examples/gateway/README.md
  examples/gateway/config.yaml
  mlflow/gateway/app.py
  mlflow/gateway/schemas/__init__.py
  mlflow/gateway/schemas/chat.py
  mlflow/gateway/schemas/completions.py
  mlflow/gateway/schemas/embeddings.py
  tests/gateway/schemas/test_chat.py
  tests/gateway/schemas/test_completions.py
  tests/gateway/schemas/test_embeddings.py
  tests/gateway/test_runner.py
Labels: rn/none, gateway

#8718 Replace `tmpdir` with `tmp_path` (part 5)
  tests/utils/test_environment.py
Labels: rn/none

#8716 Replace `tmpdir` with `tmp_path` (part 4)
  tests/utils/test_file_utils.py
Labels: rn/none

#8715 Replace `tmpdir` with `tmp_path` (part 3)
  tests/store/artifact/test_mlflow_artifact_repo.py
Labels: rn/none

#8721 Fix shell command in lint job
  .github/workflows/master.yml
Labels: rn/none

#8688 Support reading MLflow credentials from file (`~/.mlflow/credentials`)
  mlflow/environment_variables.py
  mlflow/tracking/_tracking_service/utils.py
  mlflow/tracking/context/default_context.py
  mlflow/utils/credentials.py
  tests/utils/test_credentials.py
Labels: rn/none

#8719 Disallow useless assignment before return
  mlflow/sagemaker/__init__.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  pylint_plugins/__init__.py
  pylint_plugins/assign_checker.py
  pylint_plugins/errors.py
  tests/paddle/test_paddle_model_export.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sagemaker/mock/__init__.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#8723 Remove `report_free_disk_space` in transformers test
  tests/transformers/test_transformers_model_export.py
Labels: rn/none

#8720 Skip free-disk-space if not transformers
  .github/workflows/cross-version-tests.yml
Labels: rn/none

#8704 Add Gateway client API for static routes
  mlflow/gateway/__init__.py
  mlflow/gateway/app.py
  mlflow/gateway/client.py
  mlflow/gateway/config.py
  mlflow/gateway/constants.py
  mlflow/gateway/envs.py
  mlflow/gateway/fluent.py
  mlflow/gateway/utils.py
  tests/gateway/test_client.py
  tests/gateway/test_fluent.py
  tests/gateway/test_gateway_config_parsing.py
  tests/gateway/test_runner.py
  tests/gateway/tools.py
Labels: rn/feature, area/server-infra, gateway

#8726 Update `embeddings.RequestPayload` to support text array
  mlflow/gateway/schemas/embeddings.py
  tests/gateway/schemas/test_embeddings.py
Labels: rn/none, gateway

#8727 Remove `top_p` in chat/comletions payload schema
  mlflow/gateway/schemas/chat.py
Labels: rn/none, gateway

#8707 Enhance MLflow plugins documentation with OCI integration details for seamless integration with OCI services
  docs/source/plugins.rst
Labels: area/docs, rn/documentation, area/artifacts, area/models, area/projects

#8687 add micro version to mlflow version pinning
  conftest.py
  mlflow/environment_variables.py
  mlflow/utils/environment.py
  tests/helper_functions.py
Labels: rn/bug-fix, area/models

#8691 Support app factory for mlflow server app
  mlflow/server/__init__.py
  mlflow/server/auth/__init__.py
  setup.py
  tests/server/auth/test_auth.py
  tests/server/auth/test_client.py
  tests/server/test_init.py
  tests/tracking/integration_test_utils.py
Labels: rn/none

#8732 Validate API key field in each model and mark it as required
  mlflow/gateway/config.py
  tests/gateway/test_gateway_config_parsing.py
Labels: rn/none, gateway

#8730 Use torch's `AdamW` in `examples/pytorch/BertNewsClassification/bert_classification.py`
  examples/pytorch/BertNewsClassification/bert_classification.py
Labels: rn/none

#8729 Replace `wait` with `Gateway.wait_reload`
  tests/gateway/test_runner.py
  tests/gateway/tools.py
Labels: rn/none

#8717 Detect untracked files
  .github/actions/untracked/action.yml
  .github/workflows/cross-version-tests.yml
  .github/workflows/master.yml
  .github/workflows/recipe.yml
  tests/artifacts/test_artifacts.py
  tests/recipes/test_ingest_step.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/dummy_evaluator.py
  tests/tracking/_tracking_service/test_tracking_service_client.py
  tests/utils/test_file_utils.py
Labels: rn/none

#8733 Remove `Optional` on `openai_api_base` and `anthropic_api_base`
  mlflow/gateway/config.py
Labels: rn/none, gateway

#8731 Replace `tmpdir` with `tmp_path` (part 6)
  tests/deployments/test_cli.py
  tests/projects/test_databricks.py
  tests/projects/test_project_spec.py
  tests/projects/test_projects.py
  tests/projects/test_projects_cli.py
  tests/projects/test_utils.py
Labels: rn/none

#8740 Remove `_validate_base_route`
  mlflow/gateway/config.py
Labels: rn/none

#8743 Redirect `/` to `/docs`
  mlflow/gateway/app.py
Labels: rn/none

#8744 Use the latest version if mlflow version is a dev version
  mlflow/utils/environment.py
Labels: rn/none

#8746 Add query to client and fluent apis
  mlflow/gateway/__init__.py
  mlflow/gateway/client.py
  mlflow/gateway/fluent.py
  tests/gateway/test_client.py
  tests/gateway/test_fluent.py
Labels: rn/none, area/server-infra

#8735 Add `mlflow.gateway.query` example
  examples/gateway/request.py
Labels: rn/none, gateway

#8742 Simplify example for MLflow LLM evaluation in docs
  docs/source/models.rst
Labels: area/docs, rn/none

#8745 Add docs for gateway APIs
  .circleci/config.yml
  docs/source/conf.py
  docs/source/python_api/mlflow.gateway.rst
  mlflow/gateway/client.py
  mlflow/gateway/fluent.py
Labels: rn/none, gateway

#8748 Include `github.event_name` in concurrency group to distinguish workflow runs triggered by different events
  .github/workflows/cross-version-tests.yml
  .github/workflows/dev-setup.yml
  .github/workflows/devcontainer.yml
  .github/workflows/examples.yml
  .github/workflows/js.yml
  .github/workflows/master.yml
  .github/workflows/protos.yml
  .github/workflows/r.yml
  .github/workflows/recipe-template.yml
  .github/workflows/recipe.yml
  .github/workflows/release-note-category.yml
  .github/workflows/requirements.yml
  .github/workflows/test-package-build.yml
Labels: rn/none

#8751 Fix `pip_requirements` example
  examples/pip_requirements/pip_requirements.py
Labels: rn/none

#8753 Replace `tmpdir` with `tmp_path` (part 7)
  tests/johnsnowlabs/test_johnsnowlabs_model_export.py
  tests/projects/conftest.py
  tests/projects/test_databricks.py
  tests/projects/test_project_spec.py
  tests/pyfunc/test_dependencies_functions.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/store/artifact/test_dbfs_fuse_artifact_repo.py
  tests/store/artifact/test_dbfs_rest_artifact_repo.py
  tests/tracking/_model_registry/test_utils.py
  tests/tracking/_tracking_service/test_utils.py
  tests/tracking/conftest.py
  tests/tracking/test_artifact_utils.py
  tests/tracking/test_client.py
  tests/utils/test_databricks_utils.py
  tests/utils/test_requirements_utils.py
Labels: rn/none

#8728 Fix reading model flavor config from URI for models in UC
  mlflow/utils/model_utils.py
  tests/spark/test_spark_model_export.py
  tests/store/artifact/constants.py
  tests/store/artifact/test_models_artifact_repo.py
Labels: rn/none

#8722 Remove modifications to sys.modules
  mlflow/utils/model_utils.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/utils/test_model_utils.py
  tests/utils/test_resources/dummy_package/pandas.py
Labels: rn/bug-fix

#8739 Implement Search Datasets API in Tracking Store
  mlflow/entities/__init__.py
  mlflow/entities/dataset_summary.py
  mlflow/server/__init__.py
  mlflow/server/handlers.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, area/tracking

#8756 Replace `tmpdir` with `tmp_path` (part 8)
  tests/projects/test_projects.py
  tests/store/artifact/test_azure_blob_artifact_repo.py
  tests/store/artifact/test_ftp_artifact_repo.py
  tests/store/artifact/test_gcs_artifact_repo.py
  tests/store/artifact/test_http_artifact_repo.py
  tests/store/artifact/test_s3_artifact_repo.py
  tests/store/tracking/test_sqlalchemy_store_schema.py
  tests/tensorflow/test_tensorflow2_autolog.py
  tests/tracking/test_mlflow_artifacts.py
  tests/tracking/test_tracking.py
Labels: rn/none, only-latest

#8768 Fix `stop` type of chat/completions request payload
  mlflow/gateway/schemas/chat.py
  tests/gateway/schemas/test_chat.py
Labels: rn/none, gateway

#8760 Improve error messages when using stage-based APIs with models in UC
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/store/artifact/test_unity_catalog_models_artifact_repo.py
Labels: rn/none

#8770 Disable HTTP request retry to run tests faster
  tests/gateway/test_client.py
  tests/gateway/test_fluent.py
Labels: rn/none, gateway

#8766 Prevent `tmpdir` fixture usage in tests
  pytest.ini
  tests/projects/utils.py
  tests/utils/test_environment.py
Labels: rn/none

#8764 Fix downloading MLmodel files from alias-based models:/ URIs
  mlflow/store/artifact/utils/models.py
  mlflow/utils/model_utils.py
  tests/spark/test_spark_model_export.py
Labels: rn/none

#8771 fix untracked file in gluon
  tests/gluon/test_gluon_model_export.py
Labels: rn/none

#8749 Fix tensorflow cross-version tests
  mlflow/ml-package-versions.yml
Labels: rn/none

#8775 Replace `mock.patch.dict(os.environ, ...)` with `monkeypatch.{setenv|delenv}` using ChatGPT
  tests/utils/test_databricks_utils.py
  tests/utils/test_rest_utils.py
Labels: rn/none

#8773 Refactor gateway app
  mlflow/gateway/app.py
  tests/gateway/test_gateway_app.py
Labels: rn/none, area/build, gateway

#8772 remove lightgbm & sentence-transformers repo after installation
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#8725 Infer signature from input example when logging or saving models
  mlflow/models/model.py
  mlflow/models/signature.py
  mlflow/sklearn/__init__.py
  mlflow/spark.py
  mlflow/tensorflow/__init__.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/docstring_utils.py
  mlflow/xgboost/__init__.py
  tests/autologging/test_autologging_utils.py
  tests/models/test_model_input_examples.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spark/test_spark_model_export.py
  tests/tensorflow/test_keras_model_export.py
  tests/tensorflow/test_tensorflow2_core_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/feature, area/models, only-latest

#8786 Rename `store_conf` to `save_yaml`
  tests/gateway/test_client.py
  tests/gateway/test_fluent.py
  tests/gateway/test_runner.py
  tests/gateway/tools.py
Labels: rn/none, gateway

#8791 Cast activate_cmd to string for both Unix and other cases
  mlflow/utils/virtualenv.py
Labels: area/windows, rn/none, area/projects

#8787 Use `return_value` argument of `mock.patch` instead of assigning a value to `return_value` attribute after creating a mock
  tests/projects/backend/test_loader.py
  tests/projects/test_databricks.py
  tests/projects/test_docker_projects.py
  tests/projects/test_entry_point.py
  tests/projects/test_kubernetes.py
  tests/projects/test_projects.py
  tests/recipes/test_ingest_step.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging_unit.py
  tests/store/artifact/test_databricks_models_artifact_repo.py
  tests/store/artifact/test_dbfs_artifact_repo_delegation.py
  tests/store/artifact/test_dbfs_fuse_artifact_repo.py
  tests/store/artifact/test_dbfs_rest_artifact_repo.py
  tests/store/artifact/test_models_artifact_repo.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/test_runs.py
  tests/tracking/_tracking_service/test_utils.py
  tests/tracking/default_experiment/test_databricks_job_experiment_provider.py
  tests/tracking/default_experiment/test_databricks_notebook_experiment_provider.py
  tests/tracking/fluent/test_fluent.py
  tests/tracking/test_client.py
  tests/utils/test_rest_utils.py
Labels: rn/none

#8788 Fix flaky transformers tests with retry
  tests/transformers/test_transformers_model_export.py
Labels: rn/none

#8795 Improve transformers signature inference implementation
  mlflow/transformers.py
Labels: rn/feature, area/models

#8793 Gateway add prefix and suffixes to routes
  mlflow/gateway/app.py
  mlflow/gateway/client.py
  mlflow/gateway/constants.py
  tests/gateway/test_client.py
  tests/gateway/test_fluent.py
  tests/gateway/test_gateway_app.py
  tests/gateway/test_runner.py
Labels: rn/none, area/server-infra

#8792 [Gateway] avoid reserved type keyword within payloads
  mlflow/gateway/app.py
  mlflow/gateway/config.py
  mlflow/gateway/providers/openai.py
  tests/gateway/providers/test_openai.py
  tests/gateway/test_client.py
  tests/gateway/test_fluent.py
  tests/gateway/test_gateway_app.py
  tests/gateway/test_gateway_config_parsing.py
  tests/gateway/test_runner.py
Labels: rn/none, area/server-infra, gateway

#8797 Fix `type` to `route_type` in `examples/gateway/config.yaml`
  examples/gateway/config.yaml
Labels: gateway

#8780 Test dynamic routes in test_app.py
  tests/gateway/providers/test_openai.py
  tests/gateway/test_gateway_app.py
  tests/gateway/test_runner.py
  tests/gateway/tools.py
Labels: rn/none, gateway

#8781 Improve config type
  mlflow/gateway/config.py
  mlflow/gateway/providers/openai.py
  tests/gateway/test_gateway_config_parsing.py
Labels: rn/none, gateway

#8794 Gateway fix GetRoute return structure
  mlflow/gateway/app.py
  mlflow/gateway/client.py
  tests/gateway/test_gateway_app.py
  tests/gateway/test_runner.py
Labels: rn/none, area/server-infra, gateway

#8800 Fix link to Azure ML documentation 📗
  docs/source/quickstart_mlops.rst
Labels: area/docs, rn/documentation

#8778 Add the Anthropic provider to Gateway
  .github/workflows/gateway.yml
  mlflow/gateway/providers/anthropic.py
  mlflow/gateway/providers/openai.py
  mlflow/gateway/schemas/completions.py
  requirements/gateway-requirements.txt
  requirements/gateway-requirements.yaml
  tests/gateway/providers/test_anthropic.py
Labels: rn/feature, area/server-infra

#8802 [Gateway] remove placeholder providers
  mlflow/gateway/config.py
  tests/gateway/test_gateway_config_parsing.py
Labels: rn/none, area/server-infra

#8782 Implement automatic signature inference for other flavors
  mlflow/catboost.py
  mlflow/gluon/__init__.py
  mlflow/h2o.py
  mlflow/lightgbm.py
  mlflow/paddle/__init__.py
  mlflow/pmdarima.py
  mlflow/prophet.py
  mlflow/pytorch/__init__.py
  mlflow/sentence_transformers.py
  mlflow/statsmodels.py
  tests/catboost/test_catboost_model_export.py
  tests/gluon/test_gluon_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/pmdarima/test_pmdarima_model_export.py
  tests/prophet/test_prophet_model_export.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sentence_transformers/test_sentence_transformers_model_export.py
  tests/statsmodels/model_fixtures.py
  tests/statsmodels/test_statsmodels_model_export.py
Labels: rn/feature, area/models, only-latest

#8761 Update models docs to include signature inference
  docs/source/models.rst
  mlflow/models/utils.py
Labels: area/docs, rn/none

#8803 Add support for listing artifacts in UC model registry artifact repo
  mlflow/store/artifact/unity_catalog_models_artifact_repo.py
  tests/store/artifact/test_unity_catalog_models_artifact_repo.py
Labels: rn/none

#8804 Gateway add CRUD APIs
  mlflow/gateway/__init__.py
  mlflow/gateway/app.py
  mlflow/gateway/client.py
  mlflow/gateway/constants.py
  mlflow/gateway/fluent.py
  mlflow/gateway/utils.py
  tests/gateway/test_client.py
  tests/gateway/test_fluent.py
  tests/gateway/test_gateway_app.py
  tests/gateway/test_gateway_config_parsing.py
Labels: rn/none, area/server-infra

#8798 Add REST API documentation for MLflow Gateway
  docs/Makefile
  docs/gateway_api_docs.py
  docs/source/gateway/index.rst
  docs/source/index.rst
  mlflow/gateway/app.py
  mlflow/gateway/schemas/chat.py
  mlflow/gateway/schemas/completions.py
  mlflow/gateway/schemas/embeddings.py
Labels: rn/none, gateway

#8796 Gateway refactor provider request utilities
  mlflow/gateway/providers/__init__.py
  mlflow/gateway/providers/anthropic.py
  mlflow/gateway/providers/openai.py
  mlflow/gateway/providers/utils.py
  tests/gateway/providers/test_utils.py
  tests/gateway/test_client.py
Labels: rn/none, area/server-infra

#8765 Remove deprecation warning from MlflowClient.download_artifacts()
  mlflow/tracking/client.py
Labels: rn/none, area/tracking

#8805 Gateway: Reintroduce Databricks model serving provider
  mlflow/gateway/config.py
Labels: rn/none, area/build

#8811 Add response models to static routes
  mlflow/gateway/app.py
Labels: rn/none, gateway

#8806 Add a provider for Cohere
  examples/gateway/cohere.yaml
  mlflow/gateway/config.py
  mlflow/gateway/providers/__init__.py
  mlflow/gateway/providers/cohere.py
  mlflow/gateway/schemas/chat.py
  mlflow/gateway/schemas/embeddings.py
  tests/gateway/providers/test_cohere.py
Labels: rn/none, gateway

#8812 Fix request examples
  mlflow/gateway/schemas/chat.py
  mlflow/gateway/schemas/completions.py
Labels: rn/none, gateway

#8815 Update CreateModelVersionRequest msg
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
Labels: rn/none, area/models

#8826 Rename `examples/gateway/config.yaml` to `examples/gateway/openai.yaml`
  examples/gateway/README.md
  examples/gateway/openai.yaml
Labels: rn/none, gateway

#8824 [Gateway] Fix the anthropic provider
  examples/gateway/anthropic.yaml
  mlflow/gateway/providers/anthropic.py
  tests/gateway/test_client.py
Labels: rn/bug-fix, area/server-infra, gateway

#8818 Remove useless attribute initialization in `mlflow/server/auth/sqlalchemy_store.py`
  mlflow/server/auth/sqlalchemy_store.py
Labels: rn/none

#8825 Simplify `_get_managed_session_maker`
  mlflow/store/db/utils.py
Labels: rn/none

#8814 Suppress error in `end_run` when called from `atexit`
  mlflow/tracking/fluent.py
Labels: rn/none

#8819 Remove assignment to `Base.metadata.bind`
  mlflow/server/auth/sqlalchemy_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/store/tracking/sqlalchemy_store.py
Labels: rn/none

#8837 Remove fluent function calls in auth
  mlflow/server/auth/__init__.py
Labels: rn/none

#8838 Replace `_TRACKING_PASSWORD_ENV_VAR` and `_TRACKING_PASSWORD_ENV_VAR`
  mlflow/server/auth/__init__.py
  mlflow/tracking/_model_registry/utils.py
  mlflow/tracking/_tracking_service/utils.py
  tests/server/auth/auth_test_utils.py
  tests/server/auth/test_auth.py
  tests/server/auth/test_client.py
  tests/store/artifact/test_http_artifact_repo.py
  tests/tracking/_tracking_service/test_utils.py
Labels: rn/none

#8833 Make `is_admin` bool in `update_user_admin`
  mlflow/server/auth/__init__.py
  mlflow/server/auth/client.py
Labels: rn/none
