Repository mlflow/mlflow, pull requests merged in 2023-04, with the labels that each got.

#8143 Remove `try-catch` in `cloud_storage_http_request`
  mlflow/utils/rest_utils.py
  tests/store/artifact/test_databricks_artifact_repo.py
Labels: rn/none

#8119 [Feature Branch] Dataset and source for HuggingFace
  .github/workflows/master.yml
  mlflow/data/artifact_dataset_sources.py
  mlflow/data/dataset_registry.py
  mlflow/data/dataset_source.py
  mlflow/data/dataset_source_registry.py
  mlflow/data/digest_utils.py
  mlflow/data/filesystem_dataset_source.py
  mlflow/data/huggingface_dataset.py
  mlflow/data/huggingface_dataset_source.py
  mlflow/data/pyfunc_dataset_mixin.py
  requirements/extra-ml-requirements.txt
  tests/data/test_huggingface_dataset_and_source.py
  tests/resources/data/dataset_source.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/dummy_dataset_source.py
Labels: rn/feature, area/tracking

#8144 Fix `augmented_raise_for_status` to preserve request and response attributes in original error
  mlflow/utils/rest_utils.py
  tests/utils/test_rest_utils.py
Labels: rn/none

#8148 Remove assignment to `return_value` and `side_effect`
  tests/store/artifact/test_databricks_artifact_repo.py
Labels: rn/none

#8147 Fix DISABLE_NGINX positive value across docs and tests
  mlflow/sagemaker/__init__.py
  tests/sagemaker/test_sagemaker_deployment_client.py
Labels: area/docs, rn/none

#8152 Migrate `tests/store/artifact/test_databricks_artifact_repo.py` to pytest style
  tests/store/artifact/test_databricks_artifact_repo.py
Labels: rn/none

#8128 [Feature branch] DB and schema for Datasets
  mlflow/entities/__init__.py
  mlflow/entities/dataset.py
  mlflow/entities/dataset_input.py
  mlflow/entities/input_tag.py
  mlflow/entities/run.py
  mlflow/entities/run_inputs.py
  mlflow/java/client/src/main/java/com/databricks/api/proto/databricks/Databricks.java
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/databricks.proto
  mlflow/protos/databricks_pb2.py
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
  mlflow/store/db_migrations/versions/7f2a7d5fae7d_add_datasets_inputs_input_tags_tables.py
  mlflow/store/tracking/dbmodels/models.py
  tests/entities/conftest.py
  tests/entities/test_dataset.py
  tests/entities/test_dataset_input.py
  tests/entities/test_input_tag.py
  tests/entities/test_run.py
  tests/entities/test_run_inputs.py
  tests/resources/db/latest_schema.sql
  tests/store/tracking/test_sqlalchemy_store.py
  tests/store/tracking/test_sqlalchemy_store_schema.py
Labels: rn/none, area/tracking, area/sqlalchemy

#8094 Added alias support to MLflow client
  mlflow/entities/model_registry/registered_model.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/client.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/tracking/_model_registry/test_model_registry_client.py
  tests/tracking/test_client.py
  tests/tracking/test_model_registry.py
Labels: rn/feature, area/model-registry

#8158 Sync error code proto
  mlflow/exceptions.py
  mlflow/java/client/src/main/java/com/databricks/api/proto/databricks/Databricks.java
  mlflow/protos/databricks.proto
  mlflow/protos/databricks_pb2.py
Labels: rn/none

#8165 Increase wait time threshold for tracking server to 20 seconds on windows
  tests/tracking/integration_test_utils.py
Labels: rn/none

#8111 [Feature branch] Add Numpy and Pandas Datasets
  mlflow/data/dataset_registry.py
  mlflow/data/delta_dataset_source.py
  mlflow/data/digest_utils.py
  mlflow/data/numpy_dataset.py
  mlflow/data/pandas_dataset.py
  mlflow/data/spark_dataset_source.py
  tests/data/test_delta_dataset_source.py
  tests/data/test_numpy_dataset.py
  tests/data/test_pandas_dataset.py
  tests/data/test_spark_dataset_source.py
Labels: rn/none, area/tracking

#8161 Run PySpark <= 3.3.0 tests with pandas < 2
  mlflow/ml-package-versions.yml
  mlflow/spark.py
  tests/spark/test_spark_model_export.py
Labels: rn/none, area/build

#8112 Parallelize chunk uploads in a multipart upload
  mlflow/azure/client.py
  mlflow/store/artifact/artifact_repo.py
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/utils/file_utils.py
  tests/store/artifact/test_databricks_artifact_repo.py
Labels: rn/none, area/artifacts

#8139 Disallow local model version source and `..` in path parameter
  mlflow/environment_variables.py
  mlflow/server/handlers.py
  mlflow/utils/file_utils.py
  mlflow/utils/os.py
  mlflow/utils/uri.py
  tests/tracking/integration_test_utils.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#8146 [Feature Branch] File store for MLflow datasets
  dev/generate-protos.sh
  mlflow/java/client/src/main/java/com/databricks/api/proto/databricks/Databricks.java
  mlflow/java/client/src/main/java/org/mlflow/internal/proto/Internal.java
  mlflow/protos/databricks.proto
  mlflow/protos/databricks_pb2.py
  mlflow/protos/internal.proto
  mlflow/protos/internal_pb2.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_file_store.py
Labels: rn/none, area/tracking

#8164 Add alias support to model URI parsing and disallow reserved aliases
  mlflow/models/wheeled_model.py
  mlflow/store/artifact/utils/models.py
  mlflow/utils/validation.py
  tests/store/artifact/utils/test_model_utils.py
  tests/utils/test_validation.py
Labels: rn/feature, area/model-registry

#8172 [Feature branch] log_input fluent api
  mlflow/__init__.py
  mlflow/data/dataset.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  mlflow/utils/mlflow_tags.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/none, area/tracking

#8185 [Feature branch] python server log inputs
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, area/server-infra

#8192 Remove dev suffix in `mlserver` requirements
  mlflow/entities/model_registry/model_version.py
  mlflow/models/container/__init__.py
  setup.py
  tests/test_cli.py
Labels: rn/none

#8198 Remove protobuf dependency in `tests/tensorflow/test_keras_model_export.py::test_pyfunc_serve_and_score`
  tests/tensorflow/test_keras_model_export.py
Labels: rn/none

#8154 Fix: Renaming a run discards its current status and reverts the run status back to UNFINISHED
  mlflow/server/handlers.py
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/test_rest_tracking.py
Labels: rn/bug-fix, area/tracking

#8201 create a code dataset source
  mlflow/data/code_dataset_source.py
  tests/data/test_code_dataset_source.py
Labels: rn/none

#8203 Adjust formatting to registry client logger and exception messages
  mlflow/tracking/_model_registry/client.py
Labels: rn/none, area/tracking

#8156 Fix: "Source Run" field in Model Version UI page points to wrong run model artifact in Run UI page
  mlflow/server/js/src/experiment-tracking/routes.js
  mlflow/server/js/src/model-registry/components/ModelVersionView.js
  mlflow/server/js/src/model-registry/utils/VersionUtils.test.ts
  mlflow/server/js/src/model-registry/utils/VersionUtils.ts
Labels: rn/bug-fix

#8116 Implement parallelized artifact/model downloads using range headers
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/utils/file_utils.py
  mlflow/utils/rest_utils.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/utils/test_file_utils.py
Labels: rn/feature, area/model-registry, area/tracking, integrations/databricks

#8204 Adding the ability to log LLM predictions to MLflow artifacts
  mlflow/__init__.py
  mlflow/llm.py
  mlflow/tracking/llm_utils.py
  tests/tracking/test_llm_utils.py
Labels: rn/feature, area/tracking

#8221 Pin mlserver and mlserver-mlflow due to protobuf issue with 1.3 release
  mlflow/models/container/__init__.py
  requirements/test-requirements.txt
  setup.py
  tests/test_cli.py
Labels: rn/none, area/build

#8151 Spark Dataset for MLflow Tracking
  mlflow/data/dataset_registry.py
  mlflow/data/delta_dataset_source.py
  mlflow/data/huggingface_dataset.py
  mlflow/data/spark_dataset.py
  mlflow/data/spark_dataset_source.py
  mlflow/data/spark_delta_utils.py
  tests/data/test_spark_dataset.py
Labels: rn/none, area/tracking

#8178 Fix `delete_experiment` and `restore_experiment` in FileStore implementation
  mlflow/store/tracking/file_store.py
  tests/store/tracking/test_file_store.py
Labels: rn/bug-fix, area/tracking

#8218 Tensorflow Dataset for MLflow tracking
  mlflow/data/dataset_registry.py
  mlflow/data/digest_utils.py
  mlflow/data/tensorflow_dataset.py
  tests/data/test_tensorflow_dataset.py
Labels: rn/none, area/tracking

#8181 Add support for transformers pyfunc
  .gitignore
  mlflow/deployments/__init__.py
  mlflow/ml-package-versions.yml
  mlflow/models/signature.py
  mlflow/models/utils.py
  mlflow/transformers.py
  mlflow/types/utils.py
  mlflow/utils/proto_json_utils.py
  requirements/test-requirements.txt
  setup.py
  tests/transformers/test_transformers_model_export.py
  tests/types/test_schema.py
Labels: rn/feature, area/models, area/tracking

#8228 Remove special test for Spark RC due to 3.4 release
  .github/workflows/master.yml
Labels: rn/none, area/build

#8210 Update Model URI Regex to work with UC Model names
  mlflow/store/artifact/utils/models.py
  tests/store/artifact/utils/test_model_utils.py
Labels: rn/none, area/model-registry

#8130 Implement authentication for HTTP Basic Auth
  .gitignore
  conftest.py
  dev/run-python-flavor-tests.sh
  mlflow/server/auth/__init__.py
  mlflow/server/auth/basic_auth.ini
  mlflow/server/auth/config.py
  mlflow/server/auth/entities.py
  mlflow/server/auth/sqlalchemy_store.py
  mlflow/server/handlers.py
  mlflow/utils/validation.py
  tests/server/auth/__init__.py
  tests/server/auth/test_auth.py
  tests/server/auth/test_sqlalchemy_store.py
  tests/tracking/integration_test_utils.py
Labels: rn/feature

#8187 Chunk artifact list before generating credentials and uploading on Databricks
  mlflow/store/artifact/databricks_artifact_repo.py
  tests/store/artifact/test_databricks_artifact_repo.py
Labels: rn/none, area/tracking, integrations/databricks

#8219 Allow model registry client to accept `ALREADY_EXISTS` error code
  mlflow/tracking/_model_registry/fluent.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
Labels: rn/none, area/model-registry, integrations/databricks

#8191 Implement pyfunc improvements
  mlflow/models/signature.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
  mlflow/types/schema.py
  mlflow/types/utils.py
  mlflow/utils/_capture_modules.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/feature

#8155 OpenAI flavor
  conftest.py
  docs/source/python_api/mlflow.openai.rst
  examples/openai/pyfunc.py
  examples/openai/spark_udf.py
  mlflow/__init__.py
  mlflow/environment_variables.py
  mlflow/ml-package-versions.yml
  mlflow/openai/__init__.py
  mlflow/openai/api_request_parallel_processor.py
  mlflow/openai/retry.py
  mlflow/openai/utils.py
  mlflow/pyfunc/__init__.py
  requirements/extra-ml-requirements.txt
  tests/openai/test_openai_model_export.py
Labels: rn/feature, area/models

#8242 Add `openai` flavor in `model.rst`
  docs/source/models.rst
  examples/openai/pyfunc.py
Labels: rn/none

#8243 Remove `aiohttp` from openai flavor
  mlflow/openai/__init__.py
  requirements/extra-ml-requirements.txt
Labels: rn/none

#8245 Fix captum example
  examples/pytorch/CaptumExample/Titanic_Captum_Interpret.py
Labels: rn/none

#8230 Removing the experimental tag for MLflow Recipes and stabalizing the API
  docs/source/python_api/mlflow.recipes.rst
  docs/source/recipes.rst
  mlflow/recipes/classification/v1/recipe.py
  mlflow/recipes/cli.py
  mlflow/recipes/recipe.py
  mlflow/recipes/regression/v1/recipe.py
  mlflow/recipes/step.py
  mlflow/recipes/steps/automl/flaml.py
  mlflow/recipes/steps/predict.py
  mlflow/recipes/steps/split.py
Labels: rn/breaking-change, area/recipes

#8236 Add documentation and examples for transformers flavor
  docs/source/models.rst
  examples/pytorch/CaptumExample/Titanic_Captum_Interpret.py
  examples/transformers/conversational.py
  examples/transformers/load_components.py
  examples/transformers/simple.py
  mlflow/transformers.py
  requirements/extra-ml-requirements.txt
  tests/examples/test_examples.py
Labels: area/docs, rn/feature, area/examples

#8250 Adjust ordering of flavor docs
  docs/source/models.rst
Labels: area/docs, rn/none

#7955 Allow creating wheels from source packaging.
  mlflow/environment_variables.py
  mlflow/models/wheeled_model.py
  tests/models/test_wheeled_model.py
Labels: rn/none, area/models

#8248 Replace `Inspector.from_engine` with `sqlalchemy.inspect`
  mlflow/store/db_migrations/versions/3500859a5d39_add_model_aliases_table.py
Labels: rn/none

#8197 Implement langchain flavor
  conftest.py
  docs/source/python_api/mlflow.langchain.rst
  examples/langchain/simple_chain.py
  mlflow/__init__.py
  mlflow/langchain/__init__.py
  mlflow/langchain/api_request_parallel_processor.py
  mlflow/ml-package-versions.yml
  mlflow/openai/utils.py
  requirements/extra-ml-requirements.txt
  tests/langchain/test_langchain_model_export.py
Labels: rn/feature, area/tracking

#8251 [Docs] Adding langchain flavor docs
  docs/source/models.rst
Labels: rn/documentation, area/tracking

#8199 Remove shap as core dependency
  mlflow/recipes/steps/evaluate.py
  requirements/core-requirements.txt
  requirements/core-requirements.yaml
  requirements/extra-ml-requirements.txt
  requirements/test-requirements.txt
Labels: rn/bug-fix, area/tracking, area/recipes

#8223 Add `search_model_versions` to high-level fluent API
  mlflow/__init__.py
  mlflow/tracking/_model_registry/fluent.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/feature, area/model-registry, area/tracking

#8253 Support one-column 2d array in schema enforcement
  mlflow/models/utils.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
Labels: rn/none

#8255 Ignore files path or URLs when checking dependencies
  mlflow/utils/requirements_utils.py
  tests/pyfunc/test_dependencies_functions.py
Labels: rn/none

#8234 Adding LLM Tracking docs
  docs/source/index.rst
  docs/source/llm-tracking.rst
  docs/source/python_api/mlflow.llm.rst
  mlflow/__init__.py
  mlflow/llm.py
  mlflow/tracking/llm_utils.py
Labels: rn/documentation, area/tracking

#8258 Fix IN comparison parsing
  mlflow/utils/search_utils.py
Labels: rn/none

#8252 Add InstructionalPipeline support and fix inference config bug
  mlflow/transformers.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/none, area/models

#8262 Fix cross version test dependencies for langchain
  mlflow/__init__.py
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#8263 [Bug-fix] fixing null columns profiling for MLflow Recipes
  mlflow/recipes/cards/pandas_renderer.py
  tests/recipes/cards/test_pandas_renderer.py
Labels: rn/bug-fix, area/recipes

#8267 Fix sklearn example
  examples/sklearn_elasticnet_wine/conda.yaml
  examples/sklearn_elasticnet_wine/python_env.yaml
Labels: rn/none, area/examples

#8268 Fix IN comparison parsing
  mlflow/utils/search_utils.py
  tests/store/model_registry/test_file_store.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#8272 Improve `examples/langchain/simple_chain.py`
  examples/langchain/simple_chain.py
  examples/openai/pyfunc.py
  examples/openai/spark_udf.py
Labels: rn/none

#8270 Handle cyclic dependencies in dependency inference
  mlflow/utils/requirements_utils.py
  tests/pytorch/test_pytorch_model_export.py
Labels: rn/none, only-latest

#8271 Improve `set_experiment` doc
  mlflow/tracking/fluent.py
Labels: rn/documentation

#8241 Unpin mlserver
  mlflow/models/container/__init__.py
  requirements/test-requirements.txt
  setup.py
  tests/test_cli.py
Labels: rn/none

#8257 Improve virtualenv python environment hash computation
  mlflow/utils/virtualenv.py
Labels: rn/none

#8282 Fix `openai.yaml` example
  mlflow/openai/__init__.py
Labels: rn/none, area/models

#8235 Add core tensorflow 2.x api example to mlflow/examples
  examples/README.md
  examples/tensorflow/MLProject
  examples/tensorflow/conda.yaml
  examples/tensorflow/python_env.yaml
  examples/tensorflow/train.py
  tests/examples/test_examples.py
Labels: rn/documentation, area/examples

#8285 Make `OpenAIEnvVar` private
  mlflow/openai/__init__.py
  mlflow/pyfunc/__init__.py
Labels: rn/none

#8284 Fix incorrect argument name in langchain flavor
  mlflow/langchain/__init__.py
Labels: rn/none

#8283 Remove `model_format` in `mlflow.openai.log_model` docstring
  mlflow/openai/__init__.py
Labels: rn/none, area/models

#8281 Disable ability to provide relative paths in sources
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/bug-fix, area/server-infra

#8279 Invert the default output parsing for TextGenerator subtypes
  docs/source/models.rst
  mlflow/transformers.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/none, area/models

#8293 Simplify `collapse_whitespace` implementation
  mlflow/transformers.py
Labels: rn/none

#8295 pin r version due to broken devtools in latest release
  .github/workflows/r.yml
Labels: language/r, rn/none, area/build

#8291 Fix openai flavor impelementation to support formatting messages with prediction input
  docs/source/python_api/index.rst
  docs/source/python_api/openai/index.rst
  docs/source/python_api/openai/messages.rst
  examples/openai/pyfunc.py
  examples/openai/spark_udf.py
  mlflow/openai/__init__.py
  mlflow/openai/api_request_parallel_processor.py
  mlflow/openai/utils.py
  tests/openai/test_openai_model_export.py
Labels: rn/breaking-change

#8308 Make `self.inference_config` default to empty dictionary
  mlflow/transformers.py
Labels: rn/none

#8307 Add alias support to UC Model Registry REST Store
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/protos/databricks_uc_registry_service.proto
  mlflow/protos/databricks_uc_registry_service_pb2.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/feature, area/model-registry

#8305 [Feature branch] NumPy dataset fix: incorporate targets into schema and profile
  mlflow/data/numpy_dataset.py
  tests/data/test_numpy_dataset.py
Labels: rn/none, area/tracking

#8314 [Feature branch] Make mlflow.data available when users import mlflow
  mlflow/__init__.py
Labels: rn/none, area/tracking

#8315 [Feature branch] Change MLflow dataset placeholder name to "dataset"
  mlflow/data/dataset.py
  tests/data/test_dataset.py
Labels: rn/none, area/tracking

#8292 added a h2o pyfunc usage example
  docs/source/models.rst
Labels: area/docs, rn/documentation

#8316 Update `pyfunc.log_model` doc
  mlflow/pyfunc/__init__.py
Labels: rn/none

#8319 Insert databricks profile in artifact URI before initializing artifact repo in `mlflow.artifacts.download_artifacts`
  mlflow/artifacts/__init__.py
Labels: rn/none

#8300 [Feature branch] Small improvements to dataset sources
  .github/workflows/master.yml
  mlflow/data/__init__.py
  mlflow/data/dataset_registry.py
  mlflow/data/dataset_source_registry.py
  mlflow/data/sources.py
  mlflow/data/tensorflow_dataset.py
  requirements/extra-ml-requirements.txt
  tests/data/test_dataset_source_registry.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/none, area/tracking

#8325 Fix bug when registering model version to UC with non-Databricks tracking URI configured
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/none, autoformat

#8323 Add a helper function to get MlflowCredentialContext by run_id
  mlflow/utils/databricks_utils.py
  tests/utils/test_databricks_utils.py
Labels: rn/none, area/tracking

#8324 Improve UC model registry client error messages when specifying nonexistent source files or missing Python dependencies
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/_unity_catalog/registry/utils.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/none, autoformat

#8318 [Feature branch] Introduce mlflow.data.get_source() API
  mlflow/data/__init__.py
  tests/data/test_dataset_source.py
Labels: rn/none, area/tracking

#8326 Fix regression in schema enforcement
  mlflow/models/utils.py
  mlflow/transformers.py
  mlflow/types/utils.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
  tests/pyfunc/test_scoring_server.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/bug-fix, area/models, area/scoring

#8331 Create a new request session in each process
  mlflow/utils/file_utils.py
  mlflow/utils/rest_utils.py
  tests/utils/test_rest_utils.py
Labels: rn/none

#8328 Remove virtualenv environment if we encounter unexpected error
  mlflow/utils/file_utils.py
  mlflow/utils/virtualenv.py
  tests/pyfunc/test_virtualenv.py
Labels: rn/none

#8327 Migrate `TestDatabricksModelArtifactRepository` to pytest style
  tests/store/artifact/test_databricks_models_artifact_repo.py
Labels: rn/none

#8335 Fix (doc): Update the link for sktime deployment
  docs/source/models.rst
Labels: rn/none

#8194 [Feature branch] Support Dataset in `mlflow.evaluate`
  mlflow/data/huggingface_dataset.py
  mlflow/data/numpy_dataset.py
  mlflow/data/pandas_dataset.py
  mlflow/data/pyfunc_dataset_mixin.py
  mlflow/data/spark_dataset.py
  mlflow/data/tensorflow_dataset.py
  mlflow/models/evaluation/base.py
  tests/data/test_huggingface_dataset_and_source.py
  tests/data/test_numpy_dataset.py
  tests/data/test_pandas_dataset.py
  tests/data/test_spark_dataset.py
  tests/data/test_tensorflow_dataset.py
  tests/models/test_evaluation.py
Labels: rn/none, area/tracking

#8304 [Feature Branch] Fix naming issue for Spark datasets loaded from Delta, improve test coverage
  mlflow/data/spark_dataset.py
  tests/data/test_spark_dataset.py
Labels: rn/none, area/tracking

#8302 [Feature branch] Mark datasets as experimental
  mlflow/data/artifact_dataset_sources.py
  mlflow/data/code_dataset_source.py
  mlflow/data/dataset.py
  mlflow/data/dataset_source.py
  mlflow/data/delta_dataset_source.py
  mlflow/data/filesystem_dataset_source.py
  mlflow/data/huggingface_dataset.py
  mlflow/data/huggingface_dataset_source.py
  mlflow/data/numpy_dataset.py
  mlflow/data/pandas_dataset.py
  mlflow/data/spark_dataset.py
  mlflow/data/spark_dataset_source.py
  mlflow/data/tensorflow_dataset.py
  mlflow/entities/dataset.py
  mlflow/entities/dataset_input.py
  mlflow/entities/input_tag.py
  mlflow/store/tracking/abstract_store.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: rn/none, area/tracking

#8338 Handle slashes in `_validate_non_local_source_contains_relative_paths`
  mlflow/server/handlers.py
  mlflow/utils/requirements_utils.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#8337 Handle slashes in `_validate_non_local_source_contains_relative_paths`
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#8202 [Feature branch] Autologging for datasets
  mlflow/data/digest_utils.py
  mlflow/data/numpy_dataset.py
  mlflow/data/spark_dataset.py
  mlflow/data/tensorflow_dataset.py
  mlflow/fastai/__init__.py
  mlflow/gluon/__init__.py
  mlflow/lightgbm.py
  mlflow/pyspark/ml/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/statsmodels.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tensorflow/__init__.py
  mlflow/tracking/fluent.py
  mlflow/utils/autologging_utils/client.py
  mlflow/utils/validation.py
  mlflow/xgboost/__init__.py
  tests/data/test_spark_dataset.py
  tests/lightgbm/test_lightgbm_autolog.py
  tests/sklearn/test_sklearn_autolog.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tensorflow/test_tensorflow2_autolog.py
  tests/tracking/fluent/test_fluent_autolog.py
  tests/xgboost/test_xgboost_autolog.py
Labels: rn/none, area/tracking, only-latest

#8340 Run `test_search_model_versions` faster
  tests/tracking/fluent/test_fluent.py
Labels: rn/none

#8341 add MLFLOW_DATABRICKS_NOTEBOOK_ID to code dataset source
  mlflow/data/code_dataset_source.py
  mlflow/lightgbm.py
  mlflow/pyspark/ml/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/tensorflow/__init__.py
  mlflow/xgboost/__init__.py
  tests/data/test_code_dataset_source.py
Labels: rn/none, area/tracking, only-latest

#8343 Fix naming for sklearn autologged datasets
  mlflow/sklearn/__init__.py
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/none, area/tracking, only-latest

#8347 Fix RunInputs to return entity instead of proto
  mlflow/entities/run_inputs.py
  tests/entities/test_run_inputs.py
Labels: rn/none, area/tracking

#8344 Use CodeDatasetSource if source info not provided
  mlflow/data/huggingface_dataset.py
  mlflow/data/numpy_dataset.py
  mlflow/data/pandas_dataset.py
  mlflow/data/spark_dataset.py
  mlflow/data/tensorflow_dataset.py
  tests/data/test_huggingface_dataset_and_source.py
  tests/data/test_numpy_dataset.py
  tests/data/test_pandas_dataset.py
  tests/data/test_spark_dataset.py
  tests/data/test_tensorflow_dataset.py
Labels: rn/none, area/tracking

#8351 [branch-2.3] Revert multipart download support for Databricks
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/utils/file_utils.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/utils/test_file_utils.py
Labels: rn/bug-fix

#8349 Use separate thread pool executors when uploading chunks to avoid deadlock
  mlflow/store/artifact/artifact_repo.py
  mlflow/store/artifact/databricks_artifact_repo.py
Labels: rn/none

#8348 Use separate thread pool executors when uploading chunks to avoid deadlock
  mlflow/store/artifact/artifact_repo.py
  mlflow/store/artifact/databricks_artifact_repo.py
Labels: rn/none

#8350 Revert multipart download support for Databricks
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/utils/file_utils.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/utils/test_file_utils.py
Labels: rn/bug-fix

#8355 Make a short sleep to avoid busy waiting
  mlflow/langchain/api_request_parallel_processor.py
  mlflow/openai/api_request_parallel_processor.py
Labels: rn/none

#8353 Use pytest-timeout to detect tests that take long to finish
  pytest.ini
  requirements/test-requirements.txt
Labels: rn/none
