Repository mlflow/mlflow, pull requests merged in 2023-07, with the labels that each got.

#8909 Refactor `_use_tracking_uri` and use it in `tracking_uri_mock`
  mlflow/recipes/artifacts.py
  mlflow/tracking/_tracking_service/utils.py
  mlflow/utils/file_utils.py
  tests/conftest.py
Labels: rn/none

#8915 Fix `tests/dev/test_set_matrix.py`
  dev/set_matrix.py
Labels: rn/none, only-latest

#8913 fix gluon test
  mlflow/gluon/__init__.py
Labels: rn/none, enable-dev-tests

#8847 Replace `forbid` with `allow` in pydantic models for backward compatibility
  mlflow/gateway/config.py
  mlflow/gateway/schemas/chat.py
  mlflow/gateway/schemas/completions.py
  mlflow/gateway/schemas/embeddings.py
Labels: rn/none

#8873 Use ruff for linting python files
  .github/workflows/autoformat.yml
  .github/workflows/master.yml
  .github/workflows/matchers/ruff.json
  .github/workflows/recipe-template.yml
  .pre-commit-config.yaml
  mlflow/models/evaluation/validation.py
  mlflow/recipes/cards/pandas_renderer.py
  mlflow/utils/autologging_utils/__init__.py
  pylintrc
  pyproject.toml
  requirements/lint-requirements.txt
Labels: rn/none

#8922 Fix broken tests
  tests/gateway/test_client.py
  tests/gateway/test_fluent.py
  tests/gateway/test_gateway_app.py
  tests/gateway/test_runner.py
Labels: rn/none

#8921 Enable `flake8-comprehensions`
  mlflow/pyspark/ml/__init__.py
  mlflow/store/db/utils.py
  pylintrc
  pyproject.toml
  tests/pytorch/test_tensorboard_autolog.py
  tests/sagemaker/test_sagemaker_deployment_client.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none, only-latest

#8924 Fix spark cross version test failure
  tests/spark/test_spark_model_export.py
Labels: rn/none

#8925 Remove `pylint_plugins/set_checker.py`
  pylint_plugins/__init__.py
  pylint_plugins/errors.py
  pylint_plugins/set_checker.py
  pylint_plugins/tests/test_set_checker.py
Labels: rn/none, only-latest

#8930 Remove `singleton-comparison` rule
  pylintrc
Labels: rn/none

#8927 Repalce `.format` with f-string (1)
  tests/autologging/test_autologging_client.py
  tests/catboost/test_catboost_model_export.py
  tests/integration/utils.py
  tests/models/test_cli.py
  tests/models/test_model.py
  tests/onnx/test_onnx_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_scoring_server.py
  tests/pyfunc/test_spark.py
  tests/resources/db/initial_models.py
  tests/sagemaker/mock/__init__.py
  tests/sagemaker/test_batch_deployment.py
  tests/sagemaker/test_sagemaker_deployment_client.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/test_doctor.py
  tests/tracking/context/test_databricks_job_context.py
  tests/tracking/test_log_image.py
Labels: rn/none, only-latest

#8932 Remove `use-a-generator` and `unnecessary-comprehension`
  pylintrc
Labels: rn/none

#8929 Repalce `.format` with f-string (2)
  mlflow/entities/run_info.py
  mlflow/mleap.py
  mlflow/models/model.py
  mlflow/models/signature.py
  mlflow/models/utils.py
  mlflow/sagemaker/__init__.py
  mlflow/sagemaker/cli.py
  mlflow/server/handlers.py
  mlflow/shap.py
  mlflow/sklearn/utils.py
  mlflow/store/artifact/azure_blob_artifact_repo.py
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/model_registry/dbmodels/models.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/tracking/dbmodels/initial_models.py
  mlflow/store/tracking/dbmodels/models.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
  mlflow/types/schema.py
  mlflow/types/utils.py
  mlflow/utils/autologging_utils/safety.py
  mlflow/utils/rest_utils.py
  mlflow/utils/search_utils.py
Labels: rn/none, only-latest

#8920 [Gateway] Support Azure OpenAI
  examples/gateway/azure_openai.yaml
  mlflow/gateway/config.py
  mlflow/gateway/providers/openai.py
  mlflow/gateway/providers/utils.py
  mlflow/utils/uri.py
  tests/gateway/providers/test_openai.py
  tests/gateway/test_client.py
  tests/gateway/test_fluent.py
  tests/gateway/test_gateway_app.py
  tests/gateway/test_gateway_config_parsing.py
  tests/gateway/test_runner.py
  tests/gateway/tools.py
  tests/utils/test_uri.py
Labels: rn/none, area/tracking

#8914 Add support for defining default max_tokens for Anthropic in AI Gateway
  mlflow/gateway/constants.py
  mlflow/gateway/providers/anthropic.py
  tests/gateway/providers/test_anthropic.py
Labels: rn/none, area/server-infra, gateway

#8938 Gateway: Disallow candidate_count > 1 for anthropic
  mlflow/gateway/providers/anthropic.py
  tests/gateway/providers/test_anthropic.py
Labels: rn/none, area/tracking

#8937 pin pydantic
  requirements/gateway-requirements.txt
  requirements/gateway-requirements.yaml
Labels: rn/none, area/build, gateway

#8939 Gateway: Add PR / issue / FR area for Gateway
  .github/ISSUE_TEMPLATE/bug_report_template.yaml
  .github/ISSUE_TEMPLATE/feature_request_template.yaml
  .github/pull_request_template.md
  ISSUE_TRIAGE.rst
Labels: rn/none, area/tracking

#8933 Use ruff's `unused-variable` rule
  pylintrc
  pyproject.toml
Labels: rn/none

#8940 Gateway: Update pydantic response models to ignore extra / unrecognized fields, instead of including them
  mlflow/gateway/base_models.py
  mlflow/gateway/config.py
  mlflow/gateway/schemas/chat.py
  mlflow/gateway/schemas/completions.py
  mlflow/gateway/schemas/embeddings.py
Labels: rn/none, area/tracking

#8790 Gateway: Paginate SearchRoutes API
  mlflow/gateway/app.py
  mlflow/gateway/client.py
  mlflow/gateway/config.py
  mlflow/gateway/constants.py
  mlflow/gateway/fluent.py
  mlflow/gateway/providers/anthropic.py
  mlflow/gateway/utils.py
  tests/gateway/test_client.py
  tests/gateway/test_fluent.py
  tests/gateway/test_gateway_app.py
  tests/gateway/test_runner.py
Labels: rn/none, area/models, gateway

#8836 Fix favicon in API documentation
  docs/gateway_api_docs.py
  mlflow/gateway/app.py
  tests/gateway/test_gateway_app.py
Labels: rn/none, gateway

#8916 Migrate `TestParseDbUri` to pytest style
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#8944 Remove useless variable assignment
  mlflow/utils/autologging_utils/versioning.py
  tests/evaluate/test_validation.py
  tests/recipes/test_pipeline.py
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/none

#8943 Use ruff's `undefined-name` rule
  mlflow/recipes/utils/step.py
  pylintrc
  pyproject.toml
Labels: rn/none

#8945 Prefix fields in Cohere config with `cohere_`
  mlflow/gateway/config.py
  mlflow/gateway/providers/cohere.py
  tests/gateway/providers/test_cohere.py
Labels: rn/none, gateway

#8947 Migrate `TestMlflowException` to function style
  tests/test_exceptions.py
Labels: rn/none

#8946 Remove unused fixture imports
  tests/spark/autologging/conftest.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging_crossframework.py
  tests/spark/autologging/datasource/test_spark_disable_autologging.py
  tests/spark/autologging/utils.py
Labels: rn/none

#8948 Fix `pmdarima` cross-version test
  mlflow/ml-package-versions.yml
  tests/pmdarima/test_pmdarima_model_export.py
Labels: rn/none

#8952 Fix flaky `tests/tracking/fluent/test_fluent.py::test_search_experiments`
  tests/tracking/fluent/test_fluent.py
Labels: rn/none

#8950 Migrate `TestRun`
  tests/entities/test_run.py
Labels: rn/none

#8949 Migrate `super-with-arguments` and `useless-object-inheritance` to ruff
  pylintrc
  pyproject.toml
Labels: rn/none

#8954 Migrate `TestRestStore` to function style
  tests/store/tracking/test_rest_store.py
Labels: rn/none

#8955 Enable `UP031` rule
  mlflow/cli.py
  mlflow/entities/model_registry/model_version_status.py
  mlflow/entities/run_status.py
  mlflow/entities/source_type.py
  mlflow/entities/view_type.py
  mlflow/experiments.py
  mlflow/projects/__init__.py
  mlflow/projects/_project_spec.py
  mlflow/projects/backend/local.py
  mlflow/projects/databricks.py
  mlflow/projects/utils.py
  mlflow/pytorch/_lightning_autolog.py
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/store/artifact/dbfs_artifact_repo.py
  mlflow/store/db/utils.py
  mlflow/store/tracking/file_store.py
  mlflow/tensorflow/__init__.py
  mlflow/utils/gorilla.py
  mlflow/utils/search_utils.py
  mlflow/utils/uri.py
  mlflow/utils/validation.py
  pyproject.toml
  tests/models/test_cli.py
  tests/store/model_registry/test_sqlalchemy_store.py
Labels: rn/none, only-latest

#8951 Remove `HelperEnv`
  tests/tracking/fluent/test_fluent.py
Labels: rn/none

#8956 Fix `sentence-transformers` tests
  tests/sentence_transformers/test_sentence_transformers_model_export.py
Labels: rn/none

#8958 Enable `UP034` to remove extraneous parentheses
  mlflow/pytorch/_lightning_autolog.py
  pyproject.toml
  tests/recipes/test_split_step.py
  tests/recipes/test_train_step.py
  tests/store/artifact/test_databricks_artifact_repo.py
Labels: rn/none

#8960 Replace `str({})` with `"{}"`
  tests/deployments/test_cli.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/none

#8867 Include feature_deps in CreateModelVersionRequest
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/none, area/model-registry

#8959 Replace `_parse_datatype_string`
  mlflow/pyfunc/__init__.py
  tests/types/test_schema.py
Labels: rn/none

#8967 Remove `anthropic_api_base` and `cohere_api_base`
  examples/gateway/anthropic.yaml
  mlflow/gateway/config.py
  mlflow/gateway/providers/anthropic.py
  mlflow/gateway/providers/cohere.py
  tests/gateway/providers/test_anthropic.py
  tests/gateway/test_client.py
  tests/gateway/test_gateway_config_parsing.py
Labels: rn/none

#8968 Deprecate mxnet
  mlflow/gluon/__init__.py
Labels: rn/none

#8969 Run pipdeptree to show what pins what
  .github/actions/pipdeptree/action.yml
  .github/workflows/cross-version-tests.yml
  .github/workflows/master.yml
Labels: rn/none

#8962 Use f-strings
  examples/spacy/train.py
  tests/fastai/test_fastai_autolog.py
  tests/fastai/test_fastai_model_export.py
  tests/gluon/test_gluon_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/johnsnowlabs/test_johnsnowlabs_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/mleap/test_mleap_model_export.py
  tests/onnx/test_onnx_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
  tests/pytorch/test_pytorch_model_export.py
  tests/recipes/test_predict_step.py
  tests/sagemaker/test_sagemaker_deployment_client.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spacy/test_spacy_model_export.py
  tests/spark/test_spark_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/tensorflow/test_keras_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none, only-latest

#8970 Comment out mxnet-related code to avoid import mxnet
  tests/autologging/test_autologging_behaviors_integration.py
  tests/autologging/test_autologging_utils.py
  tests/check_mlflow_lazily_imports_ml_packages.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/none

#8982 Ignore `tests/evaluate` in python job
  dev/run-python-tests.sh
Labels: rn/none

#8987 Gateway: reintroduce /v1 to anthropic URL
  mlflow/gateway/providers/anthropic.py
Labels: rn/none, area/tracking

#8964 Add compatibility for legacy transformers serialization
  mlflow/transformers.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/bug-fix, area/models

#8936 Add additional examples for AI Gateway
  examples/gateway/README.md
  examples/gateway/anthropic/README.md
  examples/gateway/anthropic/config.yaml
  examples/gateway/anthropic/example.py
  examples/gateway/azure_openai/README.md
  examples/gateway/azure_openai/config.yaml
  examples/gateway/cohere/README.md
  examples/gateway/cohere/config.yaml
  examples/gateway/cohere/example.py
  examples/gateway/openai/README.md
  examples/gateway/openai/config.yaml
  examples/gateway/openai/example.py
  examples/gateway/request.py
Labels: rn/documentation, area/examples, gateway

#8984 Pin tensorflow in R test
  .github/workflows/r.yml
Labels: rn/none

#8983 Update maintainer list
  CONTRIBUTING.md
  README.rst
Labels: rn/none

#8991 Update docstring of new method
  mlflow/store/_unity_catalog/registry/rest_store.py
Labels: rn/none, area/model-registry, integrations/databricks

#8979 Skip CI if draft PR
  .github/workflows/advice.yml
  .github/workflows/cross-version-tests.yml
  .github/workflows/examples.yml
  .github/workflows/js.yml
  .github/workflows/labeling.yml
  .github/workflows/master.yml
  .github/workflows/preview-docs.yml
  .github/workflows/protos.yml
  .github/workflows/r.yml
  .github/workflows/recipe.yml
  .github/workflows/release-note-category.yml
  .github/workflows/requirements.yml
  .github/workflows/test-package-build.yml
Labels: rn/none

#8985 Pin tensorflow for older versions of transformers due to breaking Keras change
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#8966 Remove the Databricks Job Experiment creation code
  mlflow/tracking/default_experiment/databricks_job_experiment_provider.py
  mlflow/tracking/default_experiment/registry.py
  mlflow/utils/databricks_utils.py
  tests/tracking/default_experiment/test_databricks_job_experiment_provider.py
  tests/tracking/default_experiment/test_registry.py
  tests/utils/test_databricks_utils.py
Labels: rn/none, area/tracking, integrations/databricks

#8972 [Support inference params-1]Add ParamSchema and ParamSpec in model signature
  docs/source/conf.py
  mlflow/models/model.py
  mlflow/models/signature.py
  mlflow/models/utils.py
  mlflow/types/__init__.py
  mlflow/types/schema.py
  mlflow/types/utils.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
  tests/types/test_schema.py
Labels: rn/feature, area/models, only-latest

#8994 Remove useless checkout params
  .github/workflows/r.yml
Labels: rn/none

#8895 Include resources for recipes in mlflow-skinny
  setup.py
Labels: rn/none

#8973 [Support inference params-2]Add `params` for PyFunc predict
  examples/pyfunc/train.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
  mlflow/types/schema.py
  tests/db/check_migration.py
  tests/db/test_tracking_operations.py
  tests/evaluate/test_evaluation.py
  tests/openai/test_openai_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_pyfunc_class_methods.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
  tests/pyfunc/test_spark.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sentence_transformers/test_sentence_transformers_model_export.py
  tests/store/model_registry/test_file_store.py
  tests/test_cli.py
Labels: rn/feature, area/models, only-latest

#9002 Fix typo in models docs
  docs/source/models.rst
Labels: area/docs, rn/none, area/models

#9003 Activated Ruff rule: redundant-open-modes (UP015)
  mlflow/langchain/__init__.py
  mlflow/utils/file_utils.py
  pyproject.toml
  tests/data/test_artifact_dataset_sources.py
Labels: rn/none

#8934 Infer spark udf return type from model output schema
  mlflow/pyfunc/__init__.py
  mlflow/types/schema.py
  tests/pyfunc/test_spark.py
Labels: rn/feature, area/scoring

#9005 Address unresolved comments and refactoring for #8934
  mlflow/pyfunc/__init__.py
Labels: rn/none

#9007 Activated Ruff UP011 and UP012 rules
  .github/workflows/master.yml
  dev/set_matrix.py
  mlflow/utils/rest_utils.py
  pyproject.toml
Labels: rn/none, only-latest

#9011 Replace % formatting with f-string
  mlflow/_spark_autologging.py
  mlflow/cli.py
  tests/helper_functions.py
  tests/test_cli.py
Labels: rn/none

#9010 Activate ruff print-t20
  pylintrc
  pyproject.toml
  tests/resources/example_project/greeter.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/fake_deployment_plugin.py
Labels: rn/none

#9013 Update tests/sklearn/test_sklearn_autolog.py
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/none, area/build, only-latest

#9021 Remove unused imports
  tests/evaluate/test_default_evaluator.py
  tests/projects/backend/test_local.py
  tests/store/tracking/test_sqlalchemy_store_schema.py
Labels: rn/none, area/build

#9025 Remove useless pylint disable comment
  tests/check_mlflow_lazily_imports_ml_packages.py
Labels: rn/none, area/build

#9020 Update `_parse_spark_datatype`
  mlflow/pyfunc/__init__.py
Labels: rn/none

#9022 Throw `invalid_parameter_value` error
  mlflow/pyfunc/__init__.py
Labels: rn/none

#9023 Parametrize `test_check_spark_udf_return_type`
  tests/pyfunc/test_spark.py
Labels: rn/none

#9027 Remove `print-function` rule
  pylint_plugins/__init__.py
  pylint_plugins/errors.py
  pylint_plugins/print_function.py
  pylint_plugins/tests/test_print_function.py
Labels: rn/none

#9029 Remove useless `# pylint: disable=unused-import` comments
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: rn/none, area/build

#9031 Add windows job in CircleCI for investigating windows specific issues
  .circleci/config.yml
Labels: rn/none

#9030 fix: unused loader_template in mlflow/pyfunc/__init__.py
  mlflow/pyfunc/__init__.py
Labels: rn/none

#9032 Enable `unused-arguments` rule
  mlflow/data/artifact_dataset_sources.py
  mlflow/data/delta_dataset_source.py
  mlflow/data/spark_dataset_source.py
  mlflow/johnsnowlabs.py
  mlflow/langchain/api_request_parallel_processor.py
  mlflow/models/evaluation/_shap_patch.py
  mlflow/paddle/_paddle_autolog.py
  mlflow/pyfunc/__init__.py
  mlflow/transformers.py
  pylint_plugins/import_checker.py
  pylintrc
  tests/data/test_dataset_registry.py
  tests/onnx/test_onnx_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/sagemaker/mock/__init__.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/none, only-latest

#9036 Update model signature docs to center automatic signature inference
  docs/source/models.rst
Labels: area/docs, rn/none

#9038 remove gluon from examples test suite
  tests/examples/test_examples.py
Labels: rn/none, area/examples

#9037 fix shap cross version tests
  tests/shap/test_log.py
Labels: rn/none, area/build, enable-dev-tests

#9034 Fix model cross version tests for transformers
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build, enable-dev-tests

#9035 Fix dev transformers cross version test
  tests/transformers/test_transformers_model_export.py
Labels: rn/none, area/build, enable-dev-tests

#8903 Avoid redundant model version download when logging and registering model versions to UC via log_model
  mlflow/models/model.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/model_registry/rest_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
  tests/catboost/test_catboost_model_export.py
  tests/diviner/test_diviner_model_export.py
  tests/fastai/test_fastai_model_export.py
  tests/helper_functions.py
  tests/johnsnowlabs/test_johnsnowlabs_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/mleap/test_mleap_model_export.py
  tests/onnx/test_onnx_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/pmdarima/test_pmdarima_model_export.py
  tests/prophet/test_prophet_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sentence_transformers/test_sentence_transformers_model_export.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spark/test_spark_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/store/_unity_catalog/__init__.py
  tests/store/_unity_catalog/conftest.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/tensorflow/test_keras_model_export.py
  tests/tracking/_model_registry/test_model_registry_client.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
  tests/tracking/test_client.py
  tests/transformers/test_transformers_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none, only-latest

#8974 [Support inference params-3]Add inference params for all flavors
  examples/flower_classifier/image_pyfunc.py
  examples/pyfunc/train.py
  examples/sktime/flavor.py
  examples/transformers/simple.py
  mlflow/catboost.py
  mlflow/diviner.py
  mlflow/fastai/__init__.py
  mlflow/gluon/__init__.py
  mlflow/h2o.py
  mlflow/johnsnowlabs.py
  mlflow/langchain/__init__.py
  mlflow/lightgbm.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/onnx.py
  mlflow/openai/__init__.py
  mlflow/paddle/__init__.py
  mlflow/pmdarima.py
  mlflow/prophet.py
  mlflow/pyfunc/model.py
  mlflow/pytorch/__init__.py
  mlflow/recipes/utils/wrapped_recipe_model.py
  mlflow/sentence_transformers.py
  mlflow/shap.py
  mlflow/sklearn/__init__.py
  mlflow/spacy.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/tensorflow/__init__.py
  mlflow/transformers.py
  mlflow/xgboost/__init__.py
  tests/evaluate/test_default_evaluator.py
  tests/sentence_transformers/test_sentence_transformers_model_export.py
  tests/sklearn/test_sklearn_model_export.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/feature, area/models, only-latest

#8736 Support chains with unserializable components
  docs/source/models.rst
  examples/langchain/retrieval_qa_chain.py
  mlflow/langchain/__init__.py
  mlflow/ml-package-versions.yml
  tests/langchain/state_of_the_union.txt
  tests/langchain/test_langchain_model_export.py
Labels: area/docs, rn/feature, area/examples, area/models, autoformat

#9039 Do not log missing signature warning when automatic signature inference is triggered
  mlflow/models/model.py
Labels: rn/none, area/models

#9043 pin pytorch-lightning for breaking change in torchmetrics
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build, enable-dev-tests

#8763 Add docs and guide for MLflow Gateway
  docs/source/gateway/index.rst
  mlflow/gateway/cli.py
  mlflow/gateway/client.py
  mlflow/gateway/utils.py
Labels: area/docs, rn/documentation, gateway

#9014 Support nullable array type values as spark_udf return values
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_spark.py
Labels: rn/bug-fix, area/scoring

#9048 Explicitly declare Text2TextGeneration pipeline components for hub resolution failure
  tests/transformers/test_transformers_model_export.py
Labels: rn/none, area/build, enable-dev-tests

#9056 Fix for transformers models tests
  tests/transformers/test_transformers_model_export.py
Labels: rn/none, area/build, enable-dev-tests

#9054 Gateway refactor utils followup
  mlflow/gateway/utils.py
  tests/gateway/test_utils.py
Labels: rn/none, area/gateway

#9055 [Gateway] refactor env variables
  mlflow/environment_variables.py
  mlflow/gateway/envs.py
  mlflow/gateway/utils.py
  tests/gateway/test_client.py
  tests/gateway/test_fluent.py
  tests/gateway/test_utils.py
Labels: rn/none, area/gateway

#9060 [Gateway] disallow model argument to be passed during query
  mlflow/gateway/providers/anthropic.py
  mlflow/gateway/providers/base.py
  mlflow/gateway/providers/cohere.py
  mlflow/gateway/providers/openai.py
  tests/gateway/providers/test_anthropic.py
  tests/gateway/providers/test_cohere.py
  tests/gateway/providers/test_openai.py
  tests/gateway/test_client.py
  tests/gateway/test_fluent.py
Labels: rn/none, area/gateway

#8999 fix validate_path_is_safe function on windows
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, area/tracking

#9062 Fix Gateway API documentation
  docs/gateway_api_docs.py
Labels: rn/none

#9063 Fix default value of `MLFLOW_GATEWAY_URI`
  mlflow/environment_variables.py
Labels: rn/none

#9059 Revert inf params
  docs/source/conf.py
  examples/flower_classifier/image_pyfunc.py
  examples/pyfunc/train.py
  examples/sktime/flavor.py
  examples/transformers/simple.py
  mlflow/catboost.py
  mlflow/diviner.py
  mlflow/fastai/__init__.py
  mlflow/gluon/__init__.py
  mlflow/h2o.py
  mlflow/johnsnowlabs.py
  mlflow/langchain/__init__.py
  mlflow/lightgbm.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/models/model.py
  mlflow/models/signature.py
  mlflow/models/utils.py
  mlflow/onnx.py
  mlflow/openai/__init__.py
  mlflow/paddle/__init__.py
  mlflow/pmdarima.py
  mlflow/prophet.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
  mlflow/pytorch/__init__.py
  mlflow/recipes/utils/wrapped_recipe_model.py
  mlflow/sentence_transformers.py
  mlflow/shap.py
  mlflow/sklearn/__init__.py
  mlflow/spacy.py
  mlflow/spark.py
  mlflow/statsmodels.py
  mlflow/tensorflow/__init__.py
  mlflow/transformers.py
  mlflow/types/__init__.py
  mlflow/types/schema.py
  mlflow/types/utils.py
  mlflow/xgboost/__init__.py
  tests/db/check_migration.py
  tests/db/test_tracking_operations.py
  tests/evaluate/test_default_evaluator.py
  tests/evaluate/test_evaluation.py
  tests/openai/test_openai_model_export.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_pyfunc_class_methods.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
  tests/pyfunc/test_spark.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sentence_transformers/test_sentence_transformers_model_export.py
  tests/sklearn/test_sklearn_model_export.py
  tests/store/model_registry/test_file_store.py
  tests/test_cli.py
  tests/transformers/test_transformers_model_export.py
  tests/types/test_schema.py
Labels: rn/none, only-latest

#9069 [Gateway] Adjust client and server timeout settings
  mlflow/gateway/client.py
  mlflow/gateway/constants.py
  mlflow/gateway/providers/utils.py
  mlflow/utils/rest_utils.py
  tests/gateway/providers/test_openai.py
  tests/gateway/test_client.py
Labels: rn/none, area/gateway

#9000 Database migration for mlflow auth
  docs/source/auth/index.rst
  mlflow/server/auth/__main__.py
  mlflow/server/auth/cli.py
  mlflow/server/auth/db/__init__.py
  mlflow/server/auth/db/cli.py
  mlflow/server/auth/db/migrations/alembic.ini
  mlflow/server/auth/db/migrations/env.py
  mlflow/server/auth/db/migrations/script.py.mako
  mlflow/server/auth/db/migrations/versions/8606fa83a998_initial_migration.py
  mlflow/server/auth/db/utils.py
  mlflow/server/auth/sqlalchemy_store.py
  setup.py
  tests/server/auth/db/test_cli.py
  tests/server/auth/test_cli.py
Labels: rn/feature

#9070 Ignore IntegrityError when creating admin user
  mlflow/server/auth/__init__.py
Labels: rn/none

#8975 Enable authentication on proxy artifact routes
  mlflow/server/auth/__init__.py
  tests/server/auth/test_auth.py
Labels: rn/none

#9073 Run `python3 dev/update_ml_package_versions.py`
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
Labels: only-latest

#9075 Fix `_all_tables_exist`
  mlflow/store/db/utils.py
Labels: rn/none

#9074 Separate extras and package name in requirements YAML
  .github/actions/update-requirements/action.yml
  .github/workflows/requirements.yml
  dev/generate_requirements.py
  requirements/gateway-requirements.yaml
Labels: rn/none

#9071 Remove unnecessary debug calls in auth
  mlflow/server/auth/__init__.py
Labels: rn/none

#9076 Skip gateway job if PR is a draft
  .github/workflows/gateway.yml
Labels: rn/none

#9078 Fix curl examples in gateway docs
  docs/source/gateway/index.rst
Labels: rn/none

#9079 Fix `texts` to `text`
  docs/source/gateway/index.rst
Labels: rn/none, area/gateway

#9080 Run gateway workflow on push
  .github/workflows/gateway.yml
Labels: rn/none

#9081 Gateway docs tweaks / improvements
  docs/source/gateway/index.rst
Labels: area/docs, rn/none, area/gateway

#9083 Gateway: Improve documentation for query parameters
  docs/source/gateway/index.rst
Labels: area/docs, rn/none, area/gateway

#9088 Fix the default value of `candidate_count`
  mlflow/gateway/schemas/chat.py
  tests/gateway/providers/test_anthropic.py
  tests/gateway/providers/test_openai.py
Labels: rn/none, area/gateway

#9089 Add missing `__init__.py` files
  mlflow/server/auth/db/migrations/__init__.py
  mlflow/server/auth/db/migrations/versions/__init__.py
Labels: rn/none

#9082 Run `blacken-docs` in autoformat workflow
  .github/workflows/autoformat.yml
Labels: rn/none

#9090 Fix `IntegrityError` handling in amind user creation
  mlflow/server/auth/__init__.py
  mlflow/server/auth/sqlalchemy_store.py
Labels: rn/none

#9095 Fix sklearn flavor `_get_metric_name_list` function
  mlflow/sklearn/__init__.py
Labels: rn/bug-fix, area/tracking

#9097 Update requirements/lint-requirements.txt
  requirements/lint-requirements.txt
Labels: rn/none, area/build

#9101 Improve supported provider models
  docs/source/gateway/index.rst
Labels: rn/none, area/gateway

#9105 Removed unused `_user` variable
  mlflow/server/auth/__init__.py
Labels: rn/none

#9106 Updated ruff version to 0.0.278
  requirements/lint-requirements.txt
Labels: rn/none

#9100 Remove unnecessary `openai_api_base`
  docs/gateway_api_docs.py
  docs/source/gateway/index.rst
  examples/gateway/openai/config.yaml
Labels: rn/none, area/gateway

#9053 Fix potential issues with PyFuncBackend in cli
  mlflow/pyfunc/_mlflow_pyfunc_backend_predict.py
  mlflow/pyfunc/backend.py
  mlflow/pyfunc/scoring_server/__init__.py
  tests/models/test_cli.py
Labels: rn/none

#9103 Add `make view` to quickly view documentation
  docs/Makefile
Labels: rn/none

#8976 [Support inference params-4] Support inference params for model serving
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
  mlflow/pyfunc/scoring_server/__init__.py
  mlflow/pyfunc/scoring_server/client.py
  mlflow/pyfunc/stdin_server.py
  mlflow/sagemaker/__init__.py
  mlflow/types/schema.py
  mlflow/utils/proto_json_utils.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
  tests/pyfunc/test_scoring_server.py
  tests/pyfunc/test_spark.py
  tests/sklearn/test_sklearn_model_export.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/feature, area/scoring

#9047 Add sentence-transformers doc & example
  docs/source/models.rst
  examples/sentence_transformers/simple.py
  tests/examples/test_examples.py
Labels: area/docs, rn/documentation, area/examples

#9112 Clean CI disk for pytorch cross test on version >= 2
  .github/workflows/cross-version-tests.yml
Labels: rn/none, area/build

#9118 Update enable UP032 on pyproject.toml
  dev/update_ml_package_versions.py
  mlflow/catboost.py
  mlflow/langchain/__init__.py
  mlflow/store/model_registry/dbmodels/models.py
  mlflow/store/tracking/dbmodels/models.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/client.py
  mlflow/types/utils.py
  mlflow/utils/__init__.py
  mlflow/utils/model_utils.py
  pyproject.toml
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none, area/build

#9067 Docs model serve docker h
  docs/source/models.rst
Labels: area/docs, rn/none

#9108 Document LangChain integration
  docs/source/gateway/index.rst
Labels: rn/none, area/gateway

#9125 Fix `type` to `route_type` in gateway config examples
  docs/source/gateway/index.rst
Labels: rn/none, area/gateway

#9124 Import `gateway` in `mlflow/__init__.py` for convenience
  mlflow/__init__.py
Labels: rn/none

#9123 Fix infer_signature warning in sklearn
  mlflow/sklearn/__init__.py
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/none

#9122 Drop `gluon` support
  conftest.py
  docs/source/models.rst
  docs/source/python_api/mlflow.gluon.rst
  docs/source/tracking.rst
  examples/gluon/train.py
  mlflow/__init__.py
  mlflow/gluon/__init__.py
  mlflow/gluon/_autolog.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/models/__init__.py
  mlflow/tracking/fluent.py
  mlflow/utils/autologging_utils/versioning.py
  tests/autologging/test_autologging_behaviors_integration.py
  tests/autologging/test_autologging_utils.py
  tests/check_mlflow_lazily_imports_ml_packages.py
  tests/gluon/test_gluon_autolog.py
  tests/gluon/test_gluon_model_export.py
  tests/gluon/utils.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/breaking-change, area/models

#9121 Add langchain integration in gateway doc
  docs/source/gateway/index.rst
Labels: rn/none

#8977 [Support inference params-5]Add docs for inference params
  docs/source/model-registry.rst
  docs/source/models.rst
  docs/source/plugins.rst
  mlflow/models/utils.py
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
Labels: area/docs, rn/documentation

#9128 Revert "Drop `gluon` support"
  conftest.py
  docs/source/models.rst
  docs/source/python_api/mlflow.gluon.rst
  docs/source/tracking.rst
  examples/gluon/train.py
  mlflow/__init__.py
  mlflow/gluon/__init__.py
  mlflow/gluon/_autolog.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/models/__init__.py
  mlflow/tracking/fluent.py
  mlflow/utils/autologging_utils/versioning.py
  tests/autologging/test_autologging_behaviors_integration.py
  tests/autologging/test_autologging_utils.py
  tests/check_mlflow_lazily_imports_ml_packages.py
  tests/gluon/test_gluon_autolog.py
  tests/gluon/test_gluon_model_export.py
  tests/gluon/utils.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/none

#9050 fix sklearn raw model extraction
  mlflow/models/evaluation/default_evaluator.py
  mlflow/sklearn/__init__.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/none

#9129 Fix whisper.py example
  examples/transformers/whisper.py
Labels: rn/none

#9135 Fix redundant docs page
  docs/docs/source/python_api/mlflow.johnsnowlabs.rst
Labels: rn/none

#9136 Autoformat pyhton files if `pyproject.toml` changes
  .github/workflows/autoformat.yml
Labels: rn/none, area/build

#9051 Enable flake8 pytest style
  pyproject.toml
  tests/artifacts/test_artifacts.py
  tests/autologging/test_autologging_behaviors_integration.py
  tests/autologging/test_autologging_utils.py
  tests/data/test_spark_dataset.py
  tests/entities/conftest.py
  tests/gateway/providers/test_provider_utils.py
  tests/gateway/test_gateway_config_parsing.py
  tests/gateway/test_utils.py
  tests/projects/test_databricks.py
  tests/recipes/test_ingest_step.py
  tests/recipes/test_train_step.py
  tests/sentence_transformers/test_sentence_transformers_model_export.py
  tests/server/test_handlers.py
  tests/server/test_init.py
  tests/server/test_prometheus_exporter.py
  tests/sklearn/test_sklearn_autolog.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging_crossframework.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging_unit.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
  tests/spark/test_spark_model_export.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/store/artifact/test_azure_data_lake_artifact_repo.py
  tests/store/artifact/test_cli.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/store/artifact/test_databricks_models_artifact_repo.py
  tests/store/artifact/test_dbfs_artifact_repo_delegation.py
  tests/store/artifact/test_dbfs_fuse_artifact_repo.py
  tests/store/artifact/test_dbfs_rest_artifact_repo.py
  tests/store/model_registry/test_file_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/store/tracking/test_sqlalchemy_store_schema.py
  tests/tracking/_model_registry/test_utils.py
  tests/tracking/test_rest_tracking.py
  tests/tracking/test_tracking.py
  tests/transformers/test_transformers_autolog.py
  tests/transformers/test_transformers_model_export.py
  tests/utils/test_proto_json_utils.py
Labels: rn/none, only-latest

#9120 Update ruff on requirements/lint-requirements.txt
  mlflow/pyfunc/backend.py
  requirements/lint-requirements.txt
  tests/projects/test_projects.py
  tests/recipes/test_evaluate_step.py
  tests/recipes/test_predict_step.py
  tests/recipes/test_register_step.py
  tests/recipes/test_split_step.py
  tests/recipes/test_train_step.py
  tests/recipes/test_transform_step.py
Labels: rn/none, area/build

#9139 Replace % formatting with f-string
  examples/docker/train.py
  examples/multistep_workflow/etl_data.py
  examples/multistep_workflow/load_raw_data.py
  examples/paddle/train_high_level_api.py
  examples/paddle/train_low_level_api.py
  examples/pytorch/mnist_tensorboard_artifact.py
  examples/rapids/mlflow_project/src/rf_test/train_simple.py
  examples/shap/explainer_logging.py
  examples/sklearn_elasticnet_diabetes/linux/train_diabetes.py
  examples/sklearn_elasticnet_diabetes/osx/train_diabetes.py
  examples/sklearn_elasticnet_wine/train.py
  examples/sklearn_logistic_regression/train.py
  examples/spacy/train.py
  mlflow/cli.py
  mlflow/deployments/utils.py
  mlflow/entities/lifecycle_stage.py
  mlflow/experiments.py
  mlflow/models/utils.py
Labels: rn/none, area/build

#9141 python formatting f-string from script
  mlflow/projects/__init__.py
  mlflow/projects/_project_spec.py
  mlflow/projects/databricks.py
  mlflow/projects/utils.py
  mlflow/recipes/steps/train.py
  mlflow/runs.py
  mlflow/sagemaker/__init__.py
  mlflow/server/handlers.py
  mlflow/store/artifact/azure_blob_artifact_repo.py
  mlflow/store/artifact/azure_data_lake_artifact_repo.py
  mlflow/store/artifact/dbfs_artifact_repo.py
  mlflow/store/artifact/gcs_artifact_repo.py
  mlflow/store/artifact/runs_artifact_repo.py
  mlflow/store/artifact/s3_artifact_repo.py
  mlflow/store/artifact/utils/models.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/tracking/file_store.py
Labels: rn/none

#9130 Fix `yarn build` for Windows
  mlflow/server/js/craco.config.js
Labels: rn/none

#9145 Enable `PT007` and `PT010`
  pyproject.toml
Labels: rn/none

#9148 Deflake `test_search_model_versions_order_by_simple`
  tests/store/model_registry/test_sqlalchemy_store.py
Labels: rn/none

#9142 Deprecate non-UC cross workspace registry approach
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/tracking/_model_registry/utils.py
  mlflow/utils/databricks_utils.py
Labels: rn/none

#9086 Eliminate with mock.patch.dict for environment variables (1)
  tests/projects/test_projects.py
  tests/server/test_prometheus_exporter.py
Labels: rn/none
