Repository mlflow/mlflow, pull requests merged in 2023-10, with the labels that each got.

#9782 rm trailing space on databricks.proto
  mlflow/protos/databricks.proto
Labels: rn/none

#9784 Pin werkzeug for spacy
  mlflow/ml-package-versions.yml
  tests/spacy/test_spacy_model_export.py
Labels: rn/none

#9775 refactor(aggregate_metrics): calculation logic using dictionary compr…
  mlflow/system_metrics/metrics/cpu_monitor.py
  mlflow/system_metrics/metrics/disk_monitor.py
  mlflow/system_metrics/metrics/gpu_monitor.py
Labels: rn/none

#9786 Update `Databricks.java` docstring
  .github/workflows/protos.yml
  mlflow/java/client/src/main/java/com/databricks/api/proto/databricks/Databricks.java
Labels: rn/none

#9785 Fix `logger.exception` call
  mlflow/ml-package-versions.yml
  tests/spark/test_spark_model_export.py
Labels: rn/none, enable-dev-tests

#9788 Fix error message conversion for whisper
  mlflow/transformers/__init__.py
Labels: rn/none, enable-dev-tests

#9757 Move pmdarima
  mlflow/pmdarima/__init__.py
Labels: rn/none

#9755 Search run wrong run_name IN clause
  docs/source/search-runs.rst
Labels: area/docs, rn/none

#9760 replace % with %% to unblock complex passwords/hosts for authentication
  mlflow/server/auth/db/utils.py
Labels: rn/bug-fix

#9791 Unpin flaml
  .github/workflows/recipe.yml
Labels: rn/none

#9787 Use `tests/datasets/apollo11_launch.wav` in `examples/transformers/whisper.py`
  examples/transformers/whisper.py
Labels: rn/none

#9790 Add a script to run a tracking server with gateway quickly
  CONTRIBUTING.md
  dev/server.py
Labels: rn/none

#9670 Change @docstring_format indent
  mlflow/spacy.py
  mlflow/utils/docstring_utils.py
  tests/utils/test_docstring_utils.py
Labels: area/docs, rn/none

#9663 [BUG FIX] added shell condition for windows
  mlflow/utils/virtualenv.py
Labels: area/windows, rn/none, area/projects

#9726 fixed classical ml example code using notebook
  mlflow/server/js/src/experiment-tracking/components/evaluation-artifacts-compare/CreateNotebookRunModal.tsx
Labels: rn/none

#9792 Moved mlflow/mleap.py to mlflow/mleap/__init__.py
  mlflow/mleap/__init__.py
Labels: rn/none, area/models

#9718 Extend mlflow.evaluate to support single output function
  examples/evaluation/evaluate_with_function.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_evaluation.py
Labels: rn/feature

#9781 Fixing the naming for token_count and latency metrics
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/none, area/tracking

#9763 Overhaul mlflow.metrics module docs
  docs/source/python_api/mlflow.metrics.rst
  mlflow/metrics/__init__.py
  mlflow/metrics/base.py
  mlflow/metrics/genai/genai_metric.py
  mlflow/metrics/genai/metric_definitions.py
Labels: area/docs, rn/none

#9700 [Auth] Only admins can create new user
  docs/source/auth/index.rst
  mlflow/server/auth/__init__.py
  tests/server/auth/auth_test_utils.py
  tests/server/auth/test_auth.py
  tests/server/auth/test_client.py
Labels: rn/feature, area/tracking

#9800 Fix spark dev errors
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#9802 Drop old pytorch-lightning versions
  mlflow/ml-package-versions.yml
Labels: rn/none

#9721 Update model registry documentation for aliases
  docs/source/_static/images/oss_registry_1_register.png
  docs/source/_static/images/oss_registry_2_dialog.png
  docs/source/_static/images/oss_registry_3_overview.png
  docs/source/_static/images/oss_registry_3b_version.png
  docs/source/_static/images/oss_registry_3c_version.png
  docs/source/_static/images/oss_registry_4_model.png
  docs/source/_static/images/oss_registry_4_version.png
  docs/source/_static/images/oss_registry_4b_model_alias.png
  docs/source/_static/images/oss_registry_5_transition.png
  docs/source/_static/images/oss_registry_5_version.png
  docs/source/conf.py
  docs/source/model-registry.rst
Labels: rn/documentation, area/model-registry

#9810 Move keras module to its directory
  mlflow/keras/__init__.py
Labels: rn/none

#9806 Drop support for xgboost < 1.4.2
  mlflow/ml-package-versions.yml
Labels: rn/none

#9820 Build spark with SBT
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#9819 Pin moto<=4.2.4
  requirements/test-requirements.txt
Labels: rn/none

#9794 Add system prefix to system metrics
  mlflow/system_metrics/system_metrics_monitor.py
  tests/system_metrics/test_system_metrics_logging.py
Labels: rn/feature

#9815 Adding table property to EvaluationResult to return table
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/none, area/tracking

#9817 Remove fastapi dependency
  mlflow/gateway/providers/__init__.py
  mlflow/gateway/providers/base.py
  mlflow/gateway/providers/openai.py
  mlflow/gateway/providers/utils.py
  mlflow/metrics/genai/model_utils.py
Labels: rn/none, area/tracking, area/gateway

#9811 Creating a variable_mapping dict in evalutor_config for mapping
  docs/source/python_api/mlflow.metrics.rst
  examples/evaluation/evaluate_with_llm_judge.py
  mlflow/metrics/base.py
  mlflow/metrics/genai/genai_metric.py
  mlflow/metrics/genai/metric_definitions.py
  mlflow/metrics/genai/prompts/v1.py
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
  tests/metrics/genai/prompts/test_v1.py
  tests/metrics/genai/test_genai_metrics.py
  tests/metrics/test_base.py
Labels: rn/none, area/tracking

#9665 Add a databricks login API for mlflow
  mlflow/__init__.py
  mlflow/utils/credentials.py
  requirements/test-requirements.txt
  tests/utils/test_credentials.py
  tests/utils/test_requirements_utils.py
Labels: rn/feature, area/tracking, integrations/databricks

#9765 Clarify that register_model can be called on local filesystem paths
  mlflow/tracking/_model_registry/fluent.py
Labels: rn/none

#9839 Merge fix-whisper-example
  examples/transformers/whisper.py
Labels: rn/none

#9816 Rename custom_metrics to extra_metrics
  examples/evaluation/evaluate_with_custom_metrics.py
  examples/evaluation/evaluate_with_custom_metrics_comprehensive.py
  examples/evaluation/evaluate_with_llm_judge.py
  examples/evaluation/evaluate_with_model_validation.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/recipes/steps/evaluate.py
  mlflow/recipes/steps/train.py
  tests/evaluate/test_default_evaluator.py
  tests/evaluate/test_evaluation.py
Labels: rn/none

#9251 Model configuration for PyFunc flavor
  docs/source/models.rst
  mlflow/models/evaluation/base.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
  mlflow/transformers/__init__.py
  mlflow/utils/model_utils.py
  tests/pyfunc/test_pyfunc_model_config.py
  tests/transformers/test_transformers_model_export.py
Labels: area/docs, rn/feature, area/models

#9831 clean up mlflow/__init__.py
  mlflow/__init__.py
Labels: rn/none

#9844 pin greenlet < 3 to fix `test_pytorch_autologging_supports_data_parallel_execution`
  mlflow/ml-package-versions.yml
Labels: rn/none

#9841 Use `--pre` when install `tf-nightly`
  .github/workflows/cross-version-tests.yml
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#9835 R document update
  docs/source/R-api.rst
  mlflow/R/mlflow/document.R
Labels: language/r, rn/documentation

#9832 Use targets instead of ground_truth
  mlflow/metrics/genai/prompts/v1.py
  mlflow/models/evaluation/default_evaluator.py
  tests/metrics/genai/test_genai_metrics.py
Labels: rn/none, area/tracking

#9847 Improve `get_model_dependencies` docstring
  mlflow.db
  mlflow/pyfunc/__init__.py
Labels: rn/none

#9827 DOC-FIX. Change RunData to RunInputs
  mlflow/entities/run.py
Labels: rn/none

#9848 Prepend `sys.executable -m` to command lauching tracking server
  mlflow/server/__init__.py
  tests/server/test_init.py
Labels: rn/none

#9801 Create example for evaluating code with custom metrics
  examples/evaluation/evaluate_with_custom_code_metrics.py
  examples/evaluation/evaluate_with_llm_judge.py
Labels: rn/none, area/examples

#9855 Fix col mapping
  mlflow/models/evaluation/default_evaluator.py
Labels: rn/none

#9842 Fix langchain test for newest version
  tests/langchain/test_langchain_model_export.py
Labels: rn/none

#9857 Fixing aggregations optional error
  mlflow/metrics/genai/genai_metric.py
  mlflow/metrics/genai/prompts/v1.py
  tests/metrics/genai/prompts/test_v1.py
  tests/metrics/genai/test_genai_metrics.py
Labels: rn/none, area/tracking

#9853 Move mlflow/prophet.py to mlflow/prophet/__init__.py
  mlflow/prophet/__init__.py
Labels: rn/none, area/tracking

#9838 Support for completions in OpenAI flavor
  examples/openai/completions.py
  mlflow/openai/__init__.py
  mlflow/openai/utils.py
  tests/openai/test_openai_model_export.py
Labels: rn/feature, area/models

#9727 Add doc for input_example with params
  docs/source/models.rst
  mlflow/diviner.py
  mlflow/fastai/__init__.py
  mlflow/johnsnowlabs/__init__.py
  mlflow/langchain/__init__.py
  mlflow/mleap/__init__.py
  mlflow/models/model.py
  mlflow/onnx.py
  mlflow/openai/__init__.py
  mlflow/pyfunc/__init__.py
  mlflow/shap/__init__.py
  mlflow/spacy.py
  mlflow/utils/docstring_utils.py
Labels: rn/none

#9876 Johnsnowlabs Flavor : removed pandas version constraint
  mlflow/johnsnowlabs/__init__.py
Labels: rn/feature, area/models, integrations/databricks

#9845 Improve HuggingFace dataset logging
  mlflow/data/huggingface_dataset.py
  mlflow/data/huggingface_dataset_source.py
  tests/data/test_huggingface_dataset_and_source.py
Labels: rn/documentation, area/tracking

#9880 fix-langchain-tests
  mlflow/openai/utils.py
Labels: rn/none, area/build, enable-dev-tests

#9797 Add PaLM as a provider to MLflow AI Gateway
  docs/source/gateway/index.rst
  examples/gateway/README.md
  examples/gateway/palm/README.md
  examples/gateway/palm/config.yaml
  examples/gateway/palm/example.py
  mlflow/gateway/config.py
  mlflow/gateway/providers/__init__.py
  mlflow/gateway/providers/cohere.py
  mlflow/gateway/providers/mosaicml.py
  mlflow/gateway/providers/openai.py
  mlflow/gateway/providers/palm.py
  tests/gateway/providers/test_palm.py
  tests/gateway/test_integration.py
Labels: area/docs, rn/feature, area/gateway

#9874 fix infer signature from List[str]
  mlflow/models/signature.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
Labels: rn/none

#9882 Moved mlflow/llm.py to mlflow/llm/__init__.py
  mlflow/llm/__init__.py
Labels: rn/none, area/tracking

#9859 Improve error messages
  mlflow/models/evaluation/default_evaluator.py
Labels: rn/none

#9878 Use `pyarrow.fs.HadoopFileSystem` in pyarrow > 2.0.0
  mlflow/store/artifact/hdfs_artifact_repo.py
Labels: rn/none, area/artifacts

#9858 Moved mlflow/lightgbm.py to mlflow/lightgbm/__init__.py
  mlflow/lightgbm/__init__.py
Labels: rn/none, area/tracking

#9875 Moved mlflow/spark.py to mlflow/spark/__init__.py
  mlflow/spark/__init__.py
Labels: rn/none, area/tracking

#9868 Moved mlflow/statsmodel.py to mlflow/statsmodel/__init__.py
  mlflow/statsmodels/__init__.py
Labels: rn/none, area/tracking

#9866 Moved mlflow/spacy.py to mlflow/spacy/__init__.py
  mlflow/spacy/__init__.py
Labels: rn/none, area/tracking

#9865 Moved mlflow/onnx.py to mlflow/onnx/__init__.py
  mlflow/onnx/__init__.py
Labels: rn/none, area/tracking

#9889 Add SIM210 ruff rule
  examples/pytorch/mnist_tensorboard_artifact.py
  mlflow/sagemaker/__init__.py
  pyproject.toml
Labels: rn/none

#9852 Enable `dynamicTyping` in CSV artifact viewer
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactTableView.tsx
Labels: rn/none

#9402 Ensure model traceability by providing model name and version in pyfu…
  docs/source/models.rst
  mlflow/models/container/__init__.py
  mlflow/pyfunc/mlserver.py
  mlflow/store/artifact/models_artifact_repo.py
  mlflow/utils/file_utils.py
  tests/pyfunc/test_mlserver.py
  tests/store/artifact/test_models_artifact_repo.py
Labels: area/docs, rn/feature, area/model-registry, area/models, area/scoring

#9814 Added Classification and Regression Metrics
  mlflow/metrics/__init__.py
  mlflow/metrics/metric_definitions.py
  tests/evaluate/test_default_evaluator.py
  tests/metrics/test_metric_definitions.py
Labels: rn/none, area/tracking

#9891 Fix tiktoken cache issue
  mlflow/models/evaluation/default_evaluator.py
Labels: rn/none, area/tracking

#9888 Add SIM108 ruff rule
  examples/flower_classifier/train.py
  examples/sklearn_elasticnet_wine/train.ipynb
  mlflow/cli.py
  mlflow/gateway/app.py
  mlflow/models/cli.py
  mlflow/models/evaluation/base.py
  mlflow/openai/utils.py
  mlflow/projects/utils.py
  mlflow/prophet/__init__.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/scoring_server/__init__.py
  mlflow/pyspark/ml/__init__.py
  mlflow/server/handlers.py
  mlflow/sklearn/utils.py
  mlflow/store/artifact/dbfs_artifact_repo.py
  mlflow/store/artifact/hdfs_artifact_repo.py
  mlflow/tensorflow/__init__.py
  mlflow/tracking/fluent.py
  mlflow/transformers/__init__.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/environment.py
  mlflow/utils/virtualenv.py
  pyproject.toml
  tests/evaluate/test_evaluation.py
  tests/johnsnowlabs/test_johnsnowlabs_model_export.py
  tests/models/test_model.py
  tests/projects/test_databricks.py
  tests/recipes/helper_functions.py
  tests/sklearn/test_sklearn_autolog.py
  tests/spark/test_spark_model_export.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/tensorflow/iris_data_utils.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/none

#9895 Fix the signature validation tests in sentence-transformers suite
  tests/sentence_transformers/test_sentence_transformers_model_export.py
Labels: rn/none, area/build, enable-dev-tests

#9822 Introduce `MLFLOW_GATEWAY_CONFIG_PATH` environment variable
  docs/source/gateway/index.rst
  mlflow/gateway/cli.py
Labels: rn/feature, area/gateway

#9886 Optional `model_type`
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/none, area/tracking

#9901 Fix `eval_results_table.json` saving path
  mlflow/utils/promptlab_utils.py
Labels: rn/none

#9885 Add code example for `mlflow.data.from_numpy()`
  mlflow/data/numpy_dataset.py
Labels: area/docs, rn/documentation

#9898 Mlflow metrics docs update
  docs/source/python_api/mlflow.metrics.rst
  examples/evaluation/evaluate_with_llm_judge.py
  mlflow/metrics/genai/metric_definitions.py
  mlflow/models/evaluation/base.py
Labels: area/docs, rn/none

#9890 Add SIM115 ruff rule
  mlflow/recipes/artifacts.py
  mlflow/recipes/cards/__init__.py
  mlflow/recipes/steps/evaluate.py
  mlflow/recipes/steps/train.py
  mlflow/server/handlers.py
  mlflow/utils/file_utils.py
  pyproject.toml
  tests/projects/test_project_spec.py
  tests/projects/test_utils.py
  tests/recipes/test_train_step.py
  tests/store/artifact/test_local_artifact_repo.py
  tests/store/artifact/test_s3_artifact_repo.py
  tests/tensorflow/test_tensorflow2_autolog.py
  tests/tracking/test_rest_tracking.py
  tests/utils/test_file_utils.py
Labels: rn/none

#9902 Simplify chain operations
  mlflow/recipes/steps/split.py
  mlflow/recipes/steps/train.py
Labels: rn/none

#9914 fix docs test
  mlflow/metrics/base.py
Labels: area/docs, rn/none

#9916 lint fixes
  mlflow/metrics/genai/genai_metric.py
Labels: rn/none

#9913 MLflow Evaluation and Metrics
  .github/workflows/master.yml
  docs/source/conf.py
  docs/source/python_api/mlflow.metrics.rst
  examples/evaluation/evaluate_with_custom_code_metrics.py
  examples/evaluation/evaluate_with_custom_metrics.py
  examples/evaluation/evaluate_with_custom_metrics_comprehensive.py
  examples/evaluation/evaluate_with_llm_judge.py
  examples/evaluation/evaluate_with_model_validation.py
  examples/evaluation/evaluate_with_qa_metrics.py
  mlflow/gateway/providers/__init__.py
  mlflow/gateway/providers/base.py
  mlflow/gateway/providers/openai.py
  mlflow/gateway/providers/utils.py
  mlflow/gateway/utils.py
  mlflow/metrics/__init__.py
  mlflow/metrics/base.py
  mlflow/metrics/genai/__init__.py
  mlflow/metrics/genai/genai_metric.py
  mlflow/metrics/genai/metric_definitions.py
  mlflow/metrics/genai/model_utils.py
  mlflow/metrics/genai/prompt_template.py
  mlflow/metrics/genai/prompts/__init__.py
  mlflow/metrics/genai/prompts/v1.py
  mlflow/metrics/genai/utils.py
  mlflow/metrics/metric_definitions.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/recipes/steps/evaluate.py
  mlflow/recipes/steps/train.py
  requirements/test-requirements.txt
  tests/evaluate/test_default_evaluator.py
  tests/evaluate/test_evaluation.py
  tests/metrics/genai/prompts/test_v1.py
  tests/metrics/genai/test_genai_metrics.py
  tests/metrics/genai/test_model_utils.py
  tests/metrics/genai/test_prompt_template.py
  tests/metrics/test_base.py
  tests/metrics/test_metric_definitions.py
Labels: area/docs, rn/feature, area/tracking

#9919 Add SIM-103 ruff rule
  mlflow/utils/search_utils.py
  pyproject.toml
Labels: rn/none

#9910 DBConnect support for `spark_udf`
  .github/workflows/master.yml
  examples/databricks/dbconnect.py
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_spark_connect.py
Labels: rn/none

#9920 Rename 'table' to 'tables'
  examples/evaluation/evaluate_with_custom_code_metrics.py
  examples/evaluation/evaluate_with_llm_judge.py
  examples/evaluation/evaluate_with_qa_metrics.py
  mlflow/models/evaluation/base.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/none

#9899 Latency and token count via metrics
  mlflow/metrics/__init__.py
  mlflow/metrics/metric_definitions.py
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/none, area/tracking

#9925 Latency and token count via metrics (#9899)
  mlflow/metrics/__init__.py
  mlflow/metrics/metric_definitions.py
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/none, area/tracking

#9923 Include input / output schema in error message
  mlflow/models/evaluation/default_evaluator.py
Labels: rn/none

#9926 Fix docs typo :py:class` to :py:class:`
  mlflow/models/evaluation/base.py
  mlflow/store/tracking/abstract_store.py
Labels: rn/none

#9922 Add SIM114 rule
  mlflow/models/utils.py
  mlflow/transformers/__init__.py
  mlflow/types/utils.py
  mlflow/utils/search_utils.py
  pyproject.toml
Labels: rn/none

#9933 remove unused import
  mlflow/tracking/fluent.py
Labels: rn/none

#9893 Objects and Array support in model signature
  docs/source/conf.py
  mlflow/models/signature.py
  mlflow/types/schema.py
  mlflow/types/utils.py
  tests/models/test_signature.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
  tests/pyfunc/test_spark.py
  tests/tracking/fluent/test_fluent.py
  tests/tracking/test_rest_tracking.py
  tests/types/test_schema.py
Labels: rn/none

#9932 Deprecate `MLFLOW_OPENAI_SECRET_SCOPE`
  mlflow/openai/__init__.py
  tests/openai/test_openai_model_export.py
Labels: rn/none

#9937 Add a command to run gateway quickly in `examples/gateway/README.md`
  examples/gateway/README.md
Labels: rn/none

#9940 Add SIM910 ruff rule
  pyproject.toml
Labels: rn/none

#9938 models cli: change default env-manager to virtualenv for `generate-dockerfile`
  mlflow/models/cli.py
Labels: rn/bug-fix, area/docker, area/build

#9942 Update ruff to `0.0.292`
  requirements/lint-requirements.txt
Labels: rn/none

#9950 enable RUF013 (#9949)
  mlflow/data/dataset_registry.py
  mlflow/data/dataset_source_registry.py
  mlflow/data/huggingface_dataset.py
  mlflow/data/pandas_dataset.py
  mlflow/langchain/api_request_parallel_processor.py
  mlflow/metrics/genai/prompt_template.py
  mlflow/models/evaluation/base.py
  mlflow/models/model.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/mlserver.py
  mlflow/pyfunc/model.py
  mlflow/pyfunc/scoring_server/__init__.py
  mlflow/recipes/cards/__init__.py
  mlflow/recipes/classification/v1/recipe.py
  mlflow/recipes/recipe.py
  mlflow/recipes/regression/v1/recipe.py
  mlflow/recipes/step.py
  mlflow/recipes/steps/ingest/__init__.py
  mlflow/recipes/utils/__init__.py
  mlflow/recipes/utils/step.py
  mlflow/recipes/utils/tracking.py
  mlflow/sentence_transformers/__init__.py
  mlflow/server/auth/sqlalchemy_store.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  mlflow/transformers/__init__.py
  pyproject.toml
  tests/recipes/helper_functions.py
  tests/recipes/test_train_step.py
Labels: rn/none

#9924 Improve error message for predicted-column
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/none, area/tracking

#9934 Add example for `mlflow.data.from_pandas`
  mlflow/data/pandas_dataset.py
Labels: rn/none

#9953 Remove `MLFLOW_OPENAI_SECRET_SCOPE` in `examples/openai/pyfunc.py`
  examples/openai/pyfunc.py
Labels: rn/none

#9954 Replace `"MLFLOW_GATEWAY_CONFIG_PATH"` with `MLFLOW_GATEWAY_CONFIG.name`
  mlflow/gateway/cli.py
Labels: rn/none

#9956 Implement `__repr__` for easier test debugging
  mlflow/types/schema.py
Labels: rn/none

#9906 Added dash to gitlab URL
  mlflow/server/js/src/common/utils/Utils.test.tsx
  mlflow/server/js/src/common/utils/Utils.tsx
Labels: rn/none

#9830 Evaluate input extend dataset
  examples/evaluation/evaluate_with_static_dataset.py
  mlflow/data/pandas_dataset.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
  tests/evaluate/test_evaluation.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/dummy_evaluator.py
Labels: rn/feature, area/models

#9955 Support schema inference for spark dataframe
  mlflow/types/utils.py
  tests/types/test_schema.py
Labels: rn/none

#9965 Noun error fixed in main.py
  examples/multistep_workflow/main.py
Labels: area/docs

#9883 Improving prompt to new format
  mlflow/metrics/base.py
  mlflow/metrics/genai/genai_metric.py
  mlflow/metrics/genai/prompts/v1.py
  tests/metrics/genai/prompts/test_v1.py
  tests/metrics/genai/test_genai_metrics.py
  tests/metrics/test_base.py
Labels: rn/none, area/tracking

#9966 Improving prompt to new format
  mlflow/metrics/base.py
  mlflow/metrics/genai/genai_metric.py
  mlflow/metrics/genai/prompts/v1.py
  tests/metrics/genai/prompts/test_v1.py
  tests/metrics/genai/test_genai_metrics.py
  tests/metrics/test_base.py
Labels: rn/none, area/tracking

#9963 Insert devtools section in PR description
  .github/workflows/advice.js
Labels: rn/none

#9961 Call `hashlib.md5` with `usedforsecurity=False` for FIPS
  examples/databricks/multipart.py
  mlflow/data/digest_utils.py
  mlflow/models/evaluation/base.py
  mlflow/store/tracking/file_store.py
  mlflow/utils/__init__.py
  tests/evaluate/test_evaluation.py
  tests/resources/data/dataset.py
  tests/store/tracking/test_file_store.py
Labels: rn/none

#9970 Enabled Ruff W
  examples/flower_classifier/image_pyfunc.py
  examples/sentence_transformers/simple.py
  mlflow/metrics/__init__.py
  mlflow/models/docker_utils.py
  mlflow/sagemaker/__init__.py
  mlflow/utils/docstring_utils.py
  pyproject.toml
  tests/pyfunc/test_scoring_server.py
  tests/sklearn/test_sklearn_model_export.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#9909 OpenAI inference params
  docs/source/models.rst
  examples/openai/chat_completions.py
  examples/openai/completions.py
  examples/openai/embeddings.py
  mlflow/openai/__init__.py
  mlflow/openai/utils.py
  tests/openai/test_openai_model_export.py
Labels: rn/feature, area/models

#9974 Token count latency docs
  docs/source/python_api/mlflow.metrics.rst
  mlflow/models/evaluation/base.py
Labels: area/docs, rn/none

#9972 Optional configure timeout for precanned metrics
  mlflow/metrics/genai/metric_definitions.py
Labels: rn/none, area/tracking

#9975 Advise to use temperature 0 for judge
  mlflow/metrics/genai/genai_metric.py
Labels: area/docs, rn/none

#9973 Add legal warning about third party LLM judge
  docs/source/python_api/mlflow.metrics.rst
  mlflow/metrics/genai/genai_metric.py
  mlflow/metrics/genai/metric_definitions.py
Labels: area/docs, rn/none

#9958 Fix `targets` and `predictions` error message in mlflow evaluate
  mlflow/models/evaluation/base.py
  tests/evaluate/test_evaluation.py
Labels: rn/none

#9978 Change temperature in test to 0.0
  tests/metrics/genai/prompts/test_v1.py
  tests/metrics/genai/test_genai_metrics.py
Labels: rn/none, area/tracking

#9986 fix spark connect
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_spark_connect.py
Labels: rn/none

#9988 Report memory usage in tests
  conftest.py
Labels: rn/none

#9994 changed pytest_report_teststatus to report disk during tests
  conftest.py
  tests/examples/test_examples.py
  tests/helper_functions.py
Labels: rn/none

#9982 Adding support for azure openai
  mlflow/metrics/genai/model_utils.py
  tests/metrics/genai/test_model_utils.py
Labels: rn/bug-fix, area/tracking

#9998 Include other predicted columns in eval table
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/none, area/tracking

#9944 Rename correctness to answer similarity
  docs/source/python_api/mlflow.metrics.rst
  examples/evaluation/evaluate_with_llm_judge.py
  mlflow/metrics/__init__.py
  mlflow/metrics/genai/metric_definitions.py
  mlflow/metrics/genai/prompts/v1.py
  tests/metrics/genai/test_genai_metrics.py
Labels: rn/none

#9997 Docs: Update linting command
  .github/workflows/recipe-template.yml
  CONTRIBUTING.md
Labels: rn/none

#9999 Make all metrics in `mlflow.metrics` functions
  docs/source/python_api/mlflow.metrics.rst
  mlflow/metrics/__init__.py
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
  tests/metrics/test_metric_definitions.py
Labels: area/docs, rn/none, area/tracking

#9991 Gateway dependency
  mlflow/spark/__init__.py
  mlflow/utils/_capture_modules.py
  mlflow/utils/requirements_utils.py
  tests/utils/test_requirements_utils.py
Labels: rn/none, area/artifacts, area/models, area/gateway

#10006 Support fail-fast label
  .github/workflows/master.yml
  dev/pytest.sh
  mlflow/ml-package-versions.yml
Labels: rn/none, fail-fast

#10002 [bug-fix] Fixing target and prediction mapping for eval_fn
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/bug-fix, area/tracking

#10007 Cache `evaluate.load("toxicity")`
  mlflow/metrics/metric_definitions.py
  tests/evaluate/test_default_evaluator.py
  tests/metrics/test_metric_definitions.py
Labels: rn/none

#10004 Update docs for evaluating a static dataset and a function
  docs/source/models.rst
  docs/source/python_api/mlflow.data.rst
  mlflow/data/pandas_dataset.py
Labels: rn/none

#9976 Improve understandability of EvaluationMetric
  mlflow/metrics/genai/genai_metric.py
  mlflow/metrics/genai/prompt_template.py
  mlflow/models/evaluation/base.py
  tests/metrics/genai/test_genai_metrics.py
Labels: area/docs, rn/none, area/tracking

#10017 Adding type checking for extra_metrics in mlflow.evaluate
  mlflow/models/evaluation/base.py
Labels: rn/none, area/tracking

#9983 Fix latency and predictions parameter
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
  tests/evaluate/test_evaluation.py
Labels: rn/none

#9929 Fail fast for mlflow.evaluate()
  mlflow/metrics/genai/genai_metric.py
  mlflow/metrics/metric_definitions.py
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
  tests/metrics/genai/test_genai_metrics.py
  tests/metrics/test_metric_definitions.py
Labels: rn/none

#10016 Cleaning up custom metrics from docs strings
  docs/source/models.rst
  examples/evaluation/README.md
  mlflow/models/evaluation/base.py
Labels: rn/documentation, area/tracking

#10022 Set `MLFLOW_HOME` using `env`
  .github/workflows/cross-version-tests.yml
  .github/workflows/examples.yml
  .github/workflows/master.yml
  .github/workflows/r.yml
  .github/workflows/recipe.yml
  dev/dev-env-setup.sh
  dev/install-common-deps.sh
  dev/run-python-flavor-tests.sh
  dev/run-python-sagemaker-tests.sh
  dev/run-python-tests.sh
  dev/test-dev-env-setup.sh
Labels: rn/none

#10028 Ask where the bug occurred in the bug template
  .github/ISSUE_TEMPLATE/bug_report_template.yaml
Labels: rn/none

#10030 Remvoe useless test runner scripts
  .github/workflows/master.yml
  dev/run-python-flavor-tests.sh
  dev/run-python-sagemaker-tests.sh
  dev/run-python-tests.sh
Labels: rn/none

#10033 update `.gitignore` file
  .gitignore
Labels: rn/none

#10032 fix fill-mask with multiple masks
  mlflow/transformers/__init__.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/none, area/models

#10018 Add example notebooks for QA
  examples/evaluation/LLM Evaluation Examples -- QA.ipynb
Labels: rn/none, area/examples

#10024 Making sure that eval_config values are passed to the eval_fn
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/bug-fix, area/tracking

#9928 Display OpenAI error to users for make_genai_metric
  mlflow/metrics/genai/genai_metric.py
  mlflow/metrics/genai/model_utils.py
Labels: rn/none

#10023 Add a warning to `search_model_versions` doc
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/_model_registry/fluent.py
Labels: rn/none

#10048 [Bug fix] Fixing support for numpy array for eval
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/bug-fix, area/tracking

#10062 splits tests to run them faster for models
  .github/workflows/master.yml
  conftest.py
Labels: rn/none

#10050 Add context manager for creating or using a spark session
  examples/multistep_workflow/als.py
  examples/multistep_workflow/etl_data.py
  examples/multistep_workflow/train_keras.py
  tests/models/test_signature.py
  tests/pyfunc/test_spark.py
  tests/spark/test_spark_model_export.py
  tests/types/test_schema.py
Labels: rn/none

#10020 Surface error "missing targets column" early
  mlflow/metrics/metric_definitions.py
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/none

#10054 RAG example notebook
  examples/evaluation/LLM Evaluation Examples -- RAG.ipynb
Labels: rn/none, area/examples
