Repository mlflow/mlflow, pull requests merged in 2023-03, with the labels that each got.

#7902 Ignore delta checkpoint files in spark autologging
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/MlflowAutologEventPublisher.scala
Labels: rn/none

#7804 Experiment list virtual
  mlflow/server/js/package.json
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.js
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.test.js
  mlflow/server/js/yarn.lock
Labels: rn/bug-fix, area/uiux

#7913 Merge `compile_ml_package_versions.py` and `update_ml_package_versions.py`
  .pre-commit-config.yaml
  dev/compile_ml_package_versions.py
  dev/update_ml_package_versions.py
  mlflow/ml_package_versions.py
Labels: rn/none

#7914 Handle empty PR description in `advice.js`
  .github/workflows/advice.js
Labels: rn/none

#7916 Fix flaky `test_search_experiments_filter_by_time_attribute`
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#7844 Add support for writing UC model version files at creation time
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/artifact/unity_catalog_models_artifact_repo.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/store/artifact/test_unity_catalog_models_artifact_repo.py
Labels: rn/none

#7918 Fix `tests/dev/test_update_ml_package_versions.py`
  dev/update_ml_package_versions.py
  tests/dev/test_update_ml_package_versions.py
Labels: rn/none

#7920 Improve error handling when wheel download fails
  mlflow/models/wheeled_model.py
Labels: rn/none, area/models

#7923 MLflow UI changes
  .github/workflows/js.yml
  mlflow/server/js/.eslintrc.js
  mlflow/server/js/package.json
  mlflow/server/js/src/common/components/PageContainer.js
  mlflow/server/js/src/common/components/SimplePagination.js
  mlflow/server/js/src/common/components/tables/EditableFormTable.js
  mlflow/server/js/src/common/utils/FeatureUtils.ts
  mlflow/server/js/src/experiment-tracking/components/HtmlTableView.js
  mlflow/server/js/src/experiment-tracking/components/HtmlTableView.test.js
  mlflow/server/js/src/experiment-tracking/components/RunView.js
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactTableView.js
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/header/ExperimentViewHeader.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/ExperimentViewRunsControlsActions.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/ExperimentViewRunsSortSelector.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/ExperimentViewRunsTable.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/RunsSearchAutoComplete.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/RunsSearchAutoComplete.utils.tsx
  mlflow/server/js/src/experiment-tracking/types.ts
  mlflow/server/js/src/i18n/default/en.json
  mlflow/server/js/src/model-registry/components/ModelListView.js
  mlflow/server/js/src/model-registry/components/ModelListView.test.js
  mlflow/server/js/src/model-registry/components/ModelVersionPage.test.js
  mlflow/server/js/src/model-registry/components/ModelVersionTable.css
  mlflow/server/js/src/model-registry/components/model-list/ModelListFilters.test.tsx
  mlflow/server/js/src/model-registry/components/model-list/ModelListFilters.tsx
  mlflow/server/js/src/model-registry/components/model-list/ModelListTable.test.tsx
  mlflow/server/js/src/model-registry/components/model-list/ModelListTable.tsx
  mlflow/server/js/src/model-registry/components/model-list/ModelTableCellRenderers.tsx
  mlflow/server/js/src/shared/building_blocks/PageHeader.jsx
  mlflow/server/js/yarn.lock
Labels: rn/none, area/uiux

#7922 [#7921] Modify pytorch predict to use the GPU if it's available
  docs/source/models.rst
  mlflow/environment_variables.py
  mlflow/pytorch/__init__.py
Labels: rn/feature, area/scoring

#7917 Use a shorter timeout for `_await_server_up_or_die`
  tests/test_cli.py
  tests/tracking/integration_test_utils.py
Labels: rn/none

#7924 Add two more entries to MLflow 2.2 changelog
  CHANGELOG.md
Labels: area/docs, rn/none

#7757 [Server][Feature] add plugin to allow custom configs for mlflow.server
  docs/source/plugins.rst
  mlflow/server/__init__.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/app.py
  tests/resources/mlflow-test-plugin/setup.py
  tests/server/test_init.py
Labels: rn/feature, area/server-infra

#7929 Follow-up for #7757
  docs/source/plugins.rst
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/app.py
Labels: rn/none

#7930 Update bug report title to encourage issue reporters to use `UI bug report` for UI issues
  .github/ISSUE_TEMPLATE/bug_report_template.yaml
Labels: rn/none

#7935 Use default max results of 10000 for model registry search_model_versions() API
  mlflow/store/model_registry/__init__.py
Labels: rn/bug-fix, area/model-registry

#7901 Get workspace ID from source tracking server when creating UC model versions
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/store/artifact/test_unity_catalog_models_artifact_repo.py
Labels: rn/none

#7909 Require signature for model versions in UC
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/none

#7968 Temporarily avoid alembic 1.10.0
  dev/run-python-skinny-tests.sh
  requirements/core-requirements.txt
  requirements/core-requirements.yaml
Labels: rn/none

#7965 Validate name in `FileStore.get_registered_model`
  instance/mlflow-auth.db
  mlflow/store/model_registry/file_store.py
  tests/store/model_registry/test_file_store.py
Labels: rn/none

#7928 Updating the description of the version in the documentation
  README.rst
Labels: rn/none

#7925 [Recipes][Bugfix] Correctly fixing the toPandas issue for datetime datatype to correctly render profiling
  mlflow/recipes/steps/ingest/datasets.py
  tests/recipes/test_ingest_step.py
Labels: rn/bug-fix, area/recipes

#7981 Skip `test_log_figure_plotly_image` on windows
  tests/tracking/test_log_figure.py
Labels: rn/none, area/tracking

#7987 Address TODO for alembic 1.10.0
  dev/run-python-skinny-tests.sh
  requirements/core-requirements.yaml
Labels: rn/none

#7994 Fix tensorflow cross version tests for alembic dependency on typing-extensions
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#7988 Fix `is_local_uri` for windows network drive path
  mlflow/utils/uri.py
  tests/utils/test_uri.py
Labels: rn/bug-fix, area/models

#7992 Remove broken reference
  examples/pytorch/MNIST/README.md
Labels: rn/documentation

#8000 Update protoc to match example command
  CONTRIBUTING.md
Labels: rn/none

#8002 Remove `instance/mlflow-auth.db`
  instance/mlflow-auth.db
Labels: rn/none

#7993 Allow `source` to be a local path within a run's artifact directory in create_model_version
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, area/artifacts, area/tracking

#7982 Add `--app-name` option to `mlflow server` to allow specifying mlflow app name
  docs/source/plugins.rst
  mlflow/cli.py
  mlflow/server/__init__.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/app.py
  tests/resources/mlflow-test-plugin/setup.py
  tests/server/test_init.py
Labels: rn/none

#8005 Fix `test_virtualenv_project_execution_no_python_env`
  tests/projects/test_virtualenv_projects.py
Labels: rn/none

#8001 Add registered model aliases table and entity
  mlflow/entities/model_registry/registered_model_alias.py
  mlflow/java/client/src/main/java/org/mlflow/api/proto/ModelRegistry.java
  mlflow/protos/model_registry.proto
  mlflow/protos/model_registry_pb2.py
  mlflow/store/db_migrations/versions/3500859a5d39_add_model_aliases_table.py
  mlflow/store/model_registry/dbmodels/models.py
  tests/db/schemas/mssql.sql
  tests/db/schemas/mysql.sql
  tests/db/schemas/postgresql.sql
  tests/db/schemas/sqlite.sql
  tests/resources/db/latest_schema.sql
Labels: rn/none, area/model-registry

#7964 Migrate `tests/store/tracking/test_file_store.py` to pytest
  tests/store/tracking/test_file_store.py
Labels: rn/none

#8016 Fix add Cache-Control headers to server static files prefix
  mlflow/server/__init__.py
Labels: rn/bug-fix, area/uiux, area/server-infra

#7971 Fix MLflow iFrame rendering issue
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/header/ExperimentViewHeaderShareButton.tsx
Labels: rn/bug-fix, area/uiux

#8015 Changelog for 2.2.2
  CHANGELOG.md
Labels: rn/none

#8021 Update dev versions
  mlflow/java/client/pom.xml
  mlflow/java/pom.xml
  mlflow/java/scoring/pom.xml
  mlflow/java/scoring/src/main/java/org/mlflow/sagemaker/ScoringServer.java
  mlflow/java/scoring/src/test/java/org/mlflow/ScoringServerTest.java
  mlflow/java/spark/pom.xml
  mlflow/server/js/src/common/constants.js
  mlflow/version.py
Labels: rn/none

#8023 Fix `dev/create_release_tag.py`
  dev/create_release_tag.py
Labels: rn/none

#8012 Update MetricThreshold to deprecate higher_is_better and add greater_is_better
  docs/source/models.rst
  examples/evaluation/evaluate_with_model_validation.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/validation.py
  tests/models/test_validation.py
Labels: area/docs, rn/bug-fix, rn/documentation, area/models

#7999 AzureBlobArtifactRepository to support custom CA certs
  mlflow/store/artifact/azure_blob_artifact_repo.py
  mlflow/utils/rest_utils.py
Labels: rn/none, area/artifacts, integrations/azure

#8024 Increase timeout minutes for lint job
  .github/workflows/master.yml
Labels: rn/none

#7933 Add custom domain git (change git regex)
  mlflow/server/js/src/common/utils/Utils.js
  mlflow/server/js/src/common/utils/Utils.test.js
Labels: rn/feature, area/uiux, area/projects

#8033 Fix `dev/update_mlflow_versions.py` to update R version
  dev/update_mlflow_versions.py
  mlflow/R/mlflow/DESCRIPTION
Labels: rn/none

#8027 nit typo
  mlflow/tracking/_tracking_service/client.py
Labels: rn/none, area/tracking

#8039 Fix lightning hyperparameter tuning examples
  examples/pytorch/AxHyperOptimizationPTL/conda.yaml
  examples/pytorch/AxHyperOptimizationPTL/python_env.yaml
  examples/pytorch/IterativePruning/conda.yaml
  examples/pytorch/IterativePruning/python_env.yaml
Labels: rn/bug-fix, area/examples

#8040 adjust logic for dry release logic to prevent unfound branches
  dev/create_release_tag.py
Labels: rn/none, area/build

#8031 Add Models in UC requirements to a new `[databricks]` extra
  setup.py
Labels: rn/none, area/model-registry

#8043 Rename existing data-related utils / resources to avoid conflicts with upcoming MLflow Tracking data integration
  mlflow/experiments.py
  mlflow/projects/_project_spec.py
  mlflow/store/artifact/s3_artifact_repo.py
  mlflow/utils/data_utils.py
  tests/datasets/uci-autos-imports-85.data
  tests/datasets/winequality-red.csv
  tests/datasets/winequality-white.csv
  tests/recipes/test_ingest_step.py
  tests/tensorflow/save_tf_estimator_model.py
  tests/utils/test_data.py
Labels: rn/none, area/build

#8038 Raise an exception only if param value changed
  mlflow/store/tracking/sqlalchemy_store.py
Labels: rn/bug-fix, area/tracking

#8050 fix "git submodule update" command in mlflow projects
  mlflow/projects/utils.py
Labels: rn/bug-fix, area/projects

#8028 Use `UnityCatalogModelsArtifactRepository` when UC registry URI is set
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/artifact/models_artifact_repo.py
  mlflow/store/artifact/unity_catalog_models_artifact_repo.py
  tests/store/artifact/test_models_artifact_repo.py
Labels: rn/none, area/artifacts

#8046 [Feature branch] Introduce dataset source plugin system
  mlflow/data/__init__.py
  mlflow/data/dataset_source.py
  mlflow/data/dataset_source_registry.py
  tests/data/test_dataset_source.py
  tests/data/test_dataset_source_registry.py
  tests/resources/data/__init__.py
  tests/resources/data/dataset_source.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/dummy_dataset_source.py
  tests/resources/mlflow-test-plugin/setup.py
Labels: rn/none, area/tracking

#8029 Use `UcModelRegistryStore` when UC registry URI is set
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/_model_registry/registry.py
  mlflow/tracking/_model_registry/utils.py
  mlflow/tracking/client.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/store/artifact/test_unity_catalog_models_artifact_repo.py
  tests/tracking/_model_registry/test_model_registry_client.py
  tests/tracking/_model_registry/test_utils.py
Labels: rn/none, area/model-registry

#8035 allows to configure MLServer worker count when generated with mlflow …
  mlflow/models/container/__init__.py
  mlflow/utils/cli_args.py
Labels: area/docs, rn/bug-fix, area/scoring, area/docker

#8066 Remove the command to clear python cache from Dockerfile
  Dockerfile
Labels: rn/none, area/build

#8042 [Feature branch] Plugin system for MLflow dataset tracking
  mlflow/data/__init__.py
  mlflow/data/dataset.py
  mlflow/data/dataset_registry.py
  tests/data/test_dataset.py
  tests/data/test_dataset_registry.py
  tests/data/test_dataset_source_registry.py
  tests/resources/data/dataset.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/dummy_dataset.py
  tests/resources/mlflow-test-plugin/setup.py
Labels: rn/feature, area/tracking

#8051 [Feature branch] Implement data sources for MLflow artifact repositories
  mlflow/data/artifact_dataset_sources.py
  mlflow/data/dataset_source_registry.py
  mlflow/data/filesystem_dataset_source.py
  mlflow/store/artifact/artifact_repository_registry.py
  mlflow/utils/uri.py
  tests/data/test_artifact_dataset_sources.py
Labels: rn/none, area/tracking

#8068 Fix sklearn elasticnet wine example
  examples/sklearn_elasticnet_wine/train.py
Labels: area/docs, rn/none

#8063 Fix `update_changelog.py`
  dev/update_changelog.py
Labels: rn/none

#8076 Fix `dev/update_changelog.py`
  dev/update_changelog.py
Labels: rn/none

#8073 Fix `dev/preview_docs.py` to avoid creating a new comment
  dev/preview_docs.py
Labels: rn/none

#8009 implemented feature for allowing async inference config
  mlflow/sagemaker/__init__.py
  tests/sagemaker/mock/__init__.py
  tests/sagemaker/mock/test_sagemaker_service_mock.py
  tests/sagemaker/test_sagemaker_deployment_client.py
Labels: rn/feature, integrations/sagemaker

#8055 Add Registered Model Alias Endpoints and Update RegisteredModel/ModelVersion Payloads
  mlflow/entities/model_registry/__init__.py
  mlflow/entities/model_registry/model_version.py
  mlflow/entities/model_registry/registered_model.py
  mlflow/entities/model_registry/registered_model_alias.py
  mlflow/java/client/src/main/java/org/mlflow/api/proto/ModelRegistry.java
  mlflow/protos/model_registry.proto
  mlflow/protos/model_registry_pb2.py
  mlflow/server/handlers.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/db_migrations/versions/3500859a5d39_add_model_aliases_table.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/dbmodels/models.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/model_registry/rest_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/utils/validation.py
  tests/db/schemas/mssql.sql
  tests/db/schemas/mysql.sql
  tests/db/schemas/postgresql.sql
  tests/db/schemas/sqlite.sql
  tests/entities/model_registry/test_model_version.py
  tests/entities/model_registry/test_registered_model.py
  tests/resources/db/latest_schema.sql
  tests/server/test_handlers.py
  tests/store/model_registry/test_file_store.py
  tests/store/model_registry/test_rest_store.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/utils/test_validation.py
Labels: rn/feature, area/model-registry, area/sqlalchemy

#8075 Prefix artifact names in `mlflow.evaluate`
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/recipes/steps/evaluate.py
Labels: rn/none

#8080 Upgrade Yarn to v3.5.0
  mlflow/server/js/.yarnrc.yml
  mlflow/server/js/yarn.lock
  mlflow/server/js/yarn/releases/yarn-3.3.0.cjs
  mlflow/server/js/yarn/releases/yarn-3.5.0.cjs
Labels: rn/none

#8072 Pytorch and Lightning 2.0 fixes
  examples/pytorch/AxHyperOptimizationPTL/ax_hpo_iris.py
  examples/pytorch/AxHyperOptimizationPTL/conda.yaml
  examples/pytorch/AxHyperOptimizationPTL/python_env.yaml
  examples/pytorch/BertNewsClassification/MLproject
  examples/pytorch/BertNewsClassification/README.md
  examples/pytorch/BertNewsClassification/bert_classification.py
  examples/pytorch/BertNewsClassification/conda.yaml
  examples/pytorch/BertNewsClassification/python_env.yaml
  examples/pytorch/IterativePruning/conda.yaml
  examples/pytorch/IterativePruning/iterative_prune_mnist.py
  examples/pytorch/IterativePruning/mnist.py
  examples/pytorch/IterativePruning/python_env.yaml
  examples/pytorch/MNIST/MLproject
  examples/pytorch/MNIST/README.md
  examples/pytorch/MNIST/conda.yaml
  examples/pytorch/MNIST/mnist_autolog_example.py
  examples/pytorch/MNIST/python_env.yaml
  mlflow/pytorch/__init__.py
Labels: rn/bug-fix, area/examples, area/models

#8092 Change azure storage pip dependency in Databricks extra
  setup.py
Labels: rn/none, area/model-registry, integrations/databricks

#8090 Skip custom layer usage with save_model() test in TF 2.11.1 due to suspected TF bug
  tests/tensorflow/test_keras_model_export.py
Labels: rn/none, area/models, area/build

#8096 Output tensorboard logs in a temporary directory
  tests/pytorch/iris.py
Labels: rn/none

#8048 Add Content-Type headers to HTTP artifact upload calls
  mlflow/server/handlers.py
  mlflow/store/artifact/http_artifact_repo.py
  mlflow/utils/mime_type_utils.py
  mlflow/utils/rest_utils.py
  tests/server/test_handlers.py
  tests/store/artifact/test_http_artifact_repo.py
  tests/store/artifact/test_mlflow_artifact_repo.py
  tests/utils/test_mime_type_utils.py
  tests/utils/test_rest_utils.py
Labels: rn/feature, area/artifacts

#8089 Fix ColSpec argument type hint
  mlflow/types/schema.py
Labels: rn/none

#8097 fix TF autolog for multi input models
  mlflow/tensorflow/__init__.py
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/bug-fix, area/tracking

#8091 Fix uc model registry default argument values
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/tracking/client.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/tracking/test_client.py
Labels: rn/none, area/model-registry

#8088 Log exception in `tests/check_mlflow_lazily_imports_ml_packages.py`
  tests/check_mlflow_lazily_imports_ml_packages.py
Labels: rn/none

#8087 Rename unity catalog model version statuses to be consistent with regular statuses
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
Labels: rn/none, area/model-registry, integrations/databricks, autoformat

#8093 Rename `ModelVersionOperation` enum in UC registry REST store
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/artifact/unity_catalog_models_artifact_repo.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/store/artifact/test_unity_catalog_models_artifact_repo.py
Labels: rn/none, area/model-registry, integrations/databricks

#8110 Enable `load_model` for UC models
  mlflow/store/artifact/unity_catalog_models_artifact_repo.py
  tests/store/artifact/test_unity_catalog_models_artifact_repo.py
Labels: rn/none, area/model-registry, integrations/databricks

#8069 [Feature branch] Rename datasets download() to load(), add dst_path for downloads
  mlflow/data/artifact_dataset_sources.py
  mlflow/data/dataset_source.py
  mlflow/data/filesystem_dataset_source.py
  tests/data/test_artifact_dataset_sources.py
  tests/data/test_dataset_source.py
  tests/data/test_dataset_source_registry.py
  tests/resources/data/dataset_source.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/dummy_dataset_source.py
Labels: rn/none, area/tracking

#8102 Initial PR for auth
  mlflow/server/auth/__init__.py
  setup.py
Labels: rn/none

#8105 Remove `is_patch_release` check in `dev/create_release_branch.py`
  dev/create_release_branch.py
Labels: rn/none

#8100 correcting projects doc
  docs/source/projects.rst
Labels: rn/none

#8117 Fix typo in tracking.rst
  docs/source/tracking.rst
Labels: rn/none

#8106 Fix keras version in tensorflow model saving
  mlflow/tensorflow/__init__.py
  tests/tensorflow/test_keras_model_export.py
Labels: rn/none, area/build, enable-dev-tests

#8107 Ensure `mlflow.pyfunc.spark_udf` supports `ArrayType(StructType))`
  .github/workflows/master.yml
  tests/pyfunc/test_spark.py
Labels: rn/none

#8120 Fix `mlflow.store.db.utils._all_table_exist`
  mlflow/store/db/utils.py
Labels: rn/none

#8127 Remove RStudio travis link from R README
  mlflow/R/mlflow/README.md
Labels: rn/none, area/build

#8086 Add support for transformers as a named flavor
  conftest.py
  dev/update_ml_package_versions.py
  docs/source/python_api/mlflow.transformers.rst
  mlflow/__init__.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/transformers.py
  mlflow/utils/autologging_utils/versioning.py
  mlflow/utils/docstring_utils.py
  requirements/extra-ml-requirements.txt
  requirements/test-requirements.txt
  tests/check_mlflow_lazily_imports_ml_packages.py
  tests/diviner/test_diviner_model_export.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/feature, area/models

#8134 Increase CI timeout for Python main tests
  .github/workflows/master.yml
Labels: rn/none, area/build

#7867 Custom model flavor example
  docs/source/_static/images/tracking_artifact_ui_custom_flavor.png
  docs/source/models.rst
  examples/sktime/MLproject
  examples/sktime/README.md
  examples/sktime/flavor.py
  examples/sktime/python_env.yaml
  examples/sktime/score_model.py
  examples/sktime/test_sktime_model_export.py
  examples/sktime/train.py
  requirements/test-requirements.txt
  tests/examples/test_examples.py
Labels: rn/documentation, area/examples

#8131 Bump versions for 1.30.1 release
  mlflow/R/mlflow/DESCRIPTION
  mlflow/java/client/pom.xml
  mlflow/java/pom.xml
  mlflow/java/scoring/pom.xml
  mlflow/java/scoring/src/main/java/org/mlflow/sagemaker/ScoringServer.java
  mlflow/java/scoring/src/test/java/org/mlflow/ScoringServerTest.java
  mlflow/java/spark/pom.xml
  mlflow/server/js/src/common/constants.js
  mlflow/version.py
Labels: rn/none

#8126 Disallow using a file URI as model version source
  mlflow/environment_variables.py
  mlflow/server/handlers.py
  mlflow/utils/uri.py
  tests/tracking/integration_test_utils.py
  tests/tracking/test_rest_tracking.py
  tests/utils/test_uri.py
Labels: rn/bug-fix

#8003 Support multipart upload for AWS Databricks
  mlflow/java/client/src/main/java/com/databricks/api/proto/mlflow/DatabricksArtifacts.java
  mlflow/protos/databricks_artifacts.proto
  mlflow/protos/databricks_artifacts_pb2.py
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/utils/rest_utils.py
  tests/store/artifact/test_databricks_artifact_repo.py
Labels: rn/feature
