Repository mlflow/mlflow, pull requests merged in 2024-09, with the labels that each got.

#13043 Fix Langchain dev cross version tests
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#13029 Fix llama-index dev
  mlflow/llama_index/serialize_objects.py
  mlflow/ml-package-versions.yml
  tests/llama_index/test_llama_index_model_export.py
  tests/llama_index/test_llama_index_pyfunc_wrapper.py
  tests/llama_index/test_llama_index_serialization.py
  tests/llama_index/test_llama_index_tracer.py
Labels: rn/none, enable-dev-tests

#13049 Fix `docstring` for `code_paths`
  mlflow/pyfunc/__init__.py
  mlflow/utils/docstring_utils.py
Labels: rn/none, patch-2.16.1

#13048 Add quick doc for autogen tracing
  docs/source/_static/images/llms/autogen/autogen-trace.png
  docs/source/llms/index.rst
  docs/source/llms/tracing/index.rst
  docs/source/python_api/mlflow.autogen.rst
  mlflow/autogen/__init__.py
Labels: area/docs, rn/none, patch-2.16.1

#13036 Support long conversion to float for 0 and 1
  mlflow/models/utils.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
Labels: rn/none

#13052 Skip `test_mlflow_models_serve`
  tests/test_cli.py
Labels: rn/none

#13047 Fix timezone issue with autogen tracing
  mlflow/autogen/autogen_logger.py
  tests/autogen/test_autogen_autolog.py
Labels: rn/bug-fix, area/tracking, patch-2.16.1

#13051 Fix shap cross version tests
  mlflow/ml-package-versions.yml
Labels: rn/none

#13055 Fix incorrect format arguments in `start_run`
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/none, patch-2.16.1

#13061 Install `taplo` faster
  .github/workflows/autoformat.yml
  .github/workflows/lint.yml
  dev/install-taplo.sh
Labels: rn/none

#13062 Show both stdout and stderr in wheel download error message
  mlflow/models/wheeled_model.py
  tests/models/test_wheeled_model.py
Labels: rn/none

#13067 Avoid SQLAlchemy==2.0.33
  .github/workflows/master.yml
Labels: rn/none

#12879 Fix UP031
  examples/pytorch/CaptumExample/Titanic_Captum_Interpret.py
  examples/pytorch/mnist_tensorboard_artifact.py
  examples/rapids/mlflow_project/notebooks/rapids_mlflow.ipynb
  examples/sklearn_elasticnet_wine/train.ipynb
  mlflow/entities/trace.py
  mlflow/legacy_databricks_cli/configure/provider.py
  mlflow/projects/_project_spec.py
  mlflow/projects/databricks.py
  mlflow/sklearn/utils.py
  mlflow/spark/autologging.py
  mlflow/store/artifact/utils/models.py
  mlflow/store/tracking/file_store.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/fluent.py
  mlflow/utils/conda.py
  mlflow/utils/search_utils.py
  mlflow/utils/validation.py
  tests/projects/test_project_spec.py
  tests/projects/test_projects_cli.py
Labels: rn/none

#13044 Support evaluation on an endpoint URI with the `databricks-agent` model type
  mlflow/models/evaluation/base.py
  tests/evaluate/test_evaluation.py
Labels: rn/none, area/models, patch-2.16.1

#13065 UC OSS Finalized Protos
  mlflow/protos/unity_catalog_oss_messages.proto
  mlflow/protos/unity_catalog_oss_messages_pb2.py
  mlflow/protos/unity_catalog_oss_service.proto
  mlflow/protos/unity_catalog_oss_service_pb2.py
  mlflow/store/_unity_catalog/registry_oss/rest_store_oss.py
  mlflow/utils/_unity_catalog_oss_utils.py
  tests/store/_unity_catalog/oss_registry/test_unity_catalog_oss_rest_store.py
  tests/utils/test_unity_catalog_oss_utils.py
Labels: rn/feature, area/model-registry

#13069 Fix typo 'storgate' to 'storage' in tracking server documentation
  docs/source/tracking/server.rst
Labels: area/docs, rn/none, patch-2.16.1

#13057 Add `/rerun` command to rerun failed jobs on PR
  .github/workflows/rerun.js
  .github/workflows/rerun.yml
Labels: rn/none

#13071 Add support for LLM response refusal
  mlflow/types/llm.py
  tests/pyfunc/test_chat_model_validation.py
Labels: rn/feature, area/models

#13075 Add parsing validation for utility function
  tests/utils/test_databricks_utils.py
Labels: rn/none, area/tracking, integrations/databricks

#13073 Remove SQLAlchemy pin
  .github/workflows/master.yml
Labels: rn/none

#13066 UC OSS Artifact Repository Impl (MLFlow Client)
  mlflow/store/artifact/models_artifact_repo.py
  mlflow/store/artifact/unity_catalog_oss_models_artifact_repo.py
  mlflow/utils/_unity_catalog_utils.py
  mlflow/utils/oss_utils.py
  mlflow/utils/uri.py
  tests/store/artifact/constants.py
  tests/store/artifact/test_models_artifact_repo.py
  tests/store/artifact/test_unity_catalog_oss_models_artifact_repo.py
  tests/utils/test_oss_utils.py
Labels: rn/feature, area/model-registry

#13017 Add audio support to artifact viewer UI
  mlflow/server/js/package.json
  mlflow/server/js/src/common/utils/FileUtils.ts
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/LazyShowArtifactAudioView.tsx
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactAudioView.enzyme.test.tsx
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactAudioView.tsx
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactPage.enzyme.test.tsx
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactPage.tsx
  mlflow/server/js/src/lang/default/en.json
  mlflow/server/js/yarn.lock
Labels: rn/feature, area/uiux, area/artifacts

#12981 Fix incorrect best model selection in auto checkpointing
  mlflow/utils/checkpoint_utils.py
  tests/pytorch/test_pytorch_autolog.py
Labels: rn/bug-fix, area/tracking, patch-2.15.2, patch-2.16.1

#13070 Support logging Transformer models with a path to local model checkpoints to reduce memory footprint
  mlflow/models/model.py
  mlflow/transformers/__init__.py
  mlflow/transformers/flavor_config.py
  mlflow/transformers/model_io.py
  mlflow/transformers/signature.py
  tests/transformers/test_transformers_model_export.py
  tests/transformers/test_transformers_signature.py
Labels: rn/feature, area/models, patch-2.16.1

#13081 Put tracing docs in main sidebar
  docs/source/index.rst
  docs/source/llms/langchain/autologging.rst
  docs/source/llms/llama-index/index.rst
  docs/source/llms/tracing/index.rst
  docs/source/llms/transformers/guide/index.rst
Labels: rn/none, patch-2.16.1

#13034 MLFlow OSS Rest Store
  dev/generate_protos.py
  mlflow/entities/model_registry/__init__.py
  mlflow/store/_unity_catalog/registry/__init__.py
  mlflow/store/_unity_catalog/registry/uc_oss_rest_store.py
  mlflow/store/_unity_catalog/registry_oss/__init__.py
  mlflow/store/_unity_catalog/registry_oss/rest_store_oss.py
  mlflow/store/artifact/unity_catalog_oss_models_artifact_repo.py
  mlflow/tracking/_model_registry/utils.py
  mlflow/tracking/_tracking_service/utils.py
  mlflow/tracking/registry.py
  mlflow/utils/_unity_catalog_oss_utils.py
  mlflow/utils/_unity_catalog_utils.py
  mlflow/utils/oss_registry_utils.py
  mlflow/utils/rest_utils.py
  tests/store/_unity_catalog/conftest.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_oss_rest_store.py
  tests/store/_unity_catalog/oss_registry/test_unity_catalog_oss_rest_store.py
  tests/store/artifact/test_unity_catalog_oss_models_artifact_repo.py
  tests/utils/test_oss_registry_utils.py
  tests/utils/test_unity_catalog_oss_utils.py
Labels: area/docs, rn/feature, area/model-registry, patch-2.16.1

#13087 Disable SIM103 and UP032
  dev/update_ml_package_versions.py
  pyproject.toml
Labels: rn/none, patch-2.16.1

#13089 Fetch all reviews in `.github/workflows/require-core-maintainer-approval.js`
  .github/workflows/require-core-maintainer-approval.js
Labels: rn/none

#13080 Deprecate `mlflow deployments start-server`
  mlflow/deployments/cli.py
  mlflow/gateway/cli.py
Labels: rn/none

#13090 Migrate deployments server examples
  examples/gateway/README.md
  examples/gateway/ai21_labs/README.md
  examples/gateway/ai21_labs/config.yaml
  examples/gateway/ai21_labs/example.py
  examples/gateway/anthropic/README.md
  examples/gateway/anthropic/config.yaml
  examples/gateway/anthropic/example.py
  examples/gateway/azure_openai/README.md
  examples/gateway/azure_openai/config.yaml
  examples/gateway/bedrock/README.md
  examples/gateway/bedrock/config.yaml
  examples/gateway/bedrock/example.py
  examples/gateway/cohere/README.md
  examples/gateway/cohere/config.yaml
  examples/gateway/cohere/example.py
  examples/gateway/huggingface/README.md
  examples/gateway/huggingface/config.yaml
  examples/gateway/huggingface/example.py
  examples/gateway/mistral/README.md
  examples/gateway/mistral/config.yaml
  examples/gateway/mistral/example.py
  examples/gateway/mlflow_models/README.md
  examples/gateway/mlflow_models/config.yaml
  examples/gateway/mlflow_models/example.py
  examples/gateway/mosaicml/README.md
  examples/gateway/mosaicml/config.yaml
  examples/gateway/mosaicml/example.py
  examples/gateway/openai/README.md
  examples/gateway/openai/config.yaml
  examples/gateway/openai/example.py
  examples/gateway/palm/README.md
  examples/gateway/palm/config.yaml
  examples/gateway/palm/example.py
  examples/gateway/plugin/README.md
  examples/gateway/plugin/config.yaml
  examples/gateway/plugin/example.py
  examples/gateway/plugin/my-llm/my_llm/__init__.py
  examples/gateway/plugin/my-llm/my_llm/config.py
  examples/gateway/plugin/my-llm/my_llm/providers.py
  examples/gateway/plugin/my-llm/pyproject.toml
  examples/gateway/togetherai/README.md
  examples/gateway/togetherai/config.yaml
  examples/gateway/togetherai/example.py
  examples/gateway/uc_functions/README.md
  examples/gateway/uc_functions/run.py
Labels: rn/none

#13095 Fix input schema check for LangGraph
  mlflow/langchain/utils/chat.py
Labels: rn/none, area/models, patch-2.16.1

#13094 Reduce deprecation warnings from LangChain
  mlflow/langchain/runnables.py
  mlflow/langchain/utils/__init__.py
  tests/langchain/sample_code/chain.py
  tests/langchain/sample_code/no_config/chain.py
  tests/langchain/test_langchain_databricks_dependency_extraction.py
  tests/langchain/test_langchain_model_export.py
  tests/langchain/test_langchain_tracer.py
  tests/resources/example_mlflow_2.12_langchain_model/lc_model.py
Labels: rn/none, area/build

#13100 Fix prophet docker test
  mlflow/ml-package-versions.yml
  tests/pyfunc/docker/conftest.py
  tests/pyfunc/docker/test_docker_flavors.py
Labels: rn/none, area/build, patch-2.16.1

#13103 Add MLFLOW_UC_OSS_TOKEN env variable and add it to the credentials
  mlflow/environment_variables.py
  mlflow/utils/oss_registry_utils.py
Labels: rn/none, area/model-registry, patch-2.16.1

#13101 Add AutoGen to the tracing doc
  docs/source/llms/tracing/index.rst
  examples/autogen/tracing.py
Labels: area/docs, rn/none, patch-2.16.1

#13108 Rename `MLflow Deployments Server` in `MLflow AI Gateway` in mlflow python code
  docs/gateway_api_docs.py
  mlflow/deployments/cli.py
  mlflow/deployments/mlflow/__init__.py
  mlflow/deployments/server/app.py
  mlflow/deployments/utils.py
  mlflow/environment_variables.py
Labels: rn/none

#13091 Add docs for optimized Transformers model logging method
  docs/source/llms/transformers/guide/index.rst
  docs/source/llms/transformers/index.rst
  docs/source/llms/transformers/large-models.rst
Labels: area/docs, rn/none, patch-2.16.1

#13045 Support loading `ChatDatabricks` from the partner package
  mlflow/langchain/__init__.py
  mlflow/langchain/runnables.py
  mlflow/langchain/utils/__init__.py
  mlflow/ml-package-versions.yml
  tests/langchain/test_langchain_databricks_integration.py
Labels: rn/none, area/models, patch-2.16.1

#13098 Remove usage of a stale model from Transformers tests
  tests/pyfunc/docker/test_docker_flavors.py
  tests/transformers/conftest.py
  tests/transformers/helper.py
  tests/transformers/test_flavor_configs.py
  tests/transformers/test_transformers_model_export.py
  tests/transformers/test_transformers_prompt_templating.py
Labels: rn/none, area/build, enable-dev-tests, patch-2.16.1

#13105 Update Dependency Extraction for Agents
  mlflow/langchain/databricks_dependencies.py
  tests/langchain/sample_code/langgraph_agent.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/bug-fix, patch-2.16.1

#13104 Add workloadId and workloadClass request headers
  mlflow/tracking/request_header/databricks_request_header_provider.py
  mlflow/utils/databricks_utils.py
  tests/tracking/request_header/test_databricks_request_header_provider.py
Labels: rn/none, area/model-registry, area/tracking, patch-2.16.1

#13107 Add UC OSS documentation for the model registry
  docs/source/model-registry.rst
  mlflow/tracking/_model_registry/utils.py
Labels: area/docs, rn/none, patch-2.16.1

#13115 Update test to assert string instead
  tests/store/model_registry/test_sqlalchemy_store.py
Labels: rn/none, area/model-registry

#13132 Pin spacy
  requirements/extra-ml-requirements.txt
Labels: rn/none, patch-2.16.1

#13123 Adds RunLLM chat widget to MLflow's doc site
  docs/source/_static/runllm.js
  docs/source/conf.py
Labels: rn/documentation, patch-2.16.1

#13130 Fix llama-index cross-version dev test
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#13118 Support OTLP exporter for tracing
  docs/source/llms/tracing/index.rst
  mlflow/tracing/processor/otel.py
  mlflow/tracing/provider.py
  mlflow/tracing/utils/otlp.py
  requirements/test-requirements.txt
  tests/tracing/conftest.py
  tests/tracing/test_fluent.py
  tests/tracing/utils/test_otlp.py
Labels: rn/feature, area/tracking, patch-2.16.1

#13086 fix `Model.get_tags_dict` to return result without containing config field
  mlflow/models/model.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_rest_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/bug-fix, area/tracking, patch-2.16.1

#13134 Add meta description for tracing and eval pages
  docs/source/introduction/index.rst
  docs/source/llms/llm-evaluate/index.rst
  docs/source/llms/tracing/index.rst
Labels: rn/none, patch-2.16.1

#13133 Fix `test_from_huggingface_dataset_constructs_expected_dataset_with_revision`
  tests/data/test_huggingface_dataset_and_source.py
Labels: rn/none

#13138 feat(typing): add a py.typed file
  mlflow/py.typed
Labels: rn/none, area/artifacts, area/model-registry, area/models, area/projects, area/scoring, area/tracking, area/recipes, area/deployments

#13135 Fix param pass for langchain
  mlflow/langchain/__init__.py
  mlflow/langchain/api_request_parallel_processor.py
  tests/langchain/sample_code/model_with_config.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/none, enable-dev-tests, patch-2.16.1

#13124 Rename `MLflow Deployments Server` to `MLflow AI Gateway` in docs
  docs/source/llms/deployments/guides/index.rst
  docs/source/llms/deployments/guides/step1-create-deployments.rst
  docs/source/llms/deployments/guides/step2-query-deployments.rst
  docs/source/llms/deployments/index.rst
  docs/source/llms/deployments/uc_integration.rst
  docs/source/llms/index.rst
  docs/source/llms/llm-evaluate/index.rst
  docs/source/llms/prompt-engineering/index.rst
Labels: rn/none

#13142 Replace more `mlflow deployments start-server`
  docs/source/llms/deployments/guides/step1-create-deployments.rst
  docs/source/llms/deployments/index.rst
  docs/source/llms/deployments/uc_integration.rst
  docs/source/llms/gateway/migration.rst
  docs/source/llms/prompt-engineering/index.rst
Labels: rn/none, patch-2.16.1

#13127 Add instruction for how to cherry-pick patch PRs
  dev/check_patch_prs.py
Labels: rn/none

#13141 Support merging a remote trace to the current local trace
  mlflow/__init__.py
  mlflow/entities/span.py
  mlflow/entities/trace.py
  mlflow/tracing/constant.py
  mlflow/tracing/export/inference_table.py
  mlflow/tracing/fluent.py
  mlflow/tracing/processor/mlflow.py
  mlflow/tracing/provider.py
  mlflow/tracking/client.py
  tests/tracing/test_fluent.py
Labels: rn/none, area/tracking, patch-2.16.1

#13140 Add a warning about langchain partner pacakge and promote model-from-code
  docs/source/llms/langchain/index.rst
  docs/source/model/models-from-code.rst
Labels: area/docs, rn/none, patch-2.16.1

#13143 Add metadata field for ChatModel
  mlflow/pyfunc/__init__.py
  mlflow/types/llm.py
  tests/pyfunc/test_chat_model.py
  tests/pyfunc/test_chat_model_validation.py
Labels: rn/feature

#13155 Revert "Update Dependency Extraction for Agents (#13105)"
  mlflow/langchain/databricks_dependencies.py
  tests/langchain/sample_code/langgraph_agent.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/bug-fix, area/models, patch-2.16.2

#13152 Update release version update script to account for mlflow-skinny dependency
  dev/update_mlflow_versions.py
  tests/dev/test_update_mlflow_versions.py
Labels: rn/none, area/build, patch-2.16.2

#13156 Update node in dev container for codespaces
  .devcontainer/Dockerfile.devcontainer
Labels: rn/none

#13164 Fix broken code block in `evaluate` docstring
  mlflow/models/evaluation/base.py
Labels: area/docs, rn/none, patch-2.16.2, patch-2.16.3

#13167 Use python 3.9 for spacy dev
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#13168 Skip `test_model_pyfunc_predict_with_invalid_params` if `sentence_transformers>=3.1.0`
  tests/sentence_transformers/test_sentence_transformers_model_export.py
Labels: rn/none

#13169 Add `completion_tokens_details` to expected `usage` data in llama-index flavor tests
  tests/llama_index/test_llama_index_tracer.py
Labels: rn/none

#13153 Remove AI Gateway deprecation status
  docs/source/llms/deployments/index.rst
  docs/source/llms/gateway/index.rst
  docs/source/llms/gateway/migration.rst
  mlflow/gateway/__init__.py
Labels: area/docs, rn/documentation, patch-2.16.2

#13171 Finish protect job faster when triggered with other jobs
  .github/workflows/protect.js
Labels: rn/none

#13173 Pin sentence-transformers for transformers==4.34.1
  mlflow/ml-package-versions.yml
Labels: rn/none

#13162 Drop support for OpenAI SDK v0
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/openai/__init__.py
Labels: rn/none

#13110 Add a dry-run flag to `dev/check_patch_prs.py`
  dev/check_patch_prs.py
Labels: rn/none

#13178 Isolate mlserver dependencies
  .github/workflows/master.yml
  dev/pyproject.py
  docs/source/deployment/deploy-model-to-kubernetes/tutorial.rst
  mlflow/ml-package-versions.yml
  pyproject.release.toml
  pyproject.skinny.toml
  pyproject.toml
  requirements/test-requirements.txt
  tests/test_cli.py
Labels: rn/none

#13179 Remove useless sleep in langchain autologging test
  mlflow/ml-package-versions.yml
Labels: rn/none

#13161 Improve `_validate_non_local_source_contains_relative_paths` to reject malicious path
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#13182 Pin pydantic for `llama-index < 0.11.0`
  mlflow/ml-package-versions.yml
Labels: rn/none

#13184 Fix `is_dbfs_fuse_available` to return `False` if not in databricks runtime
  mlflow/utils/databricks_utils.py
Labels: rn/none

#13172 Fix LC autologging not to require langchain-community
  mlflow/langchain/__init__.py
  mlflow/langchain/_langchain_autolog.py
  mlflow/langchain/utils/__init__.py
  mlflow/ml-package-versions.yml
  tests/langchain/conftest.py
  tests/langchain/test_langchain_autolog.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/bug-fix, area/tracking, patch-2.16.3

#13128 Extract exceeds maximum length message
  mlflow/utils/validation.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none, area/tracking

#13186 Refactor for subprocess output redirection
  mlflow/utils/databricks_utils.py
Labels: rn/none, integrations/databricks

#13189 Add depedencies for mock openai
  mlflow/ml-package-versions.yml
Labels: rn/none

#13180 Add `from_dict()` function to ChatModel dataclasses
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/loaders/chat_model.py
  mlflow/types/llm.py
  tests/pyfunc/test_chat_model.py
  tests/pyfunc/test_chat_model_validation.py
Labels: rn/feature

#13163 Move deployment servers app and runner to gateway
  mlflow/deployments/cli.py
  mlflow/deployments/server/app.py
  mlflow/gateway/app.py
  mlflow/gateway/cli.py
  mlflow/gateway/runner.py
Labels: rn/none, area/deployments, patch-2.16.3

#13192 Install fastapi uvicorn for running mock openai server
  .github/workflows/examples.yml
Labels: rn/none

#13193 Rename deployments server to AI gateway
  docs/source/index.rst
  docs/source/new-features/index.rst
Labels: rn/none

#13197 Cherry-pick renaming patches
  docs/source/index.rst
  docs/source/llms/deployments/index.rst
  docs/source/llms/gateway/index.rst
  docs/source/llms/gateway/migration.rst
  docs/source/new-features/index.rst
  mlflow/gateway/__init__.py
Labels: rn/none

#13196 Use ruff in devcontainer
  .devcontainer/devcontainer.json
Labels: rn/none

#13176 Increase run tag value limit to 8000
  mlflow/store/db_migrations/versions/f5a4f2784254_increase_run_tag_value_limit.py
  mlflow/store/tracking/dbmodels/models.py
  mlflow/utils/validation.py
  tests/resources/db/latest_schema.sql
  tests/store/tracking/test_sqlalchemy_store.py
  tests/utils/test_validation.py
Labels: rn/none, area/tracking, autoformat

#13200 Fix D417 (`undocumented param`) for public APIs
  mlflow/h2o/__init__.py
  mlflow/keras/autologging.py
  mlflow/pyfunc/__init__.py
  mlflow/spark/__init__.py
  mlflow/statsmodels/__init__.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  mlflow/transformers/__init__.py
Labels: rn/none

#13205 Replace Deployments Server with AI Gateway
  docs/source/index.rst
  docs/source/llms/langchain/notebooks/langchain-quickstart.ipynb
  docs/source/llms/openai/notebooks/openai-quickstart.ipynb
  docs/source/llms/transformers/tutorials/conversational/pyfunc-chat-model.ipynb
Labels: rn/none

#12935 Parallel download retries & refresh credentials
  mlflow/store/artifact/cloud_artifact_repo.py
  tests/store/artifact/test_cloud_artifact_repo.py
Labels: rn/bug-fix, area/model-registry, patch-2.15.2, patch-2.16.1, patch-2.16.2, patch-2.16.3

#13208 Fix add_trace in model-from-code
  mlflow/tracing/fluent.py
  mlflow/tracing/provider.py
  tests/tracing/sample_code/model_with_add_trace.py
  tests/tracing/test_fluent.py
  tests/tracing/test_provider.py
Labels: rn/none, area/tracking, patch-2.16.3

#13223 Update `log_model` docstring
  mlflow/models/model.py
  mlflow/sklearn/__init__.py
  mlflow/utils/docstring_utils.py
Labels: rn/none

#13217 Fix AI Gateway doc
  docs/source/llms/index.rst
Labels: rn/documentation, patch-2.16.3

#13144 Make Evaluation metrics callable
  mlflow/metrics/genai/genai_metric.py
  mlflow/models/evaluation/base.py
  tests/evaluate/test_default_evaluator.py
  tests/metrics/genai/test_genai_metrics.py
  tests/metrics/test_metric_definitions.py
Labels: rn/feature

#13215 Fix tracing for LangGraph
  mlflow/langchain/__init__.py
  tests/langchain/test_langgraph.py
Labels: rn/bug-fix, area/tracking, patch-2.16.3

#13230 Move ModelFromDeploymentEndpoint class to public
  mlflow/models/evaluation/base.py
  mlflow/pyfunc/model.py
Labels: rn/none, area/models, patch-2.16.3

#13229 Update `log_inputs` and `log_outputs` docstrings
  mlflow/__init__.py
  mlflow/store/tracking/abstract_store.py
  mlflow/tracking/fluent.py
Labels: rn/none

#13207 Add guide for building custom GenAI apps with ChatModel
  docs/source/_static/images/llms/chat-model-guide/agent-trace-ui.png
  docs/source/_static/images/llms/chat-model-guide/model-config-in-ui.png
  docs/source/llms/chat-model-guide/index.rst
  docs/source/llms/custom-pyfunc-for-llms/index.rst
  docs/source/llms/index.rst
Labels: area/docs, rn/documentation, patch-2.16.3

#13224 Fix some of the D417 (undocumented-param)
  examples/pytorch/BertNewsClassification/bert_classification.py
  mlflow/data/dataset_source.py
  mlflow/data/spark_delta_utils.py
  mlflow/entities/evaluation_tag.py
  mlflow/johnsnowlabs/__init__.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/models/wheeled_model.py
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_lightning_autolog.py
  mlflow/recipes/utils/tracking.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/tracing/fluent.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/request_header/registry.py
  mlflow/transformers/llm_inference_utils.py
  mlflow/transformers/model_io.py
  mlflow/types/schema.py
  mlflow/utils/credentials.py
  mlflow/utils/databricks_utils.py
  mlflow/utils/docstring_utils.py
  mlflow/utils/file_utils.py
  mlflow/utils/model_utils.py
  mlflow/utils/uri.py
  tests/sagemaker/mock/__init__.py
Labels: area/docs, rn/documentation

#13225 Update `log_model` in all flavors
  mlflow/catboost/__init__.py
  mlflow/diviner/__init__.py
  mlflow/fastai/__init__.py
  mlflow/gluon/__init__.py
  mlflow/h2o/__init__.py
  mlflow/johnsnowlabs/__init__.py
  mlflow/keras/save.py
  mlflow/langchain/__init__.py
  mlflow/lightgbm/__init__.py
  mlflow/llama_index/__init__.py
  mlflow/mleap/__init__.py
  mlflow/models/model.py
  mlflow/onnx/__init__.py
  mlflow/openai/__init__.py
  mlflow/paddle/__init__.py
  mlflow/pmdarima/__init__.py
  mlflow/promptflow/__init__.py
  mlflow/prophet/__init__.py
  mlflow/pyfunc/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/sentence_transformers/__init__.py
  mlflow/shap/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/spacy/__init__.py
  mlflow/spark/__init__.py
  mlflow/statsmodels/__init__.py
  mlflow/tensorflow/__init__.py
  mlflow/transformers/__init__.py
  mlflow/utils/docstring_utils.py
  mlflow/xgboost/__init__.py
Labels: rn/none

#13191 Add tool calling support for ChatModel
  docs/source/conf.py
  mlflow/pyfunc/loaders/chat_model.py
  mlflow/types/llm.py
  tests/pyfunc/test_chat_model.py
Labels: rn/feature

#13190 Remove pydantic import warning for Langchain >= 0.3.0
  mlflow/langchain/runnables.py
  mlflow/langchain/utils/serialization.py
  mlflow/tracing/utils/__init__.py
Labels: rn/none, area/tracking, patch-2.16.3

#13234 Fix `_get_workspace_url` to get correct workspace URL in serverless
  mlflow/utils/databricks_utils.py
Labels: rn/none

#13237 Update proto
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
Labels: rn/none

#13238 Change `@mlflow-automation autoformat` to `/autoformat`
  .github/workflows/autoformat.js
  .github/workflows/autoformat.md
  .github/workflows/autoformat.yml
  dev/format.py
  dev/ruff.py
  dev/test-generate-protos.sh
Labels: rn/none

#13240 Update metric proto
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
  mlflow/server/graphql/autogenerated_graphql_schema.py
  mlflow/server/js/src/graphql/autogenerated_schema.gql
Labels: rn/none

#13222 feat: add support for route_optimized parameter in databricks deployment client
  mlflow/deployments/databricks/__init__.py
Labels: area/docs, rn/feature, integrations/databricks, area/deployments, patch-2.16.3

#13236 Update scikit-learn autolog
  .github/workflows/mlflow-3.yaml
  examples/mlflow-3/sklearn_autolog.py
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
  mlflow/utils/autologging_utils/client.py
Labels: rn/none

#13243 Fix LangChain model test for 0.3.x
  docs/source/llms/langchain/index.rst
  mlflow/langchain/databricks_dependencies.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/none, area/tracking

#13260 fix spacy version
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
Labels: rn/none, area/build

#13265 fix: correct typo from 'experment_url' to 'experiment_url'
  mlflow/tracking/_tracking_service/client.py
Labels: rn/none, area/tracking, patch-2.16.3

#13251 Add run_id parameter to the search_trace API
  docs/source/llms/tracing/index.rst
  mlflow/tracing/fluent.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  tests/tracing/test_fluent.py
Labels: rn/documentation, area/tracking

#13233 Use None for schema and profile when fields are absent in proto
  mlflow/entities/dataset.py
  tests/entities/test_dataset.py
Labels: rn/none, area/tracking, patch-2.16.3

#13246 [MLflow] Support multiple retrievers schema via set_retriever_schema
  mlflow/models/dependencies_schemas.py
  tests/models/test_dependencies_schema.py
Labels: rn/feature, area/tracking

#13131 Add dspy flavor to MLflow
  docs/source/python_api/mlflow.dspy.rst
  mlflow/__init__.py
  mlflow/dspy/__init__.py
  mlflow/dspy/load.py
  mlflow/dspy/save.py
  mlflow/dspy/wrapper.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/models/rag_signatures.py
  mlflow/utils/requirements_utils.py
  tests/dspy/test_save.py
  tests/utils/test_requirements_utils.py
Labels: rn/feature, area/models

#13266 Update Databricks dependency extraction to handle the partner package.
  mlflow/langchain/databricks_dependencies.py
  mlflow/ml-package-versions.yml
  tests/langchain/test_langchain_databricks_dependency_extraction.py
Labels: rn/bug-fix, area/models, patch-2.17.0

#13267 Drop MLflow 1.28 Tensorflow tests
  mlflow/ml-package-versions.yml
  tests/tensorflow/mlflow-128-tf-26-env.yaml
  tests/tensorflow/test_keras_model_export.py
  tests/tensorflow/test_load_saved_tensorflow_estimator.py
Labels: rn/none

#13242 Standardize retriever span outputs to a list of MLflow `Document`s
  docs/source/llms/tracing/tracing-schema.rst
  mlflow/entities/__init__.py
  mlflow/entities/document.py
  mlflow/langchain/langchain_tracer.py
  mlflow/llama_index/tracer.py
  tests/langchain/test_langchain_document_conversion.py
  tests/langchain/test_langchain_tracer.py
  tests/llama_index/test_llama_index_node_conversion.py
  tests/llama_index/test_llama_index_tracer.py
Labels: rn/feature

#13270 Add proto for `finalizeLoggedModel` and `getLoggedModel`
  mlflow/protos/service.proto
Labels: rn/none
