Repository mlflow/mlflow, pull requests merged in 2024-12, with the labels that each got.

#13929 Fix any to Any
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  mlflow/llama_index/serialize_objects.py
  mlflow/openai/api_request_parallel_processor.py
  tests/dspy/test_dspy_autolog.py
  tests/models/test_cli.py
  tests/test_cli.py
Labels: rn/none

#13925 Pin httpx for anthropic
  mlflow/ml-package-versions.yml
Labels: rn/none

#13916 Only test every 10 version of OpenAI
  dev/set_matrix.py
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build, v2.18.1

#13920 [ML-48053] Update sidebar labels
  docs/docs/traditional-ml/creating-custom-pyfunc/notebooks/index.mdx
  docs/docs/traditional-ml/hyperparameter-tuning-with-child-runs/notebooks/index.mdx
  docs/docs/traditional-ml/hyperparameter-tuning-with-child-runs/part1-child-runs/index.mdx
  docs/docs/traditional-ml/hyperparameter-tuning-with-child-runs/part2-logging-plots/index.mdx
Labels: rn/none

#13917 Fix pyfunc data conversion
  mlflow/models/utils.py
  mlflow/pyfunc/model.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
Labels: rn/none, v2.18.1

#13892 Record input parameters to span attributes in OpenAI autologging
  mlflow/openai/_openai_autolog.py
  tests/openai/test_openai_autolog.py
Labels: rn/none, area/tracking, v2.18.1

#13862 Migrate OpenAI LLM judge implementation to use gateway provider
  mlflow/gateway/providers/openai.py
  mlflow/gateway/utils.py
  mlflow/metrics/genai/model_utils.py
  mlflow/openai/__init__.py
  mlflow/utils/openai_utils.py
  pyproject.toml
  tests/metrics/genai/test_model_utils.py
Labels: rn/none, area/tracking, v2.18.1

#13943 Format python code examples
  .pre-commit-config.yaml
  docs/docs/deep-learning/tensorflow/guide/index.mdx
  docs/docs/getting-started/logging-first-model/step6-logging-a-run/index.mdx
  docs/docs/llms/tracing/index.mdx
  docs/docs/models/index.mdx
  docs/docs/plugins/index.mdx
Labels: rn/none

#13947 Replace non-existing functions #13941
  mlflow/metrics/__init__.py
Labels: rn/none

#13895 Set dspy settings at `predict` call
  mlflow/dspy/load.py
  mlflow/dspy/wrapper.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  tests/dspy/test_save.py
Labels: rn/bug-fix, v2.18.1

#13954 Fix rdoc build script on new macbooks
  docs/build-rdoc.sh
Labels: rn/none

#13936 Prevent notebook display of traces when display is disabled
  mlflow/entities/trace.py
  mlflow/tracing/display/display_handler.py
  tests/tracing/display/test_ipython.py
Labels: rn/none

#13944 [ML-48074] Migrate tutorials and examples page
  docs/docs/tutorials-and-examples/index.mdx
  docs/rst_to_migrate/tutorials-and-examples/index.rst
Labels: rn/none

#13913 Add log_trace option to mlflow.autolog
  .github/workflows/master.yml
  mlflow/autogen/__init__.py
  mlflow/dspy/autolog.py
  mlflow/litellm/__init__.py
  mlflow/llama_index/__init__.py
  mlflow/tracking/fluent.py
  requirements/extra-ml-requirements.txt
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/none, v2.18.1

#13946 Ml 48074 migrate auth
  docs/docs/auth/index.mdx
  docs/docusaurus.config.ts
  docs/rst_to_migrate/auth/index.rst
Labels: rn/none

#13949 [ML-48075] Migrate tracking/tutorials pages
  docs/docs/tracking/tutorials/local-database/index.mdx
  docs/docs/tracking/tutorials/remote-server/index.mdx
  docs/rst_to_migrate/tracking/tutorials/local-database.rst
  docs/rst_to_migrate/tracking/tutorials/remote-server.rst
Labels: rn/none

#13950 [ML-48075] Migrate tracking/artifacts-stores page
  docs/docs/tracking/artifacts-stores/index.mdx
  docs/rst_to_migrate/tracking/artifacts-stores.rst
Labels: rn/none

#13903 Introduce crewai tracing
  conftest.py
  docs/source/_static/images/llms/crewai/crewai-trace.png
  docs/source/_static/images/logos/crewai-logo.png
  docs/source/llms/tracing/index.rst
  docs/source/python_api/mlflow.crewai.rst
  examples/crewai/tracing.py
  mlflow/__init__.py
  mlflow/crewai/__init__.py
  mlflow/crewai/autolog.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  tests/crewai/test_crewai_autolog.py
Labels: area/docs, rn/feature, area/examples, v2.18.1

#13889 Fix mlflow.evaluate() to allow passing in a spark connect dataframe
  mlflow/data/evaluation_dataset.py
  mlflow/utils/spark_utils.py
Labels: rn/bug-fix, area/tracking, autoformat, v2.18.1

#13914 Suppress "Failed to detach context" warning from OpenTelemetry
  mlflow/langchain/_langchain_autolog.py
  mlflow/langchain/langchain_tracer.py
  mlflow/tracing/provider.py
  mlflow/tracing/utils/token.py
  tests/tracing/utils/test_token.py
Labels: rn/none, area/tracking, v2.18.1

#13957 Deflake `test_litellm_tracing_async_streaming`
  tests/litellm/test_litellm_autolog.py
Labels: rn/none

#13960 Fix LlamaIndex module import failure after mlflow.autolog()
  mlflow/llama_index/tracer.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/none, area/tracking, v2.18.1

#13937 Add Ollama and Instructor examples in tracing doc
  docs/source/_static/images/llms/tracing/instructor-tracing.png
  docs/source/_static/images/llms/tracing/ollama-tracing.png
  docs/source/_static/images/logos/autogen-logo.png
  docs/source/_static/images/logos/autogen-logo.svg
  docs/source/_static/images/logos/instructor-logo.svg
  docs/source/_static/images/logos/ollama-logo.png
  docs/source/llms/tracing/index.rst
Labels: area/docs, rn/documentation, v2.18.1

#13959 Install `pytest-repeat`
  requirements/test-requirements.txt
Labels: rn/none

#13961 [ML-48075] Migrate tracking/autolog page
  docs/docs/tracking/autolog/index.mdx
  docs/docs/tracking/index.mdx
  docs/rst_to_migrate/tracking/autolog.rst
Labels: rn/none

#13962 [ML-48075] Migrate tracking/backend-stores page
  docs/docs/tracking/artifacts-stores/index.mdx
  docs/docs/tracking/backend-stores/index.mdx
  docs/rst_to_migrate/tracking/backend-stores.rst
Labels: rn/none

#13964 [ML-48075] Migrate tracking/data-api page
  docs/docs/tracking/data-api/index.mdx
  docs/rst_to_migrate/tracking/data-api.rst
Labels: rn/none

#13969 Detect incorrect `callable` type hints
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
Labels: rn/none

#13968 Add warning to use AnyType if infer_signature fails
  mlflow/models/signature.py
  tests/pyfunc/test_spark.py
Labels: rn/none, v2.18.1, v2.19.0

#13972 Fix input_example logging for chat model
  mlflow/pyfunc/__init__.py
  mlflow/types/llm.py
  tests/pyfunc/test_chat_model.py
Labels: rn/none

#13970 Simplify baseUrl env var in docusaurus config
  .circleci/config.yml
  docs/docusaurus.config.ts
Labels: rn/none

#13983 Update changelog
  CHANGELOG.md
Labels: rn/none

#13945 [ML-48076] Migrate new features page
  docs/docs/models/index.mdx
  docs/docs/new-features/index.mdx
  docs/rst_to_migrate/new-features/index.rst
  docs/src/components/Card/card.module.css
  docs/src/components/Card/index.tsx
Labels: rn/none

#13978 [ML-48075] Migrate tracking/server page
  docs/docs/tracking/autolog/index.mdx
  docs/docs/tracking/server/index.mdx
  docs/docusaurus.config.ts
  docs/rst_to_migrate/tracking/server.rst
Labels: rn/none

#13981 [ML-48075] Migrate tracking/tracking-api page
  docs/docs/tracking/tracking-api/index.mdx
  docs/rst_to_migrate/tracking/tracking-api.rst
Labels: rn/none

#13638 Added parenthesis to docs
  mlflow/models/evaluation/base.py
Labels: area/docs, rn/none, area/examples, patch-2.17.3

#13985 Fix request/response field in the search_traces output
  mlflow/entities/trace.py
  tests/tracing/test_fluent.py
Labels: rn/bug-fix, area/tracking

#13982 Add databricks extra to build job
  .github/workflows/build-wheel.yml
Labels: rn/none, area/build

#13995 Revert "Add databricks extra to build job"
  .github/workflows/build-wheel.yml
Labels: rn/none

#13996 Import `tracing` module in `mlflow/__init__.py`
  mlflow/__init__.py
Labels: rn/none

#13990 Remove Gluon flavor
  conftest.py
  dev/set_matrix.py
  docs/source/models.rst
  docs/source/python_api/mlflow.gluon.rst
  docs/source/tracking/autolog.rst
  docs/source/tutorials-and-examples/index.rst
  examples/gluon/train.py
  mlflow/__init__.py
  mlflow/gluon/__init__.py
  mlflow/gluon/_autolog.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/models/__init__.py
  mlflow/models/evaluation/utils/trace.py
  mlflow/tracking/fluent.py
  requirements/extra-ml-requirements.txt
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/breaking-change, area/tracking

#13997 Unpin `huggingface-hub`
  requirements/test-requirements.txt
Labels: rn/none

#14001 Mark tracing client APIs experimental
  docs/source/llms/tracing/index.rst
  mlflow/tracing/fluent.py
  mlflow/tracking/client.py
Labels: area/docs, rn/none, v2.19.0

#14000 Run `astral-sh/setup-uv` action in `.github/actions/setup-python` action
  .github/actions/setup-python/action.yml
  .github/workflows/lint.yml
Labels: rn/none

#14002 Fix closing-pr to ignore PRs
  .github/workflows/closing-pr.js
Labels: rn/none

#13971 Add crewai to mlflow.autolog
  mlflow/tracking/fluent.py
  tests/crewai/test_crewai_autolog.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/none

#14003 Remove flaml pin
  requirements/test-requirements.txt
Labels: rn/none

#13988 Add section for validating models in the Model page
  docs/source/models.rst
Labels: rn/none

#13998 Fix run ending behavior in context manager
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/none, v2.19.0

#14009 Improve example for validating model
  docs/source/models.rst
Labels: rn/none

#13942 Added warning as mlflow.transformers.generate_signature_output is deprecated #13327
  examples/transformers/simple.py
  mlflow/transformers/signature.py
Labels: rn/none, area/tracking, autoformat

#14012 Fix an reference error in a model doc
  docs/source/models.rst
Labels: rn/none

#14010 Fix PEFT-related transformers cross version issues
  mlflow/ml-package-versions.yml
  tests/transformers/test_transformers_peft_model.py
Labels: rn/none, v2.19.0

#13924 Add type hints support including pydantic models
  .github/workflows/master.yml
  mlflow/types/schema.py
  mlflow/types/type_hints.py
  pyproject.release.toml
  pyproject.skinny.toml
  pyproject.toml
  requirements/gateway-requirements.txt
  requirements/gateway-requirements.yaml
  requirements/skinny-requirements.txt
  requirements/skinny-requirements.yaml
  tests/types/test_type_hints.py
Labels: rn/feature, area/models

#14011 Update example in tracing contribution guide
  docs/source/llms/tracing/contribute.rst
Labels: area/docs, rn/none, v2.19.0

#14014 Add python 3.10 job
  .github/workflows/master.yml
Labels: rn/none

#13948 Fix type annotations for list_artifacts method
  mlflow/store/artifact/artifact_repo.py
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/store/artifact/databricks_sdk_models_artifact_repo.py
  mlflow/store/artifact/dbfs_artifact_repo.py
Labels: rn/none, area/tracking, integrations/azure, integrations/sagemaker, integrations/databricks

#13984 Add an method for search spans within a trace
  docs/source/conf.py
  docs/source/llms/tracing/index.rst
  mlflow/entities/trace.py
  mlflow/gateway/providers/openai.py
  tests/entities/test_trace.py
  tests/metrics/genai/test_model_utils.py
Labels: rn/feature, area/tracking, v2.19.0

#14007 Update custom_inputs and custom_outputs docs to reflect that they are now map[str, Any]
  mlflow/types/llm.py
Labels: rn/none, v2.19.0

#14023 [tracing] Fix Tracing section
  docs/source/index.rst
Labels: rn/documentation, v2.19.0

#14019 [ML-48351] Migrate model/models-from-code page
  docs/docs/model/models-from-code/index.mdx
  docs/rst_to_migrate/model/models-from-code.rst
Labels: rn/none

#14026 [ML-48352] Migrate llms/transformers pages
  docs/docs/llms/transformers/index.mdx
  docs/docs/llms/transformers/large-models/index.mdx
  docs/docs/llms/transformers/task/index.mdx
  docs/rst_to_migrate/llms/transformers/index.rst
  docs/rst_to_migrate/llms/transformers/large-models.rst
  docs/rst_to_migrate/llms/transformers/task.rst
Labels: rn/none

#14020 [ML-48351] Migrate model signatures
  docs/docs/deployment/deploy-model-locally/index.mdx
  docs/docs/model/signatures/index.mdx
  docs/docs/tracking/autolog/index.mdx
  docs/rst_to_migrate/model/signatures.rst
Labels: rn/none

#14021 [ML-48351] Migrate model/dependencies page
  docs/docs/model/dependencies/index.mdx
  docs/rst_to_migrate/model/dependencies.rst
Labels: rn/none

#14028 Remove deprecated squared parameter
  mlflow/metrics/metric_definitions.py
  mlflow/models/evaluation/evaluators/regressor.py
Labels: rn/bug-fix, area/tracking, v2.19.0

#13987 Optimize tracing enablement logic for evaluation
  mlflow/models/evaluation/utils/trace.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/import_hooks/__init__.py
  tests/dspy/test_dspy_evaluate.py
  tests/langchain/test_langchain_evaluation.py
  tests/llama_index/test_llama_index_evaluate.py
  tests/openai/test_openai_evaluate.py
  tests/tracing/helper.py
Labels: rn/none, area/tracking, v2.19.0

#14029 Make the source in Assessment optional & add CODE as a new AssessmentSourceType
  mlflow/entities/assessment_source.py
  mlflow/evaluation/assessment.py
  tests/evaluate/logging/test_assessment.py
Labels: rn/none, v2.19.0

#14015 Stringify param values in client.log_batch()
  mlflow/tracking/client.py
  tests/tracking/test_tracking.py
Labels: rn/bug-fix, area/tracking, v2.19.0

#14027 return empty array when DatabricksSDKModelsArtifactRepository.list_artifacts is called on a file
  mlflow/store/artifact/databricks_sdk_models_artifact_repo.py
  tests/store/artifact/test_databricks_sdk_models_artifact_repo.py
Labels: rn/bug-fix, area/model-registry, v2.19.0

#14032 Drop support for LightGBM < 3.3
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
Labels: rn/none

#14040 Use `mean_squared_error` if `root_mean_squared_error` is unavailable
  mlflow/metrics/metric_definitions.py
  mlflow/models/evaluation/evaluators/regressor.py
Labels: rn/none

#14025 Add additional milisecond in test_search_experiments_filter_by_time_attribute
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none, area/tracking

#14036 Fix eval test failure
  tests/evaluate/test_evaluation.py
Labels: rn/none, v2.19.0

#13989 Support passing model alias for split_models_uri
  mlflow/store/artifact/models_artifact_repo.py
  tests/store/artifact/test_models_artifact_repo.py
Labels: rn/none, v2.19.0

#14038 Temporarily pin sklearn to <1.6 in test requirements
  requirements/test-requirements.txt
Labels: rn/none, v2.19.0

#14044 [ML-48352] Migrate llms/transformers/guide page
  docs/docs/llms/transformers/guide/index.mdx
  docs/rst_to_migrate/llms/transformers/guide/index.rst
Labels: rn/none

#14052 Fix some links in docusaurus
  docs/docs/deployment/deploy-model-to-kubernetes/index.mdx
  docs/docs/introduction/index.mdx
  docs/docs/llms/sentence-transformers/guide/index.mdx
  docs/docs/model-evaluation/index.mdx
  docs/docs/model/models-from-code/index.mdx
Labels: rn/none

#14033 Add a page for search_traces
  docs/source/_static/images/llms/tracing/search-traces.png
  docs/source/llms/index.rst
  docs/source/llms/tracing/index.rst
  docs/source/llms/tracing/search-traces.rst
Labels: rn/documentation

#14039 Add documentation for predict API and uv as env manager
  docs/source/model/dependencies.rst
  docs/source/models.rst
Labels: rn/documentation

#14060 Escape special characters that could be interpreted as a formula
  mlflow/server/js/src/experiment-tracking/utils/CsvUtils.test.ts
  mlflow/server/js/src/experiment-tracking/utils/CsvUtils.ts
Labels: rn/none

#14053 Fix `content` type in mock OpenAI server
  tests/openai/mock_openai.py
Labels: rn/none

#14063 [ML-48355] Migrate llms/prompt-engineering page
  docs/docs/llms/prompt-engineering/index.mdx
  docs/rst_to_migrate/llms/prompt-engineering/index.rst
Labels: rn/none

#14070 Fix test failures in `csvUtils.test.ts`
  mlflow/server/js/src/experiment-tracking/utils/CsvUtils.test.ts
  mlflow/server/js/src/experiment-tracking/utils/CsvUtils.ts
Labels: rn/none

#14068 Set default task for ChatModel
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
  tests/pyfunc/test_chat_model.py
Labels: rn/feature, area/models, v2.19.1

#14073 [1/N] Tracing doc overhaul
  docs/docs/llms/tracing/index.mdx
  docs/docs/tracing/concept.mdx
  docs/docs/tracing/faq.mdx
  docs/docs/tracing/index.mdx
  docs/docs/tracing/integrations/contribute.mdx
  docs/docs/tracing/integrations/index.mdx
  docs/docs/tracing/production.mdx
  docs/docs/tracing/sdk/client.mdx
  docs/docs/tracing/sdk/how-to.mdx
  docs/docs/tracing/sdk/index.mdx
  docs/docs/tracing/sdk/manual-instrumentation.mdx
  docs/docs/tracing/sdk/search.mdx
  docs/docs/tracing/session.mdx
  docs/docs/tracing/tracing-schema.mdx
  docs/docusaurus.config.ts
  docs/package-lock.json
  docs/package.json
  docs/sidebars.ts
  docs/static/images/llms/tracing/search-traces.png
  docs/static/images/llms/tracing/tracing-auto-manual-mix.png
  docs/yarn.lock
Labels: rn/none, area/tracking

#14077 Fix R job in docusaurus
  docs/api_reference/source/R-api.rst
  docs/source/_static/images/llms/crewai/crewai-trace.png
  mlflow/R/mlflow/document.R
Labels: rn/none

#14072 Add pre-commit hook to detect trace iframe in ipynb files
  .pre-commit-config.yaml
  dev/check-notebooks.sh
Labels: rn/none

#14076 [ML-48357] Migrate llms/openai pages
  docs/docs/llms/openai/autologging/index.mdx
  docs/docs/llms/openai/guide/index.mdx
  docs/docs/llms/openai/index.mdx
  docs/rst_to_migrate/llms/openai/autologging.rst
  docs/rst_to_migrate/llms/openai/guide/index.rst
  docs/rst_to_migrate/llms/openai/index.rst
Labels: rn/none

#14074 Replace `types_or` with `files` in `.pre-commit-config.yaml`
  .pre-commit-config.yaml
Labels: rn/none

#14078 Disallow top-level `permissions` config in github actions workflows
  .github/policy.rego
  .github/workflows/advice.yml
  .github/workflows/autoformat.yml
  .github/workflows/build-wheel.yml
  .github/workflows/cancel.yml
  .github/workflows/cherry-picks-warn.yml
  .github/workflows/closing-pr.yml
  .github/workflows/cross-version-test-runner.yml
  .github/workflows/cross-version-tests.yml
  .github/workflows/deployments.yml
  .github/workflows/dev-setup.yml
  .github/workflows/devcontainer.yml
  .github/workflows/examples.yml
  .github/workflows/gateway.yml
  .github/workflows/js.yml
  .github/workflows/labeling.yml
  .github/workflows/lint.yml
  .github/workflows/maintainer-approval.yml
  .github/workflows/master.yml
  .github/workflows/patch.yml
  .github/workflows/preview-docs.yml
  .github/workflows/protect.yml
  .github/workflows/protobuf-cross-test.yml
  .github/workflows/protos.yml
  .github/workflows/push-images.yml
  .github/workflows/r.yml
  .github/workflows/recipe-template.yml
  .github/workflows/recipe.yml
  .github/workflows/release-note.yml
  .github/workflows/requirements.yml
  .github/workflows/rerun-cross-version-tests.yml
  .github/workflows/rerun-workflow-run.yml
  .github/workflows/rerun.yml
  .github/workflows/slow-tests.yml
  .pre-commit-config.yaml
Labels: rn/none

#14069 Add private API to log a trace directly to backend
  mlflow/tracking/client.py
  tests/tracking/test_client.py
Labels: rn/none, area/tracking, v2.19.1

#14064 Make all links relative to root
  docs/docs/deep-learning/index.mdx
  docs/docs/deep-learning/keras/index.mdx
  docs/docs/deep-learning/pytorch/index.mdx
  docs/docs/deep-learning/tensorflow/index.mdx
  docs/docs/deployment/deploy-model-to-kubernetes/index.mdx
  docs/docs/deployment/index.mdx
  docs/docs/getting-started/index.mdx
  docs/docs/getting-started/intro-quickstart/index.mdx
  docs/docs/getting-started/intro-quickstart/notebooks/index.mdx
  docs/docs/getting-started/logging-first-model/index.mdx
  docs/docs/index.mdx
  docs/docs/introduction/index.mdx
  docs/docs/llms/index.mdx
  docs/docs/llms/rag/notebooks/index.mdx
  docs/docs/llms/sentence-transformers/index.mdx
  docs/docs/llms/transformers/guide/index.mdx
  docs/docs/llms/transformers/index.mdx
  docs/docs/llms/transformers/tutorials/conversational/pyfunc-chat-model.ipynb
  docs/docs/model-evaluation/index.mdx
  docs/docs/model-registry/index.mdx
  docs/docs/models/index.mdx
  docs/docs/projects/index.mdx
  docs/docs/tracing/concept.mdx
  docs/docs/tracing/index.mdx
  docs/docs/tracing/integrations/contribute.mdx
  docs/docs/tracing/production.mdx
  docs/docs/tracing/sdk/client.mdx
  docs/docs/tracing/sdk/how-to.mdx
  docs/docs/tracing/sdk/manual-instrumentation.mdx
  docs/docs/tracing/sdk/search.mdx
  docs/docs/tracing/session.mdx
  docs/docs/tracing/tracing-schema.mdx
  docs/docs/tracking/artifacts-stores/index.mdx
  docs/docs/tracking/index.mdx
  docs/docs/tracking/tracking-api/index.mdx
  docs/docs/tracking/tutorials/local-database/index.mdx
  docs/docs/traditional-ml/creating-custom-pyfunc/index.mdx
  docs/docs/traditional-ml/hyperparameter-tuning-with-child-runs/index.mdx
  docs/docs/traditional-ml/index.mdx
Labels: rn/none

#14059 Support predict function without context param for PythonModel and ChatModel
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/loaders/chat_model.py
  mlflow/pyfunc/model.py
  mlflow/pyfunc/scoring_server/__init__.py
  mlflow/pyfunc/stdin_server.py
  tests/pyfunc/test_chat_model.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
Labels: rn/feature

#14085 Prevent unsafe checkout in `pull_request_target` workflows
  .github/policy.rego
Labels: rn/none

#14089 Use GitHub App to harden security in autoformat workflow
  .github/workflows/autoformat.yml
Labels: rn/none

#14086 Add warning if `predict` method has different signature
  docs/source/model/signatures.rst
  docs/source/plugins.rst
  mlflow/pyfunc/model.py
  tests/evaluate/test_evaluation.py
  tests/models/test_cli.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
  tests/pytorch/test_pytorch_model_export.py
  tests/store/lineage/test_downstream_lineage.py
  tests/utils/test_requirements_utils.py
Labels: rn/none

#14090 Prevent shell injection in `.github/workflows/autoformat.yml`
  .github/workflows/autoformat.yml
Labels: rn/none

#14095 Auto approve workflows triggered by automation app
  .github/workflows/autoformat.js
  .github/workflows/autoformat.yml
Labels: rn/none

#14093 Prevent unnecessary `github-token` use for `actions/github-script` action
  .github/policy.rego
  .github/workflows/rerun-workflow-run.yml
Labels: rn/none

#14104 Migrate llms/custom-pyfunc-for-llms pages
  docs/docs/llms/custom-pyfunc-for-llms/index.mdx
  docs/docs/llms/custom-pyfunc-for-llms/notebooks/index.mdx
  docs/rst_to_migrate/llms/custom-pyfunc-for-llms/index.rst
  docs/rst_to_migrate/llms/custom-pyfunc-for-llms/notebooks/index.rst
Labels: rn/none

#14105 Migrate llms/chat-model-guide page
  docs/docs/llms/chat-model-guide/index.mdx
  docs/rst_to_migrate/llms/chat-model-guide/index.rst
Labels: rn/none

#14106 Migrate llms/chat-model-intro
  docs/docs/llms/chat-model-intro/index.mdx
  docs/docs/model/signatures/index.mdx
  docs/rst_to_migrate/llms/chat-model-intro/chat-model-vs-pyfunc-table.rst
  docs/rst_to_migrate/llms/chat-model-intro/index.rst
Labels: rn/none

#14099 [1/2] Update type hint infer and validation logic
  .github/workflows/master.yml
  mlflow/types/type_hints.py
  tests/types/test_type_hints.py
Labels: rn/none

#14111 Fix `invalid-type-annotation` rule
  dev/clint/src/clint/linter.py
  mlflow/data/dataset_registry.py
  mlflow/llama_index/serialize_objects.py
  mlflow/recipes/steps/automl/flaml.py
Labels: rn/none

#14116 Fix Anthropic CI
  tests/anthropic/test_anthropic_autolog.py
Labels: rn/none, area/build, enable-dev-tests

#14084 Display a recipe for model evaluation when logging a Mosaic AI agent
  dev/pyproject.py
  mlflow/models/display_utils.py
  mlflow/models/model.py
  mlflow/models/resources/agent_evaluation_template.html
  mlflow/models/resources/eval_with_dataset_example.py
  mlflow/models/resources/eval_with_synthetic_example.py
  pyproject.release.toml
  pyproject.skinny.toml
  pyproject.toml
  tests/models/test_display_utils.py
  tests/models/test_model.py
Labels: rn/none, area/uiux, area/models, integrations/databricks

#14018 Support tracing for Bedrock LLM calls
  conftest.py
  mlflow/__init__.py
  mlflow/bedrock/__init__.py
  mlflow/bedrock/_autolog.py
  mlflow/entities/span.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/tracking/fluent.py
  tests/bedrock/test_bedrock_autolog.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/feature, area/tracking

#14079 Fix sentence transformer CI
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#13955 Jupyter notebook trace UI display
  mlflow/entities/trace.py
  mlflow/server/js/public/lib/notebook-trace-renderer/css/406.5d125dec.chunk.css
  mlflow/server/js/public/lib/notebook-trace-renderer/index.html
  mlflow/server/js/public/lib/notebook-trace-renderer/js/18.6739a820.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/331.e51faec3.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/383.f21098b2.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/406.3926360c.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/451.8920c570.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/669.f9edf07d.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/ml-model-trace-renderer.c772b289.js
  mlflow/tracing/display/__init__.py
  mlflow/tracing/display/display_handler.py
  tests/tracing/display/test_ipython.py
Labels: rn/feature, area/uiux

#14087 Add standardized messages and tools attributes in span schema
  docs/source/conf.py
  docs/source/llms/tracing/tracing-schema.rst
  docs/source/python_api/mlflow.types.rst
  mlflow/gateway/config.py
  mlflow/gateway/schemas/chat.py
  mlflow/gateway/schemas/completions.py
  mlflow/gateway/schemas/embeddings.py
  mlflow/langchain/utils/chat.py
  mlflow/llama_index/tracer.py
  mlflow/metrics/genai/model_utils.py
  mlflow/tracing/__init__.py
  mlflow/tracing/constant.py
  mlflow/tracing/utils/__init__.py
  mlflow/types/chat.py
  mlflow/utils/__init__.py
  tests/deployments/server/test_server_app.py
  tests/gateway/providers/test_anthropic.py
  tests/gateway/providers/test_cohere.py
  tests/gateway/providers/test_mlflow.py
  tests/gateway/providers/test_mosaicml.py
  tests/gateway/providers/test_openai.py
  tests/gateway/providers/test_openai_uc_functions.py
  tests/gateway/providers/test_palm.py
  tests/gateway/providers/test_togetherai.py
  tests/gateway/schemas/test_chat.py
  tests/gateway/test_gateway_app.py
  tests/gateway/test_integration.py
  tests/tracing/utils/test_utils.py
Labels: rn/feature

#14115 Fix llama index CI
  tests/llama_index/test_llama_index_tracer.py
Labels: rn/none, area/build, enable-dev-tests

#14121 Add timout-minutes to Github Actions workflows (#14101)
  .github/policy.rego
  .github/workflows/devcontainer.yml
  .github/workflows/js.yml
  .github/workflows/maintainer-approval.yml
  .github/workflows/recipe-template.yml
  .github/workflows/recipe.yml
  .github/workflows/team-review.yml
Labels: rn/none, area/build

#14119 Migrate llms/llama-index
  docs/docs/llms/llama-index/index.mdx
  docs/rst_to_migrate/llms/llama-index/index.rst
Labels: rn/none

#14114 Migrate llms/dspy page
  docs/docs/llms/dspy/index.mdx
  docs/rst_to_migrate/llms/dspy/index.rst
Labels: rn/none

#14122 Fix code block parsing error
  docs/docs/llms/llama-index/index.mdx
Labels: rn/none

#14112 Add `typing-extensions` as a dependency
  dev/clint/src/clint/config.py
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  mlflow/data/code_dataset_source.py
  pyproject.skinny.toml
  pyproject.toml
  requirements/skinny-requirements.txt
  requirements/skinny-requirements.yaml
Labels: rn/none

#14126 disable recipe-windows test
  .github/workflows/recipe.yml
Labels: rn/none, area/build

#14103 Update databricks_uc_registry_messages.proto to add `securable` field for `EmitModelVersionLineageRequest` message
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/server/js/src/graphql/autogenerated_schema.gql
Labels: rn/none, area/tracking

#14133 Added await in advice.yml and closing-pr.yml files issue #14124
  .github/workflows/advice.yml
  .github/workflows/closing-pr.yml
Labels: rn/none

#14134 Migrate llms/deployments/index.mdx page
  docs/docs/community-model-flavors/index.mdx
  docs/docs/introduction/index.mdx
  docs/docs/llms/deployments/index.mdx
  docs/docusaurus.config.ts
  docs/rst_to_migrate/llms/deployments/index.rst
Labels: rn/none

#14132 Docs for Jupyter Trace UI
  docs/source/_static/images/llms/tracing/jupyter-trace-ui.png
  docs/source/llms/index.rst
  docs/source/llms/tracing/index.rst
  docs/source/llms/tracing/notebooks/jupyter-trace-demo.ipynb
Labels: rn/none

#14140 Implement message and tools standard for OpenAI auto-tracing
  mlflow/openai/_openai_autolog.py
  mlflow/openai/utils/chat_schema.py
  tests/openai/test_openai_autolog.py
Labels: rn/none

#14135 Remove redundant run/experiment logging in Databricks notebooks
  mlflow/tracking/_tracking_service/client.py
Labels: rn/none, v2.19.1

#14141 Fix links to CLI reference
  docs/docs/deployment/deploy-model-locally/index.mdx
  docs/docs/deployment/deploy-model-to-kubernetes/index.mdx
  docs/docs/deployment/deploy-model-to-kubernetes/tutorial/index.mdx
  docs/docs/deployment/deploy-model-to-sagemaker/index.mdx
  docs/docs/deployment/index.mdx
  docs/docs/llms/prompt-engineering/index.mdx
  docs/docs/llms/sentence-transformers/index.mdx
  docs/docs/model/dependencies/index.mdx
  docs/docs/model/models-from-code/index.mdx
  docs/docs/models/index.mdx
  docs/docs/plugins/index.mdx
  docs/docs/projects/index.mdx
  docs/docs/recipes/index.mdx
  docs/docs/tracking/artifacts-stores/index.mdx
  docs/docs/tracking/backend-stores/index.mdx
  docs/docs/tracking/tracking-api/index.mdx
Labels: rn/none

#14109 fix unitialized loaded_model var
  mlflow/pyfunc/__init__.py
Labels: rn/bug-fix, area/scoring, v2.19.1

#14147 fix spacy ci
  mlflow/utils/__init__.py
Labels: rn/none

#14148 fix langchain ci
  tests/langchain/test_langchain_model_export.py
Labels: rn/none, area/build

#14142 Migrate llms/deployments folder
  docs/docs/llms/deployments/guides/index.mdx
  docs/docs/llms/deployments/guides/step1-create-deployments/index.mdx
  docs/docs/llms/deployments/guides/step2-query-deployments/index.mdx
  docs/docs/llms/deployments/uc_integration/index.mdx
  docs/rst_to_migrate/llms/deployments/guides/step1-create-deployments.rst
  docs/rst_to_migrate/llms/deployments/guides/step2-query-deployments.rst
  docs/rst_to_migrate/llms/deployments/uc_integration.rst
Labels: rn/none

#14067 Enable trace tab in runs page
  mlflow/server/js/src/common/utils/FeatureUtils.ts
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/ExperimentViewRunsModeSwitch.tsx
  mlflow/server/js/src/experiment-tracking/components/traces/TraceDataDrawer.tsx
Labels: rn/none, area/uiux, v2.19.1

#14146 Fix constraint name for MSSQL in migration 0584bdc529eb
  mlflow/store/db_migrations/versions/0584bdc529eb_add_cascading_deletion_to_datasets_from_experiments.py
Labels: rn/bug-fix, v2.19.1

#14151 Mark trace API stable
  docs/source/llms/tracing/index.rst
  mlflow/tracing/fluent.py
  mlflow/tracking/client.py
Labels: area/docs, rn/none, v2.19.1

#14091 Dictionary param support
  mlflow/models/utils.py
  mlflow/types/schema.py
  mlflow/types/utils.py
  tests/langchain/test_langchain_model_export.py
  tests/models/test_signature.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
  tests/pyfunc/test_scoring_server.py
  tests/types/test_schema.py
Labels: rn/feature

#14100 [2/2] Type hint support in pyfunc models
  .github/workflows/master.yml
  .github/workflows/r.yml
  mlflow/models/model.py
  mlflow/models/signature.py
  mlflow/models/utils.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
  mlflow/types/type_hints.py
  mlflow/types/utils.py
  tests/models/test_model.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_pyfunc_exceptions.py
  tests/pyfunc/test_pyfunc_model_with_type_hints.py
  tests/types/test_type_hints.py
Labels: rn/feature

#14154 Weekly docusaurus rebase
  .github/workflows/advice.yml
  .github/workflows/closing-pr.yml
  .github/workflows/labeling.js
  .github/workflows/labeling.yml
  .github/workflows/recipe.yml
  dev/clint/src/clint/config.py
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  docs/docs/tracing/index.mdx
  docs/docs/tracing/notebooks/jupyter-trace-demo.ipynb
  docs/static/images/llms/tracing/jupyter-trace-ui.png
  mlflow/data/code_dataset_source.py
  mlflow/openai/_openai_autolog.py
  mlflow/openai/utils/chat_schema.py
  mlflow/pyfunc/__init__.py
  mlflow/server/js/src/common/utils/FeatureUtils.ts
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/ExperimentViewRunsModeSwitch.tsx
  mlflow/server/js/src/experiment-tracking/components/traces/TraceDataDrawer.tsx
  mlflow/tracking/_tracking_service/client.py
  mlflow/utils/__init__.py
  pyproject.skinny.toml
  pyproject.toml
  requirements/skinny-requirements.txt
  requirements/skinny-requirements.yaml
  tests/langchain/test_langchain_model_export.py
  tests/openai/test_openai_autolog.py
Labels: rn/none

#14125 Fix hard-dependency to langchain package in autologging
  mlflow/langchain/__init__.py
  mlflow/langchain/_langchain_autolog.py
  mlflow/langchain/langchain_tracer.py
  mlflow/utils/autologging_utils/__init__.py
  tests/langchain/test_langchain_autolog.py
Labels: rn/bug-fix, area/tracking, enable-dev-tests, v2.19.1

#14152 Implement chat message attribute logic for LangChain
  docs/source/conf.py
  docs/source/llms/tracing/tracing-schema.rst
  mlflow/gateway/schemas/chat.py
  mlflow/gateway/schemas/completions.py
  mlflow/langchain/langchain_tracer.py
  mlflow/langchain/utils/chat.py
  mlflow/tracing/utils/__init__.py
  mlflow/types/chat.py
  tests/langchain/test_chat_utils.py
  tests/langchain/test_langchain_autolog.py
  tests/langchain/test_langchain_model_export.py
  tests/langchain/test_langchain_tracer.py
  tests/tracing/utils/test_utils.py
Labels: rn/none, area/tracking

#14161 Fix sentence-transformer unit test
  tests/sentence_transformers/test_sentence_transformers_model_export.py
Labels: rn/none

#14162 Pin pydantic version for tensorflow 2.12, 2.13
  mlflow/ml-package-versions.yml
Labels: rn/none

#14163 Specify typing_extensions version to fix R test
  .github/workflows/r.yml
Labels: rn/none

#14166 Fix test failures for old transformers
  mlflow/ml-package-versions.yml
Labels: rn/none

#14167 Remove dev testing for prophet
  mlflow/ml-package-versions.yml
Labels: rn/none

#14165 Suppress version incompatibility warnings for more flavors
  mlflow/utils/autologging_utils/__init__.py
Labels: rn/none, area/tracking

#14169 Fix log_metrics performance issue
  mlflow/utils/rest_utils.py
Labels: rn/none

#14156 Support no op type hints
  mlflow/models/signature.py
  mlflow/pyfunc/__init__.py
  mlflow/types/type_hints.py
  tests/pyfunc/test_pyfunc_model_with_type_hints.py
  tests/types/test_type_hints.py
Labels: rn/none

#14006 Groq autotracing
  conftest.py
  docs/source/_static/images/llms/groq/groq-tracing.png
  docs/source/_static/images/logos/groq-tracing.svg
  docs/source/llms/tracing/index.rst
  docs/source/python_api/mlflow.groq.rst
  examples/groq/tracing.py
  mlflow/__init__.py
  mlflow/groq/__init__.py
  mlflow/groq/_groq_autolog.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/tracking/fluent.py
  requirements/extra-ml-requirements.txt
  tests/groq/test_groq_autolog.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/feature

#14159 Add tool span attribute for Langchain tracing
  mlflow/langchain/langchain_tracer.py
  mlflow/tracing/utils/__init__.py
  mlflow/types/chat.py
  tests/langchain/test_langchain_autolog.py
  tests/langchain/test_langchain_tracer.py
Labels: rn/none, area/tracking

#14139 fix rename permission model registry
  mlflow/server/auth/__init__.py
  mlflow/server/auth/sqlalchemy_store.py
  tests/server/auth/test_sqlalchemy_store.py
Labels: rn/bug-fix, area/model-registry, area/sqlalchemy, v2.19.1

#14164 Implement message and tools standard for Anthropic auto-tracing
  mlflow/anthropic/autolog.py
  mlflow/anthropic/chat.py
  mlflow/gateway/providers/anthropic.py
  mlflow/metrics/genai/model_utils.py
  mlflow/ml-package-versions.yml
  mlflow/types/chat.py
  tests/anthropic/test_anthropic_autolog.py
  tests/gateway/providers/test_anthropic.py
Labels: rn/none, area/tracking

#14130 Pyfunc data validation in predict
  mlflow/dspy/wrapper.py
  mlflow/models/signature.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
  mlflow/pyfunc/utils/__init__.py
  mlflow/pyfunc/utils/data_validation.py
  mlflow/utils/annotations.py
  tests/pyfunc/test_pyfunc_model_with_type_hints.py
Labels: rn/feature

#14176 Fix mlflow recipe
  .circleci/config.yml
Labels: rn/none
