Repository mlflow/mlflow, pull requests merged in 2024-08, with the labels that each got.

#12814 Pyfunc get raw model
  mlflow/catboost/__init__.py
  mlflow/diviner/__init__.py
  mlflow/fastai/__init__.py
  mlflow/gluon/__init__.py
  mlflow/h2o/__init__.py
  mlflow/johnsnowlabs/__init__.py
  mlflow/keras/load.py
  mlflow/langchain/__init__.py
  mlflow/lightgbm/__init__.py
  mlflow/onnx/__init__.py
  mlflow/openai/__init__.py
  mlflow/paddle/__init__.py
  mlflow/pmdarima/__init__.py
  mlflow/promptflow/__init__.py
  mlflow/prophet/__init__.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/loaders/chat_model.py
  mlflow/pytorch/__init__.py
  mlflow/sentence_transformers/__init__.py
  mlflow/shap/__init__.py
  mlflow/spacy/__init__.py
  mlflow/spark/__init__.py
  mlflow/statsmodels/__init__.py
  mlflow/tensorflow/__init__.py
  mlflow/transformers/__init__.py
  tests/sklearn/test_sklearn_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/feature

#12845 changes "LangChain Automatic Tracing" to "OpenAI Automatic Tracing" under OpenAI tab in tracing docs
  docs/source/llms/tracing/index.rst
Labels: area/docs, rn/none, patch-2.15.1

#12782 Avoid converting input example
  docs/source/model/signatures.rst
  mlflow/langchain/__init__.py
  mlflow/models/python_api.py
  mlflow/models/utils.py
  mlflow/openai/__init__.py
  mlflow/promptflow/__init__.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/scoring_server/__init__.py
  mlflow/pyfunc/utils/serving_data_parser.py
  mlflow/sentence_transformers/__init__.py
  mlflow/transformers/__init__.py
  mlflow/utils/docstring_utils.py
  mlflow/utils/proto_json_utils.py
  tests/langchain/test_langchain_model_export.py
  tests/models/test_model.py
  tests/models/test_model_input_examples.py
  tests/promptflow/test_promptflow_model_export.py
  tests/pyfunc/docker/test_docker_flavors.py
  tests/pyfunc/test_chat_model.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
  tests/pyfunc/test_rag_model.py
  tests/sentence_transformers/test_sentence_transformers_model_export.py
  tests/spark/test_spark_model_export.py
Labels: rn/feature, area/models

#12844 Remove non-existing command from deployment doc
  docs/source/deployment/deploy-model-locally.rst
Labels: area/docs, rn/none, patch-2.15.1

#12836 Fix `update_mlflow_version.py` to update `pyproject.release.toml` as well.
  dev/update_mlflow_versions.py
  tests/dev/test_update_mlflow_versions.py
Labels: rn/none, area/build

#12843 Avoid creating a Run in OpenAI autologging when only tracing is enabled
  mlflow/langchain/_langchain_autolog.py
  mlflow/openai/_openai_autolog.py
  mlflow/tracing/trace_manager.py
  mlflow/utils/autologging_utils/config.py
  tests/langchain/test_langchain_autolog.py
  tests/openai/test_openai_autolog.py
Labels: rn/bug-fix, area/tracking, patch-2.15.1

#12779 Make `disable_for_unsupported_versions` robust
  dev/update_ml_package_versions.py
  mlflow/langchain/__init__.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/openai/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/autologging_utils/versioning.py
  mlflow/utils/docstring_utils.py
  tests/autologging/test_autologging_utils.py
Labels: rn/none, area/tracking

#12848 Serving input payload doc
  docs/source/model/signatures.rst
  docs/source/models.rst
Labels: rn/documentation

#12847 Fix sklearn autologging x distutils issue
  .github/actions/setup-python/action.yml
  mlflow/utils/environment.py
Labels: rn/none, enable-dev-tests

#12850 Prevent importing `pip`
  examples/flower_classifier/image_pyfunc.py
  pyproject.toml
  tests/utils/test_environment.py
  tests/utils/test_requirements_utils.py
Labels: rn/none

#12831 Wrap async logging batch submit by try except
  mlflow/utils/async_logging/async_logging_queue.py
Labels: rn/bug-fix, area/tracking, patch-2.15.1

#12794 Run llama-index examples in CI
  requirements/extra-ml-requirements.txt
  tests/examples/test_examples.py
Labels: rn/none, area/examples

#12851 Serving example file rename
  docs/source/model/signatures.rst
  docs/source/models.rst
  mlflow/models/utils.py
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactLoggedModelView.enzyme.test.tsx
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactLoggedModelView.tsx
  mlflow/server/js/src/experiment-tracking/constants.ts
  tests/catboost/test_catboost_model_export.py
  tests/diviner/test_diviner_model_export.py
  tests/fastai/test_fastai_model_export.py
  tests/h2o/test_h2o_model_export.py
  tests/helper_functions.py
  tests/langchain/test_langchain_model_export.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/models/test_cli.py
  tests/models/test_wheeled_model.py
  tests/openai/test_openai_model_export.py
  tests/paddle/test_paddle_model_export.py
  tests/pmdarima/test_pmdarima_model_export.py
  tests/promptflow/test_promptflow_model_export.py
  tests/prophet/test_prophet_model_export.py
  tests/pyfunc/docker/test_docker_flavors.py
  tests/pyfunc/test_chat_model.py
  tests/pytorch/test_pytorch_model_export.py
  tests/sentence_transformers/test_sentence_transformers_model_export.py
  tests/sklearn/test_sklearn_model_export.py
  tests/spacy/test_spacy_model_export.py
  tests/statsmodels/test_statsmodels_model_export.py
  tests/tensorflow/test_keras_model_export.py
  tests/tensorflow/test_keras_pyfunc_model_works_with_all_input_types.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none

#12858 Run MLflow dev cross test CI with python 10
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build, enable-dev-tests

#12853 Replace `pkg_resources` with `importlib.metadata`
  mlflow/utils/requirements_utils.py
  pyproject.toml
Labels: rn/bug-fix

#12825 Add label_list in evaluator_config
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/feature

#12863 Fix `disable_for_unsupported_versions` value
  mlflow/utils/autologging_utils/__init__.py
Labels: rn/none, patch-2.15.1

#12862 Fix test name typos
  tests/langchain/test_chat_utils.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/none

#12861 Fix: Regression connecting to MLFlow tracking server on other Databricks workspace
  mlflow/utils/databricks_utils.py
  mlflow/utils/rest_utils.py
Labels: rn/bug-fix, area/tracking

#12873 Fix url with e2 proxy
  mlflow/tracking/_tracking_service/client.py
Labels: rn/bug-fix, area/tracking, patch-2.15.1

#12860 Add note for external vector store limitation
  docs/source/llms/llama-index/index.rst
Labels: area/docs, rn/none, patch-2.15.1

#12869 [BUG] able to refresh model metrics chart manually
  mlflow/server/js/src/experiment-tracking/sdk/SampledMetricHistoryService.ts
Labels: rn/bug-fix, area/uiux, patch-2.15.1

#12864 Prevent test name typos
  .github/workflows/matchers/clint.json
  dev/clint/src/clint/__init__.py
  dev/clint/src/clint/linter.py
Labels: rn/none

#12865 Import `FakeListLLM` and `FakeEmbeddings` from `langchain_community`
  tests/evaluate/test_evaluation.py
  tests/langchain/sample_code/no_config/chain.py
  tests/langchain/test_langchain_tracer.py
  tests/resources/example_mlflow_2.12_langchain_model/lc_model.py
Labels: rn/none

#12880 Fix branch of website-e2e status badge
  README.rst
Labels: rn/none

#12889 Remove a silly debug code
  dev/set_matrix.py
Labels: rn/none, area/build

#12890 Add `**kwargs` to the new span handler in the LlamaIndex Tracer
  mlflow/llama_index/tracer.py
Labels: rn/bug-fix, area/tracking, patch-2.15.1

#12821 Fix deletion of artifacts when downloading from a non-standard DBFS location during UC model registration
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/utils/uri.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/utils/test_uri.py
Labels: rn/bug-fix, autoformat, patch-2.15.1

#12884 Add back `env_manager` attribute for _ServedPyFuncModel
  mlflow/pyfunc/__init__.py
Labels: rn/none, area/models

#12781 Improve gateway schema support for OpenAI provider
  mlflow/gateway/schemas/chat.py
  mlflow/gateway/schemas/completions.py
  mlflow/gateway/schemas/embeddings.py
Labels: rn/bug-fix, area/server-infra, area/deployments, patch-2.15.1

#12893 Remove warning in docstring_version_compatibility_warning
  mlflow/langchain/__init__.py
  mlflow/utils/docstring_utils.py
  tests/utils/test_docstring_utils.py
Labels: rn/none

#12898 Remove version from page titles
  docs/theme/mlflow/layout.html
Labels: rn/none, patch-2.15.2

#12897 Set `ensure_ascii=False` to avoid escaping non-ascii characters when serializing tracing data
  mlflow/entities/span.py
  mlflow/tracing/display/display_handler.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  tests/tracing/test_fluent.py
Labels: rn/none

#12905 Remove the duplicated entry of `SparkDataset` in the document
  docs/source/tracking/data-api.rst
Labels: area/docs, rn/none, patch-2.15.2

#12903 Catch NVML error when collecting GPU metrics
  mlflow/system_metrics/metrics/gpu_monitor.py
Labels: rn/none, rn/bug-fix, area/tracking, patch-2.15.2

#12907 Document OpenAI compatibility in deployments server docs
  docs/source/llms/deployments/index.rst
Labels: rn/none

#12888 Create rest store for UC OSS
  dev/generate_protos.py
  mlflow/data/delta_dataset_source.py
  mlflow/protos/databricks_managed_catalog_service.proto
  mlflow/protos/databricks_managed_catalog_service_pb2.py
  mlflow/protos/unity_catalog_oss_messages.proto
  mlflow/protos/unity_catalog_oss_messages_pb2.py
  mlflow/protos/unity_catalog_oss_service.proto
  mlflow/protos/unity_catalog_oss_service_pb2.py
  mlflow/store/_unity_catalog/registry_oss/__init__.py
  mlflow/store/_unity_catalog/registry_oss/rest_store_oss.py
  mlflow/utils/_unity_catalog_oss_utils.py
  mlflow/utils/rest_utils.py
  tests/store/_unity_catalog/conftest.py
  tests/store/_unity_catalog/oss_registry/test_unity_catalog_oss_rest_store.py
  tests/utils/test_unity_catalog_oss_utils.py
Labels: rn/feature, area/model-registry, autoformat

#12876 [BUG] Fix mlflow.log_metrics value type error
  mlflow/tracking/_tracking_service/client.py
  tests/tracking/_tracking_service/test_tracking_service_client.py
Labels: rn/bug-fix, area/tracking, patch-2.15.2

#12611 Support Gateway plugin LLM provider
  docs/source/llms/deployments/index.rst
  docs/source/python_api/mlflow.gateway.rst
  examples/deployments/deployments_server/plugin/README.md
  examples/deployments/deployments_server/plugin/config.yaml
  examples/deployments/deployments_server/plugin/example.py
  examples/deployments/deployments_server/plugin/my-llm/my_llm/__init__.py
  examples/deployments/deployments_server/plugin/my-llm/my_llm/config.py
  examples/deployments/deployments_server/plugin/my-llm/my_llm/providers.py
  examples/deployments/deployments_server/plugin/my-llm/pyproject.toml
  mlflow/gateway/config.py
  mlflow/gateway/provider_registry.py
  mlflow/gateway/providers/__init__.py
  mlflow/gateway/providers/ai21labs.py
  mlflow/gateway/providers/anthropic.py
  mlflow/gateway/providers/base.py
  mlflow/gateway/providers/bedrock.py
  mlflow/gateway/providers/cohere.py
  mlflow/gateway/providers/huggingface.py
  mlflow/gateway/providers/mistral.py
  mlflow/gateway/providers/mlflow.py
  mlflow/gateway/providers/mosaicml.py
  mlflow/gateway/providers/openai.py
  mlflow/gateway/providers/palm.py
  mlflow/gateway/providers/togetherai.py
Labels: rn/feature, area/deployments

#12923 langchain: load code from code_paths to system path
  mlflow/langchain/__init__.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/bug-fix, area/tracking, patch-2.15.2

#12929 Remove `assert os.path.exists(os.getcwd())` in `TempDir`
  mlflow/utils/file_utils.py
Labels: rn/none

#12914 Fix run URL logging to show full URL
  mlflow/utils/databricks_utils.py
Labels: rn/none

#12919 Remove adhoc mocking in LangChain test and use fake OpenAI service
  mlflow/langchain/__init__.py
  mlflow/ml-package-versions.yml
  mlflow/tracing/utils/__init__.py
  mlflow/utils/openai_utils.py
  tests/langchain/conftest.py
  tests/langchain/test_langchain_autolog.py
  tests/langchain/test_langchain_model_export.py
  tests/langchain/test_langchain_tracer.py
Labels: rn/none, area/build, patch-2.15.2

#12937 Use `free-disk-space` in `devcontainer`
  .github/workflows/devcontainer.yml
Labels: rn/none

#12877 Async support for trace decorator
  mlflow/tracing/fluent.py
  pytest.ini
  tests/tracing/test_fluent.py
Labels: rn/feature, area/tracking

#12932 Only print one warning for missing signature
  mlflow/models/model.py
  mlflow/store/_unity_catalog/registry/rest_store.py
Labels: rn/none

#12885 Tracing performance improvement
  mlflow/__init__.py
  mlflow/tracing/export/mlflow.py
  mlflow/tracing/processor/mlflow.py
  mlflow/tracing/provider.py
  mlflow/tracking/context/registry.py
  mlflow/tracking/fluent.py
  tests/evaluate/test_evaluation.py
  tests/langchain/test_langchain_autolog.py
  tests/tracing/conftest.py
  tests/tracing/export/test_mlflow_exporter.py
  tests/tracing/helper.py
  tests/tracing/test_fluent.py
  tests/tracking/test_client.py
Labels: rn/feature, area/tracking, patch-2.15.2

#12931 Issue a warning when the LangChain model includes a class from partner packages
  mlflow/langchain/runnables.py
  mlflow/ml-package-versions.yml
  tests/langchain/test_langchain_model_export.py
Labels: rn/none, area/tracking

#12938 Fix sftp get connection deadlock
  mlflow/store/artifact/sftp_artifact_repo.py
Labels: rn/bug-fix, area/tracking

#12915 Avoid making multiple backend calls in `start_trace`
  mlflow/tracking/client.py
  tests/tracking/_tracking_service/test_tracking_service_client.py
Labels: rn/none, area/tracking

#12950 Silence autologging supported version warning for LangChain/LlamaIndex/OpenAI
  mlflow/utils/autologging_utils/__init__.py
  tests/autologging/test_autologging_utils.py
Labels: rn/none, area/tracking

#12939 Add note for async trace logging and async function decorating
  docs/source/llms/tracing/index.rst
Labels: area/docs, rn/none

#12951 Avoid using yanked pytest version
  .devcontainer/requirements.txt
  requirements/test-requirements.txt
Labels: rn/none

#12953 Replace `querystring_parser.parse` with `flask.Request.args` in artifact handlers
  mlflow/server/handlers.py
Labels: rn/none

#12913 Initial AutoGen Tracing Implementation
  conftest.py
  mlflow/__init__.py
  mlflow/autogen/__init__.py
  mlflow/autogen/autogen_logger.py
  mlflow/entities/span.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/tracing/provider.py
  mlflow/tracking/client.py
  tests/autogen/test_autogen_autolog.py
Labels: rn/feature, area/tracking

#12899 Update LlamaIndex autologging to wrap main function for unit testing purposes
  mlflow/llama_index/__init__.py
Labels: rn/none, area/models, integrations/databricks, patch-2.15.2

#12960 Remove `querystring_parser`
  mlflow/server/handlers.py
  pyproject.release.toml
  pyproject.toml
  requirements/core-requirements.txt
  requirements/core-requirements.yaml
  tests/server/test_handlers.py
Labels: rn/none

#12936 Add additional documentation for models from code feature
  docs/source/_static/images/models/basic_model_from_code_ui.png
  docs/source/_static/images/models/langchain_model_from_code.png
  docs/source/_static/images/models/model_from_code_code_paths.png
  docs/source/_static/images/models/models_from_code_journey.png
  docs/source/llms/custom-pyfunc-for-llms/index.rst
  docs/source/llms/index.rst
  docs/source/llms/langchain/index.rst
  docs/source/model/models-from-code.rst
  docs/source/models.rst
  docs/source/traditional-ml/creating-custom-pyfunc/index.rst
  docs/source/traditional-ml/serving-multiple-models-with-pyfunc/index.rst
  mlflow/pyfunc/__init__.py
Labels: area/docs, rn/documentation, patch-2.15.2

#12962 Remove `pytz`
  mlflow/utils/time.py
  pyproject.skinny.toml
  pyproject.toml
  requirements/skinny-requirements.txt
  requirements/skinny-requirements.yaml
Labels: rn/none

#12964 Remove `entrypoints`
  mlflow/cli.py
  mlflow/data/dataset_registry.py
  mlflow/data/dataset_source_registry.py
  mlflow/deployments/plugin_manager.py
  mlflow/gateway/provider_registry.py
  mlflow/models/evaluation/evaluator_registry.py
  mlflow/projects/backend/loader.py
  mlflow/server/__init__.py
  mlflow/store/artifact/artifact_repository_registry.py
  mlflow/tracking/context/registry.py
  mlflow/tracking/default_experiment/registry.py
  mlflow/tracking/registry.py
  mlflow/tracking/request_auth/registry.py
  mlflow/tracking/request_header/registry.py
  mlflow/utils/os.py
  mlflow/utils/plugins.py
  pyproject.skinny.toml
  pyproject.toml
  requirements/skinny-requirements.txt
  requirements/skinny-requirements.yaml
  tests/projects/backend/test_loader.py
  tests/store/artifact/test_artifact_repository_registry.py
  tests/tracking/_tracking_service/test_utils.py
  tests/tracking/context/test_registry.py
  tests/tracking/default_experiment/test_registry.py
  tests/tracking/request_auth/test_registry.py
  tests/tracking/request_header/test_registry.py
Labels: rn/none

#12944 Support model-from-code in LlamaIndex flavor
  .devcontainer/requirements.txt
  docs/source/llms/llama-index/index.rst
  mlflow/llama_index/__init__.py
  mlflow/llama_index/pyfunc_wrapper.py
  mlflow/ml-package-versions.yml
  mlflow/models/model.py
  requirements/lint-requirements.txt
  tests/llama_index/sample_code/basic_vector_store.py
  tests/llama_index/sample_code/external_vector_store.py
  tests/llama_index/test_llama_index_model_export.py
  tests/models/test_model.py
Labels: rn/feature, area/tracking

#12975 Add env_manager setter for _ServedPyFuncModel
  mlflow/pyfunc/__init__.py
  tests/evaluate/test_evaluation.py
Labels: rn/none, patch-2.15.2

#12956 Fix enable_async_logging docs
  mlflow/config/__init__.py
Labels: area/docs, rn/none, patch-2.15.2

#12968 map ints to longs in `convert_dataclass_to_schema`
  mlflow/types/schema.py
  tests/models/test_signature.py
  tests/types/test_schema.py
Labels: rn/none, area/models, patch-2.15.2

#12976 Fix evaluate for LlamaIndex flavor
  mlflow/llama_index/pyfunc_wrapper.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/models/utils.py
  mlflow/utils/autologging_utils/__init__.py
  tests/llama_index/test_llama_index_evaluate.py
  tests/llama_index/test_llama_index_tracer.py
Labels: rn/bug-fix, area/models, patch-2.15.2

#12985 Enforce maintainer approval
  .github/workflows/maintainer-approval.yml
  .github/workflows/require-core-maintainer-approval.js
  .github/workflows/warn-on-editing-requirements.yml
Labels: rn/none

#12978 Support saving LlamaIndex engine directly via model-from-code
  mlflow/llama_index/__init__.py
  mlflow/llama_index/pyfunc_wrapper.py
  tests/llama_index/sample_code/basic_chat_engine.py
  tests/llama_index/sample_code/query_engine_with_reranker.py
  tests/llama_index/test_llama_index_evaluate.py
  tests/llama_index/test_llama_index_model_export.py
  tests/llama_index/test_llama_index_pyfunc_wrapper.py
Labels: rn/feature, area/tracking

#12977 Fix device when loading transformers model
  mlflow/environment_variables.py
  mlflow/transformers/__init__.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/bug-fix, patch-2.15.2

#12974 Filter invalid params for xgboost model predict
  mlflow/xgboost/__init__.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none, patch-2.15.2

#12965 Improve error message of _validate_max_results_param
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none, area/tracking, area/sqlalchemy, patch-2.15.2

#12993 Update LlamaIndex example with the modified artifact obj argument
  examples/llama_index/simple_index.py
Labels: rn/none, area/examples, patch-2.15.2

#12592 Adapt hdfs_artifact_repo to new pyarrow HdfsFileSystem interface
  docs/source/tracking/artifacts-stores.rst
  mlflow/store/artifact/hdfs_artifact_repo.py
  tests/store/artifact/test_hdfs_artifact_repo.py
Labels: rn/none, area/artifacts

#12995 Include gabrielfu in core maintainer list
  .github/workflows/require-core-maintainer-approval.js
Labels: rn/none

#12906 Switch print statement to debug log in databricks utils
  mlflow/utils/databricks_utils.py
Labels: rn/none, patch-2.15.2

#12991 Warning on invalid device param
  mlflow/transformers/__init__.py
Labels: rn/none

#12943 Allow colon in mlflow param and metric names
  mlflow/utils/validation.py
  tests/tracking/test_tracking.py
  tests/utils/test_validation.py
Labels: rn/none, area/sqlalchemy, integrations/sagemaker, area/server-infra, patch-2.15.2

#13001 Support Langgraph agents in Auto Auth
  mlflow/langchain/databricks_dependencies.py
  mlflow/ml-package-versions.yml
  tests/langchain/test_langchain_databricks_dependency_extraction.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/feature

#13013 Support Registring Functions as Dependencies
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/none

#13019 Change uc_function to function
  mlflow/langchain/databricks_dependencies.py
  mlflow/models/resources.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/langchain/test_langchain_databricks_dependency_extraction.py
  tests/langchain/test_langchain_model_export.py
  tests/models/test_resources.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/none

#12987 Fix data conversion for serving in langchain
  mlflow/models/utils.py
  tests/models/test_utils.py
Labels: rn/none, patch-2.15.2

#12996 Support saving LangGraph object via model-from-code
  mlflow/langchain/api_request_parallel_processor.py
  mlflow/langchain/runnables.py
  mlflow/langchain/utils/__init__.py
  mlflow/langchain/utils/serialization.py
  mlflow/ml-package-versions.yml
  mlflow/models/utils.py
  tests/langchain/sample_code/langgraph.py
  tests/langchain/sample_code/openai_agent.py
  tests/langchain/test_langchain_model_export.py
  tests/langchain/test_langgraph.py
Labels: rn/feature, area/models

#12983 Add `mlflow.models.Model.get_tags_dict` to generate `model-history` tag
  mlflow/models/model.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_rest_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/test_rest_tracking.py
Labels: rn/bug-fix, area/tracking, patch-2.15.2

#13025 Add docs updates for LangGraph support
  docs/source/_static/images/logos/autogen-logo.svg
  docs/source/_static/images/logos/langgraph-logo.png
  docs/source/llms/langchain/index.rst
  docs/source/new-features/index.rst
Labels: area/docs, rn/documentation

#13038 Fix transformers test
  tests/transformers/test_transformers_model_export.py
Labels: rn/none

#13005 [BUG] add support for file removal for local artifact repo
  mlflow/store/artifact/local_artifact_repo.py
  tests/store/artifact/test_local_artifact_repo.py
Labels: rn/bug-fix, area/artifacts, patch-2.15.2
