Repository mlflow/mlflow, pull requests merged in 2024-02, with the labels that each got.

#10972 Fix indentation
  docs/source/llms/deployments/guides/step1-create-deployments.rst
Labels: area/docs, rn/none

#10831 Google docstring conversion batch 4
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/_model_registry/registry.py
  mlflow/tracking/_model_registry/utils.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/_tracking_service/registry.py
  mlflow/tracking/_tracking_service/utils.py
  mlflow/tracking/artifact_utils.py
  mlflow/tracking/client.py
  mlflow/tracking/context/abstract_context.py
  mlflow/tracking/context/registry.py
  mlflow/tracking/default_experiment/abstract_context.py
  mlflow/tracking/default_experiment/registry.py
  mlflow/tracking/fluent.py
  mlflow/tracking/registry.py
  mlflow/tracking/request_auth/abstract_request_auth_provider.py
  mlflow/tracking/request_auth/registry.py
  mlflow/tracking/request_header/abstract_request_header_provider.py
  mlflow/tracking/request_header/registry.py
Labels: area/docs, rn/none

#10931 Merge GraphQL feature branch into master
  dev/proto_to_graphql/README.md
  dev/proto_to_graphql/autogeneration_utils.py
  dev/proto_to_graphql/code_generator.py
  dev/proto_to_graphql/parsing_utils.py
  dev/proto_to_graphql/schema_autogeneration.py
  dev/proto_to_graphql/string_utils.py
  mlflow/java/client/src/main/java/com/databricks/api/proto/databricks/Databricks.java
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/databricks.proto
  mlflow/protos/databricks_pb2.py
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
  mlflow/server/graphql/__init__.py
  mlflow/server/graphql/autogenerated_graphql_schema.py
  mlflow/server/graphql/graphql_custom_scalars.py
  mlflow/server/graphql/graphql_schema_extensions.py
  mlflow/server/handlers.py
  requirements/core-requirements.txt
  requirements/core-requirements.yaml
  requirements/skinny-requirements.txt
  requirements/skinny-requirements.yaml
  requirements/test-requirements.txt
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#10958 Allow completions (`prompt`), embeddings (`input`) format inputs to scoring server
  mlflow/models/python_api.py
  mlflow/pyfunc/scoring_server/__init__.py
  tests/pyfunc/test_scoring_server.py
Labels: rn/feature, area/scoring

#10830 Add keras flavor for Keras 3 support
  docs/source/conf.py
  docs/source/deep-learning/keras/index.rst
  docs/source/deep-learning/keras/quickstart/quickstart_keras.ipynb
  docs/source/python_api/mlflow.keras.rst
  mlflow/__init__.py
  mlflow/keras/__init__.py
  mlflow/keras/autolog.py
  mlflow/keras/callback.py
  mlflow/keras/load.py
  mlflow/keras/save.py
  mlflow/keras/utils.py
  mlflow/keras_core/__init__.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  requirements/doc-requirements.txt
  requirements/extra-ml-requirements.txt
  tests/keras/test_autolog.py
  tests/keras/test_callback.py
  tests/keras/test_save.py
  tests/keras_core/test_callback.py
  tests/test_flavors.py
Labels: rn/feature, area/tracking

#10982 Fix typo in deployment docs
  docs/source/deployment/deploy-model-to-kubernetes/tutorial.rst
Labels: area/docs, rn/none

#10986 Remove graphene in skinny requirements
  requirements/skinny-requirements.txt
  requirements/skinny-requirements.yaml
Labels: rn/none

#10985 Delay import of graphQL module
  mlflow/server/handlers.py
Labels: rn/none, area/build

#10820 Implement ChatModel (pyfunc subclass)
  docs/source/python_api/mlflow.pyfunc.rst
  docs/source/python_api/mlflow.types.rst
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/loaders/__init__.py
  mlflow/pyfunc/loaders/chat_model.py
  mlflow/pyfunc/model.py
  mlflow/types/__init__.py
  mlflow/types/llm.py
  tests/pyfunc/test_chat_model.py
  tests/pyfunc/test_chat_model_validation.py
Labels: rn/feature, area/models

#10796 Add source table data into lineage header
  mlflow/data/delta_dataset_source.py
  mlflow/protos/databricks_managed_catalog_messages.proto
  mlflow/protos/databricks_managed_catalog_messages_pb2.py
  mlflow/protos/databricks_managed_catalog_service.proto
  mlflow/protos/databricks_managed_catalog_service_pb2.py
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/artifact/unity_catalog_models_artifact_repo.py
  mlflow/tracking/_model_registry/utils.py
  mlflow/utils/_unity_catalog_utils.py
  tests/data/test_delta_dataset_source.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/store/artifact/test_unity_catalog_models_artifact_repo.py
  tests/utils/test_unity_catalog_utils.py
Labels: rn/none, area/model-registry

#10992 Restore dataset tracking flag
  mlflow/server/js/src/common/utils/FeatureUtils.ts
Labels: rn/bug-fix, area/uiux

#10967 Fix directory bucket region name retrieval
  mlflow/store/artifact/optimized_s3_artifact_repo.py
  tests/store/artifact/test_optimized_s3_artifact_repo.py
Labels: rn/none, area/model-registry

#11007 Exclude `fastapi==0.109.2` from deployment dependencies
  requirements/gateway-requirements.txt
  requirements/gateway-requirements.yaml
Labels: rn/none, area/build

#10991 Add indications of DL UI capabilities to the DL landing page
  docs/source/_static/images/deep-learning/dl-box-plot.gif
  docs/source/_static/images/deep-learning/dl-run-comparison.gif
  docs/source/_static/images/deep-learning/dl-run-navigation.gif
  docs/source/_static/images/deep-learning/dl-run-selection.gif
  docs/source/_static/images/deep-learning/dl-tracking.gif
  docs/source/deep-learning/index.rst
Labels: area/docs, rn/documentation

#11017 Fix incorrect logo on LLMs landing page
  docs/source/llms/index.rst
Labels: area/docs, rn/bug-fix

#10983 Enrich documentations for docker deployment
  docs/source/deployment/deploy-model-to-kubernetes/index.rst
  docs/source/deployment/index.rst
  mlflow/models/cli.py
  mlflow/models/python_api.py
Labels: area/docs, rn/none

#11011 Pin slowapi instead
  requirements/gateway-requirements.txt
  requirements/gateway-requirements.yaml
Labels: rn/none, area/build

#10989 FIx llm example tiktoken dependency error
  examples/llms/summarization/python_env.yaml
Labels: rn/none, area/examples

#11005 Update rag notebook
  docs/source/llms/rag/notebooks/mlflow-e2e-evaluation.ipynb
Labels: rn/none

#11014 Fix non-idempotent prediction due to in-place update to model-config
  mlflow/transformers/__init__.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/bug-fix, area/models

#10979 Fix missing dtype issue for transformer pipeline
  mlflow/transformers/__init__.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/bug-fix, area/models

#10879 Google docstring conversion batch 6
  mlflow/sagemaker/__init__.py
  mlflow/sentence_transformers/__init__.py
  mlflow/shap/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/sklearn/utils.py
  mlflow/spark/__init__.py
  mlflow/statsmodels/__init__.py
Labels: area/docs, rn/none

#11018 Error handling: only catch module import error caused by feature store module
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/none

#11023 Use mlflow-autmation instead of mlflow-team for team review
  .github/workflows/team-review.yml
Labels: rn/none

#10952 Fix inputs & outputs log for langchain autologging
  mlflow/langchain/__init__.py
  mlflow/langchain/_langchain_autolog.py
  mlflow/ml-package-versions.yml
  mlflow/tracking/fluent.py
  tests/langchain/test_langchain_autolog.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/none

#11030 Replace `requested_team` with `requested_reviewer`
  .github/workflows/team-review.yml
Labels: rn/none

#11031 Replace `name` with `login`
  .github/workflows/team-review.yml
Labels: rn/none

#11029 Replace SVG image to PNG to avoid false credential alarm
  docs/source/_static/images/tutorials/introductory/logging-first-model/training-annotation.png
  docs/source/_static/images/tutorials/introductory/logging-first-model/training-annotation.svg
  docs/source/getting-started/logging-first-model/step6-logging-a-run.rst
Labels: area/docs, rn/none

#11008 Support list_artifacts
  mlflow/artifacts/__init__.py
  tests/artifacts/test_artifacts.py
Labels: rn/none

#11001 Fix cross-version-tests for Keras and Tensorflow
  dev/get_minimum_required_python.py
  docs/source/conf.py
  docs/source/python_api/mlflow.keras.rst
  mlflow/keras/__init__.py
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build, enable-dev-tests

#11006 Add _unity_catalog back to mlflow.store namespace
  mlflow/store/__init__.py
  mlflow/store/_unity_catalog/__init__.py
  mlflow/store/_unity_catalog/registry/__init__.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/store/artifact/test_unity_catalog_models_artifact_repo.py
Labels: rn/none, area/build

#11015 Fix the compatibility matrix for OpenAI in MLflow Deployments Server docs
  docs/source/llms/deployments/index.rst
  examples/deployments/deployments_server/openai/config.yaml
Labels: area/docs, rn/documentation, area/examples

#11039 Improve the auth validation for `mlflow.login()`
  mlflow/utils/credentials.py
  tests/utils/test_credentials.py
Labels: rn/bug-fix

#10981 Delete leading underscore for `mlflow/spark/_autolog.py`
  mlflow/spark/__init__.py
  mlflow/spark/autologging.py
  tests/spark/autologging/conftest.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging_unit.py
  tests/spark/autologging/utils.py
Labels: rn/none

#11043 Add more package version badges
  README.rst
Labels: rn/none

#11044 Upgrade ruff to 0.2.1
  dev/ruff.py
  mlflow/utils/import_hooks/__init__.py
  pyproject.toml
  requirements/lint-requirements.txt
Labels: rn/none

#11045 Simplify `dev/ruff.py`
  dev/ruff.py
Labels: rn/none

#11048 Fix log table when containing dates
  mlflow/tracking/client.py
  tests/tracking/test_tracking.py
Labels: rn/none

#10812 Support derived metrics
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/feature, area/tracking

#11055 Upgrade GitPython requirement
  requirements/skinny-requirements.txt
  requirements/skinny-requirements.yaml
Labels: rn/none

#11010 Remove databricks cli dependency and inline used databricks cli module code
  mlflow/legacy_databricks_cli/__init__.py
  mlflow/legacy_databricks_cli/configure/__init__.py
  mlflow/legacy_databricks_cli/configure/provider.py
  mlflow/utils/databricks_utils.py
  requirements/skinny-requirements.txt
  requirements/skinny-requirements.yaml
  requirements/test-requirements.txt
  tests/projects/test_databricks.py
  tests/projects/test_docker_projects.py
  tests/projects/test_projects.py
  tests/store/_unity_catalog/conftest.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/store/artifact/test_unity_catalog_models_artifact_repo.py
  tests/utils/test_databricks_utils.py
Labels: rn/none

#11056 Add anthropic_version header for AnthropicProvider
  mlflow/gateway/config.py
  mlflow/gateway/providers/anthropic.py
Labels: rn/none

#10951 List changed pages in docs preview
  .circleci/config.yml
  dev/preview_docs.py
  docs/changed_pages.py
  docs/theme/mlflow/layout.html
Labels: rn/none

#11060 Fix dbutils error in universe driver local suite
  mlflow/utils/databricks_utils.py
Labels: rn/bug-fix

#11037 Add timeout for signature/requirement inference during Transformer model logging.
  mlflow/environment_variables.py
  mlflow/transformers/__init__.py
  mlflow/transformers/signature.py
  mlflow/utils/_capture_transformers_modules.py
  mlflow/utils/environment.py
  mlflow/utils/requirements_utils.py
  mlflow/utils/timeout.py
  tests/conftest.py
  tests/pyfunc/docker/test_docker_flavors.py
  tests/transformers/test_transformers_model_export.py
  tests/transformers/test_transformers_signature.py
Labels: rn/bug-fix, area/models

#11042 Google docstring conversion batch 8
  mlflow/keras/autolog.py
  mlflow/keras/load.py
  mlflow/keras/save.py
  mlflow/langchain/__init__.py
  mlflow/metrics/genai/genai_metric.py
  mlflow/metrics/genai/metric_definitions.py
  mlflow/models/container/__init__.py
  mlflow/models/evaluation/artifacts.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/models/evaluation/validation.py
  mlflow/models/flavor_backend.py
  mlflow/models/model.py
  mlflow/models/signature.py
  mlflow/models/utils.py
  mlflow/models/wheeled_model.py
  mlflow/projects/__init__.py
  mlflow/projects/backend/abstract_backend.py
  mlflow/projects/backend/local.py
  mlflow/projects/databricks.py
  mlflow/projects/docker.py
  mlflow/projects/utils.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/backend.py
  mlflow/pyfunc/model.py
  mlflow/pyfunc/scoring_server/__init__.py
  mlflow/pyfunc/scoring_server/client.py
  mlflow/pytorch/__init__.py
  mlflow/server/__init__.py
  mlflow/server/auth/__init__.py
  mlflow/server/auth/client.py
  mlflow/server/handlers.py
  mlflow/server/validation.py
  mlflow/sklearn/utils.py
  mlflow/utils/_unity_catalog_utils.py
  mlflow/utils/docstring_utils.py
  mlflow/xgboost/__init__.py
Labels: area/docs, rn/none

#10969 Extract databricks info from langchain flavor
  mlflow/langchain/__init__.py
  mlflow/langchain/databricks_dependencies.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/none, area/models, integrations/databricks

#11034 Support OpenAI python SDK v1
  docs/source/llms/openai/notebooks/openai-embeddings-generation.ipynb
  examples/evaluation/evaluate_with_custom_code_metrics.py
  examples/evaluation/evaluate_with_llm_judge.py
  examples/evaluation/evaluate_with_qa_metrics.py
  examples/llms/question_answering/question_answering.py
  examples/openai/azure_openai.py
  examples/openai/chat_completions.py
  examples/openai/completions.py
  examples/openai/embeddings.py
  examples/openai/spark_udf.py
  mlflow/ml-package-versions.yml
  mlflow/openai/__init__.py
  tests/openai/mock_openai.py
  tests/openai/test_openai_model_export.py
Labels: rn/none

#11059 Support converting pandas Dataframe containing dicts into EvaluationDataset
  mlflow/models/evaluation/base.py
  tests/data/test_pandas_dataset.py
Labels: rn/none

#11065 Cherry pick commits of removing legacy databricks-cli dependency
  mlflow/legacy_databricks_cli/__init__.py
  mlflow/legacy_databricks_cli/configure/__init__.py
  mlflow/legacy_databricks_cli/configure/provider.py
  mlflow/utils/databricks_utils.py
  requirements/skinny-requirements.txt
  requirements/skinny-requirements.yaml
  requirements/test-requirements.txt
  tests/projects/test_databricks.py
  tests/projects/test_docker_projects.py
  tests/projects/test_projects.py
  tests/store/_unity_catalog/conftest.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/store/artifact/test_unity_catalog_models_artifact_repo.py
  tests/utils/test_databricks_utils.py
Labels: rn/none

#10976 Implement chat & chat streaming for Cohere
  docs/source/llms/deployments/index.rst
  mlflow/gateway/providers/base.py
  mlflow/gateway/providers/cohere.py
  mlflow/gateway/schemas/chat.py
  tests/gateway/providers/test_cohere.py
Labels: rn/feature, area/deployments

#11054 Add support for ML models in UC in Azure China/Govcloud regions
  mlflow/store/artifact/azure_data_lake_artifact_repo.py
  tests/store/artifact/test_azure_data_lake_artifact_repo.py
Labels: rn/none

#11069 Format code examples in docsring using ruff
  .pre-commit-config.yaml
  mlflow/pyfunc/__init__.py
  mlflow/tensorflow/_autolog.py
  mlflow/tracking/client.py
  mlflow/utils/__init__.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/requirements_utils.py
  mlflow/utils/uri.py
  pyproject.toml
Labels: rn/none

#11073 Upgrade upload-artifact to v4 to silence node 16 deprecation warning
  .github/workflows/autoformat.yml
  .github/workflows/test-package-build.yml
Labels: rn/none

#11072 Autoformat files in `tests/protos`
  .github/workflows/autoformat.yml
Labels: rn/none

#11070 Bump python versions used in CI to latest
  .github/actions/setup-pyenv/action.yml
  .github/actions/setup-python/action.yml
  examples/virtualenv/project/entrypoint.py
  tests/resources/example_virtualenv_conda_project/entrypoint.py
  tests/resources/example_virtualenv_no_python_env/entrypoint.py
  tests/resources/example_virtualenv_project/entrypoint.py
Labels: rn/none

#11076 Update actions/download-artifact to v4
  .github/workflows/autoformat.yml
Labels: rn/none

#11071 Turn `PytestCollectionWarning` into error
  pytest.ini
  tests/data/test_dataset.py
  tests/data/test_dataset_registry.py
  tests/data/test_dataset_source.py
  tests/data/test_dataset_source_registry.py
  tests/data/test_numpy_dataset.py
  tests/data/test_pandas_dataset.py
  tests/data/test_tensorflow_dataset.py
  tests/protos/test_message.proto
  tests/protos/test_message_pb2.py
  tests/resources/data/dataset.py
  tests/resources/data/dataset_source.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/utils/test_logging_utils.py
  tests/utils/test_proto_json_utils.py
Labels: rn/none

#11063 Small fixes to Keras autologging
  mlflow/keras/__init__.py
  mlflow/keras/autologging.py
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/none

#11021 Add node id to system metrics to support logging system metrics in multi-node setup
  mlflow/__init__.py
  mlflow/environment_variables.py
  mlflow/system_metrics/__init__.py
  mlflow/system_metrics/system_metrics_monitor.py
  tests/system_metrics/test_system_metrics_logging.py
Labels: rn/feature

#11088 Update linter rule comments
  pyproject.toml
Labels: rn/none

#11092 Include all tests in Transformers cross version tests
  mlflow/ml-package-versions.yml
  tests/transformers/test_transformers_signature.py
Labels: rn/none, area/build

#11095 Use `tempfile` in `mlflow.log_artifact` example
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: rn/none

#11079 Fix duplicate `pytest_configure`
  conftest.py
  pytest.ini
Labels: rn/none

#11097 Remove `skipcacheclean` pytest marker
  conftest.py
  tests/transformers/test_transformers_model_export.py
  tests/transformers/test_transformers_signature.py
Labels: rn/none

#11027 Support input and signature for text-generation models for Chat and Completions
  mlflow/transformers/__init__.py
  mlflow/transformers/llm_inference_utils.py
  mlflow/types/llm.py
  tests/transformers/test_transformers_llm_inference_utils.py
  tests/transformers/test_transformers_model_export.py
  tests/transformers/test_transformers_prompt_templating.py
Labels: rn/feature, area/models

#11078 Enforce google style docstring
  pylint_plugins/__init__.py
  pylint_plugins/errors.py
  pylint_plugins/no_rst.py
  pylintrc
Labels: rn/none

#10956 Add a guide and tutorial for mlflow data and log_input
  docs/source/_static/images/tracking/dataset-evaluate.png
  docs/source/_static/images/tracking/dataset-mlflow-ui.png
  docs/source/tracking.rst
  docs/source/tracking/data-api.rst
Labels: area/docs, rn/documentation

#11099 Remove extra validation for model types when constructing Transformers pipeline
  mlflow/transformers/__init__.py
  mlflow/transformers/llm_inference_utils.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/none, area/models

#11075 Enable Transformers weight-less model saving
  mlflow/transformers/__init__.py
  mlflow/transformers/flavor_config.py
  mlflow/transformers/hub_utils.py
  mlflow/transformers/model_io.py
  mlflow/transformers/torch_utils.py
  mlflow/utils/docstring_utils.py
  tests/transformers/test_flavor_configs.py
  tests/transformers/test_transformers_model_export.py
  tests/transformers/test_transformers_prompt_templating.py
Labels: rn/feature, area/models, area/tracking

#11115 Remove global torch import in llm_inference_utils.py
  mlflow/transformers/llm_inference_utils.py
Labels: rn/none, area/build

#11110 Update all non ./mlflow docs
  dev/set-mlflow-spark-scala-version.py
  examples/diviner/train.py
  examples/flower_classifier/image_pyfunc.py
  examples/flower_classifier/score_images_rest.py
  examples/flower_classifier/train.py
  examples/hyperparam/search_hyperopt.py
  examples/pytorch/AxHyperOptimizationPTL/ax_hpo_iris.py
  examples/pytorch/BertNewsClassification/bert_classification.py
  examples/pytorch/IterativePruning/mnist.py
  examples/pytorch/MNIST/mnist_autolog_example.py
  examples/rapids/mlflow_project/src/rf_test/train.py
  examples/rapids/mlflow_project/src/rf_test/train_simple.py
  mlflow/legacy_databricks_cli/configure/provider.py
  mlflow/mleap/__init__.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/utils/docstring_utils.py
  tests/conftest.py
  tests/evaluate/test_validation.py
  tests/helper_functions.py
  tests/projects/test_project_spec.py
  tests/resources/data/dataset.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/dummy_dataset.py
  tests/sagemaker/mock/__init__.py
  tests/store/artifact/test_cli.py
  tests/tracking/fluent/test_fluent.py
  tests/transformers/helper.py
Labels: area/docs, rn/none

#10752 fix: importlib.metadata get
  mlflow/cli.py
  mlflow/server/__init__.py
  mlflow/utils/os.py
Labels: rn/bug-fix, area/server-infra

#11098 Remove botocore pin
  setup.py
Labels: rn/none

#11121 Lint and format notebooks in `docs`
  docs/source/conf.py
  docs/source/deep-learning/keras/quickstart/quickstart_keras.ipynb
  docs/source/deep-learning/pytorch/quickstart/pytorch_quickstart.ipynb
  docs/source/deep-learning/tensorflow/quickstart/quickstart_tensorflow.ipynb
  docs/source/getting-started/intro-quickstart/notebooks/tracking_quickstart.ipynb
  docs/source/getting-started/logging-first-model/notebooks/logging-first-model.ipynb
  docs/source/languagesections/__init__.py
  docs/source/llms/custom-pyfunc-for-llms/notebooks/custom-pyfunc-advanced-llm.ipynb
  docs/source/llms/langchain/notebooks/langchain-retriever.ipynb
  docs/source/llms/llm-evaluate/notebooks/rag-evaluation-llama2.ipynb
  docs/source/llms/llm-evaluate/notebooks/rag-evaluation.ipynb
  docs/source/llms/openai/notebooks/openai-chat-completions.ipynb
  docs/source/llms/openai/notebooks/openai-code-helper.ipynb
  docs/source/llms/openai/notebooks/openai-embeddings-generation.ipynb
  docs/source/llms/openai/notebooks/openai-quickstart.ipynb
  docs/source/llms/rag/notebooks/mlflow-e2e-evaluation.ipynb
  docs/source/llms/sentence-transformers/tutorials/paraphrase-mining/paraphrase-mining-sentence-transformers.ipynb
  docs/source/llms/sentence-transformers/tutorials/quickstart/sentence-transformers-quickstart.ipynb
  docs/source/llms/sentence-transformers/tutorials/semantic-search/semantic-search-sentence-transformers.ipynb
  docs/source/llms/sentence-transformers/tutorials/semantic-similarity/semantic-similarity-sentence-transformers.ipynb
  docs/source/llms/transformers/tutorials/audio-transcription/whisper.ipynb
  docs/source/llms/transformers/tutorials/conversational/conversational-model.ipynb
  docs/source/llms/transformers/tutorials/fine-tuning/transformers-fine-tuning.ipynb
  docs/source/model/notebooks/signature_examples.ipynb
  docs/source/testcode_block.py
  docs/source/traditional-ml/creating-custom-pyfunc/notebooks/basic-pyfunc.ipynb
  docs/source/traditional-ml/creating-custom-pyfunc/notebooks/override-predict.ipynb
  docs/source/traditional-ml/hyperparameter-tuning-with-child-runs/notebooks/hyperparameter-tuning-with-child-runs.ipynb
  docs/source/traditional-ml/hyperparameter-tuning-with-child-runs/notebooks/logging-plots-in-mlflow.ipynb
  docs/source/traditional-ml/hyperparameter-tuning-with-child-runs/notebooks/parent-child-runs.ipynb
  docs/source/traditional-ml/serving-multiple-models-with-pyfunc/notebooks/MME_Tutorial.ipynb
  pyproject.toml
Labels: rn/none

#10935 Automatic model checkpointing for pytorch-lightning training
  docs/source/conf.py
  mlflow/pyfunc/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_lightning_autolog.py
  mlflow/utils/mlflow_tags.py
  tests/pytorch/test_pytorch_autolog.py
Labels: rn/feature, area/tracking

#11118 Add warning when requirements files are edited
  .github/workflows/require-core-maintainer-approval.js
  .github/workflows/warn-on-editing-requirements.yml
Labels: rn/none, area/build

#11061 Add CLI tool for updating requirements
  mlflow/models/cli.py
  mlflow/models/model.py
  mlflow/utils/environment.py
  tests/models/test_cli.py
Labels: rn/feature, area/models

#11117 Use `iloc` when computing faithfulness metric
  mlflow/metrics/genai/genai_metric.py
  tests/metrics/genai/test_genai_metrics.py
Labels: rn/none

#11134 Update index.rst
  docs/source/deployment/index.rst
Labels: rn/documentation

#11124 Remove `min_python_version` command in `setup.py`
  .github/actions/setup-python/action.yml
  MANIFEST.in
  requirements/python-version.txt
  setup.py
Labels: rn/none

#11131 Drop prophet 1.0.1 support
  mlflow/ml-package-versions.yml
Labels: rn/none

#11123 Update openai objects to v1
  docs/source/llms/llm-evaluate/index.rst
  docs/source/llms/llm-evaluate/notebooks/question-answering-evaluation.ipynb
  docs/source/llms/openai/notebooks/openai-chat-completions.ipynb
  docs/source/llms/openai/notebooks/openai-code-helper.ipynb
  docs/source/llms/openai/notebooks/openai-quickstart.ipynb
  docs/source/llms/rag/notebooks/question-generation-retrieval-evaluation.ipynb
  docs/source/models.rst
  docs/source/python_api/openai/messages.rst
  examples/evaluation/qa-evaluation.ipynb
  examples/llms/RAG/question-generation-retrieval-evaluation.ipynb
Labels: rn/none

#11125 Add workflow that requires core maintainer approval when editing requirements paths
  .github/workflows/require-core-maintainer-approval.js
  .github/workflows/warn-on-editing-requirements.yml
Labels: rn/none, area/build

#11119 Use `python -m build` to build distributions
  .github/workflows/test-package-build.yml
Labels: rn/none

#11141 Explicitly specify `build-system` in `pyproject.toml`
  pyproject.toml
Labels: rn/none

#11143 Remove `python setup.py dependencies` command
  .github/workflows/master.yml
  setup.py
  tests/db/README.md
  tests/db/update_schemas.sh
Labels: rn/none

#11144 Add PR trigger for warn-on-editing-requirements workflow
  .github/workflows/warn-on-editing-requirements.yml
Labels: rn/none, area/build

#11120 Support PEFT models in Transformers flavor
  mlflow/ml-package-versions.yml
  mlflow/transformers/__init__.py
  mlflow/transformers/flavor_config.py
  mlflow/transformers/model_io.py
  mlflow/transformers/peft.py
  mlflow/utils/docstring_utils.py
  tests/transformers/conftest.py
  tests/transformers/helper.py
  tests/transformers/test_transformers_model_export.py
  tests/transformers/test_transformers_peft_model.py
Labels: rn/feature, area/models

#11146 Remove langchain CI test workaround
  .github/workflows/cross-version-tests.yml
Labels: rn/none, area/build

#11145 Add pull_request_target trigger to maintainer approval workflow
  .github/workflows/warn-on-editing-requirements.yml
Labels: rn/none, area/build

#10939 ML-37213 Add Pyspark Dataframe support to mlflow.pyfunc.predict
  docs/source/model/signatures.rst
  mlflow/models/utils.py
  mlflow/pyfunc/__init__.py
  requirements/test-requirements.txt
  tests/check_mlflow_lazily_imports_ml_packages.py
  tests/pyfunc/test_pyfunc_schema_enforcement_pyspark.py
Labels: rn/feature, area/models

#11000 Onboard getExperiment to GraphQL
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
  mlflow/server/graphql/autogenerated_graphql_schema.py
  mlflow/server/handlers.py
  pylintrc
  pyproject.toml
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#11158 Ignore `no-rst` for `mlflow/models/utils.py`
  pylint_plugins/no_rst.py
Labels: rn/none

#11153 Randomize temporary database file name
  tests/conftest.py
Labels: rn/none

#11160 Fix docstring decorators
  examples/jwt_auth/__init__.py
  mlflow/entities/model_registry/model_version.py
  mlflow/entities/model_registry/registered_model.py
  mlflow/mleap/__init__.py
  mlflow/tracking/metric_value_conversion_utils.py
  mlflow/utils/annotations.py
  pyproject.toml
  tests/utils/test_annotations.py
Labels: area/docs, rn/none

#11165 Remove global transformers import to fix autologging issue in MLR
  mlflow/transformers/__init__.py
  mlflow/transformers/llm_inference_utils.py
  mlflow/transformers/signature.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/none, area/models

#11149 Update hardcoded "io.delta:delta-spark_2.12:3.0.0" dependency to correct scala version
  mlflow/utils/_spark_utils.py
Labels: rn/bug-fix

#11167 Lint `setup.py`
  pyproject.toml
  setup.py
  tests/resources/mlflow-test-plugin/setup.py
Labels: rn/none

#11168 Remove `mlflow/temporary_db_migrations_for_pre_1_users` in `pyproject.toml`
  pyproject.toml
Labels: rn/none

#11151 Replace pylint `useless-assign` with ruff `RET504`
  docs/source/deep-learning/keras/quickstart/quickstart_keras.ipynb
  docs/source/llms/rag/notebooks/mlflow-e2e-evaluation.ipynb
  docs/source/llms/rag/notebooks/question-generation-retrieval-evaluation.ipynb
  docs/source/llms/rag/notebooks/retriever-evaluation-tutorial.ipynb
  docs/source/llms/transformers/tutorials/audio-transcription/whisper.ipynb
  docs/theme/mlflow/__init__.py
  examples/diviner/train.py
  examples/llms/RAG/question-generation-retrieval-evaluation.ipynb
  examples/llms/RAG/retriever-evaluation-tutorial.ipynb
  examples/pytorch/AxHyperOptimizationPTL/ax_hpo_iris.py
  examples/pytorch/AxHyperOptimizationPTL/iris_data_module.py
  examples/pytorch/CaptumExample/Titanic_Captum_Interpret.py
  examples/pytorch/IterativePruning/iterative_prune_mnist.py
  examples/pytorch/torchscript/MNIST/mnist_torchscript.py
  mlflow/fastai/__init__.py
  mlflow/gluon/__init__.py
  mlflow/pmdarima/__init__.py
  pylint_plugins/__init__.py
  pylint_plugins/assign_checker.py
  pylintrc
  pyproject.toml
  tests/evaluate/test_evaluation.py
  tests/gateway/tools.py
Labels: rn/none

#11022 Model Registry Quickstart
  docs/source/_static/images/quickstart/model-registry-quickstart/model-alias-and-tags.png
  docs/source/_static/images/quickstart/model-registry-quickstart/model-registry-ui.png
  docs/source/getting-started/index.rst
  docs/source/getting-started/registering-first-model/index.rst
  docs/source/getting-started/registering-first-model/step1-register-model.rst
  docs/source/getting-started/registering-first-model/step2-explore-registered-model.rst
  docs/source/getting-started/registering-first-model/step3-load-model.rst
Labels: area/docs, rn/none

#11156 [Bug fix] Fixing Mlflow evalaute bug for col_mapping for non llm/custom metrics
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/bug-fix, area/tracking

#10916 Add documentation for derived metrics
  docs/source/llms/llm-evaluate/index.rst
  docs/source/models.rst
  mlflow/metrics/genai/genai_metric.py
  mlflow/models/evaluation/base.py
  mlflow/pyfunc/__init__.py
Labels: rn/none

#11162 Rename AWS Bedrock to Amazon Bedrock
  docs/source/llms/deployments/index.rst
  docs/source/llms/gateway/index.rst
  docs/source/new-features/index.rst
  examples/deployments/deployments_server/bedrock/README.md
  examples/deployments/deployments_server/bedrock/config.yaml
  mlflow/gateway/config.py
  mlflow/gateway/providers/__init__.py
  mlflow/gateway/providers/bedrock.py
  tests/gateway/providers/test_bedrock.py
  tests/gateway/test_integration.py
Labels: rn/none

#10711 Refactor: move tests cases to pytest in SQLAlchemy test suite [ver#7]
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#11148 Clean tmp path instantly in Transformers CI test
  mlflow/transformers/__init__.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/none, area/build

#11166 Resolve model metadata for saved models that do not define an artifact_path
  mlflow/models/model.py
  tests/models/test_model.py
Labels: rn/none

#11174 Do not `blacken-docs` python files in autoformat workflow
  .github/workflows/autoformat.yml
Labels: rn/none

#11175 Fix fixable `line-too-long`
  dev/preview_docs.py
  dev/ruff.py
  mlflow/deployments/openai/__init__.py
  mlflow/gateway/client.py
  mlflow/projects/databricks.py
  mlflow/pyfunc/__init__.py
  mlflow/recipes/__init__.py
  mlflow/recipes/cards/pandas_renderer.py
  mlflow/recipes/regression/v1/recipe.py
  mlflow/sagemaker/__init__.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/transformers/__init__.py
  tests/autologging/test_autologging_safety_unit.py
  tests/metrics/genai/test_genai_metrics.py
  tests/resources/mlflow-test-plugin/setup.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/store/tracking/test_sqlalchemy_store_schema.py
  tests/tracking/default_experiment/test_registry.py
  tests/tracking/test_tracking.py
Labels: rn/none

#11178 Replace pylint `line-too-long` with ruff `E501`
  mlflow/models/docker_utils.py
  mlflow/recipes/cards/pandas_renderer.py
  mlflow/recipes/dag_help_strings.py
  mlflow/recipes/utils/execution.py
  mlflow/server/auth/logo.py
  mlflow/utils/databricks_utils.py
  mlflow/utils/docstring_utils.py
  pylintrc
  pyproject.toml
  tests/metrics/genai/test_genai_metrics.py
  tests/utils/test_annotations.py
  tests/utils/test_databricks_utils.py
Labels: rn/none

#11186 Don't install pylint_plugins
  setup.py
Labels: rn/none

#11181 Fix false warning for missing signature in Databricks
  mlflow/models/model.py
Labels: rn/bug-fix, area/models

#11176 Update docs on auth db config
  docs/source/auth/index.rst
Labels: area/docs, rn/documentation

#11192 Unpin pyspark for johnsnowlabs 5.2.8
  mlflow/ml-package-versions.yml
Labels: rn/none

#11183 Remove pylint
  .github/workflows/lint.yml
  .github/workflows/matchers/clint.json
  .github/workflows/recipe-template.yml
  .pre-commit-config.yaml
  dev/clint/README.md
  dev/clint/pyproject.toml
  dev/clint/src/clint/__init__.py
  dev/clint/src/clint/__main__.py
  dev/clint/src/clint/builtin.py
  dev/clint/src/clint/config.py
  dev/clint/src/clint/linter.py
  dev/disallow_rule_ids.py
  mlflow/pyspark/ml/__init__.py
  mlflow/utils/import_hooks/__init__.py
  pylint_plugins/__init__.py
  pylint_plugins/errors.py
  pylint_plugins/no_rst.py
  pylintrc
  pyproject.toml
  requirements/lint-requirements.txt
  tests/langchain/test_langchain_model_export.py
  tests/utils/test_requirements_utils.py
Labels: rn/none

#11173 Join run and experiment in graphql
  dev/proto_to_graphql/autogeneration_utils.py
  dev/proto_to_graphql/schema_autogeneration.py
  mlflow/server/graphql/autogenerated_graphql_schema.py
  mlflow/server/graphql/graphql_schema_extensions.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#11094 Add logging frequency control to tensorflow flavor for consistency with Keras flavor
  mlflow/tensorflow/__init__.py
  mlflow/tensorflow/autologging.py
  mlflow/tensorflow/callback.py
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/feature

#11205 Skip `test_xgb_autolog_does_not_break_dmatrix_instantiation_with_data_none` for xgboost > 2.0.3
  tests/xgboost/test_xgboost_autolog.py
Labels: rn/none, enable-dev-tests

#11177 Format TOML files
  .github/workflows/autoformat.yml
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  dev/taplo.sh
  pyproject.toml
Labels: rn/none

#11187 Suppress pipeline construction error message for PEFT model
  mlflow/transformers/__init__.py
  mlflow/utils/logging_utils.py
  tests/transformers/helper.py
  tests/transformers/test_transformers_peft_model.py
  tests/utils/test_logging_utils.py
Labels: rn/none, area/models

#11184 Skip requirement inference for PEFT model
  mlflow/transformers/__init__.py
  tests/transformers/test_transformers_model_export.py
  tests/transformers/test_transformers_peft_model.py
Labels: rn/none, area/models

#11194 Remove black setttings in `pyproject.toml`
  pyproject.toml
Labels: rn/none

#11207 Remove `--sdist` and `--wheel` for `python -m build`
  .github/workflows/test-package-build.yml
Labels: rn/none

#11209 Validate metric key length in `_validate_metric`
  mlflow/utils/validation.py
Labels: rn/none

#11210 Validate experiment tag key using `_validate_tag_name`
  mlflow/store/tracking/file_store.py
Labels: rn/none

#11200 Add azure openai with langchain instructions
  docs/source/llms/langchain/notebooks/langchain-quickstart.ipynb
  docs/source/llms/langchain/notebooks/langchain-retriever.ipynb
  examples/langchain/retrieval_qa_chain_azure_openai.py
Labels: area/docs, rn/none

#11218 Replace `!pip` with `%pip`
  docs/source/deep-learning/tensorflow/quickstart/quickstart_tensorflow.ipynb
  docs/source/getting-started/tracking-server-overview/index.rst
  docs/source/traditional-ml/serving-multiple-models-with-pyfunc/notebooks/MME_Tutorial.ipynb
  examples/transformers/MLFlow_X_HuggingFace_Finetune_a_text_classification_model.ipynb
Labels: rn/none

#11198 Make _init_databricks_cli_config_provider supporting Databricks Runtime 9 ~ 13
  mlflow/utils/databricks_utils.py
Labels: rn/bug-fix

#11219 Enable `RUF100` to disallow unused `noqa` comments
  mlflow/legacy_databricks_cli/configure/provider.py
  mlflow/promptlab/__init__.py
  mlflow/utils/promptlab_utils.py
  pyproject.toml
  tests/pyfunc/docker/test_docker_flavors.py
Labels: rn/none

#11188 Refactor: move tests cases to pytest in SQLAlchemy test suite [ver#8]
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#11182 Add get_metric_history_bulk_interval api
  mlflow/entities/metric.py
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
  mlflow/server/__init__.py
  mlflow/server/handlers.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#11221 Avoid transformers 4.38.1 in cross-version tests
  mlflow/ml-package-versions.yml
Labels: rn/none

#11222 Use `actions/cache@v4` to silence node 16 deprecation warning
  .github/actions/cache-pip/action.yml
  .github/workflows/r.yml
Labels: rn/none

#11220 Fix f-strings missing f prefix
  examples/sktime/flavor.py
  mlflow/gateway/providers/anthropic.py
  mlflow/gateway/providers/bedrock.py
  mlflow/recipes/cards/pandas_renderer.py
  mlflow/tracking/client.py
  mlflow/transformers/signature.py
  mlflow/utils/model_utils.py
  mlflow/utils/search_utils.py
  tests/store/tracking/test_file_store.py
Labels: rn/none

#11215 Join search model versions into GraphQL getRun operation
  dev/proto_to_graphql/code_generator.py
  mlflow/java/client/src/main/java/org/mlflow/api/proto/ModelRegistry.java
  mlflow/protos/model_registry.proto
  mlflow/protos/model_registry_pb2.py
  mlflow/server/graphql/autogenerated_graphql_schema.py
  mlflow/server/graphql/graphql_schema_extensions.py
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#11211 Fix langchain autologging missing source on created run
  mlflow/langchain/_langchain_autolog.py
  tests/langchain/test_langchain_autolog.py
Labels: rn/none

#11086 Add Langchain Dependencies to Databricks CreateModelVersion Call
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/none, area/model-registry, integrations/databricks

#11224 Update batch_size calculation in keras autolog
  mlflow/keras/autologging.py
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#11227 Fix spark model loading failure
  mlflow/utils/_spark_utils.py
Labels: rn/bug-fix

#11208 Truncate long tag and param values to maximum length
  mlflow/environment_variables.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/utils/validation.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/utils/test_validation.py
Labels: rn/none

#11204 Fix small errata in mlflow.models.predict docs
  docs/source/model/dependencies.rst
  mlflow/models/python_api.py
Labels: area/docs, rn/none

#11230 Fix keras output dtype in signature
  mlflow/keras/utils.py
  tests/keras/test_save.py
Labels: rn/bug-fix

#11217 Add unit tests with mocks to Databricks dependencies
  tests/langchain/test_langchain_databricks_dependency_extraction.py
Labels: rn/none, area/models, integrations/databricks

#11231 Increase GetMetricHistoryBulk request limit to 100
  mlflow/server/handlers.py
Labels: rn/feature, area/server-infra

#11232 Add documentations for PEFT and save_pretrained option
  docs/source/llms/custom-pyfunc-for-llms/notebooks/custom-pyfunc-advanced-llm.ipynb
  docs/source/llms/transformers/guide/index.rst
  docs/source/llms/transformers/index.rst
  docs/source/llms/transformers/tutorials/audio-transcription/whisper.ipynb
  docs/source/llms/transformers/tutorials/conversational/conversational-model.ipynb
  docs/source/llms/transformers/tutorials/fine-tuning/transformers-fine-tuning.ipynb
  docs/source/llms/transformers/tutorials/prompt-templating/prompt-templating.ipynb
  docs/source/llms/transformers/tutorials/text-generation/text-generation.ipynb
  docs/source/llms/transformers/tutorials/translation/component-translation.ipynb
  mlflow/utils/docstring_utils.py
  mlflow/utils/logging_utils.py
  tests/transformers/test_transformers_model_export.py
Labels: area/docs, rn/documentation

#11150 Call load_context() when enforcing ChatModel output
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_chat_model.py
Labels: rn/bug-fix, area/models

#11236 Pin `sentence-transformers`
  mlflow/ml-package-versions.yml
Labels: rn/none

#11244 Remove useless try-except
  mlflow/langchain/api_request_parallel_processor.py
  mlflow/utils/file_utils.py
  pyproject.toml
Labels: rn/none

#11197 Keras automatic checkpoint
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_lightning_autolog.py
  mlflow/tensorflow/__init__.py
  mlflow/tensorflow/callback.py
  mlflow/utils/checkpoint_utils.py
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/feature, area/tracking, enable-dev-tests
