Repository mlflow/mlflow, pull requests merged in 2024-01, with the labels that each got.

#10767 Fix docs instruction: "k" -> "retriever_k"
  docs/source/llms/rag/notebooks/retriever-evaluation-tutorial.ipynb
  examples/llms/RAG/retriever-evaluation-tutorial.ipynb
Labels: area/docs, rn/none

#9310 Adds tagging for sagemaker endpoints and sagemaker config. Issue #9159
  mlflow/sagemaker/__init__.py
  tests/sagemaker/mock/__init__.py
  tests/sagemaker/test_sagemaker_deployment_client.py
Labels: rn/bug-fix, area/scoring, integrations/sagemaker

#10772 Fix SQLAlchemy and typing_extensions version incompatibility
  .github/workflows/cross-version-tests.yml
  .github/workflows/master.yml
  requirements/test-requirements.txt
Labels: rn/none

#10771 Pin Python to 3.9 for statsmodels dev version
  .github/workflows/cross-version-tests.yml
  dev/get_minimum_required_python.py
Labels: rn/none, area/build, enable-dev-tests

#10698 Only include necessary information in prompt for GenAI metrics
  mlflow/metrics/genai/base.py
  mlflow/metrics/genai/genai_metric.py
  mlflow/metrics/genai/metric_definitions.py
  mlflow/metrics/genai/prompt_template.py
  mlflow/metrics/genai/prompts/v1.py
  tests/metrics/genai/test_genai_metrics.py
  tests/metrics/genai/test_prompt_template.py
Labels: rn/none

#10741 Support saving input_example with no conversion
  docs/source/models.rst
  mlflow/langchain/__init__.py
  mlflow/models/utils.py
  mlflow/openai/__init__.py
  mlflow/pyfunc/__init__.py
  mlflow/transformers/__init__.py
  mlflow/utils/docstring_utils.py
  tests/models/test_model.py
Labels: rn/none

#10764 Remove unncessary dependencies from mlflow-spark
  mlflow/java/spark/pom.xml
Labels: rn/none, area/tracking

#10776 Fix a few broken links on LLM examples
  docs/source/llms/index.rst
  examples/deployments/deployments_server/bedrock/README.md
Labels: area/docs, rn/none

#10774 Fix broken redirects on the website
  docs/source/conf.py
  docs/source/registry.rst
  requirements/doc-min-requirements.txt
Labels: area/docs, rn/none

#10783 Fix typo in docs
  mlflow/models/evaluation/base.py
Labels: rn/none

#10769 Move promptlab.py to its own directory
  mlflow/__init__.py
  mlflow/promptlab/__init__.py
  mlflow/utils/promptlab_utils.py
  tests/promptlab/test_promptlab_model.py
Labels: rn/none

#10781 Fix spacy test
  .github/workflows/cross-version-tests.yml
  mlflow/ml-package-versions.yml
  requirements/test-requirements.txt
Labels: rn/none

#10785 Fix tensorflow tests
  mlflow/ml-package-versions.yml
Labels: rn/none

#10786 Fix cross version tests
  mlflow/ml-package-versions.yml
  tests/langchain/test_langchain_model_export.py
Labels: rn/none

#10782 Update QA and RAG evaluation notebooks
  docs/source/llms/llm-evaluate/notebooks/question-answering-evaluation.ipynb
  docs/source/llms/llm-evaluate/notebooks/rag-evaluation-llama2.ipynb
  docs/source/llms/llm-evaluate/notebooks/rag-evaluation.ipynb
  examples/evaluation/qa-evaluation.ipynb
  examples/evaluation/rag-evaluation.ipynb
Labels: rn/none

#10578 Evaluate a HuggingFace LLM with mlflow.evaluate() guide
  examples/evaluation/huggingface-evaluation.ipynb
Labels: rn/none

#10778 Add deduplication logic for pip requirements and extras handling for MLflow models
  mlflow/utils/environment.py
  tests/utils/test_environment.py
Labels: rn/bug-fix, area/models

#10731 Replace get_bucket_location with head_bucket
  mlflow/store/artifact/optimized_s3_artifact_repo.py
  requirements/test-requirements.txt
  setup.py
  tests/store/artifact/test_optimized_s3_artifact_repo.py
Labels: rn/none, area/model-registry

#10770 Add tutorials and guides for LangChain
  docs/source/_static/images/tutorials/llms/langchain-agents.png
  docs/source/_static/images/tutorials/llms/langchain-retrievalqa.png
  docs/source/_static/images/tutorials/llms/stateful-chains.png
  docs/source/index.rst
  docs/source/llms/index.rst
  docs/source/llms/langchain/guide/index.rst
  docs/source/llms/langchain/index.rst
  docs/source/llms/langchain/notebooks/langchain-agent.ipynb
  docs/source/llms/langchain/notebooks/langchain-quickstart.ipynb
  docs/source/llms/langchain/notebooks/langchain-retriever.ipynb
  docs/source/models.rst
  examples/langchain/retriever_chain.py
  examples/langchain/simple_agent.py
  examples/langchain/simple_chain.py
Labels: area/docs, rn/documentation

#10758 Automatically convert OpenAI input messages to LangChain chat messages for pyfunc predict
  mlflow/langchain/api_request_parallel_processor.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/feature, area/models

#10754 Dark mode fixes: editable note and persistence
  mlflow/server/js/src/app.tsx
  mlflow/server/js/src/common/components/EditableNote.css
  mlflow/server/js/src/common/hooks/useMLflowDarkTheme.tsx
Labels: rn/none

#10784 Adds experimental support for LangChain callbacks to be passed to mlflow.langchain models via a protected method.
  mlflow/langchain/__init__.py
  mlflow/langchain/api_request_parallel_processor.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/none, area/models, integrations/databricks

#10792 Remove the Redundant duplication check in transformers dependency validation
  mlflow/transformers/__init__.py
  mlflow/utils/environment.py
  tests/transformers/test_transformers_model_export.py
  tests/utils/test_environment.py
Labels: rn/none, area/models

#10729 [WIP] Fix ReplAwareDatasourceAttributeExtractor
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/DatasourceAttributeExtractor.scala
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/ReflectionUtils.scala
  mlflow/java/spark/src/test/scala/org/mlflow/spark/autologging/ReflectionUtilsSuite.scala
Labels: rn/bug-fix, language/java

#10797 Automatically convert LangChain responses for OpenAI requests to OpenAI response format
  mlflow/langchain/__init__.py
  mlflow/langchain/api_request_parallel_processor.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/none, area/models

#10795 Add note to docstring for fluent API set_experiment
  docs/source/tracking/tracking-api.rst
  mlflow/tracking/fluent.py
Labels: area/docs, rn/none

#10759 Enhance `predict` API to serve for env validation purpose.
  docs/source/deployment/index.rst
  mlflow/models/__init__.py
  mlflow/models/cli.py
  mlflow/models/python_api.py
  mlflow/pyfunc/_mlflow_pyfunc_backend_predict.py
  mlflow/pyfunc/backend.py
  mlflow/rfunc/backend.py
  mlflow/utils/cli_args.py
  mlflow/utils/conda.py
  mlflow/utils/virtualenv.py
  tests/models/test_cli.py
  tests/models/test_python_api.py
Labels: rn/feature, area/models

#10806 Fix hf dataset test
  tests/data/test_huggingface_dataset_and_source.py
Labels: rn/none

#10761 Add LongString custom scalar
  mlflow/server/graphql/graphql_custom_scalars.py
Labels: rn/none, area/uiux

#10800 Fix documentation for LLM Evaluate
  docs/source/llms/llm-evaluate/index.rst
Labels: rn/none

#10799 Fix documentation detail for justifications
  docs/source/models.rst
Labels: rn/none

#10651 Fix local uri
  mlflow/environment_variables.py
  mlflow/server/handlers.py
  mlflow/utils/uri.py
  tests/artifacts/test_artifacts.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/test_rest_tracking.py
  tests/utils/test_file_utils.py
  tests/utils/test_uri.py
Labels: rn/none

#10807 Add document for model dependency management
  docs/source/deployment/index.rst
  docs/source/model/dependencies.rst
  docs/source/models.rst
Labels: area/docs, rn/documentation

#10811 Replace Window shell-escaping of databricks run command with bash escaping
  mlflow/projects/databricks.py
Labels: area/windows, rn/bug-fix, area/projects, integrations/databricks

#10762 Add base autogen code
  dev/proto_to_graphql/autogeneration_utils.py
  dev/proto_to_graphql/code_generator.py
  dev/proto_to_graphql/parsing_utils.py
  dev/proto_to_graphql/schema_autogeneration.py
  dev/proto_to_graphql/string_utils.py
Labels: rn/none, area/build

#10798 Refactoring of the Getting Started page
  docs/source/_static/images/tutorials/introductory/autologging-intro.png
  docs/source/_static/images/tutorials/introductory/intro-run-comparison.png
  docs/source/_static/images/tutorials/introductory/tracking-basics.png
  docs/source/getting-started/index.rst
  docs/source/getting-started/logging-first-model/index.rst
  docs/source/getting-started/quickstart-1/index.rst
  docs/source/getting-started/quickstart-2/index.rst
  docs/source/index.rst
  docs/source/tracking/backend-stores.rst
Labels: area/docs, rn/documentation

#10814 Add logs to flavor cards in docs
  docs/source/deep-learning/index.rst
  docs/source/llms/index.rst
Labels: area/docs, rn/none

#10732 google docstring conversion batch (first ~5 directories)
  mlflow/artifacts/__init__.py
  mlflow/azure/client.py
  mlflow/catboost/__init__.py
  mlflow/data/__init__.py
  mlflow/data/artifact_dataset_sources.py
  mlflow/data/dataset.py
  mlflow/data/dataset_registry.py
  mlflow/data/dataset_source.py
  mlflow/data/dataset_source_registry.py
  mlflow/data/delta_dataset_source.py
  mlflow/data/digest_utils.py
  mlflow/data/filesystem_dataset_source.py
  mlflow/data/http_dataset_source.py
  mlflow/data/huggingface_dataset.py
  mlflow/data/numpy_dataset.py
  mlflow/data/pandas_dataset.py
  mlflow/data/schema.py
  mlflow/data/spark_dataset.py
  mlflow/data/spark_dataset_source.py
  mlflow/data/spark_delta_utils.py
  mlflow/data/tensorflow_dataset.py
  mlflow/diviner/__init__.py
  mlflow/exceptions.py
Labels: area/docs, rn/none

#10104 Implement promptflow model flavor
  conftest.py
  docs/source/python_api/mlflow.promptflow.rst
  examples/promptflow/basic/flow.dag.yaml
  examples/promptflow/basic/hello.jinja2
  examples/promptflow/basic/hello.py
  examples/promptflow/basic/requirements.txt
  examples/promptflow/train.py
  mlflow/__init__.py
  mlflow/ml_package_versions.py
  mlflow/promptflow/__init__.py
  requirements/extra-ml-requirements.txt
  tests/promptflow/additional_file
  tests/promptflow/flow_with_additional_includes/echo.py
  tests/promptflow/flow_with_additional_includes/flow.dag.yaml
  tests/promptflow/flow_with_additional_includes/hello.jinja2
  tests/promptflow/flow_with_additional_includes/requirements.txt
  tests/promptflow/test_promptflow_model_export.py
Labels: rn/feature, area/models

#10828 Fix langchain notebooks
  docs/source/llms/langchain/notebooks/langchain-agent.ipynb
  docs/source/llms/langchain/notebooks/langchain-retriever.ipynb
Labels: area/docs, rn/none

#10825 Google docstring conversion batch 1
  mlflow/deployments/__init__.py
  mlflow/deployments/base.py
  mlflow/deployments/databricks/__init__.py
  mlflow/deployments/interface.py
  mlflow/deployments/mlflow/__init__.py
  mlflow/deployments/openai/__init__.py
  mlflow/deployments/plugin_manager.py
  mlflow/deployments/utils.py
  mlflow/entities/run_data.py
  mlflow/fastai/__init__.py
  mlflow/gateway/client.py
  mlflow/gateway/fluent.py
  mlflow/gateway/providers/utils.py
  mlflow/gateway/utils.py
  mlflow/gluon/__init__.py
  mlflow/h2o/__init__.py
  mlflow/johnsnowlabs/__init__.py
  mlflow/langchain/__init__.py
  mlflow/langchain/api_request_parallel_processor.py
  mlflow/langchain/runnables.py
  mlflow/openai/__init__.py
Labels: area/docs, rn/none

#10826 Google docstring conversion batch 2
  mlflow/tensorflow/__init__.py
  mlflow/tensorflow/_autolog.py
  mlflow/transformers/__init__.py
  mlflow/types/schema.py
  mlflow/types/utils.py
  mlflow/xgboost/__init__.py
Labels: area/docs, rn/none

#10827 Google docstring conversion batch 3
  mlflow/utils/__init__.py
  mlflow/utils/_spark_utils.py
  mlflow/utils/annotations.py
  mlflow/utils/arguments_utils.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/autologging_utils/client.py
  mlflow/utils/autologging_utils/events.py
  mlflow/utils/autologging_utils/logging_and_warnings.py
  mlflow/utils/autologging_utils/safety.py
  mlflow/utils/autologging_utils/versioning.py
  mlflow/utils/conda.py
  mlflow/utils/databricks_utils.py
  mlflow/utils/docstring_utils.py
  mlflow/utils/doctor.py
  mlflow/utils/environment.py
  mlflow/utils/file_utils.py
  mlflow/utils/import_hooks/__init__.py
  mlflow/utils/model_utils.py
  mlflow/utils/name_utils.py
  mlflow/utils/os.py
  mlflow/utils/process.py
  mlflow/utils/proto_json_utils.py
  mlflow/utils/request_utils.py
  mlflow/utils/requirements_utils.py
  mlflow/utils/rest_utils.py
  mlflow/utils/server_cli_utils.py
  mlflow/utils/uri.py
  mlflow/utils/virtualenv.py
Labels: area/docs, rn/none

#10834 Enable hf_transfer for CI test and prefetch
  .github/workflows/cross-version-tests.yml
  mlflow/ml-package-versions.yml
  pytest.ini
  tests/transformers/conftest.py
  tests/transformers/helper.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/none, area/build

#10839 Fix an issue with an incorrect retry default timeout for urllib3 1.x
  mlflow/utils/request_utils.py
Labels: rn/bug-fix, area/tracking

#10765 Gateway Streaming for OpenAI
  docs/source/llms/deployments/index.rst
  mlflow/deployments/server/app.py
  mlflow/gateway/providers/ai21labs.py
  mlflow/gateway/providers/anthropic.py
  mlflow/gateway/providers/base.py
  mlflow/gateway/providers/openai.py
  mlflow/gateway/providers/utils.py
  mlflow/gateway/schemas/chat.py
  mlflow/gateway/schemas/completions.py
  mlflow/gateway/utils.py
  tests/gateway/providers/test_openai.py
  tests/gateway/tools.py
Labels: rn/feature, area/deployments

#10791 Support saving prompt templates for transformers
  mlflow/models/model.py
  mlflow/transformers/__init__.py
  mlflow/utils/docstring_utils.py
  tests/transformers/test_transformers_prompt_templating.py
Labels: rn/feature, area/models

#10844 Fix langchain tests
  mlflow/ml-package-versions.yml
Labels: rn/none

#10845 Clean up langchain tests
  mlflow/langchain/utils.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/none

#10841 Add feature update cards for 2.9 and 2.10
  docs/source/_static/images/logos/gateway-header-image.png
  docs/source/_static/images/logos/homepage.png
  docs/source/new-features/index.rst
Labels: area/docs, rn/none

#10395 Add dark theme to MLflow UI
  mlflow/server/js/src/MlflowRouter.tsx
  mlflow/server/js/src/app.tsx
  mlflow/server/js/src/common/components/DarkThemeSwitch.tsx
  mlflow/server/js/src/common/components/DesignSystemContainer.tsx
  mlflow/server/js/src/common/components/EditableNote.css
  mlflow/server/js/src/common/components/MlflowHeader.tsx
  mlflow/server/js/src/common/hooks/useMLflowDarkTheme.tsx
  mlflow/server/js/src/experiment-tracking/components/App.tsx
  mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.test.tsx
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.tsx
  mlflow/server/js/src/experiment-tracking/components/HomeView.test.tsx
  mlflow/server/js/src/experiment-tracking/components/HomeView.tsx
  mlflow/server/js/src/experiment-tracking/components/ParallelCoordinatesPlotPanel.tsx
  mlflow/server/js/src/model-registry/components/CreateModelForm.tsx
  mlflow/server/js/src/shared/web-shared/design-system/index.tsx
Labels: rn/none

#10840 Suppress feature store dependency warning
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_dependencies_functions.py
Labels: rn/none, area/models

#10854 Pin uvicorn
  .github/workflows/gateway.yml
Labels: rn/none

#10835 Support objects & arrays in spark udf return type
  mlflow/pyfunc/__init__.py
  mlflow/types/utils.py
  tests/langchain/test_langchain_model_export.py
  tests/pyfunc/test_spark.py
Labels: rn/none

#10857 Increase Gunicorn worker timeout for MLflow Deployment Server pagenation test
  .github/workflows/gateway.yml
  mlflow/deployments/constants.py
  mlflow/deployments/databricks/__init__.py
  mlflow/deployments/mlflow/__init__.py
  mlflow/environment_variables.py
  tests/gateway/test_fluent.py
Labels: rn/none, area/deployments

#10849 Onboard `getRun` to graphql autogen, plus various small updates
  dev/proto_to_graphql/autogeneration_utils.py
  dev/proto_to_graphql/code_generator.py
  dev/proto_to_graphql/schema_autogeneration.py
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
  mlflow/server/graphql/autogenerated_graphql_schema.py
  mlflow/server/graphql/graphql_schema_extensions.py
  mlflow/server/handlers.py
Labels: rn/none, area/uiux, area/build

#10843 Add warning for dependency diff when model loading
  mlflow/pyfunc/__init__.py
  mlflow/utils/environment.py
  mlflow/utils/requirements_utils.py
  tests/pyfunc/test_dependencies_functions.py
  tests/pyfunc/test_spark.py
  tests/utils/test_requirements_utils.py
Labels: rn/none, area/models

#10858 Pin moto version to 4.2.x
  requirements/test-requirements.txt
Labels: rn/none, area/artifacts

#10862 Update Model Registry docs screenshots to feature new UI
  docs/source/_static/images/oss_registry_3_overview.png
  docs/source/_static/images/oss_registry_4_model.png
  docs/source/_static/images/oss_registry_4b_model_alias.png
  docs/source/_static/images/oss_registry_5_version.png
  docs/source/_static/images/oss_registry_6_version.png
  docs/source/model-registry.rst
Labels: area/docs, rn/none

#10822 Refactor Gateway provider unimplemented endpoint errors
  mlflow/gateway/providers/ai21labs.py
  mlflow/gateway/providers/anthropic.py
  mlflow/gateway/providers/base.py
  mlflow/gateway/providers/bedrock.py
  mlflow/gateway/providers/cohere.py
  mlflow/gateway/providers/huggingface.py
  mlflow/gateway/providers/mlflow.py
  mlflow/gateway/providers/mosaicml.py
  mlflow/gateway/providers/openai.py
  mlflow/gateway/providers/palm.py
  tests/gateway/providers/test_ai21labs.py
  tests/gateway/providers/test_anthropic.py
  tests/gateway/providers/test_huggingface.py
Labels: rn/none, area/deployments

#10836 Prompt template docs
  docs/source/llms/index.rst
  docs/source/llms/transformers/guide/index.rst
  docs/source/llms/transformers/index.rst
  docs/source/llms/transformers/tutorials/prompt-templating/prompt-templating.ipynb
Labels: area/docs, rn/documentation

#10867 Add hf_transfer to sentence transformers test requirements
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build, enable-dev-tests

#10852 10851: fix incorrect exception error message
  mlflow/models/utils.py
Labels: rn/none, area/models

#10859 Improve error message when code_path includes Databricks notebook
  mlflow/pyfunc/model.py
  mlflow/utils/model_utils.py
  tests/utils/test_model_utils.py
Labels: rn/none, area/models

#10801 Langchain autologging support
  .github/workflows/cross-version-tests.yml
  mlflow/langchain/__init__.py
  mlflow/langchain/_langchain_autolog.py
  mlflow/langchain/utils.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/models/model.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  mlflow/utils/autologging_utils/safety.py
  tests/langchain/conftest.py
  tests/langchain/test_langchain_autolog.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/feature

#10833 Add tips for reducing dependency errors
  docs/source/model/dependencies.rst
Labels: area/docs, rn/none

#10863 Rewrite the search run doc
  docs/source/_static/images/search-runs/created_mlflow_runs.png
  docs/source/_static/images/search-runs/run_search_bar.png
  docs/source/search-runs.rst
  docs/source/tracking/tracking-api.rst
Labels: rn/documentation

#10789 Add the HuggingFace Model Evaluation Notebook to the website
  docs/source/llms/llm-evaluate/notebooks/huggingface-evaluation.ipynb
  docs/source/llms/llm-evaluate/notebooks/index.rst
Labels: area/docs, rn/documentation

#10838 Relocate and supplement Model Signature and Input Example docs
  docs/source/_static/images/models/signature-enforcement.png
  docs/source/_static/images/models/signature-vs-no-signature.png
  docs/source/model/notebooks/signature_examples.ipynb
  docs/source/model/signatures.rst
  docs/source/models.rst
Labels: area/docs, rn/documentation

#10877 FIX: Git version not logged when executable in current path.
  mlflow/utils/git_utils.py
Labels: rn/none, area/server-infra

#10873 Fix: Template injection in MLflow Recipe leads to an RCE
  mlflow/recipes/cards/__init__.py
  mlflow/recipes/steps/ingest/__init__.py
Labels: rn/none, area/recipes

#10779 Add rate limit to deployment api
  docs/source/llms/deployments/index.rst
  examples/deployments/deployments_server/openai/config.yaml
  mlflow/deployments/server/app.py
  mlflow/deployments/server/config.py
  mlflow/environment_variables.py
  mlflow/gateway/config.py
  requirements/gateway-requirements.txt
  requirements/gateway-requirements.yaml
  tests/deployments/mlflow/test_mlflow.py
  tests/deployments/server/test_server_app.py
  tests/gateway/test_client.py
  tests/gateway/test_fluent.py
  tests/gateway/test_gateway_app.py
  tests/gateway/test_runner.py
  tests/gateway/tools.py
Labels: area/docs, rn/feature, area/deployments

#10875 Langchain autologging improvement + docs
  docs/source/llms/langchain/guide/index.rst
  docs/source/llms/langchain/index.rst
  examples/langchain/chain_autolog.py
  mlflow/langchain/_langchain_autolog.py
  tests/langchain/test_langchain_autolog.py
Labels: rn/none

#10871 Add support for retrieving license files for transformers models
  docs/source/llms/transformers/guide/index.rst
  mlflow/transformers/__init__.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/feature, area/models

#10881 Fix langchain autologging test
  .github/workflows/cross-version-tests.yml
Labels: rn/none

#10882 Fix match for `GridSearchCV.predict`
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/none, enable-dev-tests

#10876 Add unit tests for Docker image building and refactor
  mlflow/models/docker_utils.py
  mlflow/pyfunc/backend.py
  mlflow/sagemaker/cli.py
  tests/pyfunc/test_docker.py
  tests/resources/dockerfile/Dockerfile_conda
  tests/resources/dockerfile/Dockerfile_default
  tests/resources/dockerfile/Dockerfile_enable_mlserver
  tests/resources/dockerfile/Dockerfile_install_mlflow
  tests/resources/dockerfile/Dockerfile_install_mlflow_from_mlflow_home
  tests/resources/dockerfile/Dockerfile_no_model_uri
  tests/resources/dockerfile/Dockerfile_sagemaker_conda
  tests/resources/dockerfile/Dockerfile_sagemaker_virtualenv
  tests/resources/dockerfile/Dockerfile_with_mlflow_home
  tests/sagemaker/test_cli.py
Labels: rn/none, area/models

#10886 Fixed the `KeyError: 'loss'` bug for the Quickstart guidline
  docs/source/getting-started/quickstart-2/index.rst
Labels: area/docs, rn/documentation, area/examples

#10893 Fix recipe card display format
  mlflow/recipes/cards/__init__.py
  mlflow/recipes/steps/ingest/__init__.py
Labels: rn/bug-fix

#10903 Revert "Implement promptflow model flavor (#10104)"
  conftest.py
  docs/source/python_api/mlflow.promptflow.rst
  examples/promptflow/basic/flow.dag.yaml
  examples/promptflow/basic/hello.jinja2
  examples/promptflow/basic/hello.py
  examples/promptflow/basic/requirements.txt
  examples/promptflow/train.py
  mlflow/__init__.py
  mlflow/ml_package_versions.py
  mlflow/promptflow/__init__.py
  requirements/extra-ml-requirements.txt
  tests/promptflow/additional_file
  tests/promptflow/flow_with_additional_includes/echo.py
  tests/promptflow/flow_with_additional_includes/flow.dag.yaml
  tests/promptflow/flow_with_additional_includes/hello.jinja2
  tests/promptflow/flow_with_additional_includes/requirements.txt
  tests/promptflow/test_promptflow_model_export.py
Labels: rn/none, area/models

#10894 Fix azure openai and docs
  docs/source/llms/openai/guide/index.rst
  examples/openai/azure_openai.py
  mlflow/openai/__init__.py
  mlflow/utils/openai_utils.py
  tests/openai/test_openai_model_export.py
Labels: rn/none

#10856 Gateway streaming for Cohere
  docs/source/llms/deployments/index.rst
  mlflow/gateway/providers/base.py
  mlflow/gateway/providers/cohere.py
  mlflow/gateway/schemas/completions.py
  tests/gateway/providers/test_cohere.py
Labels: rn/feature, area/deployments

#10911 Update action version to silence node 16 deprecation warning
  .github/actions/setup-java/action.yml
  .github/actions/setup-python/action.yml
  .github/actions/untracked/action.yml
  .github/workflows/advice.yml
  .github/workflows/autoformat.yml
  .github/workflows/cancel.yml
  .github/workflows/closing-pr.yml
  .github/workflows/cross-version-tests.yml
  .github/workflows/deployments.yml
  .github/workflows/dev-setup.yml
  .github/workflows/devcontainer.yml
  .github/workflows/examples.yml
  .github/workflows/gateway.yml
  .github/workflows/js.yml
  .github/workflows/labeling.yml
  .github/workflows/lint.yml
  .github/workflows/master.yml
  .github/workflows/preview-docs.yml
  .github/workflows/protect.yml
  .github/workflows/protos.yml
  .github/workflows/push-images.yml
  .github/workflows/r.yml
  .github/workflows/recipe-template.yml
  .github/workflows/recipe.yml
  .github/workflows/release-note.yml
  .github/workflows/requirements.yml
  .github/workflows/rerun.yml
  .github/workflows/test-package-build.yml
Labels: rn/none

#10915 Simplify spark session fixture usage
  tests/evaluate/test_evaluation.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
  tests/tensorflow/test_keras_pyfunc_model_works_with_all_input_types.py
Labels: rn/none

#10924 Replace `pytest.warns(None)` with `warnings.catch_warnings`
  tests/autologging/test_autologging_behaviors_unit.py
Labels: rn/none

#10925 Move `tests/dev` to `dev/tests`
  .github/workflows/cross-version-tests.yml
  dev/tests/test_set_matrix.py
  dev/tests/test_update_ml_package_versions.py
Labels: rn/none

#10929 Install torchvision in gateway workflow
  .github/workflows/gateway.yml
Labels: rn/none

#10927 Fix `test_client_can_be_serialized_with_pickle`
  mlflow/tracking/_tracking_service/utils.py
  tests/tracking/test_client.py
Labels: rn/none, fail-fast

#10928 Request a review from oss team members when mlflow-team is requested a review
  .github/workflows/team-review.yml
Labels: rn/none

#10941 Introduce committer process for MLflow
  COMMITTER.md
Labels: rn/none

#10908 Multi-model custom pyfunc tutorial
  docs/source/traditional-ml/index.rst
  docs/source/traditional-ml/serving-multiple-models-with-pyfunc/index.rst
  docs/source/traditional-ml/serving-multiple-models-with-pyfunc/notebooks/MME_Tutorial.ipynb
Labels: area/docs, rn/none

#10921 Improve error message when calling get_latest_versions for models in UC
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/store/artifact/test_unity_catalog_models_artifact_repo.py
Labels: rn/none

#10930 Improve langchain autologging doc
  docs/source/conf.py
  docs/source/llms/langchain/guide/index.rst
  examples/langchain/chain_autolog.py
Labels: rn/none

#10943 Exclude `model_computed_fields` from docs
  docs/source/python_api/mlflow.gateway.rst
Labels: rn/none

#10923 Fix artifact_path in local artifact store
  mlflow/store/artifact/local_artifact_repo.py
  tests/store/artifact/test_local_artifact_repo.py
  tests/utils/test_promptlab_utils.py
Labels: rn/none

#10888 Google docstring conversion batch 7
  mlflow/langchain/__init__.py
  mlflow/langchain/retriever_chain.py
  mlflow/langchain/runnables.py
  mlflow/lightgbm/__init__.py
  mlflow/onnx/__init__.py
  mlflow/pmdarima/__init__.py
  mlflow/prophet/__init__.py
  mlflow/pyspark/ml/__init__.py
  mlflow/pyspark/ml/_autolog.py
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_lightning_autolog.py
  mlflow/recipes/cards/__init__.py
  mlflow/recipes/cards/histogram_generator.py
  mlflow/recipes/cards/pandas_renderer.py
  mlflow/recipes/classification/v1/recipe.py
  mlflow/recipes/dag_help_strings.py
  mlflow/recipes/recipe.py
  mlflow/recipes/regression/v1/recipe.py
  mlflow/recipes/step.py
  mlflow/recipes/steps/evaluate.py
  mlflow/recipes/steps/ingest/__init__.py
  mlflow/recipes/steps/ingest/datasets.py
  mlflow/recipes/utils/__init__.py
  mlflow/recipes/utils/execution.py
  mlflow/recipes/utils/metrics.py
  mlflow/recipes/utils/step.py
  mlflow/recipes/utils/tracking.py
  mlflow/recipes/utils/wrapped_recipe_model.py
Labels: area/docs, rn/none

#10949 Use merge ref instead of head ref in CircleCI
  .circleci/config.yml
Labels: rn/none

#10918 Handle unrecognized response error code
  mlflow/exceptions.py
  tests/test_exceptions.py
Labels: rn/bug-fix

#10959 Set header on DatabricksDeploymentClient requests
  mlflow/deployments/databricks/__init__.py
Labels: rn/none

#10889 Move `_spark_autologging.py` into `spark/`
  mlflow/spark/__init__.py
  mlflow/spark/_autolog.py
  tests/spark/autologging/conftest.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging_unit.py
  tests/spark/autologging/utils.py
Labels: rn/none

#10936 Make RestException pickleable
  mlflow/exceptions.py
  tests/test_exceptions.py
Labels: rn/bug-fix

#10953 fix TensorInfo TypeError exception message
  mlflow/types/schema.py
  tests/types/test_schema.py
Labels: rn/bug-fix, area/tracking

#10960 Fix prompt templating bug with Text2TextGeneration pipeline
  mlflow/transformers/__init__.py
  tests/transformers/test_transformers_prompt_templating.py
Labels: rn/bug-fix, area/models
