Repository mlflow/mlflow, pull requests merged in 2024-10, with the labels that each got.

#13283 Fix set-matrix
  dev/set_matrix.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
Labels: rn/none

#13282 Update dev versions
  mlflow/R/mlflow/DESCRIPTION
  mlflow/java/client/pom.xml
  mlflow/java/pom.xml
  mlflow/java/scoring/pom.xml
  mlflow/java/scoring/src/main/java/org/mlflow/sagemaker/ScoringServer.java
  mlflow/java/scoring/src/test/java/org/mlflow/ScoringServerTest.java
  mlflow/java/spark/pom.xml
  mlflow/server/js/src/common/constants.tsx
  mlflow/version.py
  pyproject.release.toml
  pyproject.skinny.toml
  pyproject.toml
Labels: rn/none

#13239 Implement `create_logged_model`
  mlflow/entities/logged_model.py
  mlflow/entities/model_param.py
  mlflow/entities/model_status.py
  mlflow/entities/model_tag.py
  mlflow/models/model.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: rn/none

#13274 Implement `get_logged_model`
  mlflow/store/tracking/rest_store.py
  mlflow/utils/rest_utils.py
Labels: rn/none

#13250 Update xgboost autolog
  mlflow/xgboost/__init__.py
Labels: rn/none

#13287 Implement `finalize_logged_model`
  mlflow/store/tracking/rest_store.py
Labels: rn/none

#13292 Fix Transformers cross-version tests
  mlflow/ml-package-versions.yml
Labels: rn/none

#13145 Add Artifact support for Compare Run page
  mlflow/server/js/src/experiment-tracking/components/ArtifactViewTree.tsx
  mlflow/server/js/src/experiment-tracking/components/CompareRunArtifactView.tsx
  mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/hooks/useRunsArtifacts.test.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/hooks/useRunsArtifacts.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/utils/getCommonArtifacts.test.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/utils/getCommonArtifacts.ts
  mlflow/server/js/src/lang/default/en.json
Labels: rn/feature, area/uiux

#13296 Remove `tests/tensorflow/save_keras_model.py`
  tests/tensorflow/save_keras_model.py
Labels: rn/none

#13293 Add `prompt_tokens_details` in llama-index tests
  tests/llama_index/test_llama_index_tracer.py
Labels: rn/none

#13298 Remove `tests/tensorflow/save_tf_estimator_model.py`
  tests/tensorflow/save_tf_estimator_model.py
Labels: rn/none

#13297 Add `GetCredentialsForLoggedModelUpload`
  mlflow/java/client/src/main/java/com/databricks/api/proto/mlflow/DatabricksArtifacts.java
  mlflow/protos/databricks_artifacts.proto
  mlflow/protos/databricks_artifacts_pb2.py
Labels: rn/none

#13277 LlamaIndex workflow logging
  mlflow/llama_index/__init__.py
  mlflow/llama_index/pyfunc_wrapper.py
  mlflow/ml-package-versions.yml
  mlflow/models/model.py
  tests/llama_index/sample_code/simple_workflow.py
  tests/llama_index/test_llama_index_model_export.py
  tests/llama_index/test_llama_index_pyfunc_wrapper.py
Labels: rn/feature, area/tracking

#13300 Fix logged model entity names
  mlflow/entities/__init__.py
  mlflow/entities/logged_model.py
  mlflow/entities/logged_model_input.py
  mlflow/entities/logged_model_output.py
  mlflow/entities/logged_model_parameter.py
  mlflow/entities/logged_model_status.py
  mlflow/entities/logged_model_tag.py
  mlflow/entities/model_registry/model_version.py
  mlflow/entities/model_status.py
  mlflow/entities/run_inputs.py
  mlflow/entities/run_outputs.py
  mlflow/models/model.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: rn/none

#13302 Fix lint error in `test_save_load_workflow_as_code`
  tests/llama_index/test_llama_index_model_export.py
Labels: rn/none

#13285 Don't throw an exception in update_mlflow_versions if the new version is lower
  dev/update_mlflow_versions.py
Labels: rn/none

#13306 Add `GetCredentialsForLoggedModelDownload` proto
  mlflow/java/client/src/main/java/com/databricks/api/proto/mlflow/DatabricksArtifacts.java
  mlflow/protos/databricks_artifacts.proto
  mlflow/protos/databricks_artifacts_pb2.py
Labels: rn/none

#13308 Split evaluate job
  .github/workflows/master.yml
Labels: rn/none

#13305 Llama workflow Trace
  mlflow/llama_index/tracer.py
  mlflow/ml-package-versions.yml
  mlflow/models/model.py
  tests/llama_index/test_llama_index_tracer.py
Labels: rn/none, area/tracking, patch-2.17.0

#13012 Allow visualizing and comparing nested params
  mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx
Labels: rn/feature, area/uiux, patch-2.15.2, patch-2.16.3, patch-2.17.0

#12511 Devcontainer tooling improvements
  .devcontainer/Dockerfile.devcontainer
  .devcontainer/devcontainer.json
Labels: rn/none, area/build

#13315 Adding resources to be passed in via langchain log_model
  mlflow/langchain/__init__.py
  mlflow/models/model.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/feature, area/tracking, patch-2.17.0

#13279 Mark `role` and `index` as required for chat schema
  mlflow/dspy/wrapper.py
  mlflow/models/rag_signatures.py
Labels: rn/bug-fix, area/tracking

#13322 Lint proto files
  .github/workflows/protobuf-cross-test.yml
  .pre-commit-config.yaml
  dev/lint-proto.sh
  mlflow/java/client/src/main/java/com/databricks/api/proto/mlflow/DatabricksArtifacts.java
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/databricks_artifacts.proto
  mlflow/protos/databricks_artifacts_pb2.py
  mlflow/protos/databricks_managed_catalog_messages.proto
  mlflow/protos/databricks_managed_catalog_messages_pb2.py
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
Labels: rn/none

#13318 Add proto for `SetLoggedModelTags`
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
Labels: rn/none

#13291 Update langgraph evaluate and custom mlflow.evaluate examples
  docs/source/llms/langchain/index.rst
  docs/source/llms/llm-evaluate/index.rst
Labels: area/docs, rn/none, patch-2.17.0

#13330 Fix paths
  mlflow/java/client/src/main/java/com/databricks/api/proto/mlflow/DatabricksArtifacts.java
  mlflow/protos/databricks_artifacts.proto
  mlflow/protos/databricks_artifacts_pb2.py
Labels: rn/none

#13331 Add `taplo` to `PATH`
  .github/workflows/autoformat.yml
  dev/install-taplo.sh
Labels: rn/none

#13332 Add `DeleteLoggedModelTag` and `ListLoggedModelArtifacts` protos
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
  mlflow/server/graphql/autogenerated_graphql_schema.py
Labels: rn/none

#13335 Make version selector in docs just read from the `versions.json` file
  docs/theme/mlflow/static/js/custom.js
Labels: rn/none, patch-2.17.0

#13334 Fix code examples with invalid syntax
  dev/clint/src/clint/linter.py
  mlflow/deployments/databricks/__init__.py
  mlflow/models/evaluation/base.py
  mlflow/sagemaker/__init__.py
Labels: rn/none

#13338 Implement `delete_logged_model_tag`
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
Labels: rn/none

#13347 Cherry-pick #13335 to 2.17
  docs/theme/mlflow/static/js/custom.js
Labels: rn/none

#13341 Fix spacy CI
  mlflow/ml-package-versions.yml
  tests/fastai/test_fastai_model_export.py
Labels: rn/none, area/build, enable-dev-tests

#13342 Fix transformer CI
  mlflow/ml-package-versions.yml
  tests/transformers/test_transformers_autolog.py
Labels: rn/none, area/build, enable-dev-tests

#13350 fix fastai example
  examples/fastai/python_env.yaml
Labels: rn/none, area/build

#13351 Fix slow test
  tests/pyfunc/docker/conftest.py
Labels: rn/none, area/build

#13313 Fix more `log_model` calls
  dev/clint/src/clint/linter.py
  mlflow/sklearn/__init__.py
Labels: rn/none

#13309 Detect `log_model` with keyword `artifact_path` in notebooks
  .pre-commit-config.yaml
  dev/clint/src/clint/linter.py
  docs/source/llms/openai/notebooks/openai-code-helper.ipynb
  docs/source/llms/openai/notebooks/openai-embeddings-generation.ipynb
  examples/rapids/mlflow_project/notebooks/rapids_mlflow.ipynb
  examples/sklearn_elasticnet_wine/train.ipynb
  pyproject.toml
Labels: rn/none

#13345 Make DSPy wrapper compatible with single string output
  mlflow/dspy/wrapper.py
  tests/dspy/test_save.py
Labels: rn/feature, area/tracking

#13203 Databricks SDK based models artifact repo
  mlflow/environment_variables.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/artifact/cloud_artifact_repo.py
  mlflow/store/artifact/databricks_sdk_models_artifact_repo.py
  mlflow/store/artifact/unity_catalog_models_artifact_repo.py
  mlflow/utils/uri.py
  tests/store/artifact/test_databricks_sdk_models_artifact_repo.py
Labels: rn/none, area/artifacts

#13349 Fix example "Titanic_Captum_Interpret"
  examples/pytorch/CaptumExample/Titanic_Captum_Interpret.py
  examples/pytorch/CaptumExample/titanic3.csv
Labels: rn/none, area/build

#13295 Fix infer pip requirements for UCFunctionToolkit
  mlflow/langchain/__init__.py
  mlflow/utils/environment.py
  mlflow/utils/requirements_utils.py
  tests/utils/test_requirements_utils.py
Labels: rn/none, patch-2.17.0

#13333 Add contribution guide for tracing
  docs/source/llms/index.rst
  docs/source/llms/tracing/contribute.rst
  docs/source/llms/tracing/index.rst
  docs/source/llms/tracing/tracing-schema.rst
Labels: area/docs, rn/documentation, patch-2.17.0

#13312 Move model validation functionality from `mlflow.evaluate` into a dedicated API.
  docs/source/conf.py
  docs/source/models.rst
  examples/evaluation/evaluate_with_model_validation.py
  mlflow/__init__.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/models/evaluation/validation.py
  tests/evaluate/test_default_evaluator.py
  tests/evaluate/test_evaluation.py
  tests/evaluate/test_validation.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/dummy_evaluator.py
Labels: rn/breaking-change, area/models, area/tracking

#13356 Add a workflow to build a wheel
  .github/workflows/build-wheel.yml
  dev/build.py
Labels: rn/none

#13357 Update trace UI bundles
  mlflow/server/js/public/lib/ml-model-trace-renderer/css/658.5d125dec.chunk.css
  mlflow/server/js/public/lib/ml-model-trace-renderer/index.html
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/172.59c64095.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/172.c830216e.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/241.29eda319.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/299.1a713ef5.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/309.91909b87.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/309.9b356007.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/331.91fed59f.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/458.01b4fe13.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/458.d440ad7d.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/658.abed2ae8.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/735.b403c3bf.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/743.d9bbbd21.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/746.a0726c1c.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/766.394abaa3.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/876.fd09d011.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/991.5c550c7e.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/ml-model-trace-renderer.6cdc9226.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/ml-model-trace-renderer.a81e0aa3.js
Labels: rn/feature, area/uiux, patch-2.17.0

#13364 Use `MLFLOW_MULTIPART_UPLOAD_MINIMUM_FILE_SIZE` for MPU threshold
  mlflow/store/artifact/databricks_artifact_repo.py
  tests/store/artifact/test_databricks_artifact_repo.py
Labels: rn/none

#13373 Implement `log_inputs`
  mlflow/entities/logged_model_input.py
  mlflow/store/tracking/rest_store.py
Labels: rn/none

#13375 Update `LogMetric` proto
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
Labels: rn/none

#13369 Fix mlflow DSPy tests
  mlflow/dspy/load.py
  mlflow/dspy/save.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/utils/requirements_utils.py
  tests/dspy/test_save.py
Labels: rn/bug-fix, area/tracking

#13372 Ignore empty `choices` in openai autolog
  mlflow/openai/_openai_autolog.py
  tests/openai/mock_openai.py
  tests/openai/test_openai_autolog.py
Labels: rn/none, patch-2.17.0

#13366 Fix presigned_url_artifact request
  mlflow/store/artifact/presigned_url_artifact_repo.py
  mlflow/utils/rest_utils.py
  tests/utils/test_rest_utils.py
Labels: rn/bug-fix, area/tracking, patch-2.17.0

#13389 Cherrypicks 2.17.0, updating the RC
  dev/update_mlflow_versions.py
  docs/source/_static/images/llms/llama-index/llama_index_workflow_artifacts.png
  docs/source/_static/images/llms/llama-index/llama_index_workflow_graph.png
  docs/source/_static/images/llms/llama-index/llama_index_workflow_trace.png
  docs/source/llms/index.rst
  docs/source/llms/llama-index/index.rst
  docs/source/llms/llama-index/notebooks/llama_index_workflow_tutorial.ipynb
  docs/source/llms/tracing/contribute.rst
  docs/source/llms/tracing/index.rst
  docs/source/llms/tracing/tracing-schema.rst
  docs/source/models.rst
  mlflow/cli.py
  mlflow/entities/__init__.py
  mlflow/entities/document.py
  mlflow/langchain/__init__.py
  mlflow/langchain/databricks_dependencies.py
  mlflow/langchain/langchain_tracer.py
  mlflow/llama_index/__init__.py
  mlflow/llama_index/pyfunc_wrapper.py
  mlflow/llama_index/tracer.py
  mlflow/ml-package-versions.yml
  mlflow/models/dependencies_schemas.py
  mlflow/store/artifact/mlflow_artifacts_repo.py
  mlflow/tracing/fluent.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  mlflow/utils/environment.py
  mlflow/utils/requirements_utils.py
  tests/langchain/test_langchain_databricks_dependency_extraction.py
  tests/langchain/test_langchain_document_conversion.py
  tests/langchain/test_langchain_model_export.py
  tests/langchain/test_langchain_tracer.py
  tests/llama_index/sample_code/simple_workflow.py
  tests/llama_index/test_llama_index_model_export.py
  tests/llama_index/test_llama_index_node_conversion.py
  tests/llama_index/test_llama_index_pyfunc_wrapper.py
  tests/llama_index/test_llama_index_tracer.py
  tests/models/test_dependencies_schema.py
  tests/store/artifact/test_mlflow_artifact_repo.py
  tests/tracing/test_fluent.py
  tests/utils/test_requirements_utils.py
Labels: rn/none, area/models

#13390 fix(openai): remove unnecessary chunk_dicts initialization
  mlflow/openai/_openai_autolog.py
Labels: rn/none, area/tracking, patch-2.17.0

#13381 Bump python and node version in Dockerfile
  Dockerfile
Labels: rn/none

#13402 Add a warning for cherry-picks
  .github/workflows/cherry-picks-warn.yml
Labels: rn/none

#13399 Fixed docstrings in functions
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  examples/hyperparam/search_hyperopt.py
  examples/rapids/mlflow_project/src/rf_test/train_simple.py
  mlflow/models/model.py
  mlflow/pyfunc/__init__.py
  mlflow/sklearn/__init__.py
  mlflow/tracing/processor/mlflow.py
  mlflow/tracking/fluent.py
  mlflow/utils/_unity_catalog_utils.py
  mlflow/utils/docstring_utils.py
  mlflow/utils/file_utils.py
  tests/helper_functions.py
  tests/resources/data/dataset.py
  tests/utils/test_annotations.py
  tests/utils/test_docstring_utils.py
Labels: rn/none

#13358 Reuse exceeds_maximum_length in _validate_length_limit
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/utils/validation.py
  tests/store/model_registry/test_file_store.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none, area/tracking, area/server-infra

#13382 Improve ML package version compatibility warning message
  mlflow/utils/autologging_utils/versioning.py
  mlflow/utils/docstring_utils.py
Labels: rn/none

#13408 Fix preview-docs
  .github/workflows/preview-docs.yml
Labels: rn/none

#13340 Implement `list_logged_model_artifacts`
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/databricks_artifact_repo_resources.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
Labels: rn/none

#13412 Fix useless if conditions
  dev/clint/src/clint/linter.py
Labels: rn/none

#13414 Add "resources" to the DSPy flavor "log_model" and "save_model" flavors
  mlflow/dspy/save.py
Labels: rn/none, area/models, integrations/databricks

#13415 Fix dspy test
  conftest.py
  mlflow/ml-package-versions.yml
  tests/dspy/test_save.py
Labels: rn/none, area/build, enable-dev-tests, patch-2.17.1

#13416 Fix autogen test
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
Labels: rn/none, area/build, enable-dev-tests, patch-2.17.1

#13360 [1/x] Refactor default evaluator
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/models/evaluation/evaluator_registry.py
  mlflow/models/evaluation/evaluators/classifier.py
  mlflow/models/evaluation/evaluators/default.py
  mlflow/models/evaluation/evaluators/regressor.py
  mlflow/models/evaluation/evaluators/shap.py
  mlflow/models/evaluation/utils/metric.py
  mlflow/recipes/steps/automl/flaml.py
  tests/evaluate/test_default_evaluator.py
  tests/evaluate/test_evaluation.py
  tests/resources/mlflow-test-plugin/mlflow_test_plugin/dummy_evaluator.py
Labels: rn/none, area/models

#13423 Support dependency extraction from RunnableCallables
  mlflow/langchain/databricks_dependencies.py
Labels: rn/bug-fix, enable-dev-tests, patch-2.17.1

#13410 Deserialize JSON dataset input
  tests/tracking/test_rest_tracking.py
Labels: rn/none, area/tracking, area/server-infra

#13422 Update to throw a warning instead of error when set_retriever_schema is called twice
  mlflow/models/dependencies_schemas.py
  tests/models/test_dependencies_schema.py
Labels: rn/bug-fix, area/tracking, patch-2.17.1

#13418 Include how to enable `Rebase and Merge` option in `cherry-picks-warn` message
  .github/workflows/cherry-picks-warn.yml
Labels: rn/none

#13407 Update docs and infer_signature
  docs/source/model/signatures.rst
  mlflow/models/signature.py
  mlflow/models/utils.py
  tests/models/test_signature.py
Labels: rn/documentation, patch-2.17.1

#13429 Fix docstring parameter order
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  examples/flower_classifier/train.py
  mlflow/fastai/__init__.py
  mlflow/johnsnowlabs/__init__.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/models/python_api.py
  mlflow/pyfunc/__init__.py
  mlflow/pytorch/__init__.py
  mlflow/recipes/utils/execution.py
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/tensorflow/__init__.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  mlflow/transformers/__init__.py
  mlflow/utils/proto_json_utils.py
Labels: rn/none

#13443 Add missing docstring params to public APIs
  dev/clint/src/clint/linter.py
  examples/flower_classifier/image_pyfunc.py
  mlflow/legacy_databricks_cli/configure/provider.py
  mlflow/models/evaluation/base.py
  mlflow/pyfunc/model.py
  mlflow/sagemaker/__init__.py
  mlflow/sentence_transformers/__init__.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/artifact/models_artifact_repo.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/model_registry/rest_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/client.py
  mlflow/transformers/flavor_config.py
  mlflow/utils/file_utils.py
  tests/helper_functions.py
  tests/projects/test_project_spec.py
Labels: rn/none

#13446 Fix `mlflow.pyfunc.save_model` docstring
  mlflow/pyfunc/__init__.py
Labels: rn/none, patch-2.17.1

#13448 Fix `search_traces` docstring
  mlflow/tracking/client.py
Labels: rn/none

#13430 Remove unused requirements in `ml-package-versions.yml`
  dev/set_matrix.py
  mlflow/ml-package-versions.yml
Labels: rn/none

#13445 Disable pmdarima dev test
  mlflow/ml-package-versions.yml
Labels: rn/none

#13450 Fix default evaluator resolution for list case
  mlflow/models/evaluation/base.py
  tests/evaluate/test_evaluation.py
Labels: rn/none, area/tracking

#13417 Allow cross-version tests to use python 3.10
  dev/set_matrix.py
Labels: rn/none

#13457 Implement `search_logged_models`
  mlflow/store/tracking/rest_store.py
Labels: rn/none

#13444 Fix nightly eval instrumentation test
  mlflow/models/evaluation/base.py
Labels: rn/none, area/models

#13276 Make spark_udf support Databricks Serverless, Databricks connect, and prebuilt python environment
  examples/spark_udf/README.md
  examples/spark_udf/spark_udf_with_prebuilt_env.py
  mlflow/langchain/__init__.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/dbconnect_artifact_cache.py
  mlflow/tracking/_model_registry/utils.py
  mlflow/utils/databricks_utils.py
  mlflow/utils/nfs_on_spark.py
  mlflow/utils/spark_utils.py
  mlflow/utils/virtualenv.py
  tests/pyfunc/test_spark.py
Labels: rn/feature, area/scoring

#13397 Add GCS token refresh for log_artifacts
  mlflow/store/artifact/artifact_repo.py
  mlflow/store/artifact/azure_data_lake_artifact_repo.py
  mlflow/store/artifact/cloud_artifact_repo.py
  mlflow/store/artifact/gcs_artifact_repo.py
  mlflow/store/artifact/optimized_s3_artifact_repo.py
  mlflow/store/artifact/presigned_url_artifact_repo.py
  mlflow/utils/_unity_catalog_utils.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/store/artifact/test_gcs_artifact_repo.py
  tests/store/artifact/test_presigned_url_artifact_repo.py
  tests/store/artifact/test_unity_catalog_models_artifact_repo.py
Labels: rn/none, area/artifacts, patch-2.17.0, patch-2.17.1

#13467 Make `set_logged_model_tags` return `None`
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
Labels: rn/none

#13468 Support new Transformers task for llm/v1/embedding
  mlflow/transformers/__init__.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/bug-fix, area/models, patch-2.17.1

#13469 Remove TODO for langchain-databricks testing
  tests/langchain/test_langchain_databricks_integration.py
Labels: rn/none, area/tracking, patch-2.17.1

#13473 Circleci
  .circleci/config.yml
  dev/preview_docs.py
  docs/.docusaurus/DONT-EDIT-THIS-FOLDER
  docs/.docusaurus/client-manifest.json
  docs/.docusaurus/client-modules.js
  docs/.docusaurus/codeTranslations.json
  docs/.docusaurus/docusaurus-plugin-content-blog/default/__plugin.json
  docs/.docusaurus/docusaurus-plugin-content-blog/default/blog-post-list-prop-default.json
  docs/.docusaurus/docusaurus-plugin-content-blog/default/blogMetadata-default.json
  docs/.docusaurus/docusaurus-plugin-content-docs/default/__plugin.json
  docs/.docusaurus/docusaurus-plugin-content-docs/default/p/docs-175.json
  docs/.docusaurus/docusaurus-plugin-content-docs/default/p/docs-category-tutorial-basics-ea4.json
  docs/.docusaurus/docusaurus-plugin-content-docs/default/p/docs-category-tutorial-extras-128.json
  docs/.docusaurus/docusaurus-plugin-content-docs/default/site-docs-intro-md-0e3.json
  docs/.docusaurus/docusaurus-plugin-content-docs/default/site-docs-tutorial-basics-congratulations-md-822.json
  docs/.docusaurus/docusaurus-plugin-content-docs/default/site-docs-tutorial-basics-create-a-blog-post-md-533.json
  docs/.docusaurus/docusaurus-plugin-content-docs/default/site-docs-tutorial-basics-create-a-document-md-1e4.json
  docs/.docusaurus/docusaurus-plugin-content-docs/default/site-docs-tutorial-basics-create-a-page-md-5c8.json
  docs/.docusaurus/docusaurus-plugin-content-docs/default/site-docs-tutorial-basics-deploy-your-site-md-f55.json
  docs/.docusaurus/docusaurus-plugin-content-docs/default/site-docs-tutorial-basics-markdown-features-mdx-18c.json
  docs/.docusaurus/docusaurus-plugin-content-docs/default/site-docs-tutorial-extras-manage-docs-versions-md-dff.json
  docs/.docusaurus/docusaurus-plugin-content-docs/default/site-docs-tutorial-extras-translate-your-site-md-e44.json
  docs/.docusaurus/docusaurus-plugin-content-pages/default/__plugin.json
  docs/.docusaurus/docusaurus-plugin-content-pages/default/site-src-pages-markdown-page-md-393.json
  docs/.docusaurus/docusaurus-plugin-debug/default/__plugin.json
  docs/.docusaurus/docusaurus-plugin-debug/default/p/docusaurus-debug-content-0d5.json
  docs/.docusaurus/docusaurus.config.mjs
  docs/.docusaurus/globalData.json
  docs/.docusaurus/i18n.json
  docs/.docusaurus/registry.js
  docs/.docusaurus/routes.js
  docs/.docusaurus/routesChunkNames.json
  docs/.docusaurus/site-metadata.json
  docs/.docusaurus/site-storage.json
  docs/README.md
  docs/api_reference/build-rdoc.sh
  docs/changed_pages.py
  docs/docs/sample.mdx
  docs/docusaurus.config.ts
Labels: rn/none

#13472 [DEMO] Migrate index.rst
  docs/docs/index.mdx
  docs/rst_to_migrate/index.rst
  docs/src/css/custom.css
Labels: rn/none

#13465 Improve CLI docs - attention about setting MLFLOW_TRACKING_URI
  docs/source/cli.rst
Labels: area/docs, rn/documentation, patch-2.17.1

#13471 Pin torchvision
  mlflow/ml-package-versions.yml
Labels: rn/none

#13449 Improve `model_config` description
  mlflow/pyfunc/__init__.py
Labels: rn/none

#13478 Fixed typo in docs: endpoing -> endpoint
  docs/source/traditional-ml/index.rst
Labels: area/docs, rn/documentation, patch-2.17.1

#13441 Add Genie Spaces to Resources
  mlflow/models/resources.py
  tests/models/test_resources.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/feature, patch-2.17.1

#13488 Use python 3.9 for `torch >= 2.5.0`
  mlflow/ml-package-versions.yml
Labels: rn/none

#13490 Drop pakcage versions that do not provide pre-built binaries for >= Python 3.9
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
Labels: rn/none, py39

#13487 Upgrade `actions/setup-node`
  .github/actions/setup-node/action.yml
Labels: rn/none

#13481 Add UC_Connection to Resources
  mlflow/models/resources.py
  tests/models/test_resources.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/feature, area/tracking, patch-2.17.1

#13491 Adding connections to UC as a dependency
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/feature, area/tracking, autoformat, patch-2.17.1

#13493 Use python 3.9 for autolog tests in pytorch >= 2.5.0
  mlflow/ml-package-versions.yml
Labels: rn/none

#13492 Use `ubuntu 24.04` for spark autologging 3.3.4
  .github/workflows/cross-version-tests.yml
  dev/set_matrix.py
  mlflow/ml-package-versions.yml
Labels: rn/none

#13506 Fix base URL construction for OpenAI flavor
  mlflow/openai/__init__.py
  tests/openai/test_openai_model_export.py
Labels: rn/none, patch-2.17.1

#13508 Update tutorial.rst - add missing '}' in sample curl request
  docs/source/deployment/deploy-model-to-kubernetes/tutorial.rst
Labels: area/docs, rn/none, patch-2.17.1

#13501 Support setting base URL for OpenAI via `OPENAI_BASE_URL`
  mlflow/openai/__init__.py
  mlflow/utils/openai_utils.py
  tests/openai/test_openai_model_export.py
Labels: rn/none, patch-2.17.1

#13510 Downgrade `git2r` to fix `build_doc_r` failure
  mlflow/R/mlflow/.install-deps.R
Labels: rn/none, patch-2.17.1

#13440 Fix signature inference for subclass and Optional dataclasses
  mlflow/models/rag_signatures.py
  mlflow/pyfunc/utils/input_converter.py
  mlflow/types/schema.py
  tests/models/test_signature.py
  tests/pyfunc/test_pyfunc_input_converter.py
Labels: rn/bug-fix, area/models, patch-2.17.1

#13504 Don't throw a warning if the schema is exactly the same
  mlflow/models/dependencies_schemas.py
  tests/models/test_dependencies_schema.py
Labels: rn/none, area/tracking, patch-2.17.1

#13505 Removing the default value in defining model resources
  mlflow/models/resources.py
Labels: rn/none, area/tracking

#13486 Fix code_path handling for LlamaIndex flavor
  mlflow/llama_index/__init__.py
  mlflow/models/utils.py
  tests/llama_index/sample_code/basic_chat_engine.py
  tests/llama_index/sample_code/model_config.yaml
  tests/llama_index/sample_code/query_engine_with_reranker.py
  tests/llama_index/sample_code/with_model_config.py
  tests/llama_index/sample_code/with_model_config_yaml_file.py
  tests/llama_index/test_llama_index_model_export.py
Labels: rn/bug-fix, area/models, patch-2.17.1

#13517 Add model_config param for pyfunc.spark_udf
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/backend.py
  mlflow/pyfunc/scoring_server/__init__.py
  mlflow/pyfunc/scoring_server/wsgi.py
  mlflow/pyfunc/stdin_server.py
  tests/pyfunc/test_spark.py
Labels: rn/feature, area/scoring

#13497 OpenAI Swarm tracing support
  docs/source/_static/images/llms/tracing/openai-swarm-tracing.png
  docs/source/_static/images/logos/openai-swarm-logo.png
  docs/source/llms/openai/autologging.rst
  docs/source/llms/tracing/index.rst
  mlflow/ml-package-versions.yml
  mlflow/openai/__init__.py
  mlflow/openai/_openai_autolog.py
  tests/openai/test_openai_agent_autolog.py
  tests/openai/test_openai_autolog.py
Labels: rn/feature, area/tracking, patch-2.17.1

#13518 Implement `__eq__` for `DatabricksResource` to fix langhchain tests
  mlflow/models/resources.py
Labels: rn/none

#13523 Fix `build-wheel` job
  .github/workflows/build-wheel.yml
  dev/build.py
Labels: rn/none

#13507 Run cross version tests in Python 3.9 (except transformers)
  dev/set_matrix.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  tests/spark/test_spark_model_export.py
Labels: rn/none, py39

#13383 Update Dockerfiles in `tests/db` to use Python 3.9
  tests/db/Dockerfile
  tests/db/Dockerfile.mssql
Labels: rn/none, py39

#13384 Use python 3.9 for examples/mlflow_artifacts
  examples/mlflow_artifacts/Dockerfile
  examples/mlflow_artifacts/Dockerfile.dev
Labels: rn/none, py39

#13385 Use python 3.9 in `tests/projects/test_docker_projects.py`
  tests/projects/test_docker_projects.py
Labels: rn/none, py39

#13532 Remove `--quiet` in `_create_virtualenv` for better debugging
  mlflow/utils/conda.py
  mlflow/utils/virtualenv.py
Labels: rn/none

#13386 Dehardcode python versions in `tests/projects/test_docker_projects.py`
  tests/utils/test_python_env.py
Labels: rn/none, py39

#13533 Pin transformers
  .github/workflows/gateway.yml
  .github/workflows/master.yml
Labels: rn/none

#13516 Fix mlflow.models.predict on serverless
  mlflow/models/python_api.py
  mlflow/models/utils.py
  mlflow/pyfunc/scoring_server/__init__.py
  tests/models/test_python_api.py
Labels: rn/none, patch-2.17.1

#13527 Fix tool span inputs/outputs format in LangChain autolog
  mlflow/langchain/langchain_tracer.py
  tests/langchain/test_langchain_tracer.py
  tests/langchain/test_langgraph.py
Labels: rn/bug-fix, area/tracking, patch-2.17.1

#13289 DSPy flavor docs
  docs/source/_static/images/llms/dspy/dspy-artifacts.png
  docs/source/_static/images/llms/dspy/dspy-integration-architecture.png
  docs/source/_static/images/logos/dspy-logo.png
  docs/source/llms/dspy/index.rst
  docs/source/llms/dspy/notebooks/dspy_quickstart.ipynb
  docs/source/llms/index.rst
Labels: area/docs, rn/documentation, area/models

#13519 Fix update_model_requirements
  docs/source/conf.py
  mlflow/models/__init__.py
  mlflow/models/cli.py
  mlflow/models/model.py
  tests/models/test_cli.py
Labels: rn/none, patch-2.17.1

#13537 Fix failing tests due to transformers 4.46.0
  .github/workflows/examples.yml
  .github/workflows/requirements.yml
Labels: rn/none

#13539 fix recipes test
  mlflow/pyfunc/__init__.py
  mlflow/recipes/recipe.py
Labels: rn/none

#13435 Update langchain autolog
  examples/mlflow-3/langchain_simple.py
  mlflow/langchain/__init__.py
  mlflow/langchain/_langchain_autolog.py
  mlflow/langchain/langchain_tracer.py
  mlflow/utils/uri.py
Labels: rn/none

#13503 Remove warnings during Settings serialization
  docs/source/llms/llama-index/index.rst
  mlflow/llama_index/__init__.py
  mlflow/llama_index/serialize_objects.py
Labels: rn/none, area/tracking, patch-2.17.1

#13535 Keras output conversion for serving purpose
  mlflow/keras/load.py
  tests/keras/test_save.py
Labels: rn/none, area/tracking, patch-2.17.1

#13396 Doc: Fix mlflow-spark JAR URL
  mlflow/spark/__init__.py
Labels: area/docs, rn/none, area/examples, patch-2.17.0, patch-2.17.1

#13538 Support custom chat endpoint without endpoint type set as llm judge
  mlflow/metrics/genai/genai_metric.py
  mlflow/metrics/genai/model_utils.py
  mlflow/pyfunc/model.py
  tests/evaluate/test_evaluation.py
  tests/metrics/genai/test_genai_metrics.py
  tests/metrics/genai/test_model_utils.py
Labels: rn/feature, area/tracking, patch-2.17.1

#13534 Use `tests/resources/example_project/conda.yaml` to use python 3.9
  tests/resources/example_project/conda.yaml
Labels: rn/none, py39

#13528 Llama workflow example
  .pre-commit-config.yaml
  examples/llama_index/workflow/README.md
  examples/llama_index/workflow/Tutorial.ipynb
  examples/llama_index/workflow/data/mlflow_qa_dataset.csv
  examples/llama_index/workflow/data/urls.txt
  examples/llama_index/workflow/install.sh
  examples/llama_index/workflow/pyproject.toml
  examples/llama_index/workflow/static/images/llama_index_workflow_answer_comparison.png
  examples/llama_index/workflow/static/images/llama_index_workflow_empty_experiment.png
  examples/llama_index/workflow/static/images/llama_index_workflow_hybrid_rag_concept.png
  examples/llama_index/workflow/static/images/llama_index_workflow_result_chart.png
  examples/llama_index/workflow/static/images/llama_index_workflow_runs.png
  examples/llama_index/workflow/static/images/llama_index_workflow_trace.png
  examples/llama_index/workflow/workflow/events.py
  examples/llama_index/workflow/workflow/model.py
  examples/llama_index/workflow/workflow/prompts.py
  examples/llama_index/workflow/workflow/workflow.py
  pyproject.toml
Labels: area/docs, rn/none

#13556 Update docker files to use python 3.9
  mlflow/models/docker_utils.py
  tests/resources/dockerfile/Dockerfile_install_mlflow_virtualenv
  tests/resources/dockerfile/Dockerfile_java_flavor
  tests/resources/dockerfile/Dockerfile_no_model_uri
  tests/resources/dockerfile/Dockerfile_sagemaker_virtualenv
Labels: rn/none, py39

#13560 Run skinny tests in Python 3.9
  .github/workflows/master.yml
Labels: rn/none, py39

#13541 Run pyfunc tests in Python 3.9
  .github/workflows/master.yml
  mlflow/models/signature.py
  mlflow/pyfunc/model.py
  mlflow/types/utils.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_spark.py
Labels: rn/none, py39

#13562 Fix dspy tests
  tests/dspy/test_save.py
Labels: rn/none, enable-dev-tests

#13558 Prevent slash commands from being triggered on untrusted PRs
  .github/actions/validate-author/action.yml
  .github/actions/validate-author/index.js
  .github/workflows/autoformat.js
  .github/workflows/autoformat.yml
  .github/workflows/cross-version-test-runner.js
  .github/workflows/cross-version-test-runner.yml
  .github/workflows/rerun.yml
Labels: rn/none

#13559 Run transformers tests in Python 3.9
  dev/set_matrix.py
  mlflow/ml-package-versions.yml
  tests/transformers/test_transformers_autolog.py
Labels: rn/none

#13564 Run models tests on Python 3.9
  .github/workflows/master.yml
  tests/models/test_cli.py
Labels: rn/none, py39

#13571 Run windows tests in Python 3.9
  .github/actions/setup-python/action.yml
  .github/workflows/master.yml
  tests/types/test_schema.py
Labels: rn/none, py39

#13572 Fix `shap.plots.beeswarm` call for https://github.com/shap/shap/issues/3901
  mlflow/models/evaluation/evaluators/shap.py
Labels: rn/none, py39

#13456 Make MLflow run thread-safe
  docs/conftest.py
  mlflow/langchain/api_request_parallel_processor.py
  mlflow/tracking/_model_registry/registry.py
  mlflow/tracking/_model_registry/utils.py
  mlflow/tracking/_tracking_service/registry.py
  mlflow/tracking/_tracking_service/utils.py
  mlflow/tracking/fluent.py
  mlflow/utils/thread_utils.py
  tests/conftest.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/feature, area/tracking

#13545 Run evaluate tests in Python 3.9
  .github/workflows/master.yml
  mlflow/models/evaluation/default_evaluator.py
  mlflow/models/evaluation/evaluators/shap.py
  mlflow/types/utils.py
  tests/evaluate/test_default_evaluator.py
  tests/evaluate/test_evaluation.py
Labels: rn/none, py39

#13578 Run flavors tests on Python 3.9
  .github/workflows/master.yml
Labels: rn/none, py39

#13579 Run `mlflow-recipes` notebooks in Python 3.9
  .circleci/config.yml
Labels: rn/none, py39

#13563 Drop catboost dev test
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#13557 Update `mlflow.evaluate` to link metrics to logged model
  .github/workflows/mlflow-3.yaml
  examples/mlflow-3/evaluate_example.py
  mlflow/data/evaluation_dataset.py
  mlflow/data/huggingface_dataset.py
  mlflow/data/numpy_dataset.py
  mlflow/data/pandas_dataset.py
  mlflow/data/spark_dataset.py
  mlflow/data/tensorflow_dataset.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/store/artifact/utils/models.py
Labels: rn/none

#13587 Run recipes windows tests in Python 3.9
  .github/workflows/recipe.yml
Labels: rn/none, py39

#13581 Update MLflow project examples to use Python 3.9
  tests/resources/example_mlflow_1x_sklearn_model/MLmodel
  tests/resources/example_mlflow_1x_sklearn_model/conda.yaml
  tests/resources/example_mlflow_1x_sklearn_model/model.pkl
  tests/resources/example_mlflow_1x_sklearn_model/python_env.yaml
  tests/resources/example_mlflow_1x_sklearn_model/requirements.txt
  tests/resources/example_virtualenv_conda_project/conda.yaml
  tests/resources/example_virtualenv_conda_project/entrypoint.py
  tests/resources/example_virtualenv_no_python_env/entrypoint.py
  tests/resources/example_virtualenv_no_python_env/python_env.yaml
  tests/resources/example_virtualenv_no_python_env/requirements.txt
  tests/resources/example_virtualenv_project/entrypoint.py
  tests/resources/example_virtualenv_project/python_env.yaml
  tests/resources/example_virtualenv_project/requirements.txt
Labels: rn/none, py39
