Repository mlflow/mlflow, pull requests merged in 2024-11, with the labels that each got.

#13546 Replace `logger.warning` with `sys.stdout.write` to log run and experiment information
  mlflow/tracking/_tracking_service/client.py
Labels: rn/none, area/tracking

#13626 Remove `mlflow/utils/insecure_hash.py`
  mlflow/data/digest_utils.py
  mlflow/data/evaluation_dataset.py
  mlflow/pyfunc/__init__.py
  mlflow/store/tracking/file_store.py
  mlflow/utils/conda.py
  mlflow/utils/environment.py
  mlflow/utils/insecure_hash.py
  tests/evaluate/test_evaluation.py
  tests/projects/test_projects_cli.py
  tests/resources/data/dataset.py
  tests/store/tracking/test_file_store.py
Labels: rn/none, py39

#13460 Enforce explicit `Optional` type annotation if default value is None
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  mlflow/data/pyfunc_dataset_mixin.py
  mlflow/langchain/utils/chat.py
  mlflow/metrics/base.py
  mlflow/metrics/genai/prompts/v1.py
  mlflow/utils/autologging_utils/safety.py
Labels: rn/none

#13630 updates pre-commit version and fixes stage names
  .devcontainer/requirements.txt
  .pre-commit-config.yaml
  requirements/lint-requirements.txt
Labels: rn/none

#13625 Remove PEP585-supported check in type schema enforcement from type hints
  mlflow/types/utils.py
Labels: rn/none, py39

#13646 Fix Docusaurus CircleCI
  .circleci/config.yml
Labels: rn/none

#13647 Fix Docusaurus R CircleCI
  docs/api_reference/build-rdoc.sh
  mlflow/R/mlflow/document.R
Labels: rn/none

#13419 Make autolog enabling / disabling thread-safe
  mlflow/pytorch/_lightning_autolog.py
  mlflow/pytorch/_pytorch_autolog.py
  mlflow/statsmodels/__init__.py
  mlflow/tracking/fluent.py
  mlflow/utils/autologging_utils/__init__.py
  tests/autologging/test_autologging_behaviors_unit.py
Labels: rn/feature, area/tracking

#13649 Fix LightGBM cross version tests
  tests/lightgbm/test_lightgbm_autolog.py
Labels: rn/none, enable-dev-tests, patch-2.17.3

#13549 Remove code using `spark.client._builder` in new version DBconnect
  mlflow/utils/databricks_utils.py
Labels: rn/none, area/scoring

#13631 [Docs] Updating the docs for model config in logging model as code
  mlflow/models/model_config.py
Labels: rn/documentation, area/tracking, patch-2.17.3

#13548 Add runtime version check and UDF sandbox mlflow version check for spark_udf
  mlflow/pyfunc/__init__.py
  mlflow/utils/databricks_utils.py
  tests/pyfunc/test_spark.py
  tests/utils/test_databricks_utils.py
Labels: rn/none, area/scoring

#13657 add monkeypatching for setting env var in test deployment
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  tests/autologging/test_autologging_safety_unit.py
  tests/deployments/test_deployments.py
  tests/models/test_wheeled_model.py
  tests/pyfunc/test_spark.py
  tests/recipes/test_pipeline.py
  tests/store/artifact/test_azure_blob_artifact_repo.py
  tests/store/artifact/test_hdfs_artifact_repo.py
Labels: rn/none, area/deployments

#13655 [ML-47140] Create basic folder structure
  docs/docs/auth/index.mdx
  docs/docs/community-model-flavors/index.mdx
  docs/docs/deep-learning/index.mdx
  docs/docs/deployment/index.mdx
  docs/docs/docker/index.mdx
  docs/docs/getting-started/index.mdx
  docs/docs/index.mdx
  docs/docs/introduction/index.mdx
  docs/docs/llms/index.mdx
  docs/docs/model-evaluation/index.mdx
  docs/docs/model-registry/index.mdx
  docs/docs/models/index.mdx
  docs/docs/new-features/index.mdx
  docs/docs/plugins/index.mdx
  docs/docs/projects/index.mdx
  docs/docs/quickstart-drilldown/index.mdx
  docs/docs/recipes/index.mdx
  docs/docs/sample.mdx
  docs/docs/search-experiments/index.mdx
  docs/docs/search-runs/index.mdx
  docs/docs/system-metrics/index.mdx
  docs/docs/tracking/index.mdx
  docs/docs/traditional-ml/index.mdx
  docs/docs/tutorials-and-examples/index.mdx
Labels: rn/none

#13661 Bump maximum supported pyarrow version to 18
  pyproject.release.toml
  pyproject.toml
  requirements/core-requirements.txt
  requirements/core-requirements.yaml
Labels: rn/none

#13667 Fix models artifact repository selection
  mlflow/store/artifact/models_artifact_repo.py
Labels: rn/none

#13584 Add environment variable detection in model logging
  mlflow/environment_variables.py
  mlflow/models/model.py
  mlflow/utils/model_utils.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/utils/test_model_utils.py
Labels: rn/feature

#13663 fix Enable global-variable-not-assigned (PLW0602)#13634
  mlflow/deployments/utils.py
  mlflow/gateway/utils.py
  mlflow/legacy_databricks_cli/configure/provider.py
  mlflow/spark/autologging.py
  mlflow/tracking/_model_registry/utils.py
  mlflow/tracking/_tracking_service/utils.py
  pyproject.toml
  tests/db/test_tracking_operations.py
Labels: rn/none

#13639 Log params to model in sklearn autolog
  examples/mlflow-3/sklearn_autolog.py
  mlflow/sklearn/__init__.py
Labels: rn/none

#13666 Fix scatter plots to render 0-valued metrics
  mlflow/server/js/src/experiment-tracking/components/runs-charts/components/RunsScatterPlot.tsx
Labels: rn/none

#13660 Adding to_dict as a method for model config
  mlflow/models/model_config.py
  tests/models/test_model_config.py
Labels: rn/feature, area/tracking, patch-2.17.3

#13665 Add new metric attributes in `_get_metrics_dataframe_schema`
  mlflow/evaluation/utils.py
Labels: rn/none

#13607 Support loading a model from `runs:/<run_id>/<artifact_path>`
  .github/workflows/mlflow-3.yaml
  examples/mlflow-3/load_model_from_runs_uri.py
  mlflow/models/model.py
  mlflow/store/artifact/runs_artifact_repo.py
  mlflow/tracking/client.py
Labels: rn/none

#13674 Drop Python 3.8 in dev-env-setup.sh
  dev/dev-env-setup.sh
  dev/test-dev-env-setup.sh
Labels: rn/none

#13677 Add Tomu Hirata to the mlflow members
  .github/workflows/require-core-maintainer-approval.js
  .github/workflows/team-review.yml
  CONTRIBUTING.md
  README.rst
Labels: rn/none

#13672 Fix LangChain autologging thread-safety issue
  mlflow/langchain/_langchain_autolog.py
  tests/langchain/sample_code/langgraph_diy.py
  tests/langchain/sample_code/langgraph_prebuilt.py
  tests/langchain/test_langchain_autolog.py
  tests/langchain/test_langgraph.py
Labels: rn/bug-fix, area/tracking, patch-2.17.3

#13680 Remove stale bot
  .github/stale.yml
  .github/workflows/stale.yml
Labels: rn/none

#13684 Improve sparkML log_model doc
  mlflow/spark/__init__.py
Labels: area/docs, rn/documentation

#13688 Remove status badge of stale job
  README.rst
Labels: rn/none

#13689 Remove failing `conda remove`
  .github/workflows/examples.yml
Labels: rn/none

#13553 Remove dynamic mocking in `test_sqlalchemy_store.py/_create_trace` method.
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none, area/tracking, area/server-infra

#13669 Add environment_variables.txt file documentation
  docs/source/models.rst
  examples/sklearn_logistic_regression/train.py
  mlflow/utils/model_utils.py
Labels: rn/none

#13652 Fix langchain pyfunc predict input conversion
  mlflow/langchain/api_request_parallel_processor.py
  mlflow/langchain/utils/chat.py
  tests/langchain/test_chat_utils.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/bug-fix, enable-dev-tests, patch-2.17.3

#13692 Unflake `test_system_metrics_monitor_with_multi_node`
  tests/system_metrics/test_system_metrics_logging.py
Labels: rn/none

#13658 Support UC Table Dependencies
  mlflow/models/resources.py
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/models/test_resources.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/none, area/tracking, patch-2.17.3

#13662 Enable merge queue for pull request merge
  .github/workflows/lint.yml
  .github/workflows/protect.yml
Labels: rn/none

#13695 Improved the error message when model file not found
  mlflow/models/utils.py
  tests/models/test_utils.py
Labels: rn/none

#13719 Fix the old error message in assertion for model code util
  tests/langchain/test_langchain_model_export.py
Labels: rn/none

#13715 [1/x] Support custom headers and proxy URL for LLM-as-a-Judge model
  mlflow/metrics/genai/genai_metric.py
  mlflow/metrics/genai/metric_definitions.py
  mlflow/metrics/genai/model_utils.py
  mlflow/openai/api_request_parallel_processor.py
  tests/metrics/genai/test_genai_metrics.py
  tests/metrics/genai/test_model_utils.py
Labels: rn/feature, area/tracking, patch-2.17.3

#13693 Fix Langchain Dependency Detection
  mlflow/langchain/databricks_dependencies.py
Labels: rn/none, area/tracking, patch-2.17.3

#13720 Fix `mlflow.pyfunc.load_model(f"models:/<name>/<version>")`
  mlflow/store/artifact/utils/models.py
Labels: rn/none

#13721 Avoid global import of fastapi in Gateway Adapters.
  mlflow/gateway/app.py
  mlflow/gateway/exceptions.py
  mlflow/gateway/providers/ai21labs.py
  mlflow/gateway/providers/anthropic.py
  mlflow/gateway/providers/base.py
  mlflow/gateway/providers/bedrock.py
  mlflow/gateway/providers/cohere.py
  mlflow/gateway/providers/huggingface.py
  mlflow/gateway/providers/mistral.py
  mlflow/gateway/providers/mlflow.py
  mlflow/gateway/providers/mosaicml.py
  mlflow/gateway/providers/openai.py
  mlflow/gateway/providers/palm.py
  mlflow/gateway/providers/togetherai.py
  tests/gateway/providers/test_ai21labs.py
  tests/gateway/providers/test_anthropic.py
  tests/gateway/providers/test_cohere.py
  tests/gateway/providers/test_huggingface.py
  tests/gateway/providers/test_mistral.py
  tests/gateway/providers/test_mlflow.py
  tests/gateway/providers/test_mosaicml.py
  tests/gateway/providers/test_openai.py
  tests/gateway/providers/test_palm.py
  tests/gateway/providers/test_togetherai.py
Labels: rn/none, area/tracking, patch-2.17.3

#13727 Pass `model_id` to `_get_args_with_mlflow_tracer`
  examples/mlflow-3/langchain_simple.py
  mlflow/langchain/_langchain_autolog.py
Labels: rn/none

#13712 Update deprecation annotation to support classes
  mlflow/utils/annotations.py
  tests/utils/test_annotations.py
Labels: rn/none, area/build

#13711 Fixing mismatch type error by moving evaluation data and labels to the correct device (GPU/CPU) for model inference.
  examples/pytorch/mnist_tensorboard_artifact.py
Labels: rn/none, area/examples, patch-2.17.3, v2.17.3

#13722 Fix async logging batch splitting validation rule
  mlflow/utils/async_logging/async_logging_queue.py
  tests/utils/test_async_logging_queue.py
Labels: rn/bug-fix, area/tracking, v2.18.0

#13678 Remove log_inputs_outputs in LangChain autologging
  docs/source/llms/langchain/autologging.rst
  examples/langchain/chain_autolog.py
  mlflow/langchain/__init__.py
  mlflow/langchain/_langchain_autolog.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/autologging_utils/config.py
  tests/evaluate/test_evaluation.py
Labels: rn/none, area/tracking

#13723 Remove `Willingness to contribute` section in buG report templates
  .github/ISSUE_TEMPLATE/bug_report_template.yaml
  .github/ISSUE_TEMPLATE/ui_bug_report_template.yaml
Labels: rn/none, v2.18.0

#13702 Add doc on how to use code paths for custom library
  docs/source/model/dependencies.rst
Labels: area/docs, rn/documentation

#13703 Drop optional field in ColSpec
  docs/source/conf.py
  docs/source/python_api/mlflow.types.rst
  mlflow/types/schema.py
Labels: rn/none

#13734 Fix autoformat
  .github/workflows/autoformat.js
  .github/workflows/autoformat.yml
Labels: rn/none

#13735 Rename `getPullInformation` to `getPullInfo`
  .github/workflows/autoformat.js
Labels: rn/none

#13733 Add a custom linter for preventing global imports in certain files
  dev/clint/src/clint/__init__.py
  dev/clint/src/clint/config.py
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  pyproject.toml
Labels: rn/none, area/build, v2.17.3

#13736 Add graphQL types back
  .github/workflows/protos.yml
  mlflow/server/js/package.json
  mlflow/server/js/src/graphql/autogenerated_schema.gql
Labels: rn/none

#13737 Fix `_is_at_top_level`
  dev/clint/src/clint/linter.py
Labels: rn/none

#13739 Fix typo in `step3-load-model.rst`
  docs/source/getting-started/registering-first-model/step3-load-model.rst
Labels: rn/none

#13742 Revert "Fix langchain pyfunc predict input conversion (#13652)"
  mlflow/langchain/api_request_parallel_processor.py
  mlflow/langchain/utils/chat.py
  tests/langchain/test_chat_utils.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/none

#13717 [2/x] Support non-OAI providers as LLM judges for GenAI metrics.
  mlflow/gateway/provider_registry.py
  mlflow/gateway/providers/anthropic.py
  mlflow/gateway/providers/bedrock.py
  mlflow/gateway/providers/cohere.py
  mlflow/gateway/providers/mistral.py
  mlflow/gateway/providers/togetherai.py
  mlflow/metrics/genai/model_utils.py
  tests/metrics/genai/test_genai_metrics.py
  tests/metrics/genai/test_model_utils.py
Labels: rn/feature, area/tracking, v2.18.0, v2.17.3

#13708 Encourage users to explicitly pass resources when logging langchain models with dependencies
  docs/source/llms/langchain/index.rst
  mlflow/langchain/__init__.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/none, area/models, autoformat, patch-2.17.3, v2.17.3

#13730 Add docstring warnings for upcoming changes to ChatModel
  docs/source/llms/chat-model-guide/index.rst
  mlflow/pyfunc/model.py
  mlflow/types/llm.py
  tests/pyfunc/test_chat_model.py
Labels: rn/documentation

#13743 Fix example ci
  examples/pytorch/AxHyperOptimizationPTL/conda.yaml
  examples/pytorch/AxHyperOptimizationPTL/python_env.yaml
  examples/pytorch/BertNewsClassification/conda.yaml
  examples/pytorch/BertNewsClassification/python_env.yaml
  examples/pytorch/IterativePruning/conda.yaml
  examples/pytorch/IterativePruning/python_env.yaml
Labels: rn/none, area/examples, area/build

#13745 Fix test_autolog_text_vec_model test
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/none, area/tracking, area/build, enable-dev-tests

#13755 Fix DSPy autologging for recent released version
  mlflow/dspy/autolog.py
  tests/dspy/test_dspy_autolog.py
Labels: rn/none, area/models, enable-dev-tests, v2.18.0

#13632 Auto opt-in DatabricksSDKModelsArtifactRepository for SEG enabled databricks workspaces.
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/protos/databricks_uc_registry_service.proto
  mlflow/protos/databricks_uc_registry_service_pb2.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/artifact/unity_catalog_models_artifact_repo.py
  mlflow/utils/_unity_catalog_utils.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/store/artifact/test_databricks_sdk_models_artifact_repo.py
  tests/store/artifact/test_unity_catalog_models_artifact_repo.py
  tests/store/lineage/test_downstream_lineage.py
Labels: rn/none, area/model-registry, v2.18.0

#13761 Do not skip `test_schema_is_up_to_date`
  tests/db/schemas/mssql.sql
  tests/db/schemas/mysql.sql
  tests/db/schemas/postgresql.sql
  tests/db/schemas/sqlite.sql
  tests/db/test_schema.py
Labels: rn/none, v2.18.0

#13705 Fix typo on new features page
  docs/source/new-features/index.rst
Labels: rn/none

#13699 Support passing extra envs to mlflow.models.predict
  mlflow/models/cli.py
  mlflow/models/python_api.py
  mlflow/pyfunc/backend.py
  mlflow/rfunc/backend.py
  mlflow/utils/conda.py
  mlflow/utils/environment.py
  tests/models/test_python_api.py
Labels: rn/none

#13764 Enforce using `sys.executable` when running mlflow CLI in a subprocess
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  tests/models/test_cli.py
  tests/test_cli.py
Labels: rn/none

#13741 Cascade deletes to datasets when deleting experiments
  mlflow/store/db_migrations/versions/0584bdc529eb_add_cascading_deletion_to_datasets_from_experiments.py
  mlflow/store/tracking/dbmodels/models.py
  tests/db/Dockerfile.mssql
  tests/db/compose.yml
  tests/db/schemas/mssql.sql
  tests/db/schemas/mysql.sql
  tests/db/schemas/postgresql.sql
  tests/db/schemas/sqlite.sql
  tests/resources/db/latest_schema.sql
  tests/store/tracking/test_sqlalchemy_store_schema.py
  tests/test_cli.py
Labels: rn/bug-fix, v2.18.0, v2.17.3

#13767 Cherry-pick #13741 to branch-2.18
  mlflow/store/db_migrations/versions/0584bdc529eb_add_cascading_deletion_to_datasets_from_experiments.py
  mlflow/store/tracking/dbmodels/models.py
  tests/db/Dockerfile.mssql
  tests/db/compose.yml
  tests/db/schemas/mssql.sql
  tests/db/schemas/mysql.sql
  tests/db/schemas/postgresql.sql
  tests/db/schemas/sqlite.sql
  tests/resources/db/latest_schema.sql
  tests/store/tracking/test_sqlalchemy_store_schema.py
  tests/test_cli.py
Labels: rn/bug-fix

#13769 Do not skip `test_schema_is_up_to_date` (#13761)
  tests/db/schemas/mssql.sql
  tests/db/schemas/mysql.sql
  tests/db/schemas/postgresql.sql
  tests/db/schemas/sqlite.sql
  tests/db/test_schema.py
Labels: rn/none

#13744 Fix langchain inputs conversion
  docs/source/llms/langchain/index.rst
  mlflow/environment_variables.py
  mlflow/langchain/api_request_parallel_processor.py
  mlflow/langchain/utils/chat.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/none, enable-dev-tests, v2.18.0, v2.17.3

#13676 Fix: remove extraneous quotation mark from URL in docstring
  mlflow/models/python_api.py
Labels: area/docs, rn/none, patch-2.17.3

#13706 Adds "Tutorial: Getting Started with ChatModel" docs page
  docs/source/_static/images/llms/chat-model-intro/interface_1.png
  docs/source/llms/chat-model-intro/index.rst
  docs/source/llms/index.rst
Labels: area/docs, rn/documentation, autoformat, patch-2.17.3, v2.18.0

#13762 Replace model names table for MLflow Gateway with simpler checkbox
  docs/source/llms/deployments/index.rst
  docs/source/llms/index.rst
Labels: area/docs, rn/none

#13773 Attempt to unflake system metrics test for Windows
  tests/system_metrics/test_system_metrics_logging.py
Labels: rn/none, area/build

#13718 Backtick delta table name when loading
  mlflow/data/delta_dataset_source.py
  mlflow/data/spark_delta_utils.py
  mlflow/utils/string_utils.py
Labels: rn/none, v2.18.0

#13775 Retry on `ConnectionResetError` in `dev/update_ml_package_versions.py`
  dev/update_ml_package_versions.py
Labels: rn/none

#13786 Add quick comparison table between ChatModel and PythonModel
  docs/source/llms/chat-model-guide/index.rst
  docs/source/llms/chat-model-intro/chat-model-vs-pyfunc-table.rst
  docs/source/llms/chat-model-intro/index.rst
  docs/source/llms/notebooks/chat-model-tool-calling.ipynb
  mlflow/pyfunc/model.py
Labels: area/docs, rn/none, v2.18.0

#13787 Update Transformer's chatbot tutorial not to conflict with ChatModel tutorials
  docs/source/llms/transformers/tutorials/conversational/pyfunc-chat-model.ipynb
Labels: area/docs, rn/none, v2.18.0

#13800 Support setting retriever schema for DSPy model within constructor
  mlflow/dspy/callback.py
  mlflow/dspy/load.py
  mlflow/dspy/save.py
  mlflow/langchain/__init__.py
  mlflow/models/dependencies_schemas.py
  mlflow/pyfunc/__init__.py
  tests/dspy/test_dspy_autolog.py
Labels: rn/feature, area/tracking, v2.18.0

#13798 Suppress tracing for internal prediction during DSPy logging/loading
  mlflow/dspy/load.py
  mlflow/dspy/save.py
Labels: rn/none, area/models, v2.18.0

#13802 Handle raw response in openai autolog
  mlflow/openai/_openai_autolog.py
  tests/openai/test_openai_autolog.py
Labels: rn/bug-fix, v2.18.0

#13801 Introduce Gemini tracing
  conftest.py
  dev/update_ml_package_versions.py
  docs/source/_static/images/llms/gemini/gemini-tracing.png
  docs/source/_static/images/logos/google-gemini-logo.svg
  docs/source/llms/tracing/index.rst
  docs/source/python_api/mlflow.gemini.rst
  examples/gemini/tracing.py
  mlflow/__init__.py
  mlflow/gemini/__init__.py
  mlflow/gemini/autolog.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  tests/gemini/test_gemini_autolog.py
Labels: area/docs, rn/feature, area/examples, v2.18.0

#13807 Dspy tracing doc
  docs/source/_static/images/llms/dspy/dspy-trace.png
  docs/source/llms/dspy/index.rst
  docs/source/llms/dspy/notebooks/dspy_quickstart.ipynb
  docs/source/llms/tracing/index.rst
Labels: area/docs, rn/none, v2.18.0

#13585 LiteLLM tracing
  conftest.py
  docs/source/_static/images/llms/litellm/litellm-tracing.png
  docs/source/_static/images/logos/litellm-logo.jpg
  docs/source/llms/tracing/index.rst
  docs/source/python_api/mlflow.litellm.rst
  mlflow/__init__.py
  mlflow/litellm/__init__.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/utils/autologging_utils/__init__.py
  tests/litellm/conftest.py
  tests/litellm/test_litellm_autolog.py
Labels: rn/feature, area/tracking, v2.18.0

#13785 Remove height limitation
  mlflow/server/js/src/experiment-tracking/components/ArtifactView.css
Labels: rn/none, area/artifacts, v2.18.0

#13513 Update databricks deployments to support AI gateway & additional update endpoints
  mlflow/deployments/databricks/__init__.py
  tests/deployments/databricks/test_databricks.py
Labels: rn/feature, integrations/databricks, area/deployments

#13820 Fetch PR in `patch.js` to check the latest PR description
  .github/workflows/patch.js
Labels: rn/none

#13818 Make tracing stable
  docs/source/llms/index.rst
  docs/source/llms/tracing/index.rst
  mlflow/tracing/fluent.py
  mlflow/tracking/client.py
Labels: area/docs, rn/none, v2.18.0

#13811 Avoid testing unstable versions in cross-version tests
  dev/set_matrix.py
  dev/tests/test_set_matrix.py
  dev/tests/test_update_ml_package_versions.py
  dev/update_ml_package_versions.py
Labels: rn/none

#13823 Use in-memory figure object
  examples/evaluation/evaluate_with_custom_metrics_comprehensive.py
  mlflow/fastai/callback.py
  tests/evaluate/test_default_evaluator.py
  tests/models/test_artifacts.py
Labels: rn/none

#13835 Add FAQ about trace UI issue
  docs/source/llms/tracing/index.rst
Labels: area/docs, rn/none, v2.18.1

#13821 Support saving all langchain runnables using code-based logging
  mlflow/models/model.py
Labels: rn/bug-fix, v2.18.1

#13836 Bust browser cache when mlflow version changes
  mlflow/server/js/src/shared/web-shared/model-trace-explorer/ModelTraceExplorerFrameRenderer.tsx
Labels: rn/none

#13766 Any type support
  docs/source/python_api/mlflow.types.rst
  mlflow/models/utils.py
  mlflow/types/schema.py
  mlflow/types/utils.py
  mlflow/utils/proto_json_utils.py
  tests/langchain/test_langchain_model_export.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
  tests/types/test_schema.py
Labels: rn/feature, area/models

#13841 [ML-47650] Migrate Getting Started page
  docs/docs/getting-started/index.mdx
  docs/rst_to_migrate/getting-started/index.rst
Labels: rn/none

#13842 [ML-47650] Migrate Running Notebooks page
  docs/docs/getting-started/running-notebooks/index.mdx
  docs/rst_to_migrate/getting-started/running-notebooks/index.rst
Labels: rn/none

#13793 [2/x] Support auto+manual tracing - LlamaIndex
  mlflow/llama_index/tracer.py
  tests/llama_index/test_llama_index_tracer.py
Labels: rn/feature, area/tracking

#13844 Pin pydantic to <2.10 in LangChain test
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#13847 Update ruff to 0.7.4
  mlflow/openai/_openai_autolog.py
  mlflow/pytorch/_pytorch_autolog.py
  pyproject.toml
  requirements/lint-requirements.txt
Labels: rn/none

#13795 [3/x] Support auto+manual tracing - DSPy
  mlflow/dspy/callback.py
  tests/dspy/test_dspy_autolog.py
Labels: rn/feature, area/tracking

#13849 Clean up unnecessary statements/expressions in abstract methods
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  mlflow/data/dataset.py
  mlflow/deployments/plugin_manager.py
  mlflow/gateway/providers/base.py
  mlflow/models/evaluation/base.py
  mlflow/models/flavor_backend.py
  mlflow/projects/backend/abstract_backend.py
  mlflow/tracking/registry.py
  mlflow/types/schema.py
Labels: rn/none

#13848 Support colored log and highlight the lack of signature
  mlflow/models/model.py
  mlflow/utils/logging_utils.py
Labels: rn/none

#13850 Fix langchain agent executor tests
  mlflow/ml-package-versions.yml
  tests/langchain/sample_code/openai_agent.py
  tests/langchain/test_langchain_autolog.py
  tests/langchain/test_langchain_tracer.py
Labels: rn/none, area/build

#13782 Introduce ChatCompletionRequest, ChatCompletionResponse, and ChatCompletionChunk and update ChatModel signature
  docs/source/llms/chat-model-guide/index.rst
  docs/source/llms/chat-model-intro/index.rst
  mlflow/langchain/output_parsers.py
  mlflow/models/rag_signatures.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/loaders/chat_model.py
  mlflow/pyfunc/model.py
  mlflow/types/llm.py
  tests/langchain/test_langchain_output_parsers.py
  tests/pyfunc/test_chat_model.py
  tests/pyfunc/test_chat_model_validation.py
Labels: rn/breaking-change, area/models

#13858 Allow changing max_workers for built-in LLM-as-a-Judge metrics
  mlflow/metrics/genai/metric_definitions.py
Labels: rn/bug-fix, area/models, v2.18.1

#13859 Raise an explicit error when 'databricks-agents' is missing
  mlflow/models/evaluation/base.py
  tests/evaluate/test_evaluation.py
Labels: rn/none, area/models, v2.18.1

#13864 [ML-47650] Migrate registering first model folder pages
  docs/docs/getting-started/intro-quickstart/notebooks/tracking_quickstart.ipynb
  docs/docs/getting-started/registering-first-model/index.mdx
  docs/docs/getting-started/registering-first-model/step1-register-model/index.mdx
  docs/docs/getting-started/registering-first-model/step2-explore-registered-model/index.mdx
  docs/docs/getting-started/registering-first-model/step3-load-model/index.mdx
  docs/rst_to_migrate/getting-started/registering-first-model/index.rst
  docs/rst_to_migrate/getting-started/registering-first-model/step1-register-model.rst
  docs/rst_to_migrate/getting-started/registering-first-model/step2-explore-registered-model.rst
  docs/rst_to_migrate/getting-started/registering-first-model/step3-load-model.rst
Labels: rn/none

#13854 Validate `username` and `password` are not empty
  mlflow/server/auth/__init__.py
  tests/server/auth/auth_test_utils.py
  tests/server/auth/test_auth.py
Labels: rn/none

#13846 Anytype: update infer signature for input example and doc
  docs/source/llms/chat-model-intro/index.rst
  docs/source/model/signatures.rst
  mlflow/models/signature.py
  mlflow/types/schema.py
Labels: rn/none

#13866 [ML-47987] Migrate system metrics
  docs/docs/system-metrics/index.mdx
  docs/rst_to_migrate/system-metrics/index.rst
Labels: rn/none

#13870 Use `uv pip install` to install lint requirements faster
  .github/workflows/lint.yml
Labels: rn/none

#13863 Add doc for different LLM providers for LLM-as-a-Judge metrics
  docs/source/llms/llm-evaluate/index.rst
Labels: area/docs, rn/none, v2.18.1

#13828 Add an API for adding tags to an active trace.
  docs/source/_static/images/llms/tracing/trace-session-id.png
  docs/source/llms/tracing/index.rst
  mlflow/__init__.py
  mlflow/langchain/langchain_tracer.py
  mlflow/tracing/fluent.py
  tests/tracing/test_fluent.py
Labels: rn/feature, area/tracking, v2.18.1

#13869 Add a guide for how to find, fix, and ignore typos
  .pre-commit-config.yaml
  dev/typos.md
  dev/typos.sh
Labels: rn/none

#13871 [ML-47988] Migrate Deployment page
  docs/docs/deployment/deploy-model-locally/index.mdx
  docs/docs/deployment/deploy-model-to-sagemaker/index.mdx
  docs/docs/deployment/index.mdx
  docs/rst_to_migrate/deployment/deploy-model-locally.rst
  docs/rst_to_migrate/deployment/deploy-model-to-sagemaker.rst
  docs/rst_to_migrate/deployment/index.rst
  docs/src/components/Card/card.module.css
Labels: rn/none

#13873 [ML-47988] migrate deploy-model-to-kubernetes pages
  docs/docs/deployment/deploy-model-to-kubernetes/index.mdx
  docs/docs/deployment/deploy-model-to-kubernetes/tutorial/index.mdx
  docs/rst_to_migrate/deployment/deploy-model-to-kubernetes/index.rst
  docs/rst_to_migrate/deployment/deploy-model-to-kubernetes/tutorial.rst
Labels: rn/none

#13882 Improve command to install mlflow from PR
  .github/workflows/advice.js
Labels: rn/none

#13857 Update ChatCompletionRequest and ChatCompletionResponse to use AnyType and allow more function types
  mlflow/types/llm.py
  tests/pyfunc/test_chat_model.py
  tests/pyfunc/test_chat_model_validation.py
Labels: rn/none, area/models

#13883 Add API for disabling trace display
  mlflow/tracing/__init__.py
  mlflow/tracing/display/__init__.py
  mlflow/tracing/display/display_handler.py
  tests/tracing/display/test_ipython.py
Labels: rn/none

#13884 [ML-48051] Migrate deep learning pages
  docs/docs/deep-learning/index.mdx
  docs/docs/llms/index.mdx
  docs/rst_to_migrate/deep-learning/index.rst
  docs/src/components/Card/index.tsx
Labels: rn/none

#13886 [ML-48051] Migrate deep learning Keras page
  docs/docs/deep-learning/keras/index.mdx
  docs/docs/deep-learning/keras/quickstart/quickstart_keras.ipynb
  docs/rst_to_migrate/deep-learning/keras/index.rst
Labels: rn/none

#13887 [ML-48051] Migrate deep learning Tensorflow pages
  docs/docs/deep-learning/tensorflow/guide/index.mdx
  docs/docs/deep-learning/tensorflow/index.mdx
  docs/docs/deep-learning/tensorflow/quickstart/quickstart_tensorflow.ipynb
  docs/rst_to_migrate/deep-learning/tensorflow/guide/index.rst
Labels: rn/none

#13893 [ML-48053] Migrate traditional-ml page
  docs/docs/models/index.mdx
  docs/docs/traditional-ml/index.mdx
  docs/rst_to_migrate/traditional-ml/index.rst
Labels: rn/none

#13827 Fix spark_udf conditional check on remote spark-connect client or Databricks Serverless
  mlflow/pyfunc/__init__.py
Labels: rn/bug-fix, area/scoring, v2.18.1

#13908 [ML-48053] Migrate traditional-ml/serving-multiple-models-with-pyfunc pages
  docs/docs/traditional-ml/serving-multiple-models-with-pyfunc/index.mdx
  docs/docs/traditional-ml/serving-multiple-models-with-pyfunc/notebooks/MME_Tutorial.ipynb
  docs/rst_to_migrate/traditional-ml/serving-multiple-models-with-pyfunc/index.rst
Labels: rn/none

#13878 Refresh README.md
  .github/workflows/cross-version-testing.md
  .pre-commit-config.yaml
  README.md
  README.rst
  README_SKINNY.md
  README_SKINNY.rst
  dev/README.md
  dev/build.py
  dev/pyproject.py
  examples/multistep_workflow/main.py
  pyproject.release.toml
  pyproject.skinny.toml
  pyproject.toml
  requirements/lint-requirements.txt
Labels: area/docs, rn/none, v2.18.1

#13906 Fix type hint for _validate
  mlflow/models/evaluation/validation.py
Labels: rn/none

#13915 Pin httpx for openai test
  mlflow/ml-package-versions.yml
Labels: rn/none, area/tracking, v2.18.1

#13918 Pin httpx for openai test
  mlflow/ml-package-versions.yml
Labels: rn/none, v2.18.1

#13912 Fix slow infer type
  mlflow/types/schema.py
  mlflow/types/utils.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
  tests/types/test_schema.py
Labels: rn/none, v2.18.1
