Repository mlflow/mlflow, pull requests merged in 2025-09, with the labels that each got.

#17325 Tracing: export opentelemetry metrics with span-level statistics
  .github/workflows/tracing.yaml
  docs/docs/genai/tracing/prod-tracing.mdx
  mlflow/tracing/processor/base_mlflow.py
  mlflow/tracing/processor/mlflow_v3.py
  mlflow/tracing/processor/otel.py
  mlflow/tracing/processor/otel_metrics_mixin.py
  mlflow/tracing/provider.py
  mlflow/tracing/utils/__init__.py
  mlflow/tracing/utils/otlp.py
  tests/tracing/processor/test_mlflow_v3_processor.py
  tests/tracing/processor/test_otel_metrics.py
  tests/tracing/test_provider.py
Labels: rn/feature, area/tracing, rn/highlight

#17252 Add MLFLOW_DEPLOYMENT_CLIENT_HTTP_REQUEST_TIMEOUT environment variable
  mlflow/deployments/mlflow/__init__.py
  mlflow/environment_variables.py
  tests/deployments/mlflow/test_mlflow.py
Labels: rn/feature, area/scoring

#17505 Add MLFLOW_ENABLE_OTLP_EXPORTER environment variable
  mlflow/environment_variables.py
  mlflow/tracing/utils/otlp.py
  tests/tracing/utils/test_otlp.py
Labels: rn/feature, area/tracing, v2.22.3

#17492 Migrate binary tool installation to unified Python system
  .github/actions/setup-python/action.yml
  .github/workflows/autoformat.yml
  .github/workflows/copilot-setup-steps.yml
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  CLAUDE.md
  bin/.gitignore
  bin/README.md
  bin/install.py
  dev/install-conftest.sh
  dev/install-taplo.sh
  dev/install-typos.sh
  dev/taplo.sh
  dev/typos.sh
Labels: rn/none, area/build, team-review

#17458 Allow WMR to UC cross-workspace copying of model versions
  docs/docs/classic-ml/model-registry/workflow.mdx
  mlflow/environment_variables.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/databricks_workspace_model_registry_rest_store.py
  mlflow/tracking/_model_registry/utils.py
  mlflow/tracking/client.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/store/model_registry/test_databricks_workspace_model_registry_store.py
Labels: rn/feature, area/model-registry

#17512 Update Python guide to include monkeypatch.delenv documentation
  dev/guides/python.md
Labels: area/docs, rn/none

#17483 Judge tool: List spans
  mlflow/genai/judges/tools/__init__.py
  mlflow/genai/judges/tools/constants.py
  mlflow/genai/judges/tools/list_spans.py
  mlflow/genai/judges/tools/registry.py
  mlflow/genai/judges/tools/types.py
  tests/genai/judges/test_judge_tool_list_spans.py
Labels: rn/none, area/evaluation

#17464 Judges - add support for mlflow.genai.evaluate
  mlflow/genai/judges/make_judge.py
  mlflow/genai/scorers/validation.py
  tests/genai/judges/test_make_judge.py
Labels: rn/feature, area/evaluation

#17497 Judge tool: Search Trace Regex
  mlflow/genai/judges/tools/__init__.py
  mlflow/genai/judges/tools/constants.py
  mlflow/genai/judges/tools/registry.py
  mlflow/genai/judges/tools/search_trace_regex.py
  tests/genai/judges/test_search_trace_regex_tool.py
Labels: rn/none, area/evaluation

#17485 Refactor events table to logs table after trace server API change
  mlflow/entities/databricks_trace_storage_config.py
  mlflow/protos/databricks_trace_server.proto
  mlflow/protos/databricks_trace_server_pb2.py
  mlflow/protos/databricks_trace_server_pb2.pyi
  mlflow/tracing/databricks_archival.py
  mlflow/tracing/utils/databricks_delta_utils.py
  tests/tracing/databricks_archival/test_databricks_archival.py
  tests/tracing/databricks_archival/test_databricks_trace_exporter.py
  tests/tracing/databricks_archival/test_databricks_trace_exporter_utils.py
  tests/tracing/databricks_archival/test_databricks_trace_storage_config.py
Labels: rn/none, area/tracing

#17489 Fix Spark UDF `uv` env_manager
  mlflow/projects/backend/local.py
  mlflow/utils/virtualenv.py
Labels: rn/bug-fix, area/scoring, v3.3.3

#17515 Require databricks-connect instead of databricks-agents
  .github/workflows/master.yml
  mlflow/tracing/databricks_archival.py
  tests/tracing/databricks_archival/test_databricks_archival.py
Labels: rn/none, area/tracing

#17522 Add telemetry tracking for git model versioning API
  mlflow/genai/git_versioning/__init__.py
  mlflow/telemetry/events.py
  tests/telemetry/test_tracked_events.py
Labels: rn/none

#17538 Fix `tests/tracing/export/test_mlflow_v3_exporter.py::test_export` slowness
  tests/tracing/export/test_mlflow_v3_exporter.py
Labels: rn/none, team-review

#17521 Add documentation for claude code autotracing
  docs/docs/genai/tracing/integrations/listing/claude_code.mdx
  docs/src/components/TracingIntegrations/index.tsx
  docs/static/images/llms/anthropic/claude-code-tracing.png
  docs/static/images/logos/claude-code-logo.svg
  mlflow/claude_code/hooks.py
  mlflow/claude_code/tracing.py
Labels: rn/bug-fix, rn/documentation, area/tracking, v3.4.0

#17519 Add SIMBAAlignmentOptimizer implementation
  mlflow/genai/judges/optimizers/dspy.py
  mlflow/genai/judges/optimizers/simba.py
  tests/genai/judges/optimizers/test_dspy_base.py
  tests/genai/judges/optimizers/test_simba.py
Labels: rn/none, area/evaluation

#17550 Fix Compare experiments in UI
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.tsx
Labels: rn/bug-fix, area/uiux, v3.3.3

#17547 Only update docker latest when releasing next semantic version
  .github/workflows/push-images.yml
Labels: rn/none, area/build, team-review, v3.3.3

#17546 Add UC table source for evaluate
  mlflow/data/dataset_source_registry.py
  mlflow/genai/datasets/databricks_evaluation_dataset_source.py
  tests/genai/datasets/test_evaluation_dataset.py
Labels: rn/bug-fix, team-review, area/evaluation, v3.3.3

#17542 Add clarification for trace requirements in scorers docs
  docs/docs/genai/eval-monitor/quickstart.mdx
  docs/docs/genai/eval-monitor/scorers/custom.mdx
  docs/docs/genai/eval-monitor/scorers/index.mdx
  docs/docs/genai/eval-monitor/scorers/llm-judge/predefined.mdx
Labels: area/docs, rn/documentation, team-review

#17426 Fix load_context timing in PythonModel logging
  mlflow/models/signature.py
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/none, team-review

#17560 Judges - validate input arg types to InstructionsJudge entrypoint
  mlflow/genai/judges/instructions_judge/__init__.py
  tests/genai/judges/test_make_judge.py
Labels: rn/none, area/evaluation

#17545 Remove an unlinked _pb2.pyi file
  mlflow/protos/evaluation_datasets_pb2.pyi
Labels: rn/none, area/tracking, team-review

#17477 Fix semantic-kernel cross test
  tests/semantic_kernel/resources.py
Labels: team-review

#17559 Judges - fix make_judge docstring
  mlflow/genai/judges/make_judge.py
Labels: rn/none, area/evaluation

#17584 Fix custom prompt judge encoding bug with custom judge model
  mlflow/genai/judges/utils.py
  tests/genai/judges/test_judge_utils.py
Labels: rn/bug-fix, v3.3.3, v3.4.0

#17585 Add MLflow OSS telemetry for invoke_custom_judge_model
  docs/docs/community/usage-tracking.mdx
  mlflow/genai/judges/utils.py
  mlflow/telemetry/events.py
  tests/telemetry/test_tracked_events.py
Labels: rn/feature, v3.3.3, v3.4.0

#17587 Ping usethis version
  mlflow/R/mlflow/.install-deps.R
Labels: rn/none, area/tracking, team-review, v3.3.3

#17579 Judges - Add debug logs for tool invocations
  mlflow/genai/judges/tools/registry.py
Labels: rn/none, area/evaluation

#17568 Judges - add contextual text references to prompt templatization
  mlflow/genai/judges/instructions_judge/__init__.py
  tests/genai/judges/test_make_judge.py
Labels: rn/none, area/evaluation

#17586 Escape backslash in PromptVersion.format
  mlflow/entities/model_registry/prompt_version.py
  mlflow/genai/judges/custom_prompt_judge.py
  mlflow/genai/judges/prompts/context_sufficiency.py
  mlflow/genai/judges/prompts/correctness.py
  mlflow/genai/judges/prompts/groundedness.py
  mlflow/genai/judges/prompts/guidelines.py
  mlflow/genai/judges/prompts/relevance_to_query.py
  mlflow/genai/judges/prompts/retrieval_relevance.py
  mlflow/genai/judges/prompts/safety.py
  mlflow/genai/judges/utils.py
  mlflow/genai/prompts/utils.py
  tests/entities/test_prompt.py
  tests/genai/judges/test_judge_utils.py
  tests/genai/prompts/test_prompts.py
Labels: team-review, area/prompts, v3.3.3

#17602 Remove assertions for non-existent versions in `filter_versions` function
  dev/set_matrix.py
Labels: rn/none, only-latest, team-review

#17610 Remove `py310` job
  .github/workflows/master.yml
Labels: rn/none

#17599 Refactor DSPyAlignmentOptimizer trace limit handling
  mlflow/genai/judges/optimizers/dspy.py
  mlflow/genai/judges/optimizers/simba.py
  tests/genai/judges/optimizers/test_dspy_base.py
  tests/genai/judges/optimizers/test_simba.py
Labels: rn/none, area/tracing, area/evaluation

#17601 Add Invoke Custom Judge Databricks-Only Telemetry
  mlflow/genai/judges/utils.py
  tests/genai/judges/test_judge_utils.py
  tests/telemetry/test_tracked_events.py
Labels: rn/none, area/evaluation, v3.3.3, v3.4.0

#17600 Extract source workspace ID from run_link if provided when migrating model version
  docs/docs/classic-ml/model-registry/workflow.mdx
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/model_registry/databricks_workspace_model_registry_rest_store.py
  tests/store/model_registry/test_databricks_workspace_model_registry_store.py
Labels: rn/bug-fix, area/model-registry, v3.3.3

#17608 Add AI commands as MCP prompts
  mlflow/ai_commands/__init__.py
  mlflow/ai_commands/ai_command_utils.py
  mlflow/ai_commands/genai/analyze_experiment.md
  mlflow/mcp/server.py
  tests/ai_commands/test_ai_command_utils.py
  tests/mcp/test_mcp.py
Labels: rn/feature, area/tracing

#17549 Add ability to pass tags via dataframe in mlflow.genai.evaluate
  docs/docs/genai/eval-monitor/running-evaluation/agents.mdx
  docs/docs/genai/eval-monitor/running-evaluation/prompts.mdx
  mlflow/genai/evaluation/base.py
  mlflow/genai/evaluation/constant.py
  mlflow/genai/evaluation/entities.py
  mlflow/genai/evaluation/harness.py
  mlflow/genai/evaluation/utils.py
  tests/genai/evaluate/test_evaluation.py
  tests/genai/evaluate/test_utils.py
  tests/genai/scorers/test_aggregation.py
Labels: rn/feature, area/tracking, area/evaluation, v3.4.0

#17617 Remove separate telemetry tests step from Windows workflow
  .github/workflows/master.yml
Labels: rn/none, area/build

#17624 When logging a model with prompts, link the prompts to the model
  mlflow/models/model.py
  tests/models/test_model.py
Labels: rn/none, v3.3.3, v3.4.0

#17603 Attempt to get workspace_url from notebook before host credentials
  mlflow/tracing/utils/databricks_delta_utils.py
  tests/tracing/databricks_archival/test_databricks_trace_exporter_utils.py
Labels: rn/none, area/tracing

#17616 Split slow `test_predict` into focused test functions
  tests/models/test_cli.py
Labels: rn/none, team-review

#17630 Ignore `tests/sagemaker` in windows job
  .github/workflows/master.yml
Labels: rn/none, team-review

#17612 Skip test_build_image on PR to speed up CI
  tests/pyfunc/docker/test_docker.py
Labels: rn/none, area/build, team-review

#17615 Fix --env-file flag to work with --dev mode
  dev/run-dev-server.sh
  mlflow/cli/__init__.py
  mlflow/server/__init__.py
  tests/server/test_init.py
  tests/test_cli.py
Labels: rn/bug-fix, area/server-infra

#17596 Fix an issue with 'aggregations' being applied to a legacy scorer interface
  mlflow/genai/evaluation/utils.py
  tests/genai/evaluate/test_utils.py
Labels: rn/bug-fix, team-review, area/evaluation, v3.3.3

#17644 Judges - Fix number of brackets around "trace" in instructions judge prompt
  mlflow/genai/judges/instructions_judge/constants.py
  tests/genai/judges/test_make_judge.py
Labels: rn/none, area/evaluation

#17571 Judges - add support for trace input to work on field-based InstructionsJudge
  mlflow/genai/judges/instructions_judge/__init__.py
  mlflow/genai/judges/judge_trace_utils.py
  mlflow/genai/judges/optimizers/dspy_utils.py
  mlflow/genai/scorers/builtin_scorers.py
  mlflow/genai/utils/trace_utils.py
  tests/genai/judges/optimizers/test_dspy_utils.py
  tests/genai/judges/optimizers/test_judge_trace_utils.py
  tests/genai/judges/test_make_judge.py
  tests/genai/utils/test_trace_utils.py
Labels: rn/feature, area/evaluation

#17371 Haystack Integration
  conftest.py
  dev/pyproject.py
  docs/api_reference/api_inventory.txt
  docs/api_reference/source/python_api/mlflow.haystack.rst
  docs/docs/genai/tracing/integrations/listing/haystack.mdx
  docs/src/components/TracingIntegrations/index.tsx
  docs/static/images/llms/haystack/haystack-basic-tracing.png
  docs/static/images/llms/haystack/haystack-tracing.png
  docs/static/images/logos/haystack-logo.png
  examples/haystack/tracing.py
  libs/tracing/pyproject.toml
  mlflow/__init__.py
  mlflow/haystack/__init__.py
  mlflow/haystack/autolog.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/tracking/fluent.py
  requirements/doc-requirements.txt
  requirements/extra-ml-requirements.txt
  tests/haystack/test_haystack_tracing.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/feature, autoformat, area/tracing

#17725 Markdown UI fix
  mlflow/server/js/src/common/components/EditableNote.test.tsx
  mlflow/server/js/src/common/components/EditableNote.tsx
Labels: rn/bug-fix, area/uiux, v3.4.0

#17741 Make Spark Datasource failures silent
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/DatasourceAttributeExtractor.scala
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/ExceptionUtils.scala
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/MlflowAutologEventPublisher.scala
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/ReplAwareSparkDataSourceListener.scala
  mlflow/java/spark/src/main/scala/org/mlflow/spark/autologging/SparkDataSourceListener.scala
Labels: rn/none, area/tracking, team-review, v3.4.0

#17660 Add Autologging event
  docs/docs/community/usage-tracking.mdx
  mlflow/ag2/__init__.py
  mlflow/agno/__init__.py
  mlflow/anthropic/__init__.py
  mlflow/autogen/__init__.py
  mlflow/bedrock/__init__.py
  mlflow/crewai/__init__.py
  mlflow/dspy/autolog.py
  mlflow/gemini/__init__.py
  mlflow/groq/__init__.py
  mlflow/langchain/autolog.py
  mlflow/litellm/__init__.py
  mlflow/llama_index/autolog.py
  mlflow/mistral/__init__.py
  mlflow/openai/autolog.py
  mlflow/pydantic_ai/__init__.py
  mlflow/semantic_kernel/__init__.py
  mlflow/smolagents/__init__.py
  mlflow/strands/__init__.py
  mlflow/telemetry/events.py
  mlflow/telemetry/track.py
  mlflow/tracking/fluent.py
  tests/telemetry/test_tracked_events.py
Labels: rn/none, team-review, v3.4.0

#17729 [OTel UI] Make Trace ID clickable in trace table
  mlflow/server/js/src/shared/web-shared/genai-traces-table/cellRenderers/rendererFunctions.tsx
Labels: rn/none, area/uiux

#17758 Add experiment types feature to changelog
  CHANGELOG.md
Labels: rn/none

#17748 Exclude immutable tags when setting tags
  mlflow/genai/evaluation/harness.py
  tests/genai/evaluate/test_evaluation.py
Labels: rn/none, team-review, v3.4.0

#17756 [OTel UI] Minor fixes and refactors
  mlflow/server/js/src/experiment-tracking/components/evaluations/RunViewEvaluationsTab.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/traces-v3/TracesV3Logs.intg.test.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/traces-v3/TracesV3Logs.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/traces-v3/utils/columnUtils.ts
  mlflow/server/js/src/shared/web-shared/genai-traces-table/index.ts
  mlflow/server/js/src/shared/web-shared/model-trace-explorer/ModelTraceExplorer.test-utils.ts
  mlflow/server/js/src/shared/web-shared/model-trace-explorer/ModelTraceExplorer.utils.test.tsx
Labels: rn/none, area/uiux

#17780 Fix bug in Evaluation Datasets handler and misconfigured test
  mlflow/server/handlers.py
  mlflow/store/tracking/file_store.py
  tests/server/test_handlers.py
Labels: rn/bug-fix, area/tracking, team-review, v3.4.0

#17742 Added move to top, move to bottom for charts
  mlflow/server/js/src/experiment-tracking/components/runs-charts/components/RunsChartsDraggableCardsGrid.test.tsx
  mlflow/server/js/src/experiment-tracking/components/runs-charts/components/RunsChartsDraggableCardsGridSection.tsx
  mlflow/server/js/src/experiment-tracking/components/runs-charts/components/RunsChartsFullScreenModal.tsx
  mlflow/server/js/src/experiment-tracking/components/runs-charts/components/RunsChartsGlobalChartSettingsDropdown.test.tsx
  mlflow/server/js/src/experiment-tracking/components/runs-charts/components/cards/ChartCard.common.tsx
  mlflow/server/js/src/experiment-tracking/components/runs-charts/components/cards/RunsChartsCard.tsx
  mlflow/server/js/src/lang/default/en.json
Labels: rn/feature, area/uiux, v3.4.0

#17789 Fix: Ensure databricks-connect and databricks-agents are uninstalled before pyspark installation
  .github/workflows/master.yml
Labels: rn/none, area/build, team-review

#17781 Add proper e2e test coverage for merge_records API
  tests/tracking/test_rest_tracking.py
Labels: rn/none, area/tracking, team-review

#17784 Fix `to_predict_fn` to handle traces without tags field
  mlflow/tracing/utils/copy.py
  tests/genai/evaluate/test_to_predict_fn.py
Labels: rn/bug-fix, team-review, area/tracing, v3.4.1

#17776 Add notes and warnings to docs about interoperability of legacy eval and genai eval functionality
  docs/docs/classic-ml/evaluation/index.mdx
  docs/docs/classic-ml/evaluation/model-eval.mdx
  docs/docs/genai/eval-monitor/index.mdx
Labels: area/docs, rn/none, team-review

#16248 Gemini token count
  docs/docs/genai/tracing/integrations/listing/gemini.mdx
  mlflow/gemini/autolog.py
  tests/gemini/test_gemini_autolog.py
Labels: rn/feature, area/tracking

#17805 Fix pytest import errors by removing pythonpath configuration
  pyproject.toml
Labels: rn/none, area/build, team-review

#17777 Initial constants and utils for insights
  mlflow/insights/__init__.py
  mlflow/insights/constants.py
  mlflow/insights/models.py
  mlflow/insights/utils.py
  tests/insights/__init__.py
  tests/insights/test_constants.py
  tests/insights/test_models.py
  tests/insights/test_utils.py
Labels: rn/none, area/evaluation

#17814 Add default optimizer docs
  docs/docs/genai/concepts/scorers.mdx
  docs/docs/genai/eval-monitor/scorers/llm-judge/alignment.mdx
  docs/docs/genai/eval-monitor/scorers/llm-judge/workflow.mdx
Labels: area/docs, rn/documentation, team-review, v3.4.1

#17835 Allow caller to disable eval logging
  mlflow/dspy/callback.py
  tests/dspy/test_dspy_autolog.py
Labels: rn/none, area/tracking, team-review, v3.4.1

#17795 Reduce verbosity of SIMBA optimizer logs when aligning judges
  docs/docs/genai/eval-monitor/scorers/llm-judge/alignment.mdx
  mlflow/genai/judges/base.py
  mlflow/genai/judges/make_judge.py
  mlflow/genai/judges/optimizers/dspy.py
  mlflow/genai/judges/optimizers/simba.py
Labels: rn/feature, team-review, area/evaluation

#17818 Fix a css warning in the docs build
  docs/src/components/Card/card.module.css
Labels: rn/none, area/build, team-review

#17841 Add telemetry for Judge APIs
  docs/docs/community/usage-tracking.mdx
  mlflow/genai/judges/base.py
  mlflow/genai/judges/make_judge.py
  mlflow/telemetry/events.py
  tests/telemetry/test_events.py
  tests/telemetry/test_tracked_events.py
Labels: rn/none, team-review, area/evaluation, v3.4.1

#17866 Avoid starting eval runs when parent run active outside optimization
  mlflow/dspy/callback.py
  tests/dspy/test_dspy_autolog.py
Labels: rn/none, area/tracking, autoformat, team-review, v3.4.1

#17676 Job execution backend
  .github/workflows/r.yml
  dev/install-common-deps.sh
  dev/pyproject.py
  examples/mlflow_artifacts/docker-compose.yml
  libs/skinny/pyproject.toml
  mlflow/entities/_job.py
  mlflow/entities/_job_status.py
  mlflow/environment_variables.py
  mlflow/server/__init__.py
  mlflow/server/handlers.py
  mlflow/server/jobs/__init__.py
  mlflow/server/jobs/job_runner.py
  mlflow/server/jobs/util.py
  mlflow/store/db_migrations/versions/bf29a5ff90ea_add_jobs_table.py
  mlflow/store/jobs/__init__.py
  mlflow/store/jobs/abstract_store.py
  mlflow/store/jobs/sqlalchemy_store.py
  mlflow/store/tracking/dbmodels/models.py
  pyproject.release.toml
  pyproject.toml
  tests/db/schemas/mssql.sql
  tests/db/schemas/mysql.sql
  tests/db/schemas/postgresql.sql
  tests/db/schemas/sqlite.sql
  tests/resources/db/latest_schema.sql
  tests/server/job/test_job.py
  tests/server/test_init.py
Labels: rn/feature, area/tracking, team-review

#17898 Remove required `inputs` in dataset for genai evaluate
  mlflow/genai/evaluation/entities.py
  mlflow/genai/evaluation/utils.py
  tests/genai/evaluate/test_evaluation.py
  tests/genai/evaluate/test_utils.py
Labels: rn/none

#17913 Fix test requirements CI
  .github/actions/update-requirements/action.yml
Labels: rn/none, area/build, team-review

#17893 Support get_traces and create_trace for RestStore
  mlflow/exceptions.py
  mlflow/server/handlers.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/databricks_rest_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/tracking/_tracking_service/utils.py
  tests/server/test_handlers.py
  tests/store/tracking/test_databricks_rest_store.py
  tests/store/tracking/test_rest_store.py
  tests/tracing/export/test_mlflow_v3_exporter.py
  tests/tracking/_tracking_service/test_utils.py
Labels: rn/none

#17935 Judges bug fix - use non-empty user message for compatibility with Anthropic & related models
  mlflow/genai/judges/instructions_judge/__init__.py
  tests/genai/judges/test_make_judge.py
Labels: rn/bug-fix, area/evaluation, v3.4.1

#17908 fix: allow list of types in tools JSON Schema (OpenAI autolog)
  mlflow/types/chat.py
Labels: rn/bug-fix, area/tracking, v3.4.1

#17922 Add automated uv.lock update workflow
  .github/workflows/uv.js
  .github/workflows/uv.yml
Labels: rn/none, area/build, team-review

#17946 [ML-57771] ResponsesAgent: more helpers and docs
  docs/api_reference/api_inventory.txt
  docs/api_reference/source/python_api/mlflow.types.rst
  docs/docs/genai/flavors/responses-agent-intro.mdx
  docs/docs/genai/serving/responses-agent.mdx
  mlflow/pyfunc/model.py
  mlflow/types/responses.py
  tests/langchain/test_responses_agent_langchain.py
  tests/pyfunc/test_responses_agent.py
Labels: rn/none, area/models, v3.4.1

#17970 Fix missing huey dependency in test requirements
  requirements/test-requirements.txt
Labels: rn/none, area/build, team-review

#17948 Add span timing tool for Agent Judges
  mlflow/genai/judges/tools/__init__.py
  mlflow/genai/judges/tools/constants.py
  mlflow/genai/judges/tools/get_span_performance_and_timing_report.py
  mlflow/genai/judges/tools/registry.py
  tests/genai/judges/test_judge_tool_get_span_performance_and_timing_report.py
  tests/genai/judges/test_judge_tool_registry.py
Labels: rn/feature, team-review, area/evaluation

#17931 Labeling Sessions - Create DatabricksLabelingStore and AbstractLabelingStore (Refactor)
  mlflow/genai/label_schemas/__init__.py
  mlflow/genai/labeling/__init__.py
  mlflow/genai/labeling/databricks_utils.py
  mlflow/genai/labeling/labeling.py
  mlflow/genai/labeling/stores.py
  tests/genai/label_schemas/test_label_schemas.py
Labels: rn/none

#17921 Fix usage aggregation to avoid ancestor duplication
  mlflow/tracing/utils/__init__.py
  tests/tracing/utils/test_utils.py
Labels: rn/bug-fix, autoformat, team-review, area/tracing, v3.4.1

#17944 Add kwargs to onnx.log_model
  mlflow/onnx/__init__.py
Labels: rn/none, area/tracking, team-review, v3.4.1

#17806 [4/x] Search Traces
  mlflow/cli/traces.py
  mlflow/protos/databricks_tracing.proto
  mlflow/protos/databricks_tracing_pb2.py
  mlflow/protos/databricks_tracing_pb2.pyi
  mlflow/server/handlers.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/databricks_rest_store.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracing/client.py
  mlflow/tracing/fluent.py
  mlflow/tracking/client.py
  mlflow/utils/validation.py
  tests/store/tracking/test_databricks_rest_store.py
  tests/store/tracking/test_rest_store.py
  tests/tracing/helper.py
  tests/tracing/test_fluent.py
  tests/tracking/test_client.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, team-review

#17997 Include original error details in Unity Catalog model copy failure messages
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/_unity_catalog/registry/uc_oss_rest_store.py
Labels: rn/bug-fix, area/model-registry, team-review, v3.4.1

#18003 Remove shutdown to avoid error message
  tests/tracing/test_otel_logging.py
Labels: rn/none, team-review

#17995 Doc update for Typescript SDK contribution
  docs/docs/genai/tracing/app-instrumentation/typescript-sdk.mdx
  docs/docs/genai/tracing/integrations/contribute.mdx
  libs/typescript/README.md
Labels: area/docs, rn/documentation

#18016 Fix `mlflow server` exiting immediately when optional `huey` package is missing
  mlflow/server/__init__.py
Labels: rn/bug-fix, area/build

#18020 Update proto for link/unlink experiment trace location
  mlflow/protos/databricks_tracing.proto
  mlflow/protos/databricks_tracing_pb2.py
  mlflow/protos/databricks_tracing_pb2.pyi
  mlflow/store/tracking/databricks_rest_store.py
  mlflow/tracing/client.py
  mlflow/tracing/enablement.py
  tests/store/tracking/test_databricks_rest_store.py
  tests/tracing/test_enablement.py
Labels: rn/none, area/tracing

#17999 Bump TS SDK version
  libs/typescript/core/package.json
  libs/typescript/integrations/openai/package.json
Labels: rn/none, area/tracing
