Repository mlflow/mlflow, pull requests merged in 2025-01, with the labels that each got.

#14108 Adopt Python tests for MLFlow GO implementation.
  mlflow/entities/model_registry/model_version.py
  tests/store/model_registry/test_sqlalchemy_store.py
Labels: rn/none

#14181 Fix databricks utils
  mlflow/utils/databricks_utils.py
Labels: rn/none

#14188 Fix DSPy test failures on dev
  mlflow/dspy/callback.py
  tests/dspy/test_dspy_autolog.py
  tests/dspy/test_save.py
Labels: rn/none

#14187 Fix tensorflow
  mlflow/ml-package-versions.yml
Labels: rn/none

#14172 Add tool attributes for gemini flavor
  mlflow/gemini/autolog.py
  mlflow/gemini/chat.py
  tests/gemini/test_gemini_autolog.py
Labels: rn/none, area/tracking

#14173 Implement standatd span attribute logic for Bedrock
  mlflow/bedrock/_autolog.py
  mlflow/bedrock/chat.py
  tests/bedrock/test_bedrock_autolog.py
  tests/resources/images/test.png
Labels: rn/none, area/tracking

#14198 Fix uv logs
  mlflow/utils/virtualenv.py
Labels: rn/none

#14171 Limit model input typehint to list for predict
  mlflow/models/signature.py
  mlflow/pyfunc/utils/data_validation.py
  mlflow/types/type_hints.py
  mlflow/utils/proto_json_utils.py
  tests/models/test_model.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_pyfunc_model_with_type_hints.py
  tests/types/test_type_hints.py
Labels: rn/feature

#14204 Fix promptflow tests
  mlflow/ml-package-versions.yml
Labels: rn/none

#14168 Support type hint in serving
  mlflow/environment_variables.py
  mlflow/models/utils.py
  mlflow/pyfunc/scoring_server/__init__.py
  mlflow/pyfunc/utils/data_validation.py
  mlflow/pyfunc/utils/environment.py
  mlflow/types/type_hints.py
  tests/pyfunc/test_pyfunc_model_with_type_hints.py
  tests/pyfunc/test_scoring_server.py
Labels: rn/feature

#14202 Apply timeout override to within-request local scoring server for Spark UDF inference
  docs/source/models.rst
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/scoring_server/client.py
  tests/pyfunc/test_spark.py
Labels: rn/feature, area/scoring, v2.19.1

#14203 Update presigned URL list_artifacts to return an empty list instead of an exception
  mlflow/store/artifact/presigned_url_artifact_repo.py
  tests/store/artifact/test_presigned_url_artifact_repo.py
Labels: rn/bug-fix, area/artifacts, v2.19.1

#14196 Update DSPy tracing to handle tool calling
  mlflow/dspy/callback.py
  tests/dspy/test_dspy_autolog.py
Labels: rn/none, area/tracking, v2.19.1

#14208 Split pyfunc test
  .github/workflows/master.yml
Labels: rn/none

#14189 Add predict section in artifacts tab
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactLoggedModelView.enzyme.test.tsx
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactLoggedModelView.tsx
  mlflow/server/js/src/lang/default/en.json
Labels: rn/feature

#14185 Add doc for cusotmizing langchain trace name/metadata
  docs/source/_static/images/llms/tracing/langchain-name-customize.png
  docs/source/llms/langchain/autologging.rst
  docs/source/llms/tracing/index.rst
Labels: area/docs, rn/none, v2.19.1, v2.20.0

#14213 Move predict function definition check to model creation
  mlflow/pyfunc/model.py
  mlflow/pyfunc/utils/data_validation.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_pyfunc_model_with_type_hints.py
Labels: rn/none

#14205 Implement tool standard for crewai
  mlflow/crewai/autolog.py
  mlflow/crewai/chat.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  tests/crewai/test_crewai_autolog.py
Labels: rn/none, v2.19.1, v2.20.0

#14216 Fix infer signature warnings
  mlflow/models/signature.py
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_pyfunc_model_with_type_hints.py
Labels: rn/none

#14182 Special type hint support
  mlflow/models/model.py
  mlflow/models/signature.py
  mlflow/models/utils.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/utils/data_validation.py
  mlflow/types/type_hints.py
  tests/models/test_model.py
  tests/pyfunc/test_pyfunc_model_with_type_hints.py
  tests/types/test_type_hints.py
Labels: rn/feature

#14223 Make show/hide evaluation code toggable when calling `log_model`
  mlflow/models/resources/agent_evaluation_template.html
Labels: rn/none, area/uiux, area/models, integrations/databricks, v2.19.1, v2.20.0

#13797 Introduce ChatAgent
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/loaders/__init__.py
  mlflow/pyfunc/loaders/chat_agent.py
  mlflow/pyfunc/loaders/code_model.py
  mlflow/pyfunc/model.py
  mlflow/types/agent.py
  mlflow/types/chat.py
  mlflow/types/llm.py
  tests/pyfunc/test_chat_agent.py
  tests/pyfunc/test_chat_agent_validation.py
Labels: rn/feature, area/models, v2.20.0

#14218 Improve type hints error messages
  mlflow/models/signature.py
  mlflow/pyfunc/utils/data_validation.py
  mlflow/types/type_hints.py
  mlflow/utils/warnings_utils.py
  tests/types/test_type_hints.py
Labels: rn/none, v2.20.0

#14206 Implement standard span attribute logic for LlamaIndex
  .github/workflows/master.yml
  mlflow/llama_index/chat.py
  mlflow/llama_index/tracer.py
  mlflow/tracing/utils/__init__.py
  mlflow/utils/__init__.py
  mlflow/utils/pydantic_utils.py
  tests/langchain/test_langchain_model_export.py
  tests/llama_index/test_llama_index_autolog.py
  tests/llama_index/test_llama_index_tracer.py
  tests/openai/mock_openai.py
  tests/openai/test_openai_autolog.py
  tests/tracing/utils/test_utils.py
  tests/utils/test_pydantic_utils.py
Labels: rn/none, area/tracking, v2.20.0

#14229 Update code snippet
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactLoggedModelView.enzyme.test.tsx
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactLoggedModelView.tsx
Labels: rn/none, v2.20.0

#14220 Fix the faithfulness metric for custom override parameters supplied to the callable metric implementation
  mlflow/metrics/genai/metric_definitions.py
  tests/metrics/genai/test_genai_metrics.py
Labels: rn/bug-fix, area/models, v2.19.1, v2.20.0

#14207 Implement standard span attribute logic for DSPy
  mlflow/dspy/callback.py
  tests/dspy/test_dspy_autolog.py
Labels: rn/none, area/tracking, v2.19.1, v2.20.0

#14227 Raise exception for invalid type hint
  mlflow/models/signature.py
  mlflow/pyfunc/utils/data_validation.py
  mlflow/types/type_hints.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_pyfunc_model_with_type_hints.py
  tests/types/test_type_hints.py
Labels: rn/none, v2.20.0

#14212 Add support for invokers rights in Databricks Resources
  mlflow/models/resources.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  tests/models/test_resources.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/feature, v2.19.1, v2.20.0

#14228 Raise exception if pydantic object is used in infer_signature
  mlflow/models/signature.py
  mlflow/types/utils.py
  tests/models/test_signature.py
Labels: rn/none, v2.20.0

#14234 Fix read example
  mlflow/models/utils.py
Labels: rn/none

#14232 Remove inefficient attribute lookup during setting DSPy span standard attributes
  mlflow/dspy/callback.py
Labels: rn/none, area/tracking, v2.19.1

#14046 Add model_id and params to ModelVersion proto and API
  mlflow/java/client/src/main/java/org/mlflow/api/proto/ModelRegistry.java
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/protos/model_registry.proto
  mlflow/protos/model_registry_pb2.py
  mlflow/server/graphql/autogenerated_graphql_schema.py
  mlflow/server/handlers.py
  mlflow/server/js/src/graphql/autogenerated_schema.gql
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/utils/_unity_catalog_utils.py
Labels: rn/none, area/model-registry, area/tracking

#14245 Support registering models from `MlflowClient()`
  examples/mlflow-3/register_model.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/client.py
  mlflow/utils/_unity_catalog_utils.py
Labels: rn/none, area/model-registry, area/tracking

#14246 Fix Registering Model within log_model() for MLflow 3.0
  examples/mlflow-3/register_model.py
  mlflow/models/model.py
Labels: rn/none, area/model-registry, area/tracking

#14248 Set encoding when writing/reading trace data
  mlflow/store/artifact/artifact_repo.py
Labels: rn/none, v2.20.0

#14247 Increase default max retries for requests from 5 -> 7 to improve robustness to rate limiting errors from MLflow backend
  mlflow/environment_variables.py
  tests/utils/test_rest_utils.py
Labels: rn/none, area/tracking, v2.20.0

#14239 Validate input example against signature
  mlflow/pyfunc/__init__.py
  mlflow/recipes/steps/train.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/none, v2.20.0

#14235 Warn if no type hints provided for PythonModel
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/utils/data_validation.py
  tests/pyfunc/test_pyfunc_model_with_type_hints.py
Labels: rn/none, v2.20.0

#14222 Document how to increase timeout length for tracking server
  docs/source/tracking/server.rst
Labels: rn/none

#13992 Implement `delete_artifacts` in `mlflow/store/artifact/azure_blob_artifact_repo.py`
  mlflow/store/artifact/azure_blob_artifact_repo.py
  tests/store/artifact/test_azure_blob_artifact_repo.py
Labels: rn/feature, area/artifacts, integrations/azure, v2.20.0

#14258 Fix `ContentEncoding` value
  tests/store/artifact/test_s3_artifact_repo.py
Labels: rn/none

#14225 [DOC-FIX #14183] Improve documentation for 'artifact_uri' in 'download_artifacts'
  mlflow/artifacts/__init__.py
Labels: rn/documentation, area/artifacts

#14199 Bedrock streaming tracing
  mlflow/bedrock/_autolog.py
  mlflow/bedrock/chat.py
  mlflow/bedrock/stream.py
  mlflow/bedrock/utils.py
  mlflow/tracing/utils/__init__.py
  tests/bedrock/test_bedrock_autolog.py
Labels: rn/feature, area/tracking, v2.19.1, v2.20.0

#14254 Bedrock tracing doc
  docs/source/_static/images/llms/tracing/bedrock-tracing-agent.png
  docs/source/_static/images/llms/tracing/bedrock-tracing-stream.png
  docs/source/_static/images/llms/tracing/bedrock-tracing.png
  docs/source/_static/images/logos/bedrock-logo.png
  docs/source/llms/bedrock/autologging.rst
  docs/source/llms/tracing/index.rst
  docs/source/python_api/mlflow.bedrock.rst
Labels: rn/none, area/tracking, v2.20.0

#14253 Type hint docs
  docs/source/model/python_model.rst
  docs/source/models.rst
  mlflow/pyfunc/model.py
Labels: rn/documentation, v2.20.0

#14263 Announce survey and office hours on README
  README.md
Labels: rn/none

#14178 Update example references
  docs/source/llms/deployments/uc_integration.rst
  docs/source/llms/index.rst
  examples/gateway/uc_functions/README.md
Labels: rn/none

#14195 Add Mistral AI autolog tracing integration
  conftest.py
  docs/source/_static/images/llms/mistral/mistral-tracing.png
  docs/source/llms/tracing/index.rst
  docs/source/python_api/mlflow.mistral.rst
  examples/mistral/tracing.py
  mlflow/__init__.py
  mlflow/mistral/__init__.py
  mlflow/mistral/autolog.py
  mlflow/mistral/chat.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/tracking/fluent.py
  requirements/extra-ml-requirements.txt
  tests/mistral/test_mistral_autolog.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/feature

#14242 Add API doc for `mlflow.evaluation.Assessment` entity
  docs/source/conf.py
  docs/source/python_api/mlflow.evaluation.rst
  mlflow/entities/assessment.py
  mlflow/entities/assessment_source.py
  mlflow/entities/evaluation.py
  mlflow/evaluation/assessment.py
  mlflow/evaluation/evaluation.py
  mlflow/evaluation/fluent.py
  mlflow/evaluation/utils.py
Labels: area/docs, rn/none, v2.19.1, v2.20.0

#14269 Use python 3.10 for spacy >= 3.8.4
  mlflow/ml-package-versions.yml
Labels: rn/none, v2.20.0

#14262 Improve warning msg
  mlflow/pyfunc/__init__.py
Labels: rn/none, v2.20.0

#14268 Pin boto3 to avoid recent breaking change
  mlflow/ml-package-versions.yml
Labels: rn/none, v2.20.0

#14270 Fix mistral dev cross verion test
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#14271 Fix set_tracking_uri
  mlflow/tracking/_tracking_service/utils.py
  tests/tracking/_tracking_service/test_utils.py
Labels: rn/none, v2.20.0

#14272 Add model_version to gemini tests
  tests/gemini/test_gemini_autolog.py
Labels: rn/none, enable-dev-tests

#14278 Pin boto3 in sentence_transformers cross version tests
  mlflow/ml-package-versions.yml
Labels: rn/none, v2.20.0

#14265 Spark_udf support for model with type hints
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
  mlflow/types/type_hints.py
  tests/pyfunc/test_pyfunc_model_with_type_hints.py
  tests/types/test_type_hints.py
Labels: rn/none

#14279 Skip `test_kickoff_failure`
  tests/crewai/test_crewai_autolog.py
Labels: rn/none, enable-dev-tests

#14276 Fix OpenAI autolog
  mlflow/openai/_openai_autolog.py
  mlflow/tracing/utils/__init__.py
  tests/openai/test_openai_autolog.py
Labels: rn/none, area/tracking, v2.20.0

#14249 Add `set_destination` API
  docs/source/python_api/mlflow.tracing.rst
  mlflow/tracing/__init__.py
  mlflow/tracing/destination.py
  mlflow/tracing/export/databricks_agent.py
  mlflow/tracing/processor/databricks_agent.py
  mlflow/tracing/processor/mlflow.py
  mlflow/tracing/provider.py
  mlflow/tracking/_tracking_service/utils.py
  tests/conftest.py
  tests/langchain/test_langchain_model_export.py
  tests/tracing/export/test_databricks_agent_exporter.py
  tests/tracing/processor/test_mlflow_processor.py
  tests/tracing/test_provider.py
Labels: rn/none, area/tracking, v2.20.0

#14284 Add dark theme logo in docusaurus navbar
  docs/docusaurus.config.ts
  docs/static/images/logo-dark.svg
  docs/static/images/logo-light.svg
  docs/static/images/logo.png
Labels: rn/none

#14285 Add GTM id in docusaurus
  docs/docusaurus.config.ts
Labels: rn/none

#14155 Use exclude_unset instead of exclude_none in openai chat schema
  mlflow/openai/utils/chat_schema.py
Labels: rn/none, v2.20.0

#14286 Fix groq logo
  docs/source/_static/images/logos/groq-logo.svg
Labels: area/docs, rn/none, v2.20.0

#14287 Fix docusaurus footer styles and github link
  docs/docusaurus.config.ts
  docs/src/css/custom.css
Labels: rn/none

#14281 Fix filename encoding issue in log_image
  mlflow/tracking/client.py
  mlflow/utils/uri.py
  tests/tracking/test_mlflow_artifacts.py
  tests/utils/test_uri.py
Labels: rn/bug-fix, v2.20.0

#14289 Add a quick guide for how to host MLflow on various platforms
  README.md
  docs/source/_static/images/logos/nebius-logo.png
  docs/source/getting-started/community-edition.rst
  docs/source/getting-started/index.rst
  docs/source/getting-started/intro-quickstart/index.rst
  docs/source/getting-started/intro-quickstart/notebooks/tracking_quickstart.ipynb
  docs/source/getting-started/logging-first-model/notebooks/logging-first-model.ipynb
  docs/source/getting-started/logging-first-model/step1-tracking-server.rst
  docs/source/getting-started/quickstart-2/index.rst
  docs/source/getting-started/running-notebooks.rst
  docs/source/index.rst
  docs/source/introduction/index.rst
  docs/source/llms/openai/notebooks/openai-code-helper.ipynb
  docs/source/platform.rst
Labels: area/docs, rn/documentation, v2.20.0

#14291 Change docusaurus primary color from green to blue
  docs/src/css/custom.css
Labels: rn/none

#14290 Improve docusaurus notebook formatting
  docs/docs/deep-learning/keras/quickstart/quickstart_keras.ipynb
  docs/docs/deep-learning/pytorch/quickstart/pytorch_quickstart.ipynb
  docs/docs/deep-learning/tensorflow/quickstart/quickstart_tensorflow.ipynb
  docs/docs/getting-started/intro-quickstart/notebooks/tracking_quickstart.ipynb
  docs/docs/llms/custom-pyfunc-for-llms/notebooks/custom-pyfunc-advanced-llm.ipynb
  docs/docs/llms/langchain/notebooks/langchain-quickstart.ipynb
  docs/docs/llms/langchain/notebooks/langchain-retriever.ipynb
  docs/docs/llms/llama-index/notebooks/llama_index_quickstart.ipynb
  docs/docs/llms/llama-index/notebooks/llama_index_workflow_tutorial.ipynb
  docs/docs/llms/llm-evaluate/notebooks/huggingface-evaluation.ipynb
  docs/docs/llms/llm-evaluate/notebooks/question-answering-evaluation.ipynb
  docs/docs/llms/llm-evaluate/notebooks/rag-evaluation-llama2.ipynb
  docs/docs/llms/llm-evaluate/notebooks/rag-evaluation.ipynb
  docs/docs/llms/notebooks/chat-model-tool-calling.ipynb
  docs/docs/llms/openai/notebooks/openai-chat-completions.ipynb
  docs/docs/llms/openai/notebooks/openai-code-helper.ipynb
  docs/docs/llms/openai/notebooks/openai-embeddings-generation.ipynb
  docs/docs/llms/openai/notebooks/openai-quickstart.ipynb
  docs/docs/llms/rag/notebooks/mlflow-e2e-evaluation.ipynb
  docs/docs/llms/rag/notebooks/question-generation-retrieval-evaluation.ipynb
  docs/docs/llms/rag/notebooks/retriever-evaluation-tutorial.ipynb
  docs/docs/llms/sentence-transformers/tutorials/paraphrase-mining/paraphrase-mining-sentence-transformers.ipynb
  docs/docs/llms/sentence-transformers/tutorials/quickstart/sentence-transformers-quickstart.ipynb
  docs/docs/llms/sentence-transformers/tutorials/semantic-search/semantic-search-sentence-transformers.ipynb
  docs/docs/llms/sentence-transformers/tutorials/semantic-similarity/semantic-similarity-sentence-transformers.ipynb
  docs/docs/llms/transformers/tutorials/audio-transcription/whisper.ipynb
  docs/docs/llms/transformers/tutorials/conversational/conversational-model.ipynb
  docs/docs/llms/transformers/tutorials/fine-tuning/transformers-fine-tuning.ipynb
  docs/docs/llms/transformers/tutorials/fine-tuning/transformers-peft.ipynb
  docs/docs/llms/transformers/tutorials/prompt-templating/prompt-templating.ipynb
  docs/docs/llms/transformers/tutorials/text-generation/text-generation.ipynb
  docs/docs/llms/transformers/tutorials/translation/component-translation.ipynb
  docs/docs/tracing/notebooks/jupyter-trace-demo.ipynb
  docs/scripts/convert-notebooks.py
  docs/src/components/NotebookCellOutput/index.tsx
  docs/src/components/NotebookCodeCell/index.tsx
  docs/src/components/NotebookDownloadButton/index.tsx
  docs/src/components/NotebookHTMLOutput/index.tsx
Labels: rn/none

#14280 Remove office hours announcement
  README.md
Labels: rn/none

#14295 Add link to documentation in error message
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/utils/data_validation.py
  mlflow/types/type_hints.py
  mlflow/types/utils.py
Labels: rn/none, v2.20.0

#14298 Fix type hint warning when importing builtin class
  mlflow/dspy/wrapper.py
  mlflow/pyfunc/model.py
  tests/pyfunc/test_pyfunc_model_with_type_hints.py
Labels: rn/none, area/tracking, v2.20.0

#14292 Add RunLLM to docusaurus page
  docs/docusaurus.config.ts
  docs/rst_to_migrate/_static/MLflow-logo-final-black.png
  docs/rst_to_migrate/_static/clippy.svg
  docs/rst_to_migrate/_static/favicon.ico
  docs/rst_to_migrate/_static/icons/important-icon.svg
  docs/rst_to_migrate/_static/icons/nav-home.svg
  docs/rst_to_migrate/_static/icons/note-icon.svg
  docs/rst_to_migrate/_static/icons/tip-icon.svg
  docs/rst_to_migrate/_static/icons/warning-icon.svg
  docs/static/js/runllm.js
Labels: rn/none

#14057 Implement Algolia integration
  docs/api_reference/theme/mlflow/layout.html
  docs/docusaurus.config.ts
Labels: rn/none

#14288 Support timeout for a trace
  docs/source/llms/tracing/index.rst
  mlflow/environment_variables.py
  mlflow/tracing/fluent.py
  mlflow/tracing/processor/mlflow.py
  mlflow/tracing/provider.py
  mlflow/tracing/trace_manager.py
  mlflow/tracing/utils/timeout.py
  mlflow/tracing/utils/token.py
  mlflow/tracing/utils/warning.py
  tests/conftest.py
  tests/tracing/helper.py
  tests/tracing/test_trace_manager.py
  tests/tracing/utils/test_timeout.py
  tests/tracing/utils/test_warning.py
Labels: rn/feature, area/tracking, v2.20.0

#14299 Fix notebook existence check on databricks
  mlflow/models/utils.py
Labels: rn/none, v2.20.0

#14300 Last docusaurus rebase
  README.md
  docs/api_reference/source/python_api/mlflow.tracing.rst
  docs/docs/getting-started/community-edition/index.mdx
  docs/docs/getting-started/index.mdx
  docs/docs/getting-started/intro-quickstart/index.mdx
  docs/docs/getting-started/intro-quickstart/notebooks/tracking_quickstart.ipynb
  docs/docs/getting-started/logging-first-model/notebooks/logging-first-model.ipynb
  docs/docs/getting-started/logging-first-model/step1-tracking-server/index.mdx
  docs/docs/getting-started/quickstart-2/index.mdx
  docs/docs/getting-started/running-notebooks/index.mdx
  docs/docs/index.mdx
  docs/docs/introduction/index.mdx
  docs/docs/llms/openai/notebooks/openai-code-helper.ipynb
  docs/docs/traditional-ml/hyperparameter-tuning-with-child-runs/notebooks/hyperparameter-tuning-with-child-runs.ipynb
  docs/src/content/platform.mdx
  docs/static/images/logos/nebius-logo.png
  mlflow/dspy/wrapper.py
  mlflow/ml-package-versions.yml
  mlflow/openai/_openai_autolog.py
  mlflow/openai/utils/chat_schema.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
  mlflow/pyfunc/utils/data_validation.py
  mlflow/tracing/__init__.py
  mlflow/tracing/destination.py
  mlflow/tracing/export/databricks_agent.py
  mlflow/tracing/processor/databricks_agent.py
  mlflow/tracing/processor/mlflow.py
  mlflow/tracing/provider.py
  mlflow/tracing/utils/__init__.py
  mlflow/tracking/_tracking_service/utils.py
  mlflow/tracking/client.py
  mlflow/types/type_hints.py
  mlflow/types/utils.py
  mlflow/utils/uri.py
  tests/conftest.py
  tests/crewai/test_crewai_autolog.py
  tests/langchain/test_langchain_model_export.py
  tests/litellm/test_litellm_autolog.py
  tests/openai/test_openai_autolog.py
  tests/pyfunc/test_pyfunc_model_with_type_hints.py
  tests/tracing/export/test_databricks_agent_exporter.py
  tests/tracing/processor/test_mlflow_processor.py
  tests/tracing/test_provider.py
  tests/tracking/test_mlflow_artifacts.py
  tests/types/test_type_hints.py
  tests/utils/test_uri.py
Labels: rn/none

#14304 Rebase again
  docs/docs/tracing/faq.mdx
  mlflow/environment_variables.py
  mlflow/models/utils.py
  mlflow/tracing/fluent.py
  mlflow/tracing/processor/mlflow.py
  mlflow/tracing/provider.py
  mlflow/tracing/trace_manager.py
  mlflow/tracing/utils/timeout.py
  mlflow/tracing/utils/token.py
  mlflow/tracing/utils/warning.py
  tests/conftest.py
  tests/tracing/helper.py
  tests/tracing/test_trace_manager.py
  tests/tracing/utils/test_timeout.py
  tests/tracing/utils/test_warning.py
Labels: rn/none

#14296 Unify validation messages with GO backend.
  mlflow/utils/validation.py
  tests/store/model_registry/test_file_store.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, area/tracking

#14308 Migrate `llms/langchain/index.rst` to MDX
  docs/docs/llms/langchain/index.mdx
  docs/rst_to_migrate/llms/langchain/index.rst
Labels: rn/none

#14320 Add virtual meetup link to README.md
  README.md
Labels: rn/none

#14309 Migrate `llms/langchain/autologging.rst` to MDX
  docs/docs/llms/langchain/autologging.mdx
  docs/rst_to_migrate/llms/langchain/autologging.rst
Labels: rn/none

#14310 Migrate `llms/langchain/guide/index.rst` to MDX
  docs/docs/llms/langchain/guide/index.mdx
  docs/rst_to_migrate/llms/langchain/guide/index.rst
  mlflow/langchain/retriever_chain.py
Labels: rn/none

#14323 Detect typos in MDX files in docs
  .pre-commit-config.yaml
  docs/docs/auth/index.mdx
  docs/docs/community-model-flavors/index.mdx
  docs/docs/deployment/deploy-model-to-kubernetes/index.mdx
  docs/docs/deployment/deploy-model-to-kubernetes/tutorial/index.mdx
  docs/docs/getting-started/community-edition/index.mdx
  docs/docs/getting-started/index.mdx
  docs/docs/getting-started/logging-first-model/step3-create-experiment/index.mdx
  docs/docs/getting-started/registering-first-model/step2-explore-registered-model/index.mdx
  docs/docs/getting-started/tracking-server-overview/index.mdx
  docs/docs/llms/chat-model-guide/index.mdx
  docs/docs/llms/transformers/guide/index.mdx
  docs/docs/model-registry/index.mdx
  docs/docs/model/dependencies/index.mdx
  docs/docs/model/models-from-code/index.mdx
  docs/docs/models/index.mdx
  docs/docs/projects/index.mdx
  docs/docs/recipes/index.mdx
  docs/docs/search-runs/index.mdx
  docs/docs/tracing/tracing-schema.mdx
  docs/docs/tracking/artifacts-stores/index.mdx
  docs/docs/tracking/index.mdx
  docs/docs/tracking/server/index.mdx
  docs/docs/tracking/tutorials/local-database/index.mdx
  pyproject.toml
Labels: rn/none

#14318 Fix CHANGELOG links
  CHANGELOG.md
Labels: rn/none

#14332 Fix ChatCompletionResponse for model serving Pydantic 1.x
  docs/docs/models/index.mdx
  mlflow/types/chat.py
  tests/types/test_genai_types.py
Labels: rn/bug-fix, area/models, v2.20.1

#14322 Improve API doc rendering in docusaurus
  docs/api_reference/source/index.rst
  docs/api_reference/theme/mlflow/header.html
  docs/api_reference/theme/mlflow/static/css/custom.css
  docs/api_reference/theme/mlflow/static/css/theme.css
  docs/api_reference/theme/mlflow/static/js/custom.js
Labels: rn/none

#14326 Add suffix and ignore generated notebook MDX files
  .gitignore
  docs/scripts/convert-notebooks.py
Labels: rn/none

#14250 Do not mutate output column in pyspark autolog
  mlflow/pyspark/ml/__init__.py
  mlflow/spark/__init__.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
Labels: rn/none

#14338 [Maintenanc - test only fix] Fix anthropic autolog test
  tests/anthropic/test_anthropic_autolog.py
Labels: rn/none, area/tracking

#14339 [Maintenance - test only fix] Fix Gemini autolog test
  tests/gemini/test_gemini_autolog.py
Labels: rn/none, area/tracking

#14329 Add a workaround for 404 error in doc preview
  dev/preview_docs.py
Labels: rn/none

#14342 Escape curly braces in f-string
  dev/preview_docs.py
Labels: rn/none

#14335 #14330 Issue: Updated pre-commit-config.yaml to include CHANGELOG.md to be formatted by Prettier
  .pre-commit-config.yaml
  CHANGELOG.md
Labels: rn/none, v2.20.1

#14325 Edit Docusaurus README.mds
  CONTRIBUTING.md
  docs/README.md
  docs/api_reference/README.md
  docs/package.json
Labels: rn/none

#14327 Unflake test_rest_get_artifact_api_log_image
  tests/tracking/test_mlflow_artifacts.py
Labels: rn/none, autoformat, v2.20.1

#14346 Add google analytics custom event for notebook downloads
  docs/docusaurus.config.ts
  docs/src/components/NotebookDownloadButton/index.tsx
Labels: rn/none

#14348 Fix `docs/changed_pages.py` for faster review
  docs/changed_pages.py
Labels: rn/none

#14347 Add description to `pyproject.toml` files
  dev/pyproject.py
  pyproject.release.toml
  pyproject.skinny.toml
  pyproject.toml
  tests/dev/test_update_mlflow_versions.py
Labels: rn/none

#14324 Restructure the doc sidebar
  docs/docs/dataset/index.mdx
  docs/docs/deep-learning/index.mdx
  docs/docs/deep-learning/keras/index.mdx
  docs/docs/deep-learning/pytorch/index.mdx
  docs/docs/deep-learning/tensorflow/index.mdx
  docs/docs/deployment/index.mdx
  docs/docs/getting-started/intro-quickstart/index.mdx
  docs/docs/getting-started/running-notebooks/index.mdx
  docs/docs/index.mdx
  docs/docs/llms/index.mdx
  docs/docs/llms/openai/autologging/index.mdx
  docs/docs/llms/openai/guide/index.mdx
  docs/docs/llms/openai/index.mdx
  docs/docs/llms/openai/notebooks/index.mdx
  docs/docs/llms/sentence-transformers/guide/index.mdx
  docs/docs/llms/sentence-transformers/index.mdx
  docs/docs/llms/sentence-transformers/tutorials/index.mdx
  docs/docs/llms/transformers/guide/index.mdx
  docs/docs/llms/transformers/index.mdx
  docs/docs/llms/transformers/large-models/index.mdx
  docs/docs/llms/transformers/task/index.mdx
  docs/docs/llms/transformers/tutorials/index.mdx
  docs/docs/model/dependencies/index.mdx
  docs/docs/model/index.mdx
  docs/docs/model/models-from-code/index.mdx
  docs/docs/model/python_model.mdx
  docs/docs/model/signatures/index.mdx
  docs/docs/tracing/api/client.mdx
  docs/docs/tracing/api/how-to.mdx
  docs/docs/tracing/api/index.mdx
  docs/docs/tracing/api/manual-instrumentation.mdx
  docs/docs/tracing/api/search.mdx
  docs/docs/tracing/index.mdx
  docs/docs/tracing/notebooks/index.mdx
  docs/docs/tracking/autolog/index.mdx
  docs/docs/tracking/index.mdx
  docs/docs/tracking/server/index.mdx
  docs/docs/tracking/tracking-api/index.mdx
  docs/docs/traditional-ml/index.mdx
  docs/docusaurus.config.ts
  docs/package.json
  docs/sidebars.ts
  docs/src/css/custom.css
  docs/yarn.lock
Labels: area/docs, rn/none

#14340 Fix LiteLLM autologging
  mlflow/litellm/__init__.py
Labels: rn/bug-fix, area/tracking, v2.20.1

#14315 Migrate LLM eval RST files to MDX
  docs/docs/llms/llm-evaluate/index.mdx
  docs/docs/llms/llm-evaluate/notebooks/index.mdx
  docs/rst_to_migrate/llms/llm-evaluate/index.rst
  docs/rst_to_migrate/llms/llm-evaluate/notebooks/index.rst
Labels: rn/none

#14353 Fix validation for rename registered model logic.
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/utils/validation.py
  tests/store/model_registry/test_sqlalchemy_store.py
Labels: rn/none, area/tracking

#14354 use aes256 to talk to s3
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/utils/_unity_catalog_utils.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/utils/test_unity_catalog_utils.py
Labels: rn/bug-fix, area/model-registry, autoformat, v2.20.1

#14350 Show warning in docs preview
  .circleci/config.yml
  docs/docusaurus.config.ts
Labels: rn/none

#14356 Fix doc link
  docs/source/platform.rst
Labels: rn/none

#14337 Update client._log_trace to handle empty experiment ID
  mlflow/tracking/client.py
  tests/tracking/test_client.py
Labels: rn/none, area/tracking, v2.20.1

#14360 Fix url parse logic for Databricks multi workspace usecase
  mlflow/store/artifact/models_artifact_repo.py
  tests/store/artifact/test_models_artifact_repo.py
Labels: rn/none, v2.20.1

#14349 Warn if there is a version mismatch between mlflow and mlflow-skinny
  mlflow/__init__.py
  mlflow/mismatch.py
  tests/test_mismatch.py
Labels: rn/none

#14358 Fix typo in deploy model locally documentation
  docs/docs/deployment/deploy-model-locally/index.mdx
Labels: area/docs, rn/none

#14343 Fix false alert for ChatModel type hint
  mlflow/pyfunc/model.py
  tests/pyfunc/test_pyfunc_model_with_type_hints.py
Labels: rn/bug-fix, area/models, v2.20.1

#14362 More unification of validation
  mlflow/utils/validation.py
  tests/store/model_registry/test_file_store.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/tracking/test_model_registry.py
Labels: rn/none, area/tracking

#14215 ChatAgent LangGraph and LangChain Connectors
  mlflow/langchain/chat_agent_langchain.py
  mlflow/langchain/chat_agent_langgraph.py
  mlflow/langchain/output_parsers.py
  mlflow/langchain/utils/chat.py
  tests/langchain/conftest.py
  tests/langchain/sample_code/langchain_chat_agent.py
  tests/langchain/sample_code/langgraph_chat_agent.py
  tests/langchain/test_chat_agent_langchain.py
  tests/langchain/test_chat_agent_langgraph.py
  tests/langchain/test_langchain_output_parsers.py
Labels: rn/feature, area/models, v2.20.1

#14371 Update doc for fastapi local serving
  docs/docs/deployment/deploy-model-locally/index.mdx
  docs/static/images/logos/fastapi-logo.svg
  docs/static/images/logos/flask-logo.png
Labels: rn/none

#14333 adding catboost flavor as a recognized flavor by default classifier evaluator that has a predict_proba fn
  mlflow/models/evaluation/default_evaluator.py
Labels: rn/none, area/models, v2.20.1

#14379 Fix image path on the top page
  docs/source/getting-started/running-notebooks.rst
  docs/source/index.rst
  docs/source/introduction/index.rst
  docs/source/platform.rst
Labels: rn/none

#14378 Drop Spacy <3.3 support
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
Labels: rn/none, area/build

#14359 Remove `docs/package-lock.json`
  docs/package-lock.json
Labels: rn/none

#14369 Fix `SpanEvent._get_stacktrace` to fix stacktrace formatting
  mlflow/entities/span_event.py
Labels: rn/none
