Repository mlflow/mlflow, pull requests merged in 2025-10, with the labels that each got.

#18012 Job backend: Create individual execution pool for each job function
  .github/workflows/master.yml
  .github/workflows/tracing.yaml
  .github/workflows/uc-oss.yml
  mlflow/entities/_job.py
  mlflow/environment_variables.py
  mlflow/server/__init__.py
  mlflow/server/job_api.py
  mlflow/server/job_functions.py
  mlflow/server/jobs/__init__.py
  mlflow/server/jobs/_huey_consumer.py
  mlflow/server/jobs/_job_runner.py
  mlflow/server/jobs/job_runner.py
  mlflow/server/jobs/util.py
  mlflow/store/db/utils.py
  tests/server/jobs/test_endpoint.py
  tests/server/jobs/test_job.py
  tests/server/test_init.py
Labels: rn/feature, area/tracking, team-review, area/tracing, area/evaluation

#18038 Fixes a typo in the documentation
  docs/docs/classic-ml/model-registry/workflow.mdx
Labels: rn/documentation, area/model-registry, v3.4.1

#18021 Add model_id param to update_current_trace
  mlflow/tracing/fluent.py
  tests/tracing/test_fluent.py
Labels: rn/none, area/tracing, v3.4.1

#18049 Job backend: allow explicitly setting job function to run in an individual process
  mlflow/server/jobs/__init__.py
  mlflow/server/jobs/util.py
  tests/server/jobs/test_job.py
Labels: rn/feature, area/tracking, area/tracing, area/evaluation

#18024 Pass sql warehouse Id to GetTraces
  mlflow/cli/traces.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/databricks_rest_store.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracing/client.py
  mlflow/tracing/fluent.py
  mlflow/tracking/client.py
  tests/store/tracking/test_databricks_rest_store.py
  tests/tracing/test_fluent.py
  tests/tracking/test_client.py
Labels: rn/none, area/tracing

#17928 Judges bug fix - return trace ID in feedback
  mlflow/genai/judges/utils.py
  tests/genai/judges/test_judge_utils.py
Labels: rn/none, area/evaluation, v3.4.1

#18029 Add interface for `adapt_prompts`
  docs/api_reference/api_inventory.txt
  mlflow/genai/__init__.py
  mlflow/genai/optimize/__init__.py
  mlflow/genai/optimize/adapt.py
  mlflow/genai/optimize/adapters/__init__.py
  mlflow/genai/optimize/adapters/base.py
  mlflow/genai/optimize/types.py
  tests/genai/optimize/test_adapt.py
Labels: rn/none, team-review, area/prompts, v3.4.1

#18054 Re-enable macOS CI as GitHub incident is being resolved
  .github/workflows/lint.yml
Labels: rn/none, area/build, team-review

#18039 Fix judge regression
  mlflow/genai/judges/utils.py
  tests/genai/judges/test_judge_utils.py
  tests/genai/judges/test_make_judge.py
Labels: rn/bug-fix, area/evaluation, v3.4.1

#18001 Fix trace table search bug
  mlflow/server/js/src/shared/web-shared/genai-traces-table/hooks/useMlflowTraces.tsx
Labels: rn/none, area/uiux, team-review, v3.4.1

#18030 Fix trace attribute name in dataset documentation
  docs/docs/genai/datasets/index.mdx
Labels: team-review, v3.4.1

#18073 Job backend: Set tracking uri environment variable for job runner
  mlflow/server/__init__.py
  tests/server/jobs/test_endpoint.py
Labels: rn/bug-fix, area/tracking, area/tracing

#18074 CreateTraceInfo v4
  mlflow/protos/databricks_tracing.proto
  mlflow/protos/databricks_tracing_pb2.py
  mlflow/protos/databricks_tracing_pb2.pyi
  mlflow/store/tracking/databricks_rest_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/utils/databricks_tracing_utils.py
  tests/store/tracking/test_databricks_rest_store.py
  tests/tracing/export/test_mlflow_v3_exporter.py
Labels: rn/none, area/tracing

#17879 Move get_metric_history_bulk_interval to abstract store
  mlflow/server/handlers.py
  mlflow/store/tracking/__init__.py
  mlflow/store/tracking/abstract_store.py
  tests/store/tracking/test_abstract_store.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, v3.4.1

#18097 Update CreateTraceInfo v4 body
  mlflow/store/tracking/databricks_rest_store.py
  tests/store/tracking/test_databricks_rest_store.py
Labels: rn/none, area/tracing

#18071 Job backend: add last_update_time column for job table, for counting job pending / execution time
  mlflow/entities/_job.py
  mlflow/server/job_api.py
  mlflow/store/db_migrations/versions/bf29a5ff90ea_add_jobs_table.py
  mlflow/store/jobs/sqlalchemy_store.py
  mlflow/store/tracking/dbmodels/models.py
  tests/db/schemas/mssql.sql
  tests/db/schemas/mysql.sql
  tests/db/schemas/postgresql.sql
  tests/db/schemas/sqlite.sql
  tests/resources/db/latest_schema.sql
  tests/server/jobs/test_endpoint.py
Labels: rn/feature, area/tracking, team-review

#18070 Job backend: Add Job search endpoint, for front-end code to search jobs by function / params / job status
  mlflow/entities/_job_status.py
  mlflow/server/job_api.py
  mlflow/server/job_functions.py
  mlflow/server/jobs/__init__.py
  mlflow/store/jobs/abstract_store.py
  mlflow/store/jobs/sqlalchemy_store.py
  tests/server/jobs/test_endpoint.py
  tests/server/jobs/test_jobs.py
  tests/server/jobs/test_utils.py
Labels: rn/feature, area/tracking, area/evaluation

#18101 Fix flaky `test_otel_logging` by caching database initialization
  tests/tracing/test_otel_logging.py
Labels: rn/none, team-review, v3.4.1

#18072 Add GepaPromptAdapter
  mlflow/genai/optimize/adapt.py
  mlflow/genai/optimize/adapters/__init__.py
  mlflow/genai/optimize/adapters/gepa_adapter.py
  mlflow/genai/optimize/optimizers/dspy_mipro_optimizer.py
  mlflow/genai/optimize/optimizers/dspy_optimizer.py
  mlflow/genai/optimize/optimizers/utils/__init__.py
  mlflow/genai/optimize/optimizers/utils/dspy_optimizer_utils.py
  mlflow/genai/optimize/types.py
  requirements/test-requirements.txt
  tests/genai/optimize/adapters/test_gepa_adapter.py
  tests/genai/optimize/optimizers/test_dspy_optimizer.py
  tests/genai/optimize/optimizers/utils/test_dspy_optimizer_utils.py
Labels: rn/none, team-review, area/prompts

#18118 Update assessment protos to match v4 spec
  mlflow/protos/databricks_tracing.proto
  mlflow/protos/databricks_tracing_pb2.py
  mlflow/protos/databricks_tracing_pb2.pyi
Labels: rn/none, area/tracing

#18026 Update docs for claude code SDK tracing
  docs/docs/genai/tracing/integrations/listing/claude_code.mdx
Labels: rn/documentation, area/tracking, rn/highlight

#18124 Fix flaky job test by pre-initializing database to avoid race conditions
  tests/server/jobs/test_jobs.py
Labels: rn/none

#18112 Job backend: Support setting a list for transient error classes
  mlflow/environment_variables.py
  mlflow/server/jobs/__init__.py
  mlflow/server/jobs/utils.py
  tests/server/jobs/test_jobs.py
Labels: rn/feature, area/tracking, area/tracing, area/evaluation

#18019 Fix Otel resource attribute failed to propagate
  mlflow/tracing/provider.py
Labels: rn/bug-fix, area/tracing, v3.4.1

#18081 Fix Dataset issue
  mlflow/data/dataset.py
  tests/data/test_meta_dataset.py
Labels: rn/bug-fix, area/models

#18052 Delete parent child run together
  mlflow/server/js/src/experiment-tracking/components/modals/DeleteRunModal.enzyme.test.tsx
  mlflow/server/js/src/experiment-tracking/components/modals/DeleteRunModal.tsx
Labels: rn/feature, area/uiux

#18083 Fix discrepancies between `reset.css` and databricks design system
  mlflow/server/js/src/reset.css
Labels: rn/none, area/uiux

#18077 [Datasets UI][1/x] Bump design system version
  mlflow/server/js/package.json
  mlflow/server/js/yarn.lock
Labels: rn/none, team-review

#18106 Make spans/logs table name fields in the trace location private
  docs/api_reference/api_inventory.txt
  mlflow/entities/trace_location.py
  mlflow/store/tracking/databricks_rest_store.py
  mlflow/tracing/processor/uc_table.py
  mlflow/utils/databricks_tracing_utils.py
  tests/entities/test_trace_location.py
  tests/store/tracking/test_databricks_rest_store.py
  tests/tracing/helper.py
  tests/tracing/processor/test_uc_table_processor.py
  tests/tracing/test_enablement.py
  tests/utils/test_databricks_tracing_utils.py
Labels: rn/none, area/tracing

#18082 Fix logged models not showing up in run details page
  mlflow/server/js/src/common/utils/FeatureUtils.ts
  mlflow/server/js/src/experiment-tracking/components/run-page/RunViewOverview.intg.test.tsx
Labels: rn/none, area/uiux, team-review, v3.4.1

#18103 Update search_traces V4
  mlflow/store/tracking/databricks_rest_store.py
  tests/store/tracking/test_databricks_rest_store.py
Labels: rn/none, area/tracing

#17910 Add a security middleware layer to MLflow Tracking Server
  docs/docs/classic-ml/getting-started/logging-first-model/step1-tracking-server.mdx
  docs/docs/classic-ml/tracking/server/index.mdx
  docs/docs/classic-ml/tracking/server/security/configuration.mdx
  docs/docs/classic-ml/tracking/server/security/index.mdx
  docs/docs/classic-ml/tracking/server/security/ui-access.mdx
  docs/sidebars.ts
  docs/sidebarsClassicML.ts
  examples/mlflow_artifacts/docker-compose.yml
  mlflow/cli/__init__.py
  mlflow/environment_variables.py
  mlflow/server/AGENTS.md
  mlflow/server/__init__.py
  mlflow/server/fastapi_app.py
  mlflow/server/fastapi_security.py
  mlflow/server/js/nohup.out
  mlflow/server/security.py
  mlflow/server/security_utils.py
  mlflow/utils/cli_args.py
  pyproject.release.toml
  pyproject.toml
  requirements/core-requirements.yaml
  tests/server/conftest.py
  tests/server/test_security.py
  tests/server/test_security_integration.py
  uv.lock
Labels: rn/feature, area/tracking, team-review

#18153 Improve error message for search_traces
  mlflow/tracing/client.py
  mlflow/tracing/fluent.py
  mlflow/utils/validation.py
  tests/tracing/test_fluent.py
  tests/tracking/test_client.py
  tests/utils/test_validation.py
Labels: rn/none, area/tracking, team-review, v3.4.1

#18105 [Datasets UI][7/x] Add table component for dataset rows (right pane)
  mlflow/server/js/src/experiment-tracking/pages/experiment-evaluation-datasets/components/ExperimentEvaluationDatasetJsonCell.tsx
  mlflow/server/js/src/experiment-tracking/pages/experiment-evaluation-datasets/components/ExperimentEvaluationDatasetRecordsTable.tsx
  mlflow/server/js/src/experiment-tracking/pages/experiment-evaluation-datasets/components/ExperimentEvaluationDatasetRecordsToolbar.tsx
  mlflow/server/js/src/lang/default/en.json
Labels: rn/none, area/uiux

#18110 [Datasets UI][11/x] Polish dataset empty states
  mlflow/server/js/src/experiment-tracking/pages/experiment-evaluation-datasets/ExperimentEvaluationDatasetsPage.tsx
  mlflow/server/js/src/experiment-tracking/pages/experiment-evaluation-datasets/components/ExperimentEvaluationDatasetsEmptyState.tsx
  mlflow/server/js/src/experiment-tracking/pages/experiment-evaluation-datasets/components/ExperimentEvaluationDatasetsListTable.tsx
  mlflow/server/js/src/lang/default/en.json
Labels: rn/none, area/uiux

#18098 In product onboarding 0
  mlflow/server/js/src/common/components/MlflowSidebar.tsx
  mlflow/server/js/src/experiment-tracking/components/ExperimentListTable.tsx
  mlflow/server/js/src/experiment-tracking/route-defs.ts
  mlflow/server/js/src/experiment-tracking/routes.ts
  mlflow/server/js/src/home/HomePage.tsx
  mlflow/server/js/src/home/components/DiscoverNews.test.tsx
  mlflow/server/js/src/home/components/DiscoverNews.tsx
  mlflow/server/js/src/home/components/ExperimentsHomeView.test.tsx
  mlflow/server/js/src/home/components/ExperimentsHomeView.tsx
  mlflow/server/js/src/home/components/GetStarted.test.tsx
  mlflow/server/js/src/home/components/GetStarted.tsx
  mlflow/server/js/src/home/news-items.tsx
  mlflow/server/js/src/home/quick-actions.tsx
  mlflow/server/js/src/home/types.ts
  mlflow/server/js/src/lang/default/en.json
Labels: rn/feature, area/uiux

#18113 Deprecate destination and add env var for setting location
  docs/api_reference/api_inventory.txt
  docs/api_reference/source/python_api/mlflow.tracing.rst
  docs/docs/genai/tracing/faq.mdx
  mlflow/entities/trace_location.py
  mlflow/environment_variables.py
  mlflow/tracing/destination.py
  mlflow/tracing/export/uc_table.py
  mlflow/tracing/fluent.py
  mlflow/tracing/provider.py
  mlflow/tracing/utils/__init__.py
  tests/entities/test_trace_location.py
  tests/store/tracking/test_databricks_rest_store.py
  tests/tracing/export/test_mlflow_v3_exporter.py
  tests/tracing/test_destination.py
  tests/tracing/test_provider.py
  tests/tracing/utils/test_utils.py
  tests/utils/test_databricks_tracing_utils.py
Labels: rn/none, area/tracing

#18031 Support GEPA in mlflow.genai.optimize_prompt
  docs/docs/genai/prompt-registry/optimize-prompts.mdx
  mlflow/genai/optimize/base.py
  mlflow/genai/optimize/optimizers/__init__.py
  mlflow/genai/optimize/optimizers/base_optimizer.py
  mlflow/genai/optimize/optimizers/dspy_optimizer.py
  mlflow/genai/optimize/optimizers/gepa_optimizer.py
  tests/genai/optimize/optimizers/test_gepa_optimizer.py
  tests/genai/optimize/test_base.py
Labels: rn/feature, team-review, area/prompts, v3.4.1

#18134 Add doc page for Rewrite Prompts
  docs/docs/genai/prompt-registry/adapt-prompts.mdx
  docs/sidebarsGenAI.ts
  docs/static/images/adapt_prompt_flow.svg
Labels: area/docs, rn/none, team-review

#17927 Fix documentation: update deprecated pandas fillna usage in classic-ml tutorial
  docs/docs/classic-ml/getting-started/logging-first-model/step5-synthetic-data.mdx
Labels: area/docs, rn/documentation, v3.4.1
