Repository mlflow/mlflow, pull requests merged in 2025-02, with the labels that each got.

#14370 Update models from code guide and chat model guide to always recommend models from code
  docs/docs/llms/chat-model-guide/index.mdx
  docs/docs/model/models-from-code/index.mdx
Labels: area/docs, rn/documentation

#14399 Turn `PytestUnhandledCoroutineWarning` into an error
  pytest.ini
  tests/gateway/providers/test_palm.py
Labels: rn/none

#14410 Remove `ChatMessage.tool_calls min_items` validation
  mlflow/types/chat.py
Labels: rn/none

#14395 Add intermediate_outputs property to trace
  mlflow/entities/trace.py
  mlflow/tracing/constant.py
  tests/entities/test_trace.py
Labels: rn/none, area/tracking

#14408 [Fix Docusaurus Links][1/2] Fix all broken links
  docs/docs/deep-learning/index.mdx
  docs/docs/deep-learning/tensorflow/guide/index.mdx
  docs/docs/deployment/deploy-model-to-kubernetes/tutorial/index.mdx
  docs/docs/deployment/index.mdx
  docs/docs/getting-started/registering-first-model/step1-register-model/index.mdx
  docs/docs/getting-started/registering-first-model/step2-explore-registered-model/index.mdx
  docs/docs/index.mdx
  docs/docs/introduction/index.mdx
  docs/docs/llms/chat-model-guide/index.mdx
  docs/docs/llms/custom-pyfunc-for-llms/index.mdx
  docs/docs/llms/custom-pyfunc-for-llms/notebooks/index.mdx
  docs/docs/llms/deployments/index.mdx
  docs/docs/llms/dspy/index.mdx
  docs/docs/llms/index.mdx
  docs/docs/llms/langchain/index.mdx
  docs/docs/llms/llama-index/index.mdx
  docs/docs/llms/llm-evaluate/index.mdx
  docs/docs/llms/llm-evaluate/notebooks/index.mdx
  docs/docs/llms/openai/autologging/index.mdx
  docs/docs/llms/openai/index.mdx
  docs/docs/llms/openai/notebooks/index.mdx
  docs/docs/llms/prompt-engineering/index.mdx
  docs/docs/llms/rag/notebooks/index.mdx
  docs/docs/llms/sentence-transformers/guide/index.mdx
  docs/docs/llms/sentence-transformers/index.mdx
  docs/docs/llms/sentence-transformers/tutorials/index.mdx
  docs/docs/llms/transformers/guide/index.mdx
  docs/docs/llms/transformers/index.mdx
  docs/docs/llms/transformers/task/index.mdx
  docs/docs/llms/transformers/tutorials/index.mdx
  docs/docs/model-evaluation/index.mdx
  docs/docs/model/dependencies/index.mdx
  docs/docs/model/index.mdx
  docs/docs/model/models-from-code/index.mdx
  docs/docs/model/python_model.mdx
  docs/docs/model/signatures/index.mdx
  docs/docs/new-features/index.mdx
  docs/docs/plugins/index.mdx
  docs/docs/quickstart_drilldown/index.mdx
  docs/docs/tracing/api/client.mdx
  docs/docs/tracing/api/manual-instrumentation.mdx
  docs/docs/tracing/concept.mdx
  docs/docs/tracing/index.mdx
  docs/docs/tracing/integrations/contribute.mdx
  docs/docs/tracing/integrations/langgraph.mdx
  docs/docs/tracing/notebooks/index.mdx
  docs/docs/tracing/session.mdx
  docs/docs/tracing/tracing-schema.mdx
  docs/docs/tracking/autolog/index.mdx
  docs/docs/tracking/index.mdx
  docs/docs/traditional-ml/index.mdx
  docs/docusaurus.config.ts
  docs/scripts/convert-notebooks.py
  docs/sidebars.ts
Labels: rn/none

#14407 [Fix Docusaurus Links][2/2] Fix broken anchors
  docs/docs/deployment/deploy-model-to-kubernetes/tutorial/index.mdx
  docs/docs/introduction/index.mdx
  docs/docs/llms/index.mdx
  docs/docs/llms/langchain/index.mdx
  docs/docs/llms/llm-evaluate/index.mdx
  docs/docs/llms/prompt-engineering/index.mdx
  docs/docs/llms/transformers/guide/index.mdx
  docs/docs/llms/transformers/index.mdx
  docs/docs/model-evaluation/index.mdx
  docs/docs/model/dependencies/index.mdx
  docs/docs/model/index.mdx
  docs/docs/new-features/index.mdx
  docs/docs/plugins/index.mdx
  docs/docs/projects/index.mdx
  docs/docs/recipes/index.mdx
  docs/docs/search-runs/index.mdx
  docs/docs/tracing/integrations/contribute.mdx
  docs/docs/tracing/session.mdx
  docs/docs/tracing/tracing-schema.mdx
  docs/docs/tracking/index.mdx
  docs/docusaurus.config.ts
Labels: rn/none

#14412 Restore `test-examples`
  .circleci/config.yml
  mlflow/tracking/fluent.py
Labels: rn/none

#14398 Update announcements on README
  README.md
Labels: rn/none

#14419 Fix `PyFuncModel.input_example`
  mlflow/pyfunc/__init__.py
Labels: rn/none

#14374 updated ruff to 0.9.3
  dev/generate_requirements.py
  dev/proto_to_graphql/schema_autogeneration.py
  dev/set_matrix.py
  docs/docs/deep-learning/pytorch/quickstart/pytorch_quickstart.ipynb
  docs/docs/llms/langchain/notebooks/langchain-quickstart.ipynb
  docs/docs/llms/langchain/notebooks/langchain-retriever.ipynb
  docs/docs/llms/rag/notebooks/question-generation-retrieval-evaluation.ipynb
  docs/docs/llms/transformers/tutorials/text-generation/text-generation.ipynb
  examples/gateway/uc_functions/run.py
  examples/langchain/retrieval_qa_chain_azure_openai.py
  examples/llms/RAG/question-generation-retrieval-evaluation.ipynb
  examples/llms/question_answering/question_answering.py
  examples/llms/summarization/summarization.py
  mlflow/cli.py
  mlflow/gateway/uc_function_utils.py
  mlflow/models/signature.py
  mlflow/projects/_project_spec.py
  mlflow/recipes/steps/split.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tensorflow/__init__.py
  mlflow/types/schema.py
  mlflow/utils/autologging_utils/events.py
  mlflow/utils/autologging_utils/safety.py
  mlflow/utils/conda.py
  mlflow/utils/gorilla.py
  mlflow/utils/model_utils.py
  mlflow/utils/search_utils.py
  mlflow/utils/uri.py
  mlflow/xgboost/__init__.py
  pyproject.toml
  requirements/lint-requirements.txt
  tests/conftest.py
  tests/crewai/test_crewai_autolog.py
  tests/dspy/test_dspy_autolog.py
  tests/helper_functions.py
  tests/models/test_cli.py
  tests/pytorch/test_pytorch_autolog.py
  tests/recipes/test_ingest_step.py
  tests/sagemaker/mock/__init__.py
  tests/server/auth/test_auth.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
  tests/store/artifact/test_databricks_artifact_repo.py
  tests/store/artifact/test_local_artifact_repo.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tensorflow/test_keras_model_export.py
  tests/tracking/test_mlflow_artifacts.py
Labels: rn/none, area/deployments

#14421 Fix `SqlAlchemyStore.log_inputs`
  .github/workflows/sync.py
  mlflow/store/tracking/sqlalchemy_store.py
Labels: rn/none

#14424 Fix `_parse_model_id_if_present` to handle pathlib.Path
  mlflow/store/artifact/utils/models.py
Labels: rn/none

#14425 Fix `Model.log` by making name optional
  mlflow/models/model.py
Labels: rn/none

#14426 Improve `NotImplementedError`
  mlflow/store/tracking/abstract_store.py
Labels: rn/none

#14377 Remove system message from ChatModel/ChatAgent examples
  mlflow/types/agent.py
  mlflow/types/llm.py
Labels: rn/none, area/models

#14414 Add a job to sync mlflow-3 branch with master
  .github/workflows/sync.md
  .github/workflows/sync.py
  .github/workflows/sync.yml
Labels: rn/none

#14431 Set `fetch-depth` when checking out in sync job
  .github/workflows/sync.yml
Labels: rn/none

#14428 Hack to make tests failing with `NotImplementedError("SqlAlchemyStore")` as `xfailed`
  conftest.py
Labels: rn/none

#14363 Minor tracing doc update
  docs/docs/tracing/api/how-to.mdx
  docs/docs/tracing/index.mdx
  docs/docs/tracing/integrations/contribute.mdx
  docs/docs/tracing/production.mdx
  docs/docs/tracing/tutorials/concept.mdx
  docs/docs/tracing/tutorials/index.mdx
  docs/docs/tracing/tutorials/jupyter-trace-demo.ipynb
  docs/docs/tracing/ui.mdx
  docs/static/images/logos/datadog-logo.png
  docs/static/images/logos/grafana-logo.png
  docs/static/images/logos/new-relic-logo.png
  docs/static/images/logos/servicenow-logo.avif
  docs/static/images/logos/signoz-logo.svg
  docs/static/images/logos/splunk-logo.png
Labels: area/docs, rn/none

#14411 Fix pytorch-related test failures
  mlflow/pytorch/__init__.py
  tests/pytorch/test_pytorch_model_export.py
Labels: rn/none

#14440 Support structured outputs for OpenAI autolog
  mlflow/openai/__init__.py
  mlflow/openai/_openai_autolog.py
  tests/openai/test_openai_autolog.py
Labels: rn/none

#14448 Fix build.py to restore specific files #14444
  dev/build.py
Labels: rn/bug-fix, area/build

#14449 Removed redundant newline characters in `get_stacktrace` function (Issue #14438)
  mlflow/utils/exception_utils.py
Labels: rn/none, v2.20.2

#14450 Expose environment variable declaration for deployment client timeouts in docs
  mlflow/environment_variables.py
  mlflow/pyfunc/scoring_server/__init__.py
Labels: area/docs, rn/none, v2.20.2

#14453 Bump min pydantic version to 1.10.8
  pyproject.skinny.toml
  pyproject.toml
  requirements/skinny-requirements.txt
  requirements/skinny-requirements.yaml
Labels: rn/none, v2.20.2

#14418 Add mlflow.log_trace API
  mlflow/__init__.py
  mlflow/entities/trace.py
  mlflow/entities/trace_data.py
  mlflow/tracing/constant.py
  mlflow/tracing/fluent.py
  tests/entities/test_trace.py
  tests/entities/test_trace_data.py
  tests/tracing/test_fluent.py
Labels: rn/feature, area/tracking

#14416 Add limit to the length of experiment artifact locations
  mlflow/environment_variables.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/utils/validation.py
  tests/utils/test_validation.py
Labels: rn/bug-fix

#14022 Add CSRF protection to create users route for the UI
  dev/pyproject.py
  docs/docs/auth/index.mdx
  mlflow/environment_variables.py
  mlflow/server/__init__.py
  mlflow/server/auth/__init__.py
  mlflow/server/auth/routes.py
  pyproject.release.toml
  pyproject.skinny.toml
  pyproject.toml
  requirements/doc-requirements.txt
  requirements/test-requirements.txt
  tests/server/auth/test_auth.py
  tests/server/auth/test_client.py
Labels: rn/none, v2.20.2

#14456 Pin pytorch version in spark models cross-version test
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#14460 Add 'iternal' as a typo of 'internal' in the 'pyproject.toml' typos.
  pyproject.toml
Labels: rn/none, area/build

#14328 Type hint doc fix
  docs/docs/model/index.mdx
  docs/docs/model/signatures/index.mdx
Labels: rn/none

#14368 Update ChatAgent
  mlflow/langchain/chat_agent_langchain.py
  mlflow/langchain/chat_agent_langgraph.py
  mlflow/langchain/output_parsers.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/loaders/chat_agent.py
  mlflow/pyfunc/model.py
  mlflow/pyfunc/utils/data_validation.py
  mlflow/types/agent.py
  tests/langchain/sample_code/langgraph_chat_agent.py
  tests/langchain/test_chat_agent_langchain.py
  tests/langchain/test_chat_agent_langgraph.py
  tests/langchain/test_langchain_output_parsers.py
  tests/pyfunc/test_chat_agent.py
Labels: rn/none, area/models, v2.20.2

#14467 Fix doc of remote tracking server
  docs/docs/tracking/tutorials/remote-server/index.mdx
  examples/mlflow_artifacts/docker-compose.yml
Labels: area/docs, rn/none, v2.20.2

#14364 Fix API reference link in preview
  .circleci/config.yml
  docs/sidebars.ts
Labels: rn/none

#14469 Update Protos for Runs and Logged Model Inputs and Outputs
  examples/mlflow-3/proto_inputs_outputs.py
  mlflow/entities/logged_model_input.py
  mlflow/entities/logged_model_output.py
  mlflow/entities/run.py
  mlflow/entities/run_inputs.py
  mlflow/entities/run_outputs.py
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
  mlflow/server/graphql/autogenerated_graphql_schema.py
  mlflow/server/js/src/graphql/autogenerated_schema.gql
Labels: rn/none, area/tracking

#14477 Add a note for changed pages
  dev/preview_docs.py
Labels: rn/none

#14476 Detect invalid examples in class docstrings
  dev/clint/src/clint/linter.py
  mlflow/pyfunc/dbconnect_artifact_cache.py
Labels: rn/none

#14478 Fix Cross version test for Groq >= 0.17.0
  tests/groq/test_groq_autolog.py
Labels: rn/none, v2.20.2

#14479 Bump CircleCI doc worker size
  .circleci/config.yml
Labels: rn/none

#14484 Add type hint link to 2.20 doc
  docs/source/model/signatures.rst
Labels: rn/none

#14457 Generate intermediate_outputs from spans
  mlflow/entities/trace_data.py
  tests/entities/test_trace_data.py
Labels: rn/none

#14461 Open left most tab by default
  mlflow/server/js/public/lib/ml-model-trace-renderer/css/825.b6918afe.chunk.css
  mlflow/server/js/public/lib/ml-model-trace-renderer/index.html
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/115.7273ffb2.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/172.c9efca7d.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/183.db57cc9c.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/307.e6739582.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/319.880f77a5.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/323.0c47eb8b.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/328.9a0abed5.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/331.2939438d.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/381.d5736c28.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/406.60233b08.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/458.e2874262.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/513.a3aeb043.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/517.7fb7d4e2.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/54.057c12f5.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/799.26151587.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/825.b75d4fbf.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/833.f257d1fc.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/834.b5f97905.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/836.d7cccbee.chunk.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/ml-model-trace-renderer.49991d52.js
  mlflow/server/js/public/lib/ml-model-trace-renderer/js/ml-model-trace-renderer.e7df4ffa.js
  mlflow/server/js/public/lib/notebook-trace-renderer/css/661.b6918afe.chunk.css
  mlflow/server/js/public/lib/notebook-trace-renderer/index.html
  mlflow/server/js/public/lib/notebook-trace-renderer/js/115.7273ffb2.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/183.db57cc9c.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/319.12e540f7.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/323.0c47eb8b.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/328.9a0abed5.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/331.2939438d.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/393.2c4073ce.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/406.60233b08.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/474.2058c1b9.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/517.5f61ae21.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/661.89652607.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/760.ec2c5bfc.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/834.b5f97905.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/836.d7cccbee.chunk.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/ml-model-trace-renderer.befec5f4.js
  mlflow/server/js/public/lib/notebook-trace-renderer/js/ml-model-trace-renderer.f5db0065.js
Labels: rn/none, v2.20.2

#14471 Fix DSPy thread issue
  mlflow/dspy/wrapper.py
Labels: rn/bug-fix, enable-dev-tests, v2.20.2

#14489 Fix blog link in "docs/docusaurus.config.ts"
  docs/docusaurus.config.ts
Labels: rn/none

#14481 [Docusaurus] Improve card shadow style
  docs/src/css/custom.css
Labels: rn/none

#14475 Support fetching trace request ID from Flask context for supporting streaming in model serving
  mlflow/tracing/processor/inference_table.py
  tests/tracing/processor/test_inference_table_processor.py
Labels: rn/none, area/tracking, v2.20.2

#14495 Fix typo in readme
  README.md
Labels: rn/none

#14488 Fix ChatAgent `load_model_and_predict` bug
  mlflow/pyfunc/loaders/chat_agent.py
  tests/pyfunc/test_chat_agent.py
Labels: rn/none, v2.20.2

#14498 Update langchain test dependency
  mlflow/ml-package-versions.yml
Labels: rn/none

#14486 Update autoformat to update db schema files
  .github/workflows/autoformat.yml
Labels: rn/none

#14500 Fix IterativePruning example
  examples/pytorch/IterativePruning/iterative_prune_mnist.py
Labels: rn/none, v2.20.2

#14491 Update ChatAgentToolNode to be compatible with LangGraph 0.2.70
  mlflow/langchain/chat_agent_langgraph.py
Labels: rn/none, area/models, v2.20.2

#14499 Enable markdown files in typo checker
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  examples/gateway/bedrock/README.md
  examples/synapseml/autologging.md
  mlflow/R/mlflow/README.md
  pyproject.toml
  tests/examples/README.md
Labels: rn/none

#14317 spark_udf VariantType support
  mlflow/pyfunc/__init__.py
Labels: rn/feature

#14473 Remove SetTraceTag call when exporting traces to MLflow Experiment
  mlflow/tracing/constant.py
  mlflow/tracing/export/mlflow.py
  mlflow/tracking/client.py
  tests/tracking/test_client.py
Labels: rn/none, area/tracking, v2.20.2

#14496 Fix describe_run JSON serialization.
  mlflow/entities/dataset.py
  mlflow/entities/dataset_input.py
  mlflow/entities/run_inputs.py
  tests/entities/test_run.py
  tests/entities/test_run_inputs.py
Labels: rn/none, area/tracking, v2.20.2

#14487 MLflow 3.0 Support Registering Model from runs:/ as well as models:/
  examples/mlflow-3/register_model.py
  mlflow/store/tracking/file_store.py
  mlflow/tracking/_model_registry/fluent.py
Labels: rn/none, area/model-registry, area/tracking

#14503 sync
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  examples/gateway/bedrock/README.md
  examples/pytorch/IterativePruning/iterative_prune_mnist.py
  examples/synapseml/autologging.md
  mlflow/R/mlflow/README.md
  mlflow/entities/dataset.py
  mlflow/entities/dataset_input.py
  mlflow/entities/run_inputs.py
  mlflow/langchain/chat_agent_langgraph.py
  mlflow/pyfunc/__init__.py
  mlflow/tracing/constant.py
  mlflow/tracing/export/mlflow.py
  mlflow/tracking/client.py
  pyproject.toml
  tests/entities/test_run.py
  tests/entities/test_run_inputs.py
  tests/examples/README.md
  tests/tracking/test_client.py
Labels: rn/none

#14507 Format and lint files in mlflow/store/db_migrations with ruff
  mlflow/store/db_migrations/env.py
  mlflow/store/db_migrations/versions/0584bdc529eb_add_cascading_deletion_to_datasets_from_experiments.py
  mlflow/store/db_migrations/versions/0a8213491aaa_drop_duplicate_killed_constraint.py
  mlflow/store/db_migrations/versions/0c779009ac13_add_deleted_time_field_to_runs_table.py
  mlflow/store/db_migrations/versions/181f10493468_allow_nulls_for_metric_values.py
  mlflow/store/db_migrations/versions/27a6a02d2cf1_add_model_version_tags_table.py
  mlflow/store/db_migrations/versions/2b4d017a5e9b_add_model_registry_tables_to_db.py
  mlflow/store/db_migrations/versions/2d6e25af4d3e_increase_max_param_val_length.py
  mlflow/store/db_migrations/versions/3500859a5d39_add_model_aliases_table.py
  mlflow/store/db_migrations/versions/39d1c3be5f05_add_is_nan_constraint_for_metrics_tables_if_necessary.py
  mlflow/store/db_migrations/versions/4465047574b1_increase_max_dataset_schema_size.py
  mlflow/store/db_migrations/versions/451aebb31d03_add_metric_step.py
  mlflow/store/db_migrations/versions/5b0e9adcef9c_add_cascade_deletion_to_trace_tables_fk.py
  mlflow/store/db_migrations/versions/728d730b5ebd_add_registered_model_tags_table.py
  mlflow/store/db_migrations/versions/7ac759974ad8_update_run_tags_with_larger_limit.py
  mlflow/store/db_migrations/versions/7f2a7d5fae7d_add_datasets_inputs_input_tags_tables.py
  mlflow/store/db_migrations/versions/84291f40a231_add_run_link_to_model_version.py
  mlflow/store/db_migrations/versions/867495a8f9d4_add_trace_tables.py
  mlflow/store/db_migrations/versions/89d4b8295536_create_latest_metrics_table.py
  mlflow/store/db_migrations/versions/90e64c465722_migrate_user_column_to_tags.py
  mlflow/store/db_migrations/versions/97727af70f4d_creation_time_last_update_time_experiments.py
  mlflow/store/db_migrations/versions/a8c4a736bde6_allow_nulls_for_run_id.py
  mlflow/store/db_migrations/versions/acf3f17fdcc7_add_storage_location_field_to_model_.py
  mlflow/store/db_migrations/versions/bd07f7e963c5_create_index_on_run_uuid.py
  mlflow/store/db_migrations/versions/c48cb773bb87_reset_default_value_for_is_nan_in_metrics_table_for_mysql.py
  mlflow/store/db_migrations/versions/cc1f77228345_change_param_value_length_to_500.py
  mlflow/store/db_migrations/versions/cfd24bdc0731_update_run_status_constraint_with_killed.py
  mlflow/store/db_migrations/versions/df50e92ffc5e_add_experiment_tags_table.py
  mlflow/store/db_migrations/versions/f5a4f2784254_increase_run_tag_value_limit.py
  pyproject.toml
Labels: rn/none

#14506 Fix scoring docker server test
  examples/gateway/mlflow_models/README.md
  mlflow/models/container/scoring_server/nginx.conf
  mlflow/models/container/scoring_server/wsgi.py
  tests/pyfunc/docker/test_docker_flavors.py
Labels: rn/none, v2.20.2

#14367 ChatAgent Docs
  docs/api_reference/source/conf.py
  docs/api_reference/source/python_api/mlflow.langchain.rst
  docs/api_reference/source/python_api/mlflow.pyfunc.rst
  docs/api_reference/source/python_api/mlflow.types.rst
  mlflow/langchain/chat_agent_langchain.py
  mlflow/langchain/chat_agent_langgraph.py
  mlflow/langchain/output_parsers.py
  mlflow/pyfunc/model.py
  mlflow/types/agent.py
Labels: area/docs, rn/none, v2.20.2

#14512 Replaced `get_artifact_uri` with `model_info.model_uri`
  tests/evaluate/test_evaluation.py
Labels: rn/none, v2.20.2

#14514 Retry PR creation in sync job
  .github/workflows/sync.py
Labels: rn/none

#14516 Use model info to get model URI
  tests/models/test_model_input_examples.py
  tests/models/test_signature.py
Labels: rn/none

#14525 Do not run sync job on forks
  .github/workflows/sync.yml
Labels: rn/none

#14400 Support generating traces from DSPy built-in compilation and evaluation
  docs/docs/tracing/integrations/dspy.mdx
  mlflow/dspy/autolog.py
  tests/dspy/test_dspy_autolog.py
Labels: rn/feature, area/tracking, v2.20.2

#14539 Add gtag script to docs
  docs/theme/mlflow/layout.html
Labels: rn/none

#14510 Simplify LangGraph ChatAgent to not override internal methods
  mlflow/langchain/chat_agent_langgraph.py
Labels: rn/none, area/models, v2.20.2

#14544 ChatAgent update docstring
  mlflow/types/agent.py
Labels: rn/none, v2.20.2

#14528 Use `model_info.model_uri` in `tests/gateway/tools.py`
  tests/gateway/tools.py
Labels: rn/none

#14529 Fix warning check calls
  tests/models/test_model_input_examples.py
  tests/pyfunc/test_pyfunc_schema_enforcement.py
Labels: rn/none

#14518 Fix spark_udf on databricks
  mlflow/pyfunc/__init__.py
Labels: rn/none, v2.20.2

#14515 Run sync job on Monday ~ Friday
  .github/workflows/sync.yml
Labels: rn/none

#14550 Use `model_info.model_uri` in `tests/pyfunc/test_model_export_with_class_and_artifacts.py`
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/none

#14459 Support tracing sync/async generator function with @mlflow.trace
  docs/docs/tracing/api/manual-instrumentation.mdx
  mlflow/pyfunc/__init__.py
  mlflow/tracing/constant.py
  mlflow/tracing/fluent.py
  mlflow/tracing/provider.py
  mlflow/tracing/utils/__init__.py
  tests/langchain/test_langchain_autolog.py
  tests/langchain/test_langchain_model_export.py
  tests/pyfunc/test_context.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/tracing/test_fluent.py
Labels: rn/feature, area/tracking, v2.20.2

#14540 Add gtag to docs
  docs/api_reference/theme/mlflow/layout.html
  docs/docusaurus.config.ts
Labels: rn/none

#14530 Fix cli tests
  mlflow/models/model.py
  mlflow/store/artifact/models_artifact_repo.py
  tests/models/test_cli.py
Labels: rn/none

#14551 Adjust `test_log_model_without_specified_conda_env_uses_default_env_with_expected_dependencies` to use `model_uri`
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
Labels: rn/none

#14554 Adjust `test_python_model_predict_compatible_without_params`
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/none

#14564 Fix `test_dbfs_artifact_repo_factory_acled_paths`
  tests/store/artifact/test_dbfs_artifact_repo.py
  tests/store/artifact/test_dbfs_artifact_repo_delegation.py
Labels: rn/none

#14493 [1] Adding basic data model for prompt registry
  mlflow/entities/__init__.py
  mlflow/entities/model_registry/__init__.py
  mlflow/entities/model_registry/prompt.py
  mlflow/entities/model_registry/registered_model.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/model_registry/prompt/utils.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/utils/search_utils.py
  tests/entities/test_prompt.py
  tests/store/model_registry/test_file_store.py
  tests/store/model_registry/test_sqlalchemy_store.py
Labels: rn/none, area/model-registry

#14566 lint fixes
  mlflow/entities/model_registry/model_version_deployment_job_run_state.py
  mlflow/entities/model_registry/registered_model_deployment_job_state.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/_unity_catalog/registry/uc_oss_rest_store.py
  mlflow/store/artifact/utils/models.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/model_registry/rest_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/client.py
  tests/entities/model_registry/test_model_version.py
  tests/entities/model_registry/test_registered_model.py
Labels: rn/none

#14255 Merge MLflow 3 latest
  examples/mlflow-3/register_model.py
  mlflow/entities/model_registry/__init__.py
  mlflow/entities/model_registry/model_version.py
  mlflow/entities/model_registry/model_version_deployment_job_run_state.py
  mlflow/entities/model_registry/model_version_deployment_job_state.py
  mlflow/entities/model_registry/registered_model.py
  mlflow/entities/model_registry/registered_model_deployment_job_state.py
  mlflow/java/client/src/main/java/org/mlflow/api/proto/ModelRegistry.java
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/protos/model_registry.proto
  mlflow/protos/model_registry_pb2.py
  mlflow/server/graphql/autogenerated_graphql_schema.py
  mlflow/server/handlers.py
  mlflow/server/js/src/graphql/autogenerated_schema.gql
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/_unity_catalog/registry/uc_oss_rest_store.py
  mlflow/store/artifact/utils/models.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/model_registry/rest_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/client.py
  mlflow/utils/_unity_catalog_utils.py
  tests/entities/model_registry/test_model_version.py
  tests/entities/model_registry/test_registered_model.py
  tests/tracking/_model_registry/test_model_registry_client.py
  tests/tracking/test_client.py
  tests/tracking/test_model_registry.py
  tests/utils/test_unity_catalog_utils.py
Labels: rn/none

#14569 Fix `Dataset.source` and `Dataset.source_type` docs
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
Labels: rn/none, v2.20.2

#14570 Exit if mlflow-3 branch is already up to date in `sync` workflow
  .github/workflows/sync.py
Labels: rn/none

#14572 Update model registry tests
  tests/tracking/_model_registry/test_model_registry_fluent.py
Labels: rn/none

#14553 Easy Docusaurus Fixes
  docs/docs/deployment/index.mdx
  docs/docs/getting-started/running-notebooks/index.mdx
  docs/docs/llms/index.mdx
  docs/docs/model/index.mdx
  docs/docs/tracing/api/client.mdx
  docs/docs/tracing/api/how-to.mdx
  docs/docs/tracing/index.mdx
  docs/docs/tracing/tracing-schema.mdx
  docs/docs/tracking/index.mdx
  docs/docs/traditional-ml/index.mdx
  docs/docs/traditional-ml/serving-multiple-models-with-pyfunc/notebooks/MME_Tutorial.ipynb
  docs/docusaurus.config.ts
Labels: rn/none

#14574 Fix UCFunction test
  tests/langchain/test_langchain_databricks_dependency_extraction.py
Labels: rn/none

#14580 Fix broken link in README
  README.md
Labels: area/docs, rn/none

#14571 MLflow 3 test failures
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/model_registry/rest_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  tests/entities/model_registry/test_model_version.py
  tests/store/lineage/test_downstream_lineage.py
Labels: rn/none

#14527 Add file store tests and fix some issues
  mlflow/entities/logged_model_status.py
  mlflow/store/tracking/__init__.py
  mlflow/store/tracking/file_store.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/utils/search_utils.py
  tests/store/tracking/test_file_store_logged_model.py
Labels: rn/none

#14584 Fix file store max_results
  mlflow/store/tracking/file_store.py
Labels: rn/none

#14494 [2] Add fluent/client API for CRUD prompts
  mlflow/__init__.py
  mlflow/entities/model_registry/prompt.py
  mlflow/prompt/promptlab_model.py
  mlflow/prompt/registry_utils.py
  mlflow/server/handlers.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/model_registry/prompt/utils.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
  mlflow/utils/promptlab_utils.py
  tests/prompt/test_promptlab_model.py
  tests/server/test_handlers.py
  tests/tracking/_model_registry/test_model_registry_client.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
  tests/tracking/test_client.py
Labels: rn/none, area/model-registry

#14590 Fix lineage test
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/model_registry/rest_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  tests/store/lineage/test_downstream_lineage.py
Labels: rn/none

#14594 Stop supporting spacy 3.3
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
Labels: rn/none, v2.20.3

#14597 Ignore files in `mlflow/server/js` when detecting changed flavors
  .github/workflows/cross-version-tests.yml
Labels: rn/none

#14600 Adjust `tests/pyfunc/test_model_export_with_class_and_artifacts.py::test_model_log_load`
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/none

#14601 Fix tests that serve a model without `python_env.yml`
  tests/pyfunc/test_virtualenv.py
Labels: rn/none

#14535 Fix Pydantic Models to support V1 and V2 of Pydantic and fix deprecation warnings
  docs/docs/llms/deployments/index.mdx
  examples/gateway/plugin/my-llm/my_llm/config.py
  mlflow/gateway/config.py
  mlflow/gateway/providers/mlflow.py
  mlflow/types/agent.py
  mlflow/utils/pydantic_utils.py
Labels: rn/none, v2.20.2, v2.20.3

#14603 Fix `_log_model_with_signature_and_example` to use `model_uri`
  tests/models/test_model.py
Labels: rn/none

#14593 Fix pyfunc infer_pip_requirements on serverless cluster
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/model.py
Labels: rn/none, v2.20.3

#14613 Fix `test_log_model_no_registered_model_name` and `test_log_model_calls_register_model`
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/none

#14615 Fix `test_serve_uvicorn_opts` to use `model_uri`
  tests/models/test_cli.py
Labels: rn/none

#14616 Change type hints of trace inputs/outputs to Optional[Any]
  mlflow/tracking/client.py
Labels: rn/none, area/tracking, v2.20.3

#14556 Fix register_model test
  mlflow/tracking/_model_registry/fluent.py
Labels: rn/none

#14614 Skip tests that ensure `log_model` starts a run
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_model_export_with_loader_module_and_data_path.py
Labels: rn/none

#14559 Fix default evaluator tests
  mlflow/models/evaluation/evaluators/shap.py
  mlflow/shap/__init__.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/none

#14619 Fix `test_set_signature_overwrite` to use `model_info.model_uri`
  tests/models/test_signature.py
Labels: rn/none

#14621 Simplify `test_model_log_with_databricks_runtime`
  tests/models/test_model.py
Labels: rn/none

#14623 Disable `mlflow-recipes` job
  .circleci/config.yml
Labels: rn/none

#14625 Skip `recipes` workflow
  .github/workflows/recipe.yml
Labels: rn/none, area/artifacts

#14624 Update `sync` job to push to existing PR if it exists
  .github/workflows/sync.py
Labels: rn/none

#14620 Fix `set_signature` to allow setting signature with `models:/<model_id>`
  mlflow/models/signature.py
  tests/models/test_signature.py
Labels: rn/none

#14618 Fix evaluation tests
  tests/evaluate/test_evaluation.py
Labels: rn/none

#14626 Fix failing tests in `tests/models`
  mlflow/models/model.py
  tests/models/test_model.py
  tests/models/test_wheeled_model.py
Labels: rn/none

#14628 Update `sync.md` for merge option
  .github/workflows/sync.md
Labels: rn/none

#14524 [3] Allow associating prompts and model at logging time.
  mlflow/entities/model_registry/prompt.py
  mlflow/models/model.py
  mlflow/pyfunc/__init__.py
  mlflow/tracking/client.py
  mlflow/utils/docstring_utils.py
  tests/models/test_model.py
  tests/tracking/test_client.py
Labels: rn/feature, area/model-registry

#14598 Simplify LangChain tracing patching
  mlflow/langchain/__init__.py
  mlflow/langchain/_langchain_autolog.py
  mlflow/langchain/langchain_tracer.py
  mlflow/utils/autologging_utils/safety.py
  tests/langchain/test_langchain_autolog.py
Labels: rn/bug-fix, area/tracking, v2.20.3

#14632 Implement tool standard for Groq tracing
  mlflow/groq/_groq_autolog.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  tests/groq/test_groq_autolog.py
Labels: rn/none, v2.20.3

#14633 Use `ModelInfo.model_uri` in LightGBM tests
  tests/lightgbm/test_lightgbm_model_export.py
Labels: rn/none

#14634 Use `ModelInfo.model_uri` in catboost tests
  tests/catboost/test_catboost_model_export.py
Labels: rn/none

#14635 Use `ModelInfo.model_uri` in sklearn tests
  tests/sklearn/test_sklearn_model_export.py
Labels: rn/none

#14637 Use `ModelInfo.model_uri` in sentence-transformers tests
  tests/sentence_transformers/test_sentence_transformers_model_export.py
Labels: rn/none

#14639 Use `ModelInfo.model_uri` in h2o tests
  tests/h2o/test_h2o_model_export.py
Labels: rn/none

#14568 Add a script to build a servable docs instance for development workflows
  dev/build-docs.sh
Labels: area/docs, rn/none

#14538 Introduce User Auth Policy for Pyfunc Models
  docs/api_reference/source/conf.py
  mlflow/models/auth_policy.py
  mlflow/models/model.py
  mlflow/pyfunc/__init__.py
  mlflow/utils/docstring_utils.py
  tests/models/test_auth_policy.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/feature, area/models

#14645 Mlflow sync
  .github/workflows/sync.md
  dev/build-docs.sh
  docs/api_reference/source/conf.py
  examples/catboost/train.py
  examples/diviner/train.py
  examples/evaluation/evaluate_on_binary_classifier.py
  examples/evaluation/evaluate_on_multiclass_classifier.py
  examples/evaluation/evaluate_on_regressor.py
  examples/evaluation/evaluate_with_custom_metrics.py
  examples/evaluation/evaluate_with_custom_metrics_comprehensive.py
  examples/pip_requirements/pip_requirements.py
  examples/pmdarima/train.py
  mlflow/groq/_groq_autolog.py
  mlflow/langchain/__init__.py
  mlflow/langchain/_langchain_autolog.py
  mlflow/langchain/langchain_tracer.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/models/auth_policy.py
  mlflow/models/model.py
  mlflow/pyfunc/__init__.py
  mlflow/utils/autologging_utils/safety.py
  mlflow/utils/docstring_utils.py
  tests/catboost/test_catboost_model_export.py
  tests/groq/test_groq_autolog.py
  tests/h2o/test_h2o_model_export.py
  tests/helper_functions.py
  tests/langchain/test_langchain_autolog.py
  tests/lightgbm/test_lightgbm_model_export.py
  tests/models/test_auth_policy.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/sentence_transformers/test_sentence_transformers_model_export.py
  tests/sklearn/test_sklearn_model_export.py
  tests/xgboost/test_xgboost_model_export.py
Labels: rn/none

#14646 Use `ModelInfo.mode_uri` in diviner tests
  tests/diviner/test_diviner_model_export.py
Labels: rn/none

#14647 Use `ModelInfo.mode_uri` in statsmodels tests
  tests/statsmodels/test_statsmodels_model_export.py
Labels: rn/none

#14631 Fix examples test_command_example
  examples/pip_requirements/pip_requirements.py
  mlflow/sklearn/utils.py
Labels: rn/none

#14629 Fix examples test_mlflow_run_example
  examples/pytorch/mnist_tensorboard_artifact.py
  examples/sktime/train.py
Labels: rn/none

#14648 Use `ModelInfo.model_uri` in transformers tests
  tests/transformers/test_transformers_model_export.py
Labels: rn/none

#14650 Use `ModelInfo.model_uri` in keras/TF tests
  tests/keras/test_save.py
  tests/tensorflow/test_keras_model_export.py
  tests/tensorflow/test_tensorflow2_core_model_export.py
Labels: rn/none

#14642 Replace Databricks Community Edition with Lighthouse [1]
  docs/docs/getting-started/community-edition/index.mdx
  docs/docs/getting-started/databricks-trial/index.mdx
  docs/docs/getting-started/intro-quickstart/index.mdx
  docs/docs/getting-started/quickstart-2/index.mdx
  docs/docs/getting-started/running-notebooks/index.mdx
  docs/docs/getting-started/tracking-server-overview/index.mdx
  docs/docs/projects/index.mdx
  docs/docs/tracking/backend-stores/index.mdx
  docs/sidebars.ts
  docs/static/images/quickstart/tracking-server-overview/databricks-ce-experiment-view.png
  docs/static/images/quickstart/tracking-server-overview/databricks-ce-landing-page.png
  docs/static/images/quickstart/tracking-server-overview/databricks-ce-run-view.png
  docs/static/images/quickstart/tracking-server-overview/databricks-lighthouse-experiment-view.png
  docs/static/images/quickstart/tracking-server-overview/databricks-lighthouse-landing-page.png
  docs/static/images/quickstart/tracking-server-overview/databricks-lighthouse-run-view.png
  docs/static/images/tutorials/introductory/community-edition-main.png
  docs/static/images/tutorials/introductory/import-notebook-into-ce.png
  docs/static/images/tutorials/introductory/lighthouse/experiments-page.png
  docs/static/images/tutorials/introductory/lighthouse/import-notebook.png
  docs/static/images/tutorials/introductory/lighthouse/landing-page.png
  docs/static/images/tutorials/introductory/mlflow-ui-in-ce.png
Labels: rn/documentation, v2.20.3

#14651 Add uvicorn and fastapi as skinny requirement
  pyproject.release.toml
  pyproject.skinny.toml
  requirements/core-requirements.txt
  requirements/core-requirements.yaml
  requirements/skinny-requirements.txt
  requirements/skinny-requirements.yaml
Labels: rn/none

#14656 Remove old evaluation/assessment object definitions
  docs/api_reference/source/conf.py
  docs/api_reference/source/python_api/mlflow.evaluation.rst
  mlflow/entities/assessment.py
  mlflow/entities/evaluation.py
  mlflow/evaluation/__init__.py
  mlflow/evaluation/assessment.py
  mlflow/evaluation/evaluation.py
  mlflow/evaluation/fluent.py
  mlflow/evaluation/utils.py
  tests/entities/test_assessment.py
  tests/entities/test_evaluation.py
  tests/evaluate/logging/__init__.py
  tests/evaluate/logging/test_assessment.py
  tests/evaluate/logging/test_evaluation.py
  tests/evaluate/logging/test_fluent.py
  tests/evaluate/logging/test_utils.py
  tests/evaluate/logging/utils.py
Labels: rn/breaking-change, v2.20.3

#14652 Use `ModelInfo.model_uri` in spark tests
  tests/spark/test_spark_connect_model_export.py
  tests/spark/test_spark_model_export.py
Labels: rn/none

#14662 Use `ModelInfo.model_uri` in onnx and paddle tests
  tests/onnx/test_onnx_model_export.py
  tests/paddle/test_paddle_model_export.py
Labels: rn/none

#14638 Add `last_logged_model` to fetch most recent logged model
  examples/mlflow-3/sklearn_autolog.py
  mlflow/__init__.py
  mlflow/johnsnowlabs/__init__.py
  mlflow/models/model.py
  mlflow/spark/__init__.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/fluent.py
  tests/evaluate/test_default_evaluator.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/none

#14665 Add temporal instruction to use UC Volume
  docs/docs/getting-started/databricks-trial/index.mdx
Labels: rn/none, v2.20.3

#14669 Fix `last_logged_model` example
  mlflow/tracking/fluent.py
Labels: rn/none

#14673 Use `ModelInfo.model_uri` in `prophet` and `pmdrima` tests
  tests/pmdarima/test_pmdarima_model_export.py
  tests/prophet/test_prophet_model_export.py
Labels: rn/none

#14660 Add pagination to S3ArtifactRepository.delete_artifacts
  mlflow/store/artifact/optimized_s3_artifact_repo.py
  mlflow/store/artifact/s3_artifact_repo.py
  tests/store/artifact/test_s3_artifact_repo.py
  tests/test_cli.py
Labels: rn/none, area/artifacts, v2.20.3

#14674 Use `MoelInfo.model_uri` in torch/langchain tests
  tests/langchain/test_langchain_model_export.py
  tests/pytorch/test_pytorch_model_export.py
Labels: rn/none

#14684 Use `ModelInfo.model_uri` in dspy, fastai, and spacy tests
  tests/dspy/test_save.py
  tests/fastai/test_fastai_model_export.py
  tests/spacy/test_spacy_model_export.py
Labels: rn/none

#14685 Bump `pyarrow` to 19
  pyproject.release.toml
  pyproject.toml
  requirements/core-requirements.txt
  requirements/core-requirements.yaml
Labels: rn/none, v2.20.3

#14687 Use `ModelInfo.model_uri` in shap tests
  mlflow/shap/__init__.py
  tests/shap/test_log.py
Labels: rn/none

#14663 [1] Add Assessment proto and entities
  mlflow/entities/assessment.py
  mlflow/entities/assessment_error.py
  mlflow/entities/assessment_source.py
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
  mlflow/utils/proto_json_utils.py
  tests/entities/test_assessment.py
  tests/entities/test_assessment_source.py
Labels: rn/none, area/tracking

#14671 Replace CE content on tutorials with Lighthouse
  docs/docs/deep-learning/pytorch/quickstart/pytorch_quickstart.ipynb
  docs/docs/deep-learning/tensorflow/quickstart/quickstart_tensorflow.ipynb
  docs/docs/getting-started/intro-quickstart/notebooks/tracking_quickstart.ipynb
  docs/docs/getting-started/logging-first-model/notebooks/logging-first-model.ipynb
  docs/docs/llms/openai/notebooks/openai-code-helper.ipynb
  docs/docs/traditional-ml/hyperparameter-tuning-with-child-runs/notebooks/hyperparameter-tuning-with-child-runs.ipynb
Labels: rn/none, v2.20.3

#14683 Cast `version` to `int` in `UnityCatalogOssStore`
  mlflow/store/_unity_catalog/registry/uc_oss_rest_store.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_oss_rest_store.py
Labels: rn/none
