Repository mlflow/mlflow, pull requests merged in 2025-06, with the labels that each got.

#15982 Replace shorthand scorers with direct class instantiations
  mlflow/genai/evaluation/base.py
  mlflow/genai/judges/__init__.py
  mlflow/genai/scorers/__init__.py
  mlflow/genai/scorers/builtin_scorers.py
  tests/genai/evaluate/test_evaluation.py
  tests/genai/evaluate/test_utils.py
  tests/genai/scorers/test_builtin_scorers.py
  tests/genai/scorers/test_validation.py
  tests/genai/test_scorer.py
Labels: rn/none, v2.22.1, v3.1.0

#15983 Fix: Add precision suffix to retrieval relevance
  mlflow/genai/scorers/builtin_scorers.py
  tests/genai/scorers/test_builtin_scorers.py
Labels: rn/none, v2.22.1, v3.1.0

#15999 Update `com.google.protobuf:protobuf-java` to 3.19.6
  mlflow/java/pom.xml
Labels: rn/none, v3.0.0, team-review

#16001 Use the right Java version when building docker image in `tests/spark/test_spark_model_export.py::test_model_deployment`
  tests/spark/test_spark_model_export.py
Labels: rn/none, team-review

#15970 Validate `gateway_path` in `gateway_proxy_handler`
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, v3.0.0, team-review

#16002 Fix `search-logged-models` request when server is started with `static-prefix`
  mlflow/server/js/src/experiment-tracking/hooks/logged-models/useSearchLoggedModelsQuery.tsx
Labels: rn/none

#16004 Avoid generating traces from scorers during evaluation
  mlflow/genai/scorers/base.py
  tests/genai/test_scorer.py
Labels: rn/bug-fix, area/tracking, team-review, v3.1.0

#15968 Make spark_udf support DBConnect + DBR 15.4 / DBR dedicated cluster
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/dbconnect_artifact_cache.py
Labels: rn/feature, area/scoring

#16015 Log datasets to child runs created by cross validation in sklearn autolog
  mlflow/sklearn/utils.py
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/none

#16025 Bump pytest version to 8.4.0
  pyproject.toml
  requirements/constraints.txt
  requirements/test-requirements.txt
Labels: rn/none, team-review

#15985 Swap judge for context relevance to use relevance to query
  mlflow/genai/judges/databricks.py
  mlflow/genai/scorers/builtin_scorers.py
  tests/genai/scorers/test_builtin_scorers.py
Labels: rn/none, area/tracking, v3.1.0

#15966 Fix: `mlflow.spark.log_model` does not upload model artifacts
  mlflow/spark/__init__.py
  tests/spark/test_spark_model_export.py
Labels: rn/none, v3.0.0

#16031 Fix trace table styles (#15492)
  mlflow/server/js/src/experiment-tracking/components/HomePage.tsx
  mlflow/server/js/src/experiment-tracking/components/traces/TracesViewTablePreviewCell.tsx
Labels: rn/none

#16030 Support loading runs created in 3.x in 2.x
  mlflow/entities/run_info.py
Labels: rn/none

#16033 Clarify FAQ on loading resources from MLflow 2.x to 3.x and add warning about environment separation
  docs/docs/mlflow-3/faqs.mdx
Labels: rn/none

#16034 Persist logged model params as files
  mlflow/store/tracking/file_store.py
Labels: rn/none, v3.0.0

#16044 Update default parameters of optimize_prompt
  docs/docs/prompts/optimize-prompt.mdx
  mlflow/genai/optimize/types.py
Labels: area/docs, rn/none, v3.1.0

#16046 Log eval score as metadata
  mlflow/genai/optimize/base.py
  mlflow/genai/optimize/optimizers/base_optimizer.py
  mlflow/genai/optimize/optimizers/dspy_mipro_optimizer.py
  tests/genai/optimize/test_base.py
  tests/genai/optimize/test_dspy_mipro_optimizer.py
Labels: rn/none, v3.1.0

#16010 Fix Prompt Search Proto [Part 1.5]
  mlflow/protos/unity_catalog_prompt_messages.proto
  mlflow/protos/unity_catalog_prompt_messages_pb2.py
  mlflow/protos/unity_catalog_prompt_messages_pb2_grpc.py
  mlflow/store/_unity_catalog/registry/utils.py
  tests/store/_unity_catalog/registry/test_uc_prompt_utils.py
Labels: rn/none

#16041 UC Prompt Registry Client [Part 2b]: Prompt Store Implementation for Prompt Version
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/model_registry/abstract_store.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/none

#16050 Run `generate_protos.py` multiple times in `autoformat` workflow
  .github/workflows/autoformat.yml
Labels: rn/none

#16048 Show helpful error message for invalid scorer types
  mlflow/genai/scorers/validation.py
  tests/genai/scorers/test_validation.py
Labels: rn/none, area/tracking, v3.1.0

#16024 Bug fix - Add approval deployment job stage to proto enum so that model versions can be loaded when in state `approved`
  mlflow/java/client/src/main/java/org/mlflow/api/proto/ModelRegistry.java
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/protos/model_registry.proto
  mlflow/protos/model_registry_pb2.py
  mlflow/server/graphql/autogenerated_graphql_schema.py
  mlflow/server/js/src/graphql/autogenerated_schema.gql
  tests/utils/test_unity_catalog_utils.py
Labels: rn/none, area/model-registry

#16054 Remove prefix validation for trace tags
  mlflow/tracing/client.py
  mlflow/tracing/constant.py
  tests/tracking/test_client.py
Labels: rn/none

#16059 Tracing: Add APIs for setting trace status and span exception content
  mlflow/entities/span.py
  mlflow/tracing/fluent.py
  mlflow/tracing/processor/base_mlflow.py
  mlflow/tracing/processor/inference_table.py
  mlflow/tracing/utils/__init__.py
  tests/tracing/processor/test_inference_table_processor.py
  tests/tracing/test_fluent.py
Labels: rn/none, area/tracking

#16063 Use `CIRCLE_PULL_REQUEST` instead of `CIRCLE_PR_NUMBER`
  .circleci/config.yml
Labels: rn/none, team-review

#16051 Add autolog option for genai.optimize_prompt
  docs/docs/prompts/optimize-prompt.mdx
  mlflow/genai/optimize/base.py
  mlflow/genai/optimize/optimizers/dspy_mipro_optimizer.py
  mlflow/genai/optimize/optimizers/utils/dspy_mipro_callback.py
  mlflow/genai/optimize/optimizers/utils/dspy_mipro_utils.py
  mlflow/genai/optimize/types.py
  tests/genai/optimize/optimizers/test_dspy_mipro_optimizer.py
  tests/genai/optimize/optimizers/utils/test_dspy_mipro_callback.py
  tests/genai/optimize/optimizers/utils/test_dspy_mipro_utils.py
  tests/genai/optimize/test_base.py
Labels: rn/none, team-review

#16067 Bump maximum supported version for pyspark
  .github/actions/setup-java/action.yml
  .github/workflows/cross-version-tests.yml
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  tests/autologging/test_autologging_utils.py
  tests/spark/test_spark_connect_model_export.py
Labels: rn/none, team-review

#16065 Fix catboost cross-version tests
  tests/catboost/test_catboost_model_export.py
Labels: rn/none, team-review

#16045 Compare `sitemap.xml` files to show new/removed links
  .circleci/config.yml
  docs/package.json
  docs/scripts/compare-sitemaps.ts
  docs/yarn.lock
Labels: rn/none

#16069 Add deep learning quickstart
  docs/docs/classic-ml/getting-started/deep-learning.mdx
  docs/docusaurus.config.ts
  docs/sidebarsClassicML.ts
Labels: rn/none

#16074 Prompt Registry Client: Remaining Prompt Store Infrastructure & Search Parsing [Part 3]
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/_unity_catalog/registry/utils.py
  mlflow/store/model_registry/abstract_store.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
Labels: rn/none, area/model-registry

#16060 Expose categorical rating in mlflow.genai.judges
  mlflow/entities/assessment.py
  mlflow/genai/judges/__init__.py
  mlflow/genai/judges/databricks.py
  mlflow/genai/utils/enum_utils.py
  tests/entities/test_assessment.py
  tests/genai/judges/test_judges.py
  tests/genai/scorers/test_builtin_scorers.py
  tests/genai/scorers/test_scorer.py
Labels: rn/none, area/tracking, v3.1.0

#16086 Avoid pandas 2.3.0
  pyproject.release.toml
  pyproject.toml
  requirements/core-requirements.txt
  requirements/core-requirements.yaml
  tests/conftest.py
  tests/pyfunc/docker/test_docker.py
Labels: rn/none, team-review

#16055 Add 'metadata' field to update_current_Trace
  mlflow/tracing/fluent.py
  tests/tracing/test_fluent.py
Labels: rn/none, area/tracking

#16099 Fix Client & Server Prompt Proto Divergence
  mlflow/protos/unity_catalog_prompt_messages.proto
  mlflow/protos/unity_catalog_prompt_messages_pb2.py
  mlflow/protos/unity_catalog_prompt_service.proto
  mlflow/protos/unity_catalog_prompt_service_pb2.py
  mlflow/store/_unity_catalog/registry/rest_store.py
Labels: rn/none, area/model-registry

#16102 Rename default of is_context_relevant to relevance_to_context
  mlflow/genai/judges/databricks.py
  tests/genai/judges/test_judges.py
Labels: rn/none, area/tracking, v3.1.0

#16098 Add session & user examples to update_current_trace
  mlflow/tracing/fluent.py
Labels: area/docs, rn/none

#16072 Scheduled Scorers
  mlflow/genai/__init__.py
  mlflow/genai/scheduled_scorers.py
  tests/genai/test_scheduled_scorers.py
Labels: rn/none, area/tracking, v3.1.0

#15538 Update cross-version test to run tracing SDK test
  .github/workflows/cross-version-tests.yml
  dev/set_matrix.py
  mlflow/ml-package-versions.yml
  packages/tracing/pyproject.toml
  tests/anthropic/test_anthropic_autolog.py
  tests/bedrock/test_bedrock_autolog.py
  tests/crewai/test_crewai_autolog.py
  tests/langchain/test_langchain_autolog.py
  tests/langgraph/test_langgraph_autolog.py
  tests/pydantic_ai/conftest.py
  tests/pydantic_ai/test_pydanticai_fluent_tracing.py
  tests/pydantic_ai/test_pydanticai_mcp_tracing.py
  tests/pydantic_ai/test_pydanticai_tracing.py
  tests/tracing/helper.py
Labels: rn/none, area/tracking

#16101 Revert "Avoid pandas 2.3.0"
  .github/actions/py-cache-key/action.yml
  pyproject.release.toml
  pyproject.toml
  requirements/core-requirements.txt
  requirements/core-requirements.yaml
  tests/conftest.py
  tests/pyfunc/docker/test_docker.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/utils/test_requirements_utils.py
Labels: rn/none

#16106 Fix the prompt optimizer failure with older dspy
  mlflow/genai/optimize/optimizers/dspy_mipro_optimizer.py
  tests/genai/optimize/optimizers/test_dspy_mipro_optimizer.py
Labels: rn/none, v3.1.0

#16117 Fix ellipses
  docs/docs/genai/tracing/data-model.mdx
Labels: rn/none

#16103 Fix tracing disablement conflict between predict_fn and scorers
  mlflow/genai/evaluation/base.py
  mlflow/genai/scorers/base.py
  mlflow/genai/utils/trace_utils.py
  mlflow/tracing/fluent.py
  tests/genai/scorers/test_scorer.py
  tests/tracing/test_fluent.py
Labels: rn/none, area/tracking, team-review, v3.1.0

#16091 Add GenAI prompt and version management section
  docs/docs/genai/prompt-version-mgmt/prompt-registry/app-integration.mdx
  docs/docs/genai/prompt-version-mgmt/prompt-registry/create-and-edit-prompts.mdx
  docs/docs/genai/prompt-version-mgmt/prompt-registry/create-edit-prompts.mdx
  docs/docs/genai/prompt-version-mgmt/prompt-registry/evaluate-prompts.mdx
  docs/docs/genai/prompt-version-mgmt/prompt-registry/index.mdx
  docs/docs/genai/prompt-version-mgmt/prompt-registry/lifecycle-management.mdx
  docs/docs/genai/prompt-version-mgmt/prompt-registry/manage-prompt-lifecycles-with-aliases.mdx
  docs/docs/genai/prompt-version-mgmt/prompt-registry/prompt-evaluation.mdx
  docs/docs/genai/prompt-version-mgmt/prompt-registry/use-in-deployment.mdx
  docs/docs/genai/prompt-version-mgmt/prompt-registry/use-prompts-in-apps.mdx
  docs/docs/genai/prompt-version-mgmt/prompt-registry/use-prompts-in-deployed-apps.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/app-comparison.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/compare-app-versions.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/index.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/link-evaluation-results-and-traces-to-app-versions.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/link-production-traces-to-app-versions.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/link-traces.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/manual-tracking.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/optionally-package-app-code-and-files-for-databricks-model-serving.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/quickstart.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/track-application-versions-with-mlflow.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/track-eval-results.mdx
  docs/sidebarsGenAI.ts
Labels: rn/none

#16116 Add GenAI serving section
  docs/docs/genai/serving/custom-apps.mdx
  docs/docs/genai/serving/endpoint-creation.mdx
  docs/docs/genai/serving/index.mdx
  docs/docs/genai/serving/responses-agent.mdx
Labels: rn/none

#16125 Replace `insert` with `merge_records` for dataset
  .github/workflows/master.yml
  mlflow/genai/datasets/evaluation_dataset.py
  tests/genai/evaluate/test_evaluation.py
  tests/genai/evaluate/test_utils.py
  tests/genai/scorers/test_scorer.py
Labels: rn/none, v3.1.0

#15984 Add docstring for review app and rename sync expectations
  docs/api_reference/source/python_api/mlflow.genai.rst
  mlflow/genai/__init__.py
  mlflow/genai/label_schemas/__init__.py
  mlflow/genai/label_schemas/label_schemas.py
  mlflow/genai/labeling/__init__.py
  mlflow/genai/labeling/labeling.py
  tests/genai/label_schemas/test_label_schemas.py
  tests/genai/labeling/test_labeling.py
  tests/genai/test_genai_import_without_agent_sdk.py
Labels: rn/none, area/tracking, v3.1.0, v2.22.2

#16111 Fix ONNX dev test
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests, team-review

#16081 Introduce `MLFLOW_CREATE_MODEL_VERSION_SOURCE_REGEX` to validate source parameter of `/model-versions/create` request
  docs/docs/tracking/server/index.mdx
  mlflow/environment_variables.py
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, v3.0.0, team-review

#16128 Use consistent retry policy for Databricks SDK REST API calls and non-Databricks-SDK REST API calls
  mlflow/utils/rest_utils.py
  tests/utils/test_rest_utils.py
Labels: rn/none, v3.0.0, v3.1.0, v2.22.2

#16135 Databricks Model Registry: Default URI to databricks-uc when tracking URI is databricks & registry URI is unspecified
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/tracking/_model_registry/utils.py
  mlflow/utils/uri.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/tracking/_model_registry/test_utils.py
  tests/tracking/test_client.py
Labels: rn/breaking-change, area/model-registry, v3.0.0, v3.1.0, v2.22.2

#16036 Fix: `/graphql` returns 404 when server is started with `--static-prefix`
  mlflow/server/handlers.py
  mlflow/server/js/src/experiment-tracking/components/experiment-logged-models/hooks/useExperimentLoggedModelDeleteModal.tsx
  mlflow/server/js/src/experiment-tracking/hooks/logged-models/useGetLoggedModelQuery.tsx
  mlflow/server/js/src/experiment-tracking/hooks/logged-models/usePatchLoggedModelsTags.tsx
  mlflow/server/js/src/graphql/client.ts
Labels: rn/none, v3.0.0

#16142 Pin numpy version to 1.x when running lightgbm < 4.4.0
  mlflow/ml-package-versions.yml
Labels: rn/none, team-review, v2.22.2

#15920 Fix schema version returned when parsing MLflow 2.x trace with MLflow 3.0
  mlflow/entities/trace_info.py
  mlflow/entities/trace_info_v2.py
  tests/entities/test_trace.py
  tests/entities/test_trace_info.py
  tests/entities/test_trace_info_v2.py
  tests/store/tracking/test_rest_store.py
  tests/tracing/helper.py
  tests/tracing/test_fluent.py
Labels: rn/none, area/tracking, v3.0.0, v3.1.0

#16137 New Client Methods + Search Prompt Versions Impl
  mlflow/protos/unity_catalog_prompt_service.proto
  mlflow/protos/unity_catalog_prompt_service_pb2.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/client.py
  tests/tracking/test_client.py
Labels: rn/none, area/model-registry

#16147 Add missing sentence transformers tutorials back
  docs/docs/classic-ml/deep-learning/sentence-transformers/tutorials/index.mdx
  docs/docs/classic-ml/deep-learning/sentence-transformers/tutorials/paraphrase-mining/paraphrase-mining-sentence-transformers.ipynb
  docs/docs/classic-ml/deep-learning/sentence-transformers/tutorials/quickstart/sentence-transformers-quickstart.ipynb
  docs/docs/classic-ml/deep-learning/sentence-transformers/tutorials/semantic-search/semantic-search-sentence-transformers.ipynb
  docs/docs/classic-ml/deep-learning/sentence-transformers/tutorials/semantic-similarity/semantic-similarity-sentence-transformers.ipynb
  docs/sidebarsClassicML.ts
Labels: area/docs, rn/documentation

#16146 Add redirects and fixes
  docs/docs/classic-ml/deployment/deploy-model-to-kubernetes/tutorial.mdx
  docs/docs/classic-ml/docker/index.mdx
  docs/docs/classic-ml/traditional-ml/tutorials/serving-multiple-models-with-pyfunc/index.mdx
  docs/docs/genai/flavors/chat-model-guide/chat-model-tool-calling.ipynb
  docs/docs/genai/flavors/custom-pyfunc-for-llms/notebooks/index.mdx
  docs/docs/genai/prompt-version-mgmt/prompt-registry/optimize-prompts.mdx
  docs/docusaurus.config.ts
  docs/sidebarsClassicML.ts
  docs/sidebarsGenAI.ts
Labels: rn/none

#16144 Link prompts to models
  mlflow/prompt/constants.py
  mlflow/protos/unity_catalog_prompt_messages.proto
  mlflow/protos/unity_catalog_prompt_messages_pb2.py
  mlflow/protos/unity_catalog_prompt_service.proto
  mlflow/protos/unity_catalog_prompt_service_pb2.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/client.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/store/model_registry/test_abstract_store.py
  tests/tracking/test_client.py
Labels: rn/none, area/tracking

#16149 Populate a trace from serving endpoint to evaluation result.
  mlflow/entities/span.py
  mlflow/genai/evaluation/base.py
  mlflow/genai/utils/trace_utils.py
  mlflow/tracing/constant.py
  tests/entities/test_trace.py
  tests/genai/conftest.py
  tests/genai/evaluate/test_evaluation.py
  tests/genai/evaluate/test_to_predict_fn.py
  tests/tracing/helper.py
Labels: rn/none, area/tracking, v3.1.0

#16150 Fix sanitization when judges return an error
  mlflow/genai/judges/databricks.py
  tests/genai/judges/test_judges.py
Labels: rn/none, area/tracking, v3.1.0

#16152 Client and store APIs for linking prompts to traces
  mlflow/protos/unity_catalog_prompt_messages.proto
  mlflow/protos/unity_catalog_prompt_messages_pb2.py
  mlflow/protos/unity_catalog_prompt_service.proto
  mlflow/protos/unity_catalog_prompt_service_pb2.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/client.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/store/model_registry/test_abstract_store.py
  tests/tracking/test_client.py
Labels: rn/none, area/tracking, v3.1.0

#16161 Prompt Registry Client: Full support for Tags & Aliases
  mlflow/entities/model_registry/prompt_version.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/_unity_catalog/registry/utils.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/client.py
  tests/genai/optimize/optimizers/test_dspy_mipro_optimizer.py
  tests/genai/optimize/optimizers/utils/test_dspy_mipro_callback.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/store/_unity_catalog/registry/test_uc_prompt_utils.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
  tests/tracking/test_client.py
Labels: rn/none, area/model-registry, v3.1.0

#16168 Rename log_prompts to link_prompt_versions_to_run; add Databricks integration
  mlflow/entities/model_registry/prompt_version.py
  mlflow/models/model.py
  mlflow/prompt/constants.py
  mlflow/protos/unity_catalog_prompt_messages.proto
  mlflow/protos/unity_catalog_prompt_messages_pb2.py
  mlflow/protos/unity_catalog_prompt_service.proto
  mlflow/protos/unity_catalog_prompt_service_pb2.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
  tests/langchain/test_langchain_model_export.py
  tests/models/test_model.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/store/model_registry/test_abstract_store.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
  tests/tracking/test_client.py
Labels: rn/none, area/tracking, v3.1.0

#16155 Fix sklearn test
  tests/sklearn/test_sklearn_model_export.py
Labels: rn/none, team-review

#16119 Update `list_artifacts`/`download_artifacts` to list/download logged model artifacts
  mlflow/artifacts/__init__.py
  mlflow/pyfunc/backend.py
  mlflow/store/artifact/artifact_repo.py
  mlflow/store/artifact/runs_artifact_repo.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/_tracking_service/client.py
  tests/artifacts/test_artifacts.py
  tests/test_mlflow_version_comp.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, v3.0.0, v3.1.0

#16175 Add more doc links to optimize-prompt page
  docs/docs/genai/prompt-version-mgmt/prompt-registry/optimize-prompts.mdx
Labels: area/docs, rn/none

#16153 Fix autogen tests
  tests/autogen/test_autogen_autolog.py
Labels: rn/none, team-review

#16174 Move prompt registry APIs under `mlflow.genai.prompt` namespace
  docs/api_reference/source/python_api/mlflow.rst
  docs/docs/prompts/index.mdx
  mlflow/__init__.py
  mlflow/genai/__init__.py
  mlflow/genai/prompts/__init__.py
  mlflow/tracking/_model_registry/fluent.py
  tests/genai/prompts/test_prompts.py
Labels: rn/breaking-change, area/tracking, v3.1.0

#16172 Update `yarn.lock` in docs
  .circleci/config.yml
  docs/yarn.lock
Labels: rn/none

#16171 Update ML package versions for 3.1.0
  dev/update_ml_package_versions.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
Labels: rn/none, team-review

#16173 Fix footer links in docs
  docs/src/components/Footer/Footer.tsx
Labels: rn/none, team-review

#16177 Fix labeling schemas usage
  mlflow/genai/label_schemas/__init__.py
  mlflow/genai/label_schemas/label_schemas.py
  tests/genai/label_schemas/test_label_schemas.py
Labels: rn/none, area/tracking, v3.1.0

#16180 GenAI docs - update prompt registry & remove unnecessary Databricks references
  docs/docs/genai/data-model/prompts.mdx
  docs/docs/genai/developer-workflow/phase1-build-improve.mdx
  docs/docs/genai/eval-monitor/run-scorer-in-prod.mdx
  docs/docs/genai/flavors/dspy/notebooks/dspy_quickstart.ipynb
  docs/docs/genai/flavors/index.mdx
  docs/docs/genai/flavors/openai/notebooks/openai-code-helper.ipynb
  docs/docs/genai/getting-started/connect-environment.mdx
  docs/docs/genai/getting-started/index.mdx
  docs/docs/genai/index.mdx
  docs/docs/genai/overview/why-mlflow.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/compare-app-versions.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/index.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/link-evaluation-results-and-traces-to-app-versions.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/link-production-traces-to-app-versions.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/optionally-package-app-code-and-files-for-databricks-model-serving.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/track-application-versions-with-mlflow.mdx
  docs/docs/genai/serving/endpoint-creation.mdx
  docs/docs/genai/serving/index.mdx
  docs/docs/genai/tracing/app-instrumentation/index.mdx
  docs/docs/genai/tracing/collect-user-feedback/index.mdx
  docs/docs/genai/tracing/concepts/trace/feedback.mdx
  docs/docs/genai/tracing/lightweight-sdk.mdx
  docs/docs/genai/tracing/prod-tracing.mdx
  docs/docs/genai/tracing/quality-with-traces.mdx
  docs/docs/genai/tutorials/debug-tracing.mdx
  docs/docs/genai/tutorials/dev-quality-iteration.mdx
  docs/docs/genai/tutorials/enhance-quality.mdx
  docs/docs/genai/tutorials/index.mdx
  docs/docs/genai/tutorials/jupyter-trace-demo.ipynb
  docs/docusaurus.config.ts
  docs/sidebarsGenAI.ts
  docs/src/components/ComingSoon/index.tsx
  docs/yarn.lock
Labels: rn/none, area/tracking

#16198 Fix footer image CSS processing
  docs/src/components/Footer/Footer.tsx
Labels: rn/none, v3.0.0, v3.1.0

#16200 Minor doc fixes
  docs/docs/classic-ml/mlflow-3/index.mdx
  docs/docusaurus.config.ts
  docs/sidebarsClassicML.ts
  docs/src/css/custom.css
Labels: rn/none, v2.22.2

#16199 Only upload latest docs for preview
  .circleci/config.yml
Labels: rn/none, team-review

#16205 Update API docs styles
  docs/api_reference/theme/mlflow/side_nav.html
  docs/api_reference/theme/mlflow/static/css/custom.css
  docs/api_reference/theme/mlflow/static/css/theme.css
Labels: rn/none, v2.22.2

#16208 Styling nits
  docs/src/css/custom.css
  docs/src/pages/index.module.css
Labels: rn/none, v2.22.2

#16212 Add redirect for mlflow 3 page
  docs/docs/genai/mlflow-3/breaking-changes.mdx
  docs/docs/genai/mlflow-3/deep-learning.mdx
  docs/docs/genai/mlflow-3/faqs.mdx
  docs/docs/genai/mlflow-3/genai-agent.mdx
  docs/docs/genai/mlflow-3/index.mdx
  docs/docusaurus.config.ts
  docs/sidebarsClassicML.ts
  docs/sidebarsGenAI.ts
  docs/static/images/mlflow-3/landing-page.png
Labels: rn/none, area/tracking, team-review

#16207 CHANGELOG for 3.1
  CHANGELOG.md
Labels: rn/none, team-review

#16216 Remove temporary `mlflow` version requirement
  mlflow/utils/environment.py
Labels: rn/none, team-review

#16223 Replace mlflow 3.0 with mlflow 3
  docs/docs/classic-ml/getting-started/deep-learning.mdx
  docs/docs/classic-ml/model-registry/index.mdx
  docs/docs/classic-ml/tracking/index.mdx
  docs/docs/genai/eval-monitor/index.mdx
  docs/docs/genai/eval-monitor/llm-evaluation.mdx
  docs/docs/genai/getting-started/index.mdx
  docs/docs/genai/mlflow-3/breaking-changes.mdx
  docs/docs/genai/mlflow-3/deep-learning.mdx
  docs/docs/genai/mlflow-3/genai-agent.mdx
  docs/docs/genai/mlflow-3/index.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/quickstart.mdx
Labels: area/docs, rn/none, v3.1.1

#16214 Fix footer rendering in docs for light mode display
  docs/docusaurus.config.ts
  docs/src/components/Footer/Footer.tsx
  docs/src/components/FooterMenuItem/FooterMenuItem.module.css
  docs/src/components/FooterMenuItem/FooterMenuItem.tsx
  docs/static/images/footer-blue-bg-light.png
  docs/static/images/footer-colorful-bg-light.png
  docs/static/images/footer-red-bg-light.png
  docs/static/images/mlflow-logo-black.svg
Labels: area/docs, rn/documentation

#16210 Fix api docs makefile whitespace
  docs/api_reference/Makefile
Labels: rn/none

#16219 Add `version` parameter to `experimental` decorator
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  mlflow/ag2/__init__.py
  mlflow/anthropic/__init__.py
  mlflow/autogen/__init__.py
  mlflow/bedrock/__init__.py
  mlflow/crewai/__init__.py
  mlflow/deployments/databricks/__init__.py
  mlflow/dspy/autolog.py
  mlflow/dspy/load.py
  mlflow/dspy/save.py
  mlflow/entities/assessment.py
  mlflow/entities/assessment_error.py
  mlflow/entities/assessment_source.py
  mlflow/gemini/__init__.py
  mlflow/genai/evaluation/base.py
  mlflow/genai/judges/databricks.py
  mlflow/genai/optimize/base.py
  mlflow/genai/optimize/types.py
  mlflow/genai/prompts/__init__.py
  mlflow/genai/scheduled_scorers.py
  mlflow/genai/scorers/base.py
  mlflow/genai/scorers/builtin_scorers.py
  mlflow/groq/__init__.py
  mlflow/langchain/autolog.py
  mlflow/langchain/chat_agent_langgraph.py
  mlflow/langchain/model.py
  mlflow/langchain/output_parsers.py
  mlflow/litellm/__init__.py
  mlflow/llama_index/autolog.py
  mlflow/llama_index/model.py
  mlflow/metrics/__init__.py
  mlflow/metrics/genai/genai_metric.py
  mlflow/mistral/__init__.py
  mlflow/models/auth_policy.py
  mlflow/models/dependencies_schemas.py
  mlflow/models/model.py
  mlflow/models/python_api.py
  mlflow/models/utils.py
  mlflow/openai/autolog.py
  mlflow/openai/model.py
  mlflow/pydantic_ai/__init__.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/loaders/chat_agent.py
  mlflow/pyfunc/loaders/responses_agent.py
  mlflow/pyfunc/model.py
  mlflow/pyfunc/utils/input_converter.py
  mlflow/smolagents/__init__.py
  mlflow/store/_unity_catalog/registry/uc_oss_rest_store.py
  mlflow/tracing/assessment.py
  mlflow/tracing/destination.py
  mlflow/tracing/fluent.py
  mlflow/tracing/provider.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  mlflow/types/schema.py
  mlflow/utils/annotations.py
  pyproject.toml
Labels: rn/none, team-review

#16234 Unflake `test_databricks_sdk_retry_backoff_calculation`
  mlflow/utils/rest_utils.py
  tests/utils/test_rest_utils.py
Labels: rn/none, team-review

#16218 Fix model loading error message
  mlflow/store/artifact/runs_artifact_repo.py
  tests/spark/autologging/ml/test_pyspark_ml_autologging.py
Labels: rn/none, v2.22.2, v3.1.1

#16256 Introduce Resolver class for improved AST name resolution in clint
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/resolver.py
  dev/clint/src/clint/rules.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/none

#16263 Fix name binding logic for import statements in clint resolver
  dev/clint/src/clint/resolver.py
Labels: rn/none, team-review

#16246 Anthropic token count
  docs/docs/genai/tracing/integrations/listing/anthropic.mdx
  mlflow/anthropic/autolog.py
  tests/anthropic/test_anthropic_autolog.py
Labels: rn/feature, area/tracking

#16271 Enable configuring chunk size of PresignedUrlArtifactRepository
  mlflow/store/artifact/presigned_url_artifact_repo.py
  tests/store/artifact/test_presigned_url_artifact_repo.py
Labels: rn/none, area/artifacts, team-review, v3.1.1

#16283 Redirect from ml/mlflow-3 to genai/mlflow-3
  docs/docusaurus.config.ts
Labels: area/docs, rn/none, v3.1.1

#16281 Update docs font sizing and link coloring
  docs/src/css/custom.css
Labels: area/docs, rn/documentation, team-review

#16275 Fix crewai tests
  tests/crewai/test_crewai_autolog.py
Labels: rn/none, team-review

#16290 Fix duplicated redirection setting
  docs/docusaurus.config.ts
Labels: area/docs, rn/none, v3.1.1

#16227 Fix graphql batching attacks
  mlflow/environment_variables.py
  mlflow/server/graphql/graphql_no_batching.py
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/bug-fix, team-review, v2.22.2, v3.1.1

#15976 Experiment list page
  mlflow/server/js/src/common/components/MlflowHeader.tsx
  mlflow/server/js/src/common/constants.tsx
  mlflow/server/js/src/experiment-tracking/actions.ts
  mlflow/server/js/src/experiment-tracking/components/ExperimentListTable.tsx
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.test.tsx
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.tsx
  mlflow/server/js/src/experiment-tracking/components/ExperimentPage.test.tsx
  mlflow/server/js/src/experiment-tracking/components/ExperimentPage.tsx
  mlflow/server/js/src/experiment-tracking/components/HomePage.test.tsx
  mlflow/server/js/src/experiment-tracking/components/HomePage.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/ExperimentView.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/header/ExperimentViewHeader.test.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/header/ExperimentViewHeader.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/header/ExperimentViewHeaderCompare.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/RunsSearchTooltipContent.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/hooks/useExperimentListQuery.ts
  mlflow/server/js/src/experiment-tracking/components/modals/CreateExperimentModal.enzyme.test.tsx
  mlflow/server/js/src/experiment-tracking/components/modals/CreateExperimentModal.tsx
  mlflow/server/js/src/experiment-tracking/components/modals/DeleteExperimentModal.enzyme.test.tsx
  mlflow/server/js/src/experiment-tracking/components/modals/DeleteExperimentModal.tsx
  mlflow/server/js/src/experiment-tracking/reducers/Reducers.test.ts
  mlflow/server/js/src/experiment-tracking/reducers/Reducers.ts
  mlflow/server/js/src/experiment-tracking/route-defs.ts
  mlflow/server/js/src/experiment-tracking/types.ts
  mlflow/server/js/src/lang/default/en.json
  mlflow/server/js/src/model-registry/components/model-list/ModelListFilters.tsx
Labels: rn/none

#16298 [TS #1] Initial package skeleton
  packages/typescript/.eslintrc.json
  packages/typescript/.prettierrc
  packages/typescript/CLAUDE.md
  packages/typescript/README.md
  packages/typescript/jest.config.js
  packages/typescript/package-lock.json
  packages/typescript/package.json
  packages/typescript/src/index.ts
  packages/typescript/tsconfig.json
  packages/typescript/yarn.lock
Labels: rn/none, area/tracking

#16305 Add rename experiment capability to experiment page
  mlflow/server/js/src/experiment-tracking/components/ExperimentPage.test.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/header/ExperimentViewHeader.test.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/header/ExperimentViewHeader.tsx
  mlflow/server/js/src/experiment-tracking/components/modals/RenameExperimentModal.tsx
  mlflow/server/js/src/lang/default/en.json
Labels: rn/none

#16295 Specify attribute.run_id when search_traces filters by run_id
  mlflow/tracing/client.py
  tests/tracing/test_fluent.py
Labels: rn/bug-fix, area/tracking, v3.1.1

#16316 Update utm_source for source tracking to signup URL
  docs/docs/classic-ml/deep-learning/tensorflow/quickstart/quickstart-tensorflow.ipynb
  docs/docs/classic-ml/getting-started/databricks-trial/index.mdx
  docs/docs/classic-ml/getting-started/hyperparameter-tuning/index.mdx
  docs/docs/classic-ml/traditional-ml/sklearn/quickstart/quickstart-sklearn.ipynb
  docs/docs/genai/tracing/lightweight-sdk.mdx
Labels: area/docs, rn/documentation, team-review, v3.1.1

#16276 Fix whisper example
  examples/transformers/whisper.py
Labels: rn/none, team-review

#16280 Update the docs selector dropdown
  docs/docusaurus.config.ts
  docs/src/components/NavbarItems/DocsDropdown.module.css
  docs/src/components/NavbarItems/DocsDropdown.tsx
  docs/src/css/custom.css
  docs/src/theme/NavbarItem/ComponentTypes.tsx
Labels: area/docs, rn/documentation, team-review, v3.1.1

#16308 Fix clear active model
  mlflow/tracking/fluent.py
  mlflow/utils/thread_utils.py
Labels: rn/none, team-review, v3.1.1

#16327 Fix `mlflow.genai.evaluate` example
  docs/docs/genai/overview/why-mlflow.mdx
Labels: rn/none

#16309 Move experiments search to url query and backend, add page size setting dropdown
  mlflow/server/js/src/experiment-tracking/components/ExperimentListTable.tsx
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.test.tsx
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.tsx
  mlflow/server/js/src/experiment-tracking/components/HomePage.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/hooks/useExperimentListQuery.ts
  mlflow/server/js/src/experiment-tracking/components/experiment-page/hooks/useSearchFilter.tsx
  mlflow/server/js/src/lang/default/en.json
  mlflow/server/js/src/shared/web-shared/hooks/useLocalStorage.ts
Labels: rn/none

#16299 [TS #2] Add span related entities
  mlflow/entities/span.py
  packages/typescript/.eslintrc.json
  packages/typescript/package-lock.json
  packages/typescript/package.json
  packages/typescript/src/core/constants.ts
  packages/typescript/src/core/entities/span.ts
  packages/typescript/src/core/entities/span_event.ts
  packages/typescript/src/core/entities/span_status.ts
  packages/typescript/src/core/utils/index.ts
  packages/typescript/src/core/utils/json.ts
  packages/typescript/tests/core/entities/span.test.ts
  packages/typescript/tests/core/entities/span_event.test.ts
  packages/typescript/tests/core/entities/span_status.test.ts
  packages/typescript/tests/core/utils/index.test.ts
  packages/typescript/yarn.lock
Labels: rn/none, area/tracking

#15788 [1/2] Drop support for Python 3.9
  .devcontainer/Dockerfile.devcontainer
  .devcontainer/README.md
  .github/actions/setup-python/action.yml
  Dockerfile
  dev/set_matrix.py
  examples/llama_index/workflow/pyproject.toml
  examples/mlflow_artifacts/Dockerfile
  examples/mlflow_artifacts/Dockerfile.dev
  examples/supply_chain_security/python_env.yaml
  mlflow/models/docker_utils.py
  pyproject.toml
  tests/db/Dockerfile
  tests/db/Dockerfile.mssql
  tests/projects/test_docker_projects.py
  tests/resources/dockerfile/Dockerfile_install_mlflow_virtualenv
  tests/resources/dockerfile/Dockerfile_java_flavor
  tests/resources/dockerfile/Dockerfile_no_model_uri
  tests/resources/dockerfile/Dockerfile_sagemaker_virtualenv
  tests/resources/dockerfile/Dockerfile_sagemaker_virtualenv_no_java
  tests/resources/example_docker_project/Dockerfile
  tests/resources/example_mlflow_1x_sklearn_model/MLmodel
  tests/resources/example_mlflow_1x_sklearn_model/conda.yaml
  tests/resources/example_mlflow_1x_sklearn_model/python_env.yaml
  tests/resources/example_project/conda.yaml
  tests/resources/example_virtualenv_conda_project/conda.yaml
  tests/resources/example_virtualenv_conda_project/entrypoint.py
  tests/resources/example_virtualenv_no_python_env/entrypoint.py
  tests/resources/example_virtualenv_no_python_env/python_env.yaml
  tests/resources/example_virtualenv_project/entrypoint.py
  tests/resources/example_virtualenv_project/python_env.yaml
Labels: rn/none, only-latest, team-review, py310

#16323 Fix `B006` lint error in `create_labeling_session` by avoiding mutable defaults
  dev/clint/src/clint/comments.py
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  mlflow/genai/labeling/__init__.py
Labels: rn/none, team-review

#16347 Restore YamlSafeDumper for fs backwards compatibility
  mlflow/utils/file_utils.py
Labels: rn/none, team-review, v3.1.1, v3.0.1

#16332 Bulk delete experiments
  mlflow/server/js/src/experiment-tracking/components/ExperimentListView.tsx
  mlflow/server/js/src/experiment-tracking/components/modals/BulkDeleteExperimentModal.test.tsx
  mlflow/server/js/src/experiment-tracking/components/modals/BulkDeleteExperimentModal.tsx
  mlflow/server/js/src/experiment-tracking/components/modals/ConfirmModal.tsx
  mlflow/server/js/src/lang/default/en.json
Labels: rn/none

#15604 Fix bedrock provider, configured inference profile compatibility
  mlflow/gateway/providers/bedrock.py
  tests/gateway/providers/test_bedrock.py
Labels: rn/bug-fix, area/models, v3.1.1, v3.0.1

#16350 Add code review guidelines in `.github/copilot-instructions.md`
  .github/copilot-instructions.md
Labels: rn/none, team-review

#16348 Update docs for remote tracking server
  docs/docs/classic-ml/tracking/tutorials/remote-server/index.mdx
Labels: area/docs, rn/none, team-review, v3.1.1

#16352 Fix `mlflow.genai.evaluate` call with non-existing arguments
  docs/docs/genai/tracing/search-traces.mdx
Labels: rn/none, team-review, v3.1.1

#16325 Support pagination in get-history of FileStore and SqlAlchemyStore
  mlflow/java/client/src/main/java/org/mlflow/tracking/MlflowClient.java
  mlflow/server/handlers.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/test_rest_tracking.py
Labels: rn/feature, area/tracking, team-review, v3.1.1

#16322 Add run_id to Assessments to support table storage
  mlflow/entities/assessment.py
  tests/entities/test_assessment.py
Labels: rn/feature, area/tracking

#16364 Update CRAN maintainer
  mlflow/R/mlflow/DESCRIPTION
Labels: language/r, rn/none, area/build, v3.1.1, v3.0.1

#16340 Mistral Token Count + Doc Update
  docs/docs/genai/tracing/integrations/listing/mistral.mdx
  mlflow/mistral/autolog.py
  tests/mistral/test_mistral_autolog.py
Labels: rn/feature, area/tracking

#16331 Fix spark test
  tests/spark/test_spark_model_export.py
Labels: rn/none, area/build, enable-dev-tests

#16312 AG2 Token Count + Doc Update
  docs/docs/genai/tracing/integrations/listing/ag2.mdx
  mlflow/ag2/ag2_logger.py
  tests/ag2/test_ag2_autolog.py
Labels: rn/feature, area/tracking

#16313 Autogen token count
  docs/docs/genai/tracing/integrations/listing/autogen.mdx
  mlflow/autogen/__init__.py
  tests/autogen/test_autogen_autolog.py
Labels: rn/feature, area/tracking

#16344 Support PII masking via custom span post-processor
  mlflow/entities/span.py
  mlflow/tracing/__init__.py
  mlflow/tracing/config.py
  mlflow/tracing/provider.py
  mlflow/tracing/utils/processor.py
  tests/tracing/utils/test_config.py
  tests/tracing/utils/test_processor.py
Labels: rn/feature, area/tracking

#16356 Support downloading logged model artifacts
  mlflow/server/js/src/experiment-tracking/components/ArtifactView.tsx
Labels: rn/bug-fix, team-review, v3.1.1

#16381 Migrate SQLAlchemyStore to use V3 trace schema
  mlflow/entities/trace_info_v2.py
  mlflow/server/handlers.py
  mlflow/store/db/utils.py
  mlflow/store/db_migrations/versions/5b0e9adcef9c_add_cascade_deletion_to_trace_tables_fk.py
  mlflow/store/db_migrations/versions/867495a8f9d4_add_trace_tables.py
  mlflow/store/db_migrations/versions/cbc13b556ace_add_v3_trace_schema_columns.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/dbmodels/models.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracing/client.py
  mlflow/tracing/constant.py
  mlflow/tracing/export/mlflow_v3.py
  mlflow/tracing/fluent.py
  mlflow/tracing/processor/mlflow_v3.py
  mlflow/tracing/provider.py
  mlflow/tracing/utils/truncation.py
  mlflow/tracking/client.py
  tests/db/schemas/mssql.sql
  tests/db/schemas/mysql.sql
  tests/db/schemas/postgresql.sql
  tests/db/schemas/sqlite.sql
  tests/entities/test_trace.py
  tests/genai/evaluate/test_to_predict_fn.py
  tests/resources/db/latest_schema.sql
  tests/store/model_registry/test_abstract_store.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_rest_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracing/conftest.py
  tests/tracing/test_fluent.py
  tests/tracing/test_provider.py
  tests/tracing/utils/test_truncation.py
  tests/tracing/utils/test_utils.py
  tests/tracking/test_client.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, area/tracking, team-review

#16404 Move the Lighthouse main signup page to GenAI
  docs/docs/genai/getting-started/databricks-trial/index.mdx
  docs/docusaurus.config.ts
  docs/sidebarsClassicML.ts
  docs/sidebarsGenAI.ts
Labels: area/docs, rn/documentation, team-review, v3.1.1

#16397 [DOC-FIX] Dspy doc fix
  docs/docs/genai/tracing/integrations/listing/dspy.mdx
Labels: area/docs, rn/documentation, v3.1.1

#16415 Remove commented-out markdown cells from Keras quickstart notebook
  docs/docs/classic-ml/deep-learning/keras/quickstart/quickstart-keras.ipynb
Labels: area/docs, rn/none, team-review

#16416 Fix HTML comments in MDX files by converting to JSX comments
  docs/docs/genai/flavors/openai/autologging/index.mdx
  docs/docs/genai/prompt-version-mgmt/prompt-registry/use-prompts-in-apps.mdx
  docs/docs/genai/prompt-version-mgmt/prompt-registry/use-prompts-in-deployed-apps.mdx
  docs/docs/genai/prompt-version-mgmt/version-tracking/compare-app-versions.mdx
Labels: area/docs, rn/none, team-review

#16417 Remove empty JSX expressions from documentation links
  docs/docs/classic-ml/deployment/deploy-model-to-sagemaker/index.mdx
  docs/docs/classic-ml/deployment/index.mdx
  docs/docs/classic-ml/model/index.mdx
  docs/docs/classic-ml/search/search-runs/index.mdx
Labels: area/docs, rn/none, team-review

#16301 [TS #3] Add trace level entities
  packages/typescript/src/core/entities/span.ts
  packages/typescript/src/core/entities/trace.ts
  packages/typescript/src/core/entities/trace_data.ts
  packages/typescript/src/core/entities/trace_info.ts
  packages/typescript/src/core/entities/trace_location.ts
  packages/typescript/src/core/entities/trace_state.ts
  packages/typescript/tests/core/entities/trace.test.ts
  packages/typescript/tests/core/entities/trace_info.test.ts
  packages/typescript/tests/core/entities/trace_location.test.ts
  packages/typescript/tests/core/entities/trace_state.test.ts
Labels: rn/none, area/tracking

#16386 [TS #3.5] Add CI job
  .github/workflows/typescript.yml
  .pre-commit-config.yaml
  packages/typescript/.prettierignore
  packages/typescript/jest.config.js
  packages/typescript/package-lock.json
  packages/typescript/src/core/constants.ts
  packages/typescript/src/core/entities/span.ts
  packages/typescript/src/core/utils/index.ts
  packages/typescript/src/core/utils/json.ts
  packages/typescript/tests/core/entities/span.test.ts
  packages/typescript/tests/core/entities/span_status.test.ts
  packages/typescript/tests/core/utils/index.test.ts
  packages/typescript/yarn.lock
Labels: rn/none, area/build

#16434 Remove sections with broken links from GenAI docs
  docs/docs/genai/overview/key-challenges.mdx
  docs/docs/genai/overview/why-mlflow.mdx
Labels: area/docs, rn/none, v3.1.1

#16433 Add ESLint rule to validate NotebookDownloadButton URLs
  docs/eslint-plugin-mlflow-docs/index.js
  docs/eslint-plugin-mlflow-docs/rules/valid-notebook-url.js
  docs/eslint.config.js
  docs/package.json
  docs/yarn.lock
Labels: area/docs, rn/none

#16349 [TS #4] Add `startSpan` API and in-memory trace manager
  packages/typescript/.eslintrc.json
  packages/typescript/src/core/api.ts
  packages/typescript/src/core/entities/span.ts
  packages/typescript/src/core/entities/span_status.ts
  packages/typescript/src/core/entities/trace_data.ts
  packages/typescript/src/core/entities/trace_info.ts
  packages/typescript/src/core/provider.ts
  packages/typescript/src/core/trace_manager.ts
  packages/typescript/src/core/utils/index.ts
  packages/typescript/src/exporters/mlflow.ts
  packages/typescript/tests/core/api.test.ts
  packages/typescript/tests/core/entities/span.test.ts
  packages/typescript/tests/core/entities/span_status.test.ts
  packages/typescript/tests/core/entities/trace.test.ts
  packages/typescript/tests/core/trace_manager.test.ts
  packages/typescript/tests/core/utils/index.test.ts
  packages/typescript/tests/helper.ts
Labels: rn/none, area/tracking

#16445 Fix R crate() function calls to use explicit model parameter
  mlflow/R/mlflow/tests/testthat/test-model.R
Labels: language/r, rn/none, team-review

#16447 Revert bold links on hover
  docs/src/css/custom.css
Labels: area/docs, rn/none, v3.1.2

#16319 Add FileStore handling for Update and Delete assessments
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/file_store.py
  tests/store/tracking/test_file_store.py
Labels: rn/feature, area/tracking

#16394 Add lint rule to enforce parameterized generic types
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  docs/docs/classic-ml/deep-learning/sentence-transformers/tutorials/paraphrase-mining/paraphrase-mining-sentence-transformers.ipynb
  examples/promptflow/basic/_utils.py
  examples/promptflow/basic/hello.py
  mlflow/anthropic/chat.py
  mlflow/artifacts/__init__.py
  mlflow/bedrock/_autolog.py
  mlflow/bedrock/chat.py
  mlflow/bedrock/stream.py
  mlflow/data/dataset_registry.py
  mlflow/dspy/util.py
  mlflow/gateway/uc_function_utils.py
  mlflow/genai/datasets/evaluation_dataset.py
  mlflow/genai/evaluation/base.py
  mlflow/genai/scorers/base.py
  mlflow/genai/scorers/builtin_scorers.py
  mlflow/genai/scorers/scorer_utils.py
  mlflow/genai/scorers/validation.py
  mlflow/genai/utils/data_validation.py
  mlflow/genai/utils/trace_utils.py
  mlflow/langchain/api_request_parallel_processor.py
  mlflow/langchain/chat_agent_langgraph.py
  mlflow/langchain/utils/chat.py
  mlflow/langchain/utils/logging.py
  mlflow/llama_index/pyfunc_wrapper.py
  mlflow/llama_index/serialize_objects.py
  mlflow/mistral/chat.py
  mlflow/models/dependencies_schemas.py
  mlflow/models/evaluation/default_evaluator.py
  mlflow/models/model.py
  mlflow/models/resources.py
  mlflow/models/utils.py
  mlflow/openai/api_request_parallel_processor.py
  mlflow/openai/utils/chat_schema.py
  mlflow/promptflow/__init__.py
  mlflow/pyfunc/context.py
  mlflow/pyfunc/scoring_server/__init__.py
  mlflow/pyfunc/utils/serving_data_parser.py
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/dbfs_artifact_repo.py
  mlflow/tracing/export/async_export_queue.py
  mlflow/tracing/fluent.py
  mlflow/tracing/utils/__init__.py
  mlflow/tracking/multimedia.py
  mlflow/transformers/llm_inference_utils.py
  mlflow/types/schema.py
  mlflow/types/utils.py
  mlflow/utils/autologging_utils/config.py
  mlflow/utils/autologging_utils/safety.py
  mlflow/utils/docstring_utils.py
  mlflow/utils/environment.py
  mlflow/utils/pydantic_utils.py
  mlflow/utils/rest_utils.py
  tests/genai/evaluate/test_evaluation.py
  tests/pyfunc/test_mlserver.py
  tests/pyfunc/test_scoring_server.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracing/helper.py
Labels: rn/none, area/build, team-review

#16457 Fix clint violations: Replace `name` with `artifact_path` in mlflow.spark.log_model examples
  docs/docs/classic-ml/traditional-ml/sparkml/guide/index.mdx
  docs/docs/classic-ml/traditional-ml/sparkml/index.mdx
Labels: area/docs, rn/none, team-review, v3.1.2

#16458 Fix non-existent `mlflow.active_experiment()` calls in GenAI docs
  docs/docs/genai/getting-started/connect-environment.mdx
Labels: area/docs, rn/none, team-review

#16446 Fix bullet points in docs
  docs/docs/classic-ml/dataset/index.mdx
  docs/docs/classic-ml/index.mdx
  docs/docs/classic-ml/model/signatures/index.mdx
  docs/docs/genai/index.mdx
Labels: area/docs, rn/none, v3.1.2

#16442 Update ArtifactRepository constructors to accept tracking_uri parameter
  mlflow/store/artifact/artifact_repo.py
  mlflow/store/artifact/artifact_repository_registry.py
  mlflow/store/artifact/azure_blob_artifact_repo.py
  mlflow/store/artifact/azure_data_lake_artifact_repo.py
  mlflow/store/artifact/cloud_artifact_repo.py
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/databricks_logged_model_artifact_repo.py
  mlflow/store/artifact/databricks_models_artifact_repo.py
  mlflow/store/artifact/databricks_sdk_artifact_repo.py
  mlflow/store/artifact/dbfs_artifact_repo.py
  mlflow/store/artifact/ftp_artifact_repo.py
  mlflow/store/artifact/gcs_artifact_repo.py
  mlflow/store/artifact/hdfs_artifact_repo.py
  mlflow/store/artifact/local_artifact_repo.py
  mlflow/store/artifact/mlflow_artifacts_repo.py
  mlflow/store/artifact/models_artifact_repo.py
  mlflow/store/artifact/runs_artifact_repo.py
  mlflow/store/artifact/s3_artifact_repo.py
  mlflow/store/artifact/sftp_artifact_repo.py
  mlflow/store/artifact/uc_volume_artifact_repo.py
  tests/store/artifact/test_artifact_repository_registry.py
  tests/store/artifact/test_azure_blob_artifact_repo.py
  tests/store/artifact/test_azure_data_lake_artifact_repo.py
  tests/store/artifact/test_dbfs_artifact_repo.py
  tests/store/artifact/test_gcs_artifact_repo.py
Labels: rn/feature, area/artifacts, area/tracking, integrations/azure, integrations/databricks

#16459 Improve error message for datatime schema check
  mlflow/models/utils.py
  mlflow/pyfunc/__init__.py
Labels: rn/none, team-review

#16456 Add mlflow function validation rules in clint
  dev/clint/src/clint/__init__.py
  dev/clint/src/clint/index.py
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  docs/docs/classic-ml/auth/index.mdx
  docs/docs/classic-ml/community-model-flavors/index.mdx
  docs/docs/classic-ml/deep-learning/tensorflow/guide/index.mdx
  docs/docs/classic-ml/traditional-ml/sparkml/guide/index.mdx
  docs/docs/genai/prompt-version-mgmt/prompt-registry/index.mdx
  docs/docs/genai/prompt-version-mgmt/prompt-registry/manage-prompt-lifecycles-with-aliases.mdx
  docs/docs/genai/tracing/faq.mdx
  docs/docs/genai/tracing/quality-with-traces.mdx
  docs/docs/genai/tracing/search-traces.mdx
  docs/docs/prompts/index.mdx
  pyproject.toml
Labels: area/docs, rn/none, area/examples, area/build, team-review

#16430 Add functionality for assessments APIs in TracingClient to work in OSS
  mlflow/entities/assessment.py
  mlflow/server/handlers.py
  mlflow/store/db_migrations/versions/770bee3ae1dd_add_assessments_table.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracing/assessment.py
  mlflow/tracing/client.py
  mlflow/tracking/client.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_rest_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracing/test_assessment.py
  tests/tracking/test_rest_tracking.py
Labels: rn/feature, area/tracking

#16465 Refactor `LogModelArtifactPath` rule to use `SymbolIndex`
  dev/clint/src/clint/index.py
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  dev/clint/src/clint/utils.py
  mlflow/genai/prompts/__init__.py
  mlflow/metrics/genai/base.py
  mlflow/pytorch/__init__.py
  mlflow/pytorch/_lightning_autolog.py
  mlflow/sagemaker/__init__.py
  mlflow/spark/__init__.py
  mlflow/tracking/_model_registry/fluent.py
Labels: rn/none, team-review

#16473 Store failed Python tests as GitHub Action summary
  conftest.py
Labels: rn/none, area/build, team-review

#16470 Fix content issues with tracing docs
  docs/docs/genai/tracing/observe-with-traces/index.mdx
  docs/docs/genai/tracing/observe-with-traces/query-via-sdk.mdx
Labels: area/docs, rn/documentation, team-review, v3.1.2
