Repository mlflow/mlflow, pull requests merged in 2025-08, with the labels that each got.

#16987 Fix lang localization json file key mis-match with default en.json
  mlflow/server/js/src/lang/de-DE.json
  mlflow/server/js/src/lang/es-ES.json
  mlflow/server/js/src/lang/fr-FR.json
  mlflow/server/js/src/lang/it-IT.json
  mlflow/server/js/src/lang/ja-JP.json
  mlflow/server/js/src/lang/ko-KR.json
  mlflow/server/js/src/lang/pt-BR.json
  mlflow/server/js/src/lang/pt-PT.json
  mlflow/server/js/src/lang/zh-CN.json
  mlflow/server/js/src/lang/zh-HK.json
  mlflow/server/js/src/lang/zh-TW.json
Labels: rn/none, area/uiux, v3.2.0

#16981 Fix set_destination
  mlflow/tracing/provider.py
  tests/tracing/test_provider.py
Labels: rn/none, v3.2.0

#16977 Replace Scheduled Scorers API to a Scorer Registration System
  mlflow/genai/__init__.py
  mlflow/genai/scheduled_scorers.py
  mlflow/genai/scorers/__init__.py
  mlflow/genai/scorers/base.py
  mlflow/genai/scorers/builtin_scorers.py
  mlflow/genai/scorers/registry.py
  tests/genai/scorers/test_registered_scorers.py
  tests/genai/test_genai_import_without_agent_sdk.py
Labels: rn/feature, v3.2.0

#17024 Add mypy type checking to dev/clint
  .pre-commit-config.yaml
  dev/clint/src/clint/__init__.py
  dev/clint/src/clint/comments.py
  dev/clint/src/clint/config.py
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/resolver.py
  dev/clint/src/clint/rules/base.py
  dev/clint/src/clint/rules/do_not_disable.py
  dev/clint/src/clint/rules/forbidden_set_active_model_usage.py
  dev/clint/src/clint/rules/implicit_optional.py
  dev/clint/src/clint/rules/thread_pool_executor_without_thread_name_prefix.py
  dev/clint/src/clint/rules/unnamed_thread.py
  dev/clint/src/clint/rules/unparameterized_generic_type.py
  pyproject.toml
  requirements/lint-requirements.txt
Labels: rn/none, area/build

#17018 Add linting rule to prevent mlflow.get_artifact_uri usage in examples
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules/__init__.py
  dev/clint/src/clint/rules/get_artifact_uri.py
  dev/clint/tests/rules/test_get_artifact_uri.py
  docs/docs/classic-ml/community-model-flavors/index.mdx
  docs/docs/classic-ml/evaluation/metrics-visualizations.mdx
  docs/docs/classic-ml/evaluation/model-eval.mdx
  docs/docs/classic-ml/evaluation/shap.mdx
  docs/docs/classic-ml/traditional-ml/index.mdx
  docs/docs/classic-ml/traditional-ml/sklearn/guide/index.mdx
  docs/docs/classic-ml/traditional-ml/xgboost/guide/index.mdx
  examples/gateway/mlflow_models/README.md
  mlflow/pmdarima/__init__.py
  pyproject.toml
Labels: area/docs, rn/none, area/build

#16998 Fix predict with pre-releases
  docs/docs/classic-ml/model/dependencies/index.mdx
  docs/docs/classic-ml/model/index.mdx
  docs/docs/classic-ml/model/python_model.mdx
  mlflow/models/python_api.py
  mlflow/pyfunc/backend.py
  mlflow/utils/virtualenv.py
  tests/projects/test_projects_cli.py
Labels: rn/bug-fix, v3.2.0

#16923 [GenAI] Initial implementation of Git versioning for model tracking
  mlflow/genai/__init__.py
  mlflow/genai/git_versioning/__init__.py
  mlflow/genai/git_versioning/git_info.py
  tests/genai/test_git_versioning.py
Labels: rn/feature, area/tracking

#17026 Fix model_validator
  mlflow/types/responses.py
  mlflow/types/responses_helpers.py
  mlflow/utils/pydantic_utils.py
Labels: rn/none, team-review, v3.2.0

#17020 Fix typo in docstring
  mlflow/tracking/fluent.py
Labels: area/docs, rn/none, area/tracking, v3.2.0

#17048 Disable eslint `no-nonnull-assertion` in tests
  mlflow/server/js/.eslintrc.js
  mlflow/server/js/src/common/components/error-boundaries/SectionErrorBoundary.test.tsx
Labels: rn/none, team-review, v3.2.0

#17017 Remove `MLFLOW_ENABLE_TRACE_DUAL_WRITE_IN_MODEL_SERVING` env var.
  mlflow/environment_variables.py
  mlflow/tracing/export/inference_table.py
  mlflow/tracing/processor/mlflow_v3.py
  tests/langchain/test_langchain_model_export.py
  tests/tracing/export/test_inference_table_exporter.py
Labels: rn/none, area/tracing, v3.2.0

#17036 Add API inventory check to documentation build
  docs/api_reference/api_inventory.txt
  docs/api_reference/source/conf.py
Labels: area/docs, rn/none, area/build

#17029 [GenAI] Implement git model versioning with automatic model creation and refactor tests
  mlflow/genai/git_versioning/__init__.py
  mlflow/genai/git_versioning/git_info.py
  mlflow/utils/mlflow_tags.py
  tests/genai/test_git_versioning.py
Labels: rn/feature, area/models, area/tracking, area/build

#17050 Add back chat attribute parsing if present
  mlflow/server/js/src/shared/web-shared/model-trace-explorer/ModelTraceExplorer.utils.test.tsx
  mlflow/server/js/src/shared/web-shared/model-trace-explorer/ModelTraceExplorer.utils.tsx
Labels: rn/none, area/uiux, v3.2.0

#16999 Update index.mdx regarding a single Typo
  docs/docs/classic-ml/deployment/deploy-model-locally/index.mdx
Labels: area/docs, rn/none, rn/documentation, v3.2.0

#17057 Consolidate requirements generation into pyproject.py
  .github/actions/update-requirements/action.yml
  .github/workflows/master.yml
  .github/workflows/protos.yml
  .pre-commit-config.yaml
  dev/extract_deps.py
  dev/generate_requirements.py
  dev/pyproject.py
  requirements/core-requirements.txt
  requirements/gateway-requirements.txt
  requirements/lint-requirements.txt
  requirements/skinny-requirements.txt
  requirements/tracing-requirements.txt
  tests/db/README.md
  tests/db/update_schemas.sh
Labels: rn/none, area/build, team-review

#17051 Add `remote_name` parameter to git versioning for repository URL extraction
  mlflow/genai/git_versioning/__init__.py
  mlflow/genai/git_versioning/git_info.py
  tests/genai/test_git_versioning.py
Labels: rn/feature, area/tracking

#17077 Move API inventory check from Sphinx conf.py to GitHub Actions workflow
  .github/workflows/docs.yml
  docs/api_reference/source/conf.py
Labels: rn/none, area/build, team-review

#16253 Allow users to pass the encoding tokenizer
  mlflow/metrics/__init__.py
  mlflow/metrics/metric_definitions.py
Labels: rn/feature, v2.22.2, v3.1.1

#17052 Refactor optimize_prompt to support custom optimizer
  docs/api_reference/api_inventory.txt
  mlflow/genai/optimize/__init__.py
  mlflow/genai/optimize/base.py
  mlflow/genai/optimize/optimizers/__init__.py
  mlflow/genai/optimize/optimizers/base_optimizer.py
  mlflow/genai/optimize/optimizers/dspy_mipro_optimizer.py
  mlflow/genai/optimize/optimizers/dspy_optimizer.py
  mlflow/genai/optimize/optimizers/utils/__init__.py
  mlflow/genai/optimize/optimizers/utils/dspy_mipro_callback.py
  mlflow/genai/optimize/optimizers/utils/dspy_optimizer_utils.py
  mlflow/genai/optimize/types.py
  tests/genai/optimize/optimizers/test_dspy_mipro_optimizer.py
  tests/genai/optimize/optimizers/test_dspy_optimizer.py
  tests/genai/optimize/optimizers/utils/test_dspy_optimizer_utils.py
  tests/genai/optimize/test_base.py
Labels: rn/feature, autoformat, team-review, area/prompts, v3.2.1

#17062 Fix llama_index
  mlflow/llama_index/tracer.py
  tests/llama_index/test_llama_index_autolog.py
  tests/llama_index/test_llama_index_model_export.py
  tests/llama_index/test_llama_index_tracer.py
Labels: rn/none, team-review

#17087 Add databricks/mosaicml guide for ai gateway
  docs/docs/genai/governance/ai-gateway/configuration.mdx
Labels: area/docs, rn/none, team-review

#17038 Make fastapi + uvicorn the default MLflow server backend, with flask compatibility middleware
  docs/docs/classic-ml/getting-started/logging-first-model/step1-tracking-server.mdx
  docs/docs/classic-ml/getting-started/registering-first-model/step2-explore-registered-model.mdx
  docs/docs/classic-ml/getting-started/tracking-server-overview/index.mdx
  docs/docs/classic-ml/model-registry/tutorial.mdx
  docs/docs/classic-ml/tracking/server/index.mdx
  docs/docs/genai/serving/index.mdx
  mlflow/cli.py
  mlflow/server/__init__.py
  mlflow/server/fastapi_app.py
  mlflow/utils/cli_args.py
  tests/server/auth/test_auth.py
  tests/server/test_init.py
  tests/test_cli.py
Labels: rn/feature, area/tracking

#17073 [1][Span logging] Introduce DB migrations for SqlAlchemyStore span logging
  mlflow/store/db_migrations/versions/a1b2c3d4e5f6_add_spans_table.py
  mlflow/store/tracking/dbmodels/models.py
  tests/db/schemas/mssql.sql
  tests/db/schemas/mysql.sql
  tests/db/schemas/postgresql.sql
  tests/db/schemas/sqlite.sql
  tests/resources/db/latest_schema.sql
Labels: rn/none, area/tracking

#17101 Fix DSPy test compatibility with dspy>=3.0.0
  tests/dspy/test_save.py
Labels: rn/none, area/models, enable-dev-tests

#17082 remove api_key before log to fix security thread
  mlflow/crewai/autolog.py
Labels: rn/bug-fix, area/tracing

#17079 [OSS GenAI Eval #7] Support `custom_prompt_judge` in OSS
  mlflow/genai/evaluation/entities.py
  mlflow/genai/judges/__init__.py
  mlflow/genai/judges/builtin.py
  mlflow/genai/judges/custom_prompt_judge.py
  mlflow/genai/judges/utils.py
  tests/genai/judges/conftest.py
  tests/genai/judges/test_builtin.py
  tests/genai/judges/test_custom_prompt_judge.py
  tests/genai/judges/test_judge_utils.py
Labels: rn/none, area/evaluation

#17080 Add TTL cache for webhook delivery with event-based filtering
  mlflow/environment_variables.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/webhooks/delivery.py
  tests/server/test_handlers.py
  tests/webhooks/test_e2e.py
Labels: rn/feature, area/model-registry

#17034 Add memory span type
  docs/docs/genai/tracing/concepts/span.mdx
  libs/typescript/core/src/core/constants.ts
  mlflow/crewai/autolog.py
  mlflow/entities/span.py
  mlflow/server/js/src/shared/web-shared/model-trace-explorer/ModelTrace.types.ts
  mlflow/server/js/src/shared/web-shared/model-trace-explorer/ModelTraceExplorer.utils.tsx
  mlflow/server/js/src/shared/web-shared/model-trace-explorer/ModelTraceExplorerIcon.tsx
  tests/crewai/test_crewai_autolog.py
Labels: rn/feature, team-review, area/tracing

#17120 Fix jupyter notebook bundle
  mlflow/server/js/craco.config.js
Labels: rn/none, team-review

#17127 Update warning section
  docs/docs/classic-ml/webhooks/index.mdx
Labels: rn/none

#17084 Document the usage of custom optimizers with optimize_prompt
  docs/docs/genai/prompt-registry/optimize-prompts.mdx
  mlflow/genai/optimize/base.py
  mlflow/genai/optimize/optimizers/base_optimizer.py
  mlflow/genai/optimize/optimizers/dspy_optimizer.py
  mlflow/genai/optimize/types.py
Labels: area/docs, rn/documentation, autoformat, team-review, v3.2.1

#17067 Deprecate set_destination API
  mlflow/tracing/destination.py
  mlflow/tracing/provider.py
Labels: rn/none, area/tracing, v3.3.0

#17132 Remove databricks-agents hard dependency in GenAI Evaluate
  .github/workflows/master.yml
  mlflow/genai/scorers/builtin_scorers.py
  mlflow/genai/scorers/validation.py
  mlflow/genai/utils/trace_utils.py
  tests/genai/conftest.py
  tests/genai/evaluate/test_evaluation.py
  tests/genai/evaluate/test_utils.py
  tests/genai/judges/conftest.py
  tests/genai/judges/test_builtin.py
  tests/genai/judges/test_custom_prompt_judge.py
  tests/genai/label_schemas/test_label_schemas.py
  tests/genai/labeling/test_labeling.py
  tests/genai/scorers/test_builtin_scorers.py
  tests/genai/scorers/test_scorer.py
  tests/genai/scorers/test_validation.py
  tests/genai/utils/test_trace_utils.py
Labels: rn/none, area/evaluation, v3.3.0

#17159 [OSS GenAI Eval #11] GenAI Eval minimum doc
  docs/docs/genai/assessments/expectations.mdx
  docs/docs/genai/assessments/feedback.mdx
  docs/docs/genai/eval-monitor/index.mdx
  docs/docs/genai/eval-monitor/legacy-llm-evaluation.mdx
  docs/docs/genai/eval-monitor/notebooks/huggingface-evaluation.ipynb
  docs/docs/genai/eval-monitor/notebooks/index.mdx
  docs/docs/genai/eval-monitor/notebooks/question-answering-evaluation.ipynb
  docs/docs/genai/eval-monitor/notebooks/rag-evaluation-llama2.ipynb
  docs/docs/genai/eval-monitor/notebooks/rag-evaluation.ipynb
  docs/docs/genai/eval-monitor/quickstart.mdx
  docs/docs/genai/getting-started/index.mdx
  docs/docs/genai/prompt-registry/evaluate-prompts.mdx
  docs/docs/genai/tracing/index.mdx
  docs/docusaurus.config.ts
  docs/sidebarsGenAI.ts
  docs/src/content/setup_server.mdx
  docs/static/images/llms/tracing/genai-evaluation-compare.png
  docs/static/images/mlflow-3/eval-monitor/evaluation-driven-development.png
  docs/static/images/mlflow-3/eval-monitor/quickstart-eval-hero.png
  docs/static/images/mlflow-3/eval-monitor/quickstart-eval-result.png
  docs/static/images/mlflow-3/eval-monitor/quickstart-eval-trace.png
  mlflow/server/js/src/shared/web-shared/genai-traces-table/components/GenAiEvaluationTracesReview.utils.tsx
Labels: rn/documentation, team-review, area/evaluation, v3.3.0

#17168 Handle UserMemory import conditionally in crewai
  mlflow/crewai/__init__.py
  mlflow/crewai/autolog.py
Labels: rn/none, enable-dev-tests, team-review

#17157 Retire _AUTOLOGGING_SUPPORTED_VERSION_WARNING_SUPPRESS_LIST list
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/autologging_utils/versioning.py
Labels: rn/none, area/tracking, team-review

#17170 Remove TensorFlow-based transformers tests
  mlflow/ml-package-versions.yml
  tests/pyfunc/docker/test_docker_flavors.py
  tests/transformers/conftest.py
  tests/transformers/helper.py
  tests/transformers/test_flavor_configs.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/none, area/build, team-review

#17176 Update `down_revision` in migration script to correct reference
  mlflow/store/db_migrations/versions/1a0cddfcaa16_add_webhooks_and_webhook_events_tables.py
  tests/db/schemas/mssql.sql
Labels: rn/none

#17169 Fix tracking_uri_scheme for tracing sdk
  mlflow/telemetry/client.py
  tests/telemetry/test_track.py
Labels: rn/none, team-review, v3.3.0

#17182 Enable diagnostic settings for agents in semantic kernel autolog
  mlflow/semantic_kernel/autolog.py
Labels: rn/none, enable-dev-tests

#17177 Import `WSGIMiddleware` from `fastapi`, not `starlette`
  mlflow/server/fastapi_app.py
Labels: rn/none, team-review

#17193 Revert "Deprecate set_destination API (#17067)"
  mlflow/tracing/destination.py
  mlflow/tracing/provider.py
Labels: rn/none, area/tracing, v3.3.0

#17192 Fix absolute URLs in new trace table code
  mlflow/server/js/src/shared/web-shared/genai-traces-table/cellRenderers/LoggedModelCell.tsx
  mlflow/server/js/src/shared/web-shared/genai-traces-table/hooks/useExperimentVersionsQuery.tsx
  mlflow/server/js/src/shared/web-shared/genai-traces-table/hooks/useGenAiTraceEvaluationArtifacts.tsx
  mlflow/server/js/src/shared/web-shared/genai-traces-table/hooks/useMlflowTraces.test.tsx
  mlflow/server/js/src/shared/web-shared/genai-traces-table/hooks/useMlflowTraces.tsx
Labels: rn/none, v3.3.0

#17166 Fix Databricks secret scope check to reduce error rates
  mlflow/utils/environment.py
Labels: rn/bug-fix, area/tracking, team-review, v3.3.0

#17198 Fix deprecated apt-key usage in MSSQL Dockerfile
  tests/db/Dockerfile.mssql
Labels: rn/none, area/build

#17203 Run mlflow server with sqlite
  docs/docs/classic-ml/webhooks/index.mdx
Labels: rn/none

#17200 Kill server worker process in teardown
  tests/store/model_registry/test_rest_store_webhooks.py
Labels: rn/none

#17199 Support uri model string in optimize
  mlflow/genai/optimize/base.py
  mlflow/genai/optimize/optimizers/dspy_mipro_optimizer.py
  mlflow/genai/optimize/optimizers/dspy_optimizer.py
  mlflow/genai/optimize/types.py
  tests/genai/optimize/optimizers/test_dspy_optimizer.py
Labels: rn/none, area/prompts, v3.2.1

#16583 Webhooks support
  dev/generate_protos.py
  dev/run-python-skinny-tests.sh
  docs/api_reference/api_inventory.txt
  docs/api_reference/source/python_api/mlflow.webhooks.rst
  docs/docs/classic-ml/webhooks/index.mdx
  docs/sidebarsClassicML.ts
  mlflow/entities/__init__.py
  mlflow/entities/model_registry/registered_model.py
  mlflow/entities/webhook.py
  mlflow/environment_variables.py
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Webhooks.java
  mlflow/protos/webhooks.proto
  mlflow/protos/webhooks_pb2.py
  mlflow/server/handlers.py
  mlflow/store/db_migrations/versions/1a0cddfcaa16_add_webhooks_and_webhook_events_tables.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/dbmodels/models.py
  mlflow/store/model_registry/rest_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/client.py
  mlflow/utils/validation.py
  mlflow/webhooks/__init__.py
  mlflow/webhooks/constants.py
  mlflow/webhooks/delivery.py
  mlflow/webhooks/types.py
  pyproject.release.toml
  pyproject.toml
  requirements/core-requirements.yaml
  tests/db/schemas/mssql.sql
  tests/db/schemas/mysql.sql
  tests/db/schemas/postgresql.sql
  tests/db/schemas/sqlite.sql
  tests/entities/test_webhook.py
  tests/resources/db/latest_schema.sql
  tests/server/test_handlers.py
  tests/store/model_registry/test_rest_store_webhooks.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/tracking/test_client_webhooks.py
  tests/webhooks/app.py
  tests/webhooks/test_e2e.py
Labels: rn/feature, team-review, rn/highlight

#17069 Tracing | Add OpenAI Responses API Built-In Tools
  mlflow/openai/utils/chat_schema.py
Labels: rn/none, area/tracing

#17205 Fix default value handling in `create_webhook`
  mlflow/server/handlers.py
Labels: rn/none, v3.3.0

#17212 Mark webhook APIs as experimental
  mlflow/tracking/client.py
Labels: rn/none

#17196 Add typehint notice
  docs/docs/classic-ml/model/python_model.mdx
Labels: rn/none, team-review, v3.3.0

#17216 Update `dev/update_changelog.py` to create a major new features section
  dev/update_changelog.py
Labels: rn/none, team-review

#17163 Fix issue with get_label_schema has no attribute
  mlflow/genai/label_schemas/label_schemas.py
  tests/genai/label_schemas/test_label_schemas.py
Labels: rn/bug-fix, area/evaluation, v3.2.1, v3.3.0

#17185 Fix trace enablement in oss genai eval
  mlflow/genai/evaluation/base.py
  mlflow/genai/evaluation/utils.py
  tests/genai/utils/test_trace_utils.py
Labels: rn/none, area/evaluation, v3.3.0

#17214 Add 3.3.0 CHANGELOG
  CHANGELOG.md
Labels: rn/none, team-review

#17227 Fix OpenAI Agents tracing
  docs/docusaurus.config.ts
  mlflow/ml-package-versions.yml
  mlflow/openai/_agent_tracer.py
  mlflow/openai/autolog.py
  tests/openai/test_openai_agent_autolog.py
Labels: rn/bug-fix, team-review, area/tracing, v3.3.0

#17231 Add protobuf stub file generation to generate_protos.py
  dev/generate_protos.py
  mlflow/protos/assessments_pb2.pyi
  mlflow/protos/databricks_artifacts_pb2.pyi
  mlflow/protos/databricks_filesystem_service_pb2.pyi
  mlflow/protos/databricks_managed_catalog_messages_pb2.pyi
  mlflow/protos/databricks_managed_catalog_service_pb2.pyi
  mlflow/protos/databricks_pb2.pyi
  mlflow/protos/databricks_trace_server_pb2.pyi
  mlflow/protos/databricks_uc_registry_messages_pb2.pyi
  mlflow/protos/databricks_uc_registry_service_pb2.pyi
  mlflow/protos/facet_feature_statistics_pb2.pyi
  mlflow/protos/internal_pb2.pyi
  mlflow/protos/mlflow_artifacts_pb2.pyi
  mlflow/protos/model_registry_pb2.pyi
  mlflow/protos/scalapb/scalapb_pb2.pyi
  mlflow/protos/service_pb2.pyi
  mlflow/protos/unity_catalog_oss_messages_pb2.pyi
  mlflow/protos/unity_catalog_oss_service_pb2.pyi
  mlflow/protos/unity_catalog_prompt_messages_pb2.pyi
  mlflow/protos/unity_catalog_prompt_service_pb2.pyi
  mlflow/protos/webhooks_pb2.pyi
Labels: rn/none, area/build, team-review

#17187 Support OTel and MLflow dual export
  docs/docs/genai/tracing/prod-tracing.mdx
  mlflow/environment_variables.py
  mlflow/tracing/processor/otel.py
  mlflow/tracing/provider.py
  tests/tracing/conftest.py
  tests/tracing/test_provider.py
  tests/tracing/utils/test_otlp.py
Labels: rn/feature, area/tracing

#17260 Track prompt optimization
  docs/docs/community/usage-tracking.mdx
  mlflow/genai/optimize/base.py
  mlflow/telemetry/events.py
  requirements/test-requirements.txt
  tests/telemetry/test_tracked_events.py
Labels: rn/none, team-review, v3.3.0

#17269 Add temporary pin for OpenAI due to breaking changes with LiteLLM
  requirements/constraints.txt
Labels: rn/none, area/build, team-review

#17281 Revert "Introduce `mlflow autolog claude` to trace claude code interections
  .gitignore
  mlflow/claude_code/README.md
  mlflow/claude_code/__init__.py
  mlflow/claude_code/cli.py
  mlflow/claude_code/config.py
  mlflow/claude_code/hooks.py
  mlflow/claude_code/tracing.py
  mlflow/cli.py
  tests/claude_code/test_cli.py
  tests/claude_code/test_config.py
  tests/claude_code/test_tracing.py
Labels: rn/none

#17262 Track GenAI evaluate event
  docs/docs/community/usage-tracking.mdx
  mlflow/genai/evaluation/base.py
  mlflow/telemetry/events.py
  tests/telemetry/test_tracked_events.py
Labels: rn/none, team-review

#17289 Create experimental `enable_databricks_trace_archival` and `disable_databricks_trace_archival` APIs
  mlflow/tracing/archival.py
  tests/tracing/test_archival.py
Labels: rn/none, team-review, area/evaluation, v3.3.0

#17272 ResponsesAgent `Message` class allow empty content
  mlflow/types/responses_helpers.py
  tests/pyfunc/test_responses_agent_validation.py
Labels: rn/none, area/models, v3.3.1

#17290 Fix the slowness of dspy tracing
  mlflow/dspy/callback.py
  tests/dspy/test_dspy_autolog.py
Labels: rn/bug-fix, team-review, area/tracing, v3.3.1

#17296 Fix tag display as column in experiment overview
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/ExperimentViewRunsTable.enzyme.test.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/ExperimentViewRunsTable.tsx
Labels: rn/bug-fix, area/uiux, v3.3.1

#17295 Fix pyspark ml autolog docstring
  mlflow/pyspark/ml/__init__.py
Labels: area/docs, rn/none, v3.3.1

#17250 Add support for dataset name persistence
  mlflow/data/evaluation_dataset.py
  mlflow/genai/evaluation/base.py
  tests/genai/evaluate/test_evaluation.py
Labels: rn/feature, team-review, area/evaluation, v3.3.1

#17116 Fixed workspace id resolution and genai view creation in external environments
  .github/workflows/master.yml
  mlflow/genai/experimental/databricks_trace_archival.py
  mlflow/genai/experimental/databricks_trace_exporter_utils.py
  tests/genai/experimental/test_databricks_trace_exporter_utils.py
  tests/genai/test_genai_import_without_agent_sdk.py
Labels: rn/none, area/tracing

#17322 show axis labels for parallel coordinates chart in expanded state
  mlflow/server/js/src/experiment-tracking/components/runs-charts/components/charts/ParallelCoordinatesPlot.tsx
Labels: rn/none, area/uiux

#17301 Fix LC cross version test
  tests/langchain/test_langchain_databricks_dependency_extraction.py
  tests/langchain/test_langchain_databricks_integration.py
Labels: rn/none, area/models, team-review

#17242 Updated otel schema and archival genai view
  mlflow/genai/experimental/databricks_trace_archival.py
  mlflow/genai/experimental/databricks_trace_exporter.py
  mlflow/genai/experimental/databricks_trace_exporter_utils.py
  mlflow/genai/experimental/databricks_trace_otel.proto
  mlflow/genai/experimental/databricks_trace_otel_pb2.py
  tests/genai/experimental/test_databricks_trace_archival.py
  tests/genai/experimental/test_databricks_trace_exporter.py
Labels: rn/none, area/tracing

#17302 Add MLflow traces CLI command with comprehensive search and management capabilities
  mlflow/cli/__init__.py
  mlflow/cli/traces.py
  mlflow/utils/jsonpath_utils.py
  mlflow/utils/string_utils.py
  tests/cli/__init__.py
  tests/cli/test_traces.py
  tests/utils/test_jsonpath_utils.py
  tests/utils/test_string_utils.py
Labels: rn/feature, area/uiux, area/tracing

#17117 [6/7] Add evaluation dataset REST interface
  dev/generate_protos.py
  docs/api_reference/api_inventory.txt
  mlflow/entities/dataset_record.py
  mlflow/entities/dataset_record_source.py
  mlflow/entities/evaluation_dataset.py
  mlflow/genai/datasets/__init__.py
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Datasets.java
  mlflow/protos/datasets.proto
  mlflow/protos/datasets_pb2.py
  mlflow/protos/datasets_pb2.pyi
  mlflow/protos/evaluation_datasets.proto
  mlflow/protos/evaluation_datasets_pb2.py
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
  mlflow/protos/service_pb2.pyi
  mlflow/server/__init__.py
  mlflow/server/handlers.py
  mlflow/store/tracking/__init__.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/dbmodels/models.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  mlflow/utils/databricks_utils.py
  tests/entities/test_dataset_record.py
  tests/entities/test_dataset_record_source.py
  tests/genai/datasets/test_fluent.py
  tests/genai/evaluate/test_evaluation.py
  tests/genai/test_genai_import_without_agent_sdk.py
  tests/server/test_handlers.py
  tests/store/tracking/test_rest_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/test_client.py
  tests/tracking/test_rest_tracking.py
Labels: rn/feature, area/tracking, team-review

#17308 Remove unnecessary info logs for trace archival enablement
  mlflow/genai/experimental/databricks_trace_archival.py
Labels: rn/none

#17299 Remove Tool.run dependency
  mlflow/pydantic_ai/__init__.py
  tests/pydantic_ai/test_pydanticai_fluent_tracing.py
  tests/pydantic_ai/test_pydanticai_tracing.py
Labels: rn/none, team-review, area/tracing, v3.3.2

#17328 Judge builder stub SDK
  docs/api_reference/api_inventory.txt
  mlflow/genai/judges/__init__.py
  mlflow/genai/judges/base.py
  tests/genai/judges/test_judge_base.py
Labels: rn/feature, area/evaluation

#17305 Introduce mlflow autolog claude to trace claude code interactions
  .gitignore
  mlflow/claude_code/README.md
  mlflow/claude_code/__init__.py
  mlflow/claude_code/cli.py
  mlflow/claude_code/config.py
  mlflow/claude_code/hooks.py
  mlflow/claude_code/tracing.py
  mlflow/cli/__init__.py
  tests/claude_code/test_cli.py
  tests/claude_code/test_config.py
  tests/claude_code/test_tracing.py
Labels: rn/feature, area/tracing

#17261 Track create_webhook event
  docs/docs/community/usage-tracking.mdx
  mlflow/telemetry/events.py
  mlflow/tracking/_model_registry/client.py
  tests/telemetry/test_tracked_events.py
Labels: rn/none, team-review, v3.3.2

#17151 Strands Agent Tracing
  conftest.py
  dev/pyproject.py
  docs/api_reference/api_inventory.txt
  docs/api_reference/source/python_api/mlflow.strands.rst
  docs/docs/genai/tracing/integrations/listing/strands.mdx
  docs/src/components/TracingIntegrations/index.tsx
  docs/static/images/llms/strands/strands-tracing.png
  docs/static/images/logos/strands-logo.png
  examples/strands/tracing.py
  libs/tracing/pyproject.toml
  mlflow/__init__.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/semantic_kernel/autolog.py
  mlflow/strands/__init__.py
  mlflow/strands/autolog.py
  mlflow/tracing/utils/__init__.py
  mlflow/tracking/fluent.py
  requirements/extra-ml-requirements.txt
  tests/strands/conftest.py
  tests/strands/test_strands_tracing.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/feature, area/tracking, enable-dev-tests, rn/highlight

#17298 Update Scorers API doc
  mlflow/entities/scorer.py
  mlflow/genai/scorers/registry.py
Labels: area/docs, rn/documentation, team-review

#17360 Refactor ingest_api_sdk to zerobus_sdk
  mlflow/genai/experimental/databricks_trace_exporter.py
  mlflow/genai/experimental/databricks_trace_exporter_utils.py
  tests/genai/experimental/conftest.py
  tests/genai/experimental/test_databricks_trace_exporter.py
  tests/genai/experimental/test_databricks_trace_exporter_utils.py
  tests/tracing/test_provider.py
Labels: rn/none, area/tracing

#17072 Add REST store and API support for logging spans
  .github/workflows/tracing.yaml
  mlflow/entities/span.py
  mlflow/server/fastapi_app.py
  mlflow/server/otel_api.py
  mlflow/store/tracking/rest_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracing/utils/__init__.py
  mlflow/tracing/utils/otlp.py
  tests/entities/test_span.py
  tests/server/auth/test_auth.py
  tests/server/auth/test_client.py
  tests/spark/autologging/datasource/test_spark_datasource_autologging.py
  tests/tracing/test_otel_logging.py
  tests/tracking/integration_test_utils.py
  tests/tracking/test_model_registry.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, area/tracking

#17358 Track log params event
  docs/docs/community/usage-tracking.mdx
  mlflow/telemetry/events.py
  mlflow/tracking/_tracking_service/client.py
  tests/telemetry/test_tracked_events.py
Labels: rn/none, team-review, v3.3.2

#17379 Fix scorer status for MLflow tracking backend
  mlflow/genai/scorers/base.py
  tests/genai/scorers/test_scorer_CRUD.py
Labels: rn/bug-fix, area/tracking, team-review

#17359 Track log_metric event
  docs/docs/community/usage-tracking.mdx
  mlflow/telemetry/events.py
  mlflow/tracking/_tracking_service/client.py
  tests/telemetry/test_tracked_events.py
Labels: rn/none, team-review, v3.3.2

#17349 Add genai packages import for startTraceEvent
  .github/workflows/master.yml
  docs/docs/community/usage-tracking.mdx
  mlflow/telemetry/constant.py
  mlflow/telemetry/events.py
  tests/telemetry/test_tracked_events.py
Labels: rn/none, team-review, v3.3.2

#17376 Fix AG2 cross version tests
  mlflow/ml-package-versions.yml
Labels: area/build, team-review, v3.3.2

#17309 [1/3] Correlations backend - SQL Store and NPMI
  mlflow/store/analytics/__init__.py
  mlflow/store/analytics/trace_correlation.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracing/analysis.py
  tests/store/analytics/__init__.py
  tests/store/analytics/test_trace_correlation.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/feature, area/tracking

#17394 Add retry policy support to _invoke_litellm for improved reliability
  mlflow/genai/judges/utils.py
  tests/genai/judges/test_judge_utils.py
Labels: rn/bug-fix, area/tracing, v3.3.2

#17380 Update Git versioning docs to use `mlflow.genai.enable_git_model_versioning` API
  docs/docs/genai/version-tracking/track-application-versions-with-mlflow.mdx
  docs/static/images/git-versioning.png
Labels: area/docs, rn/documentation

#17398 Track mlflow experiment id
  docs/docs/community/usage-tracking.mdx
  mlflow/telemetry/events.py
  mlflow/telemetry/track.py
  tests/telemetry/test_client.py
  tests/telemetry/test_tracked_events.py
Labels: rn/none, team-review, v3.3.2

#17384 Fix RFunc Backend for mlflow models CLI
  mlflow/models/flavor_backend.py
  mlflow/rfunc/backend.py
Labels: rn/none, area/models, team-review, v3.3.2

#17391 Check version of MLflow server before log_spans calls to determine whether span logging is supported
  mlflow/store/tracking/rest_store.py
  mlflow/utils/rest_utils.py
  tests/store/tracking/test_rest_store.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, area/tracing

#17395 Add docs for package lock
  docs/docs/classic-ml/model/dependencies/index.mdx
Labels: area/docs, rn/documentation, team-review, v3.3.2

#17408 Add VS Code configuration for consistent development environment
  .vscode/extensions.json
  .vscode/settings.json
Labels: rn/none, area/build

#17390 Extend builtin scorers to be instances of Judge
  mlflow/genai/judges/builtin_judges.py
  mlflow/genai/scorers/builtin_scorers.py
  tests/genai/scorers/test_serialization.py
Labels: rn/none, area/evaluation

#17412 Add tool registry for judges
  mlflow/genai/judges/tools/__init__.py
  mlflow/genai/judges/tools/base.py
  mlflow/genai/judges/tools/constants.py
  mlflow/genai/judges/tools/get_trace_info.py
  mlflow/genai/judges/tools/registry.py
  tests/genai/judges/test_judge_tool_get_trace_info.py
  tests/genai/judges/test_judge_tool_registry.py
Labels: rn/none, area/evaluation

#17418 Add deprecation warning to set_retriever_schema
  mlflow/models/dependencies_schemas.py
Labels: rn/none, area/tracing, area/evaluation, v3.3.2

#17406 Add import for SpanType
  docs/docs/genai/tracing/quickstart/python-openai.mdx
Labels: area/docs, rn/none, v3.3.2

#17004 Improve WheeledModel._download_wheels safety
  mlflow/models/wheeled_model.py
  tests/models/test_wheeled_model.py
Labels: rn/feature, team-review

#17422 Add sleep to deflake test_litellm_tracing_async
  tests/litellm/test_litellm_autolog.py
Labels: rn/none, enable-dev-tests, area/tracing, v3.3.2

#17421 Decrease batch time interval
  mlflow/telemetry/constant.py
Labels: rn/none, v3.3.2

#17420 Add back import MLflow event
  docs/docs/community/usage-tracking.mdx
  mlflow/telemetry/client.py
  mlflow/telemetry/events.py
  tests/telemetry/test_client.py
Labels: rn/none, v3.3.2

#17121 Add error handling for s3 client errors
  mlflow/server/handlers.py
  mlflow/store/artifact/s3_artifact_repo.py
  tests/store/artifact/test_s3_artifact_repo.py
Labels: rn/none

#17076 Add automatic Git-based model versioning for GenAI applications
  docs/api_reference/api_inventory.txt
  docs/docs/genai/version-tracking/track-application-versions-with-mlflow.mdx
  docs/static/images/git-versioning.png
  mlflow/genai/__init__.py
  mlflow/genai/git_versioning/__init__.py
  mlflow/genai/git_versioning/git_info.py
  mlflow/utils/mlflow_tags.py
  tests/genai/test_git_versioning.py
Labels: rn/feature, team-review

#17441 Lint fix for changelog
  CHANGELOG.md
Labels: rn/none, team-review

#17411 Add Databricks backend support to MLflow server
  CLAUDE.md
  dev/run-dev-server.sh
  mlflow/server/handlers.py
  tests/server/test_handlers.py
Labels: rn/feature, area/model-registry, area/tracking

#17417 Add 'mlflow runs create' CLI command for programmatic run creation
  CLAUDE.md
  mlflow/runs.py
  tests/test_runs.py
Labels: rn/feature, area/tracking

#17396 [10/10] Eval dataset unity
  docs/api_reference/api_inventory.txt
  docs/src/api_modules.json
  mlflow/genai/datasets/__init__.py
  mlflow/genai/datasets/evaluation_dataset.py
  mlflow/genai/evaluation/base.py
  tests/genai/datasets/test_fluent.py
Labels: rn/feature, team-review, area/evaluation

#17415 Add AlignmentOptimizer abstract class for Judge alignment
  docs/api_reference/api_inventory.txt
  mlflow/genai/judges/__init__.py
  mlflow/genai/judges/base.py
  tests/genai/judges/test_alignment_optimizer.py
Labels: rn/feature, area/evaluation

#17444 [CLI] Add 'mlflow runs link-traces' command
  mlflow/runs.py
  tests/test_runs.py
Labels: rn/feature, area/tracking, area/tracing

#17452 Cherry-pick CVE fix to 2.22
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, team-review

#17436 Fix Issue 17348: Support basic auth in TypeScript SDK
  docs/docs/genai/tracing/quickstart/typescript-openai.mdx
  libs/typescript/core/src/clients/client.ts
  libs/typescript/core/src/clients/utils.ts
  libs/typescript/core/src/core/config.ts
  libs/typescript/core/src/core/provider.ts
Labels: bug, rn/bug-fix, area/tracking, v3.3.3

#17455 Improve Python style guide section titles and descriptions
  .github/copilot-instructions.md
  CLAUDE.md
  dev/guides/python.md
Labels: area/docs, rn/none, team-review

#17427 Add fixture for local test
  mlflow/telemetry/utils.py
  tests/telemetry/conftest.py
Labels: rn/none, team-review

#17428 Add logs for telemetry
  mlflow/environment_variables.py
  mlflow/telemetry/client.py
  mlflow/telemetry/track.py
  mlflow/telemetry/utils.py
Labels: rn/none, team-review

#17459 Fix compareExperimentsSearch in route-defs (#17434)
  mlflow/server/js/src/experiment-tracking/route-defs.ts
Labels: rn/bug-fix, area/uiux

#17445 Judges - extend invoke_litellm to support tool calling
  mlflow/genai/judges/tools/registry.py
  mlflow/genai/judges/utils.py
  tests/genai/judges/test_custom_prompt_judge.py
  tests/genai/judges/test_judge_utils.py
Labels: rn/none, area/evaluation

#17435 Add docs for MLflow MCP server
  docs/docs/genai/mcp/index.mdx
  docs/sidebarsGenAI.ts
Labels: area/docs, rn/none

#17468 Add pytest monkeypatch guidance to Python style guide
  dev/guides/python.md
Labels: rn/none, team-review

#17449 Create/Add MLflow Client Version Header for Requests
  mlflow/tracking/request_header/default_request_header_provider.py
  mlflow/utils/rest_utils.py
  tests/utils/test_rest_utils.py
Labels: rn/none, area/tracking, v3.3.3

#17486 Remove experimental message about MPU/MPD in docs
  docs/docs/classic-ml/tracking/artifact-stores/index.mdx
Labels: area/docs, rn/documentation, team-review, v2.22.3

#17474 Add a warning message for trace destination setting in model serving environment
  mlflow/tracing/provider.py
Labels: rn/none, area/tracing

#17369 Export MLflow spans OTel /v1/traces API, enabling per-span logging & search by span
  mlflow/entities/span.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracing/client.py
  mlflow/tracing/export/mlflow_v3.py
  mlflow/tracing/processor/base_mlflow.py
  mlflow/tracing/trace_manager.py
  mlflow/tracing/utils/__init__.py
  tests/tracing/processor/test_mlflow_v3_processor.py
  tests/tracing/test_fluent.py
Labels: rn/none, area/tracing

#17496 Implement Judge field methods and refactor prompts
  docs/api_reference/api_inventory.txt
  mlflow/genai/judges/base.py
  mlflow/genai/judges/instructions_judge/__init__.py
  mlflow/genai/judges/prompts/context_sufficiency.py
  mlflow/genai/judges/prompts/correctness.py
  mlflow/genai/judges/prompts/groundedness.py
  mlflow/genai/judges/prompts/guidelines.py
  mlflow/genai/judges/prompts/relevance_to_query.py
  mlflow/genai/judges/utils.py
  mlflow/genai/scorers/builtin_scorers.py
  tests/genai/judges/test_alignment_optimizer.py
  tests/genai/judges/test_judge_base.py
  tests/genai/judges/test_make_judge.py
  tests/genai/scorers/test_builtin_scorers.py
  tests/genai/scorers/test_serialization.py
Labels: rn/none, area/evaluation
