Repository mlflow/mlflow, pull requests merged in 2025-03, with the labels that each got.

#14743 Fix DSPy tracing in serving
  mlflow/dspy/callback.py
  mlflow/dspy/load.py
  tests/dspy/test_dspy_autolog.py
Labels: rn/bug-fix, area/tracking

#14796 Revert "Deprecate `MLserver` integration"
  docs/docs/deployment/deploy-model-locally/index.mdx
  mlflow/models/cli.py
Labels: rn/none

#14783 Add content to tracing/api page
  docs/docs/tracing/api/index.mdx
Labels: rn/none, v2.21.0

#14779 Support installing `mlflow-skinny` from a Git URL
  .github/workflows/build-wheel.yml
  README_SKINNY.md
  dev/build.py
  dev/install-common-deps.sh
  dev/pyproject.py
  skinny/LICENSE.txt
  skinny/MANIFEST.in
  skinny/README.md
  skinny/mlflow
  skinny/pyproject.toml
  tests/dev/test_update_mlflow_versions.py
Labels: rn/none

#14756 Fix gpu system metrics
  mlflow/system_metrics/metrics/gpu_monitor.py
Labels: rn/none, area/tracking, v2.20.4, v2.21.0

#14767 Simplify get_model_info
  mlflow/models/model.py
  tests/models/test_model.py
Labels: rn/none

#14778 Fix spark models logging issue
  mlflow/spark/__init__.py
  mlflow/store/artifact/models_artifact_repo.py
Labels: rn/none

#14781 Fix langchain test
  mlflow/models/model.py
Labels: rn/none

#14773 Easy docusaurus fixes part 2
  docs/docs/community-model-flavors/index.mdx
  docs/docs/docker/index.mdx
  docs/docs/llms/deployments/guides/step1-create-deployments/index.mdx
  docs/docs/llms/deployments/guides/step2-query-deployments/index.mdx
  docs/docs/llms/deployments/index.mdx
  docs/docs/model-registry/index.mdx
  docs/docs/quickstart_drilldown/index.mdx
  docs/docs/tracing/integrations/dspy.mdx
  docs/docs/tracing/integrations/openai.mdx
  docs/docs/tracing/tracing-schema.mdx
  docs/docs/tutorials-and-examples/index.mdx
  docs/docusaurus.config.ts
  docs/docusaurusConfigUtils.ts
  docs/postProcessSidebar.ts
  docs/sidebars.ts
Labels: rn/none, v2.21.0

#14799 Fix single deletion case for s3 repository
  mlflow/store/artifact/optimized_s3_artifact_repo.py
  mlflow/store/artifact/s3_artifact_repo.py
  tests/store/artifact/test_s3_artifact_repo.py
  tests/test_cli.py
Labels: rn/none, v2.20.4, v2.21.0

#14800 Remove gunicorn option from model serving Dockerfile
  mlflow/models/container/__init__.py
  mlflow/models/docker_utils.py
  tests/helper_functions.py
  tests/models/test_cli.py
  tests/resources/dockerfile/Dockerfile_conda
  tests/resources/dockerfile/Dockerfile_custom_scipy
  tests/resources/dockerfile/Dockerfile_default
  tests/resources/dockerfile/Dockerfile_enable_mlserver
  tests/resources/dockerfile/Dockerfile_install_mlflow
  tests/resources/dockerfile/Dockerfile_install_mlflow_virtualenv
  tests/resources/dockerfile/Dockerfile_java_flavor
  tests/resources/dockerfile/Dockerfile_no_model_uri
  tests/resources/dockerfile/Dockerfile_sagemaker_conda
  tests/resources/dockerfile/Dockerfile_sagemaker_virtualenv
  tests/resources/dockerfile/Dockerfile_with_mlflow_home
Labels: rn/none, v2.21.0

#14792 Support async API tracing for OpenAI
  docs/docs/tracing/integrations/openai.mdx
  mlflow/ml-package-versions.yml
  mlflow/openai/__init__.py
  mlflow/openai/_openai_autolog.py
  requirements/test-requirements.txt
  tests/openai/test_openai_agent_autolog.py
  tests/openai/test_openai_autolog.py
Labels: rn/feature, area/tracking, v2.21.0

#14765 Add docusaurus build script that can be run from release pipeline
  .circleci/config.yml
  dev/preview_docs.py
  docs/README.md
  docs/changed_pages.py
  docs/package.json
  docs/scripts/build-all.py
Labels: rn/none, v2.21.0

#14814 Avoid `dspy` 2.6.9
  requirements/extra-ml-requirements.txt
Labels: rn/none

#14815 Fix dark mode for markdown editor header
  mlflow/server/js/src/common/components/EditableNote.css
Labels: rn/none, v2.20.4

#14802 Fix symlink handling in `dev/pyproject.py`
  dev/pyproject.py
Labels: rn/none

#14804 Make `preview-docs` fail gracefully
  dev/preview_docs.py
Labels: rn/none

#14818 Implement `ArtifactRepository.__repr__` for better debuggability
  mlflow/store/artifact/artifact_repo.py
Labels: rn/none

#14819 Make `get_trace` throw if request ID is online trace ID
  mlflow/tracking/client.py
  tests/tracking/test_client.py
Labels: rn/none

#14821 Add optional env var to specify maven args during javadocs build process
  docs/api_reference/build-javadoc.sh
Labels: rn/none

#14816 Fix `Model.load` with runs uri
  mlflow/store/artifact/runs_artifact_repo.py
  tests/fastai/test_fastai_autolog.py
  tests/models/test_model.py
Labels: rn/none

#14826 Add guide for tracing deepseek
  docs/docs/tracing/index.mdx
  docs/docs/tracing/integrations/deepseek.mdx
  docs/docs/tracing/integrations/index.mdx
  docs/static/images/llms/deepseek/deepseek-tracing-agent.png
  docs/static/images/llms/deepseek/deepseek-tracing.png
  docs/static/images/logos/deepseek-logo.png
Labels: area/docs, rn/documentation

#14795 Merge prompt registry feature branch
  mlflow/__init__.py
  mlflow/entities/__init__.py
  mlflow/entities/model_registry/__init__.py
  mlflow/entities/model_registry/prompt.py
  mlflow/entities/model_registry/registered_model.py
  mlflow/models/model.py
  mlflow/prompt/promptlab_model.py
  mlflow/prompt/registry_utils.py
  mlflow/pyfunc/__init__.py
  mlflow/server/handlers.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/tracking/_model_registry/client.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
  mlflow/utils/docstring_utils.py
  mlflow/utils/promptlab_utils.py
  mlflow/utils/search_utils.py
  tests/entities/test_prompt.py
  tests/models/test_model.py
  tests/prompt/test_promptlab_model.py
  tests/server/test_handlers.py
  tests/store/model_registry/test_file_store.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/tracking/_model_registry/test_model_registry_client.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
  tests/tracking/test_client.py
Labels: rn/none, area/model-registry, v2.21.0

#14798 Add warning for runs uri when loading model
  mlflow/store/artifact/runs_artifact_repo.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/none

#14837 Apply #14833 to release branch
  dev/update_mlflow_versions.py
Labels: rn/none, area/tracking

#14830 Fix warning for pyfunc decorator inside mlflow module
  mlflow/pyfunc/model.py
Labels: rn/none, v2.20.4

#14782 Fix `mlflow.doctor` to fall back to `mlflow-skinny` when `mlflow` is not found
  dev/run-python-skinny-tests.sh
  mlflow/utils/doctor.py
Labels: rn/bug-fix

#14813 Update installation instructions for installing MLflow from a pull request
  .github/workflows/advice.js
Labels: rn/none

#14788 Fix TS types
  mlflow/server/js/src/common/components/DesignSystemContainer.tsx
  mlflow/server/js/src/common/components/ErrorView.tsx
  mlflow/server/js/src/common/components/IconButton.tsx
  mlflow/server/js/src/common/components/TrimmedText.tsx
  mlflow/server/js/src/common/utils/ErrorWrapper.test.ts
  mlflow/server/js/src/experiment-tracking/components/MetricsPlotControls.enzyme.test.tsx
  mlflow/server/js/src/experiment-tracking/components/PermissionDeniedView.tsx
  mlflow/server/js/src/experiment-tracking/components/RunNotFoundView.tsx
  mlflow/server/js/src/experiment-tracking/utils/NoteUtils.ts
  mlflow/server/js/src/experiment-tracking/utils/test-utils/Fixtures.ts
  mlflow/server/js/src/experiment-tracking/utils/test-utils/ReduxStoreFixtures.ts
  mlflow/server/js/src/index.tsx
  mlflow/server/js/src/model-registry/components/CreateModelButton.test.tsx
  mlflow/server/js/src/model-registry/components/CreateModelButton.tsx
  mlflow/server/js/src/model-registry/components/ModelStageTransitionDropdown.tsx
  mlflow/server/js/src/model-registry/utils/SearchUtils.test.ts
  mlflow/server/js/src/shared/building_blocks/CopyBox.tsx
  mlflow/server/js/src/shared/building_blocks/Spacer.tsx
Labels: rn/none

#14824 Improve `_enforce_array` efficiency
  mlflow/models/utils.py
  tests/models/test_utils.py
Labels: rn/none, v2.20.4

#14849 Fix changelog update script
  dev/update_changelog.py
Labels: rn/none

#14853 Request review in sync job
  .github/workflows/sync.py
Labels: rn/none

#14850 Fix test_mlflow_callback_exception with dspy dev
  tests/dspy/test_dspy_autolog.py
Labels: rn/none, v2.20.4

#14857 Pin shap
  .github/workflows/master.yml
Labels: rn/none

#14852 fix: clear button fix in run search text box
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/RunsSearchAutoComplete.tsx
Labels: rn/none, v2.20.4

#14866 Fix doc links
  docs/sidebars.ts
Labels: rn/none, v2.20.4

#14797 Fix: `pyfunc.load_model()` followed by `predict()` does not log trace associated with the model
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/context.py
  mlflow/tracing/processor/mlflow.py
  mlflow/tracing/utils/__init__.py
  tests/pyfunc/test_logged_models.py
Labels: rn/none

#14723 Supports ADLS artifact repo
  mlflow/store/artifact/artifact_repository_registry.py
  mlflow/store/artifact/azure_data_lake_artifact_repo.py
  tests/store/artifact/test_azure_data_lake_artifact_repo.py
Labels: rn/feature, area/artifacts

#14870 Document how to exclude symlinks from searches
  CONTRIBUTING.md
Labels: rn/none

#14861 Import lazily-loaded modules in `TYPE_CHECKING` block for code completion to work in IDEs
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  mlflow/__init__.py
Labels: rn/none

#14834 Support alias for prompt
  mlflow/__init__.py
  mlflow/entities/model_registry/prompt.py
  mlflow/prompt/registry_utils.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
  tests/entities/test_prompt.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
  tests/tracking/test_client.py
Labels: rn/none, area/model-registry, v2.21.0

#14860 Remove pyspark if databricks-connect exists in pip requirements
  mlflow/utils/environment.py
  tests/utils/test_environment.py
Labels: rn/none, v2.20.4, v2.21.0

#14867 Cherry pick doc fix
  docs/sidebars.ts
Labels: rn/none

#14854 OpenAI token refresh fix
  mlflow/utils/openai_utils.py
Labels: rn/none, v2.20.4

#14878 Fix version selecter in docusaurus docs
  docs/api_reference/theme/mlflow/static/js/custom.js
Labels: rn/none, v2.21.0

#14880 Fix langgraph dev tests
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests

#14879 Cherry-pick: Fix version selecter in docusaurus docs (#14878)
  docs/api_reference/theme/mlflow/static/js/custom.js
Labels: rn/none

#14863 fix: avoid double scroll bars
  mlflow/server/js/src/common/components/PageContainer.tsx
Labels: rn/none, v2.20.4

#14793 Support async Anthropic tracing
  docs/docs/tracing/integrations/anthropic.mdx
  docs/static/images/llms/anthropic/anthropic-tool-calling.png
  mlflow/anthropic/__init__.py
  mlflow/anthropic/autolog.py
  mlflow/tracing/utils/__init__.py
  tests/anthropic/test_anthropic_autolog.py
  tests/tracing/utils/test_utils.py
Labels: rn/feature, area/tracking, v2.21.0

#14876 Make autogen logger exception safe
  mlflow/autogen/autogen_logger.py
  tests/autogen/test_autogen_autolog.py
Labels: rn/none, area/tracking, v2.21.0

#14839 Support mysql ssl connections with client certs
  docs/docs/tracking/backend-stores/index.mdx
  mlflow/environment_variables.py
  mlflow/store/db/utils.py
  tests/store/db/test_utils.py
Labels: rn/feature, area/tracking, area/sqlalchemy, v2.20.4

#14881 Add guide about using MLflow tracing across thread
  docs/docs/tracing/api/manual-instrumentation.mdx
  docs/docs/tracing/faq.mdx
  docs/static/images/llms/tracing/tracing-multi-thread.png
Labels: rn/documentation, area/tracking, v2.21.0

#14884 Fix false alert from AMD GPU monitor
  docs/docs/system-metrics/index.mdx
  mlflow/system_metrics/metrics/rocm_monitor.py
  mlflow/system_metrics/system_metrics_monitor.py
Labels: rn/bug-fix, area/tracking, v2.21.0

#14883 fix: TS types
  mlflow/server/js/src/common/components/IconButton.tsx
  mlflow/server/js/src/common/components/SimplePagination.stories.tsx
  mlflow/server/js/src/common/components/SimplePagination.test.tsx
  mlflow/server/js/src/common/components/SimplePagination.tsx
  mlflow/server/js/src/common/components/Spinner.tsx
  mlflow/server/js/src/common/forms/validations.ts
  mlflow/server/js/src/common/utils/FileUtils.ts
  mlflow/server/js/src/common/utils/StringUtils.ts
  mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx
  mlflow/server/js/src/experiment-tracking/components/RunLinksPopover.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/ExperimentViewDescriptionNotes.tsx
  mlflow/server/js/src/experiment-tracking/components/modals/GetLinkModal.tsx
  mlflow/server/js/src/experiment-tracking/types.ts
  mlflow/server/js/src/model-registry/components/ModelListPage.tsx
  mlflow/server/js/src/model-registry/components/ModelVersionTable.tsx
  mlflow/server/js/src/model-registry/constants.tsx
  mlflow/server/js/src/model-registry/utils.tsx
  mlflow/server/js/src/model-registry/utils/SearchUtils.ts
Labels: rn/none

#14891 fix: text color fix in headings
  mlflow/server/js/src/reset.css
Labels: rn/none, v2.21.0

#14873 fix: remove `log_trace` at top level module
  mlflow/__init__.py
Labels: rn/bug-fix, area/tracking

#14894 Sync
  docs/api_reference/theme/mlflow/static/js/custom.js
  docs/docs/system-metrics/index.mdx
  docs/docs/tracing/api/manual-instrumentation.mdx
  docs/docs/tracing/faq.mdx
  docs/docs/tracing/integrations/anthropic.mdx
  docs/docs/tracking/backend-stores/index.mdx
  docs/static/images/llms/anthropic/anthropic-tool-calling.png
  docs/static/images/llms/tracing/tracing-multi-thread.png
  mlflow/R/mlflow/DESCRIPTION
  mlflow/anthropic/__init__.py
  mlflow/anthropic/autolog.py
  mlflow/autogen/autogen_logger.py
  mlflow/environment_variables.py
  mlflow/java/client/pom.xml
  mlflow/java/pom.xml
  mlflow/java/scoring/pom.xml
  mlflow/java/scoring/src/main/java/org/mlflow/sagemaker/ScoringServer.java
  mlflow/java/scoring/src/test/java/org/mlflow/ScoringServerTest.java
  mlflow/java/spark/pom.xml
  mlflow/ml-package-versions.yml
  mlflow/server/js/src/common/components/IconButton.tsx
  mlflow/server/js/src/common/components/PageContainer.tsx
  mlflow/server/js/src/common/components/SimplePagination.stories.tsx
  mlflow/server/js/src/common/components/SimplePagination.test.tsx
  mlflow/server/js/src/common/components/SimplePagination.tsx
  mlflow/server/js/src/common/components/Spinner.tsx
  mlflow/server/js/src/common/constants.tsx
  mlflow/server/js/src/common/forms/validations.ts
  mlflow/server/js/src/common/utils/FileUtils.ts
  mlflow/server/js/src/common/utils/StringUtils.ts
  mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx
  mlflow/server/js/src/experiment-tracking/components/RunLinksPopover.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/ExperimentViewDescriptionNotes.tsx
  mlflow/server/js/src/experiment-tracking/components/modals/GetLinkModal.tsx
  mlflow/server/js/src/experiment-tracking/types.ts
  mlflow/server/js/src/model-registry/components/ModelListPage.tsx
  mlflow/server/js/src/model-registry/components/ModelVersionTable.tsx
  mlflow/server/js/src/model-registry/constants.tsx
  mlflow/server/js/src/model-registry/utils.tsx
  mlflow/server/js/src/model-registry/utils/SearchUtils.ts
  mlflow/server/js/src/reset.css
  mlflow/store/db/utils.py
  mlflow/system_metrics/metrics/rocm_monitor.py
  mlflow/system_metrics/system_metrics_monitor.py
  mlflow/tracing/utils/__init__.py
  mlflow/utils/openai_utils.py
  mlflow/version.py
  pyproject.release.toml
  pyproject.toml
  skinny/pyproject.toml
  tests/anthropic/test_anthropic_autolog.py
  tests/autogen/test_autogen_autolog.py
  tests/store/db/test_utils.py
  tests/tracing/utils/test_utils.py
Labels: rn/none

#14895 Add necessary redirects in docusaurus
  .gitignore
  docs/docusaurus.config.ts
  docs/src/api_modules.json
Labels: rn/none, v2.21.0

#14897 Cherry-pick: Add necessary redirects in docusaurus (#14895)
  .gitignore
  docs/docusaurus.config.ts
  docs/src/api_modules.json
Labels: rn/none

#14875 Fix transformers `persist_pretrained_model`
  mlflow/store/artifact/models_artifact_repo.py
Labels: rn/none

#14893 Get rid of path parameter from `SqlAlchemyStore.log_metrics`
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#14896 Fix a bug in tag creation where tag values containing `": "` get truncated
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/ExperimentViewRunsControlsActionsSelectTags.tsx
Labels: rn/bug-fix

#14898 Fix changed pages link in doc preview
  dev/preview_docs.py
Labels: rn/none

#14913 Fix Location.from_node to report correct lint error locations
  dev/clint/src/clint/linter.py
Labels: rn/none, area/build

#14749 Log logged model metrics in `SqlAlchemyStore`
  mlflow/entities/metric.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/fluent.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#14906 Fix ollama doc
  docs/docs/tracing/integrations/ollama.mdx
Labels: rn/none, v2.21.0

#14904 Replace `__class__` with `__name__` in schema error message
  mlflow/types/schema.py
Labels: rn/none

#14859 fix: code editor theme in experiment trace tab
  mlflow/server/js/src/experiment-tracking/components/traces/quickstart/TraceTableAutogenQuickstartContent.tsx
  mlflow/server/js/src/experiment-tracking/components/traces/quickstart/TraceTableCustomQuickstartContent.tsx
  mlflow/server/js/src/experiment-tracking/components/traces/quickstart/TraceTableLangchainQuickstartContent.tsx
  mlflow/server/js/src/experiment-tracking/components/traces/quickstart/TraceTableLlamaIndexQuickstartContent.tsx
  mlflow/server/js/src/experiment-tracking/components/traces/quickstart/TraceTableOpenAIQuickstartContent.tsx
Labels: rn/none, v2.20.4, v2.21.0

#14910 fix: clear input values in `add tag` model form after adding tags
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/ExperimentViewRunsControlsActionsAddNewTagModal.tsx
Labels: rn/none, v2.21.0

#14786 clean up libraries in package.json
  mlflow/server/js/package.json
  mlflow/server/js/yarn.lock
Labels: rn/none

#14927 chore: remove office hours announcements
  README.md
  skinny/README.md
Labels: rn/none

#14929 Fix error message for prompt registry
  mlflow/entities/model_registry/prompt.py
  mlflow/prompt/registry_utils.py
  mlflow/tracking/client.py
  mlflow/utils/validation.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
  tests/tracking/test_client.py
Labels: rn/none, area/model-registry, v2.21.0

#14909 Prompt management UI (combined changeset)
  mlflow/server/js/package.json
  mlflow/server/js/src/app.tsx
  mlflow/server/js/src/common/components/MlflowHeader.tsx
  mlflow/server/js/src/common/components/ScrollablePageWrapper.tsx
  mlflow/server/js/src/common/utils/reactQueryHooks.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/PromptsDetailsPage.test.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/PromptsDetailsPage.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/PromptsPage.test.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/PromptsPage.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/api.test.ts
  mlflow/server/js/src/experiment-tracking/pages/prompts/api.ts
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptContentCompare.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptContentPreview.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptDetailsMetadata.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptDetailsSourceRunsBox.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptDetailsTagsBox.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptPageErrorHandler.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptVersionMetadata.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptVersionsDiffSelectorButton.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptVersionsTable.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptVersionsTableAliasesCell.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptsListFilters.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptsListTable.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptsListTableNameCell.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptsListTableTagsCell.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptsListTableVersionCell.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/diff.ts
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/useCreatePromptModal.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/useCreateRegisteredPromptMutation.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/useDeletePromptModal.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/useDeletePromptVersionModal.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/usePromptDetailsPageViewState.test.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/usePromptDetailsPageViewState.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/usePromptDetailsQuery.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/usePromptSourceRunsInfo.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/usePromptsListQuery.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/useUpdateRegisteredPromptTags.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/test-utils.ts
  mlflow/server/js/src/experiment-tracking/pages/prompts/types.ts
  mlflow/server/js/src/experiment-tracking/pages/prompts/utils.ts
  mlflow/server/js/src/experiment-tracking/route-defs.ts
  mlflow/server/js/src/experiment-tracking/routes.ts
  mlflow/server/js/src/experiment-tracking/types.ts
  mlflow/server/js/src/lang/default/en.json
  mlflow/server/js/src/model-registry/components/aliases/ModelVersionTableAliasesCell.tsx
  mlflow/server/js/src/model-registry/components/aliases/ModelVersionViewAliasEditor.intg.test.tsx
  mlflow/server/js/src/model-registry/components/model-list/ModelListFilters.tsx
  mlflow/server/js/src/shared/web-shared/errors/ErrorLogType.ts
  mlflow/server/js/src/shared/web-shared/errors/ErrorName.ts
  mlflow/server/js/src/shared/web-shared/errors/PredefinedErrors.test.tsx
  mlflow/server/js/src/shared/web-shared/errors/PredefinedErrors.tsx
  mlflow/server/js/src/shared/web-shared/errors/index.ts
  mlflow/server/js/tsconfig.tsbuildinfo
  mlflow/server/js/yarn.lock
Labels: rn/none, area/uiux

#14907 Fix: `ExperimentViewRunsControlsActionsSelectTags` doesn't set loading state to `false` when `set-tag` request fails.
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/ExperimentViewRunsControlsActionsSelectTags.tsx
Labels: rn/bug-fix

#14935 Rename "description" field in the Prompt object into "commit message"
  mlflow/entities/model_registry/prompt.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
  tests/entities/test_prompt.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
  tests/tracking/test_client.py
Labels: rn/none, area/tracking

#14924 fix: style adjustment in description note of experiment view
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/ExperimentViewDescriptionNotes.tsx
Labels: rn/none, v2.21.0

#14925 Implement pagination for `SqlAlchemyStore.search_logged_models`
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/utils/search_utils.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#14932 Fix for prompts source IDs retrieval
  mlflow/server/js/.gitignore
  mlflow/server/js/src/experiment-tracking/pages/prompts/PromptsDetailsPage.test.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/PromptsDetailsPage.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptDetailsMetadata.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptDetailsSourceRunsBox.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptVersionMetadata.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptVersionRuns.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/usePromptRunsInfo.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/test-utils.ts
  mlflow/server/js/src/experiment-tracking/pages/prompts/utils.ts
  mlflow/server/js/src/lang/default/en.json
  mlflow/server/js/tsconfig.tsbuildinfo
Labels: rn/none, area/uiux, v2.21.0

#14940 Fix code example for Prompt loading
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptContentPreview.tsx
Labels: rn/none, area/model-registry

#14941 Small fixes: search debounce, diff colors and alias modal captions
  mlflow/server/js/src/experiment-tracking/pages/prompts/PromptsDetailsPage.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/PromptsPage.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptContentCompare.tsx
  mlflow/server/js/src/lang/default/en.json
  mlflow/server/js/src/model-registry/hooks/useEditRegisteredModelAliasesModal.tsx
Labels: rn/none, area/uiux, v2.21.0

#14942 Prompt registry backend fixes
  mlflow/prompt/registry_utils.py
  mlflow/store/artifact/utils/models.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/tracking/client.py
  tests/store/artifact/test_databricks_models_artifact_repo.py
  tests/store/artifact/test_models_artifact_repo.py
  tests/store/artifact/utils/test_model_utils.py
  tests/store/model_registry/test_rest_store.py
  tests/tracking/test_client.py
Labels: rn/none, area/model-registry, v2.21.0

#14949 Create mlflow run for DSPy compile
  mlflow/dspy/autolog.py
  mlflow/dspy/callback.py
  mlflow/dspy/util.py
  tests/conftest.py
  tests/dspy/conftest.py
  tests/dspy/test_dspy_autolog.py
  tests/dspy/test_dspy_util.py
Labels: rn/feature, area/tracking

#14956 Add helpful error message for permission issue in predict API
  mlflow/models/python_api.py
Labels: rn/none

#14943 fix: theme color adjustment in code snippet in `CreateNotebookRunModal`
  mlflow/server/js/src/experiment-tracking/components/evaluation-artifacts-compare/CreateNotebookRunModal.tsx
Labels: rn/none, v2.21.0

#14958 Remove prompt metadata table on the page top
  mlflow/server/js/src/experiment-tracking/pages/prompts/PromptsDetailsPage.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptDetailsMetadata.tsx
  mlflow/server/js/src/lang/default/en.json
Labels: rn/none, area/tracking

#14957 Fix bugs inPrompt registry name validation
  mlflow/entities/model_registry/prompt.py
  mlflow/prompt/constants.py
  mlflow/prompt/registry_utils.py
  mlflow/server/js/src/experiment-tracking/pages/prompts/PromptsPage.test.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/useCreatePromptModal.tsx
  mlflow/server/js/src/lang/default/en.json
  mlflow/store/model_registry/file_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
  mlflow/tracking/client.py
  tests/store/model_registry/test_file_store.py
  tests/store/model_registry/test_sqlalchemy_store.py
  tests/tracking/test_client.py
Labels: rn/none, area/model-registry, v2.21.0

#14948 Support passing Prompt object to `log_model` and add the argument to more flavors
  docs/api_reference/source/conf.py
  mlflow/dspy/save.py
  mlflow/entities/model_registry/prompt.py
  mlflow/langchain/__init__.py
  mlflow/llama_index/__init__.py
  mlflow/models/model.py
  mlflow/openai/__init__.py
  mlflow/promptflow/__init__.py
  mlflow/pyfunc/__init__.py
  mlflow/sentence_transformers/__init__.py
  mlflow/tracking/client.py
  mlflow/transformers/__init__.py
  tests/entities/test_prompt.py
  tests/models/test_model.py
  tests/tracking/test_client.py
Labels: rn/none, area/model-registry, v2.21.0

#14944 Support auto-association of prompt with active run
  mlflow/entities/model_registry/prompt.py
  mlflow/tracking/_model_registry/fluent.py
  tests/entities/test_prompt.py
  tests/langchain/sample_code/chain_with_mlflow_prompt.py
  tests/langchain/test_langchain_model_export.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
Labels: rn/none, area/tracking, v2.21.0

#14969 Trace server experiment
  mlflow/tracing/destination.py
  tests/tracing/test_destination.py
Labels: rn/none, area/tracking, v2.21.0

#14964 Render version metadata
  mlflow/entities/model_registry/prompt.py
  mlflow/server/js/src/experiment-tracking/pages/prompts/PromptsDetailsPage.test.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptVersionMetadata.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptVersionTags.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/useCreatePromptModal.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/useCreateRegisteredPromptMutation.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/test-utils.ts
  mlflow/server/js/src/lang/default/en.json
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
  tests/tracking/test_client.py
Labels: rn/none, area/tracking, v2.21.0

#14980 Fix invalid type issue for ModelRegistry RestStore
  mlflow/store/model_registry/rest_store.py
Labels: rn/bug-fix, area/model-registry, v2.21.0

#14978 Fix langchain test
  tests/langchain/test_langchain_databricks_dependency_extraction.py
Labels: rn/none

#14984 Add prompt version tag editor to UI
  mlflow/server/js/src/common/hooks/useEditKeyValueTagsModal.tsx
  mlflow/server/js/src/common/utils/TagUtils.ts
  mlflow/server/js/src/experiment-tracking/pages/prompts/PromptsDetailsPage.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/api.ts
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptContentPreview.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptVersionMetadata.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptVersionTags.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/useUpdatePromptVersionMetadataModal.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/useUpdateRegisteredPromptTags.tsx
  mlflow/server/js/src/lang/default/en.json
Labels: rn/none, v2.21.0

#14892 Update Assessment to allow Feedback/Expectation to also have an Error
  mlflow/entities/assessment.py
  mlflow/tracing/assessment.py
  mlflow/utils/proto_json_utils.py
  tests/entities/test_assessment.py
  tests/tracing/test_assessment.py
Labels: rn/none, v2.21.0

#14755 ChatAgent Updates
  mlflow/langchain/chat_agent_langgraph.py
  mlflow/langchain/output_parsers.py
  mlflow/types/agent.py
  tests/langchain/test_langchain_output_parsers.py
  tests/langgraph/sample_code/langgraph_chat_agent.py
  tests/langgraph/sample_code/langgraph_chat_agent_custom_inputs.py
  tests/langgraph/test_langgraph_autolog.py
  tests/pyfunc/test_chat_agent.py
  tests/pyfunc/test_chat_agent_validation.py
Labels: rn/none, area/models, v2.21.0

#14985 Fix spark cross version test failures
  tests/spark/test_spark_model_export.py
Labels: rn/none, v2.21.0

#14979 Fix duplicated run ID logging in a prompt
  mlflow/tracking/client.py
  tests/tracking/test_client.py
Labels: rn/none, area/model-registry, v2.21.0

#14986 Handle GeneratorExit in `trace` wrapper
  mlflow/tracing/fluent.py
Labels: rn/none, v2.21.0

#14991 Sync master
  docs/api_reference/source/conf.py
  mlflow/dspy/save.py
  mlflow/entities/assessment.py
  mlflow/entities/model_registry/prompt.py
  mlflow/langchain/__init__.py
  mlflow/langchain/chat_agent_langgraph.py
  mlflow/langchain/output_parsers.py
  mlflow/llama_index/__init__.py
  mlflow/models/model.py
  mlflow/openai/__init__.py
  mlflow/promptflow/__init__.py
  mlflow/pyfunc/__init__.py
  mlflow/sentence_transformers/__init__.py
  mlflow/server/js/src/common/hooks/useEditKeyValueTagsModal.tsx
  mlflow/server/js/src/common/utils/TagUtils.ts
  mlflow/server/js/src/experiment-tracking/components/run-page/RunViewOverview.intg.test.tsx
  mlflow/server/js/src/experiment-tracking/components/run-page/RunViewOverview.tsx
  mlflow/server/js/src/experiment-tracking/components/run-page/overview/RunViewRegisteredPromptsBox.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/PromptsDetailsPage.test.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/PromptsDetailsPage.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/api.ts
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptContentPreview.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptVersionMetadata.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptVersionTags.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/useCreatePromptModal.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/useCreateRegisteredPromptMutation.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/usePromptVersionsForRunQuery.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/useUpdatePromptVersionMetadataModal.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/hooks/useUpdateRegisteredPromptTags.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/test-utils.ts
  mlflow/server/js/src/experiment-tracking/pages/prompts/types.ts
  mlflow/server/js/src/lang/default/en.json
  mlflow/store/model_registry/rest_store.py
  mlflow/tracing/assessment.py
  mlflow/tracing/destination.py
  mlflow/tracing/fluent.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
  mlflow/transformers/__init__.py
  mlflow/types/agent.py
  mlflow/utils/proto_json_utils.py
  tests/entities/test_assessment.py
  tests/entities/test_prompt.py
  tests/langchain/sample_code/chain_with_mlflow_prompt.py
  tests/langchain/test_langchain_databricks_dependency_extraction.py
  tests/langchain/test_langchain_model_export.py
  tests/langchain/test_langchain_output_parsers.py
  tests/langgraph/sample_code/langgraph_chat_agent.py
  tests/langgraph/sample_code/langgraph_chat_agent_custom_inputs.py
  tests/langgraph/test_langgraph_autolog.py
  tests/models/test_model.py
  tests/pyfunc/test_chat_agent.py
  tests/pyfunc/test_chat_agent_validation.py
  tests/spark/test_spark_model_export.py
  tests/tracing/test_assessment.py
  tests/tracing/test_destination.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
  tests/tracking/test_client.py
Labels: rn/none

#14946 Add demo notebooks for type hints
  examples/README.md
  examples/demos/pythonmodel_agent_with_uc_tools.ipynb
  examples/demos/pythonmodel_type_hints_quickstart.ipynb
Labels: rn/none

#14936 Draft prompt registry doc
  docs/docs/prompts/cm.mdx
  docs/docs/prompts/evaluate.mdx
  docs/docs/prompts/index.mdx
  docs/docs/prompts/run-and-model.mdx
  docs/sidebars.ts
  docs/static/images/llms/prompt-registry/compare-prompt-versions.png
  docs/static/images/llms/prompt-registry/create-prompt-alias.png
  docs/static/images/llms/prompt-registry/create-prompt-ui.png
  docs/static/images/llms/prompt-registry/prompt-aliases-list.png
  docs/static/images/llms/prompt-registry/prompt-evaluation-chart.png
  docs/static/images/llms/prompt-registry/prompt-evaluation-result.png
  docs/static/images/llms/prompt-registry/prompt-evaluation-trace.png
  docs/static/images/llms/prompt-registry/prompt-logged-graph.png
  docs/static/images/llms/prompt-registry/prompt-logged-model-links.png
  docs/static/images/llms/prompt-registry/prompt-logged-model.png
  docs/static/images/llms/prompt-registry/prompt-logged-trace.png
  docs/static/images/llms/prompt-registry/prompt-registry-header.png
  docs/static/images/llms/prompt-registry/registered-prompt.png
  docs/static/images/llms/prompt-registry/update-prompt-ui.png
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
Labels: area/docs, rn/documentation, v2.21.0

#14954 Fix infinite recursion error with warning handler module
  mlflow/utils/autologging_utils/logging_and_warnings.py
  tests/utils/test_autologging_utils.py
Labels: rn/bug-fix, area/models, v2.21.0

#14990 Unsupport search prompts by tags temporary
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptsListFilters.tsx
Labels: rn/none, area/tracking, v2.21.0

#14992 Openai agent sdk doc
  docs/docs/tracing/index.mdx
  docs/docs/tracing/integrations/index.mdx
  docs/docs/tracing/integrations/openai-agent.mdx
  docs/docs/tracing/integrations/swarm.mdx
  docs/static/images/llms/tracing/openai-agent-tracing-function-calling.png
  docs/static/images/llms/tracing/openai-agent-tracing-guardrail.png
  docs/static/images/llms/tracing/openai-agent-tracing.png
  docs/static/images/logos/openai-agent-logo.png
Labels: rn/none, area/tracking, v2.21.0

#14987 Support OpenAI Agent SDK Auto Tracing
  mlflow/ml-package-versions.yml
  mlflow/openai/__init__.py
  mlflow/openai/_agent_tracer.py
  mlflow/tracking/client.py
  tests/openai/test_openai_agent_autolog.py
Labels: rn/feature, area/tracking, v2.21.0

#14981 fix: show `not found page` if prompt name does not exist
  mlflow/server/js/src/experiment-tracking/pages/prompts/PromptsDetailsPage.test.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/PromptsDetailsPage.tsx
  mlflow/server/js/src/experiment-tracking/pages/prompts/components/PromptNotFoundView.tsx
Labels: rn/none, v2.21.0

#14994 Agent -> Agents
  docs/docs/tracing/integrations/openai-agent.mdx
  docs/docs/tracing/integrations/swarm.mdx
Labels: rn/none, area/tracking, v2.21.0

#14962 Add eval logging for DSPy
  mlflow/dspy/autolog.py
  mlflow/dspy/callback.py
  tests/dspy/test_dspy_autolog.py
Labels: rn/feature, area/tracking

#15000 Validate logged model name
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/utils/validation.py
  tests/models/test_model.py
  tests/store/tracking/test_file_store_logged_model.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#14919 docs: Tracking Server
  docs/docs/tracking/server/index.mdx
Labels: rn/none

#14920 docs: Misc formatting fixes
  docs/docs/getting-started/index.mdx
  docs/docs/getting-started/quickstart-2/index.mdx
  docs/docs/tracking/server/index.mdx
  docs/docs/tracking/tracking-api/index.mdx
  docs/docs/tracking/tutorials/local-database/index.mdx
Labels: rn/none

#14901 [langchain] Link traces to logged model
  mlflow/langchain/__init__.py
  mlflow/langchain/_langchain_autolog.py
  mlflow/langchain/langchain_tracer.py
  mlflow/langchain/utils/__init__.py
  mlflow/models/model.py
  tests/conftest.py
  tests/langchain/conftest.py
  tests/langchain/test_langchain_autolog.py
Labels: rn/none

#15007 Always use branch-x.y for changelog
  dev/update_changelog.py
Labels: rn/none, v2.21.0

#14938 Implement `CreateLoggedModel` and `GetLoggedModel` in tracking server
  mlflow/entities/logged_model.py
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#15018 Implement `FinalizeLoggedModel` in tracking server
  mlflow/entities/logged_model_status.py
  mlflow/server/handlers.py
  mlflow/store/tracking/rest_store.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#15021 Implement `SetLoggedModelTags` and `DeleteLoggedModelTag` in tracking server
  mlflow/server/handlers.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_file_store_logged_model.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#14858 fix: react18 warning
  mlflow/server/js/package.json
  mlflow/server/js/src/index.tsx
  mlflow/server/js/yarn.lock
Labels: rn/none

#14965 fix: ESLint warning fix
  mlflow/server/js/.eslintrc.js
  mlflow/server/js/package.json
  mlflow/server/js/src/emotion.d.ts
  mlflow/server/js/yarn.lock
Labels: rn/none

#15005 fix: show the metric diff highlight in compare experiment view
  mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx
Labels: rn/none, v2.21.0

#15014 fix: missing `attributes.` in `searchRunsByUser`
  mlflow/server/js/src/experiment-tracking/routes.test.tsx
  mlflow/server/js/src/experiment-tracking/routes.ts
Labels: rn/none, v2.21.1

#14993 [dspy] Link traces to logged model
  mlflow/dspy/autolog.py
  mlflow/dspy/callback.py
  mlflow/dspy/load.py
  mlflow/dspy/save.py
  tests/dspy/test_dspy_autolog.py
Labels: rn/none

#15009 Log params and dataset for DSPy optimization
  mlflow/dspy/autolog.py
  mlflow/dspy/callback.py
  mlflow/dspy/util.py
  tests/dspy/test_dspy_autolog.py
  tests/dspy/test_dspy_util.py
Labels: rn/none, area/tracking, v2.21.1

#15029 Improve test coverage for `log_model`
  tests/pyfunc/test_logged_models.py
Labels: rn/none

#15028 Ban more special characters in logged model name validation
  mlflow/utils/validation.py
  tests/store/tracking/test_file_store_logged_model.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#14982 Even faster `mlflow-skinny` installation
  .github/workflows/advice.js
  dev/install-skinny.sh
Labels: rn/none

#14947 Support sorting logged models by metrics and attributes: SqlAlchemyStore
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#15023 [openai] link traces to logged models
  mlflow/langchain/__init__.py
  mlflow/langchain/_langchain_autolog.py
  mlflow/langchain/langchain_tracer.py
  mlflow/models/model.py
  mlflow/openai/__init__.py
  mlflow/openai/_openai_autolog.py
  tests/openai/test_openai_autolog.py
Labels: rn/none

#14995 Fix Gemini dev test
  tests/gemini/test_gemini_autolog.py
Labels: rn/none, v2.21.1

#15039 Change the time of rerun-cross-version-tests
  .github/workflows/rerun-cross-version-tests.yml
Labels: rn/none, v2.21.1

#15040 Fix prepare_readme.py filename
  mlflow/ml-package-versions.yml
Labels: rn/none, v2.21.1

#15017 Gemini embeddings to Mlflow AI Gateway + Unit test
  examples/gateway/gemini/README.md
  examples/gateway/gemini/config.yaml
  examples/gateway/gemini/example.py
  mlflow/gateway/config.py
  mlflow/gateway/provider_registry.py
  mlflow/gateway/providers/gemini.py
  tests/gateway/providers/test_gemini.py
Labels: rn/feature

#15037 Fix dspy test
  mlflow/dspy/autolog.py
  mlflow/dspy/load.py
  mlflow/dspy/save.py
Labels: rn/none

#15020 [llama_index] link traces to logged model
  mlflow/llama_index/__init__.py
  mlflow/llama_index/tracer.py
  tests/llama_index/sample_code/basic_retriever.py
  tests/llama_index/test_llama_index_autolog.py
Labels: rn/none

#15041 Support filtering logged models: `SqlAlchemyStore`
  mlflow/store/tracking/dbmodels/models.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  mlflow/utils/search_logged_model_utils.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#15048 Fix sklearn dev test
  mlflow/ml-package-versions.yml
Labels: rn/none

#15019 Fix assessment proto/dict conversion
  mlflow/entities/assessment.py
  mlflow/entities/assessment_error.py
  tests/entities/test_assessment.py
Labels: rn/none, area/tracking

#15053 Remove 0x prefix from span and trace iD
  mlflow/tracing/utils/__init__.py
  tests/entities/test_span.py
Labels: rn/none, v2.21.1

#15010 Set inputs field in create_run in SqlAlchemyStore
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none, area/tracking, v2.21.1

#14868 Add --install-java option to sagemaker build-and-push-container
  mlflow/models/docker_utils.py
  mlflow/sagemaker/cli.py
  mlflow/utils/cli_args.py
  tests/resources/dockerfile/Dockerfile_sagemaker_virtualenv_no_java
  tests/sagemaker/test_cli.py
Labels: rn/feature, language/java, area/models, area/docker, integrations/sagemaker, v2.20.4, v2.21.1

#15063 Implement `LogOutputs` REST API
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#15056 Bump min support version for transformers
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
Labels: rn/none

#15044 FileStore order_by fix
  mlflow/store/tracking/file_store.py
  mlflow/utils/search_utils.py
  tests/store/tracking/test_file_store_logged_model.py
Labels: rn/none

#15076 Add meetup examples
  examples/demos/mlflow-3/README.md
  examples/demos/mlflow-3/deep_learning.py
  examples/demos/mlflow-3/genai.py
  examples/demos/mlflow-3/ml.py
Labels: rn/none

#14959 fix: class component to functional component
  mlflow/server/js/src/common/components/Spinner.tsx
  mlflow/server/js/src/experiment-tracking/components/HtmlTableView.tsx
  mlflow/server/js/src/experiment-tracking/components/ParallelCoordinatesPlotControls.tsx
  mlflow/server/js/src/experiment-tracking/components/RunNotFoundView.tsx
  mlflow/server/js/src/model-registry/components/CreateModelButton.tsx
Labels: rn/none

#15050 fix: model name with asterisk
  mlflow/server/js/package.json
  mlflow/server/js/yarn.lock
Labels: rn/none, v2.21.1

#15024 Implement `SearchLoggedModels` in tracking server
  mlflow/server/handlers.py
  mlflow/store/tracking/rest_store.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#15034 Show images in the metric tab
  mlflow/server/js/src/experiment-tracking/reducers/ImageReducer.ts
Labels: rn/bug-fix, v2.21.1

#15058 Spark udf fix
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_spark.py
Labels: rn/none

#15035 Check for pandas null values in infer_schema in infer_signature + Test
  mlflow/types/utils.py
  tests/types/test_schema.py
Labels: rn/none, v2.21.1

#15030 fix: fix tag names for autocomplete
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/RunsSearchAutoComplete.tsx
  mlflow/server/js/src/experiment-tracking/components/experiment-page/components/runs/RunsSearchAutoComplete.utils.tsx
Labels: rn/none, v2.21.1
