Repository mlflow/mlflow, pull requests merged in 2025-04, with the labels that each got.

#15085 Add 'return_type' argument to mlflow.search_traces() API
  docs/api_reference/source/conf.py
  docs/docs/tracing/api/search.mdx
  docs/docs/tracing/tracing-schema.mdx
  docs/static/images/llms/tracing/search-traces-on-ui.png
  mlflow/tracing/fluent.py
  mlflow/tracking/client.py
  tests/tracing/display/test_ipython.py
  tests/tracing/test_fluent.py
Labels: rn/none, area/tracking, v2.21.1, v2.21.3

#15178 Disable autogen 0.4 cross test
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
Labels: rn/none, area/tracking

#15184 Rename models/recources to prevent import errors
  dev/pyproject.py
  mlflow/models/display_utils.py
  mlflow/models/notebook_resources/agent_evaluation_template.html
  mlflow/models/notebook_resources/eval_with_dataset_example.py
  mlflow/models/notebook_resources/eval_with_synthetic_example.py
  pyproject.release.toml
  pyproject.toml
  skinny/pyproject.toml
Labels: rn/none, v2.21.3

#15143 Add document page for DSPy optimizer tracking
  docs/docs/llms/dspy/index.mdx
  docs/docs/llms/dspy/optimizer.mdx
  docs/sidebars.ts
Labels: area/docs, rn/documentation, v2.21.3

#15103 [langchain] create LoggedModel for autologging
  mlflow/__init__.py
  mlflow/dspy/autolog.py
  mlflow/langchain/__init__.py
  mlflow/langchain/_langchain_autolog.py
  mlflow/langchain/langchain_tracer.py
  mlflow/models/model.py
  mlflow/openai/_openai_autolog.py
  mlflow/tracking/fluent.py
  tests/langchain/test_langchain_autolog.py
Labels: rn/none

#15187 MLflow UI export 2025.03.31 followup
  mlflow/server/js/yarn.lock
Labels: rn/none, area/uiux

#15189 Flip `isExperimentLoggedModelsUIEnabled` and `shouldEnableGraphQLRunDetailsPage`
  mlflow/server/js/src/common/utils/FeatureUtils.ts
  mlflow/server/js/src/experiment-tracking/components/run-page/RunViewOverview.intg.test.tsx
  mlflow/server/js/src/experiment-tracking/components/run-page/hooks/useRunDetailsPageData.test.tsx
Labels: rn/none

#15198 Fix spark ML save model error in Databricks shared or serverless cluster
  mlflow/spark/__init__.py
Labels: rn/bug-fix, area/tracking, v2.21.3

#15212 Sync master to mlflow 3
  dev/install-common-deps.sh
  mlflow/spark/__init__.py
  mlflow/tracing/export/mlflow.py
  mlflow/tracing/fluent.py
  tests/conftest.py
  tests/tracing/export/test_mlflow_exporter.py
  tests/tracing/test_fluent.py
  tests/tracing/test_provider.py
  tests/tracking/test_client.py
Labels: rn/none

#15186 Stop parsing list or dict input in dspy.Example
  mlflow/dspy/util.py
  tests/dspy/test_dspy_util.py
Labels: rn/none, area/tracking, v2.21.3

#15214 Add fluent API set_logged_model_tags and delete_logged_model_tag
  mlflow/__init__.py
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/feature, area/tracking

#15219 Fix datasets parameter validation for `log_inputs`
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#15106 [llama_index] create LoggedModel in autolog
  mlflow/dspy/autolog.py
  mlflow/langchain/_langchain_autolog.py
  mlflow/llama_index/__init__.py
  mlflow/llama_index/tracer.py
  mlflow/openai/_openai_autolog.py
  mlflow/utils/autologging_utils/config.py
  tests/llama_index/test_llama_index_autolog.py
Labels: rn/none

#15220 Fix `log_metric` to use model_id, dataset_name, and dataset_digest
  mlflow/server/handlers.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#15223 Log params for openai autolog
  mlflow/models/evaluation/utils/trace.py
  mlflow/openai/_openai_autolog.py
  tests/openai/test_openai_autolog.py
Labels: rn/none

#15221 Pass missing `models` to `log_inputs`
  mlflow/server/handlers.py
  mlflow/store/tracking/sqlalchemy_store.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#15078 MLflow 3.0 docs
  docs/docs/mlflow-3/deep-learning.mdx
  docs/docs/mlflow-3/genai-agent.mdx
  docs/docs/mlflow-3/index.mdx
  docs/sidebars.ts
  docs/static/images/mlflow-3/deep-learning/logged_models.png
  docs/static/images/mlflow-3/deep-learning/model_artifacts.png
  docs/static/images/mlflow-3/deep-learning/run_page.png
  docs/static/images/mlflow-3/genai/chatbot_prompt.png
  docs/static/images/mlflow-3/genai/evaluate_metrics.png
  docs/static/images/mlflow-3/genai/logged_model_autolog_traces.png
  docs/static/images/mlflow-3/genai/logged_model_page.png
  docs/static/images/mlflow-3/genai/logged_models_tab.png
  docs/static/images/mlflow-3/simple_example_model.png
  docs/static/images/mlflow-3/simple_example_models_tab.png
  docs/static/images/mlflow-3/simple_example_run_page.png
  docs/static/images/mlflow-3/simple_example_traces.png
Labels: rn/none

#15226 Remove temporary workaround to install mlflow from `mlflow-3` branch
  mlflow/utils/environment.py
Labels: rn/none

#15237 Install `accelerate` to fix `NameError: name 'init_empty_weights' is not defined` in sentence-transformers cross-version tests
  mlflow/ml-package-versions.yml
Labels: rn/none

#15074 Load context when infering signature from type hints
  mlflow/pyfunc/__init__.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/pyfunc/test_pyfunc_model_with_type_hints.py
Labels: rn/none, v2.21.1, v2.21.3

#15235 Replace `sklearn.utils.parallel_backend` with `joblib.parallel_backend`
  tests/sklearn/test_sklearn_autolog.py
Labels: rn/none, enable-dev-tests

#15236 Replace `mlflow-automation` with `mlflow-app[bot]`
  .github/workflows/autoformat.yml
  .github/workflows/release-note.js
  .github/workflows/sync.py
  dev/update_changelog.py
Labels: rn/none

#15208 Update deprecation message for log_models
  mlflow/langchain/__init__.py
  mlflow/openai/__init__.py
Labels: rn/none, v2.21.3

#15242 Make improvements / fix bugs in assessments docstrings
  mlflow/entities/assessment.py
  mlflow/tracing/assessment.py
Labels: rn/none, area/tracking

#15244 Document how to increase verbosity for `mlflow.models.predict`
  mlflow/models/python_api.py
Labels: rn/none

#15246 Fix installation command
  docs/docs/mlflow-3/genai-agent.mdx
  docs/docs/mlflow-3/index.mdx
Labels: rn/none

#15249 Avoid `transformers==4.51.0`
  .github/workflows/cross-version-tests.yml
  .github/workflows/gateway.yml
  .github/workflows/lint.yml
  .github/workflows/master.yml
  .github/workflows/slow-tests.yml
  requirements/constraints.txt
Labels: rn/none

#15016 Strip slash
  mlflow/store/artifact/optimized_s3_artifact_repo.py
  mlflow/store/artifact/s3_artifact_repo.py
  tests/store/artifact/test_s3_artifact_repo.py
Labels: rn/bug-fix, area/artifacts, area/tracking, area/server-infra, v2.21.1

#15252 Ignore v3 tag in patch workflow
  .github/workflows/patch.js
Labels: rn/none

#15052 Update dependencies from langchain_databricks to databricks_langchain.
  mlflow/langchain/databricks_dependencies.py
  mlflow/langchain/utils/__init__.py
  mlflow/ml-package-versions.yml
  tests/langchain/test_langchain_databricks_dependency_extraction.py
  tests/langchain/test_langchain_databricks_integration.py
Labels: rn/none

#15255 Remove fastai in MLFlow 3
  conftest.py
  docs/api_reference/source/conf.py
  docs/api_reference/source/python_api/mlflow.fastai.rst
  docs/docs/deep-learning/index.mdx
  docs/docs/model/index.mdx
  docs/docs/tracking/autolog/index.mdx
  docs/docs/tutorials-and-examples/index.mdx
  docs/src/api_modules.json
  examples/README.md
  examples/fastai/MLproject
  examples/fastai/README.md
  examples/fastai/python_env.yaml
  examples/fastai/train.py
  mlflow/__init__.py
  mlflow/fastai/__init__.py
  mlflow/fastai/callback.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/models/__init__.py
  mlflow/tracking/fluent.py
  requirements/extra-ml-requirements.txt
  tests/autologging/test_autologging_behaviors_integration.py
  tests/check_mlflow_lazily_imports_ml_packages.py
  tests/examples/test_examples.py
  tests/fastai/test_fastai_autolog.py
  tests/fastai/test_fastai_model_export.py
  tests/pyfunc/docker/conftest.py
  tests/pyfunc/docker/test_docker_flavors.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/breaking-change, area/tracking

#15241 Log metrics to model id after eval
  mlflow/models/evaluation/base.py
  tests/evaluate/test_evaluation.py
Labels: rn/feature, area/tracking, autoformat

#15261 Use the latest version of `wheel` and `setuptools`
  .github/workflows/master.yml
  dev/install-common-deps.sh
Labels: rn/none

#15264 Unset `per_page` in patch workflow
  .github/workflows/patch.js
Labels: rn/none

#15263 Fix mlflow 3 installation command
  docs/docs/mlflow-3/genai-agent.mdx
  docs/docs/mlflow-3/index.mdx
Labels: rn/none

#15266 Add issues:write permission to patch workflow
  .github/workflows/patch.yml
Labels: rn/none

#15262 Turn off progress bar while downloading wheels
  mlflow/models/wheeled_model.py
Labels: rn/none

#15258 Remove H2O in MLflow 3
  .github/workflows/r.yml
  conftest.py
  docs/api_reference/source/R-api.rst
  docs/api_reference/source/python_api/mlflow.h2o.rst
  docs/docs/model/index.mdx
  docs/docs/tutorials-and-examples/index.mdx
  docs/src/api_modules.json
  examples/README.md
  examples/h2o/MLproject
  examples/h2o/python_env.yaml
  examples/h2o/random_forest.ipynb
  examples/h2o/random_forest.py
  examples/h2o/wine-quality.csv
  mlflow/R/mlflow/.create-test-env.R
  mlflow/R/mlflow/DESCRIPTION
  mlflow/R/mlflow/NAMESPACE
  mlflow/R/mlflow/R/model-h2o.R
  mlflow/R/mlflow/man/mlflow_save_model.Rd
  mlflow/R/mlflow/tests/testthat/test-model-h2o.R
  mlflow/__init__.py
  mlflow/h2o/__init__.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/models/__init__.py
  mlflow/models/cli.py
  mlflow/models/python_api.py
  mlflow/pyfunc/backend.py
  requirements/extra-ml-requirements.txt
  tests/check_mlflow_lazily_imports_ml_packages.py
  tests/examples/README.md
  tests/examples/test_examples.py
  tests/h2o/test_h2o_model_export.py
  tests/pyfunc/docker/test_docker_flavors.py
Labels: rn/breaking-change, area/tracking

#15268 Set `exclude_unset=False` to fix groq tests
  .github/workflows/cross-version-tests.yml
  tests/groq/test_groq_autolog.py
Labels: rn/none, enable-dev-tests

#15247 Allow log_model() with existing model_id
  mlflow/models/model.py
  tests/pyfunc/test_logged_models.py
Labels: rn/none, area/tracking

#15272 Pin GitHub actions to a full length commit SHA
  .github/actions/cache-pip/action.yml
  .github/actions/setup-java/action.yml
  .github/actions/setup-node/action.yml
  .github/actions/setup-python/action.yml
  .github/actions/validate-author/action.yml
  .github/workflows/advice.yml
  .github/workflows/autoformat.yml
  .github/workflows/build-wheel.yml
  .github/workflows/cancel.yml
  .github/workflows/cherry-picks-warn.yml
  .github/workflows/closing-pr.yml
  .github/workflows/cross-version-test-runner.yml
  .github/workflows/cross-version-tests.yml
  .github/workflows/deployments.yml
  .github/workflows/dev-setup.yml
  .github/workflows/devcontainer.yml
  .github/workflows/examples.yml
  .github/workflows/gateway.yml
  .github/workflows/js.yml
  .github/workflows/labeling.yml
  .github/workflows/lint.yml
  .github/workflows/maintainer-approval.yml
  .github/workflows/master.yml
  .github/workflows/patch.yml
  .github/workflows/preview-docs.yml
  .github/workflows/protect.yml
  .github/workflows/protobuf-cross-test.yml
  .github/workflows/protos.yml
  .github/workflows/push-images.yml
  .github/workflows/r.yml
  .github/workflows/recipe-template.yml
  .github/workflows/release-note.yml
  .github/workflows/requirements.yml
  .github/workflows/rerun-cross-version-tests.yml
  .github/workflows/rerun-workflow-run.yml
  .github/workflows/rerun.yml
  .github/workflows/slow-tests.yml
  .github/workflows/sync.yml
  .github/workflows/team-review.yml
  .github/workflows/uc-oss.yml
Labels: rn/none

#15269 Remove `hf:/` prefix in snapshot location
  tests/transformers/test_transformers_model_export.py
Labels: rn/none

#15278 Sync
  .github/actions/cache-pip/action.yml
  .github/actions/setup-java/action.yml
  .github/actions/setup-node/action.yml
  .github/actions/setup-python/action.yml
  .github/actions/validate-author/action.yml
  .github/workflows/advice.yml
  .github/workflows/autoformat.yml
  .github/workflows/build-wheel.yml
  .github/workflows/cancel.yml
  .github/workflows/cherry-picks-warn.yml
  .github/workflows/closing-pr.yml
  .github/workflows/cross-version-test-runner.yml
  .github/workflows/cross-version-tests.yml
  .github/workflows/deployments.yml
  .github/workflows/dev-setup.yml
  .github/workflows/devcontainer.yml
  .github/workflows/examples.yml
  .github/workflows/gateway.yml
  .github/workflows/js.yml
  .github/workflows/labeling.yml
  .github/workflows/lint.yml
  .github/workflows/maintainer-approval.yml
  .github/workflows/master.yml
  .github/workflows/patch.js
  .github/workflows/patch.yml
  .github/workflows/preview-docs.yml
  .github/workflows/protect.yml
  .github/workflows/protobuf-cross-test.yml
  .github/workflows/protos.yml
  .github/workflows/push-images.yml
  .github/workflows/r.yml
  .github/workflows/release-note.yml
  .github/workflows/requirements.yml
  .github/workflows/rerun-cross-version-tests.yml
  .github/workflows/rerun-workflow-run.yml
  .github/workflows/rerun.yml
  .github/workflows/slow-tests.yml
  .github/workflows/sync.yml
  .github/workflows/team-review.yml
  .github/workflows/uc-oss.yml
  mlflow/R/mlflow/DESCRIPTION
  mlflow/java/client/pom.xml
  mlflow/java/pom.xml
  mlflow/java/scoring/pom.xml
  mlflow/java/scoring/src/main/java/org/mlflow/sagemaker/ScoringServer.java
  mlflow/java/scoring/src/test/java/org/mlflow/ScoringServerTest.java
  mlflow/java/spark/pom.xml
  mlflow/models/wheeled_model.py
  mlflow/server/js/src/common/constants.tsx
  mlflow/version.py
  pyproject.release.toml
  pyproject.toml
  skinny/pyproject.toml
  tests/groq/test_groq_autolog.py
  tests/transformers/test_transformers_model_export.py
Labels: rn/none

#15267 Update workers default value and docstring
  mlflow/models/cli.py
  mlflow/utils/cli_args.py
Labels: rn/none

#15256 Always create a run for dspy eval
  mlflow/dspy/callback.py
  tests/dspy/test_dspy_autolog.py
Labels: rn/none, area/tracking, v2.21.4

#15254 [Anthropic] Create external model and link traces
  mlflow/anthropic/__init__.py
  mlflow/anthropic/autolog.py
  tests/anthropic/test_anthropic_autolog.py
Labels: rn/none

#15275 Retry when request to `huggingface_hub` fails with 429
  mlflow/transformers/hub_utils.py
Labels: rn/none

#15232 Performance: refactor _get_run_inputs to make a single database call
  mlflow/store/tracking/sqlalchemy_store.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none, area/tracking, area/sqlalchemy, v2.21.4

#15248 mlflow.evaluate(): Add model_id parameter to link metrics / traces to a particular loggedmodel
  mlflow/models/evaluation/base.py
  tests/evaluate/test_evaluation.py
Labels: rn/none, area/tracking

#15251 Fix databricks-connect inference
  .github/workflows/master.yml
  mlflow/utils/requirements_utils.py
  tests/utils/test_requirements_utils.py
Labels: rn/none, v2.21.4

#15288 Document what `skinny/mlflow` is to avoid confusion
  dev/pyproject.py
  skinny/README.md
  skinny/README_SKINNY.md
  skinny/pyproject.toml
Labels: rn/none

#15286 fix openai gateway adapter
  mlflow/gateway/providers/openai.py
  tests/gateway/providers/test_openai.py
Labels: rn/bug-fix, area/deployments, v2.21.4

#15290 Sync
  .github/workflows/master.yml
  dev/pyproject.py
  mlflow/dspy/callback.py
  mlflow/models/cli.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/transformers/hub_utils.py
  mlflow/utils/cli_args.py
  mlflow/utils/requirements_utils.py
  skinny/README.md
  skinny/README_SKINNY.md
  skinny/pyproject.toml
  tests/dspy/test_dspy_autolog.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/utils/test_requirements_utils.py
Labels: rn/none

#15287 Validate auth password to be string longer than 8 chars
  mlflow/server/auth/__init__.py
  mlflow/server/auth/basic_auth.ini
  mlflow/server/auth/sqlalchemy_store.py
  mlflow/utils/validation.py
  tests/helper_functions.py
  tests/server/auth/test_auth.py
Labels: rn/bug-fix, area/server-infra, v2.21.4

#15163 Implement async export for Databricks trace export and make it default
  docs/docs/tracing/api/how-to.mdx
  mlflow/environment_variables.py
  mlflow/tracing/export/async_export_queue.py
  mlflow/tracing/export/databricks.py
  mlflow/tracing/export/mlflow.py
  mlflow/utils/rest_utils.py
  tests/tracing/export/test_async_export_queue.py
  tests/tracing/export/test_databricks_exporter.py
  tests/tracing/export/test_mlflow_exporter.py
Labels: rn/feature, area/tracking

#15297 Stringify non-string tags and enforce length limits on v3 TraceInfo
  mlflow/entities/trace_info.py
  mlflow/tracing/fluent.py
  mlflow/tracking/client.py
  tests/entities/test_trace_info.py
Labels: rn/none, v2.21.4

#14939 Automatically update Text Artifact view in UI
  mlflow/server/js/src/experiment-tracking/components/ArtifactView.tsx
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactPage.tsx
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactTextView.tsx
  mlflow/server/js/src/lang/default/en.json
Labels: rn/feature, area/uiux

#15066 Copy button added for new run using notebook
  mlflow/server/js/src/experiment-tracking/components/evaluation-artifacts-compare/CreateNotebookRunModal.tsx
Labels: rn/none, area/uiux, v2.21.1

#15303 Explicitly set python that `reticulate` uses
  .github/workflows/r.yml
  mlflow/R/mlflow/.install-deps.R
  mlflow/R/mlflow/tests/testthat/test-keras-model.R
Labels: rn/none

#15285 Update Fluent Search Logged Models to Paginate with Client Calls
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/none, area/tracking

#15233 Add get_last_active_trace works in model serving / monitoring
  docs/api_reference/source/python_api/mlflow.rst
  docs/docs/tracing/tracing-schema.mdx
  docs/docs/tracing/tutorials/jupyter-trace-demo.ipynb
  examples/tracing/client.py
  examples/tracing/fluent.py
  examples/tracing/multithreading.py
  mlflow/__init__.py
  mlflow/entities/trace.py
  mlflow/tracing/export/databricks.py
  mlflow/tracing/export/inference_table.py
  mlflow/tracing/fluent.py
  tests/dspy/test_dspy_autolog.py
  tests/entities/test_trace.py
  tests/entities/test_trace_data.py
  tests/langchain/test_langchain_autolog.py
  tests/langchain/test_langchain_tracer.py
  tests/langgraph/test_langgraph_autolog.py
  tests/litellm/test_litellm_autolog.py
  tests/openai/test_openai_autolog.py
  tests/tracing/export/test_databricks_exporter.py
  tests/tracing/export/test_inference_table_exporter.py
  tests/tracing/test_fluent.py
  tests/tracing/utils/test_utils.py
  tests/tracking/fluent/test_fluent_autolog.py
  tests/tracking/test_client.py
Labels: rn/breaking-change, area/tracking, v2.21.4, v2.22.0

#15308 Sync
  .github/workflows/r.yml
  mlflow/R/mlflow/.install-deps.R
  mlflow/R/mlflow/tests/testthat/test-keras-model.R
  mlflow/entities/trace_info.py
  mlflow/server/js/src/experiment-tracking/components/ArtifactView.tsx
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactPage.tsx
  mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactTextView.tsx
  mlflow/server/js/src/experiment-tracking/components/evaluation-artifacts-compare/CreateNotebookRunModal.tsx
  mlflow/server/js/src/lang/default/en.json
  mlflow/tracing/fluent.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  tests/entities/test_trace_info.py
  tests/tracing/export/test_databricks_exporter.py
  tests/tracking/test_client.py
Labels: rn/none

#15298 Migrate the legacy `mlflow.evaluation.Assessment` to the new `mlflow.entity.Assessment`
  mlflow/entities/assessment.py
  mlflow/entities/assessment_source.py
  mlflow/evaluation/assessment.py
  mlflow/evaluation/utils.py
  mlflow/tracking/client.py
  tests/entities/test_assessment.py
  tests/entities/test_assessment_source.py
  tests/evaluate/logging/test_assessment.py
  tests/evaluate/logging/test_assessment_entity.py
  tests/evaluate/logging/test_fluent.py
  tests/evaluate/logging/test_utils.py
Labels: rn/none, area/tracking

#15311 Move assessment error in Feedback
  mlflow/entities/assessment.py
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/databricks_trace_server.proto
  mlflow/protos/databricks_trace_server_pb2.py
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
  mlflow/store/tracking/rest_store.py
  mlflow/tracing/assessment.py
  mlflow/tracking/client.py
  tests/entities/test_assessment.py
  tests/store/tracking/test_rest_store.py
  tests/tracing/test_assessment.py
Labels: rn/none

#15313 Fix langchain retriever notebook title
  docs/docs/llms/langchain/notebooks/langchain-retriever.ipynb
Labels: rn/none, v2.21.4

#15312 Sync
  docs/api_reference/source/python_api/mlflow.rst
  docs/docs/tracing/tracing-schema.mdx
  docs/docs/tracing/tutorials/jupyter-trace-demo.ipynb
  examples/tracing/client.py
  examples/tracing/fluent.py
  examples/tracing/multithreading.py
  mlflow/__init__.py
  mlflow/entities/trace.py
  mlflow/tracing/export/databricks.py
  mlflow/tracing/export/inference_table.py
  mlflow/tracing/fluent.py
  tests/dspy/test_dspy_autolog.py
  tests/entities/test_trace.py
  tests/entities/test_trace_data.py
  tests/langchain/test_langchain_autolog.py
  tests/langchain/test_langchain_tracer.py
  tests/langgraph/test_langgraph_autolog.py
  tests/litellm/test_litellm_autolog.py
  tests/openai/test_openai_autolog.py
  tests/tracing/export/test_databricks_exporter.py
  tests/tracing/export/test_inference_table_exporter.py
  tests/tracing/test_fluent.py
  tests/tracing/utils/test_utils.py
  tests/tracking/fluent/test_fluent_autolog.py
  tests/tracking/test_client.py
Labels: rn/none

#15240 Support tracing OpenAI Responses API
  docs/docs/tracing/integrations/openai.mdx
  mlflow/openai/__init__.py
  mlflow/openai/_openai_autolog.py
  mlflow/openai/utils/chat_schema.py
  tests/openai/mock_openai.py
  tests/openai/test_openai_responses_autolog.py
Labels: rn/feature, area/tracking, v2.22.0

#15314 Deduplicate Assessment prot messages
  dev/generate_protos.py
  mlflow/entities/assessment.py
  mlflow/entities/assessment_error.py
  mlflow/entities/assessment_source.py
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Assessments.java
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Service.java
  mlflow/protos/assessments.proto
  mlflow/protos/assessments_pb2.py
  mlflow/protos/databricks_trace_server.proto
  mlflow/protos/databricks_trace_server_pb2.py
  mlflow/protos/service.proto
  mlflow/protos/service_pb2.py
  tests/entities/test_assessment.py
Labels: rn/none

#15333 Make assessment backward compatible
  mlflow/entities/assessment.py
  tests/entities/test_assessment.py
Labels: rn/none, area/tracking, v2.21.4

#15305 Deprecate extra_model_classes in langchain autolog
  mlflow/langchain/__init__.py
Labels: rn/none

#15302 Drop log_models option and auto track of model_id for GenAI flavors
  mlflow/anthropic/__init__.py
  mlflow/anthropic/autolog.py
  mlflow/dspy/autolog.py
  mlflow/dspy/callback.py
  mlflow/dspy/load.py
  mlflow/dspy/save.py
  mlflow/langchain/__init__.py
  mlflow/langchain/_langchain_autolog.py
  mlflow/langchain/langchain_tracer.py
  mlflow/llama_index/__init__.py
  mlflow/llama_index/tracer.py
  mlflow/openai/__init__.py
  mlflow/openai/_openai_autolog.py
  tests/anthropic/test_anthropic_autolog.py
  tests/dspy/test_dspy_autolog.py
  tests/langchain/test_langchain_autolog.py
  tests/llama_index/test_llama_index_autolog.py
  tests/openai/test_openai_autolog.py
Labels: rn/none

#15335 Install `libtiff-dev` to fix ragg installation error
  .github/workflows/r.yml
Labels: rn/none

#15243 Add optuna storage utility to enable parallel hyperparam tuning
  .github/workflows/master.yml
  mlflow/pyspark/optuna/__init__.py
  mlflow/pyspark/optuna/storage.py
  tests/pyspark/optuna/test_storage.py
Labels: rn/feature, area/models, v2.20.0

#15336 Skip tests that rely on hugginface hub if it's unhealthy
  mlflow/metrics/metric_definitions.py
  tests/data/test_huggingface_dataset_and_source.py
  tests/gateway/providers/test_huggingface.py
  tests/helper_functions.py
Labels: rn/none

#15321 Use `MessageToDict` to convert Assessment entity to dict to mirror its proto
  mlflow/entities/assessment.py
  mlflow/utils/proto_json_utils.py
  tests/entities/test_assessment.py
Labels: rn/none

#15349 Fix `_is_hf_hub_healthy` to handle import error
  tests/helper_functions.py
Labels: rn/none

#15292 Fix `Model.load` slowness
  mlflow/models/model.py
  mlflow/pyfunc/model.py
Labels: rn/none, v2.22.0

#15319 Fix llamaindex test
  tests/llama_index/test_llama_index_tracer.py
Labels: rn/none, area/tracking

#15350 Sync
  .github/workflows/master.yml
  .github/workflows/r.yml
  mlflow/metrics/metric_definitions.py
  mlflow/protos/databricks_trace_server.proto
  mlflow/protos/databricks_trace_server_pb2.py
  mlflow/pyspark/optuna/__init__.py
  mlflow/pyspark/optuna/storage.py
  tests/data/test_huggingface_dataset_and_source.py
  tests/gateway/providers/test_huggingface.py
  tests/helper_functions.py
  tests/pyspark/optuna/test_storage.py
Labels: rn/none

#15320 Exclude CrewAI 0.114.0
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#15339 Add set_active_model and get_active_model_id
  docs/api_reference/source/conf.py
  mlflow/__init__.py
  mlflow/environment_variables.py
  mlflow/models/model.py
  mlflow/tracing/processor/mlflow.py
  mlflow/tracking/fluent.py
  tests/conftest.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/none

#15353 Fix pytorch cross version tests
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#15352 Fix logging-first-model notebook links
  docs/docs/getting-started/logging-first-model/index.mdx
  docs/docs/getting-started/logging-first-model/notebooks/index.mdx
Labels: rn/none

#15317 Disable autologging tests for autogen >= 0.4 and litellm >= 1.59.12
  dev/set_matrix.py
  mlflow/ml-package-versions.yml
Labels: rn/none, area/build

#15279 Update `TraceInfo` class to match TraceV3 format
  mlflow.db
  mlflow/entities/__init__.py
  mlflow/entities/assessment.py
  mlflow/entities/trace.py
  mlflow/entities/trace_info.py
  mlflow/entities/trace_info_v3.py
  mlflow/entities/trace_location.py
  mlflow/entities/trace_state.py
  mlflow/entities/trace_status.py
  mlflow/store/tracking/rest_store.py
  mlflow/utils/proto_json_utils.py
  tests/entities/test_trace.py
  tests/entities/test_trace_info.py
  tests/entities/test_trace_info_v3.py
  tests/entities/test_trace_location.py
  tests/entities/test_trace_state.py
  tests/tracing/export/test_databricks_agent_legacy_exporter.py
  tests/tracing/export/test_databricks_exporter.py
  tests/tracing/export/test_inference_table_exporter.py
  tests/tracing/export/test_mlflow_exporter.py
  tests/tracing/utils/test_timeout.py
  tests/tracking/_tracking_service/test_tracking_service_client.py
  tests/tracking/test_client.py
Labels: rn/none

#15358 Fix API reference link in doc preview
  docs/docusaurus.config.ts
  docs/scripts/build-all.py
Labels: rn/none

#15363 Sync
  dev/set_matrix.py
  docs/docs/getting-started/logging-first-model/index.mdx
  docs/docs/getting-started/logging-first-model/notebooks/index.mdx
  mlflow/ml-package-versions.yml
  mlflow/models/model.py
  mlflow/pyfunc/model.py
  tests/llama_index/test_llama_index_tracer.py
Labels: rn/none

#15282 [ML-52305] mlflow.genai.evaluate() PoC commit
  mlflow/genai/__init__.py
  mlflow/genai/evaluation/__init__.py
  mlflow/genai/evaluation/base.py
  mlflow/genai/evaluation/utils.py
  mlflow/genai/scorers/__init__.py
  mlflow/genai/scorers/base.py
  mlflow/genai/scorers/dummy_builtin_scorer.py
  mlflow/tracing/utils/__init__.py
  tests/tracing/utils/test_utils.py
Labels: rn/feature, area/tracking

#15351 Fix langchain cross-version test
  tests/langchain/test_langchain_evaluation.py
Labels: rn/none, area/build

#15341 Set active_model when loading models for GenAI
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  mlflow/dspy/load.py
  mlflow/environment_variables.py
  mlflow/langchain/__init__.py
  mlflow/llama_index/__init__.py
  mlflow/openai/__init__.py
  mlflow/tracking/fluent.py
  tests/conftest.py
  tests/dspy/test_dspy_autolog.py
  tests/langchain/test_langchain_autolog.py
  tests/langgraph/test_langgraph_autolog.py
  tests/llama_index/test_llama_index_autolog.py
  tests/openai/test_openai_autolog.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/none

#15370 [Tracing SDK][1] Remove tracing dependency to MLflowClient
  dev/set_matrix.py
  docs/api_reference/source/python_api/mlflow.rst
  docs/docs/getting-started/logging-first-model/index.mdx
  docs/docs/getting-started/logging-first-model/notebooks/index.mdx
  docs/docs/tracing/api/how-to.mdx
  docs/docs/tracing/tracing-schema.mdx
  examples/tracing/langchain_auto.py
  examples/tracing/multithreading.py
  mlflow/__init__.py
  mlflow/anthropic/autolog.py
  mlflow/autogen/autogen_logger.py
  mlflow/bedrock/_autolog.py
  mlflow/bedrock/stream.py
  mlflow/dspy/callback.py
  mlflow/entities/span.py
  mlflow/genai/__init__.py
  mlflow/genai/evaluation/__init__.py
  mlflow/genai/evaluation/base.py
  mlflow/genai/evaluation/utils.py
  mlflow/genai/scorers/__init__.py
  mlflow/genai/scorers/base.py
  mlflow/genai/scorers/dummy_builtin_scorer.py
  mlflow/langchain/langchain_tracer.py
  mlflow/ml-package-versions.yml
  mlflow/models/model.py
  mlflow/openai/_agent_tracer.py
  mlflow/openai/_openai_autolog.py
  mlflow/pyfunc/model.py
  mlflow/server/handlers.py
  mlflow/store/artifact/artifact_repo.py
  mlflow/store/artifact/local_artifact_repo.py
  mlflow/tracing/assessment.py
  mlflow/tracing/client.py
  mlflow/tracing/export/mlflow.py
  mlflow/tracing/fluent.py
  mlflow/tracing/processor/mlflow.py
  mlflow/tracing/provider.py
  mlflow/tracing/utils/__init__.py
  mlflow/tracing/utils/artifact_utils.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  tests/autogen/test_autogen_autolog.py
  tests/examples/test_examples.py
  tests/llama_index/test_llama_index_tracer.py
  tests/pyfunc/test_logged_models.py
  tests/tracing/conftest.py
  tests/tracing/export/test_mlflow_exporter.py
  tests/tracing/helper.py
  tests/tracing/processor/test_mlflow_processor.py
  tests/tracing/test_assessment.py
  tests/tracing/test_fluent.py
  tests/tracing/test_provider.py
  tests/tracing/utils/test_utils.py
  tests/tracking/_tracking_service/test_tracking_service_client.py
  tests/tracking/test_client.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none, area/tracking

#15378 Add introduction to the sidebar
  docs/sidebars.ts
Labels: rn/none, v2.21.4

#15293 You need two *separate* shells for js dev server
  CONTRIBUTING.md
Labels: rn/none, v2.21.4

#15379 Remove module reload usage in test
  mlflow/pyfunc/utils/data_validation.py
  tests/pyfunc/test_pyfunc_model_with_type_hints.py
Labels: rn/none, v2.22.0

#15357 Move optuna module to `mlflow/optuna`
  .github/workflows/master.yml
  mlflow/optuna/__init__.py
  mlflow/optuna/storage.py
  mlflow/pyspark/optuna/__init__.py
  tests/optuna/test_storage.py
Labels: rn/none

#15390 Fix llama-index cross version test
  tests/llama_index/test_llama_index_tracer.py
Labels: rn/none

#15371 Added allow_missing parameter in load_prompt
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
  tests/tracking/test_client.py
Labels: rn/feature, area/model-registry

#15393 Fix whisper example
  examples/transformers/whisper.py
Labels: rn/none

#15368 Remove deprecated code_path argument in MLflow 3
  mlflow/pyfunc/__init__.py
  mlflow/utils/model_utils.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/breaking-change, area/tracking

#15366 Remove deprecated tags in MLflow 3
  mlflow/projects/utils.py
  mlflow/utils/mlflow_tags.py
  tests/projects/test_projects.py
Labels: rn/none, area/tracking

#15394 Handle null delta in openai autolog
  mlflow/openai/_openai_autolog.py
Labels: rn/none

#15343 Remove 'higher_is_better` args in evaluation validation metricThreshold
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/validation.py
Labels: rn/breaking-change, area/scoring

#15391 Sync
  .github/workflows/master.yml
  CONTRIBUTING.md
  docs/docusaurus.config.ts
  docs/scripts/build-all.py
  docs/sidebars.ts
  mlflow/optuna/__init__.py
  mlflow/optuna/storage.py
  mlflow/pyfunc/utils/data_validation.py
  mlflow/pyspark/optuna/__init__.py
  tests/langchain/test_langchain_evaluation.py
  tests/optuna/test_storage.py
  tests/pyfunc/test_pyfunc_model_with_type_hints.py
Labels: rn/none

#14971 Update langchain_tracer for serializing invocation params when using Structured Output + Unit test
  mlflow/langchain/langchain_tracer.py
  tests/langchain/test_langchain_tracer.py
Labels: rn/bug-fix, area/uiux, area/tracking

#15380 [Tracing SDK][2] Split yaml utils from file_utils.py
  mlflow/models/container/__init__.py
  mlflow/store/artifact/models_artifact_repo.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/tracking/file_store.py
  mlflow/utils/file_utils.py
  mlflow/utils/yaml_utils.py
  tests/helper_functions.py
  tests/projects/test_virtualenv_projects.py
  tests/store/model_registry/test_file_store.py
  tests/store/tracking/test_file_store.py
  tests/utils/test_file_utils.py
  tests/utils/test_yaml_utils.py
Labels: rn/none, area/tracking, v2.21.4

#15399 Ignore `tests/optuna` in `.github/workflows/protobuf-cross-test.yml`
  .github/workflows/master.yml
  .github/workflows/protobuf-cross-test.yml
Labels: rn/none

#15365 Remove deprecated MLFLOW_GCS_DEFAULT_TIMEOUT config
  docs/docs/tracking/artifacts-stores/index.mdx
  mlflow/environment_variables.py
  mlflow/store/artifact/gcs_artifact_repo.py
Labels: rn/breaking-change, area/tracking

#15362 Remove `baseline_model` and relevant arguments in evaluate API
  mlflow/models/evaluation/base.py
  tests/evaluate/test_validation.py
Labels: rn/breaking-change, area/tracking

#15369 Remove torch flavor requirements_file argument
  mlflow/pytorch/__init__.py
  tests/pytorch/test_pytorch_model_export.py
Labels: rn/breaking-change, area/tracking

#15299 Migrate `TraceData` to v3 format
  mlflow/entities/trace.py
  mlflow/entities/trace_data.py
  mlflow/tracing/trace_manager.py
  tests/entities/test_trace.py
  tests/entities/test_trace_data.py
  tests/evaluate/test_evaluation.py
  tests/tracing/test_fluent.py
Labels: rn/none

#15397 Handle request error in hugging hub health check
  tests/helper_functions.py
Labels: rn/none

#15392 Remove confusing docstring in `parse_prompt_uri`
  mlflow/tracking/client.py
Labels: rn/none

#15400 Simplify DSPy example code
  docs/docs/llms/dspy/optimizer.mdx
Labels: rn/none, v2.21.0

#15404 Add lint rule for empty cell
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  docs/docs/llms/llm-evaluate/notebooks/question-answering-evaluation.ipynb
  docs/docs/llms/llm-evaluate/notebooks/rag-evaluation.ipynb
  docs/docs/llms/rag/notebooks/retriever-evaluation-tutorial.ipynb
  docs/docs/traditional-ml/hyperparameter-tuning-with-child-runs/notebooks/parent-child-runs.ipynb
  examples/evaluation/qa-evaluation.ipynb
  examples/evaluation/rag-evaluation.ipynb
  examples/h2o/random_forest.ipynb
  examples/llms/RAG/retriever-evaluation-tutorial.ipynb
  examples/rapids/mlflow_project/notebooks/rapids_mlflow.ipynb
  examples/sklearn_elasticnet_wine/train.ipynb
Labels: rn/none

#15395 Fix bert pytorch example
  examples/pytorch/BertNewsClassification/python_env.yaml
Labels: rn/none

#15377 Support linking traces in evaluate to active model
  mlflow/models/evaluation/base.py
  tests/evaluate/test_evaluation.py
Labels: rn/none

#15406 Sync
  .github/workflows/master.yml
  .github/workflows/protobuf-cross-test.yml
  dev/clint/src/clint/linter.py
  dev/clint/src/clint/rules.py
  docs/docs/llms/dspy/optimizer.mdx
  docs/docs/llms/llm-evaluate/notebooks/question-answering-evaluation.ipynb
  docs/docs/llms/llm-evaluate/notebooks/rag-evaluation.ipynb
  docs/docs/llms/rag/notebooks/retriever-evaluation-tutorial.ipynb
  docs/docs/traditional-ml/hyperparameter-tuning-with-child-runs/notebooks/parent-child-runs.ipynb
  examples/evaluation/qa-evaluation.ipynb
  examples/evaluation/rag-evaluation.ipynb
  examples/h2o/random_forest.ipynb
  examples/llms/RAG/retriever-evaluation-tutorial.ipynb
  examples/pytorch/BertNewsClassification/python_env.yaml
  examples/rapids/mlflow_project/notebooks/rapids_mlflow.ipynb
  examples/sklearn_elasticnet_wine/train.ipynb
  examples/transformers/whisper.py
  mlflow/langchain/langchain_tracer.py
  mlflow/openai/_openai_autolog.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
  tests/helper_functions.py
  tests/langchain/test_langchain_tracer.py
  tests/llama_index/test_llama_index_tracer.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
  tests/tracking/test_client.py
Labels: rn/none

#15361 Remove evaluator custom_metrics arg in MLflow 3
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/default_evaluator.py
  tests/evaluate/test_default_evaluator.py
  tests/evaluate/test_evaluation.py
Labels: rn/breaking-change, area/scoring

#15408 MLflow 3.0 docs (#15078)
  docs/docs/mlflow-3/deep-learning.mdx
  docs/docs/mlflow-3/genai-agent.mdx
  docs/docs/mlflow-3/index.mdx
  docs/sidebars.ts
  docs/static/images/mlflow-3/deep-learning/logged_models.png
  docs/static/images/mlflow-3/deep-learning/model_artifacts.png
  docs/static/images/mlflow-3/deep-learning/run_page.png
  docs/static/images/mlflow-3/genai/chatbot_prompt.png
  docs/static/images/mlflow-3/genai/evaluate_metrics.png
  docs/static/images/mlflow-3/genai/logged_model_autolog_traces.png
  docs/static/images/mlflow-3/genai/logged_model_page.png
  docs/static/images/mlflow-3/genai/logged_models_tab.png
  docs/static/images/mlflow-3/simple_example_model.png
  docs/static/images/mlflow-3/simple_example_models_tab.png
  docs/static/images/mlflow-3/simple_example_run_page.png
  docs/static/images/mlflow-3/simple_example_traces.png
Labels: rn/none

#15381 Add `to_predict_fn` API to convert endpoint URI to a callable
  mlflow/genai/__init__.py
  mlflow/genai/evaluation/__init__.py
  mlflow/genai/evaluation/base.py
  mlflow/genai/evaluation/utils.py
  tests/genai/evaluate/test_evaluation.py
Labels: rn/feature, area/tracking, autoformat

#15403 Update `TraceInfoV3.to_dict` to serialize `execution_duration` as int for JSON representation for inference tables
  mlflow/entities/trace_info_v3.py
  tests/entities/test_trace.py
  tests/entities/test_trace_info_v3.py
  tests/tracing/export/test_inference_table_exporter.py
Labels: rn/none

#15374 Add Scorer base class and scorer decorator
  .github/workflows/master.yml
  mlflow/entities/trace_data.py
  mlflow/genai/evaluation/base.py
  mlflow/genai/evaluation/utils.py
  mlflow/genai/scorers/base.py
  mlflow/genai/utils/trace_utils.py
  mlflow/tracing/utils/__init__.py
  pyproject.toml
  tests/genai/test_scorer.py
  tests/genai/utils/test_trace_utils.py
  tests/tracing/utils/test_utils.py
Labels: rn/none, area/scoring, area/tracking

#15119 Introduce ResponsesAgent
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/loaders/__init__.py
  mlflow/pyfunc/loaders/code_model.py
  mlflow/pyfunc/loaders/responses_agent.py
  mlflow/pyfunc/model.py
  mlflow/types/responses.py
  mlflow/types/responses_helpers.py
  tests/pyfunc/test_responses_agent.py
  tests/pyfunc/test_responses_agent_validation.py
Labels: rn/none, area/models, v2.21.4, v2.22.0

#15413 Fix `LoggedModel` api links in mlflow-3 preview page
  docs/docs/mlflow-3/index.mdx
  docs/src/components/APILink/index.tsx
Labels: rn/none

#15417 Construct non-hex digits filename uuid for step-wise image name
  mlflow/tracking/client.py
  tests/tracking/test_mlflow_artifacts.py
Labels: rn/none, v2.22.0

#15315 Remove `set_pb_value` and `parse_pb_value`
  mlflow/entities/assessment.py
  mlflow/entities/span.py
  mlflow/entities/span_event.py
  mlflow/store/tracking/rest_store.py
  mlflow/utils/proto_json_utils.py
Labels: rn/none

#15426 Restore `parse_pb_value` and `set_pb_value`
  mlflow/utils/proto_json_utils.py
Labels: rn/none

#12161 Add `trailing-whitespace` in `.pre-commit-config.yaml`
  .pre-commit-config.yaml
  docs/docs/deployment/deploy-model-locally/index.mdx
  docs/docs/getting-started/databricks-trial/index.mdx
  docs/docs/getting-started/index.mdx
  docs/docs/getting-started/running-notebooks/index.mdx
  docs/docs/getting-started/tracking-server-overview/index.mdx
  docs/docs/llms/dspy/optimizer.mdx
  docs/docs/llms/index.mdx
  docs/docs/llms/langchain/autologging.mdx
  docs/docs/llms/langchain/guide/index.mdx
  docs/docs/llms/llm-evaluate/notebooks/index.mdx
  docs/docs/model/dependencies/index.mdx
  docs/docs/model/index.mdx
  docs/docs/model/python_model.mdx
  docs/docs/model/signatures/index.mdx
  docs/docs/projects/index.mdx
  docs/docs/recipes/index.mdx
  docs/docs/search-runs/index.mdx
  docs/docs/tracing/api/how-to.mdx
  docs/docs/tracing/api/index.mdx
  docs/docs/tracing/integrations/gemini.mdx
  docs/docs/tracing/tracing-schema.mdx
  docs/docs/tracking/index.mdx
Labels: rn/none

#15420 Sync
  mlflow/entities/assessment.py
  mlflow/entities/span.py
  mlflow/entities/span_event.py
  mlflow/store/tracking/rest_store.py
  mlflow/utils/proto_json_utils.py
Labels: rn/none

#15396 Increase traceinfo tag value limit
  mlflow/entities/trace_info.py
  mlflow/tracing/constant.py
  mlflow/tracing/processor/mlflow.py
  tests/entities/test_trace_info.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracing/processor/test_mlflow_processor.py
Labels: rn/none, v2.22.0

#15376 Expose scorers
  mlflow/genai/scorers/__init__.py
  mlflow/genai/scorers/builtin_scorers.py
  tests/genai/scorers/test_builtin_scorers.py
Labels: rn/feature, area/tracking

#15422 [tensorflow] Link metrics to LoggedModels in autologging
  mlflow/tensorflow/__init__.py
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/none

#13991 Enable RUF003 to avoid ambiguous unicode characters in comments
  mlflow/utils/requirements_utils.py
  pyproject.toml
  tests/db/test_tracking_operations.py
  tests/tracing/test_fluent.py
Labels: rn/none, v2.21.4

#15436 Remove legacy Databricks exporter
  mlflow/tracing/export/databricks_agent_legacy.py
  mlflow/tracing/provider.py
  tests/tracing/export/test_databricks_agent_legacy_exporter.py
  tests/tracing/test_provider.py
Labels: rn/none, area/tracking

#15444 Sync
  .pre-commit-config.yaml
  docs/docs/deployment/deploy-model-locally/index.mdx
  docs/docs/getting-started/databricks-trial/index.mdx
  docs/docs/getting-started/index.mdx
  docs/docs/getting-started/running-notebooks/index.mdx
  docs/docs/getting-started/tracking-server-overview/index.mdx
  docs/docs/llms/dspy/optimizer.mdx
  docs/docs/llms/index.mdx
  docs/docs/llms/langchain/autologging.mdx
  docs/docs/llms/langchain/guide/index.mdx
  docs/docs/llms/llm-evaluate/notebooks/index.mdx
  docs/docs/mlflow-3/genai-agent.mdx
  docs/docs/mlflow-3/index.mdx
  docs/docs/model/dependencies/index.mdx
  docs/docs/model/index.mdx
  docs/docs/model/python_model.mdx
  docs/docs/model/signatures/index.mdx
  docs/docs/projects/index.mdx
  docs/docs/search-runs/index.mdx
  docs/docs/tracing/api/how-to.mdx
  docs/docs/tracing/api/index.mdx
  docs/docs/tracing/integrations/gemini.mdx
  docs/docs/tracing/tracing-schema.mdx
  docs/docs/tracking/index.mdx
  mlflow/entities/trace_info.py
  mlflow/entities/trace_info_v3.py
  mlflow/tracing/constant.py
  mlflow/tracing/processor/mlflow.py
  tests/entities/test_trace_info.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracing/processor/test_mlflow_processor.py
Labels: rn/none

#15423 [pytorch] Link metrics to LoggedModels in autologging
  mlflow/pytorch/_lightning_autolog.py
  mlflow/utils/autologging_utils/__init__.py
  tests/pytorch/test_pytorch_autolog.py
Labels: rn/none

#15442 Avoid top-level `databricks.sdk` imports
  dev/clint/src/clint/linter.py
  mlflow/store/artifact/databricks_sdk_models_artifact_repo.py
  pyproject.toml
Labels: rn/none, v2.20.0

#15424 [keras] Link metrics to LoggedModels in autologging
  mlflow/keras/autologging.py
  mlflow/keras/callback.py
  tests/keras/test_autolog.py
Labels: rn/none

#15322 Remove example_no_conversion param
  docs/docs/llms/transformers/tutorials/text-generation/text-generation.ipynb
  docs/docs/model/signatures/index.mdx
  mlflow/langchain/__init__.py
  mlflow/models/utils.py
  mlflow/openai/__init__.py
  mlflow/promptflow/__init__.py
  mlflow/pyfunc/__init__.py
  mlflow/sentence_transformers/__init__.py
  mlflow/transformers/__init__.py
  mlflow/utils/docstring_utils.py
Labels: rn/breaking-change, area/tracking

#15387 Rename `request_id` to `trace_id`
  docs/docs/mlflow-3/genai-agent.mdx
  docs/docs/mlflow-3/index.mdx
  docs/docs/tracing/api/client.mdx
  docs/docs/tracing/api/how-to.mdx
  docs/docs/tracing/api/search.mdx
  docs/docs/tracing/tracing-schema.mdx
  docs/docs/tracing/ui.mdx
  examples/tracing/client.py
  examples/tracing/multithreading.py
  mlflow/autogen/autogen_logger.py
  mlflow/entities/span.py
  mlflow/entities/trace.py
  mlflow/entities/trace_info.py
  mlflow/langchain/langchain_tracer.py
  mlflow/llama_index/tracer.py
  mlflow/openai/_openai_autolog.py
  mlflow/tracing/fluent.py
  mlflow/tracing/utils/__init__.py
  mlflow/tracing/utils/warning.py
  mlflow/tracking/client.py
  tests/entities/test_span.py
  tests/entities/test_trace_data.py
  tests/tracing/export/test_inference_table_exporter.py
  tests/tracing/export/test_mlflow_exporter.py
  tests/tracing/processor/test_inference_table_processor.py
  tests/tracing/processor/test_mlflow_processor.py
  tests/tracing/test_fluent.py
  tests/tracing/test_trace_manager.py
  tests/tracing/utils/test_utils.py
  tests/tracing/utils/test_warning.py
  tests/tracking/test_client.py
  tests/tracking/test_rest_tracking.py
Labels: rn/breaking-change, area/tracking

#15415 Remove inference config for transformers flavor in MLflow 3
  mlflow/transformers/__init__.py
Labels: rn/breaking-change, area/tracking

#15412 Remove `every_n_iter` param in tensorflow autologging in MLflow 3
  docs/docs/deep-learning/tensorflow/guide/index.mdx
  mlflow/tensorflow/__init__.py
  tests/tensorflow/test_tensorflow2_autolog.py
Labels: rn/breaking-change, area/tracking

#15459 Enable ruff n804
  mlflow/entities/assessment.py
  mlflow/gateway/providers/openai.py
  mlflow/tracing/trace_manager.py
  pyproject.toml
Labels: rn/none, area/build

#12902 Emit a warning for `mlflow.get_artifact_uri()` usage outside active run
  mlflow/tracking/fluent.py
Labels: rn/breaking-change, area/tracking

#15463 Fix missing assessment propagation in `TraceInfo.to_v3`
  mlflow/entities/trace_info.py
  tests/tracing/test_assessment.py
Labels: rn/none, area/tracking

#15449 [paddle] Link metrics to LoggedModels in autologging
  mlflow/paddle/_paddle_autolog.py
  tests/paddle/test_paddle_autolog.py
Labels: rn/none

#15450 [statsmodels] Link metrics to LoggedModels in autologging
  mlflow/statsmodels/__init__.py
  tests/statsmodels/test_statsmodels_autolog.py
Labels: rn/none

#15446 Update auth for logged models
  mlflow/server/auth/__init__.py
  mlflow/server/handlers.py
  tests/server/auth/test_auth.py
Labels: rn/none

#15433 [Tracing SDK][3] Make fluent/client APIs work in light-weight tracing SDK
  conftest.py
  mlflow/__init__.py
  mlflow/entities/trace_info.py
  mlflow/store/artifact/models_artifact_repo.py
  mlflow/tracing/destination.py
  mlflow/tracing/fluent.py
  mlflow/tracing/utils/__init__.py
  mlflow/tracking/__init__.py
  mlflow/tracking/_tracking_service/utils.py
  mlflow/tracking/fluent.py
  mlflow/types/__init__.py
  mlflow/utils/autologging_utils/__init__.py
  mlflow/utils/autologging_utils/client.py
  mlflow/utils/autologging_utils/safety.py
  mlflow/utils/mime_type_utils.py
  mlflow/utils/uri.py
  mlflow/utils/validation.py
  mlflow/version.py
  tests/autologging/test_autologging_client.py
  tests/conftest.py
  tests/dev/test_update_mlflow_versions.py
  tests/tracing/display/test_ipython.py
  tests/tracing/export/test_databricks_agent_legacy_exporter.py
  tests/tracing/export/test_databricks_exporter.py
  tests/tracing/helper.py
  tests/tracing/processor/test_inference_table_processor.py
  tests/tracing/processor/test_mlflow_processor.py
  tests/tracing/test_assessment.py
  tests/tracing/test_fluent.py
  tests/tracing/test_provider.py
  tests/tracing/utils/test_timeout.py
  tests/tracing/utils/test_utils.py
  tests/tracking/test_tracking.py
Labels: rn/none, area/tracking

#15443 Add prefix to model id and show kind error message from load_model
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/artifact_utils.py
  tests/tracking/test_artifact_utils.py
Labels: rn/none
