Repository mlflow/mlflow, pull requests merged in 2025-05, with the labels that each got.

#15559 Migrate `UCVolumesArtifactRepository` to use `DatabricksSdkArtifactRepository`
  mlflow/store/artifact/databricks_sdk_artifact_repo.py
  mlflow/store/artifact/uc_volume_artifact_repo.py
  tests/store/artifact/test_uc_volumes_artifact_repo.py
Labels: rn/none

#15576 Avoid llama-index-core 0.12.34
  requirements/constraints.txt
Labels: rn/none

#15545 Remove temp mlflow requirement for dev
  mlflow/utils/environment.py
Labels: rn/none

#15575 Fix a bug where `databricks-sdk` doesn't set `multipart_upload_chunk_size` parameter
  mlflow/store/artifact/databricks_sdk_artifact_repo.py
Labels: rn/none

#14790 Add Calibration Plots to Default Classifier Evaluator
  mlflow/models/evaluation/calibration_curve.py
  mlflow/models/evaluation/evaluators/classifier.py
  tests/evaluate/test_default_evaluator.py
Labels: rn/none, area/models, v2.20.4, v2.22.1

#15577 Avoid using `NULLS LAST` when sorting logged models for MySQL
  .github/workflows/master.yml
  mlflow/store/tracking/sqlalchemy_store.py
  tests/conftest.py
  tests/db/compose.yml
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#15581 Client + Server Communication Issue: Handle New Response Proto (GetTraceInfoV3)
  mlflow/store/tracking/rest_store.py
  tests/store/tracking/test_rest_store.py
Labels: rn/none, area/tracking

#15578 list asynchnorous API as supported
  mlflow/anthropic/__init__.py
Labels: rn/none

#15569 Simplify PIP_CONSTRAINT value using ${{ github.workspace }}
  .github/workflows/cross-version-tests.yml
  .github/workflows/gateway.yml
  .github/workflows/lint.yml
  .github/workflows/master.yml
  .github/workflows/slow-tests.yml
Labels: rn/none

#15584 Bump version to 3.0.0.dev0
  mlflow/R/mlflow/DESCRIPTION
  mlflow/java/client/pom.xml
  mlflow/java/pom.xml
  mlflow/java/spark/pom.xml
  mlflow/server/js/src/common/constants.tsx
  mlflow/utils/environment.py
  mlflow/version.py
  pyproject.release.toml
  pyproject.toml
  skinny/pyproject.toml
Labels: rn/none, area/tracking

#15574 create mlflow tracing for smolagents
  conftest.py
  docs/api_reference/source/python_api/mlflow.smolagents.rst
  docs/docs/tracing/index.mdx
  docs/docs/tracing/integrations/index.mdx
  docs/docs/tracing/integrations/smolagents.mdx
  docs/static/images/llms/smolagents/smolagents-tracing.png
  docs/static/images/logos/smolagents-logo.png
  examples/smolagents/tracing.py
  mlflow/__init__.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/smolagents/__init__.py
  mlflow/smolagents/autolog.py
  mlflow/smolagents/chat.py
  mlflow/tracking/fluent.py
  tests/smolagents/test_smolagents_autolog.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/feature, area/tracking

#15587 Support setting databricks auth profile by 'DATABRICKS_CONFIG_PROFILE' environ variable.
  mlflow/utils/databricks_utils.py
Labels: rn/feature, area/tracking, v2.22.1

#15437 Support tracing ResponsesAgent predict
  mlflow/openai/utils/chat_schema.py
  mlflow/tracing/fluent.py
  mlflow/tracing/utils/__init__.py
  tests/pyfunc/test_responses_agent.py
Labels: rn/none, area/tracking

#15593 Mandate source ID for assessments
  mlflow/entities/assessment_source.py
  mlflow/tracing/assessment.py
  tests/entities/test_assessment.py
  tests/tracing/test_assessment.py
Labels: rn/none, area/tracking

#15566 Fix cross version test for crewai 0.117
  tests/crewai/test_crewai_autolog.py
Labels: rn/none, area/tracking, v2.22.1

#15580 Migrate DB offline tracing to V3 API
  mlflow/tracing/export/mlflow_v2.py
  mlflow/tracing/export/mlflow_v3.py
  mlflow/tracing/processor/base_mlflow.py
  mlflow/tracing/processor/databricks.py
  mlflow/tracing/processor/mlflow_v2.py
  mlflow/tracing/processor/mlflow_v3.py
  mlflow/tracing/provider.py
  mlflow/utils/databricks_utils.py
  tests/tracing/export/test_mlflow_v2_exporter.py
  tests/tracing/export/test_mlflow_v3_exporter.py
  tests/tracing/helper.py
  tests/tracing/processor/test_mlflow_v2_processor.py
  tests/tracing/processor/test_mlflow_v3_processor.py
  tests/tracing/test_fluent.py
  tests/tracing/test_provider.py
Labels: rn/none, area/tracking

#15573 Update scorer return types to include int, list[Assessment]
  mlflow/genai/evaluation/base.py
  mlflow/genai/scorers/base.py
Labels: rn/none, area/tracking

#15598 Fix Spark cross tests
  tests/spark/test_spark_model_export.py
Labels: rn/none, area/build

#15543 Update return for mlflow.genai.evaluate()
  mlflow/genai/evaluation/base.py
Labels: rn/none

#15602 Update to 3.0 endpoints
  mlflow/store/tracking/rest_store.py
  mlflow/utils/rest_utils.py
  tests/store/tracking/test_rest_store.py
Labels: rn/none, area/tracking

#15589 Support V3 trace dual write from model serving endpoint
  mlflow/entities/trace_info.py
  mlflow/environment_variables.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracing/client.py
  mlflow/tracing/export/inference_table.py
  mlflow/tracing/export/mlflow_v3.py
  mlflow/tracing/processor/inference_table.py
  mlflow/tracing/processor/mlflow_v3.py
  mlflow/tracing/provider.py
  mlflow/tracing/utils/__init__.py
  mlflow/utils/databricks_utils.py
  tests/dspy/test_dspy_autolog.py
  tests/langchain/test_langchain_autolog.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracing/export/test_inference_table_exporter.py
  tests/tracing/processor/test_inference_table_processor.py
  tests/tracing/test_fluent.py
  tests/tracing/utils/test_utils.py
Labels: rn/none, area/tracking

#15567 Fix typo in DatabricksUCConnection
  mlflow/models/resources.py
Labels: rn/none, v2.22.1

#15606 Connect `model_id` to the traces created by `mlflow.genai.evaluate`
  mlflow/genai/evaluation/base.py
  tests/genai/evaluate/test_evaluation.py
  tests/genai/scorers/test_builtin_scorers.py
Labels: rn/none, area/tracking, integrations/databricks, v2.22.1

#15597 Remove unnecessary export of get_default_pip_requirements and get_default_conda_env
  mlflow/dspy/__init__.py
  mlflow/langchain/__init__.py
  mlflow/llama_index/__init__.py
  mlflow/openai/__init__.py
  mlflow/utils/docstring_utils.py
Labels: rn/none, area/tracking

#15607 Update genai example to langchain
  docs/docs/mlflow-3/genai-agent.mdx
  docs/docs/mlflow-3/index.mdx
  docs/static/images/mlflow-3/genai/chatbot_prompt.png
  docs/static/images/mlflow-3/genai/evaluate_metrics.png
  docs/static/images/mlflow-3/genai/logged_model_autolog_traces.png
  docs/static/images/mlflow-3/genai/logged_model_page.png
  docs/static/images/mlflow-3/genai/logged_models_tab.png
Labels: rn/none

#15553 PydanticAI Autologging
  conftest.py
  docs/api_reference/source/python_api/mlflow.pydantic_ai.rst
  docs/docs/tracing/index.mdx
  docs/docs/tracing/integrations/index.mdx
  docs/docs/tracing/integrations/pydantic_ai.mdx
  docs/static/images/llms/pydantic-ai/pydanticai-mcp-tracing.png
  docs/static/images/llms/pydantic-ai/pydanticai-tracing.png
  docs/static/images/logos/pydanticai-logo.png
  examples/pydanticai/tracing.py
  mlflow/__init__.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  mlflow/pydantic_ai/__init__.py
  mlflow/pydantic_ai/autolog.py
  mlflow/tracking/fluent.py
  tests/pydantic_ai/test_pydanticai_fluent_tracing.py
  tests/pydantic_ai/test_pydanticai_mcp_tracing.py
  tests/pydantic_ai/test_pydanticai_tracing.py
  tests/tracking/fluent/test_fluent_autolog.py
Labels: rn/feature, area/tracking

#15601 ResponsesAgent interface update
  mlflow/openai/utils/chat_schema.py
  mlflow/pyfunc/__init__.py
  mlflow/pyfunc/loaders/responses_agent.py
  mlflow/pyfunc/model.py
  mlflow/tracing/utils/__init__.py
  mlflow/types/responses.py
  tests/pyfunc/test_responses_agent.py
  tests/pyfunc/test_responses_agent_validation.py
Labels: rn/documentation, area/models, v2.22.1

#15533 Update mlflow-3 quickstart
  docs/docs/mlflow-3/index.mdx
  docs/static/images/mlflow-3/ai_assistant_prompt.png
  docs/static/images/mlflow-3/simple_example_traces.png
Labels: rn/none

#15558 Add examples to logged models APIs
  mlflow/tracking/fluent.py
Labels: rn/none

#15617 Fix Logged Model Failed Status from Proto
  mlflow/entities/logged_model_status.py
Labels: rn/none, area/tracking

#15613 replace deprecated `mlflow deployments start-server` with `mlflow gateway start`
  dev/server.py
Labels: rn/none, v2.22.1

#15069 Gemini AI Gateway - Chat completion and completion + Unit Test
  docs/docs/llms/deployments/index.mdx
  examples/gateway/gemini/README.md
  examples/gateway/gemini/config.yaml
  examples/gateway/gemini/example.py
  mlflow/gateway/providers/gemini.py
  tests/gateway/providers/test_gemini.py
Labels: rn/feature

#15621 Replace deployments start-server with gateway start
  examples/gateway/huggingface/README.md
  examples/llama_index/workflow/data/mlflow_qa_dataset.csv
Labels: rn/none, v2.22.1

#15622 Update `install-skinny.sh` to allow installation from master branch
  .github/workflows/advice.js
  dev/install-skinny.sh
Labels: rn/none

#15608 Add final touches to mlflow.genai.evaluate
  mlflow/genai/evaluation/base.py
  mlflow/genai/evaluation/utils.py
  mlflow/genai/scorers/__init__.py
  mlflow/genai/scorers/base.py
  mlflow/genai/scorers/builtin_scorers.py
  tests/genai/test_scorer.py
Labels: rn/none, area/tracking

#15624 Add `log_model_artifact` to client
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  tests/tracking/test_client.py
Labels: rn/none

#15627 Add a section listing logged model APIs
  docs/api_reference/source/python_api/mlflow.rst
Labels: rn/none

#15619 Fix `is_model_traced`
  mlflow/genai/evaluation/base.py
  mlflow/genai/evaluation/utils.py
  mlflow/genai/utils/trace_utils.py
  tests/genai/evaluate/test_evaluation.py
  tests/genai/evaluate/test_utils.py
  tests/genai/utils/test_trace_utils.py
Labels: rn/none, area/tracking

#14700 Add compression to pyfunc log model
  mlflow/environment_variables.py
  mlflow/pyfunc/model.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/feature, area/models, v2.21.1, v2.21.4, v2.22.1

#15638 Replace `artifact_path` with `name` in sklearn autolog
  mlflow/sklearn/__init__.py
Labels: rn/none

#15640 Do not include metrics, tags, and params in `LoggedModel.__repr__`
  mlflow/entities/logged_model.py
Labels: rn/none

#15642 Update `request_id` argument in `mlflow.set_trace_tag`/`m,lflow.delete_trace_tag` APIs
  mlflow/tracing/fluent.py
  tests/tracing/test_fluent.py
Labels: rn/none, area/tracking

#15639 Validate run_id passed to search_traces() exist in the experiment
  mlflow/tracing/client.py
  tests/tracing/test_fluent.py
Labels: rn/none, area/tracking

#15605 Fix span event timestamp doc
  mlflow/entities/span_event.py
Labels: rn/none, area/tracking

#15612 Fix predict premission issue
  mlflow/models/python_api.py
  mlflow/utils/virtualenv.py
Labels: rn/none, v2.22.1

#15647 Remove unnecessary `logging.basicConfig(level=logging.INFO)`
  mlflow/tracing/export/async_export_queue.py
Labels: rn/none

#15649 Remove skip marker in `tests/store/artifact/test_databricks_artifact_repo.py`
  mlflow/store/artifact/databricks_artifact_repo_resources.py
  tests/store/artifact/test_databricks_artifact_repo.py
Labels: rn/none

#15645 Fix logged model status during model logging
  mlflow/models/model.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/fluent.py
  tests/models/test_model.py
  tests/store/tracking/test_file_store_logged_model.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/test_rest_tracking.py
Labels: rn/none

#15651 Allow `finalize_logged_model` to accept str as `status`
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/none

#15616 Fix Search Logged Models Fluent to use Max Results
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/none, area/tracking

#15637 Reuse a single empty OTEL Resource in Span.from_dict to cut search_tr…
  mlflow/entities/span.py
Labels: rn/none, area/tracking, v2.22.1

#15648 Avoid using short timeout for trace logging for read path
  mlflow/environment_variables.py
  mlflow/store/artifact/databricks_artifact_repo.py
  mlflow/store/artifact/databricks_artifact_repo_resources.py
  mlflow/utils/rest_utils.py
Labels: rn/none, area/tracking

#15634 Trace search: Avoid spawning threads for span fetching if include_spans=False
  mlflow/tracing/client.py
Labels: rn/bug-fix, area/tracking

#15635 [MLflow 2.x] Trace search: Avoid spawning threads for span fetching if include_spans=False
  mlflow/tracking/_tracking_service/client.py
Labels: rn/bug-fix, area/tracking

#15644 Import genai module at top level
  mlflow/__init__.py
  mlflow/genai/__init__.py
  mlflow/genai/evaluation/utils.py
  mlflow/genai/scorers/base.py
  tests/genai/evaluate/test_evaluation.py
  tests/genai/evaluate/test_utils.py
  tests/genai/test_scorer.py
Labels: rn/none, area/tracking

#15620 Fix dict->pandas conversion for GenAI eval API
  mlflow/genai/evaluation/base.py
  mlflow/genai/evaluation/utils.py
  tests/genai/evaluate/test_utils.py
Labels: rn/none, area/tracking

#15633 Print a link to a UC registered model when logging it
  mlflow/models/model.py
  mlflow/utils/databricks_utils.py
  tests/models/test_model.py
  tests/utils/test_databricks_utils.py
Labels: rn/none, area/model-registry, v2.22.1

#15594 Support complex types for expectation assessment value
  mlflow/entities/assessment.py
  mlflow/java/client/src/main/java/org/mlflow/api/proto/Assessments.java
  mlflow/protos/assessments.proto
  mlflow/protos/assessments_pb2.py
  mlflow/tracing/assessment.py
  tests/entities/test_assessment.py
Labels: rn/none, area/tracking

#15668 Disable `runs:/<run_id>/artifact` warning
  mlflow/store/artifact/runs_artifact_repo.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/none

#15445 Added search prompts function to list all the prompts registered
  docs/docs/prompts/index.mdx
  mlflow/__init__.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/tracking/client.py
  tests/tracking/test_client.py
Labels: rn/feature, area/model-registry

#15658 Remove `document_recall` metric
  mlflow/genai/scorers/__init__.py
  mlflow/genai/scorers/builtin_scorers.py
  tests/genai/scorers/test_builtin_scorers.py
Labels: rn/none, area/tracking

#15623 Fix set active model during model loading
  mlflow/dspy/load.py
  mlflow/langchain/model.py
  mlflow/llama_index/model.py
  mlflow/models/model.py
  mlflow/openai/model.py
  mlflow/tracking/fluent.py
  tests/dspy/test_dspy_autolog.py
  tests/langchain/test_langchain_autolog.py
  tests/llama_index/test_llama_index_autolog.py
  tests/openai/test_openai_autolog.py
Labels: rn/none

#15675 Check directories passed to `pytest --ignore` and ensure they exist
  .github/workflows/master.yml
  .github/workflows/protobuf-cross-test.yml
  conftest.py
Labels: rn/none

#15664 Change `finalize_logged_model` status type hint to `Literal`
  docs/api_reference/source/conf.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: rn/none

#15669 Add a page for 2.x compatibility details
  docs/docs/mlflow-3/index.mdx
Labels: rn/none

#15657 Use more realistic examples in logged model API docstrings
  mlflow/tracking/fluent.py
Labels: rn/none

#15671 Use `filter_string` when search for models matching `name` or `run_id`
  mlflow/store/artifact/runs_artifact_repo.py
  mlflow/tracking/_model_registry/fluent.py
Labels: rn/none

#15643 Update DataFrame schema returned from `mlflow.search_trace()` to be V3 format
  docs/docs/tracing/api/search.mdx
  mlflow/entities/trace.py
  tests/tracing/test_fluent.py
Labels: rn/breaking-change, area/tracking

#15686 Rename `TraceInfoV3` to `TraceInfo`, `TraceInfo` to `TraceInfoV2`
  mlflow/entities/__init__.py
  mlflow/entities/trace.py
  mlflow/entities/trace_info.py
  mlflow/entities/trace_info_v2.py
  mlflow/entities/trace_info_v3.py
  mlflow/server/handlers.py
  mlflow/store/tracking/abstract_store.py
  mlflow/store/tracking/dbmodels/models.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/rest_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracing/client.py
  mlflow/tracing/processor/base_mlflow.py
  mlflow/tracing/processor/inference_table.py
  mlflow/tracing/processor/mlflow_v2.py
  mlflow/tracing/processor/mlflow_v3.py
  mlflow/tracing/processor/otel.py
  mlflow/tracing/trace_manager.py
  mlflow/tracing/utils/artifact_utils.py
  tests/entities/test_trace_info.py
  tests/entities/test_trace_info_v3.py
  tests/genai/conftest.py
  tests/server/test_handlers.py
  tests/store/tracking/test_file_store.py
  tests/store/tracking/test_rest_store.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracing/conftest.py
  tests/tracing/export/test_inference_table_exporter.py
  tests/tracing/export/test_mlflow_v3_exporter.py
  tests/tracing/helper.py
  tests/tracing/test_assessment.py
  tests/tracing/test_fluent.py
  tests/tracking/test_client.py
Labels: rn/none

#15653 Fix error when creating deployment jobs
  mlflow/store/_unity_catalog/registry/rest_store.py
Labels: rn/none, area/model-registry, v2.22.1

#15663 Disable async logging in Databricks notebook and increase default queue size limit
  docs/docs/tracing/api/how-to.mdx
  docs/docs/tracing/production.mdx
  mlflow/environment_variables.py
  mlflow/tracing/export/mlflow_v3.py
  tests/tracing/export/test_mlflow_v3_exporter.py
Labels: rn/none

#15590 Deprecate mlflow.evaluations module
  mlflow/evaluation/assessment.py
  mlflow/evaluation/evaluation.py
  mlflow/evaluation/evaluation_tag.py
  mlflow/evaluation/fluent.py
  mlflow/evaluation/utils.py
Labels: rn/none, area/tracking

#15680 Remove `markdown` and `jinja` from mlflow depedencies
  pyproject.release.toml
  pyproject.toml
  requirements/core-requirements.txt
  requirements/core-requirements.yaml
Labels: rn/none

#15702 Fix `ImportError: cannot import name 'MappingProxyType' from 'types' (/home/runner/work/mlflow/mlflow/tests/types/__init__.py)`
  .github/workflows/master.yml
Labels: rn/none

#15673 Do not fetch `mlflow/server/js` in `install-skinny.sh` for fast installation
  dev/install-skinny.sh
Labels: rn/none

#15659 Add Validation for Nonempty Model ID in Logged Model Client APIs
  mlflow/tracking/client.py
  tests/tracking/test_client.py
Labels: rn/none, area/tracking

#15707 Replace gunicorn with uvicorn for docker feature docs
  mlflow/models/cli.py
  mlflow/models/python_api.py
Labels: rn/none, v2.22.1

#15705 Record serving trace metadata
  mlflow/pyfunc/context.py
  mlflow/tracing/processor/inference_table.py
  mlflow/utils/mlflow_tags.py
  tests/tracing/processor/test_inference_table_processor.py
Labels: rn/none, area/tracking

#15650 Record notebook and git metadata in trace metadata
  mlflow/tracing/processor/base_mlflow.py
  mlflow/tracing/utils/environment.py
  mlflow/utils/mlflow_tags.py
  tests/entities/test_trace.py
  tests/tracing/processor/test_mlflow_v2_processor.py
  tests/tracing/utils/test_environment.py
Labels: rn/feature, area/tracking

#15688 Update scorer docstring
  mlflow/genai/scorers/base.py
Labels: rn/none, area/tracking

#15708 Fix file store `delete_logged_model` to delete models with metrics
  mlflow/store/tracking/file_store.py
  tests/store/tracking/test_file_store_logged_model.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#15682 Link metric to active_model
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent.py
  tests/tracking/test_client.py
Labels: rn/none

#15655 Make `inputs` optional in mlflow.genai.evaluate when `trace` is present
  mlflow/genai/evaluation/base.py
  mlflow/genai/evaluation/utils.py
  tests/genai/evaluate/test_evaluation.py
  tests/genai/evaluate/test_utils.py
Labels: rn/none, area/tracking

#15677 Add FAQs page for mlflow 3.0
  docs/changed_pages.py
  docs/docs/mlflow-3/faqs.mdx
  docs/sidebars.ts
Labels: rn/none

#15684 Remove active model id env var set
  mlflow/environment_variables.py
  mlflow/tracking/fluent.py
  mlflow/utils/environment.py
  tests/conftest.py
  tests/models/test_python_api.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/none

#15697 log_feedback(): Use Source
  mlflow/tracing/assessment.py
  tests/tracing/test_assessment.py
Labels: rn/none, area/tracking

#15678 Support predict_stream in dspy flavor
  docs/docs/llms/dspy/index.mdx
  mlflow/dspy/save.py
  mlflow/dspy/wrapper.py
  tests/dspy/test_dspy_autolog.py
  tests/dspy/test_save.py
Labels: rn/feature, area/models, v2.22.1

#15715 Fix mlflow-3 FAQs section
  docs/docs/mlflow-3/faqs.mdx
Labels: rn/none

#15698 Model params create model version
  mlflow/java/client/src/main/java/org/mlflow/api/proto/ModelRegistry.java
  mlflow/protos/databricks_uc_registry_messages.proto
  mlflow/protos/databricks_uc_registry_messages_pb2.py
  mlflow/protos/model_registry.proto
  mlflow/protos/model_registry_pb2.py
  mlflow/server/handlers.py
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/store/model_registry/abstract_store.py
  mlflow/store/model_registry/file_store.py
  mlflow/store/model_registry/rest_store.py
  mlflow/store/model_registry/sqlalchemy_store.py
Labels: rn/none, v2.22.1

#15654 Make builtin scorers callable
  mlflow/genai/scorers/builtin_scorers.py
  tests/genai/test_scorer.py
Labels: rn/none, v2.22.1

#15670 Add `IN` and `NOT IN` support to `search_logged_models filter_string`: sqlalchemy
  mlflow/store/db/utils.py
  mlflow/utils/search_logged_model_utils.py
  tests/store/tracking/test_sqlalchemy_store.py
Labels: rn/none

#15681 Fix smolagents tests
  mlflow/ml-package-versions.yml
  tests/smolagents/test_smolagents_autolog.py
Labels: rn/none

#11773 Improve error handling if tracking uri is not set when running 'mlflow gc'
  mlflow/cli.py
Labels: rn/bug-fix, v2.22.1

#15695 Add code examples in doc strings for scorers
  mlflow/genai/scorers/builtin_scorers.py
Labels: rn/none, area/tracking

#15720 Add `mlflow.genai.rst` to autogenerate API reference
  docs/api_reference/source/conf.py
  docs/api_reference/source/python_api/mlflow.genai.rst
  mlflow/genai/evaluation/base.py
  mlflow/genai/scorers/base.py
  mlflow/genai/scorers/builtin_scorers.py
Labels: rn/none

#15732 Show kind warning for full queue
  mlflow/tracing/export/async_export_queue.py
  tests/tracing/export/test_async_export_queue.py
Labels: rn/none, v2.22.1

#15723 Print a links to logged models and UC registered model versions when they are created
  mlflow/environment_variables.py
  mlflow/models/model.py
  mlflow/tracking/_model_registry/fluent.py
  mlflow/utils/databricks_utils.py
  tests/models/test_model.py
  tests/tracking/_model_registry/test_model_registry_fluent.py
  tests/utils/test_databricks_utils.py
Labels: rn/none, area/tracking, v2.22.1

#15738 Revert "Remove active model id env var set (#15684)"
  mlflow/environment_variables.py
  mlflow/tracking/fluent.py
  mlflow/utils/environment.py
  tests/conftest.py
  tests/models/test_python_api.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/none

#15743 Pin `databricks-agents<0.22.0` in genai tests
  .github/workflows/master.yml
Labels: rn/none

#15735 Fix dict serde for complex assessment objects
  mlflow/entities/assessment.py
  mlflow/entities/trace_info.py
  tests/entities/test_trace_info.py
  tests/entities/test_trace_info_v2.py
  tests/entities/test_trace_info_v3.py
Labels: rn/none, area/tracking

#15636 Update Search Logged Models Docstrings Supported Filter Comparators
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
Labels: rn/none, area/tracking

#15717 Introduce client and fluent APIs for `LogLoggedModelParams`
  docs/api_reference/source/python_api/mlflow.rst
  mlflow/__init__.py
  mlflow/store/tracking/file_store.py
  mlflow/store/tracking/sqlalchemy_store.py
  mlflow/tracking/_tracking_service/client.py
  mlflow/tracking/client.py
  mlflow/tracking/fluent.py
  tests/store/tracking/test_file_store_logged_model.py
  tests/store/tracking/test_sqlalchemy_store.py
  tests/tracking/fluent/test_fluent.py
  tests/tracking/test_rest_tracking.py
Labels: rn/feature, area/tracking

#15660 Pass `inputs` as keyword arguments to the predict_fn
  mlflow/genai/evaluation/base.py
  mlflow/genai/evaluation/utils.py
  mlflow/genai/utils/trace_utils.py
  mlflow/pyfunc/model.py
  tests/genai/evaluate/test_evaluation.py
  tests/genai/evaluate/test_utils.py
  tests/genai/scorers/test_builtin_scorers.py
  tests/genai/test_scorer.py
  tests/genai/utils/test_trace_utils.py
Labels: rn/none, area/tracking

#15728 Fix the termination behavior of AsyncTraceExportQueue
  .github/workflows/tracing.yaml
  mlflow/tracing/export/async_export_queue.py
  tests/tracing/export/test_async_export_queue.py
Labels: rn/none, v2.22.1

#15687 Derive request and expectations from traces
  mlflow/data/pandas_dataset.py
  mlflow/genai/evaluation/base.py
  mlflow/genai/evaluation/constant.py
  mlflow/genai/evaluation/utils.py
  tests/genai/conftest.py
  tests/genai/evaluate/test_evaluation.py
  tests/genai/evaluate/test_utils.py
  tests/genai/test_scorer.py
Labels: rn/none, area/tracking

#15751 Fix `test_model_pip_requirements_pin_numpy_when_pandas_included`
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
Labels: rn/none, area/artifacts

#15748 Fix `Failed to flatten nested params: 'NoneType' object has no attribute 'items'` in log_model
  mlflow/models/model.py
Labels: rn/none

#15750 Increase default number of threads for trace span downloads during search
  mlflow/environment_variables.py
  mlflow/tracing/client.py
Labels: rn/none, area/tracking

#15730 Rename `mlflow.evaluate` to `mlflow.models.evaluate` and show warnings in databricks
  mlflow/__init__.py
  mlflow/genai/evaluation/base.py
  mlflow/models/evaluation/base.py
  mlflow/models/evaluation/deprecated.py
  tests/evaluate/test_deprecated.py
  tests/genai/evaluate/test_evaluation.py
  tests/genai/evaluate/test_utils.py
Labels: rn/none, area/tracking

#15747 Only print out logged model URL when workspace URL is available
  mlflow/models/model.py
Labels: rn/none

#15683 Replace deprecated min_items with min_length
  mlflow/gateway/providers/cohere.py
  mlflow/gateway/schemas/chat.py
  mlflow/types/chat.py
Labels: rn/none, v2.22.1

#15746 Fix `set_experiment` to throw for unexpected error
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/none

#15733 Cast float time to int in Span.to_proto
  mlflow/entities/span.py
Labels: rn/none, area/tracking

#15749 Fix broken link for Seldon Core and update stale serving framework explanation
  docs/docs/deployment/deploy-model-to-kubernetes/index.mdx
Labels: rn/none, v2.22.1

#15753 Fix reset_mlflow_uri fixture
  tests/conftest.py
Labels: rn/none

#15690 Validate required columns for built-in scorers for fail-fast
  mlflow/genai/evaluation/base.py
  mlflow/genai/scorers/builtin_scorers.py
  mlflow/genai/scorers/validation.py
  tests/genai/scorers/test_validation.py
  tests/tracing/helper.py
Labels: rn/none, area/tracking

#15703 treat NOT_GIVEN as “no tools” in _parse_tools
  mlflow/openai/utils/chat_schema.py
  tests/openai/test_openai_autolog.py
Labels: rn/none, area/tracking, v2.22.1

#15742 Print a link to a deployment job when connecting it to a registered model
  mlflow/store/_unity_catalog/registry/rest_store.py
  mlflow/utils/databricks_utils.py
  tests/store/_unity_catalog/model_registry/test_unity_catalog_rest_store.py
  tests/utils/test_databricks_utils.py
Labels: rn/none, area/model-registry, v2.22.1

#15765 Ignore tests/genai in `.github/workflows/requirements.yml`
  .github/workflows/requirements.yml
Labels: rn/none

#15766 Unpin protobuf for onnx `1.1.8`
  mlflow/ml-package-versions.yml
Labels: rn/none

#15676 Tracing: Store trace size in bytes as metadata
  mlflow/tracing/constant.py
  mlflow/tracing/export/inference_table.py
  mlflow/tracing/export/mlflow_v3.py
  mlflow/tracing/utils/__init__.py
  tests/entities/test_trace_info.py
  tests/tracing/export/test_inference_table_exporter.py
  tests/tracing/export/test_mlflow_v3_exporter.py
Labels: rn/none, area/tracking

#15737 Allow passing extra columns to scorer
  mlflow/genai/evaluation/utils.py
  mlflow/genai/scorers/base.py
  tests/genai/conftest.py
  tests/genai/evaluate/test_utils.py
  tests/genai/test_scorer.py
Labels: rn/none, area/tracking

#15745 Fix active model in multi-threads and inference table
  mlflow/environment_variables.py
  mlflow/tracing/processor/base_mlflow.py
  mlflow/tracing/processor/inference_table.py
  mlflow/tracking/fluent.py
  tests/pyfunc/test_model_export_with_class_and_artifacts.py
  tests/tracing/processor/test_inference_table_processor.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/none, v3.0.0

#15771 Fix `mlflow.genai.to_predict_fn` implementation
  mlflow/genai/evaluation/base.py
  tests/genai/evaluate/test_evaluation.py
Labels: rn/none, area/tracking

#15755 Overhaul assessment entities for easier usage
  .github/workflows/master.yml
  docs/api_reference/source/conf.py
  docs/api_reference/source/python_api/mlflow.rst
  mlflow/__init__.py
  mlflow/entities/__init__.py
  mlflow/entities/assessment.py
  mlflow/entities/assessment_source.py
  mlflow/genai/scorers/base.py
  mlflow/tracing/assessment.py
  mlflow/tracing/client.py
  tests/entities/test_assessment.py
  tests/entities/test_trace_info.py
  tests/genai/evaluate/test_evaluation.py
  tests/genai/evaluate/test_utils.py
  tests/genai/test_scorer.py
  tests/store/tracking/test_rest_store.py
  tests/tracing/test_assessment.py
Labels: rn/none, area/tracking, v2.22.1, v3.0.0

#15770 Use `expectations` field to pass expectations to the eval harness
  mlflow/genai/evaluation/utils.py
  mlflow/genai/scorers/builtin_scorers.py
  mlflow/genai/scorers/dummy_builtin_scorer.py
  mlflow/genai/scorers/validation.py
  tests/genai/evaluate/test_utils.py
  tests/genai/scorers/test_validation.py
Labels: rn/none, area/tracking, v3.0.0

#15726 Fix langchain model serving
  mlflow/langchain/api_request_parallel_processor.py
  mlflow/langchain/model.py
  mlflow/tracing/export/inference_table.py
  mlflow/utils/rest_utils.py
  tests/langchain/sample_code/workflow.py
  tests/langchain/test_langchain_model_export.py
Labels: rn/none, v3.0.0

#15768 Relax built-in scorer validation to info message
  mlflow/genai/scorers/builtin_scorers.py
  mlflow/genai/scorers/validation.py
  tests/genai/evaluate/test_evaluation.py
  tests/genai/scorers/test_builtin_scorers.py
  tests/genai/scorers/test_validation.py
Labels: rn/none, area/tracking, v3.0.0

#15756 Introduce `MLFLOW_LOGGING_LEVEL` environment variable
  mlflow/environment_variables.py
  mlflow/utils/logging_utils.py
  tests/utils/test_logging_utils.py
Labels: rn/none, v3.0.0

#15596 Add source argument to from_huggingface method.
  mlflow/data/huggingface_dataset.py
  tests/data/test_huggingface_dataset_and_source.py
Labels: rn/none, v2.22.1

#15769 Unify global_guideline_adherence and guideline_adherence
  mlflow/genai/scorers/__init__.py
  mlflow/genai/scorers/builtin_scorers.py
  tests/genai/scorers/test_builtin_scorers.py
  tests/genai/scorers/test_validation.py
Labels: rn/none, area/tracking, v3.0.0

#15739 Fix update_registered_model for deployment jobs
  mlflow/store/_unity_catalog/registry/rest_store.py
Labels: rn/none, v3.0.0

#15776 Replace yanked spacy version with non-yanked version
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
Labels: rn/none

#15773 Manually update ML package versions before MLflow 3.0 release
  dev/update_ml_package_versions.py
  mlflow/ml-package-versions.yml
  mlflow/ml_package_versions.py
  pyproject.release.toml
  pyproject.toml
  skinny/pyproject.toml
  tests/gemini/test_gemini_autolog.py
  tests/pydantic_ai/test_pydanticai_fluent_tracing.py
  tests/pydantic_ai/test_pydanticai_tracing.py
Labels: rn/none

#15790 Use `team-review` label to trigger team review because `mlflow-automation` account will be removed soon
  .github/workflows/team-review.yml
Labels: rn/none, team-review

#15777 Suppress warnings for retry_after_secs
  mlflow/utils/rest_utils.py
  tests/utils/test_rest_utils.py
Labels: rn/none, v3.0.0

#15772 Support `download_artifacts(run_id=..., artifact_path=...)` to load model artifacts
  mlflow/artifacts/__init__.py
  mlflow/tracking/_tracking_service/client.py
  tests/artifacts/test_artifacts.py
Labels: rn/none

#15775 Manually update dependency versions before MLflow 3.0 release
  pyproject.release.toml
  pyproject.toml
  requirements/core-requirements.txt
  requirements/core-requirements.yaml
Labels: rn/none

#15615 Fix GenAI logging
  mlflow/dspy/load.py
  mlflow/dspy/save.py
  mlflow/langchain/model.py
  mlflow/llama_index/model.py
  mlflow/openai/model.py
  mlflow/utils/autologging_utils/__init__.py
  tests/langgraph/sample_code/langgraph_with_autolog.py
  tests/langgraph/test_langgraph_autolog.py
Labels: rn/none, v3.0.0

#15792 Add @experimental mark to GenAI evaluation APIs
  mlflow/genai/evaluation/base.py
  mlflow/genai/evaluation/utils.py
  mlflow/genai/scorers/base.py
  mlflow/genai/scorers/builtin_scorers.py
  mlflow/models/evaluation/base.py
  tests/genai/evaluate/test_evaluation.py
Labels: rn/none, area/tracking, v3.0.0

#15782 Remove old autoformat command (`@mlflow-automation autoformat`)
  .github/workflows/autoformat.js
Labels: rn/none

#15791 fix column validation for guidelines
  mlflow/genai/scorers/builtin_scorers.py
  tests/genai/scorers/test_validation.py
Labels: rn/none, area/tracking, v3.0.0

#15797 Relax accelerate pin for transformers 4.52.0.dev0
  mlflow/ml-package-versions.yml
Labels: rn/none, enable-dev-tests, team-review

#15793 Remove `mlflow-automation` items in `CHANGELOG`
  CHANGELOG.md
  docs/changed_pages.py
Labels: rn/none, team-review

#15759 Show more helpful warnings for invalid dataset/predict_fn
  mlflow/genai/evaluation/base.py
  mlflow/genai/evaluation/utils.py
  mlflow/genai/utils/data_validation.py
  mlflow/genai/utils/trace_utils.py
  mlflow/tracing/fluent.py
  tests/genai/evaluate/test_evaluation.py
  tests/genai/evaluate/test_utils.py
  tests/genai/utils/test_data_validation.py
  tests/genai/utils/test_trace_utils.py
Labels: rn/none, area/tracking, v3.0.0

#15799 Remove model_id from `start_span`
  mlflow/tracing/fluent.py
  mlflow/tracing/processor/base_mlflow.py
  mlflow/tracking/fluent.py
  tests/tracking/fluent/test_fluent.py
Labels: rn/none, v3.0.0

#15795 Overwrite custom feedback name to scorer name in custom scorer
  mlflow/entities/assessment.py
  mlflow/genai/scorers/base.py
  tests/genai/test_scorer.py
Labels: rn/none, area/tracking

#15740 Update Lighthouse signup and signin links
  docs/docs/getting-started/databricks-trial/index.mdx
  docs/docs/getting-started/index.mdx
  docs/docs/getting-started/running-notebooks/index.mdx
  docs/static/images/tutorials/introductory/lighthouse/tracing-tutorial.png
Labels: area/docs, rn/documentation

#15716 MLflow 3 breaking changes list
  docs/docs/mlflow-3/breaking-changes.mdx
  docs/docs/mlflow-3/index.mdx
Labels: area/docs, rn/documentation

#15798 Fix test failures in click 8.2
  mlflow/cli.py
  tests/test_cli.py
Labels: rn/none, team-review
